### ISSUE TITLE
Install via npm and yarn fails

### ISSUE THREAD

**Issue by samayo** [segmentio/nightmare#1007]
I have CentOs7 running in Windows 10 via Virtualbox, and trying to install nightmare is giving me this error. 

```
 [root@simon node]# npm install -g nightmare
/usr/local/lib/node_modules/nightmare/node_modules/electron/install.js:46
  throw err
  ^
Error: read ECONNRESET
    at exports._errnoException (util.js:837:11)
    at TLSWrap.onread (net.js:544:26)
npm ERR! Linux 3.10.0-514.6.1.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "nightmare"
npm ERR! node v4.1.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! electron@1.4.15 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@1.4.15 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.npm/_logs/2017-02-20T10_40_46_132Z-debug.log
```

And here is the error log: 
```
[root@simon node]# tail /root/.npm/_logs/2017-02-20T10_40_46_132Z-debug.log
21882 error If you do, this is most likely a problem with the electron package,
21882 error not with npm itself.
21882 error Tell the author that this fails on your system:
21882 error     node install.js
21882 error You can get information on how to open an issue for this project with:
21882 error     npm bugs electron
21882 error Or if that isn't available, you can get their info via:
21882 error     npm owner ls electron
21882 error There is likely additional logging output above.
21883 verbose exit [ 1, true ]
```

I can't tell what the issue issue, as I am new to installing JS libraries from npm/yarn registry

**Comment by jekku** [comment]
I can't get why you have to install it globally, tho. Can you try installing electron globally first, THEN install nightmare globally after - if you're in to the kind of stuff. I feel it's 'kinky' hehe. I just install it on the local folder of the app, always.

**Comment by jekku** [comment]
BTW this also happens to me before when office internet is slow (third world here). Perhaps a problem in the VMs connection bridge to the host, too.

**Comment by jekku** [comment]
Because in nodejs, ECONNRESET most probably means that the npm's end of the request/response cycle abruptly got closed on your local machine. Put simply, a connection problem.

**Comment by samayo** [comment]
So, what is the solution? Install electron separately?

**Comment by jekku** [comment]
Could be. I'm not too sure. But I really think it's between your ISP and npmjs.org

**Comment by samayo** [comment]
It can't be a connection problem as I can download pakckages like vue, bulma, font-awesome in the same way with no issues.

let's just hope someone chimes in

**Comment by casesandberg** [comment]
Are you still having trouble? I am going to close this, but feel free to re-open if its still an issue.
