### ISSUE TITLE
beforeFeature / afterFeature

### ISSUE THREAD

**Issue by nayaramoura** [segmentio/nightmare#1011]
**What are you trying to achieve?**

There are some actions that I need to execute after running all tests in a feature.
I am wondering if we already have something like "beforeFeature / afterFeature".

**What do you get instead?**

I've already analyzed the codeceptjs options _before/after_ and the _beforeSuite/afterSuite_. The first one doesn't work for my case because it executes once for each scenario. The second doesn't have access to the browser.

So, basically, I want a command that behaves like before/after but runs only once at the and of the feature execution.

Talking to codeceptjs' devs, they suggested me the following:

> You can start it manually:
> Consider using beforeSuite with manualStart: true option enabled.
> Then you will need to create a custom method like I.startBrowser():
> 
> ```
> startBrowser() {
>   return this.helpers["WebDriverIO"]._startBrowser()
> }
> ```
> And this should work in beforeSuite context:
> 
> ```
> BeforeSuite((I) => {
>   I.startBrowser();
> });
> ```
> Also add restart: false option, to keep browser up between tests.

**So, the final question:
Is there something like **this.helpers["WebDriverIO"]._startBrowser()** for Nightmare?**

**Details**

CodeceptJS version: 0.4.8
NodeJS Version: 6.2.1
Operating System: IOS
Nightmare version: 2.7.0

**Comment by casesandberg** [comment]
You could utilize a test runner like mocha or jasmine which has built-in before and after hooks. I am going to close this for now but feel free to re-open it with some more details.
