### ISSUE TITLE
Nightmare no work. Error electron?

### ISSUE THREAD

**Issue by StanleyMilligan** [segmentio/nightmare#1013]
OS Centos
node version 4.0.0-pre
nightmarejs latest version

`# DEBUG=nightmare:*,electron:* node --harmony example.js`
`**electron:stderr /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64/node_modules/nightmare/node_modules/electron/dist/electron: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory +0ms**
`

How do I fix this error?

**Comment by rosshinkley** [comment]
It looks like you're missing `libxss`?  It looks like Atom also [had this problem](https://github.com/atom/atom/issues/13176), do any of the solutions there work?

**Comment by flexbrane** [comment]
@StanleyMilligan you need to use `Xvfb`, as explain on:
* https://github.com/segmentio/nightmare/issues/224
* https://github.com/segmentio/nightmare/issues/892
