### ISSUE TITLE
Click in an element until it disapear

### ISSUE THREAD

**Issue by marcelinhov2** [segmentio/nightmare#1015]
Hi, I'm new with Nightmare and I need a help.

I have a feature in my website that load more posts, 5 in 5. I need a way to click the button that load more posts, until it hide from my screen. Everytime that I click, it load more 5 posts. After all posts are loaded, it hide from my screen.

Is it possible to simulate this feature?

Thanks

**Comment by rosshinkley** [comment]
This is _very_ similar to #625.  Modified from that issue slightly, and probably _way_ oversimplified:

```js
var Nightmare = require('nightmare');
var vo = require('vo');
var nightmare = Nightmare({
  show: true
});

var run = function * () {
  yield nightmare.goto('http://example.tld');

  while(yield nightmare.exists("some-button-selector")) {
    yield nightmare.click("some-button-selector");
  }
  //... logic to do something with the posts ...
  yield nightmare.end();
};

vo(run)(function(err) {
  console.dir(err);
  console.log('done');
});
```

Note this carries the same stipulations:  This is _very_ naive, and if you're not careful, could end up causing a hang.
