### ISSUE TITLE
ERR_NETWORK_ACCESS_DENIED

### ISSUE THREAD

**Issue by snraets** [segmentio/nightmare#1016]
I am getting this error the when visiting certain sites like:

http://www.footlocker.com/product/model:236830/sku:S80686/adidas-ultra-boost-womens/
http://www.basspro.com/Lowrance-Hook4-Fishfinder/Chartplotter-with-Nautic-Insight-Pro-and-Cover/product/175348/

**Comment by rosshinkley** [comment]
Hm, can you provide more information?  Is the Nightmare script running on a box behind a firewall or anything else that would prevent network requests?  If not, could you provide a minimum repro script?

**Comment by snraets** [comment]
It's strange.  I can visit the sites using Chrome, or Firefox.

The error is this:

earch failed: { message: 'navigation error',
  code: -138,
  details: 'ERR_NETWORK_ACCESS_DENIED',
  url: 'http://www.footlocker.com/product/model:236830/sku:S80686/adidas-ultra-boost-womens/' }

**Comment by snraets** [comment]
Other sites work.

https://www.bedbathandbeyond.com/store/product/samsonite-reg-aspire-xlite-21-5-inch-spinner-in-black/1060001276?categoryId=12325

**Comment by snraets** [comment]
I think this is our network @ work.  I tried at home and had no problem.  Thanks for responding so quickly.

**Comment by rosshinkley** [comment]
Closing for the moment.  Feel free to reopen/open a new issue if this crops up again.
