### ISSUE TITLE
on mac installation of package struck at     electron@1.4.15 postinstall /Users/jay/node_modules/nightmare/node_modules/electron

### ISSUE THREAD

**Issue by jpca999** [segmentio/nightmare#1017]
for the last 15 + minutes, nothing is updating or changing . 

![image](https://cloud.githubusercontent.com/assets/1026325/23325720/849d795c-fac5-11e6-91e1-d91d7fc1ab91.png)

![image](https://cloud.githubusercontent.com/assets/1026325/23325729/8eb6f102-fac5-11e6-81f2-d85096407d52.png)

**Comment by reinpk** [comment]
i had this same issue on an airplane, worked fine once i was on low-latency ground internet. definitely an electron issue though, not a nightmare issue.

**Comment by jpca999** [comment]
yes it strated working  thx
