### ISSUE TITLE
Nightmare running under Electron and Electron Prebuilt

### ISSUE THREAD

**Issue by entrptaher** [segmentio/nightmare#1018]
By default, Nightmare does not want to use the existing process.

This issue concerns the following issues,
https://github.com/segmentio/nightmare/pull/967
https://github.com/segmentio/nightmare/issues/856
https://github.com/segmentio/nightmare/issues/835

## What is the issue?
If installed in the dist folder to run from an electron app,
Nightmare runs fine under electron upto a certain electron version. 
If different electron path is specified, then runs perfectly.

## Explanation
Host electron can be any version but the guest electron version works only if it's electron prebuilt (ie, 1.2.5).
nightmare version 2.7.0 runs fine from within an electron app.
later versions where electron were used instead of electron prebuilt, does not work at all.

## Screenshot:
 - Nightmare with electron prebuilt works,
![](http://i.imgur.com/rysXOVz.png)

 - And, nightmare with electron does not work. Shows **bad argument**.
![](http://i.imgur.com/aM6GaeR.png)

### Case 1
In later versions, If we specify a different electron path, then nightmare runs fine. Assuming we are running electron using `npm start` command, whereas the start command is `"start": "./node_modules/.bin/electron ."`, 

Works! Even though it's using the same electron package.
```js
 electronPath: require('./node_modules/electron')
```

### Case 2
If we put the nightmare as an app inside a electron resources/app folder, similar behavior can be seen.

Works! 
```js
 electronPath: require('./node_modules/electron')
```

Does not work! 
```
electronPath: require('electron')
```

![](http://i.imgur.com/YJfselm.png)

**Comment by tomsotte** [comment]
Another temporary solution is:
`const electronPath = require('electron').remote.app.getPath('exe');`
Add or remove `remote` if you are using nightmare from the renderer or just from the main process.

**Comment by josephrocca** [comment]
Just confirming that this works great, thanks! Simple example code to make it easy for others to test:

```
  let Nightmare = require('nightmare');
  let nightmare = Nightmare({
    electronPath: require('./node_modules/electron'),
    show: true,
  });

  nightmare
    .goto('https://duckduckgo.com')
    .type('#search_form_input_homepage', 'github nightmare ')
    .click('#search_button_homepage')
    .wait('#zero_click_wrapper .c-info__title a')
    .evaluate(function () {
      return document.querySelector('#zero_click_wrapper .c-info__title a').href;
    })
    .end();
    .then(function (result) {
      console.log(result);
    })
    .catch(function (error) {
      console.error('Search failed:', error);
    });
```

**Comment by Craigtut** [comment]
Has anyone else found any solutions to use nightmare from the renderer that work once **packaged**?

I'm a week into learning electron, so I don't fully understand the packaging processes yet. So far I've been using [the boilerplate](https://github.com/chentsulin/electron-react-boilerplate) that uses [Electron Builder](https://github.com/electron-userland/electron-builder) to package.

**1. Some questions and feedback on solutions above. First I've tried:**

```
const electronPath = require('electron').remote.app.getPath('exe');
```
and this works great until you package everything up. It just ends up opening an identical version of your electron app alongside the first. Chased a couple similar rabbit holes with [Electron Remote](https://github.com/electron-userland/electron-remote) thinking maybe I needed to not be using the renderer for nightmare.

**2. Also tried going back to nightmare 2.7.0 and it works in dev!** 
But again when it's packaged it then gives the error
```
Error: spawn ENOTDIR
    at exports._errnoException (util.js:1022)
    at ChildProcess.spawn (internal/child_process.js:313)
    at Object.exports.spawn (child_process.js:399)
    at Nightmare.queue (/Users/craig/Documents/Code/super-8-desktop/release/mac/Super 8.app/Contents/Resources/app.asar/nod…:108)
```

_I can post the full error call stack if that helps._

**3.Then finally I've tried both **Case 1** and **Case 2** as mentioned in the OP.**
Both never work in dev environment with an error of

```
Electron failed to install correctly, please delete node_modules/electron and try installing again
```

even though I'm positive they have installed correctly.

Any thoughts or help? Has anyone gotten nightmare to work **inside the renderer once packaged**?

**Comment by entrptaher** [comment]
I've always provided the binary packages and the node_modules folder separately. more onto this at the end of this reply.

# Case: 
Now, for the sake of testing, 
 - used the same code(from https://github.com/segmentio/nightmare/issues/835) on the boilarplate.
 - used proper relative path to electron folder.
 - used `DEBUG=nightmare*` to find what's going on.
Works fine. 
![screenshot_2017-05-22_01-32-34](https://cloud.githubusercontent.com/assets/8284972/26287051/ae64a40a-3e94-11e7-8c88-aa5ebb72f91e.png)

# Case:
 - read that the boilerplate uses two package.json files. This comment has a good short explanation regarding the situation. https://github.com/electron-userland/electron-builder/issues/912#issuecomment-260644200
I know I can use the electron from either node_modules folder. Both worked.
![screenshot_2017-05-22_01-42-30](https://cloud.githubusercontent.com/assets/8284972/26287050/aa570fba-3e94-11e7-97cd-0e68e05b406f.png)


# Case:
 - tried to package the electron from within App folder, got the error,
```
Package "electron" is only allowed in "devDependencies".
```
Now that's something related to electron_builder.

**Comment by Craigtut** [comment]
Thanks for testing it out. I'm still not having any luck packaging though. Were you able to get any of these solutions to package and still work? Can you expand or link to more of what you mean by "provided the binary packages and the node_modules folder separately"?

I think I found why the two suggestions in the OP, Case 1 and Case 2 aren't working for me.
```
electronPath: require('./node_modules/electron')
```
always returned an error that electron wasn't installed correctly. Using webpack (which is used on the [boilerplate](https://github.com/chentsulin/electron-react-boilerplate)), it seems to try and reference 'path.txt' and the binary by relative path rather than absolute. This then throws all sorts of errors.

How did you get the above to work when you tried with the boilerplate?

**Comment by entrptaher** [comment]
I provided screenshots that I provided the node_modules folder seperately.
The case is more likely related to electron builder than nightmare.

**Comment by KamesCG** [comment]
An issue has been submitted the the electron-builder issues queue

[](https://github.com/electron-userland/electron-builder/issues/1776)

**Comment by casesandberg** [comment]
Solution at https://github.com/electron-userland/electron-builder/issues/1776, closing this as resolved.

**Comment by entrptaher** [comment]
@casesandberg, For past few hours/days, I can see you are closing lots of issues which is great and I was following what you were doing. 

But I think you are missing the context on several issues. Such as this one, it was not about electron-builder, you cannot just read last reply and close the issue as resolved. The original issue is still not resolved.

An issue #856, which was created before #1018 cannot be duplicate of #1018 which was created later. 

Anyway, the issue still persists, there is no normal way to run a nightmare inside electron, unless you use a simple fix/workaround to this problem which I've been mentioning all the time. If you think the workaround is the final solution, then better include such thing in the docs since many people had problem with this.

**Comment by TimNZ** [comment]
Started worked on implementing support for using current electron process right now.
Does not address the above issues around using the parent Electron executable.

Refer #1236

**Comment by crcms** [comment]
@Craigtut Hi，I am using nightmare, and the package has encountered the same problem, but used in the `dev` state
`require('../../node_modules/electron')` Is normal, as shown below, when `build` will appear the following problem
![qq 20180319125356](https://user-images.githubusercontent.com/22486914/37578583-d7e7f052-2b74-11e8-83e1-be962b4ad848.png)[]
I use (https://github.com/SimulatedGREG/electron-vue) electron-vue，Internally called nightmare
Did you solve it? I am very anxious how to solve this problem, thank you

**Comment by entrptaher** [comment]
@crcms somehow I feel it's due to the directory. Like it says it's in dist folder. Maybe a relative path issue?

**Comment by ChaoLiou** [comment]
Hi, im using nightmare too. In my situation, it works well on _npm start_ but run the exe after packaging, it keeps opening new browser window and no crawling website.
i think it is about the electronPath, im using this config in renderer.js:
const nightmare = Nightmare({ show: false, electronPath: require('electron').remote.app.getPath('exe') });

https://github.com/ChaoLiou/PttRealTime

**Comment by jacky-ttt** [comment]
@ChaoLiou I am facing the same situation. I am using `nightmare` in an electron app and `electron-forge` for boilerplate. Nightmare works in dev, but not after packaged. However, I have successfully made the whole thing work by using `electronPath: require('../../node_modules/nightmare/node_modules/electron'),` in both dev and prod. 
Hope this can help.

**Comment by ChaoLiou** [comment]
@jacky-ttt
hey! thanks for your reply first!
I try to copy `/node_modules/electron` to `/node_modules/nightmare/node_modules/electron`,
and do `require('../../node_modules/nightmare/node_modules/electron')`
The error said " cannot find module '../../node_modules/nightmare/node_modules/electron' "
Did I do wrong something?
Another question: Is your situation first time in prod like that the browser keeps opening new window? or just the error occurs?

**Comment by jacky-ttt** [comment]
@ChaoLiou Sorry for late reply. 

There is no need for copy `/node_modules/electron` to `/node_modules/nightmare/node_modules/electron` And the reason why there is a module not found error is that the electron path should be relative to where you are calling it. In the project linked below, I am using `../node_modules/nightmare/node_modules/electron`. That is the location where I can find the electron module. 

Also, my situation is that it shows that nightmare module is not found, but not browser keeps opening new window. 

I uploaded a workable project. Hope this can help to clarify things. 
https://github.com/jacky-ttt/nightmare-in-electron-app
Please read the README.md for instructions to run the project.
