### ISSUE TITLE
PDF buffer error : path must be a string or Buffer

### ISSUE THREAD

**Issue by jfmmm** [segmentio/nightmare#1019]
I'm trying to send a pdf back as a buffer throught an express route, but I get an error and I'm pretty sure I'm doing this correctly.

here my code:

```Javascript
  nightmare
    .goto('http://www.pdfreactor.com/product/samples/invoice/invoice.html')
    .wait()
    .pdf({
      pageSize: 'A4',
      printBackground: true
    }, function(err, data){
      console.log(err);
      console.log('welp');
      res.contentType("application/pdf");
      res.send(data);
    })
    .end()
    .then(function (result) {
      console.log(result);
    })
    .catch(function (error) {
      console.error('failed:', error);
    });
```

```
I get this error:
TypeError: path must be a string or Buffer
    at TypeError (native)
    at Object.fs.open (fs.js:631:11)
    at Object.fs.writeFile (fs.js:1303:6)
    at /Users/myUsername/myProject/node_modules/nightmare/lib/actions.js:657:15
    at EventEmitter.<anonymous> (/Users/myUsername/myProject/node_modules/nightmare/lib/ipc.js:93:18)
    at EventEmitter.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at ChildProcess.<anonymous> (/Users/myUsername/myProject/node_modules/nightmare/lib/ipc.js:49:10)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[nodemon] app crashed - waiting for file changes before starting...
```

If I look inside actions.js it seem like it should go throught the second condition and set path as undefined and then this should call done() with a buffer instead of calling fs.writeFile and return and error because path is undefined.

Is it an error or am I missing something?

**Comment by jfmmm** [comment]
don't know if it's a premise thing, but there a function in the third parameter. If I log arguments I get three thing even tho I'm only passing 2.

```
{ '0': { pageSize: 'A4', printBackground: true },
  '1': [Function],
  '2': { [Function: f] called: false } }
```

I fixed it for now by passing false as a third parameter so it push that weird function.

```Javascript
    .pdf({
      pageSize: 'A4',
      printBackground: true
    }, function(err, data){
      console.log(err);
      console.log('welp');
      res.contentType("application/pdf");
      res.send(data);
    },
    false)
```
```
{ '0': { pageSize: 'A4', printBackground: true },
  '1': [Function],
  '2': false,
  '3': { [Function: f] called: false } }
```

**Comment by rosshinkley** [comment]
I think the documentation is a little misleading here: the Nightmare `.pdf()` function does not take a callback as the second parameter.  In your initial example, Nightmare is treating the options object you're passing in as the path, and the function you're passing in as the internal `done` callback.  In the second, it's treating the options object correctly, but treating the function as the internal `done` callback.  This will almost certainly hang and not continue.

If you want the PDF as a buffer, try something like the following:

```js
.pdf({
  pageSize: 'A4',
  printBackground: true
})
.then((pdfBuffer) => {
  //use the pdf buffer
})
```

**Comment by jfmmm** [comment]
Make sense, thanks for the help.

I'll close this later after testing it.
