### ISSUE TITLE
screenshot to buffer as jpg

### ISSUE THREAD

**Issue by novoxudonoser** [segmentio/nightmare#1020]
Is there any way to take s screenshot in jpg format returning to buffer? It is possible to specify format in path, but I don't want to save screenshot on disk.

**Comment by jfmmm** [comment]
It say how right in the doc.
https://github.com/segmentio/nightmare#user-content-screenshotpath-clip

**Comment by novoxudonoser** [comment]
> If path is provided, it saves the image to the disk

>> I don't want to save screenshot on disk

**Comment by rosshinkley** [comment]
JPGs are not supported yet, pending #950.

If you want a PNG buffer, don't pass the path paramter.  Something like:

```js
nightmare
  .screenshot()
  .then((buffer) => {
    //buffer is a buffer of the PNG
  })
```

**Comment by jfmmm** [comment]
If path is provided, it saves the image to the disk. **Otherwise it returns a Buffer of the image data.**
