### ISSUE TITLE
Multiple processes: windows open and hang

### ISSUE THREAD

**Issue by louisscruz** [segmentio/nightmare#1021]
First off, I have to thank everyone who has worked on nightmare! Coming from phantom, it's been such a relief and pleasure to use so far.

I'm currently working a project that performs a kind of breadth-first graph traversal to find broken links. I am creating (for now) eight Nightmare instances that make parallel/concurrent requests to perform the traversal. It works very well at the beginning, visiting about 210-220 links per minute. It pretty evenly slows down from there until about 800 links have been traversed. Around 800 links, even though the instances are explicitly created with `show: false`, the processes begin to show (windows pop up), and once the windows pop up, those Nightmare instances seem to be hung.

First, I create workers:

```javascript
const generateWorkers = (number) => {
  const workers = {};
  for (let i = 0; i < number; i += 1) {
    const nightmare = Nightmare({
      show: false,
      pollInterval: 50,
      webPreferences: {
        partition: `persist: logged in`
      }
    });
    workers[i] = nightmare;
  }
  return workers;
}
//...
const workers = generateWorkers(8);
```

Then I define a `login` function:

```javascript
const nightmare = Nightmare({
  show: true,
  pollInterval: 50,
  webPreferences: {
    partition: 'persist: logged in'
  }
});

const login = async () => {
  try {
    return await nightmare
      .goto('https://github.com/login')
      .wait(function () {
        const url = document.URL;
        return url === 'https://github.com/';
      })
      .end()
  } catch(e) {
    console.log(e);
  }
};
```

Then I put it all together:

```javascript
login()
  .then(() => {
    const startTime = new Date();
    const handleWorkers = setInterval(() => {
      if (availableWorkers.length > 0 && linkQueue.length > 0) {
        const freeWorker = availableWorkers.dequeue();
        displayLinkData(startTime, freeWorker);
        const currentLink = linkQueue.dequeue();
        visitAndScrapeLinks(currentLink, freeWorker)
          .then((links) => {
            if (!links) {
              availableWorkers.enqueue(freeWorker);
              return;
            }
            links.forEach((link) => {
              linkQueue.enqueue(link);
            });
            availableWorkers.enqueue(freeWorker);
          })
          .catch(() => {
            availableWorkers.enqueue(freeWorker);
            return;
          });
      }
      if (linkQueue.length > 0 && availableWorkers.length === 8) {
        clearInterval(handleWorkers);
      }
    }, 50);
  });
```

I'm assuming that this is a memory issue. However, I thought that creating the Nightmare instances a single time at the beginning would prevent this kind of issue. Is this issue related to the fact that all of the instances share a single partition? Perhaps the accumulated cookies/local storage becomes too much to handle? If that's the case, is there a better way to handle the initial login and/or partitioning? Would it be helpful to, every so often, call `end()` on the Nightmare instances and create new ones? I'm new to `electron` and`nightmare`, so any help moving forward would be much appreciated!

**Comment by louisscruz** [comment]
I just ran more test. When I use 20 workers, I get significantly further, but the processes all eventually hang. This time I got to this point (in my custom logs):

```
Visited 1409 links.
407 links remaining.
(averaging 128.2 per minute)
(averaging 6.17 seconds per request)
there are currently 0 broken links
there are currently 20 workers
```

Looking at activity monitor, I'm going from about 3gb of used memory to 14gb of used memory by the end (out of my total of 16gb). This seems to confirm that it is indeed a memory issue.

**Comment by jekku** [comment]
@louisscruz I'm just curious - what happens if you use different partitions? In your code, e.g.:

const generateWorkers = (number) => {
  const workers = {};
  for (let i = 0; i < number; i += 1) {
    const nightmare = Nightmare({
      show: false,
      pollInterval: 50,
      webPreferences: {
        partition: `persist: ${uuid-v4}`
      }
    });
    workers[i] = nightmare;
  }
  return workers;
}
//...
const workers = generateWorkers(8);
```

Would this consume more memory, or will it actually cause some speed up due to a separation of shared storages?

**Comment by louisscruz** [comment]
@jekku When the partition name doesn't match the partition name of the initial login instance it can't proceed.

**Comment by louisscruz** [comment]
This might be a different kind of issue. Here's an update:

I've completely refactored my code and simultaneously set it so that the workers `end()` after a certain number of requests and are replaced by new instances. I figured that this would help out if there were some kind of a memory issue. However, it definitely didn't. Even when it is the case that there are fewer links and/or the ordering of the traversal changes, I can't make it through the traversal. It tends to hang around this point:

```
60 links remaining.
(averaging 138.39 links per minute)
(averaging 4.96 seconds per request)
there are currently 4 broken links
there are currently 24 workers
Visited 499 links.
```

The last time I ran it, it appeared that when the windows pop up, there are some dialogues for selecting a download location for zip files. Some of the links that are traversed are apparently links for zip downloads. Is there any way to configure Nightmare to ignore these sorts of URLs? Or is that something that has to be done manually in my algorithm? I'd really like to test this out...

By the way, I haven't even had a chance to really optimize my crawler yet, but I'm getting about 280 - 300 link traversals per minute without distribution. Nightmare is fast!

**Comment by LeMoussel** [comment]
I am very interested in your crawler with Electron/Nightmare . Do you share your code?

**Comment by rosshinkley** [comment]
I haven't had a chance to dig into load testing Nightmare recently, and now you have me curious.  I'll see if I can carve out some time to tinker with this at some point soon.  I suspect you're _probably_ right, that this is a memory issue, but I haven't seen Nightmare start popping up windows unless they're generated from the site, and even then, I can't remember exactly the last time I saw that behavior.

I'd be curious if you set up something like [`nightmare-crash-reporter`](https://github.com/rosshinkley/nightmare-crash-reporter) if that might yield any useful information.  (I kind of doubt it, but hey, can't hurt to look.)

>  Some of the links that are traversed are apparently links for zip downloads. Is there any way to configure Nightmare to ignore these sorts of URLs?

If it would help, [`nightmare-download-manager`](https://github.com/rosshinkley/nightmare-download-manager) has an `ignoreDownloads` option that might help you skirt downloads specifically.  Is that what you're after?

**Comment by louisscruz** [comment]
@LeMoussel Here's my project: https://github.com/louisscruz/hub-crawl

**Comment by louisscruz** [comment]
@rosshinkley Thanks for that! I'll give that a shot later today.

**Comment by louisscruz** [comment]
@rosshinkley Wow, your `nightmare-download-manager` did it! It no longer hangs with the `ignoreDownloads: true`.

There is still a drastic slowdown in performance throughout my crawler's run. With 24 workers, my last run, which was about 10 minutes long, started around 240 links per minute and ended at 110 links per minute. I'm curious how the shared session/partition affects this.

Anyways, my original issue is cleared up. I hope this helps someone else!
