### ISSUE TITLE
The type definition is older

### ISSUE THREAD

**Issue by CatsMiaow** [segmentio/nightmare#1022]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/nightmare/index.d.ts

Who, Update, Help!

**Comment by stephenmathieson** [comment]
This seems like an issue you should open with the `DefinitelyTyped` project, as we don't have any control over their typedefs.

**Comment by rosshinkley** [comment]
Closing as this is a `DefinitelyTyped` issue.
