### ISSUE TITLE
Webpack issue with ipc

### ISSUE THREAD

**Issue by tgemes** [segmentio/nightmare#1023]
Just ran into this today. Would be interested in providing a solution if I could get some guidance from the dev team on where to look for a root cause.

My issue is that after compiling my code with webpack nightmare.exists, nightmare.wait, nightmare.evaluate etc just hangs with no timeout. I guess something must be clashing in the way ipc is handled in webpack and in nightmare.js, because I can trace the events with the javascript function inside all the way to IPC emit, but nothing happens afterwards. Nightmare.goto works since it requires no javascript to run in the page context.

I added a console.log to ipc.js to be able to see what are the latest events happening.
```
  process.on('message', function(data) {
    console.log(data);
    emit.apply(emitter, sliced(data));
  });
```

This is the code I ran:
```
yield nightmare.goto(config.pageURL).wait();
var found = yield nightmare.exists(config.button);
```
The last line is never executed so I never know if the button was found. If I run this without webpack, it works though.

These are the last messages logged:
```
[ 'continue' ]
[ 'continue' ]
[ 'continue' ]
[ 'javascript',
  '(function javascript () {\n  var ipc = __nightmare.ipc;\n  try {\n    var response = (function (selector) {\n    return (document.querySelector(selector)!==null);\n  })(null)\n    ipc.send(\'response\', response);\n  } catch (e) {\n    ipc.send(\'error\', e.message);\n  }\n})()' ]
[ 'javascript',
  '(function javascript () {\n  var ipc = __nightmare.ipc;\n  try {\n    var response = (function (selector) {\n    return (document.querySelector(selector)!==null);\n  })(null)\n    ipc.send(\'response\', response);\n  } catch (e) {\n    ipc.send(\'error\', e.message);\n  }\n})()' ]
```

My nightmare app is compiled using target:electron in webpack since I'm using electron to run nightmare anyway. This works fine, there are no issues starting the app, only on nightmare.exists, wait, evaluate etc as mentioned above.

Any help is appreciated on how I could troubleshoot this further.

From my package json:
```
"scripts": {
    "start": "webpack && electron build.js"
  },
```

This is my webpack config:
```
'use strict';
const
    webpack = require('webpack'),
    loader = __dirname + '/webpack.loader',
    path = require('path');
const APP_PATH = path.join(__dirname);
const APP_SRC_PATH = path.join(APP_PATH);
const PKG = require(path.join(APP_PATH, 'package.json'));
const MODULES = PKG.dependencies;
const EXCLUDED_SRC = /(__tests__|node_modules)/;

module.exports = {
    cache: false,
    context: APP_PATH,
    entry: [
        path.join(APP_PATH, 'main.js')
    ],
    target: 'electron',
    output: {
        path: APP_PATH,
        pathinfo: true,
        filename: 'build.js'
    },
    node: {
        global: true,
        __dirname: true,
        __filename: true
    },
    module: {
        loaders: [
            {
                test: /\.js$/,
                exclude: EXCLUDED_SRC,
                include: [
                    APP_SRC_PATH
                ],
                loader: loader
            }
        ]
    },
    externals: [
        function (context, request, callback) {
            let moduleName = request.split('/')[0];
            let moduleParam = MODULES[moduleName] || false;
            if (moduleParam) {
                return callback(null, 'commonjs2 ' + request);
            }
            callback();
        }
    ],
    plugins: [
        new webpack.IgnorePlugin(/\.(css|html|json|md|txt)$/)
    ]
};
```

And a super simple webpack.loader.js:
```
'use strict';
module.exports = function (source) {
    return source;
};
```

**Comment by KamesCG** [comment]
Did you manage to find a solution?

I'm attempting to integrate Nightmare into 'electron-react-boilerplate' and running across dependencies issues with Webpack too.

**Comment by casesandberg** [comment]
You have to end all call with `.done()` otherwise electron will hang. I am going to close this, but feel free to open a new issue if you can't get it work.
