### ISSUE TITLE
window.open authentication not inherited from nightmare instance

### ISSUE THREAD

**Issue by zerg000000** [segmentio/nightmare#1024]
The window opened by parent webpage are not inherited the proxy and authentication settings the parent has, so 401 is shown.

        nightmare
	      .authentication(username, password)
	      .goto(url + '/Login.aspx')
		  .click('#MenuReport')
		  .click('#MenuMain_lbRpt')
		  .wait(2000)
		  .type('#ucDateFrom_txtDate','01-08-2016')
		  .type('#ucDateTo_txtDate','31-08-2016')
		  .click('#btnGenerate')
          .catch(done)

The popup has return 401.

**Comment by rosshinkley** [comment]
Popups are not directly supported by Nightmare, and while I am certain the `preload` script doesn't get inherited with popup windows, I would not be surprised if other settings such as proxy are also not inherited.
