### ISSUE TITLE
Site-specific memory leak?

### ISSUE THREAD

**Issue by micahsmith** [segmentio/nightmare#1026]
I'm working on an app that automates logins. I've noticed that when nightmare/electron navigates to Zapier, https://zapier.com/app/login, the renderer process continues to increase its memory use, even when there is no navigation, and the process should be idling.

Nightmare v2.9.1. I've run it both with the prebuilt electron binary and manually setting the electronPath to a new version, but the issue persists.

I don't know whether this is a Nightmare issue or an Electron issue, so I'd be interested to hear whether anyone can provide some insight into it, and whether it can be replicated.

**Comment by rosshinkley** [comment]
I've had similar issues with Chromium (and Chrome for that matter) bleeding memory.  Slack and Gmail have traditionally been my go-to examples of this - leave them open for any extended period of time, and eventually the browser process will gobble up all of the available memory.  I haven't had a real chance to dig into if it's a Chromium bug or a product bug, but I suspect Zapier may have a similar problem.

**Comment by micahsmith** [comment]
The same issue doesn't seem to happen in Chrome. I should also note that the bleed is quite fast: the usage seems to grow ~100M every few seconds. Is there any good workaround for this issue, or is it just the case that some sites are going to suck?

I mean, worst case scenario, I can arrange to kill any electron processes that get to memory hungry, but I would prefer something more elegant.

Thanks for the quick response, by the way. I really appreciate all the work you've done on this project!

**Comment by rosshinkley** [comment]
>The same issue doesn't seem to happen in Chrome. 

Mmm, that's troubling.

>I should also note that the bleed is quite fast: the usage seems to grow ~100M every few seconds.

That's even more troubling.  When I've seen memory leaks, I'm talking on the order of megabytes an hour (if that), not an instant gobble.  My knee-jerk would be to say "try Electron's latest," but you've already tried that.

A quick gander through Electron's issues yielded electron/electron#8051 and electron/electron#7350 which seem close-ish?  Are either of those close to your case?

Also, is a minimum repro case possible?  I'm a glutton for punishment and would like to see this myself.

>Thanks for the quick response, by the way.

No problem.  Trying to get better about it, so far so good.

>I really appreciate all the work you've done on this project!

D'aw.  I can't take hardly any credit, but thank you anyway.

**Comment by micahsmith** [comment]
I take it that you haven't been able to replicate, and after having tried to replicate it for several days in a row without success, I'm about to give up.

My inclination at this point is to let Nightmare/Electron run every once in a while, and periodically check to see if the leak reoccurs. I would welcome any thoughts on best methods to log and debug any leaks in the future.

**Comment by micahsmith** [comment]
Haven't been able to reproduce. I'm going to go ahead and close this.

**Comment by rosslavery** [comment]
Just found this issue and wanted to mention that I'm encountering something very similar myself right now. Easily reproducible too. Seems to happen whenever I run an `evaluate` on a specific website (Google AdWords).

Memory skyrockets by 100mb every second or so to infinity until I kill the process.

Doesn't happen in Chrome-regular.
