### ISSUE TITLE
Remove internal queue and have actions return promises

### ISSUE THREAD

**Issue by matthewmueller** [segmentio/nightmare#1028]
Now that node natively supports async/await (!) we can probably remove the internal queueing system and just have the actions return promises.

This would definitely be a breaking change but *should* allow for more concurrency, so you could do things like this:

```js
async function main () {
  const page = await nightmare.goto("https://google.com")
  const screens = [ ... ] 
  const screenshots = await Promise.all(screens.map(function (s) {
     return page.viewport(s.width, s.height).screenshot(s.output)
  })
}

main()
  .then(console.log)
  .catch(console.error)
```

**Comment by rosshinkley** [comment]
This would introduce an awful lot of lifting that the internal queue currently takes care of - two things that come to mind off the top of my head.  One, starting Electron is a queued action, meaning the instance does not start Electron until the first action is called as a part of the queue, and we get that for (more or less) free.  Wouldn't your approach mean all functions would have to check that?  Two, custom action creation is injected as a part of the queue after the Electron instance is started and the browser window sugar is propped up but before any of the user-queued actions are executed.  How would that work?

**Comment by casesandberg** [comment]
It doesn't look like there has been any progress on this issue lately. I am going to go ahead and close it, but feel free to open it back up if anyone wants to take a stab at a PR.
