### ISSUE TITLE
Electron dependency on libX11-xcb

### ISSUE THREAD

**Issue by adityabansod** [segmentio/nightmare#1030]
Not quite an issue per se, but this popped up in my headless env that I had to make accommodations for when rebuilding my docker images tonight.

I started to get hangs complaining with `DEBUG=nightmare` that `127: command not found - you may not have electron installed correctly`.

Further digging with `DEBUG=*` revealed electron was trying to load `libX11-xcb`, so I had to manually add that to my Dockerfile's `apt-get install` list.

**Comment by casesandberg** [comment]
Ah, great digging! I am going to close this, but it will be here for anyone else that searches for it.
