### ISSUE TITLE
wait for dynamic added element

### ISSUE THREAD

**Issue by novoxudonoser** [segmentio/nightmare#1031]
I have a code:
```
await n.wait((s) => { return (document.querySelector(s) ? true : false) },s1);
```
The element with selector `s1` is not present on the page when the `wait` is called, the `fn` each time it polls returns `false`. Then, when the element with `s1` selector added, `fn` returns `true` and poll for `fn` stops, but after that the `wait` fails with timeout. I expected that after `fn` return `true` the `wait` will continue successfully. Same with `wait(s1)`.

**Comment by rosshinkley** [comment]
That's how it should work, and I cannot recreate the behavior you're seeing.  Can you provide a minimum repro?

**Comment by casesandberg** [comment]
Can you provide some more information or a way to reproduce? I am going to close this for now but feel free to open a new issue with some more details.
