### ISSUE TITLE
screenshot working in local node repl, not working in node repl in docker 

### ISSUE THREAD

**Issue by clement360** [segmentio/nightmare#1032]
I'm trying to capture screenshots for multiple pages from a node container. to test it out I have been running this code:

```
var Nightmare = require('nightmare');

var google = new Nightmare().goto('https://www.webcomponents.org/element/GoogleWebComponents/google-map').wait(10000).screenshot('/public/screenshots/maps.png').run(function(err, nightmare) { console.log('DONE')});
```

it works perfectly on my local machine. in docker I don't even get an error. it does nothing. I'm running on the official node:6.3.0 image. could this be some type of networking issue?

**Comment by mstraughan86** [comment]
The resolution to the screenshot issue in docker instance is found here: [https://github.com/segmentio/nightmare/issues/224#issuecomment-267195843](https://github.com/segmentio/nightmare/issues/224#issuecomment-267195843)
