### ISSUE TITLE
Infinite installing

### ISSUE THREAD

**Issue by rico345100** [segmentio/nightmare#1034]
When I type "npm install nightmare", installation is stuck like this and never proceed:

```bash
rico345100ui-MacBook-Pro:jasmine rico345100$ npm install --save-dev nightmare
(node:21564) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

> electron@1.6.1 postinstall /Users/rico345100/Desktop/learn/jasmine/node_modules/electron
> node install.js
```

I almost wait 20 minutes, but nothing changed. I removed whole node_module and retried, but still same.

I'm using
- node v6.9.2
- npm v3.10.9

**Comment by rico345100** [comment]
Nah, it just working now. Looks like kind of some network issue.

**Comment by rico345100** [comment]
Sorry, I just re-run the install, same issues happens again. When I forcely stop install and re-install, it saids:

> Electron failed to install correctly, please delete node_modules/electron and try installing again

So remove node_modules and npm install, same problem continues.

Oh, I forgot to mention it, I'm using MacOS 10.11.3 El Capitan.

**Comment by entrptaher** [comment]
Can you try the following code and see when it's getting stuck?
 - `npm install --verbose --save nightmare`

Also, you can try other package managers/wrappers like `yarn` 
and run either of the following commands, 
 - `yarn add nightmare`
 - `yarn add --verbose nightmare`

You don't have to share the whole log directly, you can see where it gets stuck and tell us.

**Comment by dks-ait** [comment]
Hitting the same issue
Node : v8.1.0
Npm : v5.0.3

 I am on MacOS Sierra(10.12.5)

Will try the verbose one and revert back with results.

**Comment by dks-ait** [comment]
Verbose shows the issue -

`> electron@1.6.11 postinstall /Users/devesh/Documents/Projects/TrNmare/node_modules/electron
> node install.js

Downloading electron-v1.6.11-darwin-x64.zip
[>                                            ] 2.3% of 46.08 MB (29.36 kB/s)`

It the download that is taking huge time. I am on a decent internet but still the download speeds are less. I think the location its downloading from is throttling the speed.

**Comment by dks-ait** [comment]
The download gets stuck after some time :(

Not moving beyond this point now (this is the 3rd time it has got stuck while downloading, last time it downloaded 44% and got stuck :()
```
Downloading electron-v1.6.11-darwin-x64.zip
[====>                                        ] 12.2% of 46.08 MB (19.84 kB/s)

```

**Comment by entrptaher** [comment]
The speed depends on Amazon s3 where the contents of repos are saved. I
tried paid VPNs and proxies, the speed changes depending on where you/your
proxy live.

**Comment by casesandberg** [comment]
Are you still having trouble and have you tried 2.10.0? I am going to close this, but feel free to open a new issue if you are still having problems.

**Comment by dks-ait** [comment]
I got around the problem, by downloading electron from its site manually and then letting nightmare use the same.
 
I havent tried the nightmare 2.10.0 yet.
