### ISSUE TITLE
Is it possible to debug code inside evaluate()

### ISSUE THREAD

**Issue by iwxfer** [segmentio/nightmare#1041]
I have complex code inside evaluate, console.log is not useful inside evaluate.

**Comment by entrptaher** [comment]
Maybe something like this might be helpful. Maybe there is something we still have to explore. Maybe it's there but just not documented. :)

![2017-03-15 15_44_47](https://cloud.githubusercontent.com/assets/8284972/23942403/63aa83c2-0996-11e7-882b-f9b580f6e538.png)

Then Each time I update the runMe file, it get's executed on that page in isolation. 

![2017-03-15 15_44_56-example domain](https://cloud.githubusercontent.com/assets/8284972/23942431/7cd31d28-0996-11e7-9a82-597e6ece6d5e.png)

**Comment by daninfpj** [comment]
There's an [openDevTools] option(https://github.com/segmentio/nightmare#opendevtools)

This link should be helpful if you need more info: http://christopherdecoster.com/posts/nightmare/

**Comment by casesandberg** [comment]
Looks like this is resolved. I am going to close this for now but feel free to open a new issue if you are still having problems.
