### ISSUE TITLE
Cannot load a custom preload script

### ISSUE THREAD

**Issue by nquoctuan** [segmentio/nightmare#1042]
hi guys, the issue is about creating a custom preload script to hook alert message or confirm dialog from browser.
main.js :
```
var Nightmare = require('nightmare'),
  nightmare = Nightmare({
    openDevTools: {
      mode:'detach'
    },
  show: true,
  webPreferences: {
        devTools: true,
        preload: 'alertMessage.js',
        nodeIntegration: false,
        webSecurity: false,
        allowRunningInsecureContent: true
      }
});
  
nightmare.useragent('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3015.0 Safari/537.36');

nightmare.goto('http://www.google.com')
  .then(function() {
	return nightmare.url();  
  })
  .then(u => {
	  console.log('The url is: ' + u);
  });

```

alertMessage.js (not do anything yet):
```
window.__nightmare = {};
__nightmare.ipc = require('electron').ipcRenderer;
```

However, i got an error like:
```
Uncaught TypeError: Cannot read property 'nightmare' of undefined
  javascript @ VM106:3
  (anonymous function) @ VM106:38
  electron.ipcRenderer.on @ init.js:51
  emitMany @ events.js:127
  emit @ events.js:201
```

Any ideas, I am appreciated.
Thanks,

**Comment by entrptaher** [comment]
Use `path` module to solve your issue. The reason is your preload script is not getting proper paths while running in the browser unless specified.

```js
var Nightmare = require('nightmare'),
    path = require('path'), // ADD THIS
    nightmare = Nightmare({
        show: true,
        webPreferences: {
            preload: path.resolve('preload.js') // USE PATH.RESOLVE FUNCTION
        }
    });
```

**Comment by nquoctuan** [comment]
hi  @entrptaher,

Thanks for your reply. Actually, the source code is to simplify the path. The thing is the script is able to load but get some issue with 'nightmare' which is inside the ```alertMessage.js```

Any other idea, thanks.

**Comment by entrptaher** [comment]
Well, I just gave you the idea. Simplify the path and it'll load without errors.

**Comment by johnferro** [comment]
I'm going to second @entrptaher's solution.  The preload option gets passed as an option to the initialization of electron's browser window.  As documented [here](https://github.com/electron/electron/blob/master/docs/api/browser-window.md#new-browserwindowoptions): "The value should be the absolute file path to the script."  While it may appear that the script is loading properly because the error is showing up in the electron console, no script is getting loaded which breaks nightmare since it is requiring those two lines of preload script.

**Comment by rosshinkley** [comment]
Closing this as it seems resolved.

**Comment by iki** [comment]
@nquoctuan I just run into the same issue. The passed preload script replaces [Nightmare preload script](https://github.com/segmentio/nightmare/blob/master/lib/preload.js), so just load it from top of your preload script. That works for me.
```
require('nightmare/lib/preload')
```
