### ISSUE TITLE
.pdf() zoomed-in

### ISSUE THREAD

**Issue by iget-esoares** [segmentio/nightmare#1046]
Hi,

I'm trying to save a page as PDF, everything works fine except for the size: even choosing A4 size, my output pdf looks like zoomed-in.

```
nightmare
    .goto(url)
    .wait()
    .pdf(output, {
        pageSize: 'A4',
    })
    .end()
    .then(function (result) {
        console.log('PDF File Generated successfully.');
    })
    .catch(function (error) {
        console.error('Search failed:', error);
    });
```

When I print the same example on Chrome, it scale is fine.
I'm pretty sure that I've seen a issue of this, but cannot found anymore!

**Comment by rosshinkley** [comment]
Can you provide a sample page where you see this issue?

**Comment by casesandberg** [comment]
Are you still having trouble? I am going to close this, but feel free to open a new issue if its still a problem.
