### ISSUE TITLE
Is it possible to drag and drop using nightmare?

### ISSUE THREAD

**Issue by simonweil** [segmentio/nightmare#1047]
And thank you for a great project!

**Comment by brotzky** [comment]
I've trying to do the same thing. I'm using a dropzone and can't seem to get images to upload. I've tried using nightmare-upload but that has failed as well.

**Comment by ZhengHe-MD** [comment]
same thing here.

**Comment by honglish** [comment]
I am curious about this too!

**Comment by casesandberg** [comment]
It currently isnt possible, sorry.
