### ISSUE TITLE
Proper usage of wait("selector"). How to run code immadiately after loading element?

### ISSUE THREAD

**Issue by piotrek-k** [segmentio/nightmare#1050]
There is a website, where I want to type credentials using `nightmare`, log in and then click a button.

```javascript
var Nightmare = require('nightmare');
var nightmare = Nightmare({ show: true })

nightmare
    .goto('https://www.packtpub.com/packt/offers/free-learning')
    .wait('#account-bar-login-register > a.login-popup')
    .click("#account-bar-login-register > a.login-popup")
    .type("#email", "some_email")
    .type("#password", "some_password")
    .click("form [type=submit]")
    //.wait(2000)
    .wait("#deal-of-the-day > div > div > div.dotd-main-book-summary.float-left > div.dotd-main-book-form.cf > div.float-left.free-ebook > a")
    .click("#deal-of-the-day > div > div > div.dotd-main-book-summary.float-left > div.dotd-main-book-form.cf > div.float-left.free-ebook > a")
    .evaluate(function () {
        document.querySelector("#deal-of-the-day > div > div > div.dotd-main-book-summary.float-left > div.dotd-main-book-form.cf > div.float-left.free-ebook > a").click();
    });
```

The problem is: button that should be clicked at the end (`#deal-of-the-day > div > div > div.dotd-main-book-summary.float-left > div.dotd-main-book-form.cf > div.float-left.free-ebook > a`) is not being clicked. It's probably because page needs some time to load. That's why I used this line:
```javascript
.wait("#deal-of-the-day > div > div > div.dotd-main-book-summary.float-left > div.dotd-main-book-form.cf > div.float-left.free-ebook > a")
```
To wait until it loads. But it doesn't work. If I use
```javascript
.wait(2000)
```
it works properly, but this solution doesn't satisfy me. The page doesn't have to load within two seconds and sometimes it might take more.

Am I using this method wrong way? How can I run code immadiately after page load?

**Comment by sbacic** [comment]
I had this very same problem and what helped me was setting `pollInterval` to `50` in the nightmare config. I'm not sure if this is a bug or some weird timing issue but it should definitely be fixed or at the very least clarified.

**Comment by ippa** [comment]
I've only played with nightmare for a very short while, but I got the impression `click(selector)` will automatically wait for that selector to be available (I assumed with the same global timeout-value as wait() has). Seems verbose to have to place an identical `wait(selector_a)` before each and every `click(selector_a)`

**Comment by sbacic** [comment]
I'm sure about your exact problem but wait(selector) or wait(fn) was not working properly for me until I adjusted the pollInterval. I'm reasonably sure that you don't have to call wait() before click() unless the click() selector is loaded dynamically.

**Comment by sbacic** [comment]
To add to my original post - I've gone over the tests and found this little gem:
https://github.com/segmentio/nightmare/blob/master/test/index.js#L341

Apparently, wait can be made more reliable by adding a longer softTimeout value (I've been using 1000ms) as the second argument, eg: wait('a', 1000). Not sure why this isn't mentioned in the documentation.

**Comment by chtrinh** [comment]
@sbacic: good find, didn't know about that option

**Comment by zhoutiannan1995** [comment]
It seems that the button already exists, but not on focus. You can use DEBUG=nightmare:actions* to see how long does the wait() take. I think that it's 0ms

**Comment by casesandberg** [comment]
Looks like this is resolved. I am going to close this for now but feel free to open a new issue if you are still having problems.

**Comment by idchlife** [comment]
@sbacic exactly what I was looking for! Thanks!

**Comment by jmmitchell** [comment]
I am just adding my 2 cents that I have never had wait('selector') work until I changed the `pollInterval ` value to 50 as sbacic detailed above. This indicates there is still an issue that default pollInterval of 250 is not sufficient or there is a bug.
