### ISSUE TITLE
How can I make requests to site through network interface IP?

### ISSUE THREAD

**Issue by privilio** [segmentio/nightmare#1051]
Hi.

I have several network interfaces with various IP addresses. How can I make requests to site through these IPs?

I can easily make request through proxy:
```javascript
var nightmare = Nightmare({
  show: true,
  switches: {
    'proxy-server': '1.2.3.4:5678',
    'ignore-certificate-errors': true
  }
});

nightmare
  .goto('https://api.ipify.org/?format=text')
  .wait(3000)
  .evaluate(function () {
    return document.body.innerText;
  })
  .end()
  .then(function (result) {
    console.log(result);
  })
  .catch(function (error) {
    console.error('Search failed:', error);
  });
```

But how can I do this with the network interface IP that I need?

**Comment by casesandberg** [comment]
Are you still having trouble? I am going to close this, but feel free to open a new issue if its still a problem.
