### ISSUE TITLE
Manipulating CSS resources

### ISSUE THREAD

**Issue by adamdyson** [segmentio/nightmare#1053]
Is it possible for Nightmare (or by any other means E.g. JavaScript) to manipulate (inline or external) CSS styles, either before or after loading a web page?

Below is an example of what I'm looking to achieve. If a CSS rule contains the `custom-property` I'd like to duplicate or alter the property name to become `new-property`.

```
.some-class-name
{
    custom-property: rgba(0, 0, 255, 0.3);
}
```

```
.some-class-name
{
    new-property: rgba(0, 0, 255, 0.3);
}
```

**Comment by rosshinkley** [comment]
The short answer is yes - you could certainly use `.evaluate()` and use `document.querySelector()` to get the DOM element, then you have the entirety of CSS to play with.  Off the cuff:

```js
.evaluate(() => {
  var element = document.querySelector('.some-class-name');
  element['new-property'] = 'new-property-value';
  delete element['custom-property'];
})
```
(What I can't recall off the top of my head is if `delete` will actually delete the inline style.  You might want to have a look at MDN.)

Alternatively, you could also use `.inject()` to pull in, say, jQuery to do the same.

**Comment by adamdyson** [comment]
@rosshinkley thanks for the reply. I ended up making a simple example outside of Nightmare using JavaScript to manipulate the styles loaded in the DOM. The problem I encountered was that custom property names and values (which are not part of the CSS spec) are never loaded in the first place.

I did come up with a hack for property names, that was to prefix them with double hyphens.

**Comment by casesandberg** [comment]
Looks like this is resolved. I am going to close this for now but feel free to open a new issue if you are still having problems.

**Comment by maajja** [comment]
why when i use that suddenly quit from electron??
can somebody explained what happened?? i use electron 9.4.3
