### ISSUE TITLE
Why alwaysOnTop: true, on runner.js?

### ISSUE THREAD

**Issue by quiuquio** [segmentio/nightmare#1055]
In case of show: true, the electron window is always on top.
I checked for related issues and couldn't find anything. Is there a reason to keep it this way?
If no, shouldn't it be 'alwaysOnTop: false' by default, or shouldn't there be a way to deactivate it?

**Comment by rosshinkley** [comment]
See #434 and #452.  It has to do with preventing virtual desktop switching.

You can deactivate `alwaysOnTop: false` by passing it in as an option.  I'd leave the default as `true` there as it does fix a known problem.
