### ISSUE TITLE
.wait(undefined) behaviour

### ISSUE THREAD

**Issue by jakoivis** [segmentio/nightmare#1056]
Would be nice if in this case wait would fail my tests. In my case I moved some code so that the variable in .wait argument became undefined. After that change, tests were passing without actually testing anything any more. So it is easy to render your tests useless with some small mistakes.

**Comment by entrptaher** [comment]
So was waitTimeout were being called when you passed .wait(undefined)?

**Comment by jakoivis** [comment]
I have waitTimeout: 10000. Does it have some affect on this matter? with .wait(undefined) the test does not time out.

**Comment by entrptaher** [comment]
Okay so this is a feature request, right?
Did you ever try something like this?
```js
var Nightmare = require('nightmare');		
var nightmare = Nightmare({ show: true });

nightmare
  .goto('https://example.com')
  .wait(function(){
  	return undefined;
  })
  .title()
  .end()
  .then(function (result) {
    console.log(result);
  })
  .catch(function (error) {
    console.error(error);
  });
```

You can use `.wait(fn)` to parse instead of plain `.wait(selector)`

**Comment by jakoivis** [comment]
Actually I mostly use .wait(fn). It turns out I created a custom wait action since I needed better better error reporting when something fails. I can also handle the undefined checking there myself now.

**Comment by casesandberg** [comment]
Looks like this is resolved. I am going to close this for now but feel free to open a new issue if you are still having problems.
