### ISSUE TITLE
why using nightmare.evaluate in nightmare.use faild

### ISSUE THREAD

**Issue by ShuraChow** [segmentio/nightmare#1058]
```
nightmare
   .goto(anypage)
   .evaluate(function () {
      console.log(1);
   })
   .use(function(callback){
      return function(nightmare) {
         var x = somelib();
         nightmare
            .evaluate(function (x) {
               console.log(x);
            },x)
            .end()
      };})
```

i can get console.log(1) without console.log(x)
if i something wrong?
how can i made this code to running out console.log(x)?
THX!

**Comment by rosshinkley** [comment]
Two questions: one, why are you using `.use()`, and two, what is `x`?

**Comment by ShuraChow** [comment]
my answer:
1. sometimes i need using 3rd lib to processing what i got. (like graphics captcha etc.)
2. x means the process result (it can be understood here as a verification code), then i'll using the 'x' to fill the form.

in this case (captcha and decode), is there any other way?

**Comment by nolka** [comment]
If you open developer tools in electron, i think, you can see "2" in their js console

**Comment by ShuraChow** [comment]
@nolka it's nothing

**Comment by ShuraChow** [comment]
@rosshinkley  am i wrong?

**Comment by casesandberg** [comment]
Your second example works for me. Are you still having trouble and have you tried 2.10.0? I am going to close this, but feel free to open a new issue if you are still having problems.
