### ISSUE TITLE
Can i respond to 'will-download' event?

### ISSUE THREAD

**Issue by lolownia** [segmentio/nightmare#1059]
Hi! 
I'd like to be able to control the "download as" popup to select the filename for a downloaded file. I read that it's possible by listening to 'will-download' event. Is it supported by Nightmare?

**Comment by aight8** [comment]
exactly the same problem.

**Comment by rosshinkley** [comment]
[`nightmare-download-manager`](https://github.com/rosshinkley/nightmare-download-manager) or [`nightmare-inline-download`](https://github.com/rosshinkley/nightmare-inline-download) might help you solve this.

**Comment by overflowz** [comment]
it is possible with libraries provided by @rosshinkley 
also things to consider: those libraries (or nightmare or even electron itself), can't handle new window's created dynamically (like <a target="_blank">).

for now, I'm trying to get the link of the download (if it's possible) and then create iframe on the document with that download link and append to body, which will trigger will-download on the same window.

**Comment by entrptaher** [comment]
@overflowz, While evaluating, You can just replace the every "_blank"  to have the links open in same page.

**Comment by overflowz** [comment]
@entrptaher sometimes it fails to load urls (for example PDF's directly). I don't remember the actual problem, but when I was opening PDF's I was getting errors which I really don't remember.

**Comment by casesandberg** [comment]
Looks like this is resolved. I am going to close this for now but feel free to open a new issue if you are still having problems.
