### ISSUE TITLE
Custom accept-language headers

### ISSUE THREAD

**Issue by pdehaan** [segmentio/nightmare#106]
How do I pass custom accept language headers to Nightmare?
I'm trying to scrape my site X times testing X different locales but need to pass in custom HTTP headers.

**Comment by reinpk** [comment]
unfortunately this doesn't appear to be possible upstream in electron https://github.com/atom/electron/blob/master/docs/api/browser-window.md

but if there is a way i'm missing, happy to re-open and implement
