### ISSUE TITLE
Is .use() correct for set of test cases?

### ISSUE THREAD

**Issue by nolka** [segmentio/nightmare#1062]
Hi!
I want to use .use() method to wrap some test cases in different pieces of code, and glue it together using nightmare's chained calls of .use() method, for example:
```js
/// create nightmare instance...

n
    .use(testcase1)
    .use(testcase2)
    .use(testcaseN)
    .then(()=>{
        done();
    })
    .catch((err) => {
        console.log(err);
     })
``` 

This is correct usage?

**Comment by casesandberg** [comment]
Yep, this would be the right way to do it!
