### ISSUE TITLE
Proxy use

### ISSUE THREAD

**Issue by Mystogan6** [segmentio/nightmare#1064]
SO I'm uising nightmare to generate scenarios of users using a page to get the HTTP-Requests of the page proxy-ed
To do so I'm using http-proxy and setting it like this : 

```javascript
var http = require('http'),
    httpProxy = require('http-proxy');

httpProxy.createProxyServer({target:'http://localhost:9000', auth: 'test:test'}).listen(8000);
http.createServer(function (req, res) {
  res.writeHead(200, { 'Content-Type': 'text/plain' });
  res.write('request successfully proxied!' + '\n' + JSON.stringify(req.headers, true, 2));
  res.end();
}).listen(9000);
```

and then I use nightmare like this : 
```javascript
var nightmare = Nightmare({show: true,
		switches : {
			'proxy-server': 'localhost:9000;',
			'ignore-certificate-errors': true,
		}})
nightmare.authentication('test', 'test')
		.goto('http://localhost:4200/login')
		.type('#name', 'test'+user)
		.type('#pwd', 'test'+user)
		.click('#log')
		.wait('body')
```

but when I launch it, nightmare goes on the proxy (so localhost:9000) and ignores the goto(localhost:4200), can someone help me?

**Comment by casesandberg** [comment]
Are you still having trouble and have you tried 2.10.0? I am going to close this, but feel free to open a new issue if you are still having problems.
