### ISSUE TITLE
Catch all network errors from console (404, insecure content, ...)

### ISSUE THREAD

**Issue by bravecow** [segmentio/nightmare#1065]
How to catch all errors (including network 404) from electron console? I think I should somehow to listen messages from debugger? (I would like same as http://nightwatchjs.org/api#getLog method)

https://electron.atom.io/docs/api/debugger/

Please, cover this case in docs or answer here. Can't make it work though `Nightmare.action`=/

Thanks! <3

**Comment by casesandberg** [comment]
You can find some more information about debugging here: https://github.com/segmentio/nightmare#debugging, but to do what you are looking for you just need to set and env var of `DEBUG=*`
