### ISSUE TITLE
Can you add a page.set('clipRect') method? please

### ISSUE THREAD

**Issue by MakoMakox** [segmentio/nightmare#107]
I tried to add the method myself but i was unsuccessful
.This is the code that I tried to implement in the actions.js file:
exports.viewRect = function(clipRect, done){
  this.page.set('clipRect', clipRect , done);
  console.log(this.page)
};
http://phantomjs.org/api/webpage/property/clip-rect.html as reference .
The object that was passed to the method should look like this:
{
    top: clipRect.top,
    left: clipRect.left,
    width: clipRect.width,
    height: clipRect.height
    };

I'm trying to take a screenshot of a dom element in the page.
I don't know how to access the phantomjs instance so I can add other methods that are available in phantomjs.

**Comment by mickaelandrieu** [comment]
... or just take the CasperJS's one ? Why re-invent the wheel ?
https://github.com/n1k0/casperjs/blob/master/modules/casper.js#L294

**Comment by reinpk** [comment]
ok, added in `2.0.2` support for the `clip` parameter: https://github.com/segmentio/nightmare#screenshotpath-clip
