### ISSUE TITLE
Clicking on an element twice doesn’t register the second click

### ISSUE THREAD

**Issue by mrdanimal** [segmentio/nightmare#1072]
I have the following code:

```
yield nightmare
  .click(“.ThumbUpButton”) // this click works
  .wait(".ThumbUpButton.ThumbUpButton--active");
console.log(‘we get here’);

yield nightmare
  .click(".ThumbUpButton”); // this click never fires
console.log(‘we never get here’)
```

The second click apparently never fires. Is this a bug or is there something that I’m missing?

**Comment by KalibRx** [comment]
I may be wrong, but I believe you're dom changes between re-referencing nightmare. Does it work when you do this?:

```
yield nightmare
  .click(“.ThumbUpButton”) // this click works
  .wait(".ThumbUpButton.ThumbUpButton--active")
  .click(".ThumbUpButton”); // this click never fires
```

**Comment by mrdanimal** [comment]
Sorry, I should have made my example even simpler. Even without any waits or anything, the second click never fires:
```
yield nightmare
  .click(“.ThumbUpButton”) // this click works
  .click(".ThumbUpButton”) // this click doesn't
```

If I put a `wait(100)` between them, then the second `click` does fire. I wonder if it's actually an issue with Chrome, possibly debouncing event.

**Comment by KalibRx** [comment]
Based on your most recent comment it sounds like it's definitely something client-side but I shall take a peek!

**Comment by casesandberg** [comment]
Are you still having trouble? I am going to close this, but feel free to open a new issue if its still a problem.
