### ISSUE TITLE
evaluate_now returns null

### ISSUE THREAD

**Issue by tomgcoleman** [segmentio/nightmare#1073]
I would like to write a custom action which does stuff based on the result of evaluate_now.  Sadly the return value is always null.

I also tried the solution from here, which fails for the same reason.
http://stackoverflow.com/questions/36723849/nightmare-conditional-wait

    var Nightmare = require('nightmare');
    
    Nightmare.action('getResultFromEvaluate', function(done) {
    
        this.evaluate_now(function() {
            return "result_back_from_evaluate_now";
        }, function(result) {
            console.log('value from evaluate_now: <<' + result + '>>');
            done(null, true);
        });
        return this;
    });
    
    var nightmare = Nightmare();
    
    nightmare
        .goto('https://www.google.com')
        .getResultFromEvaluate()
        .evaluate(function() {
            return 'result_back_from_evaluate';
        })
        .end()
        .then(function(sz) {
            console.log(sz)
        });

**Comment by casesandberg** [comment]
You have to call the cb with whatever data you want the evaluate function to return:
```
Nightmare.action('getResultFromEvaluate', function(done) {
    this.evaluate_now(function() {
        done(null, "result_back_from_evaluate_now");
    }, function(result) {
        console.log('value from evaluate_now: <<' + result + '>>');
        done(null, true);
    });
});
```
