### ISSUE TITLE
Iframes only load with webPreferences.show = true

### ISSUE THREAD

**Issue by RobinClowers** [segmentio/nightmare#1076]
I'm loading a page that contains an iframe, and everything works fine when I render the electron window, but once I set show to false, it never requests the iframe url at all. Is this expected? Is there any know workaround?

I'm using https://github.com/rosshinkley/nightmare-iframe-manager, but it seems like this is a problem with nightmare itself, since the iframe actually doesn't load at all.

I did file an issue there as well, just in case: https://github.com/rosshinkley/nightmare-iframe-manager/issues/17.

**Comment by casesandberg** [comment]
Are you still having trouble and have you tried 2.10.0? I am going to close this, but feel free to open a new issue if you are still having problems.
