### ISSUE TITLE
Suggestion: Update nightmarejs.org to mention which browser backend is used

### ISSUE THREAD

**Issue by sbrl** [segmentio/nightmare#1079]
The backend browser that's used by Nightmare JS is unclear to visitors of the website. The side-by-side code examples suggest that PhantomJS is the backend that's used, but according to the README of this repository that's not the case - it's electron + chromium.

I propose that Nightmare JS's website be updated to mention explicitly which backend is used.

**Comment by techtonik** [comment]
Which site are you talking about? Link from GitHub leads to segmentio catalog that eventually leads back to GitHub.

**Comment by sbrl** [comment]
@techtonik I'm talking about http://www.nightmarejs.org/ - the top result on Google (for me at least).

**Comment by techtonik** [comment]
Maybe there are plans to add WebDriver support or somebody is working on it?

**Comment by casesandberg** [comment]
We are currently working on a rewrite of the docs and will be launching a new website that includes this. I am going to close this for now.

**Comment by techtonik** [comment]
Looks like NIghtmare is Electron-only, so looks like there won't be any WebDriver support.
