### ISSUE TITLE
nightmare async fail?

### ISSUE THREAD

**Issue by wayneseymour** [segmentio/nightmare#1083]
I'd like to use Nightmare for e2e Tests.
I've encountered some errors when running this simple example:

```javascript
const Nightmare = require("nightmare");
describe("Load a Page", function() {
  this.timeout("30s");
  let nightmare = null;
  beforeEach(() => {
    nightmare = Nightmare({ show: true });
  });
  describe("/ (Home Page)", () => {
    it("should load without error", done => {
      nightmare
        .goto("http://localhost:5000/")
        .evaluate(function() {
          return document.title;
        })
        .end()
        .then(function(result) {
          console.log(result);
          done();
        })
        .catch(function(error) {
          console.error("Search failed:", error);
          done();
        });
    });
  });
});
```
...results in:
```shell
  Load a Page
    / (Home Page)
      1) should load without error


  0 passing (30s)
  1 failing

  1) Load a Page / (Home Page) should load without error:
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```
This simple example does call done in the `then` and the `catch` blocks, so I wasn't expecting it to hang until the timeout was met.

> Mac OS X Sierra, latest nightmare@^2.10.0, mocha@^3.2.0

**Comment by casesandberg** [comment]
Are you still having trouble? I am going to close this, but feel free to open a new issue if its still a problem.

**Comment by raquelhortab** [comment]
This happens to me too, I got it working most of the times locally (inside a docker container), but in production it's never working, we always get the timeout error...

**Comment by raquelhortab** [comment]
Hi! after almost a year, I need to work with nightmare again to add a functionality to an old project and found my own comment looking for solutions... 
I am only trying to call a js function from the document on beforeEach. I have started with a minimum example where I only call evaluate to return some value but it does not seem to work.

```
describe('blahblah', function() {
 beforeEach(function * () {
    nightmare = new Nightmare({...});
    console.log("something"); // this works
    // this does not work:
    let a = yield nightmare.evaluate(function() {return "hello"}).end().then((res)=>{console.log(result); done();});
    console.log(a); // nothing is printed
    // this does not work:
    nightmare.evaluate(function() {return "hello"}).end().then((res)=>{console.log(result); done();});
 }
...
}
```

I must say sometimes I do believe the library's name is quite well chosen
