### ISSUE TITLE
Using multiple evaluate() calls in the same test?

### ISSUE THREAD

**Issue by radiovisual** [segmentio/nightmare#1085]
I have a rather complicated SPA with a lot of different interactive form elements. I am using Nightmare to test the page and it's functionality, but I am finding that my tests are quickly getting out of hand, as I have to write a lot of tests that repeat some of the same steps from previous tests. 

In an effort to make my testing more DRY, I am hoping to find a workflow that lets me run multiple evaluation steps within the same test, this lets me check for small features and behaviors, without having to repeat the same steps over and over in multiple tests just to test these small changes.

For example, here is one idea where I am trying to return data from multiple `evaluate` methods and then trying to assert the collected values after calling `.end().then()`:

```js
  test('one', (done) => {
    nightmare
      .goto(visit('/'))
      .click('#button1')
      // first evaluate
      .evaluate(() => {
        return [1, 2];
      })
      // .. do more stuff
      .click('#button2')
      .click('#button3')
      // second evaluate
      .evaluate(() => {
        return [3, 4];
      })
      .end()
      .then((actualValues) => {
        expect(actualValues).toBe([1, 2, 3, 4]);
        done();
      })
      .catch((error) => {
        throw error;
      });
  });
```

But of course, I only get the results of the last `.evaluate`:

![image](https://cloud.githubusercontent.com/assets/5614571/24942632/1bd976a6-1f4a-11e7-88f4-d6effe449635.png)

Similarly, I can't use some sort of global object, since the global object would be unreachable from the method chains:

```js
test('two', (done) => {
    const objects = {};
    nightmare
      .goto(visit('/'))
      .wait(300)
      // first evaluate
      .evaluate(() => {
        objects.one = 1;
      })
      // .. do more stuff
      .wait(300)
      // second evaluate
      .evaluate(() => {
        objects.two = 2;
      })
      .end()
      .then(() => {
       // ERROR: objects is undefined
        expect(objects.one).toBe(1);
        expect(objects.two).toBe(2);
        done();
      })
      .catch((error) => {
        throw error;
      });
  });
```

**So is there a workflow that might permit multiple evaluations in a single test?** Or a workflow that would allow me to evaluate the page at different stages of the test? Or am I doomed to writing out my tests individually, in a way that isn't DRY?

**Comment by sdougbrown** [comment]
I've found using an `async/await` syntax to be a much friendlier workflow for this case...

```
  test('one', async (done) => {
    try {
      const first = await nightmare
        .goto(visit('/'))
        .click('#button1')
        // first evaluate
        .evaluate(() => {
          return [1, 2];
        })

      // .. do more stuff
      const second = await nightmare.click('#button2')
        .click('#button3')
        // second evaluate
        .evaluate(() => {
          return [3, 4];
        })

      expect([].concat(first, second)).toBe([1, 2, 3, 4]);
      await nightmare.end()
    } catch (error) {
      throw error;
    }
    done();
  });
```

I just figured this out myself so there might be a way to refine this a bit, but it's not too bad.  I find it easy to reason about it when you realize that the queue will evaluate until the next `then()/await` so you could break at pretty much any point, but for my own case I generally only need to break at each evaluate.

This should work fine with newer versions of node now that `async/await` has native support, or you could add [fast-async](https://www.npmjs.com/package/fast-async) to a babel workflow - up to you. 😄 

Enjoy!

**Comment by casesandberg** [comment]
Looks like this is resolved. I am going to close this for now but feel free to open a new issue if you are still having problems.

**Comment by stonkpunk** [comment]
alternate solution - 

the problem happens because the code within the evaluated function only has access to the variables in the browser's scope. because the obj you use to store the intermediate values exists in the node scope but not the browser scope, it's undefined for the evaluated function. but you can still use localStorage, cookies, etc to store the values.

eg, if you want to do multiple evals without making multiple nightmare instances, you can, for example, store the result using localStorage.setItem("eval1","first result") etc and then in the final eval return [localStorage.setItem("eval1"),localStorage.setItem("eval2")] etc

hacky but works for me
