### ISSUE TITLE
No error when Nightmare fails due to wrong Electron executable format (platform)

### ISSUE THREAD

**Issue by lzrski** [segmentio/nightmare#1086]
## Steps to reproduce:

1.  Have some kind of virtualisation (VM, Docker for Mac, etc.) with shared project folder.

1.  Install nightmare in your host OS (say OS X):

    ```sh
    npm install nightmare
    ```

1.  Prepare following test script:

    ```javascript
    "use strict";

    const Nightmare = require("nightmare");

    const browser = new Nightmare;

    console.log("Start");

    browser
      .goto("https://www.scrambled.com/")
      .title()
      .end(console.log)
      .catch(console.error);
    ```

    and save it `arch.js`.

1.  Run it:

    ```
    $ node arch.js 
    Start
    Scrambled - Smart content, delicious results - Food Film & Photography
    ```

1.  Now run it in your virtual machine with different platform (say Linux):

    ```
    $ xvfb-run node arch.js
    Start
    ```

## Expected result:

I'd like to get some kind of error that I could handle. 

I know what's wrong, but it's not very friendly, especially for colleagues who are not very experienced with Node.js. In local development it can happen quite often that you run dependency installation on your host instead of VM or the other way around. It can be confusing and time wasting.

**Comment by casesandberg** [comment]
Using `DEBUG=*` from the [debugging section](https://github.com/segmentio/nightmare#debugging) does tell you when there is a problem like this.

**Comment by casesandberg** [comment]
Using `DEBUG=*` from the [debugging section](https://github.com/segmentio/nightmare#debugging) does tell you when there is a problem like this.

**Comment by lzrski** [comment]
I respectfully disagree with closing this one. Having a possibility to infer the reason of failure from logs doesn't satisfy the need for proper error handling (with `try - catch` etc.). 

When it comes to logs, IMHO this kind of failure should be reported with default runtime configuration. I can't imagine a situation where it would be desirable for a program to silently crash. It definitely shouldn't be a default behaviour.

**Comment by casesandberg** [comment]
Ah, I agree, my bad

**Comment by lzrski** [comment]
Thank you. 

Nightmare is a great tool. Important part of our monitoring is running on it and I really appreciate the hard work your are putting into it's development. Keep it up :-)

**Comment by matthewmueller** [comment]
We'll be tracking this one in #1233. Thanks for bringing it up!
