### ISSUE TITLE
NightmareJS raises inconsistent errors

### ISSUE THREAD

**Issue by rinogo** [segmentio/nightmare#1088]
In different situations, NightmareJS seems to raise unique/inconsistent errors.  It would be much more useful to have a consistent error data structure.

Some examples of different errors I've received:

## Nice format, all fields have non-empty values
```
{ message: 'navigation error',
  code: -7,
  details: 'Navigation timed out after 1000 ms',
  url: 'https://example.com' }
```

## Empty `details`
```
{ message: 'navigation error',
  code: -3,
  details: '',
  url: 'https://example.com' }
```

## Non-friendly `details`
```
{ message: 'navigation error',
  code: -105,
  details: 'ERR_NAME_NOT_RESOLVED',
  url: 'https://non-existent-website-nifgeoawniogea.com/' }
```

## Different data structure
```
[Error: .wait() timed out after 1000msec]
```

With these different error structures, I've had to write a `.catch()` call that handles the various nuanced differences.

If we could always expect all fields to be present and non-empty, our `.catch()` calls could be very simple.  Example:

```
.catch(function (error) {
	console.error({"status": "error", "details": error.details});
});
```

**Comment by rinogo** [comment]
Also, if it helps anyone, here's the [`.catch()` block I'm currently using](https://gist.github.com/rinogo/5958c4a60905a963673317656e055c6c).  It works for the error messages I've encountered, but likely should be extended further.

**Comment by entrptaher** [comment]
I vote for the same. Navigation error code -3 is not helpful at all.

```
{ message: 'navigation error',
code: -3,
details: '',
url: 'http://example.com' }
```

**Comment by nlack** [comment]
yeah, it really sucks.

**Comment by Khady** [comment]
Isn't `-3` a code from
https://cs.chromium.org/chromium/src/net/base/net_error_list.h?

**Comment by rinogo** [comment]
@Khady Could be!  Regardless:

1. The message/details could be improved to be a lot more helpful.
2. The formatting of the various errors generated by NightmareJS should be more predictable.  The same data structure should be used throughout, and a helpful message and/or details should be included with each error.

**Comment by Auxilinaut** [comment]
I'm glad to see I'm not the only one with this sort of problem. Code -3 is popping up about 90% of the time for this project I'm on and the other 10% it just... works perfectly fine. I am using Cloud9 with NightmareJS in headless mode however, so I will attempt to run my script locally and have it show what's going on.

**Comment by casesandberg** [comment]
Does anyone have some time to throw together a PR for this? I would be happy to take a look at it. I am going to close this, but feel free to open a new issue if you get a chance to work on it.

**Comment by perry-mitchell** [comment]
Sorry @casesandberg, but why close this issue if this is an outstanding problem? Even if it's not easily solved through nightmare, isn't it better to recognise this as an reoccurring problem?

I too am seeing this issue about 5-10% of runs with `{show: true}`. It happens for colleagues running linux/osx machines and on a variety of target URLs.

**Comment by entrptaher** [comment]
@casesandberg, I agree, why are you closing this issue if it was never solved? Same goes with some of other issues, are you just going around closing issues so we can create same issues again?

It happens to me all the time with random websites where the requests are suddenly aborted on some part of the page. So far I .catch() and ignore -3 code, but we don't have anyone who can provide us with some more helpful indepth data.

**Comment by rinogo** [comment]
@perry-mitchell and @entrptaher - I feel like this is standard practice amongst many OS projects... Have you seen the "Won't Fix" tag on other source management/bug reporting systems?  At times I feel like closing out issues is a maintainer's way of saying, "bug or not, I'm not going to fix this".  Kind of a bummer.  Oh well - what can you do except perhaps contribute a fix yourself?...  If this is a high priority fix for you, I bet you could expedite its resolution by sending @casesandberg a few 💰, 🍺, or ☕️. 😄

**Comment by perry-mitchell** [comment]
Since a colleague added a [preload script](https://gist.github.com/perry-mitchell/fc7dcd9949f3763ce85eb11b71894ad9) to nightmare, we haven't seen this issue since. Here's hoping it stays gone.

@rinogo Of course, but I'd say it's a bit different in this case. This issue was closed without any meaningful action (including "Won't Fix"), which is what I was getting at. It is a high priority for myself, but if the maintainers won't acknowledge it as an important bug I must admit it's a bit off-putting in terms of contributing. Of course if I happen to find a solution while working with Nightmare I'll definitely create a PR.

**Comment by rinogo** [comment]
@perry-mitchell I hear ya!  Maintenance on OS projects is understandably a challenge for users/contributors and maintainers alike.  Thanks for providing that preload script, by the way! :)
