### ISSUE TITLE
Update setup/quickstart docs with missing prerequisite setup requirements

### ISSUE THREAD

**Issue by CollinChaffin** [segmentio/nightmare#1089]
For someone moving to JS after almost 30yrs in other languages, I'm very frustrated that after following all these setup docs, I cannot get any of the real testing examples to work out of the box and need some assistance.  Heck, as an example - just the statement of "you add this to your package.json".....um - which package.json?  I know that sounds silly but....I have about 300 package.json files on my drive.  Is it the main Mocha's package.json?  Or, a fresh brand new one corresponding to the test.js project the example here has me creating?  The docs have zero indication of which package.json it's even referring to.

I'm very confident I have traced all of this headache down to a huge amount of prerequisite setup specifically for the Mocha stuff simply being overlooked and the assumption made that anyone wanting to use nightmare, you must be all set up and established with Mocha testing as well as being very familiar with it.  I am neither.  I do however do enough js coding that is utilizing node and jquery these days that there is absolutely no reason I should not be able to very quickly get the provided test.js working, yet I'm pulling my hair out on why this is not working and want to verify there is not some bigger prereq missing from this quick setup quide.

I know after doing a npm install -g nightmare and mocha - the good news is that the base install of nightmare is working because the DuckDuckGo test in this readme worked great.  I just cannot run any provided examples that appear to require some mocha config above and beyond having it installed.

I hate to bother anyone with this but since this step-by-step quick setup does in fact walk through the prerequisites and it is just not accurate that simply having mocha installed is sufficient as it states, then I would like to help make it accurate so others do not face this frustration.

Here is executing the example test.js as provided here, after a step by step setup from the walkthrough from the docs:
```
describe('Load a Page', function() {
^
ReferenceError: describe is not defined

....more error info......
```

I have done a global -g npm install of mocha and nightmare and it appears there is some other Mocha-related setup above and beyond the statement made in these setup docs that those 2 things installed will execute the test.js example given.  I am running on Windows 7x64 latest node/mocha.  The only step I did not complete because it is not at all clear is the possible addition to a package.json.  I can do that but since the docs are totally unclear on which package.json if someone could point me to the right package.json I can see if that is the missing piece and we can update the docs accordingly.

Any help is greatly appreciated!

**Comment by casesandberg** [comment]
We are currently re-writing all of the examples and documentation!
