### ISSUE TITLE
nightmare:log crashed

### ISSUE THREAD

**Issue by overflowz** [segmentio/nightmare#1090]
Well, hello there.

I'm trying to download data, which is placed in UInt8Array in a browser.

This code produces nightmare:log crashed issue on Windows.

````await nightmare.goto('http://google.com');
  await nightmare.evaluate(() => {
    const arr = new Uint8Array(8495242);
    const blob = new Blob(arr); // <-- this causes crash.
    const url = URL.createObjectURL(blob);

    return url;
  });
````

It works fine on Chrome by default, but in nightmare logs I see only this:

````
Fri, 14 Apr 2017 00:55:31 GMT nightmare:actions .evaluate() fn on the page
Fri, 14 Apr 2017 00:55:31 GMT nightmare:log crashed [{},false]
````

Anyways, do someone know any other workaround to download UInt8Array from a page?

**Comment by casesandberg** [comment]
Are you still having trouble and have you tried 2.10.0? I am going to close this, but feel free to re-open if it's still an issue.
