### ISSUE TITLE
nigthmare.click()  : Cannot get the 404 error

### ISSUE THREAD

**Issue by xblanc33** [segmentio/nightmare#1094]
Hello,

I am running the following script 

`var Nightmare = require('nightmare');		
var nightmare = Nightmare({ show: true });

nightmare
  .on('console',function(type) {
    console.log("Console")
  })
  .goto('http://localhost:8080/')
  .wait('#nofile')
  .click('#nofile')
  .evaluate(function() {
    return document.body;
  })
  .then(function (result) {
    console.log("results:"+JSON.stringify(result));
  })
  .catch(function (error) {
    console.error('Search failed:', error);
  });`

where #nofile point to a 404 .

However, I didn't receive any event from the console and no error in the catch.

The evaluate performs well and returns nothing as document.body is null !!!

Can someone tells me how can I know that there is a 404 error ?

Regards (and thanks for making Nightmare)

**Comment by fouad** [comment]
Hey @xblanc33 

Check out a previous response about error codes in https://github.com/segmentio/nightmare/issues/790#issuecomment-247870576

Let us know if you have any other questions :)

Thanks!

**Comment by xblanc33** [comment]
#790 works for goto() 
not for click() ?
