### ISSUE TITLE
Can't click on a generated element

### ISSUE THREAD

**Issue by gvdh** [segmentio/nightmare#1095]
Hello everyone, 

I'm having an issue using nightmarejs since a few days and i can't figure it out so i post it here.
I made a script wich navigate through a website (login and change page) but i'm desperately stuck on a selector. I need to click on an input to generate a list, like this : 

<img width="542" alt="capture d ecran 2017-04-17 a 20 46 51" src="https://cloud.githubusercontent.com/assets/25708380/25100168/6014039a-23af-11e7-81ad-159ceba8968f.png">

So i made it to here but then i can't click on any of the options. I made a screenshot after the click on input so i know the list has been generated, i also printed the html after this and i can see it : 

<img width="1275" alt="capture d ecran 2017-04-17 a 20 52 07" src="https://cloud.githubusercontent.com/assets/25708380/25100275/c6573e1a-23af-11e7-9bda-de76fed454ef.png">

The options have an id but i can't click on it, and i don't get why ! Also, in the html print the generated list is below the footer.

Here is my code :
```
.click('.connexion-btn')
.wait('.na-login')
.type('input[name="login_s"]', 'login') // Substitute with your username
.type('input[name="pswd_s"]', 'password')// Substitute with your password
.click('#form_std > div.na-login-form-row.connection-submit > input')
.wait('.connexion-np')
.click('body > div.students > div.main-header-wrapper > div.shell > div.nav > ul > li.menuli.item-2 > a')
.wait('#annuaire_form > div:nth-child(4)')
.screenshot('screen5.png')
//.wait('#s2id_autogen14')
.click('#s2id_autogen13')
.wait('#select2-result-label-19', 5000)
.click('#select2-result-label-19')
.wait(5000)
.screenshot('screen6.png')
```

Everything work but the click('#select2-result-label-19'). 
Any ideas 🆘 ?

**Comment by casesandberg** [comment]
Are you still having trouble and have you tried 2.10.0? I am going to close this, but feel free to re-open if it's still an issue.
