### ISSUE TITLE
.click() is not working

### ISSUE THREAD

**Issue by dorjon** [segmentio/nightmare#1096]
Hi Team,
I am trying to test ionic app using nightmare. using selector ('#menumore') it should open the menu tab. which is not showing even i have applied wait for more time.
```
var Nightmare = require( "nightmare" );
var BASE_URL = "http://localhost:7500/#/index",

browser = new Nightmare({
  show: true,
  typeInterval: 20,
  pollInterval: 50
});


browser
  .goto(BASE_URL)
  .click('#menumore')
  .wait(5000)
  .end()
  .then(function (result) {
    console.log(result);
  })
  .catch(function (error) {
    console.error('Search failed:', error);
  });

```
console out put is showing success 

![image](https://cloud.githubusercontent.com/assets/19553002/25140035/97917ffa-247c-11e7-9c2b-1c69b4ed1b14.png)

The same thing is working when I am using webdriverIO for the same.  
Not able to identify why its not working ? please help

**Comment by casesandberg** [comment]
Are you still having trouble and have you tried 2.10.0? I am going to close this, but feel free to re-open if it's still an issue.
