### ISSUE TITLE
Navigation Error

### ISSUE THREAD

**Issue by sean-hill** [segmentio/nightmare#1097]
Hey there!

I'm getting a `navigation error` error with this code:

### Example
```js
var Nightmare = require('nightmare')
var nightmare = Nightmare({ show: true })

nightmare.goto('https://customer.xfinity.com/')
```

### Error
```json
{ 
  "message": "navigation error",
  "code": -3,
  "details": "",
  "url": "https://customer.xfinity.com/#/"
}
```
This error happens probably about 80% of the time, but occasionally it makes it through the command. It seems like Xfinity is doing a bunch of redirects, so maybe that is causing an issue?

**Comment by pg1671** [comment]
I have the same navigation error on my own site https://www.mypresences.com/. There are no redirects.

**Comment by sweinertjr** [comment]
+1

**Comment by casesandberg** [comment]
Are you still having trouble and have you tried 2.10.0? I am going to close this, but feel free to re-open if it's still an issue.

**Comment by xblanc33** [comment]
I have the same error with 2.10.0
Can't understand why.

**Comment by allen1991** [comment]
it really still happen again and again, sometimes it works, but many time failed, error appear。

**Comment by sean-hill** [comment]
@allen1991 nightmare is dead. Use something like puppeteer or playwright 😄
