### ISSUE TITLE
window open even if show=false

### ISSUE THREAD

**Issue by xblanc33** [segmentio/nightmare#1100]
Hello,

Nightmare still shows a window when clicking on <a target="_blank"></a> even if show=false in the options.

**Comment by calvinl** [comment]
I've been trying to resolve this too, but maybe for a different reason. It's fine in MacOS, but when a new window is opened using headless linux (xvfb-run) the script hangs - maybe it can't open new windows headlessly? 

Would love to see a solution.

**Comment by casesandberg** [comment]
Are you still having trouble and have you tried 2.10.0? 

You can also try the headless Chrome implementation in v3 which does everything in the background! https://github.com/segmentio/nightmare/tree/v3.

I am going to close this, but feel free to re-open if you are still having problems.
