### ISSUE TITLE
Character right side of cursor / extra character

### ISSUE THREAD

**Issue by stephan-v** [segmentio/nightmare#1103]
Whenever I run nightmare and use `type` there seems be a character on the right side of the cursor 60% of the time when I use type with a longer word. Of course this is what I see when I use the `show` property.

```
nightmare
    .goto('https://myurl.com')
    .click('#button')
    .type('#password', 'mylongpasswordexample987')
```

This also causes validation for the password field to fail so it seems to add an extra character in there. Can something be done about this?

**Comment by casesandberg** [comment]
Go ahead and try out the headless Chrome implementation in v3, it actually solves this issue! https://github.com/segmentio/nightmare/tree/v3.

I am going to close this, but feel free to re-open if you are still having problems.
