### ISSUE TITLE
xvfb-run VPS running errors

### ISSUE THREAD

**Issue by pkoperkowsky** [segmentio/nightmare#1104]
On VPS (Debian 7 64bit) I run the command:

DEBUG = nightmare xvfb-run --server-args = "- screen 0 1024x768x24" test.js node

And I receive such errors: https://pastebin.com/Cj8YEpNW

The test.js file is an example of "DuckDuckGo": https://github.com/segmentio/nightmare#examples

What could be the reason?

**Comment by casesandberg** [comment]
Looks like the errors pastebin expired, can you comment them inline in the issue here? I am going to close this for now but feel free to re-open it with some more details.
