### ISSUE TITLE
Feature Request: Support for XPath

### ISSUE THREAD

**Issue by shellscape** [segmentio/nightmare#1106]
Sometimes automation leaves us in a sticky wicket for sites that employ libraries like React. A button may not have a class, and it's parent chain may not have any attributes that make them readily identifiable, but something like `` using XPath and `document.evaluate` can get us the element we're looking for.

I'd like to request adding XPath support to the methods which currently have css selectors for parameters.

**Comment by heevy** [comment]
+1

**Comment by andela-sjames** [comment]
+1

**Comment by casesandberg** [comment]
Do you have some time to throw together a PR for this? I would be happy to take a look at it. I am going to close this, but feel free to re-open if you get a chance to work on it.

**Comment by shellscape** [comment]
@casesandberg if I had the ability to re-open issues, I would reopen it. this is a premature close, and I think it shows some lack of leadership - no one, not a single collaborator nor maintainer has commented on this prior to closing, yet the feature request seems to have some mild interest from other users. poor choice, there. with how under water the project is with regard to pull requests, I have little faith one would get looked at. and with 170+ pending issues in the queue, I can understand why'd you be quick to try and pick off some easy-target issues, but this was the wrong call.

**Comment by casesandberg** [comment]
Sorry for the premature close. This is currently not on the roadmap as we are focusing on the chrome headless implementation at the moment. As I said, if you would like to take a stab at a PR I would be more than happy to take a look at it!

**Comment by shellscape** [comment]
@casesandberg thanks for commenting. Is there a discussion the team can point to, to outline the decision to move to chrome headless, especially considering the development of [puppeteer](https://github.com/GoogleChrome/puppeteer)? I ask as one of the main draws of this was the use of electron. (And the discussion may warrant closure of the issue)

**Comment by matthewmueller** [comment]
Talked to the folks at segment about this a bit and we're going to stick with electron, since puppeteer is already a great option for headless chrome.

Regarding the issue, there's actually native xpath support in the browser with [document.evaluate]().

You could utilize xpath in nightmare like this:

```js
```
