### ISSUE TITLE
Feature Request: Support for HTMLNode Instances

### ISSUE THREAD

**Issue by shellscape** [segmentio/nightmare#1107]
In some (I'd wager many) situations, we're waiting for an element to appear on a page, or we're executing many operations on the same element. A decent pattern would be to use some `const` variables to store the reused selector, but it would be great to use `evaluate` to return a Node (or a new convenience method) to be reused. This would [albeit marginally] speed up some operations as well.

**Comment by TimNZ** [comment]
There's no way of passing DOM nodes out of the Electron BrowserWindow that hosts the page.

I would recommend just using .evaluate() if you have need to do your own caching, though I am curious about what you are doing that you think there could be a performance issue? :)

**Comment by shellscape** [comment]
@TimNZ if we were, for instance, mapping nodes from an indirect selector, based on attribute data (would require an array of nodes, but same difference :)). throwing it back to the days of yore for a pseudo example:

```js
$('input').map(function() {
    if(/some pattern/.test($(this).val())) {
      return this;
    }
  });
```

Or potentially something like that. I should have included more information in the original issue because I honestly can't remember the exact use case I had in mind with this one haha. Please feel free to close if you'd like to.

(On a side note, some issue templates on the repo would be useful! Probably would have reminded me to be more verbose in my haste creating this issue)

**Comment by TimNZ** [comment]
Haha.  I'm going through old issues as I'm doing significant mods and seeing if anything in old issues needed attention now. 
#1254

**Comment by matthewmueller** [comment]
Closing since we've mentioned before that you can't pass DOM nodes between the electron and node processes.

I'll also make a note to look at the documentation to see if we can explain that better.
