### ISSUE TITLE
Feature Request: Provide Access to Underlying BrowserWindow

### ISSUE THREAD

**Issue by shellscape** [segmentio/nightmare#1108]
Pretty much what the title says :)

**Comment by casesandberg** [comment]
Can you provide some more information or a code example? I am going to close this for now but feel free to re-open it with some more details.

**Comment by shellscape** [comment]
lolwut. @casesandberg non-collaborators don't have the ability to re-open issues. this is a premature close, and I think it shows some lack of leadership - no one, not a single collaborator nor maintainer has commented on this prior to closing, and with 170+ pending issues in the queue, I can understand why'd you be quick to try and pick off some easy-target issues, but this was the wrong call.

[`BrowserWindow`](https://electron.atom.io/docs/api/browser-window/) - it's literally the entry point for an app using electron. The feature request is asking for this to be made accessible via nightmare.js API.

I'm not sure if you just copy/pasted your closing message or if you're serious that you need a code example for that. But it's pretty obvious what's being requested here.

**Comment by casesandberg** [comment]
Sorry @shellscape, I did not understand the title. We are working on the v3 which uses chrome headless and ditches electron.
