### ISSUE TITLE
When something in a test times out, does it retry?

### ISSUE THREAD

**Issue by mrdanimal** [segmentio/nightmare#1109]
As far as I can tell, it doesn't. I also can't see any way to handle a timeout to ensure that it fails gracefully and can be retried. The biggest cause of spurious failures in my tests is because some `wait(selector)` times out occasionally, and as far as I can tell, there's no way to handle these cases, so when I run my entire suite, some percentage of my tests _always_ fail. Am I overlooking something?

edit: I should clarify: I'm using mocha and it has a `retries` setting, but it doesn't seem to retry unless a test actually fails instead of just timing out. I think I need a way to handle timeouts so I can explicitly throw an error.

**Comment by casesandberg** [comment]
You should be able to wrap the nightmare code in a try catch and throw an error there so that mocha will trigger the retry!

I am going to close this, but feel free to re-open if you are still having problems.
