### ISSUE TITLE
nightmare hanging, element is clearly visible

### ISSUE THREAD

**Issue by HoneyryderChuck** [segmentio/nightmare#1111]
I'm having an issue with using nightmare, where I ask it to click a button, wait for another, and then evaluate.

```js
nightmare.goto(appDomain)
				.wait()
				.click("#login")
				.wait("#logout")
				.evaluate( () => {
...
```

I run with `show: true` to debug, and the electron app clearly shows the logout button. It hangs until the timeout is reached.
The app is a single-page server-side-rendered app, and the callback-based login forces a page full render; so the markup is coming indeed from the server and should be visible on first paint, which only makes me confused.

How can a debug this further? I've read other tickets where people complain of electron/nightmare conflicts, but I'm using the latest ones (nightmare: 2.10.0, electron: 1.4.4), and don't know exactly where to start from.

**Comment by edmcmanwich** [comment]
@HoneyryderChuck I'm having the same issue. After a full page render triggered by a click the wait function sometimes fails to execute. Did you have any success diagnosing the issue?

**Comment by HoneyryderChuck** [comment]
@edmcmanwich , nop, I gave up and started doing something else.

**Comment by cmordue** [comment]
I have the same issue too. It's a hack but I ended up adding a `.wait(100)` after the click and before the `.wait(#element-in-response)` and our test hasn't been flaky.

**Comment by casesandberg** [comment]
Looks like this is resolved. I am going to close this for now but feel free to open a new issue if you are still having problems.
