### ISSUE TITLE
Is the cache cleared between sequential uses of nightmare? 

### ISSUE THREAD

**Issue by mashaalmemon** [segmentio/nightmare#1112]
Hi There,

Based on what I understand from the conversation had in #184, it seems that cache is on by default. 

However assume a use case where nightmare is used to traverse multiple pages of a site. Further assume that there are multiple components of the site can be cached and reused between page visits (i.e. header images, footer images, scripts, etc.). I'm trying to wrap my head around cache behaviour in the specific case is when each page traversal is carried out sequentially in its own instance of nightmare. Imagine high level pseudo code for such a scenario as (starting at the root of the site):

1. instantiate nightmare instance
2. visit page url given and find all links on page pointing to this same site
3. destroy nightmare instance (effectively shutting down browser) 
4. for each link found on page
    - go back to 1

My question is, between independent and sequentially run instances of nightmare, is the cache of previous pages visited, accessible to subsequently instantiated instances of nightmare? Is the cache kept intact or is it ignored/deleted. 

Like a browser used by a user on his/her machine, each time they start-up the browser, cache exists and is ready for use unless they explicitly clear the cache. Is this also the case here?

Any guidance in this regard will be helpful. Thanks in advance.

**Comment by casesandberg** [comment]
It currently does not. Go ahead and try out the headless Chrome implementation in v3, it shares the cache! https://github.com/segmentio/nightmare/tree/v3.

I am going to close this, but feel free to re-open if you are still having problems.
