### ISSUE TITLE
How to login a page has recaptcha by using nightmare?

### ISSUE THREAD

**Issue by duongli45** [segmentio/nightmare#1113]
Hi all, I'm trying to use nightmare to test some functions on my website.
But my website has login with recaptcha, so does it have any way to bypass this case?  
I have an idea that try to copy(?) the cookies from current browser (logged in already) to nightmare and use it to enter my site. Is that correct? If not, how can I test my website? 
please give me some recommendation. thanks

**Comment by duongli45** [comment]
@rosshinkley Can you take a look at my case

**Comment by jesobreira** [comment]
If that's your site, then you could just disable recaptcha for the testing, then re-enable it.

Take a look at [Death By Captcha](http://www.deathbycaptcha.com) as well.

**Comment by casesandberg** [comment]
Are you still having trouble? I am going to close this, but feel free to re-open if its still an issue.
