### ISSUE TITLE
How to really set the headers?

### ISSUE THREAD

**Issue by PapillonV** [segmentio/nightmare#1115]
How can I set the exact headers to send with every request?

I mean really the exact headers.

E.g., I want this:

Host: localhost:8080
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0
Connection: keep-alive
...

I do NOT want this:

Host: localhost:8080
Connection: keep-alive
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0
...

It is possible to use onBeforeSendHeaders to add and replace some (not all) headers, but I have no control about the order in which it will be sent.

I tried a workaround and just faked the header like this:

requestHeaders: {
  'Accept': null,
  'Accept-Language': null,
  'Accept-Encoding': null,
  'Referrer': null,
  'Cookie': null,
  'Connection": null,
  'foo': '1234\r\nbar: 1234\r\ntest: foobar'
}

This works partly as a workaround. But what doesn't work is to remove the 'Connection' entry. The 'Connection: keep-alive' header is added no matter what I try. And it is always added right on top, which I don't want.

Is there a way to either manually set the full header for every response as a string and not as an object, or at least a way to remove the 'Connection: keep-alive' header which gets automatically added?

**Comment by casesandberg** [comment]
Are you still having trouble and have you tried 2.10.0? I am going to close this, but feel free to re-open if it's still an issue.
