### ISSUE TITLE
Enable Right-Click in Window?

### ISSUE THREAD

**Issue by TomAshley303** [segmentio/nightmare#1121]
I can't seem to figure out how to enable the right-click menu in Nightmare's Electron window. It can be done in Electron by adding code to the renderer process script. How to do in Nightmare? I need to be able to right click and inspect specific elements without having to wade through the DOM elements in the inspector.

**Comment by casesandberg** [comment]
This currently isn't enabled. Do you have some time to throw together a PR for this? I would be happy to take a look at it. I am going to close this, but feel free to open a new issue if you get a chance to work on it.
