### ISSUE TITLE
How does nightmare exit so smoothly?

### ISSUE THREAD

**Issue by stevenvachon** [segmentio/nightmare#1124]
I asked this in the Gitter channel, but received no response:

> i'm trying to implement an electron html test runner for [npmjs.com/testee](https://npmjs.com/testee) -- my code works, but it doesn't exit when tests are finished.. nightmare quits electron smoothly every time, but i can't find the code that makes this happen

I tried adding [these event listeners](https://github.com/segmentio/nightmare/blob/master/lib/nightmare.js#L246-L251), but no change in behaviour.

**Comment by casesandberg** [comment]
You should also end on uncaught exceptions like it is done here: https://github.com/segmentio/nightmare/blob/e68d0f2ec7e32da9d2f353eb3ed19e86adce0f6d/lib/nightmare.js#L154-L158
