### ISSUE TITLE
No error messages when electron exits with code 127

### ISSUE THREAD

**Issue by dcecile** [segmentio/nightmare#1126]
I'm setting up Nightmare for the first time on Linux, and I tried running the first example, which executed without any output at all. After investigating myself, I figured out that I'm experiencing #224, but it would be nice if Nightmare had raised an error right away.

This issue is not about the installation problem (tracked in #224). This issue is about Nightmare's behavior when there are installation problems.

Here's the example code from [Readme.md](../blob/master/Readme.md#examples):

```js
var Nightmare = require('nightmare');		
var nightmare = Nightmare({ show: true });

nightmare
  .goto('https://duckduckgo.com')
  .type('#search_form_input_homepage', 'github nightmare')
  .click('#search_button_homepage')
  .wait('#zero_click_wrapper .c-info__title a')
  .evaluate(function () {
    return document.querySelector('#zero_click_wrapper .c-info__title a').href;
  })
  .end()
  .then(function (result) {
    console.log(result);
  })
  .catch(function (error) {
    console.error('Search failed:', error);
  });
```

On my system, this example code executed without outputting *anything at all*.

Here's the output using `DEBUG=nightmare`, which includes a note that the electron process failed with exit code 127:

```
  nightmare queuing process start +0ms
  nightmare queueing action "goto" for https://duckduckgo.com +8ms
  nightmare queueing action "type" +5ms
  nightmare queueing action "click" +0ms
  nightmare queueing action "wait" +0ms
  nightmare queueing action "evaluate" +0ms
  nightmare running +2ms
  nightmare electron child process exited with code 127: command not found - you may not have electron installed correctly +63ms
  nightmare electron child process not started yet, skipping kill. +2ms
```

And here's the output from running `node_modules/.bin/electron` directly (actual root cause, not shown in Nightmare debug info):

```
error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
```

To make it easier for users to notice an installation problem, maybe Nightmare could raise an error if the electron child process exited without success and/or none of the Nightmare commands got executed by electron.

**Comment by matthewmueller** [comment]
Yep agreed, this should be addressed by: https://github.com/segmentio/nightmare/issues/1233

If you're still running into difficulties with running nightmare on linux, you can check out: https://github.com/segmentio/nightmare/issues/224#issuecomment-365938300
