### ISSUE TITLE
Wait for react dynamic components

### ISSUE THREAD

**Issue by archieherbias** [segmentio/nightmare#1128]
I have a react webapp that has dynamic components and get rendered after an API call. I want to create a pdf after the components are rendered. I tried using `wait('.some-class')` but it seems that it is not re-rendering the components in the headless browser after an API call.

Is this possible with this library to wait for re-render of react components?

**Comment by airtoxin** [comment]
It seems to issue about React.js not Nightmre.js. 
React have no API to get internal state (now rendering, now mounting), so you can't wait fully page rendered except helping any rendered classes.

**Comment by entrptaher** [comment]
It seems there is a react plugin for nightmare.
https://www.npmjs.com/package/nightmare-react-utils

**Comment by archieherbias** [comment]
Seems `nightmare-react-utils` will be useful for my problem. I'll try to dig some of it and hopefully get it working.
Thanks @entrptaher !

**Comment by casesandberg** [comment]
Looks like this is resolved. I am going to close this for now but feel free to open a new issue if you are still having problems.
