### ISSUE TITLE
How to search for more complex queries?

### ISSUE THREAD

**Issue by codeofsumit** [segmentio/nightmare#1129]
Example: I'd like to get a sibling element of the element whose child with the class `'bla'` has the text `Mo 03.04`.

in jQuery that's something like:
`$('.bla:contains('Mo 03.04')').parent().next()`. Is that possible?

Otherwise I'd get all elements with the class `bla`, loop over it and compare the `innerText`.
But I can't return the DOM array in `.evaluate()`, neither can I pass utility functions that I'd need to it (like lodash or momentJS).

How would you go about it?

**Comment by nlack** [comment]
you could use an index on an querySelectorAll and return it for later use... if you could use the dev tool to get the css selector path this would be the best option i could think of 🤔 
https://github.com/alexbardas/nightmare-har-plugin uses the dev-tool

**Comment by casesandberg** [comment]
It doesn't look like there has been any progress on this issue lately. I am going to go ahead and close it, but feel free to open a new issue.
