### ISSUE TITLE
Did the development halt?

### ISSUE THREAD

**Issue by entrptaher** [segmentio/nightmare#1133]
Just a little question, The last commit is 1 month old. The issues are piling up. Builds are failing.
So what is the catch? What is missing? Are we waiting for headless-chrome?
I'm looking for a constructive discussion.

**Comment by rosshinkley** [comment]
No.  I personally haven't had a ton of time to devote to Nightmare as of late, but that should change in the next week or so.  I'm going to (try to) do an issue and PR review ... soon.

**Comment by casesandberg** [comment]
Going to close this one, feel free to continue the discussion.
