### ISSUE TITLE
🐛 Setting cookies for other domains fails

### ISSUE THREAD

**Issue by cheapsteak** [segmentio/nightmare#1135]
This seems always to fail

```js
const Nightmare = require('nightmare');

const browser = Nightmare({
  show: true,
}) 
.viewport(300, 300)

browser
  .goto('about:blank')
  .wait(1000)
  .cookies.set({
      name: 'token',
      value: 'some token',
      path: '/query',
      secure: true
    })
  .wait(1000)
  .catch(e => console.warn('failed to set cookies', e))
```

No error message is given, the caught exception is an empty object

OSX 10.12.3  
Node 7.10.0  (also tried on 6.9.1)
Also tried with other valid previously saved cookie values, no go

Just tried it on a windows machine as well, still no good

Tried providing it with latest electron-prebuilt and electron in electronPath, no go

**Comment by cheapsteak** [comment]
Dug a bit into the code

This: [`emitter.once(`CALL_RESULT_${id}`, function() {` ...](https://github.com/segmentio/nightmare/blob/master/lib/ipc.js#L87-L95) gets executed immediately after [`emitter.emit.apply(emitter, ['CALL', id, name].concat(args));`](https://github.com/segmentio/nightmare/blob/master/lib/ipc.js#L97), triggerd by [`process.on('message')`](https://github.com/segmentio/nightmare/blob/master/lib/ipc.js#L44-L50)

`arguments` has value of `{ '0': {} }`

**Comment by cheapsteak** [comment]
Seems to be an issue with setting cookies for other domains, can only set cookies for the same domain

**Comment by JonathanBristow** [comment]
I've tried to do this and ran into the same problem you have.
You can't set a cookie for a domain if you're not on that domain.

Have a look at persisting partitions instead.

**Comment by casesandberg** [comment]
Looks like this is resolved. I am going to close this for now but feel free to open a new issue if you are still having problems.
