### ISSUE TITLE
Can Nightmare be used as replacement for PhantomJS?

### ISSUE THREAD

**Issue by sowani** [segmentio/nightmare#1139]
Hi,

This is not any kind of issue, but rather a query. As I did not find any mailing list for Nightmare, I thought I will ask it here.

I have been using PhantomJS for headless browser testing. As PhantomJS project is doomed, I am looking for alternatives for it. Can I replace it with Nightmare? How easy it would be to replace it with Nightmare? (like just drop-in, or some little changes etc.).

If there is any documentation, past discussion thread etc., please let me know.

Thanks,
Atul.

**Comment by casesandberg** [comment]
Looks like this is resolved. I am going to close this for now but feel free to open a new issue if you are still having problems.
