### ISSUE TITLE
Webfonts not loading

### ISSUE THREAD

**Issue by bahlo** [segmentio/nightmare#114]
Hey,

I want to make a screenshot from a website which embeds its fonts via `@font-face`, but they're not loaded. I will set up a demonstration and post it here.

Have a great day and keep up the good work! :octocat:

**Comment by reinpk** [comment]
just retested this in `2.x` based on electron, and the font now renders correctly :)

![font-rendering](https://cloud.githubusercontent.com/assets/658545/9837539/3120051c-59f7-11e5-9eb4-ad615a32769f.png)

**Comment by brunowego** [comment]
Thanks @reinpk :+1:
