### ISSUE TITLE
Multi-process scraper in Nightmare.js doesn't work

### ISSUE THREAD

**Issue by ChristopherDedominici** [segmentio/nightmare#1140]
I'm developing a scraper that works perfectly if I run it in single process but when I run it in a multi-process way something very curious happen: 
basically all the nightmare instances start successfully but then only one of them is executed while the others stop working.

I'm thinking that probably the last instance to start "overrides" the previous ones.
Does anyone has any suggestion/idea?

To fork the process I use this code:
```
childVector[i] = cp.fork("./file.js");
childVector[i].send(JSON.stringify(informations));
childVector[i].on('message', function(message) {
       doStuff();                      
});
```

**Comment by casesandberg** [comment]
Go ahead and try out the headless Chrome implementation in v3, it allows multiple processes running at the same time! https://github.com/segmentio/nightmare/tree/v3.
