### ISSUE TITLE
Run tests on Firefox

### ISSUE THREAD

**Issue by techtonik** [segmentio/nightmare#1141]
Targeting tests for single browser is bad for web. Is it possible to run nightmare tests on Firefox?

**Comment by nlack** [comment]
Nope, nightmare uses [electron](https://electron.atom.io/) to get a webview which bases on chromium and V8~ You're looking for [Selenium](http://www.seleniumhq.org/)

**Comment by casesandberg** [comment]
As @nlack stated, nightmare uses electron. There is currently no plan to support any other browsers.
