### ISSUE TITLE
Scroll web page div elements

### ISSUE THREAD

**Issue by samavamsi1** [segmentio/nightmare#1142]
Can some one help me how to scroll the web page which is present in div or else Keydown events

**Comment by nlack** [comment]
see .scrollTo() in README.md
or use [javascript](https://developer.mozilla.org/en/docs/Web/API/Window/scrollTo) in .evaluate()

**Comment by samavamsi1** [comment]
is it possible to scroll by element ?

**Comment by nlack** [comment]
i think you mean scroll only in a scrollable area and not on the complete page? Like i said before, use `evaluate()` and google it on you own, since there is no function for it, make you own 🤔

**Comment by nzwsch** [comment]
@samavamsi1

```javascript
var Nightmare = require('Nightmare')

Nightmare.action('scrollIntoView', function (selector, done) {
  this.evaluate_now((selector) => {
    // https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView
    document.querySelector(selector).scrollIntoView(true)
  }, done, selector)
})

var nightmare = Nightmare({ show: true })

nightmare
  .goto('https://github.com/blog')
  .scrollIntoView('#blog-main .blog-post:last-child')
  .evaluate(function () {
    return document
      .querySelector('#blog-main .blog-post:last-child .blog-post-title')
      .innerText // returns post title...
  })
  .then((result) => console.log(result))
  // .then(nightmare.end())
  .catch((e) => console.dir(e))
```

**Comment by casesandberg** [comment]
Looks like this is resolved. I am going to close this for now but feel free to open a new issue if you are still having problems.

**Comment by iamdubx** [comment]
What if I just need this `document.querySelector('.PermalinkOverlay').scrollTo(0, 1000)`

Code snippet above seems too much for such stuff. Can anybody help me hot to scroll specific el?

**Comment by iamdubx** [comment]
This one doesn't work

```js
Nightmare.action('scrollOverlay', function (selector, done) {
  this.evaluate_now((selector) => {
    document.querySelector(selector).scrollTo(0, 1000)
  }, done, selector)
})
```
`document.querySelector(...).scrollTo is not a function`
