### ISSUE TITLE
electron npm dependency is not following SemVer rules

### ISSUE THREAD

**Issue by tothdavid** [segmentio/nightmare#1143]
Electron packages are not versioned using SemVer:
https://electron.atom.io/docs/tutorial/electron-versioning/
> Due to its dependency on Node and Chromium, it is not possible for the Electron project to adhere to a SemVer policy. You should therefore always reference a specific version of Electron.

So due to this nightmare npm package can cause breaking changes to a project even without a new release of nightmare npm package.
(In our case electron introduced a new typescript definition dependency which was not compatible with one of our own dependencies which broke the build.)

Please consider using fixed electron version or using ~ instead of ^.

**Comment by casesandberg** [comment]
Do you have some time to throw together a PR for this?

**Comment by casesandberg** [comment]
I am going to close this, but feel free to open up a new issue or PR for this.
