### ISSUE TITLE
Documentation for .header is misleading.

### ISSUE THREAD

**Issue by entrptaher** [segmentio/nightmare#1144]
The code format on `.header` function looks like an array, 
`.header([header, value])`

which is misleading. People might think the header accepts one parameter consisting an array.

The correct format is:
`.header(header, value)`

Which means the `.header` will accept two parameters.

**Comment by nlack** [comment]
true, but it would be really cool, if the function accept a header array 🤔

**Comment by casesandberg** [comment]
Do you have some time to throw together a PR for this?

**Comment by casesandberg** [comment]
I am going to close this, but feel free to open up a new issue or PR for this.
