### ISSUE TITLE
Unable to click the selector in the nightmare and is inject perfect

### ISSUE THREAD

**Issue by samavamsi1** [segmentio/nightmare#1146]
.inject('js', 'jquery.js')
.evaluate(function(){
    return $("#btn-checkin").click();
})

**Comment by nlack** [comment]
more context? now i would say the .goto() is needed 💩

**Comment by samavamsi1** [comment]
its just a sample code in my script i have added goto() but it doesnt work

**Comment by samavamsi1** [comment]
my webpage keeps on reloading if i am trying to inject the jquery.js file

**Comment by nlack** [comment]
could it be a site problem? exists a jquery on the page? inject jquery with you browser and test you methods, also use the dev tool console to look for errors.

**Comment by casesandberg** [comment]
Can you provide some more information or a code example? I am going to close this for now but feel free to open a new issue with some more details.
