### ISSUE TITLE
Possible to set devtools settings?

### ISSUE THREAD

**Issue by cheapsteak** [segmentio/nightmare#1147]
Specifically want to add blackbox patterns  
![image](https://cloud.githubusercontent.com/assets/743976/26653277/a30f6fde-4620-11e7-89d6-368a2ac78f74.png)

There are scripts that contain "debugger" statements that pause the scripts if devtools is open

Only solution I can think of now is to add rules to blackbox those scripts

**Comment by casesandberg** [comment]
There currently isnt a way to do this.
