### ISSUE TITLE
Evaluate times out on the second time being called

### ISSUE THREAD

**Issue by simonwolter** [segmentio/nightmare#1148]
I have two nightmare calls inside a function and this function is in a loop. One of the nightmare calls go to localhost which runs a node js server. The first loop works perfectly. In the second loop the evaluate function of the second nightmare instance which goes to localhost always times out. My code looks like this:

    function loopFunction(){
        var nightmare1 = Nightmare({ show: false,  executionTimeout: time, waitTimeout: time});

        nightmare1
            .goto(url)
            .inject('js', './lib/jquery-3.2.1.min.js')
            .evaluate(function () {
                // Do something
            })
            .end()
            .then(function (obj) {
                // Do something
            })
            .catch(function (error) {
                console.error('nightmare failed:', error);
            });

        var nightmare2 = Nightmare({ show: false});
        nightmare2
            .goto(localhost)
            .inject('js', './lib/jquery-3.2.1.min.js')
            .evaluate(function() {
                // Do something
            })
            .end()
            .then(function(result) {
                // Do something
            })
            .catch(function(err){
                console.error('nightmare failed: ', err);
            });
    }

I get this error:
Error: Evaluation timed out after 30000msec.  Are you calling done() or resolving your promises?
I'm new to node js and nightmare and maybe so solution is pretty easy but I cannot find a solution for myself.

**Comment by nlack** [comment]
What is happened, when evaluate() timeouted 🤔 
some hint : 
> The maxiumum amount of time to wait for an .evaluate() statement to complete.

Check you `evaluate()` call? Is the loop concurrency safe? Need something like [this]?(https://hackernoon.com/nightmarishly-good-scraping-with-nightmare-js-and-async-await-b7b20a38438f)
