### ISSUE TITLE
how to select hidden dropdown in nightmare

### ISSUE THREAD

**Issue by samavamsi1** [segmentio/nightmare#1152]
Can some one help how i should pick the element

**Comment by zlodes** [comment]
Try to use `.evaluate()` and, maybe, jQuery.
```
nightmare.evaluate(function(selector, value) {
   jQuery(selecotor).val(value);
}, 'yourSelectSelector', 'valueToSelect')
```

**Comment by samavamsi1** [comment]
how to select thevalue when it is in react dropdown

**Comment by jackSnaps** [comment]
@samavamsi1 I've used these steps while using nightmare:
• Go to webpage in Chrome
• Cntrl-click the element and choose "inspect," which should open Chrome Developer Tools
• Find the relevant code for the element, click on that code and then choose Copy > Selector

**Comment by samavamsi1** [comment]
i have tried the same method and given the
.select('selector',[value=option]) but it shows value cannot be focus .is
there a alternate way and the select element which i write is perfect or
any error

**Comment by samavamsi1** [comment]
example:
var Nightmare=require('nightmare');
var nightmare=Nightmare({show:true});

var url='https://jedwatson.github.io/react-select/'


 nightmare
 	.goto(url)
 	.evaluate(function(){
    	return $('#example > div > div:nth-child(1) > div.Select.Select--single.is-searchable.has-value > input[value="queensland"]').foucus();
            return $('#example > div > div:nth-child(1) > div.Select.Select--single.is-searchable.has-value > input[value="queensland"]').click()

   })
   .wait()
   .then(function(){
   	
   })

**Comment by airtoxin** [comment]
Because page isn't loaded jquery so you should inject jquery into page before page load.

**Comment by samavamsi1** [comment]
.inject('js','file location and name') is it correct syntax

**Comment by alexis1990** [comment]
anyone find an issue ???

**Comment by samavamsi1** [comment]
nightmare
    .goto('https://jedwatson.github.io/react-select/')
    .mousedown('.Select-value.State-NSW')
    .type('.Select-value.State-NSW', 'queensland\u000d')
