### ISSUE TITLE
Xlib:  extension "RANDR" missing on display ":0". On RHEL7

### ISSUE THREAD

**Issue by shakeebatme** [segmentio/nightmare#1154]
Running nightmare on **Jenkins Piepline** which has a slave configured on  _RHEL7_. And nightmare test case freezes. 

```
Tue, 06 Jun 2017 18:17:19 GMT nightmare running
Tue, 06 Jun 2017 18:17:19 GMT electron:stderr Xlib:  extension "RANDR" missing on display ":0".
Tue, 06 Jun 2017 18:17:19 GMT electron:stderr Xlib:  extension "RANDR" missing on display ":0".
```
has written **groovyScript** as 

```
wrap([$class: 'Xvfb', screen: '1440x900x24', autoDisplayName: true]) {
   ......
}
```

**Comment by rbjorklin** [comment]
Have you got all the necessary dependencies installed? We were seeing a similar problem on Centos while it was working just fine on Debian. I just created #1174 to jot the dependencies for Centos 7 (and therefore RHEL 7) down somewhere. Hope it helps!

**Comment by casesandberg** [comment]
Are you still having trouble with this?

**Comment by casesandberg** [comment]
I am going to close this, but feel free to open up a new issue if you are still having problems.
