### ISSUE TITLE
Nightmare giving errors in docker container, working fine when run locally

### ISSUE THREAD

**Issue by uLan08** [segmentio/nightmare#1155]
What I am trying to do is to save the page to a pdf, everything is working fine when I do it locally but if I run things in a container it gives an error. After investigating and trying to troubleshoot for a day or two, I could still not figure out what was wrong. So here I am.

The error it's giving me is 
```
Error: spawn /app/node_modules/electron/dist/electron ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:122:9)
```

**Comment by airtoxin** [comment]
your container includes `xvfb` ?

**Comment by uLan08** [comment]
no, what is that?

**Comment by airtoxin** [comment]
xvfb is virtual display. Electron can't execute in simple Docker container. It needs display.

**Comment by uLan08** [comment]
ohh. so do I only need to install it on the container or do I also need to run it somehow?

**Comment by airtoxin** [comment]
install xvfb and execute nightmare script via `svfb-run` or so

**Comment by airtoxin** [comment]
I use https://hub.docker.com/r/fentas/nightmare/ image.

```
docker run --rm -i \
  -v `pwd`:`pwd` \
  -e "NODE_ENV=production" \
  -e "DEBUG=_" \
  fentas/nightmare \
  bash -c "cd `pwd` && xvfb-run npm run test:e2e"
```

**Comment by uLan08** [comment]
hmm, but i don't have a specific nightmare script. nightmare is being called on demand. when there is a need to save to pdf and it is being built into `index.js`. so do i do something like `xvfb-run node dist/index.js`?

**Comment by airtoxin** [comment]
yes, `xvfb-run node dist/index.js` may works.

**Comment by uLan08** [comment]
I am using a node-alpine base image and I can't run `xvfb-run` command after installing. It says that is not found. For the past hour I have been reading on how to be able to run it to no luck.

**Comment by airtoxin** [comment]
Actually, I can't help about xvfb. But those script may helps you https://hub.docker.com/r/fentas/nightmare/~/dockerfile/

**Comment by uLan08** [comment]
I am now able to run `xvfb-run node dist/index.js` but the problem still persists. I also have set the docker shared memory to `128M`

**Comment by airtoxin** [comment]
hmm...
How about remove `node_modules` and reinstall modules?

**Comment by uLan08** [comment]
but `node_modules` are being reinstalled everytime the container is being built.

**Comment by uLan08** [comment]
I based my Dockerfile on this https://github.com/cjpetrus/alpine_webkit2png btw, just incase someone who is familiar with `xvfb` can help.

**Comment by uLan08** [comment]
Update: After rebuilding my image using Ubuntu base image, it is not giving out the error anymore but it seems the file is not being saved. I have a`console.log` that triggers after a file has been successfully generated but it never fires. I am saving the files to the `/tmp` directory though, I don't know if that matters. And I also manually checked the `/tmp` folder in the container and the files were not there.

**Comment by uLan08** [comment]
Added the other dependencies to install for nightmare to run and it worked. My image size when to around 1.5 GB though. Hopefully I can get this to work using alpine linux. Thanks btw guys.

**Comment by zhenyulin** [comment]
was having issues figuring out what exact packages I will need to run `nightmare` on `node:alpine` for e2e test

**Comment by jch254** [comment]
Did anyone get nightmare running on Alpine Linux? Cheers

**Comment by uLan08** [comment]
I haven't revisited this yet. Let us know if you're able to hack a solution.

**Comment by chalecao** [comment]
i got the error 
"stdin: is not a tty"

**Comment by iki** [comment]
I installed [xvfb](https://pkgs.alpinelinux.org/packages?name=xvfb&branch=edge) on [node:8-alpine](https://hub.docker.com/_/node/) using ```apk update && apk add xvfb``` and used [xvfb-run](https://manpages.ubuntu.com/manpages/trusty/man1/xvfb-run.1.html) script from https://github.com/cjpetrus/alpine_webkit2png to simplify the execution.

Anyway even the shell can't run electron there. Maybe [glibc is needed](https://wiki.alpinelinux.org/wiki/Running_glibc_programs), because electron uses it.
```
/var/www $ xvfb-run node_modules/electron/dist/electron
/var/www/bin/xvfb-run: line 184: node_modules/electron/dist/electron: not found
```

**Comment by matthewmueller** [comment]
Hi @iki, this comment should be able to help you out: https://github.com/segmentio/nightmare/issues/224#issuecomment-365938300
