### ISSUE TITLE
Incognito mode

### ISSUE THREAD

**Issue by ricpumanes** [segmentio/nightmare#1156]
Hi, just wanted to ask if it's possible to set NightmareJS to incognito mode? Or is it doing it by default? I'm new to using it so it's a little confusing. Thanks for the help!

**Comment by airtoxin** [comment]
`Nightmare({show: false});` ?

**Comment by ricpumanes** [comment]
@airtoxin i dont think that helps. It just shows the browser when Nightmare runs, right? What does it have to do with the 'incognito'? Or Did I grt it right?

**Comment by airtoxin** [comment]
what is incognito mode?

**Comment by ricpumanes** [comment]
It's one of Google Chrome's functionality which opens a new browser window for you but never keeps your browsing cookies or history.

**Comment by airtoxin** [comment]
I see. By default nightmare does incognito mode like behaviors.

> By default nightmare will create an in-memory partition for each instance. This means that any localStorage or cookies or any other form of persistent state will be destroyed when nightmare is ended. If you would like to persist state between instances you can use the webPreferences.partition api in electron.

https://github.com/segmentio/nightmare#storage-persistence-between-nightmare-instances

**Comment by ricpumanes** [comment]
Got it! Thanks @airtoxin !

**Comment by airtoxin** [comment]
please close issue 👍
