### ISSUE TITLE
failed: { message: 'navigation error',   code: -7,   details: 'Navigation timed out after 30000 ms'

### ISSUE THREAD

**Issue by ijshah** [segmentio/nightmare#1159]
I am using nightmare for web scrapping.for less records it works fine but for more record its gives nevigation timed out after 3000ms. Below is my code.

router.post('/getDetails', function(req, res, next) {

      stagecollection.find({
          "cityId": "1735"
        },
        function(err, data) {
          if (err) console.error();
          async.eachSeries(data, function(val, cb) {
            selectionarray.push(val.stageId);
            cb();
          });

          async.each(selectionarray, function(val, cb) {
            var nightmare = Nightmare({
              // show: true
            });
            nightmare
              .goto('example.com')
              .wait('select[name="cityId"]')
              .select('select[name="cityId"]', 1735)
              .wait('select[name="stageId"]')
              .select('select[name="stageId"]', val)
              .wait('#findBusStages')
              .wait(3000)
              .evaluate(function() {
                return document.documentElement.innerHTML; //pass all of the html as text
              })
              .end()
              .then(function(html) {
                var dom = cheerio.load(html);
               
                 var finalarray = dom('#findBusStages').children().eq(1).map(function(i) {
                   return dom(this).text().trim();
                 }).get();

                var bulk = busroutelistcollection.collection.initializeOrderedBulkOp();

                bulk.insert({
                  cityId: 1735,
                  stageId: val,
                  routeList: finalarray
                });

                bulk.execute(function(err, res1) {
                  console.log("insertedcount-", res1.nInserted);
                  var bulk = busroutelistcollection.collection.initializeOrderedBulkOp();
                });

              })
              .catch(function(error) {
                console.error('failed:', error);
              });
            cb();
          });
        });
  });

**Comment by Jackzhangpan** [comment]
@ijshah  I have the same problem， you solve it?

**Comment by val7000** [comment]
same thing @ijshah how did you solve it?

**Comment by GV-EI** [comment]
@ijshah how did you solve it? can you please explain i increase wait time too..but i wont works,the issue is persists

**Comment by davidjmorin** [comment]
same.. how to solve?
