### ISSUE TITLE
Example with Yahoo : TypeError

### ISSUE THREAD

**Issue by MathRobin** [segmentio/nightmare#116]
Hello !

I have just install the latest Nightmare 1.5.6. When I try to run the "Yahoo example", I get this :

```
phantom stdout: TypeError: 'null' is not an object (evaluating 'document.querySelector(selector).focus')

  phantomjs://webpage.evaluate():2
  phantomjs://webpage.evaluate():3
  phantomjs://webpage.evaluate():3

Done!
```

Seems that works but not really correctly.

**Comment by BerndErnst** [comment]
How about a bunch more examples?
The Yahoo example is still broken.
