### ISSUE TITLE
How to observe and respond to changes of specific dom elements?

### ISSUE THREAD

**Issue by zeroEvidence** [segmentio/nightmare#1160]
Hi all,

I'm using nightmare to scrape data from a webapp that has a lot of content being updated via AJAX requests at short and irregular intervals, I'm interested in only a small portion of the data that is being updated, is it possible to "listen" / "observe" a dom element for changes then have nightmare to execute a function accordingly?

The only solution I can think of is to have a plugin that accepts css selectors, create a MutationObserver to watch for changes and then to send the data to my application via an AJAX request.

Can anyone offer suggestions? or recommend a better solution?

Thanks in advance!

**Comment by zeroEvidence** [comment]
@Mr0grog presented this solution on nightmare's gitter. Just is case someone needs to solve this problem in the future! 

`function scrapeStuff() {
  nightmareInstance
    .evaluate(() => {
      return document.querySelector('#something').textContent;
    })
    .then(text => {
      // do something with the found text
    });
}

nightmareInstance
  .on('console', (type, arg) => {
    if (type === 'log' && arg === '::PAGE_UPDATED::') {
      scrapeStuff();
    }
  })
  .evaluate(() => {
    const observer = new MutationObserver(() => {
      console.log('::PAGE_UPDATED::');
    });
    observer.observe(document.querySelector('#something'), {
      childList: true,
      characterData: true,
      subtree: true
    });
  });`

**Comment by casesandberg** [comment]
That's a great solution! Going to close this for now, but people will still be able to find it by searching.
