### ISSUE TITLE
Chrome is not defined when trying to access window.chrome object

### ISSUE THREAD

**Issue by doanchu** [segmentio/nightmare#1163]
Chrome is not defined when trying to access window.chrome object. It seems Electron support some chrome.* APIs. How is it possible that chrome is not defined when using nightmarejs?

**Comment by matthewmueller** [comment]
Hi @doanchu, this isn't possible in nightmare right now. Nightmare runs on the main frame using the default execution context. Here's a diagram:

![image](https://user-images.githubusercontent.com/170299/36416363-72d68d64-165b-11e8-853c-041d3b3652ec.png)

`window.chrome` would be available in the *extension* execution contexts.

Do you know how to set this up in electron? If so, I can probably help you set it up in nightmare.

**Comment by matthewmueller** [comment]
Going to close this since this issue is getting stale. Please feel free to reopen if you're still running into this problem and have additional information for us :-)
