### ISSUE TITLE
.inject does not appear to work

### ISSUE THREAD

**Issue by jnikelski** [segmentio/nightmare#1169]
Sorry for the vague issue name -- I spent most of Friday trying to debug this issue, and by day's end was unable to craft a more useful/descriptive problem report name. 

Generally speaking, it would appear as if functions injected into Nightmare are apparently not available for use. This may be a misunderstanding in how to use this function -- my presumption is that *.inject* permits me to inject a function into the currently webpage, and then call that function within my *.evaluate* function. Sadly, I have been unable to get this to work Here's a simple example where I:
(1) login
(2) inject function jimmy() into the returned page
(3) try to access jimmy() in the .evaluate -- which is not found

Example: 
```async function login(){
    console.log('Starting the function *login* ...\n');
    const rx = await nightmare
        .viewport(2000,1000) // set viewport width & height high enough to get entire Oscar apt screen width
        .useragent(USERAGENT)
        .goto(EMR_LOGIN_URL)
        .type('input[name=username]', EMR_USERNAME)
        .type('input[name=password]', EMR_PASSWORD)
        .wait(1000)
        .type('input[name=pin]', EMR_PIN)
        .click('input[type=submit')
        .wait('td.title', 5000)       // page should be loaded at this point
        .wait(3000)                    // make sure
        .inject('js', 'injected.js')  // inject function jimmy()
        .wait('#search>a', 5000)
        .evaluate(function () {
            // return the full html of the currently loaded appointment page
            const html =  document.documentElement.innerHTML;
            debugger;
            jimmy();    // access the injected function
            return html;
        })
        .then(function(result) {
            return result;
        })
        .catch(function(error){
            console.error(`ERROR:Login Fx. ${error}`);
            process.exit(1);
        });
    
    return rx;
}
```
The test function looks like this:
```function jimmy(){
    console.log('JIMMY!!!');
    alert('JIMMY!!!!');
}
```
Upon running this, I get:
```  nightmare:actions .wait() for 3000ms +14ms
  nightmare:actions .wait() for #search>a element or 5000msec +3s
  nightmare:actions .evaluate() fn on the page +8ms
ERROR:Login Fx. jimmy is not defined
```
The debugger kicks in, but the next line fails, unable to find the function in the current page. A dump of the html confirms that the function is not on the page.

**Comment by casesandberg** [comment]
The function in evaluate does not have access to outside scope, that is why it is saying your function `jimmy` is not defined. It should work if you switch it to an ES6 auto-bound function:
```
.evaluate(() => {
  const html =  document.documentElement.innerHTML;
  jimmy();    // access the injected function
  return html;
})
```

**Comment by martinpitt** [comment]
I pulled my hair out for an hour or two, too, so for posterity:

I already called the injected function in an ES6-style `{} => {  myfunc() }`, but it also needs to be *defined* like that:
```js
myfunc = () => {
    return 42;
}
```

I previously had
```js
function myfunc() {
    return 42;
}
```
which does not work.
