### ISSUE TITLE
What is the roadmap of NightmareJS ?

### ISSUE THREAD

**Issue by mickaelandrieu** [segmentio/nightmare#117]
Hi @reinpk,

I'm part of casperjs team and I look at your project since months.
As you may notice, casperjs project is a little bit inactive... we don't have time to realy maitain it for now.

Imo, casperjs has some cons:
* not realy nodejs supported
* testing api / exporter is so coupled to the main/casper api
* a lot of weird behaviors

casperjs have also some pros:
* the best docs ever (realy, I contribute to a lot of projects including big frameworks like Symfony2, and casperjs has the best docs and a lot of samples)
* easy to use, easy to learn
* fast, realy fast / Selenenium
* fully tested, used by major companies
* (subjective) I like it, because I contribute to

I see that nightmare is actively maintained and I have a lot of ideas to suggest, probably to add fonctionnalities which I have on casper to nightmare.

You said the goal of nightmare is to expose only "few" methods, is there any chance that you change your mind on that ?

Regards,

**Comment by reinpk** [comment]
sounds good, we do intend to keep improving nightmare, though we'll keep the API small and push people to develop frameworks around it.
