### ISSUE TITLE
Unable to load app until wait() finish running

### ISSUE THREAD

**Issue by edosantillana** [segmentio/nightmare#1171]
I'm developing a little app with Express-Generator files structure and Nightmarejs, so i'm using routes. The Nightmare function is in my index.js file inside the routes directory, the wait() function waits until the right element loads, everything looks fine but when I run the app it can't find the index file until the wait function is completed. I figured it out because at the beginning it shows the 404 Not Found page but if I refresh the page several times (time enough to load the elements) then it works. I test it with wait(8000) and if I refresh the page until this amount of time it also works.
I made another test without routes, I mean, working only in the app.js file and it works fine, the page waits for the loading time and then showed the results, so that makes me think that I'm configuring something wrong in the routes files. Any ideas? Thank you.

**Comment by casesandberg** [comment]
Can you provide a code sample for this?

**Comment by casesandberg** [comment]
I am going to close this, but feel free to open up a new issue if you are still having problems.
