### ISSUE TITLE
Packages necessary for running Nightmare headless on Centos 7

### ISSUE THREAD

**Issue by rbjorklin** [segmentio/nightmare#1174]
So this isn't really an issue but more an attempt to contribute back my experiences of getting Nightmare running on Centos 7. See #224 for a long discussion on xvfb and pm2, especially [these](https://github.com/segmentio/nightmare/issues/224#issuecomment-239335488) [two](https://github.com/segmentio/nightmare/issues/224#issuecomment-261322814) posts might be of interest.

To run Nightmare you're going to want the non `-dev` variants of the build dependencies which can be found [here](https://electron.atom.io/docs/all/#build-instructions-linux) and also `libXScrnSaver` is mandatory for some reason.

**Comment by thandonguocmo2020** [comment]
thanks

**Comment by giscafer** [comment]
No match for argument: libgnome-keyring
