### ISSUE TITLE
Objects thrown instead of errors

### ISSUE THREAD

**Issue by lzrski** [segmentio/nightmare#1175]
I suspect this may be more appropriate for electron/electron, but decided to start here to pick your mind.

It seems that errors from Electron instance (e.g. `navigation error`) when they reach my application are not instances of error. They are objects with `message` property:

```js
{
  "message": "navigation error",
  "code": -105,
  "details": "ERR_NAME_NOT_RESOLVED",
  "url": "http://no-such-address.com/"
}
```

Do you think it's something that should be addressed in this project or in Electron? I feel it's a bug in one of these.

**Comment by casesandberg** [comment]
Yes, that is an electron error, it should be filed over there.
