### ISSUE TITLE
Make testing environment 'less real world'

### ISSUE THREAD

**Issue by Hermanya** [segmentio/nightmare#118]
Nightmare needs 'less real world', local web pages for testing.
* Current circleci build status is 'failed' because of timeouts.
* It would also make testing environment more consistent across the world. Yahoo serves different pages in different regions.
* Some edge case features are hard to test on 'real world' web pages.

**Comment by reinpk** [comment]
yeah totally agree, this is the next major improvement for nightmare i think

**Comment by reinpk** [comment]
fixed a while ago by the indomitable @dominicbarnes
