### ISSUE TITLE
How do I attach to the electron instance to use a debugger from within Nightmare?

### ISSUE THREAD

**Issue by maxcr** [segmentio/nightmare#1182]
I'm trying to produce some meaningful debug output to actually figure out where electron is crashing. I can't recreate the error without nightmare. The output from `DEBUG=*` seems to be nightmare only.

**Comment by wnxhaja** [comment]
how about you try this one. https://electron.atom.io/devtron/

**Comment by maxcr** [comment]
Thank you man I appreciate it. Looks like a good solution.

**Comment by casesandberg** [comment]
Are you still having trouble? I am going to close this, but feel free to open a new issue if you cant get it to work.
