### ISSUE TITLE
NightmareJs's site getting down

### ISSUE THREAD

**Issue by kousuketanihata** [segmentio/nightmare#1183]
http://www.nightmarejs.org/ is not connecting.
Does anyone know about this?

**Comment by fouad** [comment]
Hey @kousuketanihata sorry about that! Looks like there a weird issue with nightmarejs.org https://github.com/segmentio/nightmarejs.org/commit/df9adfefd39d2dbe772f9c1421684d19defc71fc#diff-50f29519600c68cb98dfc9766b28b111 (we're in the process of updating the site to include docs and some examples, so this shouldn't be an issue in the future!)
