### ISSUE TITLE
alert in an iframe hangs nightmare forever

### ISSUE THREAD

**Issue by aml11** [segmentio/nightmare#1184]
Hello,

using a brand new project with default preload, and navigating to a page that has an iframe that has an alert would result in electron hanging forever.

This is due to the fact that the preload isn't loaded into the child iframes just the top frame, so nothing hooks the window.alert.

This can be easily reproduced with this snippet in the page html:
```javascript
let iframe = document.createElement('iframe');
document.body.appendChild(iframe);
let sc = iframe.contentDocument.createElement("script")
sc.textContent = "window.alert('1');";
iframe.contentDocument.body.appendChild(sc)
```

You can see a live demo here:
[http://jsfiddle.net/6mSuK/1286/](url)

This code with a clean project shows it as well:
```javascript
var Nightmare = require('nightmare');
var nightmare = Nightmare({ show: true });

nightmare
    .goto('http://jsfiddle.net/6mSuK/1286/')
    .end()
    .then(function(result) {
        console.log("end");
    })
    .catch(function(error) {
        console.log(error);
    });
```

Is this expected behavior?

Thanks.

**Comment by aml11** [comment]
It appears to be an electron issue :( 
electron/electron/issues/2605

Any ideas to maybe get around this?

**Comment by maxcr** [comment]
Electron has so many fucking issues lately. I might need to abandon Nightmare for a while and switch back to a Phantom based scraper.

**Comment by casesandberg** [comment]
Closing this as it looks like electron will not be merging it.
