### ISSUE TITLE
Add new event "double click"

### ISSUE THREAD

**Issue by echinen** [segmentio/nightmare#1186]
Hello everyone,

I needed to use a double click event in my project with nightmare. But I didn´t find a solution to that. I think it would be interesting to have this event as an option.

**Comment by casesandberg** [comment]
Have you tried doing two successive `.click()`s? Just curious if that meets your needs.

**Comment by casesandberg** [comment]
Are you still having trouble? I am going to close this, but feel free to open a new issue if its still a problem.

**Comment by jagunosra** [comment]
i have tried the two successive click and it's not working... i am already stucked on this..

**Comment by nzhtrtlc** [comment]
no progress ?

**Comment by echinen** [comment]
I used this lib -> https://github.com/Mr0grog/nightmare-real-mouse in my project to simulate the double click event. It worked normally.
