### ISSUE TITLE
Is it possible to tell Chrome to open in mobile mode? 

### ISSUE THREAD

**Issue by JonathanBristow** [segmentio/nightmare#1188]
How would one go about getting Chrome (Electron) to open itself up in mobile mode? 
By mobile mode I mean the emulator you can turn on in the development tools.

**Comment by casesandberg** [comment]
You can set the window width and height and set the useragent to a mobile browser.

**Comment by entrptaher** [comment]
@JonathanBristow this gist will help you out, https://gist.github.com/emenoh/65708b03f1a99d92f14db9b0d60d8fd0
