### ISSUE TITLE
Sending Email via Outlook.com

### ISSUE THREAD

**Issue by ickyrr** [segmentio/nightmare#1192]
I'm curious, has anyone tried doing this? I have this code: (assuming i'm already logged in to my Outlook.com account)

```
return nightmare
          .wait(2000)
          .realClick("button[title='Write a new message (N)']")
          .wait(2000)
          .type("input[aria-label='To']", "email@email.com")
          ...
          .realClick("button[aria-label='Send']");
```

It just displays an error `Error: The message must have at least one recipient.`
Any help would be appreciated. :)

**Comment by casesandberg** [comment]
It sounds like there is a form error on the page that you are trying to submit the form on. Make sure you have filled out all of the required fields.
