### ISSUE TITLE
.click() on nth element?

### ISSUE THREAD

**Issue by kaytrance** [segmentio/nightmare#1194]
Lets assume we have a unordered list on a page with id **my-list** with links:

```html
<ul id="my-list">
   <li><a href="/link1">link 1</a></li>
   <li><a href="/link2">link 2</a></li>
   <li><a href="/link3">link 3</a></li>
   <li><a href="/link4">link 4</a></li>
</ul>
```

What **_selector_** should I provide for **nightmare.click(selector)** function to click on, for example, 3rd link in that list?

**Comment by cjhuaxin** [comment]
like this:

```javascript
nm.goto('')
     .click('a[href="/link3"]')
     .then();
```

**Comment by airtoxin** [comment]
You can only use electron's browser native selector in click function, if page doesn't load DOM manipulation library like a jQuery.
https://github.com/segmentio/nightmare/blob/master/lib/actions.js#L102

**Comment by casesandberg** [comment]
`.click()` accepts any CSS selector, you can click the 3rd one in your example like this:
```
...
.click('#my-list li:nth-child(3) a')
...
```

**Comment by JimTheMan** [comment]
@casesandberg The original question was "click on nth element", not nth-child.

**Comment by aixinalei** [comment]
you can give up nightmare's click .you can use jquery and evaluate to slove this question
eg:    
.evaluate(()=>{
      $(document).find('#my-list li a').click();
 })
