### ISSUE TITLE
.wait(selector) failing when show: false

### ISSUE THREAD

**Issue by brandonmp** [segmentio/nightmare#1195]
Using nightmare 2.10

This code works:

```
const nmPrefs = {
        webPreferences: {
            partition: 'persist: persist-key'
        },
        show: true,
        executionTimeout: 1000 * 60
    };
const nm = Nightmare(nmPrefs);

const t = await nm
            .goto('some login url')
            .wait('.some-selector', 2500)
             // username is already inputted and persisted to partition
            .type('#password', process.env.PASSWORD)
            .click('#Login')
            .wait('.some-selector-on-new-page', 2500)
            .title();

console.log(t) // returns correct page title
```

However, when I set `show:false`, the `title()` call returns the title of the login page, suggesting to me that the page isn't advancing correctly. 

Notably, when I change all the `wait(selector)` to `wait(time)`, it works fine. This is unexpected b/c I'm using the `wait(selector, timeout)` signature.

`wait(time)` works fine for my purposes, I just wanted to file a bug report in case this isn't a known issue.

**Comment by TimNZ** [comment]
Weird.  

Painful to debug without being able to test against the particular page.

It's not impossible the page or Chromium/Electron is using Page Visibility API and not rendering  if hidden.

You could do an .evaluate() action and query the DOM to find '.some-selector-on-new-page', or return back the HTML of the page and see how it differs when visible.

**Comment by matthewmueller** [comment]
hi @brandonmp, are you still having this issue? Happy to help you out but we'll need either the full script or a runnable example. Here's a template you can use to create that example:

```js
const Nightmare = require('nightmare')
const express = require('express')
const http = require('http')

main().catch(console.error)

function html(body) {
  return `<!doctype><html><head><meta charset="UTF-8"> </head><body>${body}</body></html>`
}

async function main() {
  const app = express()
  const server = await Server(app)

  app.get('/', (req, res) => {
    res.send(html(`server response here`))
  })

  const nightmare = Nightmare({
    loadTimeout: 45 * 1000,
    waitTimeout: 5 * 1000,
    show: true
  })

  await nightmare.goto(server.url, '/')

  // nightmare code here

  await nightmare.end()
  await server.close()
}

async function Server(handler) {
  const server = await new Promise((res, _rej) => {
    var s = http.createServer(handler)
    s.listen(0, 'localhost', function() {
      res(s)
    })
  })

  const address = server.address()
  return {
    url: `http://${address.address}:${address.port}`,
    close: function() {
      return new Promise((res, _rej) => server.close(res))
    }
  }
}
```

**Comment by matthewmueller** [comment]
Going to close this since this issue is getting stale. Please feel free to reopen if you're still running into this problem and have additional information for us :-)
