### ISSUE TITLE
Navigation error (-3) on setting Cookie header

### ISSUE THREAD

**Issue by kuraga** [segmentio/nightmare#1199]
```javascript
nightmare
    .goto('https://www.whoscored.com/Regions/252/Tournaments/2/England-Premier-League',
        { 'Cookie': 'valid header string' })
    .end()
    .then(function (result) {
    })
    .catch(function (err) {
      console.error(err);
    });
```
```
{ message: 'navigation error',
  code: -3,
  details: '',
  url: 'https://www.whoscored.com/Regions/252/Tournaments/2/England-Premier-League' }
```

Why? Thanks.

**Comment by kuraga** [comment]
@rosshinkley , @stephenmathieson , @reinpk , help, please...
Is it a bug or my fault? And how do I set cookies if I have a header line?
Thanks!

**Comment by airtoxin** [comment]
use [`.cookie`](https://github.com/segmentio/nightmare#cookies) api.

**Comment by kuraga** [comment]
@airtoxin , thanks!
But it's not an excellent option since I should parse cookies first.
So, it's not a bug?

**Comment by casesandberg** [comment]
Cookies are currently only supported via the `.cookie` interface. You can set cookies first though:
```
nightmare
    .cookies.set({ 'Cookie': 'valid header string' })
    .goto('https://www.whoscored.com/Regions/252/Tournaments/2/England-Premier-League')
    .end()
    .then(function (result) {
    })
    .catch(function (err) {
      console.error(err);
    });
```

**Comment by spfund** [comment]
I think it's still there. Sorry, I first did only find the "open" issue here and commented there.
https://github.com/segmentio/nightmare/issues/1412

I'm not sure what's going on.

I also found this https://github.com/segmentio/nightmare/issues/1070 but I can't see how this should have anything to do with evaluate...

My structure is
```
describe('Blah', function() {
    it('Bluh', function(done) {
         
        nightmare
        .viewport(1360, 800)
        .goto('...')
        .wait(...)
        .click(...)
        ...
        .evaluate(function() {
            ...
        })
        .end()
        .then(...)
        .catch(function(error) {
            console.error('Nightmare Error:', error);
            done('Error:', error);
        });
       
    })           
});
```

And if it does not work, then it will throw the error at "goto"...

Sometimes it works, sometimes not - it does not load the url and does not test.
