### ISSUE TITLE
Form Fields not targeted properly

### ISSUE THREAD

**Issue by dtothefp** [segmentio/nightmare#120]
I've noticed since changes were merged in last weekend that Nightmare no longer fills out form fields properly.  You can see an example in my repo here

https://github.com/dtothefp/nightmare-timeout-test-example/tree/master

If you run the tests, generated screenshots show that form inputs do not contain the correct information.  If you switch to my branch where I use an older version of Nightmare I previously forked:

https://github.com/dtothefp/nightmare-timeout-test-example/tree/dfoxpowell/nightmare-v1.6.0

```
rm -rf node_modules
npm cache clean
npm i
```

If you previously `npm i` in the master branch.  Then run the tests again and you will see that form fields are filled out properly.  You will also see in this branch the test timeout failures I submitted previously in

https://github.com/segmentio/nightmare/issues/102

**Comment by dtothefp** [comment]
@reinpk Any news on this, or should we file an issue elsewhere? I've had my Nightmare version constrained for far too long, and there have been many updates in `node phantom` module. I'm also working to switch to PhantomJS 2.0.0 which surprising worked fine if I was on Nightmare 1.6.0 but upgraded old Nightmare package.json to 0.7.2 of https://github.com/sgentle/phantomjs-node. Even the simple Optimizely signin form fails, as you can see the email and password get entered in the same input:

![screen shot 2015-03-22 at 11 49 50 pm](https://cloud.githubusercontent.com/assets/4656726/6773885/d36c2de8-d0ed-11e4-82c9-a121ef1972af.png)

**Comment by dtothefp** [comment]
@reinpk I've actually pinpointed the problem to this PR https://github.com/segmentio/nightmare/pull/100/files that switches the `type` action to implement the `sendEvent` Phantom method. I'm not sure if this is a problem with `phantomjs-node`'s implementation of `sendEvent` or a problem in PhantomJS itself, but for now would you consider reverting as it doesn't seem worthwhile to have such a small change potentially effecting users?

When I get some time later in the week I can put together some tests to pinpoint the problem more acuratelly and determine if I should submit an issue with `phantomjs-node` or PhantomJS

**Comment by reinpk** [comment]
yeah, that change seems to have made a lot more issues than it solved... the reason we switched it is because some fancier forms didn't respond well to the value setting method... but it was much simpler and more robust :P see #81, maybe there's a hack that sets value and then does a single `sendEvent` or something.

yeah, i'm definitely open to reverting that change and looking for a better solution.

**Comment by dtothefp** [comment]
@reinpk do I need to contribute something to revert this change, or would you like to do it? I'm tired of pulling from a fork of Nightmare just because of this small issue

**Comment by reinpk** [comment]
yeah makes sense, could you send over a pull request from your fork? happy to merge

**Comment by dtothefp** [comment]
@reinpk addressed it here https://github.com/segmentio/nightmare/pull/195. Sorry ended up having a bit of a "gitmare" and screwed up a couple PR's which I had to close. Would be great to get this merged as soon as you have a change.

**Comment by reinpk** [comment]
in v2 we're using electron instead of phantomjs, and electron doesn't have a native keypress function, so we're going back to the way it worked here originally, which should fix this issue in v2.0 #200

**Comment by naturalethic** [comment]
This issue has re-appeared in my tests.  Observe:

<img width="674" alt="screen shot 2015-12-25 at 12 13 19 pm" src="https://cloud.githubusercontent.com/assets/1254/12004284/b174fc3a-ab01-11e5-8df7-11b6d3859607.png">
