### ISSUE TITLE
How to use nightmare to inject script to developer tools ?

### ISSUE THREAD

**Issue by CrazySyntax** [segmentio/nightmare#1200]
Hi, 

I'm pretty new to nightmare.js. I want to use it for automation to script injections to websites.  
For example, I want nightmare.js to illustrate a situation that a user opened the developer tools, clicked 'F12' and typed in console:
` alert('Hello World'). 
`
Is it possible to do it with nightmare.js?

**Comment by balajmarius** [comment]
See [preload-scripts](https://github.com/segmentio/nightmare#custom-preload-script)

**Comment by patrickisallen** [comment]
I was looking to do something similar but still can't seem to get anything working. I perform a login and then I want to perform a javascript function on the page that has loaded in the developer tools console that gives me a list of items outputted to the console and then be able to capture that.

I have even tried injecting the script into the head element  on .evaluate() and attempting to execute it there but have no luck there.

**Comment by Khady** [comment]
I think you can try to have a look at nightmare-har. It injects scripts. But I don't know if that's what exactly what you want.

**Comment by casesandberg** [comment]
Are you still having trouble with this? Did nightmare-har meet your needs?

**Comment by patrickisallen** [comment]
I found a different solution still just using nightmare. 
Using the 

nightmare.on("console", (log, msg) => {
  //all outputs of the console are printed line by line as they come from the msg variable
  //so doing console.log(msg) will print everything as it comes
  //If you needed to filter you can just include an if statement to get what you want
}

**Comment by casesandberg** [comment]
Ah, great!

**Comment by G-BASUT** [comment]
> I found a different solution still just using nightmare.
> Using the
> 
> nightmare.on("console", (log, msg) => {
> //all outputs of the console are printed line by line as they come from the msg variable
> //so doing console.log(msg) will print everything as it comes
> //If you needed to filter you can just include an if statement to get what you want
> }

Can you share one example?
