### ISSUE TITLE
Can't set cookies from a file

### ISSUE THREAD

**Issue by RafekPL** [segmentio/nightmare#1201]
Hi.

I assume it's some minor problem and I'm a novice so can't get to the bottom of it.

I have one file which logs in to a website and stores a cookie in a .json file, which is all fine, but in the second file I can't set that cookie, as I'm getting a simple [object Object] error

First file: the part that saves the cookie:
```.cookies.get()
 .end()
 .then((cookies) => {
     require('fs').writeFileSync(
   'cookies.json',
   JSON.stringify(cookies, null, 4)
  );
```

Second file that gives an error (part of it):

```
storedCookies = fs.readFileSync('cookies.json');
        
yield nightmare
        .goto('about:blank'); 
        

        
      for(var i = 0; i < storedCookies.length; i++){
      nightmare.cookies.set(storedCookies[i].name, storedCookies[i].value)
      }


      // nightmare.cookies.set(JSON.parse(storedCookies)) //I tried doing it this way, which doesn't work as well for me

```

I am using TWO 'yield nightmare' in this file, not sure if it is a problem. If I delete the second yield (which immediately starts with a .goto, I get screamed at :P 

I have tried sessions or partitions, even setting a user data folder (which stays empty).
Don't know what to do now
And my formatting is messed up, sorry for that

**Comment by TimNZ** [comment]
Try:

fs.writeFileSync('cookies.json',JSON.stringify(...),'utf8')
var storedCookies = fs.readFileSync('cookies.json','utf8')

If you don't specify the file encoding (utf8) the contents are written as binary Buffer
https://nodejs.org/api/fs.html#fs_fs_readfilesync_path_options

**Comment by matthewmueller** [comment]
Thanks @TimNZ, I think that's the problem. Additionally, you'll want to parse the JSON and you'll want to yield on the `cookie.set. Something like this:

```js
storedCookies = require('./cookies.json')

yield nightmare.goto('about:blank'); 

for(var i = 0; i < storedCookies.length; i++){
  yield nightmare.cookies.set(storedCookies[i].name, storedCookies[i].value)
}
```
