### ISSUE TITLE
Support for spread operator

### ISSUE THREAD

**Issue by luanpotter** [segmentio/nightmare#1202]
There seem to be support for several ES6 features in the browser, but spread operator doesn't work. My questions are:

(1) Why is it so, and how easy it is to implement? I understand you use node, and that's already being support for a while now.

(2) Where can I find a comprehensive list of what is supported and what is not?

Thanks in advance! Awesome work, BTW!

PS. Spread operator example:

```
    const a = { a: 1 }, b = { b: 2, ...a };
    console.log(b);
```

**Comment by airtoxin** [comment]
It's a Electron's issue.
If you want to use spread operator, use transpiler such a babel.

**Comment by casesandberg** [comment]
@airtoxin is correct, you will want to transpile you code beforehand with babel. You can use the babel-loader in a custom webpack config.
