### ISSUE TITLE
Undesired redirects only on remote headless server

### ISSUE THREAD

**Issue by akvarma** [segmentio/nightmare#1205]
Hi,

I've been getting redirects back to the home page only on my remote server (Digital Ocean - Ubuntu 16.04).

Works just fine a few times after the server has just been deployed, but the redirects start after that, creating problems with the entire flow.

I'm using the node-xvfb package on Meteor, in case that helps in any way.

Works great locally. Any clues?

Thanks in advance!

**Comment by matthewmueller** [comment]
hi @akvarma, we'll need a bit more info. Could you please post your code (ideally an isolated test case), so we can help you further?

**Comment by matthewmueller** [comment]
Going to close this since this issue is getting stale. Please feel free to reopen if you're still running into this problem and have additional information for us :-)
