### ISSUE TITLE
Build a cache which stores HTML/CSS/JS dependencies

### ISSUE THREAD

**Issue by Vineeth-Mohan** [segmentio/nightmare#1206]
I have an entire site to crawl and I would like to store the CSS/HTML/JS in the cache and reuse it whenever required. How can i achieve this functionality.

**Comment by Khady** [comment]
Add a proxy like squid and configure nightmare to use it. Also, as long as nightmare is running, it has some cache. So better to keep your instances alive as much as possible.

**Comment by Vineeth-Mohan** [comment]
I am aware of squid based solution , what I was trying to see was to implement cache on nodeJS itself by capturing web request and injecting cache code.

**Comment by casesandberg** [comment]
There currently isn't a solution to inject cached code into the page. It would be worth checking out the headless Chrome implementation in v3, headless chrome does a bunch of different types of caching! https://github.com/segmentio/nightmare/tree/v3. I am going to close this, but feel free to open a new issue if you have anymore questions.
