### ISSUE TITLE
Add an API to specify the device pixel ratio

### ISSUE THREAD

**Issue by CWBudde** [segmentio/nightmare#1209]
For PhantomJS a new API was recently added to specify the devicePixelRatio. This comes handy especially for automated screenshot capturing of iOS device content (screenshots needed for iTunesConnect).

It would be nice to see a way to specify this devicePixelRatio with nightmare as well.

**Comment by TimNZ** [comment]
How about being able to pass an optional function to .goto() that is called from the preload script before the actual page content is loaded?  

```
nightmare.goto('https://www.quirksmode.org/m/tests/dpr.html',null /* headers */ ,function() { window.devicePixelRatio = 3})
```

**Comment by TimNZ** [comment]
Track via #1254 for time being.

**Comment by TimNZ** [comment]
Ignore above, this works now:

Nightmare({ show: true, webPreferences: {zoomFactor: 2 /* devicePixelRatio */ }})

https://electron.atom.io/docs/api/browser-window/#new-browserwindowoptions

**Comment by matthewmueller** [comment]
Awesome, thanks for the info @TimNZ. I just did a quick check to make sure that zoom and devicePixelRatio were directly related and it appears to be the case.

Before and after zooming in chrome (`cmd +`):

![Uploading Screen Shot 2018-02-19 at 4.09.48 PM.png…]()
