### ISSUE TITLE
Explain (or [re]move) Nightmare.version

### ISSUE THREAD

**Issue by CWBudde** [segmentio/nightmare#1210]
At the moment the documentation is a bit unclear as it reads:

> **Nightmare(options)**
> 
> Create a new instance that can navigate around the web. The available options are documented here, along with the following nightmare-specific options.
> 
> **Nightmare.version**
> 
> Returns the version of Nightmare.
> 
> **waitTimeout (default: 30s)**
> [...]

It seems as if the Nightmare.version doesn't fit there as I would expect to read nightmare-specific constructor options.

In addition version always seems to return 'undefined' over here. Eventually, it has been replaced by engineVersions but the change wasn't reflected in the documentation!?

**Comment by casesandberg** [comment]
Do you have some time to throw together a PR for this? I would be happy to take a look at it.

**Comment by TimNZ** [comment]
Nightmare.version prints fine, not defined in a nightmare instance 
e.g. var nightmare = new Nightmare(), nightmare.version is undefined

I would just move Nightmare.version ref in README to static properties section, or just remove it completely..
