### ISSUE TITLE
window in background

### ISSUE THREAD

**Issue by deesx** [segmentio/nightmare#1214]
I'm as new as I searched for it, sorry if has been answered; but could not get a clue about having the window to appear in the background when using the show:true option

In other words, i'd be looking into being able to code in the text editor without interruption, seeing the tests running in the electron browser in the background

Some might answer that it would be better to just remove the show option, but still i was wondering if that was possible to get such behaviour; to make sure i was not missing anything

**Comment by airtoxin** [comment]
Threre is no option.

**Comment by casesandberg** [comment]
There is currently no way to do this.
