### ISSUE TITLE
Connect to remote nightmare instance

### ISSUE THREAD

**Issue by sabrehagen** [segmentio/nightmare#1216]
We have nightmare running on a remote server with `show: false`. We'd like to connect in and display what the remote nightmare browser is seeing on our local machines. Is there a way to connect to a remote running nightmare instance, just like X forwarding with ssh?

**Comment by airtoxin** [comment]
no

**Comment by entrptaher** [comment]
First point. show:false will disable the show.

**Comment by casesandberg** [comment]
This currently isn't possible, although I know the headless chrome folks are working on a solution for it.
