### ISSUE TITLE
Randomly fails to execute function queued in .goto()

### ISSUE THREAD

**Issue by jmullo** [segmentio/nightmare#1220]
On a random test run, all Mocha tests will just time out. No errors or unhandled exceptions.

In `Nightmare.prototype.goto()`, this never gets executed:
`self.child.call('goto', url, headers, this.options.gotoTimeout, fn);`

Nightmare 2.10.0
Electron 1.6.2
Mocha 3.3.0
Node 6.9.4
RHEL 7.4

**Comment by jmullo** [comment]
After the first .goto() call, Nightmare is stuck in this state:

`Nightmare.state: 'initial'`
`Nightmare.running: true`
`Nightmare.proc ChildProcess.connected: false`
`Nightmare.proc ChildProcess.signalCode: null`
`Nightmare.proc ChildProcess.exitCode: 1`
`Nightmare.proc ChildProcess.killed: false`

**Comment by casesandberg** [comment]
Can you paste an example of the full test here so we can take a look at it?

**Comment by casesandberg** [comment]
I am going to close this, but feel free to open up a new issue if you are still having problems.

**Comment by jmullo** [comment]
Why the rush to close this? The problem has not fixed itself.

I haven't been able to provide an example, as this is a large project containing code I just cannot share.
