### ISSUE TITLE
Value return by goto is sometimes empty

### ISSUE THREAD

**Issue by Khady** [segmentio/nightmare#1223]
Sometimes (pretty often at my scale actually...), the value returned by the `goto` method is empty. I don't know which value it is, I don't manage to serialize it to my logs.

I have this condition

```typescript
try { val = await nightmare.goto("https://google.com") } catch (error) { return false; }
if (val === undefined || val === null || !val) {
```
 and it enters the `if` branch.

If I understand the documentation correctly, `goto` is not supposed to return an empty value like this. It should either return an object or throw an error.

Is it a bug or I have wrong expectations about `goto` behavior?

**Comment by Khady** [comment]
Sorry it's a typo, `httpResult` is `val`. I updated the snippet.

**Comment by Khady** [comment]
goto returns/throws correctly in my local too. But I use it on servers for a big number of pages and in this case it has this strange behavior. I have multiple nightmare processes that are launched in one nodejs process. I don't know if it can be the reason of the problem.

**Comment by airtoxin** [comment]
I see, nightmare can't run in parallel because nightmare instance is singleton.

**Comment by Khady** [comment]
So it's impossible to do multiple `new Nightmare(options)` in parallel? I have to launch multiple nodejs processes if I want to do that?

Thanks for your help

**Comment by airtoxin** [comment]
yes. It needs to launch single instance `new Nightmare()` per single node.js process.

**Comment by Khady** [comment]
Ok. Can close this issue then. I'll reopen it if I still have some problems with multiple processes.

Thank you for the quick and helpful answers!
