### ISSUE TITLE
returning nightmare promise from then()

### ISSUE THREAD

**Issue by mehdymohajery** [segmentio/nightmare#1229]
I'm trying to click on a button if it exists and then continue with nightmare promise but after then() 
I can't access the promise. How can i fix this?
 ```
.exists('#btnLogin')
.then(function(elementExists) {
	if (elementExists) 
	     return nightmare.click('#btnLogin');
	else 
	    return nightmare.wait(10);
})
```

**Comment by qaz3954179** [comment]
nightmare.wait('#btnLogin')

**Comment by mehdymohajery** [comment]
@qaz3954179  I'm not waiting for a control , this page shows different elements  based on different conditions. basically I want to have a ClickIfExists() method.

**Comment by qaz3954179** [comment]
you can use Nightmare.action method to  implement it.

**Comment by casesandberg** [comment]
The chain is not a promise until you use `.end()`.

**Comment by entrptaher** [comment]
```
var Nightmare = require('nightmare');
var nightmare = Nightmare({ show: true });

nightmare
  .goto('https://github.com/segmentio/nightmare/issues/1229')
  .evaluate(()=>{
      let elementExists = document.querySelector("#partial-discussion-header > div.TableObject.gh-header-meta > div.TableObject-item.TableObject-item--primary > a");
      if (elementExists)
           return elementExists.click()
      else
          return false;
  })
  .then(()=>{
    console.log('that was easy')
  })
```

You can simply do things like this with evaluate. Or create a action like this,

```
var Nightmare = require('nightmare');
var nightmare = Nightmare({
  show: true
});

Nightmare.action("clickIfExists", function(selector,done) {
  this.evaluate_now(function(selector) {
    document.activeElement.blur()
    var element = document.querySelector(selector)
    if (!element) {
      throw new Error('Unable to find element by selector: ' + selector)
    }
    var event = document.createEvent('MouseEvent')
    event.initEvent('click', true, true)
    element.dispatchEvent(event)
  }, done, selector)
})

nightmare
  .goto('https://github.com/segmentio/nightmare/issues/1229')
  .clickIfExists("#partial-discussion-header > div.TableObject.gh-header-meta > div.TableObject-item.TableObject-item--primary > a")
  .title()
  .then((title) => {
    console.log('that was easy and I got the title ', title)
  })
  .catch((e)=>{
    console.log(e);
  })
```

You can also pass the promise as you want in you example. The promise it returned properly. You are just not using that promise chain properly.

var Nightmare = require('nightmare');
var nightmare = Nightmare({
  show: true
});

nightmare
  .goto('https://github.com/segmentio/nightmare/issues/1229')
  //.exists("#partial-discussion-header > div.TableObject.gh-header-meta > div.TableObject-item.TableObject-item--primary > a")
  .exists("#whateverItDoesntExist")
  .then(function(elementExists) {
    if (elementExists)
      return nightmare
        .click('#partial-discussion-header > div.TableObject.gh-header-meta > div.TableObject-item.TableObject-item--primary > a')
        .wait()
        .title()
    else
      return nightmare
        .wait(1000)
        .title() // yes whatever, return something like title or don't
  })
// Continue the chain
  .then((title)=>{
    console.log(title)
  })

**Comment by TimNZ** [comment]
@entrptaher "Conditional actions" or something like that would be a useful section in the docs with that example.

**Comment by matthewmueller** [comment]
I think the above example should cover it, however for anything complicated, I recommend using either `async/await` or `generators`. Nightmare supports both natively:

```js
const exists = await nightmare.exists('#btnLogin')
if (exists) {
  await nightmare.click('#btnLogin')
} else {
  await nightmare.wait(10000)
}
```
