### ISSUE TITLE
Selecting multiple values on .select()

### ISSUE THREAD

**Issue by CarlosMC** [segmentio/nightmare#1230]
HI there! 
Thanks for the great work you're doing with Nightmarejs.

Is there a way to make a multiple value selection on a list? 
something like this:

**.select('#MultipleList', ['value1', 'value2', 'value3']);**

kind regards!

**Comment by airtoxin** [comment]
No. You should use DOM manipulation library like a jQuery in evaluate method.

```js
nightmare.evaluate(() => {
  $('#MultipleList .value1').click();
  $('#MultipleList .value2').click();
  $('#MultipleList .value3').click();
  return null;
});
```

**Comment by casesandberg** [comment]
Like @airtoxin said, you should be using something like jquery. I am going to close this for now but feel free to open a new issue if you have any more questions.

**Comment by CarlosMC** [comment]
THanks for helping me guys!

this code worked for me:

        .evaluate(function( valuesToSelect ) {
           $('#MultipleList').val(valuesToSelect);
        }, ['value1', 'value2', 'value3'])

sorry if reopen, but i wanted to leave the solution in case someone else need it.

**Comment by casesandberg** [comment]
Awesome! Glad to hear that helped

**Comment by banhaserhij** [comment]
@CarlosMC 
Im sorry, but i have a error like this:

>  TypeError: Cannot read property 'val' of null
>     at fn (<anonymous>:6:25)
>     at javascript (<anonymous>:21:21)
>     at <anonymous>:36:3
>     at EventEmitter.electron.ipcRenderer.on (/home/sergii/WebstormProjects/nightmare-art/node_modules/electron/dist/resources/electron.asar/renderer/init.js:63:28)
>     at emitMany (events.js:146:13)
>     at EventEmitter.emit (events.js:223:7) code: -1 }

Can you help me, becouse i don't know what to do... Here is code, maybe i somethink wrong write:
```
nightmare
    .goto('https://brovdi.art/administrator/index.php')
    .type('#mod-login-username', login)
    .type('#mod-login-password', password)
    .click('.login-button')
    .wait('#content > div > div > div.row-fluid > div.span3 > div > div:nth-child(2) > ul > li > a > span')
    .click('#content > div > div > div.row-fluid > div.span3 > div > div:nth-child(2) > ul > li > a > span')
    // .click('#limit')
    // .select('#limit',9)
    .wait('#limit')
    .select('#limit', 0)
    .wait(3500)
    .click('#adminForm > div.box-bottom > table > tbody > tr:nth-child(1) > td.name > span > a')
    .wait('#categories')
    //.select('#categories', 8)
    .evaluate((categories) => {
        $('#categories').val(categories);
    }, ['value1', 'value2', 'value3'])
    .wait(5000)
    .click('#toolbar-save > button')
    .wait(5000)
    .evaluate(() => document.querySelector('#adminForm > div.box-bottom > table > tbody > tr:nth-child(2) > td.name > span > a').href)
    .end()
    .then(console.log)
    .catch(error => {
        console.error('Search failed:', error)
    });
```
