### ISSUE TITLE
[WIP] Adding support for Nightmare to work inside current Electron process

### ISSUE THREAD

**Issue by TimNZ** [segmentio/nightmare#1236]
I want the automation goodness of Nightmare for an app I'm building, where it needs to work in the current Electron process, with  BrowserWindow and WebView.

If anyone else is working on this please let me know asap as I'm starting on dev today as I have a need for it right now.

PR next week.

Have not yet architected the changes, will scope this out properly first.

**Comment by entrptaher** [comment]
This might be of some help. https://github.com/segmentio/nightmare/issues/835#issuecomment-257035603

**Comment by TimNZ** [comment]
Working on adding in-process support to Nightmare right now when executing inside an Electron app.

* New Nightmare option 'useCurrentElectron' (likely renamed), support boolean or object with settings
* Work with BrowserWindow and a webview (hopefully no issues there)

Changes:

* Add a 'NightmareInProcess' function to nightmare.js that will be used if 'useCurrentElectron' specified.
* Re-use all the current queueing mechanism as much possible
* Implement a mock wrapper for ChildProcess returned from process.spawn so as to minimise changes in existing nightmare.js and ipc.js code.
* Separate browser process code from renderer process code in runner.js
-> runner.js: app level code for browser process, only used in traditional Nightmare usage
-> instance.js: wrapper for running actions in a BrowserWindow or webview

**Comment by KamesCG** [comment]
With curiosity, I have to ask how are you packaging the Electron application?

Do you plan on using electron-builder(https://www.npmjs.com/package/electron-builder) or another Electron packager? Just a warning, if you are using electron-builder to package the application, the electron binary is changed, so running Nightmare with the changed Electron binary, does not create the intended result i.e. Nightmare won't work.

**Comment by TimNZ** [comment]
As I said above, these changes do not address the issue with launching new Electron processes from within an existing process, that trickiness continues.

The packaging is irrelevant as I use only parts of Nightmare to automate a BrowserWindow/webview using the existing Electron process, bypassing all the process launching and co-ordination.

Use case?

I am building essentially an Electron based browser where I want to re-use Nightmare to automate a webview embedded within the app.  So I'm making changes to support this, and by extension to BrowserWindow.

I can look at the packaging issue another time to continue launching Electron runner as a separate process from within an existing Electron process, without duplicating Electron install, the packaging issue etc.

Off the top of my head, since packaging for Electron apps will always launch the 'main' script specified in package.json, you may need to add some basic command-line detection in the newly launched process in your main script and detect it's Nightmare and trigger Nightmare to run.

The changes I am making are a step towards enabling that.

**Comment by KamesCG** [comment]
Apologies for not reading more thoroughly above - I came from a different thread and only read your first post.

I'm circling back to the Nightmare/Electron packaging problem in the next 2-3 weeks.

I think the idea of the main process identifying if it's running Nightmare or the Application. You're probably correct, I can't foresee any major underlying issues to rebuilding the binary and running Electron, because all the correct methods for Nightmare should still be there. I think it's just a matter of debugging and understanding how everything is being tossed around under the hood.

Do you have an open repo you are working with?

**Comment by TimNZ** [comment]
Hi @KamesCG 

I definitely wouldn't look at doing anything around fiddling with the Electron binary/launcher.
The code for running the main script must be either be coded into electron.asar, or the embedded in the binary, though text search for a boot.js from one of my apps got no hit.

More likely, I would look at add a 'require('nightmare').shouldRunNightmare()' type function into my main script and if it decides Nightmare has launched this process, run the Nightmare runner, otherwise regular code flow.

In the meantime perhaps you can do research on whether there is any way to override the launch file for packaged electron and put together a definitive summary of the state of this, in case there is a way we are not aware of?

**Comment by TimNZ** [comment]
About 75% way through implementing.  Tested and works well.

Can launch a new BrowserWindow, or pass in an existing BrowserWindow or webview (must have loaded the necessary preload.js content yourself for IPC).

This will not address the situation where you are running within Electron and for some reason want to use current launching of new Electron process, as per above.

Though I can't see any reason you'd need to for security or process isolation, though there may be considerations for running multiple instances e.g. performance.

```
const {app} = require('electron');
const Nightmare = require('nightmare');

app.on('ready',() => {
  let nightmare = new Nightmare({ show: true,inProcess: true });
// let nightmare = new Nightmare({inProcess: existingBrowserWindow });

  nightmare
    .goto('https://google.com')
    .type('[name=q]','xemware')
    .wait(5000)
    .evaluate((selector) => {
      return document.querySelector(selector).value;
    },'[name=q]')
    .end()
    .then((result) => {
      console.log(result);
    })

})
```

**Comment by KamesCG** [comment]
I'm just now wrapping my head around what you're doing a little bit! It's been a couple months since working directly that code.

That's amazing - this solution has me so excited!

**Comment by TimNZ** [comment]
Follow in #1254
