### ISSUE TITLE
.type(selector, false) mysteriously stopped clearing text field

### ISSUE THREAD

**Issue by gerebdavid** [segmentio/nightmare#1239]
I've been using nightmare for a while, wrote hundreds of lines of test. But today one of my old tests stopped working while running a deployment, because `.type(selector, false)` mysteriously stopped clearing the textfield, however `.type(selector, 'some text')` works well. I've tried with the latest version and also with older versions, down to `2.6.0`. But got the same result.

**Comment by entrptaher** [comment]
can you try this and see if the problem is gone?
`.type(selector, "")`
Basically set it empty.

**Comment by gerebdavid** [comment]
@entrptaher i tried with `.type(selector, '')` and also `.type(selector)` same result

**Comment by gerebdavid** [comment]
it seems, that it's loosing focus or something like that, now it works like this
```
await nightmare.type(selector, false)
await nightmare
  .type(selector, false)
  .type(selector, text)
```

**Comment by casesandberg** [comment]
Looks like this is resolved. I am going to close this for now but feel free to open a new issue if you are still having problems.
