### ISSUE TITLE
Loading upwork login page (or many other pages with cloudflare) fails on nightmare

### ISSUE THREAD

**Issue by entrptaher** [segmentio/nightmare#1240]
If we try to open pages backed by cloudflare, it blocks us randomly. This is not an issue with cloudflare since loading the page on other browsers works fine. The issue only happens on electron/NightmareJS. 

This is the code.

```js
// Nightmare Code
const path = require('path');
var Nightmare = require('nightmare');
var nightmare = Nightmare({
  show: true,
  openDevTools: {
    mode: 'detach'
  }
});

nightmare
  .viewport(1300, 900)
  .goto('https://www.upwork.com/login')
  .title()
  .then(function(title) {
    console.log(title);
  })
  .catch(function(error) {
    console.error(error);
  });

// Puppeteer code
const puppeteer = require('puppeteer');
puppeteer.launch({
  headless: false
}).then(async browser => {
  const page = await browser.newPage();
  await page.setViewport({
    width: 1300,
    height: 800
  });

  try {
    await page.goto('https://www.upwork.com/login')
    let title = await page.title()
    console.log(title)
  } catch (e) {
    console.log(e)
  }
});

```
And this is the video of what happens.
![](https://media.giphy.com/media/3ohhwoeqyRDMyYYS8o/giphy.gif)
https://giphy.com/gifs/3ohhwoeqyRDMyYYS8o/fullscreen

So far I tried various chrome based browsers and firefox, worked perfectly fine. 
And nightmare loaded on first run, failed on every runs after that. 
I tried cleaning cache, cookies, changing versions etc. No avail.

**Comment by TimNZ** [comment]
What version of Electron is installed?

Works fine for me. 

Don't get any console errors as display in gif after repeatedly running

Can you please provide an example app that reproduces the issue.

Regardless it is not a Nightmare issue.

**Comment by entrptaher** [comment]
I tried the latest versions as well as previous versions. 
Tried proxies and without proxies.

**Comment by TimNZ** [comment]
If you provide a simple complete app that can reproduce the problem I will look at it.

**Comment by entrptaher** [comment]
The above script reproduces on my end. I'll try to provide some more info.

**Comment by matthewmueller** [comment]
Hi @entrptaher,

Just to get some background before working on this, did the puppeteer version work correctly? And are you still facing this issue or did you resolve it?

**Comment by entrptaher** [comment]
Still get them. It's supposed to show me title only if it loads.
Loads okay first time. Stops loading from second time.
Then changed proxy/vpn, loaded first time, stopped from second time.

![image](https://user-images.githubusercontent.com/8284972/36393066-376df15a-15d8-11e8-90df-9834c4d923d5.png)

**Comment by matthewmueller** [comment]
Hmm, okay I'm able to reproduce it. Is it working with puppeteer every time?

**Comment by entrptaher** [comment]
Yes. It works with puppeteer almost all the time.

**Comment by entrptaher** [comment]
Closing this issue for now. Will reopen if faced problem in future or have better explanation.
