### ISSUE TITLE
Action and Scenario as object (enhancement?)

### ISSUE THREAD

**Issue by xblanc33** [segmentio/nightmare#1243]
Dear all,

First of all, thank you for developping NightmareJS. This is really helpful.

I am using it since several months and I always have to dynamically create actions and scenario.

I therefore developped a small framework to easily create action and scenario : https://github.com/webautotester/action

I hope it will help ! If needed I can help to integrate it better with Nighmare.
Otherwize, juste forget about it.

Again thanks

Regards

**Comment by casesandberg** [comment]
This is awesome! I am going to close this but people will still be able to find it by searching.
