### ISSUE TITLE
Taking PDF of long page cause visual artifacts

### ISSUE THREAD

**Issue by cupuyc** [segmentio/nightmare#1245]
I print very long page as PDF { height: 16118, width: 1385 } in headless mode on MacOS and Debian 8. Resulted PDF for some reason contains cut off page.

<img width="246" alt="9ozoqbmouw" src="https://user-images.githubusercontent.com/54808/29915075-58c97936-8e43-11e7-9293-9fd7e06dcfa1.png">

When I run page with GUI When I enable show for Electron, then it displays fine.

I understand that this could be Electron issue, but hope to find answers here as well.

**Comment by TimNZ** [comment]
Since it works fine when the BrowserWindow is visible, it is definitely not a Nightmare issue.

**Comment by cupuyc** [comment]
Ok.
My **workaround** was to reduce the number of columns in ui-grid to avoid horizontal scroll to appear.
That helped me.
Closing, as might be electron pdf issue.
