### ISSUE TITLE
Emmiting an event before ending the instance

### ISSUE THREAD

**Issue by yatki** [segmentio/nightmare#1251]
Hey, I'm using nightmare for end to end user testing with ava.

Sometimes I wait for an element and element is not visible. Thus, I get a wait timeout exception. So far so good.

What i want to do is taking a screenshot of that moment before ending the instance. However, as soon as wait throws the exception, next steps are being skipped. 

[./node_modules/nightmare/lib/nightmare.js:336](https://github.com/segmentio/nightmare/blob/master/lib/nightmare.js)

```javascript
    // Immediately halt execution if an error has been thrown, or we have no more queued up steps.
    if (err || !item) return done.apply(self, arguments);
```

And when i get the error in catch statement, endInstance function is already being invoked and i can't get the screenshot.

Is there a work around for this? Or can we add hooks for getting the instance right before it's being closed.

Thanks.

**Comment by TimNZ** [comment]
Look at the complex example I posted in #1253 

You should be able to omit the .end() from the main chain and call it from .catch() and .then() when you finally need to end.

**Comment by yatki** [comment]
@TimNZ That's great. I worked for my case. Thank you very much.

For those who may need this, i solved this in my case, basically like this:

```javascript
nightmare
  .then(() => {
    done();
  })
  .catch((error) => {
    nightmare.screenshot(screenShotPath);
    nightmare.end()
      .then(() => { throw error; })
      .catch(done);
  });
```
