### ISSUE TITLE
unable to clear input field value when typing falsy value

### ISSUE THREAD

**Issue by davidkwan95** [segmentio/nightmare#1252]
This is similar to the issue at https://github.com/segmentio/nightmare/issues/810

I am unable to clear the input field when putting an empty string or falsy value inside the type or insert method, although the documentation says 
```
.type(selector[, text])  
Enters the text provided into the selector element.
Empty or falsey values provided for text will clear the selector's value.
```

**Comment by TimNZ** [comment]
This works:

```
nightmare
    .goto('http://google.com')
    .type('[name=q]','hi')
    .wait(1000)
    .type('[name=q]','')
    .wait(1000)
    .end()
    .then((result) => {
      console.log(result);
    })
```

**Comment by davidkwan95** [comment]
okay, seems like it's a problem with the site I'm trying to automate. it works fine with other sites
