### ISSUE TITLE
Proposed v3 

### ISSUE THREAD

**Issue by TimNZ** [segmentio/nightmare#1254]
I've just pushed WIP branch to my fork, which I propose triggers a bump to Nightmare v3.

https://github.com/TimNZ/nightmare/tree/in-process

I'm about a week away from committing a completed/tested version, as I did these changes for my own app that I need to release asap.

Major changes:
* Secure preload.js no longer exposing window.__nightmare #1060  (breaking change unless support for current and secure preload.js is retained via option switch)
* Support running inside an existing Electron process #1236 

Decisions to be made:
* Handling timeouts and 'killing' in-process runner instance
* Retention of insecure preload.js

Example of using inside an Electron process.
Note a seperate Electron process is not launched solving regularly raised pain of running Nightmare from a packaged Electron app.

```
const {app} = require('electron');
const Nightmare = require('../lib/nightmare');
const nightmare = Nightmare({ show: true,inProcess: true, openDevTools: true, executeJavaScriptSecure: true });

app.on('ready',() => {
  nightmare
    .goto('https://google.com')
    .type('[name=q]','xemware')
    .evaluate((selector) => {
      return document.querySelector(selector).value;
    },'[name=q]')
    .end()
    .then((result) => {
      console.log(result);
    })

})
```

I'd love feedback on the implementation, testing, creating tests, suggestions, help with updating README.

Having gotten pretty intimate with Nightmare working on this I'd be keen to be made a Collaborator to help work through the outstanding issues and on-going development.

**Comment by johnferro** [comment]
@TimNZ I'm interested in helping out on at least the secure javascript side of things (not as familiar with what you're trying to do in terms of having it run inside electron process).  I'd like to hear from @casesandberg or @ejcx on needing to keep the `window.__nightmare` functionality around or as the default.  As long as this changes the version to v3 I'd be in favor of getting rid of it completely and if someone needs that functionality they can add it back in a custom preload + extension.  In my opinion its definitely too severe of a vulnerability to leave as the default.

**Comment by TimNZ** [comment]
Changing it is easy and I have done it in a breaking way.

Even with the existing preload.js, sanitising what channels can be sent to would be an improvement, without breaking the current system, by implementing a wrapper around the ipc object.
This is for the default preload.js, so no-one who uses that cares how it's done anyway.

It only breaks for people who use their own custom preload, and my view on that is:
* They should be knowledgeable enough to fix that themselves if given a heads up.
* Can't be very common so not going to affect a lot of people
* Is declared an explicit breaking change for v3

**Comment by Samsinite** [comment]
Nice work! Took a look at your fork, we were looking at doing the exact same thing as you: running nightmare in an existing electron app. Currently, we are in research mode to determine if this tool might work for a project, if this tool is chosen, we'd definitely be putting in more research to help maintain opening nightmare inside of a existing electron process. At the moment though, I do have some feedback on some spots that seemed a little buggy.

First, `.end()` doesn't seem to work, instead the open window just hangs.

Neither does this:
```

**Comment by TimNZ** [comment]
I haven't pushed the latest commits in quite a while.
The project driving an in-process Nightmare is parked for a little while.

There's a lot of debug info in the current src so I can't push it now, and I've got other priorities.

I'll likely resume dev on it very early January.

One issue is running multiple chains on webview at the same time.
There appears to be a bug with Electron IPC messages getting routed/lost from the renderer process to main and back to host BrowserWindow renderer process (via ipc.sendToHost).

Performance tweaking would be last, though I'd be surprised if there was a meaningful real world difference - you'd have to define what 'slower' is.

**Comment by Samsinite** [comment]
Definitely saw the debug info, but for researching I wasn't too concerned about that. If we use it, we can always help with that. Thanks for putting the time into getting it where it is currently at.

**Comment by Samsinite** [comment]
I was stress testing it. Tried running 50 nightmare windows at the same time and it was really slow, promises even started timing out.

**Comment by Samsinite** [comment]
Out of curiosity (I haven't dug into the code), why is it communicating with the host webview instead of the `main` process?

**Comment by TimNZ** [comment]
I would say it will be useless for that.

The issue with Electron IPC that I spent quite a few hours trying to debug, tracing into Electron API code, may be a show stopper.  It would require an expert to figure out what is happening, either in my code, or inside Electron.

Single instance works fine.

More to say early Jan.

**Comment by matthewmueller** [comment]
Going to close this since most of the issues have been addressed. Thanks for the hard work @TimNZ!

**Comment by danielravina** [comment]
so is it possible to run Nightmare inside electron since https://github.com/segmentio/nightmare/releases/tag/3.0.0 ? If so, how?

**Comment by euandrei** [comment]
@danielravina I am curious of the same fact. Is there anything I am missing ? Where can we find details about the implementation / way to handle ?
