### ISSUE TITLE
Chaining? Help?

### ISSUE THREAD

**Issue by jagunosra** [segmentio/nightmare#1255]
Hi Everyone,

I want to achieve a chaining method for my test cases. Is this possible?

If yes How?

My structure is I want to run the nightmare using methods.

For example:

Function login(){

}

Function addrow(){

}

function deleterow(){

}
function runtest(){
//testcase1
login()
addrow()

//testcase2
login()
deleterow()

}

**Comment by airtoxin** [comment]
Answer is yes.
You can use [`nightmare.use(plugin)`](https://github.com/segmentio/nightmare#useplugin) method.

```js
function login(loginArg) {
  return function(nightmare) {
    return nightmare.goto(...).evaluate(...).wait(...)
  }
}

function runtest() {
  nightmare
    .use(login('userid', 'password'))
    .use(addRow())
}
```

**Comment by jagunosra** [comment]
I have tried to use the above but i got an error. 
fn is not a function

> runtest()
> function login(id,pass){
>   return function(nightmare){ 
>      return nightmare
>         .goto(baseUrl)
>         .wait('.login')                         // wait until the element with class .login is on the page (that means the page loaded)
>         .click('.login a')                      // click it to display login form "modal"
>         .wait('input[name=email]')              // wait until the email input is on the page, which means we are almost ready to fill it out
>         .wait(5000)                             // wait an additional second for the form entrance animation to complete
>         .type('input[name=email]', id)       // fill out email field
>         .type('input[name=password]', pass) // fill out password field
>         .click('button.auth0-lock-submit')      // click submit button
>         .wait(5000)  
>         .wait('#explorer-container')
>         .click('#explorer-container .row .nav-item .folder-expand-caret-right')  
>         .wait(5000)      
>         .click('#explorer-container > div.row > div.folder-nav > div:nth-child(2) > div > div:nth-child(2) > div:nth-child(5) > div.nav-item')
>         .wait('#explorer-container .row .folder-details')
>         .dblclick('#explorer-container > div.row > div.folder-details > div > div > div > div:nth-child(1)')
>         .wait(3000) 
>         .click('#nav-primary > li:nth-child(5) > a')
>         .wait(3000)        
>         .catch(function (err) {
>          throw (err instanceof Error ? err : new Error(err));
>           })
>   }
> }
> function addNewRowToolBar(){
>   nightmare
>   .click('#lineItemsContainer > div > div > div.data-table-controls > a.data-table-add-row.cello-ignore-clicks') //add new row
>   
> }
> 
> function runtest(){
> nightmare
> .use(login(email,password))
> .use(addNewRowToolBar())
> }

**Comment by airtoxin** [comment]
`nightmare.use()` method accepts the function that returns nightmare instance.
So your `addNewRowToolBar()` function should also return that.

**Comment by jagunosra** [comment]
I have tried adding the nightmare return but the electron didn't pop up? 

function login(id,pass){
  return function(nightmare){ 
     return nightmare
        .goto(baseUrl)
        .wait('.login')                         // wait until the element with class .login is on the page (that means the page loaded)
        .click('.login a')                      // click it to display login form "modal"
        .wait('input[name=email]')              // wait until the email input is on the page, which means we are almost ready to fill it out
        .wait(5000)                             // wait an additional second for the form entrance animation to complete
        .type('input[name=email]', id)       // fill out email field
        .type('input[name=password]', pass) // fill out password field
        .click('button.auth0-lock-submit')      // click submit button
        .wait(5000)  
        .wait('#explorer-container')
        .click('#explorer-container .row .nav-item .folder-expand-caret-right')  
        .wait(5000)      
        .click('#explorer-container > div.row > div.folder-nav > div:nth-child(2) > div > div:nth-child(2) > div:nth-child(5) > div.nav-item')
        .wait('#explorer-container .row .folder-details')
        .dblclick('#explorer-container > div.row > div.folder-details > div > div > div > div:nth-child(1)')
        .wait(3000) 
        .click('#nav-primary > li:nth-child(5) > a')
        .wait(3000)        
        .catch(function (err) {
         throw (err instanceof Error ? err : new Error(err));
          })
  }
}
function addNewRowToolBar(){
  return function(nightmare){  
  return nightmare
  .click('#lineItemsContainer > div > div > div.data-table-controls > a.data-table-add-row.cello-ignore-clicks') //add new row
  .catch(function (err) {
    throw (err instanceof Error ? err : new Error(err));
     })
     
  }
}

function runtest(){
  return function(nightmare){ 
    return nightmare
  .use(login(email,password))
  .use(addNewRowToolBar())
  .catch(function (err) {
    throw (err instanceof Error ? err : new Error(err));
     })
    }
}

runtest()
