### ISSUE TITLE
Feature Request: Option To Prevent Blur After Type

### ISSUE THREAD

**Issue by armordog** [segmentio/nightmare#1258]
I'd like to be able to call `Nightmare.type()` without Nightmare `blur`ing the field at the end.

My use case is a typeahead field. When the field loses focus, the dropdown collapses.

Ideally, I'd be able to pass an additional argument to `Nightmare.type` which causes `blurSelector` to be skipped. (https://github.com/segmentio/nightmare/blob/master/lib/actions.js#L264).

For now, I'm working around it like this:
```
.evaluate(() => {
                const el = document.querySelector('#some_id');
                el.focus();
                el.value = 'some input';
                el.dispatchEvent(new Event('input'));
            })
```

Thank you for Nightmare.

**Comment by TimNZ** [comment]
Hey @armordog 

Looks like maintenance on this awesome library has stalled or is at least sporadic.

I'm working on a fork #1236 and will be very actively maintaining/enhancing it as I'm using it in a commercial app about to enter beta.

There is a WIP 'in-process' branch you can reference in package.json 'timnz/nightmare#in-process' that adds support for disabling blur on .type/.insert.

https://github.com/TimNZ/nightmare/tree/in-process

Refer to Readme on 'blurInput' and updated description for .type and .insert

Provide feedback in my fork issues.

Hopefully I can get made a collaborator on here.

**Comment by matthewmueller** [comment]
Hi @armordog, given that this is a bit of an edge case, a custom action would work best here. In this example, I've created one called `input` that doesn't blur after:

```js
const Nightmare = require('nightmare')

main().catch(console.error)

async function main() {
  Input(Nightmare)

  const nightmare = Nightmare({ show: true })

  await nightmare.goto('https://google.com')
  await nightmare.input('#lst-ib', 'nightmare is')
  await nightmare.input('#lst-ib', ' awesome')
  await sleep(5000)
  await nightmare.end()
}

function sleep(ms) {
  return new Promise(res => setTimeout(res, ms))
}

function Input(Nightmare) {
  Nightmare.action(
    'input',
    function(name, options, parent, win, renderer, done) {
      parent.respondTo('input', function(value, done) {
        var chars = String(value).split('')

        function type() {
          var ch = chars.shift()
          if (ch === undefined) {
            return done()
          }

          // keydown
          win.webContents.sendInputEvent({
            type: 'keyDown',
            keyCode: ch
          })

          // keypress
          win.webContents.sendInputEvent({
            type: 'char',
            keyCode: ch
          })

          // keyup
          win.webContents.sendInputEvent({
            type: 'keyUp',
            keyCode: ch
          })

          // defer function into next event loop
          setTimeout(type, options.typeInterval)
        }

        // start
        type()
      })
      done()
    },
    function(selector, text, done) {
      // focus, type
      return this.evaluate_now(
        selector => document.querySelector(selector).focus(),
        () => this.child.call('input', text, done),
        selector
      )
    }
  )
}
```
