### ISSUE TITLE
Electron EOF Issue in Docker Container (Not XVFB related)

### ISSUE THREAD

**Issue by PWAckerman** [segmentio/nightmare#1262]
I have written a short nightmare script that executes perfectly on my local machine, but when I containerize it, I run into an issue with Electron. I have dockerized Nightmare plenty of times before, and am installing the requisite libraries and running the script with xvfb as is standard. However, once nightmare has queued its actions, I'm running into an EOF error from Electron, "EOF in backquote substitution".

```
Sun, 10 Sep 2017 17:14:58 GMT nightmare queueing action "wait"
Sun, 10 Sep 2017 17:14:58 GMT nightmare queueing action "wait"
Sun, 10 Sep 2017 17:14:58 GMT nightmare queueing action "evaluate"
Sun, 10 Sep 2017 17:14:58 GMT nightmare running
Sun, 10 Sep 2017 17:14:58 GMT electron:stderr /app/node_modules/nightmare/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron: 5: /app/node_modules/nightmare/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron: Syntax error: EOF in backquote substitution
Sun, 10 Sep 2017 17:14:58 GMT nightmare electron child process exited with code 2: undefined
```

Here is my Dockerfile, for reference:

```
  FROM node:6

  RUN apt-get update &&\
    apt-get install -y \
    xvfb \
    x11-xkb-utils \
    xfonts-100dpi \
    xfonts-75dpi \
    xfonts-scalable \
    xfonts-cyrillic \
    x11-apps \
    clang \
    libdbus-1-dev \
    libgtk2.0-dev \
    libnotify-dev \
    libgnome-keyring-dev \
    libgconf2-dev \
    libasound2-dev \
    libcap-dev \
    libcups2-dev \
    libxtst-dev \
    libxss1 \
    libnss3-dev \
    gcc-multilib \
    g++-multilib

  WORKDIR /app
  ADD package.json /app/
  RUN npm install
  RUN mkdir files
  ENV DEBUG=*
  ADD . /app

  CMD DEBUG=* xvfb-run --server-args="-screen 0 1024x768x24" node scheduler.js
```

**Comment by sweinertjr** [comment]
Have you added `node_modules` to your `.dockerignore` file? It looks as though you're trying to use the MacOS binary inside your docker container, which isn't going to work out very well!

**Comment by PWAckerman** [comment]
Y'know, I assumed at the time that that was the source of the issue, but couldn't justify to myself why NPM would be installing and/or using the MacOS binary as I was watching the output of NPM as the image was created. It's clear now that NPM was installing the correct binary, but `node_modules` was being overwritten by `ADD . /app` in the Dockerfile. Adding the `.dockerignore` worked. In the past, I had been building the image on an Ubuntu server over SSH, so there was no compatibility issue with the redundancy of both installing via NPM and copying `node_modules`. Will have to keep an eye out for this type of issue in the future! Thanks!
