### ISSUE TITLE
Nightmare Script

### ISSUE THREAD

**Issue by ivannluz** [segmentio/nightmare#1263]
Hello guys, I'm new using javascript and nightmare so,
I was trying to do a simple script , the script needs to click on all the links on the web page
and check if the response is 200.

This is my actual code:

var  Nightmare = require('nightmare');
  vo = require('vo'),
  nightmare = Nightmare({ show: true });

var run = function * () {
  var urls = ['https://intelius.com/dir/state'];
  
  for (var i = 1; i < 50; i++) { // loop for all the cities, 

    yield nightmare.goto('https://intelius.com/dir/state')
    .click('#pagecontent > div:nth-child(1) > div.large-12.small-12.margin-top > ul > li:nth-child('+i+') > a')    
    .then((gotoResult) => 
          {
       console.log(gotoResult.code); //prints out the HTTP status for the request
         });
       }
  }
  

vo(run)(function(err) {
  console.log(err);
});

My first idea was navigate to the web page and click all the links and check the status and then return to the index page but I my script fail because only the goto method has the method gotoResult in order to check if the page give me the status so My question if there is a way to just ask for the status after the script do the click in other link?

**Comment by TimNZ** [comment]
Use .evaluate to return array of all the links in the page you want to check and then use node net module or 'request' package to check the status of each url.

https://stackoverflow.com/a/19051457/1494940

Good/ambitious project for someone new to node/nightmare :)

```
nightmare
.goto(url)
.evaluate(() => {
   // return array of links 
})
.then((links) => {
    return Promise.all(array of promises for checking each link)
    .then(results) => {
         nightmare
               .end()
    })
})
```

**Comment by matthewmueller** [comment]
Hi @ivannluz, this should work:

```js
```
