### ISSUE TITLE
 error while loading shared libraries: libXss.so.1:

### ISSUE THREAD

**Issue by 1marty4sale** [segmentio/nightmare#1265]
I am getting the following error when trying to run nightmare on heroku:

` electron:stderr /app/node_modules/nightmare/node_modules/electron/dist/electron: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory`

Firstly, it looks like it is trying to load electron from the nightmare directory rather than the root node_modules.  From my past few hours of googling it seems like that shouldn't be the case - is that correct?

Secondly, any ideas as to how to fix it?

**Comment by 1marty4sale** [comment]
Sorry, seemed I didn't have the buildpacks installed correctly.  Reinstalled them and all is now working.

Thanks for Nightmare!

**Comment by SultanAbuGhazal** [comment]
I am facing the same issue. Quick question @1marty4sale, what buildpacks did you install and in what order?

**Comment by 1marty4sale** [comment]
From memory it was a heroku issue.  The Buildpacks weren't installing on a specific dyno.  When I tried creating a new one they installed fine.  Build pack order was from a tutorial which I can't seem to find anymore...


https://github.com/heroku/heroku-buildpack-apt
https://github.com/captain401/heroku-buildpack-xvfb.git
https://github.com/benschwarz/heroku-electron-buildpack.git
https://github.com/heroku/heroku-buildpack-nodejs.git
