### ISSUE TITLE
Support of proxy-pac-url

### ISSUE THREAD

**Issue by Khady** [segmentio/nightmare#1267]
I try to configure nightmare with the `--proxy-pac-url` switch. However, I don't manage to get something else than an error:

```
  nightmare:log Navigating: "http://lemonde.fr",
  nightmare:log             headers: [none],
  nightmare:log             timeout: 30000 +6ms
  nightmare:log did-start-loading [{}] +7ms
  nightmare:log did-fail-provisional-load [{},-131,"ERR_MANDATORY_PROXY_CONFIGURATION_FAILED","http://lemonde.fr/",true] +161ms
  nightmare:log did-fail-load [{},-131,"ERR_MANDATORY_PROXY_CONFIGURATION_FAILED","http://lemonde.fr/",true] +0ms
2017-09-21T05:54:03.813Z - info: http://lemonde.fr : error MANDATORY_PROXY_CONFIGURATION_FAILED during goto to http://lemonde.fr: 
{ message: 'navigation error',
  code: -131,
  details: 'ERR_MANDATORY_PROXY_CONFIGURATION_FAILED',
  url: 'http://lemonde.fr/' }
```

My pac file is very simple and works with chromium:

```javascript
function FindProxyForURL(url, host) {
  return "PROXY 127.0.0.1:10000;";
}
```

If I the proxy address in a `--proxy-server` switch, it works without problem.

I don't think the pac file is even loaded. Any idea? Electron is supposed to support proxy-pac-url: https://github.com/electron/electron/blob/master/docs/api/chrome-command-line-switches.md#--proxy-pac-urlurl

**Comment by Khady** [comment]
Support for proxy-pac-url seems to bome from this PR:
https://github.com/electron-archive/brightray/pull/123
https://github.com/electron/electron/issues/1599

Is it too "recent" for nightmare?

**Comment by Khady** [comment]
Here is how electron appears in my htop:
```
/home/louis/Code/p/v2/d/node_modules/electron/dist/electron /home/louis/Code/p/v2/d/node_modules/nightmare/lib/runner.js {"switches":{"force-device-scale-factor":1,"high-dpi-support":1,"ignore-certificate-errors":true,"proxy-pac-url":"file:///home/louis/Code/p/v2/d/built/proxy_pac.js"},"dock":false}```

**Comment by matthewmueller** [comment]
Hi @khady, did you try passing in the url via the switches here: https://github.com/segmentio/nightmare#switches ?

**Comment by matthewmueller** [comment]
Going to close this since this issue is getting stale. Please feel free to reopen if you're still running into this problem and have additional information for us :-)
