### ISSUE TITLE
networkRequest.abort()  issue?

### ISSUE THREAD

**Issue by niknickolas** [segmentio/nightmare#127]
Hi, I have one question. When I use the event handler resourceRequested, I get an error when calling the abort method of the object networkRequest
// Unhandled stream error in pipe.
Object #\<Object\> has no method 'abort'
Because the object networkRequest contains
{
objectName: ",
'destroyed(QObject*)': [Function],
'destroyed()': [Function],
'deleteLater()': [Function],
'abort()': [Function],
'changeUrl(QString)': [Function]
}

But even calling networkRequest\['abort()'\]() gets the error
Error: cannot call function of deleted QObject

Is there any other way to cancel the load unwanted files?

I use phantomJS v 1.9.8 and 1.9.0, node v 0.10.33 , ubuntu 14.04

**Comment by reinpk** [comment]
hmmmm, yes it looks like onResourceRequested actually has two functions that execute in different contexts.... https://github.com/sgentle/phantomjs-node#functionality-details and currently the function getting passed is executing in the external context not the phantomjs context.

**Comment by reinpk** [comment]
i've split it into two events, one that's triggered when on `resourceRequestStarted` that executes in the phantomjs context, and allows you to abort, change url, or adjust headers. `resourceRequested` will remain the same thing, executed in the external context.
