### ISSUE TITLE
print html to PDF : problems with table display in PDF

### ISSUE THREAD

**Issue by BigKongfuPanda** [segmentio/nightmare#1271]
Hi , when printing html to PDF,  there is a problem which is some th of a table displayed repeatedly inside the table, the repeated th would like to locate at any where in the table. There are two pictures as follow: 
![image](https://user-images.githubusercontent.com/16985024/30774586-7fa4b4a8-a04a-11e7-97da-dbdabffd0056.png)
![image](https://user-images.githubusercontent.com/16985024/30774593-b19bd5f4-a04a-11e7-9e57-093bd80812ce.png)

ps: my English is not so good, maybe I did not explain the problem very clearly, so if you have any thing want to ask me, please do not hesitate!

---------------------------------------------------------------
the config code is like this: 
![image](https://user-images.githubusercontent.com/16985024/31008384-8fad32a2-a4c9-11e7-9170-3b546754691c.png)

**Comment by matthewmueller** [comment]
hi @BigKongfuPanda, are you still having this problem? 

If so, could you please copy and paste your code so I can help you debug further?

**Comment by matthewmueller** [comment]
Going to close this since this issue is getting stale. Please feel free to reopen if you're still running into this problem and have additional information for us :-)
