### ISSUE TITLE
Error: Failed to find Electron v1.7.8 for linux-x64

### ISSUE THREAD

**Issue by wnxhaja** [segmentio/nightmare#1272]
I tried to install the nightmare on my local project and I get this error:

`Error: Failed to find Electron v1.7.8 for linux-x64 at https://github.com/electron/electron/releases/download/v1.7.8/electron-v1.7.8-linux-x64.zip
`

Which is correct since electron for linux is not yet supported in version 1.7.8
https://github.com/electron/electron/releases/tag/v1.7.8

Any suggestion?

**Comment by ergose** [comment]
In the same boat. Related to this: https://github.com/electron/electron/issues/10595

**Comment by wnxhaja** [comment]
This will probably take time. Should we do PR to change the version of nightmare's electron to ~1.6.X?
