### ISSUE TITLE
Did anyone experience docker killing process with nightmare? Comment has error, output etc

### ISSUE THREAD

**Issue by idchlife** [segmentio/nightmare#1276]
I have a process which uses nightmare to do some stuff, here is output of ctop:

![image](https://user-images.githubusercontent.com/4563032/30935542-afe0be5e-a3d9-11e7-8f03-54c9d5f16a41.png)

Right when nightmare tries do do stuff, creates instance of electron it dies like that:

![image](https://user-images.githubusercontent.com/4563032/30935694-1f198698-a3da-11e7-8d73-96c388bf62d9.png)

SIGINT

What could be the problem?

**Comment by matthewmueller** [comment]
hi @idchlife, are you still running into this issue? I'm not sure I'm quite following your issue:

Is the issue that docker is occasionally killing the node container?

**Comment by idchlife** [comment]
@matthewmueller actually I resolved this error in the topic somewhere here... Anyway, this issue is not relevant, for more info for those experiencing issue: do remember, you do not need using xvfb.startSync() manually, find the solution, it's out there. This issue was a long time ago and I can't at the moment find code but solution exists and it's on the internet.

**Comment by djalmaaraujo** [comment]
I have the same issue and I don't know how to fix now. Help? @idchlife

**Comment by idchlife** [comment]
@djalmaaraujo I can't actually remember things, but I would like to show several files I used.

This is entrypoint (basically .sh script) for my docker container for node with nightmare:

```bash
#!/usr/bin/env bash
set -e

# Start Xvfb
Xvfb -ac -screen scrn 1024x768x8 :9.0 &
export DISPLAY=:9.0

pm2-docker start pm2.config.js --only user_checker
```

this is part of process in pm2 config:

```javascript
module.exports = {
  /**
   * Application configuration section
   * http://pm2.keymetrics.io/docs/usage/application-declaration/
   */
  apps : [
    {
      name      : "user_checker",
      script    : "./dist/scripts/user-checker.js",
      // interpreter: "xvfb-run",
      watch: ["./dist"],
      ignore_watch : ["./node_modules", "./sessions"],
      max_restarts: 5,
      env: {
        "NODE_ENV": "dev",
        "DEBUG": "nightmare,electron:*",
        "DISPLAY": ":9.0"
      }
    },
  ],
};

```

I really hope this would help, since this part of an app works flawlessly!

**Comment by djalmaaraujo** [comment]
@idchlife I am not sure if I understood at all what you said. Here's my situation:

I run nightmare using `pm2` or `forever`, but when nightmare is about to end(), it launches the `SIGINT` signal, and this makes `pm2` or `forever` kill the process for both nightmare + the server running itself.

Makes sense to you? Is somehow related to this?

**Comment by idchlife** [comment]
@djalmaaraujo those env variable:

"DEBUG": "nightmare,electron:*"

will give debug output info about this

**Comment by djalmaaraujo** [comment]
@idchlife Let me paste the output for you (i am already using DEBUG):

This is the end of the log:

```bash
...
...
Fri, 08 Jun 2018 20:37:36 GMT nightmare:actions .evaluate() fn on the page
Fri, 08 Jun 2018 20:37:36 GMT nightmare:log did-frame-finish-load [{},true]
Fri, 08 Jun 2018 20:37:36 GMT nightmare:log did-finish-load [{}]
Fri, 08 Jun 2018 20:37:36 GMT nightmare:log page-favicon-updated [{},["https://www.sifge.caixa.gov.br/x.ico"]]
Fri, 08 Jun 2018 20:37:36 GMT nightmare:actions .pdf()
Fri, 08 Jun 2018 20:37:36 GMT nightmare:actions .pdf() captured with length 82243
Fri, 08 Jun 2018 20:37:36 GMT nightmare electron child process exited with code 0: success!
```

As you can see: this part: `Fri, 08 Jun 2018 20:37:36 GMT nightmare electron child process exited with code 0: success!` is sending a kill signal. So.... `pm2` or `forever` will understand that you want to kill their process.

**Comment by djalmaaraujo** [comment]
@idchlife I was able to make it work by running the process using unix, not pm2 or forever. But that's not the best solution or what I wanted.

This works because the signal ends just for the node process.

```bash
DEBUG=* xvfb-run -a --server-args=\"-screen 0 1024x768x24\" node queueConsumer/index.js 2>&1 > output.log &
```

**Comment by idchlife** [comment]
@djalmaaraujo I can't quiet grasp the problem you facing. It seems you get your nightmare process do things you want and then it dies peacefully? What seems to be the problem?

**Comment by djalmaaraujo** [comment]
@idchlife Here's the situation:

- script.js is a file that pulls something from a database and use nightmare. (Imagine sript.js as a `setInterval() with a command to run `take-pdf.js`)
- I need something to put my script.js to run in the background (linux/aws)
- I decided to use `pm2` or `forever`, ok?
- My script.js, calls another script called `take-pdf.js` with nightmare commands to access 1 page and print a pdf.
- script.js runs perfectly and generates the pdf using `take-pdf.js`
- But when we call `nightmare.end()` inside of `take-pdf.js`, Electron sends a KILL signal, and this signal is also passed to `pm2`/`forever`.
- `pm2`/`forever` kills the "background process" of script.js.

Is that simple to understand? :)
