### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by allenhwkim** [segmentio/nightmare#1277]
I followed README.md, and I got the above error.

Should it be this?
```
var Nightmare = require('nightmare');
```
instead of
```
import Nightmare from 'nightmare';
```

**Comment by gtleal** [comment]
Precisely! @allenhwkim

**Comment by bm-stschneider** [comment]
or you have to use babel-cli -> babel-node

**Comment by lai32290** [comment]
This issue probably is not reference `Nightmare`, but is about Node.

**Comment by epleterte** [comment]
This issue _is_ about Nightmare documentation, though. The Usage section says to run the exampls js with `node`, which doesn't work (out of the box). I'd expect a hint about babel, or I'd expect the example to use `require` instead of `import` (so that the example works).

**Comment by lai32290** [comment]
@epleterte , make sense, I agree with your point.

**Comment by iblessedi** [comment]
can anybody post a code which can run the Nightmare?

**Comment by lai32290** [comment]
@iblessedi I created a example for you.

https://www.pastiebin.com/5a3cf122bc0bf

**Comment by iblessedi** [comment]
Thank you.

**Comment by matthewmueller** [comment]
Hey folks, sorry for the confusion there, I just updated the examples to make sure they're runnable.
