### ISSUE TITLE
Using Nightmare in a Loop in a Promise .then()

### ISSUE THREAD

**Issue by TomAshley303** [segmentio/nightmare#1285]
I've been trying to get this working for a day now. I need to do something like this:

```
let keyword = 'horror games';
let kwOptions = {
    qs: {
        query: keyword,
    },
    url: "https://api.example.com/",
    json: true
};
rp(kwOptions)
    .then(function(relKeywords){
        console.log(relKeywords[1]);
        relKeywords[1].forEach(function (element) {
            console.log('searching for: ' + element);
            nightmare.evaluate(function() {
                document.querySelector('input[cloom-label="query"]').setAttribute('value', ''); // Clear search box
            });
            nightmare.type('input[cloom-label="query"]', ' ' + element + '\u000d');
            nightmare.click('span._5d a');
            nightmare.wait(5000)
        });
    })
    .catch(function(err){
        console.log("Couldn't get keywords: "+err);
    });
```

I'm trying to work with a result from `request-promise` and then loop through those results and work on them. If I use code like this, it iterates through all the nightmare actions really fast without waiting for them to finish. I can't use yield in .then(). I keep running into problems like this where I can't use `yield` and things go wrong.

**Comment by TomAshley303** [comment]
An answer was given to me here but I feel like it could have been simpler: https://stackoverflow.com/a/46578051/1390723

**Comment by entrptaher** [comment]
Can you give me the actual api link, so I can provide you the answer with some working screenshots? The answer is pretty simple actually. You just need to make sure all actions are running one after another in the loop.

Otherwise, you can follow this example.
```
let vo = require('vo');
var Nightmare = require('nightmare');
let nightmare = Nightmare();

var run = function* () {
    var urls = ['http://www.yahoo.com', 'http://example.com', 'http://w3c.org'];
    var titles = [];
    for (var i = 0; i < urls.length; i++) {
        var title = yield nightmare.goto(urls[i])
            .wait('body')
            .title();
        titles.push(title);
    }
    return titles;
}

vo(run)(function (err, titles) {
    console.dir(titles);
});
```

**Comment by matthewmueller** [comment]
As @entrptaher posted, I'd definitely recommend using async/await or generators for anything complicated.

FWIW, there's another example of doing this in this issue: #1372
