### ISSUE TITLE
.click or .wait issue?

### ISSUE THREAD

**Issue by paulsez** [segmentio/nightmare#129]
Hello @reinpk,

I'm trying a very simple test but the result is not what I've expected.

var Nightmare = require('nightmare');
new Nightmare()
.goto('http://www.mypage.com/login')
.type('input[name=username]', 'myusername')
.type('input[name=password]', 'mypassword')
.click('input.button')
.wait()
.screenshot('test.jpg') 
.run(function(err, Nightmare){
    console.log('Done.');
});

I suppose that the generated screenshot should be of the page after login. Instead I only get the Done message and a screenshot of the login page.
I've tried using wait with selector (div from the landing page after login process) but the result is the same.
Any advice?

Thank you!

**Comment by reinpk** [comment]
i tried adding some actions that cause new pages to load, but the screenshots seem to work for me....

```js
var Nightmare = require('nightmare');

new Nightmare()
  .goto('https://segment.com')
  .click('[href="/docs"]')
  .wait()
  .screenshot('test.png')
  .run();
```

29 seconds for the next page load seems really long?
