### ISSUE TITLE
How to scroll specific element?

### ISSUE THREAD

**Issue by iamdubx** [segmentio/nightmare#1292]
For example, I want to execute this 

```js
document.querySelector('.PermalinkOverlay').scrollTo(0, 1000)
```
How it can be done? It's just one line in JS. All this evaluated stuff seems so overkill for such task. Is there any other way?

**Comment by iamdubx** [comment]
I tried this, but got an error

```js
Nightmare.action('scrollOverlay', function (selector, done) {
  this.evaluate_now((selector) => {
    document.querySelector(selector).scrollTo(0, 1000)
  }, done, selector)
})
```
`document.querySelector(...).scrollTo is not a function`

**Comment by garibay** [comment]
Why not something like:

```
let coordinates = yield nightmare.evaluate(() => {
    let target = document.querySelectorAll('.PermalinkOverlay');
    if (target !== null && target !== undefined  && target.length) {
        return [target[0].offsetTop, target[0].offsetLeft];
    }
});
```
`yield nightmare.scrollTo(coordinates[0], coordinates[1]);`

Or I suppose the same method could be used to do it all from within the `evaluate` call.

**Comment by matthewmueller** [comment]
Thanks @garibay, that would work. Another option would be to do it using `evaluate`:

```js
await nightmare.evaluate(selector => {
  document.querySelector(selector).scrollTo(0, 1000)
}, '.PermalinkOverlay')
```
