### ISSUE TITLE
Does not select element

### ISSUE THREAD

**Issue by danielsalles** [segmentio/nightmare#1293]
```js
const Nightmare = require('nightmare')
const nightmare = Nightmare({ show: true, executionTimeout: 10000, openDevTools: true })

nightmare
.goto('https://www.jucesponline.sp.gov.br/BuscaAvancada.aspx')
.type('#ctl00_cphContent_frmBuscaAvancada_txtDataAberturaInicio', '10/10/2017')
.type('#ctl00_cphContent_frmBuscaAvancada_txtDataAberturaFim', '10/10/2017')
.select('#ctl00_cphContent_frmBuscaAvancada_ddlTipoEmpresa', 21)
.click('#ctl00_cphContent_frmBuscaAvancada_btPesquisar')
.wait(2000)
.wait('#ctl00_cphContent_gdvResultadoBusca_gdvContent')
.evaluate(() => {
   return document.getElementById('ctl00_cphContent_gdvResultadoBusca_gdvContent')
})
.then(d => console.log('return: ', d))
.catch(err => console.error('ERROR: ', err))
```
`return null`

![return to return](https://image.ibb.co/bUuFow/Captura_de_tela_de_2017_10_13_09_49_15.png)

But when change `return document.getElementById('ctl00_cphContent_gdvResultadoBusca_gdvContent')` to `console.log(document.getElementById('ctl00_cphContent_gdvResultadoBusca_gdvContent'))`

![return to console.log](https://image.ibb.co/eWbZgG/Captura_de_tela_de_2017_10_13_09_46_04.png)

**Comment by matthewmueller** [comment]
Hi @danielsalles, I think the problem is that you're trying to return a DOM node, rather than a property on a DOM node. Since evaluate sends data across processes, we can't return complex objects like that.

The website you provided isn't loading for me, but I think you can fix your problem with something like this instead:

```js
await nightmare.evaluate(() => {
  return document.getElementById('content').nodeName
})
```
