### ISSUE TITLE
Allow listening for `end` event

### ISSUE THREAD

**Issue by keithkml** [segmentio/nightmare#1301]
I'd like to automatically save screenshots after every test. We already have a `createNightmare` helper function which sets window size and injects some HTTP headers. So a nice way to save screenshots would be for that helper function to add a listener for when `end()` is called call, right before Nightmare terminates the Electron instance.

Looking at the Nightmare source code, it appears that there's no way to listen for `end`, and it seems risky to override `end` itself.

**Comment by matthewmueller** [comment]
Hi @keithkml, I think this would be a bit race-y unless we also added flow control in that `end` event.

I'd recommend an `afterEach` function:

```js
const Nightmare = require('nightmare')
const assert = require('assert')

describe('google', () => {
  let nightmare

  beforeEach(async () => {
    nightmare = Nightmare({ show: false })
  })

  afterEach(async () => {
    const screenshot = await nightmare.screenshot()
    console.log(screenshot)
    await nightmare.end()
  })

  it('should check the title', async function() {
    this.timeout('10s')

    await nightmare.goto('https://google.com')

    // test the title
    const title = await nightmare.title()
    assert.equal(title, 'Google')
  })
})
```

Does that work for you?

**Comment by keithkml** [comment]
Unfortunately we don't use Jasmine or whatever that is :) We use Tape which does not have setup/teardown methods.

What kind of race condition are you worried about?

**Comment by matthewmueller** [comment]
Haha, it's mocha. Sorry I should have been more clear :-)

The race I'm talking about is between the screenshot action and cleaning up. Something like:

```js
nightmare.on('end', function() {
  const buf = nightmare.screenshot()
  await fs.writeFile("screen.png", buf)
})

await nightmare.end()
```

In this example, `nightmare.end()` would kill the process before the screenshot has finished writing. Given that you're using tape, I'd probably create a small wrapper function. I'm not too familiar with tape, so this might be a bit off but something like this:

```js

const Nightmare = require('nightmare')
const assert = require('assert')

// your tests
function TestGoto(tape) {
  test(tape, async nightmare => {
    await nightmare.goto('https://google.com')
    assert.equal('Google', await nightmare.title())
  })
}

// test helper
async function test(tape, fn) {
  const nightmare = Nightmare({ show: false })
  let err

  // don't let failed assertion kill the node process
  try {
    await fn()
  } catch (e) {
    err = e
    tape.fail(err)
  }

  // take a screenshot either way
  const buf = await nightmare.screenshot()
  await fs.writeFile('screenshot.png', buf)
  await nightmare.end()

  // finally fail or pass
  err ? tape.fail(err) : tape.pass()
}
```

**Comment by matthewmueller** [comment]
Going to close this since this issue is getting stale. Please feel free to reopen if you're still running into this problem and have additional information for us :-)
