### ISSUE TITLE
General query - what are common test assertions used?

### ISSUE THREAD

**Issue by kensoh** [segmentio/nightmare#1302]
Hi Maintainers and guys, may I check from you what are common assertions that you use in your test automation? Eg check that element contains text, check element exists etc. Crowdsourcing inputs for test assertions support for a personal project. This is not an issue, please feel free to close if irrelevant.

In that project I made a wrapper around CasperJS but as CasperJS has no support for visible / headless Chrome, test assertions won't work. Working to address that in the personal project, for some basic range of assertion scenarios to work with Chrome.

**Comment by matthewmueller** [comment]
Hi @kensoh, I think it's easiest to keep things simple, I'd recommend `assert`:

```js
const Nightmare = require('nightmare')
const assert = require('assert')

describe('google', () => {
  it('should check the title', async function() {
    this.timeout('10s')

    const nightmare = Nightmare({ show: false })
    await nightmare.goto('https://google.com')

    // tests
    const title = await nightmare.title()
    assert.equal(title, 'Google')
  })
})
```

**Comment by kensoh** [comment]
Hi @matthewmueller thanks for your reply, noted! 😃
