### ISSUE TITLE
nightmare electron child process exited with code 1: general error - you may need xvfb

### ISSUE THREAD

**Issue by idchlife** [segmentio/nightmare#1305]
I know this issue was "kinda" already posted, but there is situation when I have everything needed for electron to run with xvfb (as I see it) and still electrons shuts down asking for xvfb.
I even started writing "new Xvfb xvfb.startSync() ... ... xvfb.StopSync()" everywhere but still, some processes shuts down with "you need xvfb" error.

This is my dockerfile config for installation of all needed packages for electron to run with xvfb.

Am I missing something?

```Dockerfile
FROM node:8.3.0

RUN apt-get update

# Installing the packages needed to run Nightmare
RUN apt-get install -y \
  xvfb \
  x11-xkb-utils \
  xfonts-100dpi \
  xfonts-75dpi \
  xfonts-scalable \
  xfonts-cyrillic \
  x11-apps \
  clang \
  libdbus-1-dev \
  libgtk2.0-dev \
  libnotify-dev \
  libgnome-keyring-dev \
  libgconf2-dev \
  libasound2-dev \
  libcap-dev \
  libcups2-dev \
  libxtst-dev \
  libxss1 \
  libnss3-dev \
  gcc-multilib \
  g++-multilib
```

It will be very convenient of course to use nightmare without explicitly starting and stopping xvfb everytime. Especially when there is huge logic behind nightmare doing things separated into methods.

**Comment by asanchezgiraldo** [comment]
I am also getting this error intermittently.

```Wed, 22 Nov 2017 06:01:32 GMT nightmare queueing action "viewport"
Wed, 22 Nov 2017 06:01:32 GMT nightmare running
Wed, 22 Nov 2017 06:01:39 GMT nightmare electron child process exited with code 1: general error - you may need xvfb
ERROR The Electron 1.8.1 / Linux 0.0.0 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.

Type "testcafe -h" for help.
Wed, 22 Nov 2017 06:03:30 GMT nightmare electron child process not started yet, skipping kill.
/bin/xvfb-run: line 186: kill: (29432) - No such process
Build step 'Execute shell' marked build as failure
```

I am running my test using testcafe version 0.17.1 with nightmare as a browser in a Centos box

```
 Running tests in:
 - Electron 1.8.1 / Linux 0.0.0
```

**Comment by zwtan** [comment]
I've CentOS installed, but doesn't have xvfb for this purpose. Have installed the missing dependency as below to resolve my issue. Mainly caused by Electron and Nightmare/CentOS

**Packages to be installed**
sudo yum groupinstall "Development Tools"
sudo yum install gtk+-devel gtk2-devel

sudo yum install libasound.so.2 libXv.so.1 libXss.so.1 libSM.so.6 libXi.so.6 libXrender.so.1 libXrandr.so.2 libfreetype.so.6 libfontconfig.so.1 libz.so.1 libgthread-2.0.so.0 libstdc++.so.6 libQtDBus.so.4
libQtGui.so.4 pulseaudio-libs.i686

sudo yum install pango.x86_64 libXcomposite.x86_64 libXcursor.x86_64 libXdamage.x86_64 libXext.x86_64 libXi.x86_64 libXtst.x86_64 cups-libs.x86_64 libXScrnSaver.x86_64 libXrandr.x86_64 GConf2.x86_64 alsa-lib.x86_64 atk.x86_64 gtk3.x86_64 -y

**Comment by rpascal** [comment]
@idchlife where you able to get this working? I am having this issue appear on and off.

**Comment by k1r0s** [comment]
:hand:  @idchlife

**Comment by k1r0s** [comment]
So ... yeah: `nightmare electron child process exited with code 1: general error - you may need xvfb`

It seems like there should be an alternative for running headless browser testing.. Why do we have to install electron to do so? Lynx!?!?!?!

**Comment by k1r0s** [comment]
Gonna try PhantomJS

**Comment by rpascal** [comment]
@k1r0s take a look at puppeteer I like it a lot. Its similar to nightmare 
https://github.com/GoogleChrome/puppeteer

**Comment by k1r0s** [comment]
https://hub.docker.com/r/jribar/node-phantomjs/

![image](https://user-images.githubusercontent.com/6052309/36181888-222130f6-1127-11e8-8ca6-8556b025c661.png)

:1st_place_medal:

**Comment by k1r0s** [comment]
@rpascal Yeah! sounds good. I'll try to deal with phantom first. But definetly we need to look up alternatives :)

**Comment by matthewmueller** [comment]
Hey folks, that error doesn't point to much, it's a generic error, but I think I know the reason you're seeing it: you need to make sure to end nightmare **before** you close the xvfb server.

I just posted another example on #224 based on this issue that should resolve your issues.
