### ISSUE TITLE
Intercept all request

### ISSUE THREAD

**Issue by luanpotter** [segmentio/nightmare#1308]
Hey,

I was wondering if there was an easy way to intercept all requests, that is:

 * all request made directly via `.goto('url')`
 * all requests made by the browser thereafter, like images it fetched, <script> tags, css, anything
 * all requests made via AJAX (i.e., `XmlHttpRequest`) by the pages

That is, I want to intercept all request that would show up in the Network tab of Chromium.

By intercept I mean read all details, allow or disallow the request, if allowed, tamper the response, if disallowed, provide a redirect/proxy or fixed mock or response.

There seems to be a few issues with similar topics around, but none seem to provide a possible mock for all request.

**Comment by SergeyYermak** [comment]
Any progress on this? I just need to view a request body.

**Comment by matthewmueller** [comment]
Yep you can do that with custom actions. Here's an example to see the header details and optionally cancel requests:

```js
var Nightmare = require('nightmare')

main().catch(console.error)

async function main() {
  // define a new action
  Nightmare.action(
    'onBeforeSendHeaders',
    //define the action to run inside Electron
    function(name, options, parent, win, renderer, done) {
      win.webContents.session.webRequest.onBeforeSendHeaders((details, cb) => {
        // call our event handler
        parent.call('onBeforeSendHeaders', details, res => {
          res ? cb(Object.assign({}, res)) : cb({ cancel: false })
        })
      })
      done()
    },
    function(handler, done) {
      // listen for "onBeforeSendHeaders" events
      this.child.respondTo('onBeforeSendHeaders', handler)
      done()
    }
  )

  const nightmare = Nightmare({ show: true })

  // start listening
  await nightmare.onBeforeSendHeaders((details, cb) => {
    console.log(details.headers)
    cb({ cancel: false })
  })

  await nightmare.goto('https://google.com')

  await nightmare.end()
}

function sleep(ms) {
  return new Promise(res => setTimeout(res, ms))
}
```

In that same vein, there's a bunch of other events you can listen to as well: https://github.com/electron/electron/blob/master/docs/api/web-request.md

All of these events would follow the same flow as the example above.

**Comment by stphane** [comment]
Interesting @matthewmueller, thank you, what if I want nightmare to visit two different URLs but still be listening to this event ? _(Given the same routine should be executed whatever the URL is.)_
→ Should `nightmare.onBeforeSendHeaders(…)` be called right before every single `nightmare.goto(…)` ?  
→ Or should it be executed at most once before all calls ? ().

Like does the following code make sense ?
```
// Register event handler
await nightmare.onBeforeSendHeaders(details, cb) =>{
    // Console.log('Log same thing every time a webrequest is about to happen and for every site I visit');
});

// For every URL, wait 5 seconds so "onBeforeSendHeaders" handler has a chance to intercept some webrequests.
await nightmare.goto('http://example.com').waitms(5000);
await nightmare.goto('http://example2.com').waitms(5000);
```
