### ISSUE TITLE
Browser does not want to start

### ISSUE THREAD

**Issue by punkkk** [segmentio/nightmare#1309]
Hello!
Why my js ends without any actions if i write something like
` this.proxyNightmare.authentication(login, password)
            .goto('https://www.maxbet.com') `
But if i use:
` this.proxyNightmare.authentication(login, password)
            .goto('https://www.maxbet.com')
            .then() `
it's okay. I've spent a hour to realize it. :(

**Comment by knoxcard** [comment]
This is because it returns a Promise. Read up on Javascript Promises.

**Comment by punkkk** [comment]
so what the different between handled promise or not? i can put some commands like 
```             .goto(config.url)
            .type('#txtID', config.urlLogin)
            .type('#txtPW', '')
            .type('#txtPW2', config.urlPassword)
            .click('.somebtnselector')
            .wait(2500)
            .inject('js', './something.js')
            .wait(8500)
```
And if i didnt type `.then()` or `await` it will not work  it will not do anything.

**Comment by TimNZ** [comment]
Only .end() and .then() trigger the action queue to be processed.

**Comment by matthewmueller** [comment]
Thanks @TimNZ, I think you've answered @punkkk's question
