### ISSUE TITLE
Multithreading with nightmarejs

### ISSUE THREAD

**Issue by MakoMakox** [segmentio/nightmare#131]
I'm looking to make multiple instances of nightmare and running some tests on different websites in same time. I tried using jxcore for multithreading and nightmarejs but i was unsuccessful. Then I tried using synchronize.js (http://alexeypetrushin.github.io/synchronize/docs/index.html) and I was successful but it used the same instance of nightmarejs, I don't know why. Does someone know a good approach on this ? Thank you for your time guys :)

**Comment by samuelmeireles** [comment]
Did you found a solution?

**Comment by MakoMakox** [comment]
I managed to make it run In a multithread, I'm working on it really. I will post as soon as I have a ncie written slution. If anynone has progress on this I'm only ears.

**Comment by samuelmeireles** [comment]
Look at this https://github.com/Buzzvil/ghost-town
