### ISSUE TITLE
My webpage isn't loading when running the test (Ubuntu)

### ISSUE THREAD

**Issue by RejinR** [segmentio/nightmare#1310]
I was just trying out nightmare js and it seems like my wepage isn't loading for some reason. The title of the window and all changes according to my webpage, but nothing is shown on screen.
I checked out the network calls and it looks like some the chunked js files are not loading.. Network call is pending.
I then put up the same website in a virtual box and it worked.. I did a few tests. The next day, i got the same issue for the webpage on the virtual box. Can't figure out what's going wrong.

`const Nightmare = require('nightmare');

const nightmare = Nightmare(
  {
    show: true,
    width: 1600,
    height: 900
  }
);

nightmare
  .goto('http://localhost:3000')
  .wait(1000)
  .type('#root_demographics_givenName', 'Mark')
  .type('#root_demographics_familyName', 'John')
  .type('#root_demographics_dob', '18041994')
  .select('#root_demographics_gender', 'M')
  .type('#root_personAttributes_iKad', '58492839')
  .type('#root_personAttributes_mobile', '3473483423')
  .type('#root_personAttributes_email', 'reojr@ijfe.com')
  .select('#root_visitAttributes_visitingDepartment', 'Ortho')
  .select('#root_visitAttributes_userType', 'Cash')
  .wait(3000)
  .end()
  .then(function (result) {
    console.log(result)
  })
  .catch(function (error) {
    console.error('Error:', error);
  });`

**Comment by matthewmueller** [comment]
Hi @RejinR, sorry for the delay. Are you still having this problem?

If so, are you running ubuntu through virtualbox? And are you using xvfb?

**Comment by matthewmueller** [comment]
Going to close this since this issue is getting stale. Please feel free to reopen if you're still running into this problem and have additional information for us :-)
