### ISSUE TITLE
Nightmare continues on before meta redirect happens

### ISSUE THREAD

**Issue by jimmaay** [segmentio/nightmare#1313]
Code that goes to a page that gets redirected through a meta redirect like

`<meta http-equiv="refresh" content="0; url=redirect.html">`

the code continues past goto right after the page loads but before redirecting. Nightmare should probably act as if a redirect happened - e.g. 301/302.

**Comment by TimNZ** [comment]
Reasonable to expect that.

You could add a .wait(<seconds>) to the action chain after the .goto

Nightmare does no parsing of page content to detect this.

.goto() ends when Electron says the page has finished loading, and the next nightmare action gets executed.

The meta redirect will be executed after page finished loading event.

**Comment by matthewmueller** [comment]
Oh man, haven't seen one of those tags in awhile 😅 

@TimNZ is right, Nightmare does no parsing of page content to detect this and from an HTTP standpoint this would be a `200 OK` response.

I think your best bet is to wait for some feature on the `redirect.html` page. Here's an example detecting that the `document.location.pathname` is `/redirect.html`.

```js
const Nightmare = require('nightmare')
const express = require('express')
const http = require('http')

main().catch(console.error)

async function main() {
  const app = express()
  const server = await Server(app)

  app.get('/', (req, res) => {
    res.send(`
      <!doctype>
      <html>
        <head>
          <meta charset="UTF-8">
          <meta http-equiv="refresh" content="0; url=redirect.html">
          <title>1st Page</title>
        </head>
        <body>redirecting soon</body>
      </html>
    `)
  })

  app.get('/redirect.html', (req, res) => {
    res.send(`
      <!doctype>
      <html>
        <head>
          <meta charset="UTF-8">
          <title>2nd Page</title>
        </head>
        <body>redirected!</body>
      </html>
    `)
  })

  const nightmare = Nightmare({ show: true })

  await nightmare.goto(server.url, '/')
  await nightmare.wait(() => {
    return document.location.pathname === '/redirect.html'
  })

  await nightmare.end()
  await server.close()
}

async function Server(handler) {
  const server = await new Promise((res, _rej) => {
    var s = http.createServer(handler)
    s.listen(0, 'localhost', function() {
      res(s)
    })
  })

  const address = server.address()
  return {
    url: `http://${address.address}:${address.port}`,
    close: function() {
      return new Promise((res, _rej) => server.close(res))
    }
  }
}
```
