### ISSUE TITLE
Issues with promise returns.

### ISSUE THREAD

**Issue by legraphista** [segmentio/nightmare#1314]
Given the following code, here are some examples where nightmare returns as `undefined`
```js
const Nightmare = require('nightmare'); // 2.10.0

(async () => {
  const n = await Promise.resolve(new Nightmare());
  console.log(n);  // -> undefined
})();

Promise.resolve(new Nightmare()).then(x => console.log(x)); // -> undefined

(async () => { 
  const n = new Nightmare(); 
  await n.goto('https://github.com'); 
  return n;
})().then(console.log) // -> undefined
```

**Comment by legraphista** [comment]
As a workaround, it can be encapsulated in an object before returning from an async function: 
```js
(async () => { 
  const n = new Nightmare(); 
  await n.goto('https://github.com'); 
  return { n };
})().then(({ n }) => console.log(n)) // -> Nightmare { ...
```

**Comment by matthewmueller** [comment]
Hmm, that is quite odd. I'm not sure what's causing that.  From my own testing:

```js
const Nightmare = require('nightmare')

function Test() {
  if (!(this instanceof Test)) return new Test()
}

Promise.resolve(new Test()).then(v => console.log('Test', v)) // Test Test { }
Promise.resolve(new Nightmare()).then(v => console.log('Nightmare', v)) // Nightmare undefined
```

Out of curiosity, what's the use case here? The only thing I can think of is wanting to wait for electron to start, but `new Nightmare()` wouldn't do that.

**Comment by matthewmueller** [comment]
Going to close this since this issue is getting stale. Please feel free to reopen if you're still running into this problem and have additional information for us :-)

**Comment by legraphista** [comment]
Hi @matthewmueller!
I'm sorry, I must have missed your notification.
Here is a practical example:

```js
const Nightmare = require('nightmare'); // @latest
const assert = require('assert')

// generate a nightmare window based on some setup
const makeNightmareWindow = async () => {
  const n = new Nightmare({
  	width: 720,
  	height: 1280,
  	show: true
  }); 

  // make some app specific setup 
  await n.useragent('my fancy UA')
  await n.goto('https://github.com'); 	

  return n;
}

// bootstrap async code
(async () => { 
  const myNightmare = await makeNightmareWindow();
  console.log('myNightmare is:', typeof myNightmare);
  assert(myNightmare instanceof Nightmare, 'Where did it go?');

  await n.evaluate(`(() => { alert('hello world'); })()`); 

  await n.end();
  
})().catch(console.error) 
```

As expected, a window opens and navigates to github.com, but then it fails at the `assert`:
```js
> myNightmare is: undefined
> { AssertionError [ERR_ASSERTION]: Where did it go?
    at __dirname (/private/tmp/index.js:22:3)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' }
```

**Comment by matthewmueller** [comment]
Ahh okay, I got it now. This is one of the downsides of using ["thenables"](https://promisesaplus.com/#point-7) here: https://github.com/segmentio/nightmare/blob/6fa76b5679280f6b7f7b70b75473fabc0b7ace14/lib/nightmare.js#L578-L592

Basically await will implicitly call that `.then` function until there's nothing left in the queue and it returns undefined. I wish we could return `this`, but unfortunately that results in an ∞ loop of promises then-ing.

**Comment by legraphista** [comment]
Ah, I see. That's unfortunate. Well, at least we have the workaround 😄
