### ISSUE TITLE
Unexpected end of JSON input while parsing near '...smB98GZzkf6ZRNn6N8/Ym'

### ISSUE THREAD

**Issue by reggi** [segmentio/nightmare#1321]
im getting error on install

569 http fetch GET 304 https://registry.npmjs.org/@types%2fnode 31ms (from cache)
570 silly fetchPackageMetaData error for @types/node@^7.0.18 Unexpected end of JSON input while parsing near '...smB98GZzkf6ZRNn6N8/Ym'
571 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...smB98GZzkf6ZRNn6N8/Ym'
571 verbose stack     at JSON.parse (<anonymous>)
571 verbose stack     at parseJson (/Users/treggi/.nvm/versions/node/v9.2.0/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/node_modules/json-parse-better-errors/index.js:7:17)
571 verbose stack     at consumeBody.call.then.buffer (/Users/treggi/.nvm/versions/node/v9.2.0/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/body.js:96:50)
571 verbose stack     at <anonymous>
571 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
572 verbose cwd /Users/treggi/Downloads/nightmare-2.10.0
573 verbose Darwin 16.7.0
574 verbose argv "/Users/treggi/.nvm/versions/node/v9.2.0/bin/node" "/Users/treggi/.nvm/versions/node/v9.2.0/bin/npm" "i"
575 verbose node v9.2.0
576 verbose npm  v5.5.1
577 error Unexpected end of JSON input while parsing near '...smB98GZzkf6ZRNn6N8/Ym'
578 verbose exit [ 1, true ]

**Comment by matthewmueller** [comment]
I think this is a problem with NPM/network conditions
