### ISSUE TITLE
Nightmare is not able to open Whatsapp web

### ISSUE THREAD

**Issue by lai32290** [segmentio/nightmare#1323]
I tried to open Whatsapp web by `Nightmare`, but it's keeping initial loading, it's not able to show up the conversation list and QR code.

I checked the browser's console, but there has no any error.

Someone had same problem? Should I add some option to let it work?

**Comment by blindhover** [comment]
nightmare's default preload has prevent 'onunload' and 'onbeforeunload' from being set in the browser.

**Comment by lai32290** [comment]
understood, is possible to disable this feature? because I had a look at the [options list](https://github.com/electron/electron/blob/master/docs/api/browser-window.md#new-browserwindowoptions), but there has nothing about it.

**Comment by blindhover** [comment]
@lai32290 maybe you can just modify the default preload and use it as your own custom version.
have a look at [https://github.com/segmentio/nightmare#custom-preload-script](url)

**Comment by timkock** [comment]
@lai32290  this helped #1082

**Comment by matthewmueller** [comment]
Duplicate of #1082. I'll make sure we test whatsapp when we fix this.
