### ISSUE TITLE
about mocha

### ISSUE THREAD

**Issue by yanlee26** [segmentio/nightmare#1324]
`  Load a Page
    / (Home Page)
      1) should load without error

  0 passing (3s)
  1 failing

  1) Load a Page / (Home Page) should load without error:
     Error: done() invoked with non-Error: {"message":"navigation error","code":-111,"details":"ERR_TUNNEL_CONNECTION_FAILED","url":"https://gethoodie.com/"}
      at process._tickCallback (internal/process/next_tick.js:103:7)
`

**Comment by matthewmueller** [comment]
Hmm, not sure about this one but it looks like the website is down now. Here's a test example:

```
const Nightmare = require('nightmare')
const chai = require('chai')
const expect = chai.expect

describe('mocha', () => {
  it('Load a Page / (Home Page) should load without error', async function() {
    this.timeout('10s')

    const nightmare = Nightmare({ show: true })
    try {
      const res = await nightmare.goto('https://gethoodie.com/')
      console.log(res)
    } catch (e) {
      console.log(e)
    } finally {
      await nightmare.end()
    }
  })
})
```
