### ISSUE TITLE
how to embed nightmare inside electron as webview?

### ISSUE THREAD

**Issue by jokyme** [segmentio/nightmare#1326]
i want to embed nightmare inside electron as a webview, i have tried this:  https://github.com/TimNZ/nightmare

but it's not work, Google home page can be loaded normally, but it does not type anything or click button, and not error output.

``` javascript
<webview style="height:600px;" src="https://www.google.com"></webview>
<script>
import Nightmare from 'nightmare';
const webview = document.querySelector('webview')
    nightmare = new Nightmare({
        inProcess: {
            window: webview
        }
    });

    nightmare
        .goto('https://www.google.com/ncr')
        .type('input[name="q"]','github')
        .click('input[name="btnK"]')
        .wait('#ires')
</script>
```

**Comment by TimNZ** [comment]
I'll have a look at this next week.
I haven't pushed the latest into the fork.

Also, you need to use the 'in-process' branch.

**Comment by jokyme** [comment]
yes, i'm using the 'in-process' branch. and it's not work with webview.
could you please help to push the latest version of 'in-process' branch into the fork at today or this weekend? thanks!
On the other hand, i also send you an email about this issue at yesterday.
@TimNZ

**Comment by matthewmueller** [comment]
Closing this issue, since we're tracking this feature here: https://github.com/segmentio/nightmare/issues/393
