### ISSUE TITLE
Certain page doesn't load, only using proxy...

### ISSUE THREAD

**Issue by TRiBotWillB** [segmentio/nightmare#1328]
When trying to visit a certain page, it simply fails to load and times out, this is what I've tried:

-Clearing cookies / cache on each instance
-Loading page without proxy (Works)
-Loading page with proxy, on browser (Works)
-Using a separate partition for each instance

I get the following error: 

`(node:11984) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
{ message: 'navigation error',
  code: -7,
  details: 'Navigation timed out after 30000 ms',
  url: 'http://www.adidas.com/yeezy' }
(node:11984) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): ReferenceError: end is not defined`

**Comment by amokan** [comment]
A couple things to verify (I crawl at a massive scale for a living, so i'm dealing with this stuff 24/7)

* What user agent string are you using? If not providing one, most large sites will block you real quick.
* Did you test in curl using the proxy IP? `curl -L -x <proxy ip>:<port> --user-agent "<user agent string here>" "<url>"`

How are you running nightmare? Headless? I run into error 7 (the one you got) in a few different scenarios - one being that someone blacklisted an IP, when one of my squid boxes are down, or finally when i'm hitting my limits on a crawling node where I run my nightmare instances.

Good luck.

**Comment by TRiBotWillB** [comment]
This is the user agent I'm using:
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3128.0 Safari/537.36`

I'll test it in curl and get back to you!

**Comment by amokan** [comment]
@TRiBotWillB Weird. I'm currently connected through one of my proxies and cannot hit adidas.com at all... and i've never crawled them before. They must be real aggressive on crawling.

**Comment by amokan** [comment]
@TRiBotWillB Interesting thing is it works fine through Safari. But not Chrome. Clearly they are trying to prevent something. Maybe give a different user agent a shot (one that is not chrome).

This UA string worked for me inside Chrome

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/604.3.5 (KHTML, like Gecko) Version/11.0.1 Safari/604.3.5`

**Comment by TRiBotWillB** [comment]
I was able to both pages using the user agent provided, thanks!

**Comment by TRiBotWillB** [comment]
I decided to grab the user agent from my chrome browser which appears to be newer than the one I was using and it is working fine now..

**Comment by matthewmueller** [comment]
Thanks for helping to resolve this one @amokan!
