### ISSUE TITLE
Nightmare not loading all background images?

### ISSUE THREAD

**Issue by cjroebuck** [segmentio/nightmare#1330]
Trying to screenshot the full height of this website but the images at the bottom are failing to load in, tried with many delays and it's failing to load the bottom rows of images:

URL: 
http://shawcommercial-stg.azularcdev.com/client/#/room/bedroom-001/0733V/33100/9X36/ashlar/5/0/0

Screenshot: 
![shot_fed0bc253d0dc9902177d802559b91d1](https://user-images.githubusercontent.com/12208/33349742-5d5bf514-d493-11e7-8bdf-cc6e96bdf2dc.png)
Notice the bottom half of the floor is blank - (the floor is a tiled grid of divs with background image set)

Am I running into some limit of electron / chromium?

**Comment by matthewmueller** [comment]
hi @cjroebuck, i think it's still loading the tiles, in my case it took ~10s. Strange website. Here's what worked for me:

```js
var Nightmare = require('nightmare')
var fs = require('fs')

main().catch(console.error)

async function main() {
  const nightmare = Nightmare({ show: true })
  const query = 'hello nightmare'

  const buf = await nightmare
    .viewport(1500, 1600)
    .goto(
      'http://shawcommercial-stg.azularcdev.com/client/#/room/bedroom-001/0733V/33100/9X36/ashlar/5/0/0'
    )
    .wait(10000)
    .screenshot()

  // write the file
  await new Promise((res, rej) => {
    fs.writeFile('screenshot.png', buf, err => (err ? rej(err) : res()))
  })

  await nightmare.end()
}
```
