### ISSUE TITLE
Nightmare screenshots stretched

### ISSUE THREAD

**Issue by leovingi** [segmentio/nightmare#1334]
I'm going through a list of sites and taking screenshots of certain elements, ads in this case. Most of them work just fine, but every now and then I get a screenshot that looks like this
https://imgur.com/a/f8StB

The viewport is 1920x1080, but the whole thing is run on a Ubuntu server through xvfb (if that matters).
The screenshot size is 970x250, as it should be, it's the size of the ad, but it appears to only capture half of it.

Any idea what could possibly cause this or where I could even begin to look for an answer? I couldn't find anything like this in the open or closed issues.

Cheers!

**Comment by matthewmueller** [comment]
Hi @leovingi, are you still running into this problem? If so, do you have some code I could use to debug it? 

Also did it only appear when running via xvfb or were you able to reproduce it locally?

**Comment by matthewmueller** [comment]
Going to close this since this issue is getting stale. Please feel free to reopen if you're still running into this problem and have additional information for us :-)
