### ISSUE TITLE
nightmare in loop 

### ISSUE THREAD

**Issue by Tuqzar** [segmentio/nightmare#1336]
Hi. Can someone help to me wrap my code to loop. When i try make it i get error about next:
(node:7861) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Nothing responds to "goto"
(node:7861) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
This headache the last three days.

var Nightmare = require('nightmare');
const nightmare = Nightmare({ show: true, dock: true, });

let numbers = ['89616093018','89616093012'];
let result = [];

nightmare
  .goto('http://kody.su')
  .type('.search__field', '89616093018')
  .click('.search__submit')
  .wait('#text > div > p:nth-child(7)')
  .evaluate(() => 
      document.querySelector('#text > div > p:nth-child(7)').textContent)
  .end()
  .then(console.log)

try make loop:

numbers.forEach(function(numbers) {
  nightmare
   .goto('http://kody.su')
   .type('.search__field', numbers)
   .click('.search__submit')
   .wait('#text > div > p:nth-child(7)')
   .evaluate(() => 
      document.querySelector('#text > div > p:nth-child(7)').textContent)
   .end()
   .then(function(result){
      result.push(result);
  })
});

**Comment by Tuqzar** [comment]
i think the problem in аsynchronous piece

**Comment by neto391994** [comment]
Same problem here :(
Please help

**Comment by rpascal** [comment]
Take a look here it should help:
https://github.com/rosshinkley/nightmare-examples/blob/master/docs/common-pitfalls/async-operations-loops.md

**Comment by iamdubx** [comment]
@rpascal horrible solution.

**Comment by rpascal** [comment]
@iamdubx could you elaborate on how this is horrible? It's not very useful to anyone by just saying it is horrible.

**Comment by iamdubx** [comment]
@rpascal well, loop using `reduce` or `vo` is not a clean solution. The code becomes very ugly.

**Comment by rpascal** [comment]
@iamdubx would you be able to provide a cleaner solution for us?

**Comment by matthewmueller** [comment]
Now that we have `async/await` these kinds of problems are much easier:

```js
const Nightmare = require('nightmare')

main().catch(console.error)

async function main() {
  const nightmare = Nightmare({ show: true })
  const numbers = ['89616093018', '89616093012']
  const results = []

  for (let i = 0; i < numbers.length; i++) {
    const n = numbers[i]

    const result = await nightmare
      .goto('http://kody.su')
      .type('.search__field', n)
      .click('.search__submit')
      .wait('#text > div > p:nth-child(7)')
      .evaluate(
        () => document.querySelector('#text > div > p:nth-child(7)').textContent
      )

    results.push(result)
  }

  console.log('got results %s', results.join('\n'))

  await nightmare.end()
}
```

For older nodes, this can also be done with generators in a similar fashion. If anyone needs that solution I can prepare one too.
