### ISSUE TITLE
running on c9 and handling c9 warning screen

### ISSUE THREAD

**Issue by tansaku** [segmentio/nightmare#1337]
We have nightmare running on c9, but it's hitting the the c9 warning screen:

![](https://dl.dropbox.com/s/69whs6ircc3yt3h/Screenshot%202017-12-07%2016.41.00.png?dl=0)

We can write code to click the "open the app" button, but that's then hard coding to how things run on c9.  We're trying to set the cookie that avoids this preview screen like so:

```js
   const nightmare = Nightmare();
   nightmare.goto('https://mastering-phoenix-framework-federicoesparza.c9users.io:8081')
     .cookies.set({
       name: 'c9.live.user.click-through',
       value: 'ok',
       path: '/',
       secure: true,
       domain: '.mastering-phoenix-framework-federicoesparza.c9users.io',
       expires: 'Sun, 19 Nov 2978 05:00:00 GMT'
     })
```
but that's not working.

I wonder if anyone has a good set up for running nightmare acceptance tests on c9 that deals with the preview screen, and perhaps also running a testing server?  We have added some scripts to help:

```json
  "scripts": {
    "start": "react-scripts start",
    "testserver": "PORT=8081 react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom src/__tests__/**/*.test.js",
    "features": "xvfb-run react-scripts test --env=jsdom src/features/*.test.js",
    "features-debug": "DEBUG=nightmare* xvfb-run react-scripts test --env=jsdom src/features/*.test.js",
    "eject": "react-scripts eject"
  }
```
but it would be great to know what others are doing both on c9 and off c9 to reduce the amount of typing to run the tests, run acceptance tests separate from unit tests etc.

many thanks in advance

**Comment by tansaku** [comment]
what's really odd is when we do automated acceptance testing on c9 using hound on a phoenix server we don't seem to encounter the preview screen at all, and I can't work out why it's not a problem there ... but it is for nightmare ...

**Comment by tansaku** [comment]
We now seem to have a version working using this:

```json
  test('it welcomes the user', (done) => {
   const nightmare = Nightmare();
   nightmare.cookies.set({
       url: 'https://mastering-phoenix-framework-federicoesparza.c9users.io:8081/',
       name: 'c9.live.user.click-through',
       value: 'ok',
       path: '/',
       secure: true,
       domain: '.mastering-phoenix-framework-federicoesparza.c9users.io',
       expires: '2187-08-16T13:12:47.580Z'
     })
     .goto('https://mastering-phoenix-framework-federicoesparza.c9users.io:8081')
    //  .click('a.solid.fat.info.button') // never worked
    //  .wait('.App-title') 
     .evaluate(() =>
        document.body.textContent
        // document.querySelector('.App-title') // not working for some reason
     )
     .end()
     .then((text) => {
       expect(text).to.include('Welcome to Sing for Needs');
       done();
     });
```

**Comment by matthewmueller** [comment]
thanks for sharing!
