### ISSUE TITLE
Saving the response of the nightmare to the variable

### ISSUE THREAD

**Issue by lrembacz** [segmentio/nightmare#1338]
Is there a way to save the response of the nightmare captured from site and then save it as variable or save it in the file localy / on own server?

I need this information to send it via socket.

Thanks :D

**Comment by matthewmueller** [comment]
Hi @lrembacz, yes you can save the response like this:

```js
const res = await nightmare.goto('http://google.com')
websocket.send(res)
```

Does that answer your question?

**Comment by matthewmueller** [comment]
Yah, result should be passed through, assuming the xvfb is streaming to stdout properly.

**Comment by lrembacz** [comment]
Yeah its working. But every time i need to start xvfb and then wait. Its pretty ineffective. 

Okey I got the answer using your code and returning Promise :D 

```
var url = process.argv[2];

var Nightmare = require('nightmare');

let main = (param) => { 
	return new Promise( function(resolve, reject) {
	  var nightmare = Nightmare({ show: true })
	  const response = nightmare.goto(url)
		    .wait('.url')
		    .evaluate(function() {
				return document.querySelector('url').getAttribute('src')
			});

	  if (response) {
      	nightmare.end(resolve(response));
      } 
	  reject(new Error('error'));
	});
}

main().then(console.log)
```

Thanks for your help and time! :D Its great :D
