### ISSUE TITLE
screenshot() silently does nothing if given path has no extension

### ISSUE THREAD

**Issue by ncraike** [segmentio/nightmare#134]
If you call `nightmare.screenshot()` with a `path` which lacks an extension, the function seems to silently fail and not create any file at all.

From looking at the [Nightmare code](https://github.com/segmentio/nightmare/blob/master/lib/actions.js#L305) and the [PhantomJS documentation](http://phantomjs.org/api/webpage/method/render.html), I suspect this may be an upstream issue with PhantomJS itself. However, I haven't tested with PhantomJS directly - I have little experience of using PhantomJS directly (thus my use of this library).

Even if this is an upstream issue, it'd be great for user-friendliness if the `screenshot()` function checked for one of the supported extensions, or even just if the [documentation of the function](https://github.com/segmentio/nightmare#screenshotpath) mentioned that an extension is required.

**Comment by reinpk** [comment]
was fixed by #135, thanks to you both!
