### ISSUE TITLE
How can I attach to electron window?

### ISSUE THREAD

**Issue by DenisChulkov** [segmentio/nightmare#1343]
I test application which consists of standalone electron windows. Can I attach to electron window using nightmare?

**Comment by matthewmueller** [comment]
Hi @DenisChulkov, I'm not too familiar with attaching to running electron processes. Would attaching to an existing electron app use something like this: https://github.com/electron/spectron?

What are you trying to do? Test an electron app using nightmare? 

Lastly, any code you could provide would be much appreciated to help debug this issue. Thanks!

**Comment by matthewmueller** [comment]
Going to close this since this issue is getting stale. Please feel free to reopen if you're still running into this problem and have additional information for us :-)
