### ISSUE TITLE
Break testcafe framework

### ISSUE THREAD

**Issue by tuanquynet** [segmentio/nightmare#1344]
The block code in preload.js file cause problem on testcafe framework. The source code
https://github.com/segmentio/nightmare/blob/master/lib/preload.js#L13

I am concerning if I can comment that block of code to fix the problem.

thanks.

**Comment by matthewmueller** [comment]
Hi @tuanquynet,

Did you try this one? https://github.com/ryx/testcafe-browser-provider-nightmare

I'm not too familiar with testcafe, a couple questions:

- what's the error you're receiving?
- do you have a testcafe example I could use to get started?

**Comment by matthewmueller** [comment]
Going to close this since this issue is getting stale. Please feel free to reopen if you're still running into this problem and have additional information for us :-)
