### ISSUE TITLE
.wait() timed out

### ISSUE THREAD

**Issue by fishcharlie** [segmentio/nightmare#1349]
I have the following code to test to ensure the URL is correct before doing an assertion test.

	await browser.wait((expectedURL) => window.location.href == expectedURL, "http://localhost:3000/myTestPage");
	let result = await browser.evaluate(() => window.location.href);
	expect(result).to.equal("http://localhost:3000/myTestPage");

For some reason it looks like that `.wait` is timing out after the standard 30 seconds. Changing it to the following works. BUT it waits 30 seconds still before running the `finally` and `expect` code. So the wait isn't working correctly.

	let result;
	try {
		await browser.wait((expectedURL) => window.location.href == expectedURL, "http://localhost:3000/myTestPage");
	} catch (e) {
		
	} finally {
		result = await browser.evaluate(() => window.location.href);
	}
	expect(result).to.equal("http://localhost:3000/myTestPage");

The assertion works fine and `result` is equal to `http://localhost:3000/myTestPage`.

Why would the wait not be evaluating correctly? The wait function should be returning true at some point, but it either isn't being called or isn't returning true.

I tried adding a `console.log` within the wait function but that **never** gets printed to my terminal. Even on success.

I should mention this problem doesn't happen all the time. Sometimes it works fine, sometimes I notice this glitch (maybe 50/50).

**Comment by gcaraciolo** [comment]
I had this problem too.
I think it is because the code sent to the browser is lost on page refresh (If like me, you are waiting to validate a url after some redirects).

Nightmare will throw an exception if the code sent to the browser (electron) doesn't response in 30 seconds. This answer the ```catch()```. After the exception is thrown you can run code again on nightmare, and things work as expected (like in your ```finally()```)

**Comment by fishcharlie** [comment]
@gcaraciolo Any ideas for a solution? This seems super inefficient and a huge waste of time.

**Comment by gcaraciolo** [comment]
@fishcharlie unfortunately, not yet :/

**Comment by juancarlosfarah** [comment]
I'm experiencing the same problem on a redirect after submitting a login form. If you have any ideas about how to solve this without timing out, they will be much appreciated. I will keeping working on it and post any updates here.

**Comment by matthewmueller** [comment]
Hey folks, do you have a full example I can use to debug this? I've created an example with a couple redirects (posted below) but it seems to be working okay for me. 

One thing I did notice was that it will timeout if you give it the previous URL before the redirect. In the example below, giving it `server.url + '/a'` would cause a timeout, since the final destination is `server.url + '/b'`. Could that be the issue? 

Here's the example I'm using:

```js
const express = require('express')
const Nightmare = require('nightmare')
const http = require('http')

async function main() {
  const app = express()
  const server = await Server(app)

  // launch nightmare
  var nightmare = Nightmare({
    loadTimeout: 45 * 1000,
    waitTimeout: 5 * 1000
  })

  // go to /
  app.get('/', function(req, res) {
    console.log('arrived at /, redirecting to /a')
    res.redirect('/a')
  })

  // redirect to: /a
  app.get('/a', function(req, res) {
    setTimeout(() => {
      console.log('arrived at /a, redirecting to /b')
      res.redirect('/b')
    }, 1000)
  })

  // redirect to: /b
  app.get('/b', function(req, res) {
    console.log('arrived at /b, sending 200')
    res.sendStatus(200)
  })

  // goto "/"
  await nightmare.goto(server.url + '/')

  // wait until we're at "/b"
  await nightmare.wait(function(expectedURL) {
    return expectedURL == window.location.href
  }, server.url + '/b')

  // shut'er down
  await nightmare.end()
  await server.close()
}

async function Server(handler) {
  var server = await new Promise(function(res, rej) {
    var s = http.createServer(handler)
    s.listen(0, 'localhost', function() {
      res(s)
    })
  })

  const address = server.address()
  return {
    url: `http://${address.address}:${address.port}`,
    close: function() {
      return new Promise((res, rej) => server.close(res))
    }
  }
}

main()
  .then(() => console.log('done'))
  .catch(console.error)
```

**Comment by matthewmueller** [comment]
Going to close this since this issue is getting stale. Please feel free to reopen if you're still running into this problem and have additional information for us :-)

**Comment by janouo** [comment]
Hi @matthewmueller I am experiencing (nightmare is behaving intermittently) something similar, for example I cloned the following repo https://github.com/hellokoding/registration-login-spring-hsql and started it with a mvn spring-boot:start.

I run nightmare inside mocha many times:
bash~ for i in {1..999}; do echo "-- ------ try number $i -- -------";npx mocha test/test-login-new.js; done

and the content of the js is:
`const Nightmare = require('nightmare');
const expect = require('chai').expect;

const nightmare = Nightmare({ show: false });

describe('testing login', () => {
  it('visits login form', (done) => {
    nightmare
      .goto('http://localhost:8080')
      .insert('#username', 'tonyacunar@gmail.com')
      .insert('#password', 'yachamama')
      .click('button.btn.btn-lg.btn-primary')
      .wait('#logoutForm')
      .evaluate(() => document.querySelector('h2').innerText)
      .then((h2Text) => {
        expect(h2Text.includes('Welcome')).to.equal(true);
        done();
      })
      .catch(error => done(error));
  });
});
`
I added the missing Ids; anyway the test starts failing in the two hundred something try. Below there is an output of a code run

-- ------ try number 240 -- -------


  testing login
    ✓ visits login form (2426ms)


  1 passing (2s)

-- ------ try number 241 -- -------


  testing login
    1) visits login form


  0 passing (30s)
  1 failing

  1) testing login visits login form:
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  



-- ------ try number 242 -- -------


  testing login
    1) visits login form


  0 passing (30s)
  1 failing

  1) testing login visits login form:
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  



-- ------ try number 243 -- -------


  testing login
    1) visits login form


  0 passing (30s)
  1 failing

  1) testing login visits login form:
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  



-- ------ try number 244 -- -------


  testing login
    1) visits login form


  0 passing (30s)
  1 failing

  1) testing login visits login form:
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  



-- ------ try number 245 -- -------


  testing login
    1) visits login form


  0 passing (30s)
  1 failing

  1) testing login visits login form:
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  



-- ------ try number 246 -- -------


  testing login
    ✓ visits login form (17769ms)


  1 passing (19s)

-- ------ try number 247 -- -------


  testing login
    ✓ visits login form (4541ms)


  1 passing (8s)

-- ------ try number 248 -- -------


  testing login
    ✓ visits login form (11620ms)


  1 passing (12s)

-- ------ try number 249 -- -------


  testing login
    ✓ visits login form (5130ms)


  1 passing (8s)

**Comment by janouo** [comment]
Just to add, the problem is that the wait function does not always work as expected

**Comment by mzaatar** [comment]
Same here, I think "wait" fails randomly.

**Comment by ramazan793** [comment]
`wait()` doesn't work correctly sometimes

**Comment by raquelhortab** [comment]
how's that closed? For me is not the wait() call since I'm not using it, but I sometimes get the same error. Locally, I just get it once in a while but in production, it never works. I am using nightmare inside docker.
