### ISSUE TITLE
Socks5a Proxy 

### ISSUE THREAD

**Issue by webworker01** [segmentio/nightmare#1352]
Hello, I am attempting to use a proxy that requires a username and password. I found the authentication example and sadly it does not seem to work.  I get either ERR_CONNECTION_RESET or ERR_EMPTY_RESPONSE depending on whether I am connecting to an http or https website respectively. 

Is the authentication method just http authentication or will it also authenticate for socks 5a?

**Comment by matthewmueller** [comment]
Hi @webworker01, I'm not too familiar with socks5a proxying. Do you mind sharing your setup code or an example you're trying to get working?

It sounds like you're trying to do something like this:

```js
nightmare.goto("socks5h://user:pass@someurl")
```

Yep, the authentication API seems to be just for basic auth. Under the hood it uses this event: https://electronjs.org/docs/api/app#event-login

**Comment by matthewmueller** [comment]
Going to close this since this issue is getting stale. Please feel free to reopen if you're still running into this problem and have additional information for us :-)
