### ISSUE TITLE
Website not crawlable? (Evaluation timed out after 30000msec)

### ISSUE THREAD

**Issue by timohausmann** [segmentio/nightmare#1353]
Hi. This code works with every other URL I can think of, but not with the one I want (bildindex):

```javascript
nightmare
  .on('did-finish-load', function() {
    console.log('FINISHED!');
  })
  .goto('http://www.bildindex.de/document/obj67004025')
  .evaluate(() => {
    return document.title;
  })
  .end()
  .then((title) => {
    console.log(title);
  })
  .catch((error) => {
    console.error('fail:', error);
  });
```

console output:
```
$ node index.js
FINISHED!
fail: Error: Evaluation timed out after 30000msec.  Are you calling done() or resolving your promises?
```

I tried different timeout-parameters and wait-functions, but nothing helped me.
When I use {show: true}, I can see the page loading. It takes longer than other websites, still I don't understand what's the problem here ... can somebody help me?

**Comment by matthewmueller** [comment]
It looks like it's working now. I'm getting a title of:

```
Porträt von Johannes Oporinus (1507 - 1568) | Tobias Stimmer | Bildindex der Kunst & Architektur - Bildindex der Kunst & Architektur - Startseite Bildindex
```

It's weird that `did-finish-load` and goto finished at different times for you. Testing it now, it appears to finish at the same time for me. I wonder if there was an electron issue that got fixed.
