### ISSUE TITLE
Problem When Typing Emoji

### ISSUE THREAD

**Issue by derryberni** [segmentio/nightmare#1355]
`.type("textarea[name='about_me']", "😂") `
When i'm try to type emoji for example 😂 but when run nightmare i got it ��
How I can fix this ?

Thanks

**Comment by matthewmueller** [comment]
It looks like we've inherited this issue upstream: https://github.com/GoogleChrome/puppeteer/issues/1096

As a workaround, you can use `nightmare.insert("textarea[name='about_me']", '😂')`

Based on that issue, it looks like we could detect which unicode characters are too long and change the API to use `.insert()`.

Here's a working example: https://github.com/matthewmueller/nightmare-issues/blob/master/1355.js
