### ISSUE TITLE
Combine screenshot and html actions

### ISSUE THREAD

**Issue by themattrobinson** [segmentio/nightmare#1359]
What's the easiest way to combine two or more Nightmare actions into one call?

For example, I'd love  to take a screenshot and get the HTML of the current page with one call instead of calling .screenshot(path) and then .html(path).

**Comment by themattrobinson** [comment]
Sorry, I just found you can group actions with "use":  https://github.com/rosshinkley/nightmare-examples/blob/master/docs/beginner/use.md

**Comment by matthewmueller** [comment]
yep, that's the recommended approach!
