### ISSUE TITLE
Electron vulnerability, requires update!

### ISSUE THREAD

**Issue by shiftie** [segmentio/nightmare#1363]
Hi,

Electron versions >=1.7 to < 1.7.11 have a known vulnerability: https://electronjs.org/blog/protocol-handler-fix

Can you please update Electron version to `1.7.11` & publish a new version?

**Comment by ctrlaltdev** [comment]
Hi,
I've submitted a pull request to address that vulnerability: https://github.com/segmentio/nightmare/pull/1364

**Comment by ctrlaltdev** [comment]
@ejcx This was the issue related to the PR #1364

**Comment by ejcx** [comment]
Thanks @ctrlaltdev
