### ISSUE TITLE
Set Signed Cookie

### ISSUE THREAD

**Issue by bendiggle** [segmentio/nightmare#1365]
Hi, Just wondering if there is a way to set a signed cookie?
e.g.
```
nightmare
        .cookies.set({
          url: 'url',
          name: 'cookieName',
          value: 'cookieValue',
          signed: true
        })
```

I have an express app that looks for a signed cookie `req.signedCookies.cookieName` however it is unable to find it as nightmare only sets a non-signed cookie.

**Comment by matthewmueller** [comment]
Hi @bendiggle, it's a bit awkward with the current API, but signed cookies aren't anything special from the browser's perspective, so we just can do something like this:

```js
const cookie = require('cookie-signature')
const Nightmare = require('nightmare')

async function main() {
  const nightmare = Nightmare()

  const name = 'test'
  const secret = 'yolo'
  const value = 'coolness'
  const signed = 's:' + cookie.sign(value, secret)

  const headers = {
    Cookie: [name, signed].map(encodeURIComponent).join('=')
  }

  await nightmare.goto('http://localhost:5000/cookie', headers)
  const res = await nightmare.evaluate(() => document.body.textContent)
  console.log('cookie =', res)

  await nightmare.end()
}
```

A working example is available here: https://github.com/matthewmueller/nightmare-issues/blob/master/1365.js
