### ISSUE TITLE
Is there any way to wait until the whole page loaded instead of element

### ISSUE THREAD

**Issue by ffoysal** [segmentio/nightmare#1366]
We have scenario where we wait for certain elements which works but we need to wait until the whole page loaded with all javascript and css.

**Comment by matthewmueller** [comment]
Hi @ffoysal

The solution does depend on the exact situation, but `nightmare.goto(url)` waits for a `load` event which is typically fired when all the assets have finished loading.

If you provide a runnable example, I can help you debug your issue.

**Comment by ffoysal** [comment]
@matthewmueller Thank you very much. I can't use the load as the page is loading on the event of a button click (post request).  unfortunately I cannot provide the runnable example as it is private application.

**Comment by matthewmueller** [comment]
@ffoysal totally understand. Still it's not possible to debug without an example. It should be pretty simple to create a standalone example that illustrate the issue. Here's a minimal template to get you started:

```js
const Nightmare = require('nightmare')
const express = require('express')
const http = require('http')

main().catch(console.error)

function html(body) {
  return `<!doctype><html><head><meta charset="UTF-8"> </head><body>${body}</body></html>`
}

async function main() {
  const app = express()
  const server = await Server(app)

  app.get('/', (req, res) => {
    res.send(html(`server response here`))
  })

  const nightmare = Nightmare({
    loadTimeout: 45 * 1000,
    waitTimeout: 5 * 1000,
    show: true
  })

  await nightmare.goto(server.url, '/')

  // nightmare code here

  await nightmare.end()
  await server.close()
}

async function Server(handler) {
  const server = await new Promise((res, _rej) => {
    var s = http.createServer(handler)
    s.listen(0, 'localhost', function() {
      res(s)
    })
  })

  const address = server.address()
  return {
    url: `http://${address.address}:${address.port}`,
    close: function() {
      return new Promise((res, _rej) => server.close(res))
    }
  }
}
```

Closing for now. If you're able to isolate the problem in an example, I'd be happy to help you further. Thanks!
