### ISSUE TITLE
how to use nightmare in electron?

### ISSUE THREAD

**Issue by xuzhengquan** [segmentio/nightmare#1368]
when i set nightmare electronPath, i got error
`Uncaught Error: spawn C:\Users\atyun\Desktop\automation-network-win32-x64\automation-network-win32-x64\resources\app\node_modules\electron\dist\Electron.app\Contents\MacOS\Electron ENOENT`

**Comment by matthewmueller** [comment]
This isn't possible yet, but it's a high priority for us to get this working. Follow along here for updates: https://github.com/segmentio/nightmare/issues/393
