### ISSUE TITLE
What is the problem of this custom action?

### ISSUE THREAD

**Issue by lewis617** [segmentio/nightmare#1371]
```
Nightmare.action('setValue', function (selector, value, done) {
  this.evaluate_now((selector, value) => {
    document.querySelector(selector).value = value;
    return value;
  }, done, selector, value);
});
```
After I use it, the input will be clear again.

**Comment by matthewmueller** [comment]
Hi @lewis617, can you provide a runnable example, so I can help you debug?

**Comment by lewis617** [comment]
I can't found the error in demo, it only throw an error in my website, maybe it's my website's logic went wrong.
