### ISSUE TITLE
Allow .wait() to accept multiple selectors

### ISSUE THREAD

**Issue by mattxgreen** [segmentio/nightmare#1377]
I propose a change to allow `.wait()` to accept multiple selectors as an OR condition to extend functionality. This is very useful to me in my use-case, and wanted to give this back to the community. All original functionality is retained. Usage:

`.wait('#selector1', '#selector2', '#selector3', 5000)`
 
This will wait until any one of the listed selectors has been found, and makes use of the optional softTimeout (at 5000ms)

Pull request in: https://github.com/segmentio/nightmare/pull/1376

**Comment by matthewmueller** [comment]
Thanks @mattxgreen, we'll continue discussion in the PR

**Comment by sonickseven** [comment]
i had the same problem, but i try with other way.

**to my work it**

	.wait(function(){ // multiple selector
		return document.querySelector('#selector1')||document.querySelector('#selector2')
	})

**Comment by mattxgreen** [comment]
Yeah, that's the current solution.
