### ISSUE TITLE
nightmare electron child process exited with code 1: general error - you may need xvfb

### ISSUE THREAD

**Issue by Swiffers** [segmentio/nightmare#1378]
hi, 

I've tested everything on https://github.com/segmentio/nightmare/issues/224, none of the solution fix the issue. 

As [matthewmueller recommend](https://github.com/segmentio/nightmare/issues/224#issuecomment-283904015)  when closing the issue, I'm posting a new one. 

### Environnement
The OS run on a [VPS at AWS](https://aws.amazon.com/marketplace/pp/B01M26MMTT)
`node -v` =  `v9.5.0`
`npm -v`=  `5.6.0`
`lsb_release -a` = `Kali GNU/Linux Rolling`

### Debug informations
`foo@kali:~/tmp$ sudo DEBUG=* node node_modules/nightmare/example.js`
```nightmare queuing process start +0ms
  nightmare queueing action "goto" for http://yahoo.com +3ms
  nightmare queueing action "type" +1ms
  nightmare queueing action "click" +0ms
  nightmare queueing action "wait" +0ms
  nightmare queueing action "evaluate" +0ms
  nightmare running +0ms
  nightmare electron child process exited with code 1: general error - you may need xvfb +54ms
  nightmare electron child process not started yet, skipping kill. +0ms```

**Comment by matthewmueller** [comment]
hi @Swiffers, to help with debugging this issue, could you provide a Dockerfile of your setup?

It looks like there's a kali linux base image here: https://hub.docker.com/r/kalilinux/kali-linux-docker/

**Comment by Swiffers** [comment]
I haven't been using docker here; Should I?

**Comment by matthewmueller** [comment]
No worries, I've never used Kali before either. If it's similar to ubuntu, following the instructions I just posted here should work:

https://github.com/segmentio/nightmare/issues/224#issuecomment-365938300

**Comment by Swiffers** [comment]
It works like a charm

**Comment by Swiffers** [comment]
But, what are the steps to follow to run xvfb as a command line tool?
The shell command: `xvfb-run command`
