### ISSUE TITLE
2.10.0 does not match between github and npm

### ISSUE THREAD

**Issue by DPechacek** [segmentio/nightmare#1379]
When I add nightmare to my package.json and install it through npm, I am not getting the mouseout function that is in the github repository.  Both are listed at the same version, but there are obvious differences.

**Comment by matthewmueller** [comment]
Hey so `mouseout` is still in master and hasn't been released yet. I'll be cutting a new release in the next couple days

For now I'd work off master 😀

```sh
yarn add https://github.com/segmentio/nightmare.git
```
