### ISSUE TITLE
Custom action callback with evaluate_now it's not working

### ISSUE THREAD

**Issue by rubenfa** [segmentio/nightmare#1383]
Hi,

I'm trying to do an operation with Nightmare after `evaluate_now`. I'm following [this example](https://github.com/segmentio/nightmare/issues/1073), but I think I'm doing something wrong. There is my current code:

```
Nightmare.action('saveState', function(r, done) {
    this.evaluate_now(function(done) {
        done(null, document.documentElement.innerHTML);
    }, function(result) {
        console.log('value from evaluate_now: <<' + result + '>>');
        r.setKey("last", result);
        done(null, true);
    });
});
```
The problem is that `result`  is null, when it should be an HTML document.

Any help will be appreciated.

**Comment by matthewmueller** [comment]
hi @rubenfa, `evaluate_now` is actually part of the private API and should be avoided since it doesn't respect the queue's ordering. You can accomplish this task pretty easily with `evaluate`:

```js
const state = await nightmare.evaluate(() => {
  return document.documentElement.outerHTML
})
```
