### ISSUE TITLE
Issue with getting all of the instances of a selector

### ISSUE THREAD

**Issue by benonymus** [segmentio/nightmare#1399]
Hey there,

I started to use nightmare today, and I can not fogure out how to get all of the instances of a selector, 
for example .evaluate(() => document.querySelector('.xd').innerText)
so here i'm getting the data from the first occurance but how do i get all and then print out all?

Thank you

**Comment by Mithrilhall** [comment]
@benonymus 

Something like this perhaps?

```
var cheerio = require('cheerio');
...
...
...
.evaluate(function() {
  return document.gody.innerHTML;
}).then(function (body) {
  var $ = cheerio.load(body);
  var links = $('a');
})```

**Comment by Paul-Hess** [comment]
document.querySelector('.xd') will only return the first instance found of the selector '.xd'. Using document.querySelectorAll('.xd') will return an array of all instances of elements with the class 'xd'.
you might try something like .evaluate(() => document.querySelectorAll('.xd').map(el => el.innerText)

**Comment by benonymus** [comment]
hey, at the end I did it like this .evaluate(() => Array.from(document.querySelectorAll('.xd')).map(element => element.innerText))

also do you might know how to scroll down on the page?
