### ISSUE TITLE
Two issues

### ISSUE THREAD

**Issue by zachfeldman** [segmentio/nightmare#140]
- Sometimes a website with a hashtag in the URL doesn't load
- How can I monitor for ajaxComplete events? Injecting code constantly gives me a 
`phantom stdout: TypeError: 'null' is not an object (evaluating 'a.parentNode')`

**Comment by reinpk** [comment]
thanks for the reports! can you include an example script that's occasionally failing for the hashtag?

for monitoring the ajax events, i'd give `.on('resourceRequested', ...)` or `.on('resourceReceived', ...)` a try: https://github.com/segmentio/nightmare#onevent-callback

i'll close for now, but can reopen with a test case, thanks!

**Comment by zachfeldman** [comment]
@reinpk it seems a little preemptive to not respond to a ticket for almost a month and then close it without giving the opener any chance to post sample code, just putting it out there. This is an old issue and I've since found an alternate solution so I don't have any sample code for you anymore, but I would have about a month ago =). Thanks for your work!

**Comment by reinpk** [comment]
ah bummer, yeah my workflow is to close and then reopen quite often. it's not a finality :)
