### ISSUE TITLE
Add action for taking screenshot of specific DOM element

### ISSUE THREAD

**Issue by gottlike** [segmentio/nightmare#141]
Nightmare is currently missing a rather helpful and important feature: Taking a screenshot of a specific DOM element, instead of the entire page.

MakoMakox, already created such an action [here](https://github.com/MakoMakox/nightmare/blob/master/lib/actions.js#L352) and [here](https://github.com/MakoMakox/nightmare/blob/master/lib/actions.js#L370). Unfortunately s/he closed the relevant ticket https://github.com/segmentio/nightmare/issues/107, even though the feature was not merged into the Nightmare codebase yet.

**Comment by MakoMakox** [comment]
I reopened the issue until it will get merged into  the Nightmare codebase . I didn't expect that someone else will need it :+1: .

**Comment by reinpk** [comment]
cool, going to merge this with #107 as i agree it seems helpful!
