### ISSUE TITLE
Can I use Xpath in selector?

### ISSUE THREAD

**Issue by kamsoonz** [segmentio/nightmare#143]
Hi,

Can I use xpath in selector ?

If yes, how can I do that ?

Thanks.

**Comment by reinpk** [comment]
i believe xpath is for xml node selection, but the selector here is designed for html pages and gets passed through to `document.querySelector()`, which i don't believe supports xpath, no.

**Comment by toebbel** [comment]
FYI: (X)HTML is a subset of XML so, xpath can be used to query HTML elements.
Selenium offers XPath selection for example.
