### ISSUE TITLE
Viewport not working?

### ISSUE THREAD

**Issue by KyleGobel** [segmentio/nightmare#144]
Hey guys,

Either i'm doing something wrong or this isn't working.  I'm trying to set the viewport before taking a screenshot, and no matter what order or whatever i place these calls in, the screenshot is always the full page (very long images).

```js
new Nightmare()
		.viewport(1080, 1920)
		.goto(uri)
		.wait()
		.url(function(url) {
			endUrl = url;
		})
		.screenshot(filename)
		.run(function() {
			//some code
		});
```

**Comment by reinpk** [comment]
interesting, from my experiments it seems to respect the width parameter https://cloudup.com/cZTInhjYPB0 but not the height. presumably it also needs a scroll offset for the height... using cliprect: https://github.com/ariya/phantomjs/issues/10619

it looks like this can be solved alongside #107 so i'm going to merge this into that issue, thanks kyle!
