### ISSUE TITLE
Use lodash instead of deep-defaults

### ISSUE THREAD

**Issue by fcastilloec** [segmentio/nightmare#1456]
`npm audit` shows that there's a vulnerability (low but still a vulnerability) with the version of `lodash` used by the `deep-defaults` dependency. The package `deep-defaults` hasn't been updated in two years, and I doubt it will.
I think you should switch to using `lodash` directly since it has the method `_.defaultsDeep` which does exactly what `deep-defaults` package does without having any vulnerabilities.
I could submit a PR if necessary (I probably will in the next few days)

**Comment by kounelios13** [comment]
I noticed something today.There are 2 active pull requests on `deep-defaults` that fix the problem.On of them has been reviewed but none of them has been merged
