### ISSUE TITLE
How to prevent Electron from reacting to custom protocol URLs (e.g itmss://)

### ISSUE THREAD

**Issue by eugene-kn** [segmentio/nightmare#1467]
On windows if a web page performs redirect to itmss://itunes.apple.com/app/id1046409045?ck=609994&sn=20771394759&cid=909572033_20771394759&cb_param1=20180615185818s923xy4ddUaksxRaXLRjVg that starts iTunes. Any way to prevent that? I read about app.removeAsDefaultProtocolClient(protocol[, path, args]) but I don't know how to invoke it via nightmare. Thank you!

**Comment by KuoKongQingYun** [comment]
Have the same problem too.
do you have any solution?

**Comment by eugene-kn** [comment]
Sorry, I found no solution and decided not to use nightmare. Good luck!

---
Eugene

**Comment by KuoKongQingYun** [comment]
@eugene-kn 
Thank you all the same,
I use puppeteer now.
