### ISSUE TITLE
Support for keyboard event

### ISSUE THREAD

**Issue by funkyboy** [segmentio/nightmare#147]
Hi,

I have a form with no button. It is submitted when the enter key is pressed.
Does nightmare support keyboard events?

I have tried something like this

```
var keyEvent = new KeyboardEvent("keydown", {key : "Enter", char : "", shiftKey: false});
var q = document.querySelector('#nameInput')
q.dispatchEvent(keyEvent)
```

within evaluation() but no luck.

**Comment by dexcell** [comment]
I've got the same issue.
But you can write `.type("\n");` to simulate enter keypress. at least it's looks like works for me here.

**Comment by reinpk** [comment]
looks like electron supports something like this now, closing in favor of #244 where we can track progress

**Comment by josephrocca** [comment]
For people who get here via google, this sort of thing works fine for me:
```
const Nightmare = require('nightmare');
const nightmare = new Nightmare({ show: true });
(async function() {

  await nightmare
  .goto('https://google.com.au')
  .type('body', 'github nightmarejs') // type into currently-focused input box
  .wait(500)
  .type('body', '\u000d') // press enter

})();

```

**Comment by yanlee26** [comment]
I think nightmare does something pretty cool!
