### ISSUE TITLE
Nightmare program with Electron in Production Environment(IIS) is not working. There is no response from the nightmare.goto(url) call. 

### ISSUE THREAD

**Issue by jubishkammily** [segmentio/nightmare#1478]
Hello , 

I have created an application wit NightmareJs with Electron to get the screen shot of a rendered image. This application is working in the development environment but after deploying it in the production environment its not giving me any responses. 

I am not able get any error messages also back from the nightmare.goto(url) call.  I am not able to resolve this since there is no error message from the module.

 How to get error messages back in production environemnt ?

A simpe nightmare program is not giving any response at all.
```

 var nightmare = new Nightmare({
        frame: false,
        show: false
    });


nightmare.goto(url)
    .evaluate(chartDefenitionJsonObj => {

        c3.generate(chartDefenitionJsonObj);
    }, chartDefenitionJsonObj);

    var outputFilePath = "./graph.png";
    nightmare.wait(selector)
        .evaluate(() => {
            const body = document.querySelector('body');
            const element = document.querySelector('svg');
            const rect = element.getBoundingClientRect();
            return {
                bodyWidth: body.scrollWidth, // Get dimensions of the page.
                bodyHeight: body.scrollHeight,
                x: rect.left,
                y: rect.top,
                height: rect.bottom - rect.top,
                width: rect.right - rect.left
            };
        })
        .then(rect => {
            .screenshot(outputFilePath);
        })
        .then((buffer) => {
           callback("", buffer);
            return nightmare.end();

        })
        .catch(err => {
         
            callback(err, "")
            return nightmare.end();

        });
```

**Comment by jubishkammily** [comment]
Anybody here who can help me on this ?

**Comment by jubishkammily** [comment]
Anybody here who can help me on this ?

**Comment by srgraham** [comment]
I'm getting similar issues. I think it's because my production is a headless server.

No .then() gets hit, no .catch() gets hit. Running everything in a try/catch doesn't catch anything. All that happens is the code exits (without error), since the event loop detects there's nothing to run. I'm still attempting to debug this.

**Comment by srgraham** [comment]
This solved it for me on linux environment: https://www.linode.com/docs/development/nodejs/use-nightmarejs-to-automate-headless-browsing/#create-and-run-the-automation-script
