### ISSUE TITLE
nightmare triggered only once

### ISSUE THREAD

**Issue by canyoudev** [segmentio/nightmare#1481]
Hi there. I am trying to use `nightmare` with little `Express` server and I have an issue.

```js
app.get('/not-working', (req, res) => {
  console.log('not-working')
  nightmare
    .goto('https://google.com')
    .wait(randomPause)
    .end()
    .then((done) => {
      console.log('done')
      res.status(200).json({
        message: 'not-working'
      })
    }).catch(error => console.error(error))
})
```

This runs only once, first time. All other hit's to this url doesnt start `nightmare`!

Why is this happening and how to fix it?

**Comment by canyoudev** [comment]
Fixed by setting instance inside this route.

**Comment by hoyuenkim** [comment]
@ChrisRobston Hello. I have same problem wieh you but I can not fix it now.. can you help me?
