### ISSUE TITLE
Nightmare + Passport.js: failing to destroy session?

### ISSUE THREAD

**Issue by serv** [segmentio/nightmare#149]
Hi,

I am trying to use nightmare.js to simulate signing out and doing some functional tests after that.
![](http://i.imgur.com/NFFMwrf.png)

As the alert says, I went through the sign out process. But the session seems like it's not destroyed yet.
The top nav bar isn't showing sign in and sign up links.

Any idea what might be going on?
Wondering if this is a similar situation as this.
https://github.com/detro/ghostdriver/issues/170

**Comment by reinpk** [comment]
hey @serv unfortunately no idea here :/ if you have an example where we could repro that would be awesome though... ideally we can verify that the switch to electron in v2 eliminates the problem.
