### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by perry-mitchell** [segmentio/nightmare#1490]
Nightmare could really use a changelog. The releases on Github give no information, so a either a changelog file or some kind of release procedure would do this project a lot of good in my opinion. Seeing what changed version to version is incredibly useful, especially for such a complex library.

A `CHANGELOG.md` file is a super simple system to adopt and can be used to [communicate all major changes](https://github.com/buttercup/buttercup-core/blob/master/CHANGELOG.md) quite easily.

**Comment by iget-master** [comment]
Actually, they have a changelog, but it's names `History.md`.

See https://github.com/segmentio/nightmare/blob/master/History.md

**Comment by perry-mitchell** [comment]
@iget-master I'm completely blind it seems! Thank you 😅
