### ISSUE TITLE
Cannot download a file

### ISSUE THREAD

**Issue by jfrumar** [segmentio/nightmare#151]
Has anyone been able to download a file?

I have tried a few approaches. The first was:

```js
.on('filePicker', function(oldFile) {
            console.log('onFilePicker(' + oldFile + ') called');
            return 'a-filename.ext';
          })
```

That code was never triggered.

Then [someone mentioned](https://groups.google.com/forum/#!topic/phantomjs/JChUakj--24) onFileDownload, but that also didn't work.

I have a listener to output resource requests (and it is correctly logging the attempt to retrieve the file):

```js
.on('resourceRequested', function(requestData, networkRequest) {
            console.log('Request (#' + requestData.id + '): ' + JSON.stringify(requestData));
          })
```

I can't just stream the file to disk because it's behind an authenticated session, hence the need for PhantomJS.

Anyone able to get file downloading to work? I think [Casper](http://docs.casperjs.org/en/latest/modules/casper.html#casper-download) has it going, so I will try that next.

**Comment by azurelogic** [comment]
If you can get a hyperlink to the file, then it's not too hard. I used something like this:

```
nightmare.evaluate(
  function () {
    var data = [];
    var xhr = new XMLHttpRequest();
    xhr.open("GET", $("target_anchor").attr('href'), false);
    xhr.overrideMimeType("text/plain; charset=x-user-defined");
    xhr.send();
    data.push(xhr.responseText);
    return data;
  },
  function(data) {
    fs.writeFile("my_filename", data[0], "binary", function(err, x) {console.log('wrote file');});
});
```

It's not very async, but you get the idea.

**Comment by jfrumar** [comment]
That's an interesting approach. I might try it next time, but wouldn't be optimal for large files as the whole file needs to be loaded into memory.

I ended up just extracting the session cookie headers, and then running wget on the command line, setting the necessary headers to pull down the file.

**Comment by rclai** [comment]
How did you extract the cookie header information?

**Comment by rclai** [comment]
@azurelogic how would you do the same thing you did but on a asp.net web form page where there are different submit buttons (and the entire page is a form)?

**Comment by fritx** [comment]
docs of electron download-item: https://github.com/atom/electron/blob/master/docs/api/download-item.md
related PR: https://github.com/atom/electron/pull/2840

**Comment by alexose** [comment]
:+1:

Downloads can be triggered in a number of tricky ways (javascript redirect, iframe, etc).  Being able to plug into the ```will-download``` event would be huge.

**Comment by darthcloud** [comment]
This page is a good test for that eventual feature:
http://www.fangraphs.com/projections.aspx?pos=all&stats=bat&type=steameru

Export Data link at the bottom right export a csv file.

Proper download support is something that always lacked in the various headless browser, nice to see Electron support, hopefully Nightmare will make use of it :)

**Comment by AspireToCodeBetter** [comment]
Hello All, I am having the same issue. Anyone who has a solution to this?

**Comment by rosshinkley** [comment]
With the release of #425 in 2.3.0, I've gone ahead and released plugins that will take care of downloads:

* [nightmare-download-manager](https://github.com/rosshinkley/nightmare-download-manager)
* [nightmare-inline-download](https://github.com/rosshinkley/nightmare-inline-download)

I'm considering this issue resolved.  If you have further questions or problems, please open a new issue.

**Comment by alexose** [comment]
This is amazing!  Thank you.
