### ISSUE TITLE
How to deploy my nightmare nodejs app to any hosting platform like heroku or aws 

### ISSUE THREAD

**Issue by Ali-Khan5** [segmentio/nightmare#1530]
can anyone give me a no nonsense way to deploy my app, its really frustrating .
Thanks in advance

**Comment by scottie** [comment]
This has been answered here numerous times.
You have not visual elements to your linux server so you must give it something for the electron browser to run in, nightmare works with a real browser remember.

```
Install XVFB
THEN: DEBUG=nightmare xvfb-run --server-args="-screen 0 1024x768x24" node cnn.js
```

**Answer:**
https://github.com/segmentio/nightmare/issues/224

**Comment by Ali-Khan5** [comment]
thank you
