### ISSUE TITLE
Where I can find the CI service?

### ISSUE THREAD

**Issue by gustavosizilio** [segmentio/nightmare#1535]
Is this project using continuous integration services (e.g., Travis-CI or Jenkings)? Or has it used at any point of its lifetime?

**Comment by eklem** [comment]
I'm guessing it uses circleci.com from the folder [.circleci](https://github.com/segmentio/nightmare/blob/master/.circleci/config.yml) with the [config.yml](https://github.com/segmentio/nightmare/blob/master/.circleci/config.yml) containing some tests.

**Comment by gustavosizilio** [comment]
You're right! Thank you!
