### ISSUE TITLE
Issues on v0.12 of node

### ISSUE THREAD

**Issue by rfink** [segmentio/nightmare#156]
Getting the following errors running document.querySelector in Nightmare 1.7.0 on version 0.12.0 of node.

dyld: lazy symbol binding failed: Symbol not found: __ZN2v86Object3SetENS_6HandleINS_5ValueEEES3_NS_17PropertyAttributeE
  Referenced from: /Users/rfink/watchtower/default-tests/node_modules/nightmare/node_modules/phantom/node_modules/dnode/node_modules/weak/build/Release/weakref.node
  Expected in: dynamic lookup

dyld: Symbol not found: __ZN2v86Object3SetENS_6HandleINS_5ValueEEES3_NS_17PropertyAttributeE
  Referenced from: /Users/rfink/watchtower/default-tests/node_modules/nightmare/node_modules/phantom/node_modules/dnode/node_modules/weak/build/Release/weakref.node
  Expected in: dynamic lookup

**Comment by reinpk** [comment]
yuck, sorry! on v2 we're running all the tests and development on 0.12, and ditching phantomjs for electron, so this should be resolved shortly, see #200
