### ISSUE TITLE
output page content is strange

### ISSUE THREAD

**Issue by lvyachao** [segmentio/nightmare#159]
For "Walmart.com", Here I just use .wait(5000) after .goto() 
Then I use the screenshot, check the page. Its text form and submit button is odd. (Show strange pictures and different position)

Further actions like .type is not work.

![sth2](https://cloud.githubusercontent.com/assets/3384807/6423588/658bf95a-beb6-11e4-822f-c340449745b7.png)

**Comment by reinpk** [comment]
good news, just tested this on v2 and the rendering looks fixed :) v2 will be out tomorrow see #200
![test](https://cloud.githubusercontent.com/assets/658545/9835218/c529f326-5993-11e5-9123-f4012ba04be4.png)
