### ISSUE TITLE
Unable to check the radio button

### ISSUE THREAD

**Issue by shashanka2a** [segmentio/nightmare#1614]
Initially I tried,click() method.But it only looks for button, link, or image.There is a check() method for radio buttons,but it is not working for me.
It says :
Failed: { TypeError: Cannot set property 'checked' of null

Is there a method called checkOption()?

**Comment by Mako-L** [comment]
document.querySelector('input').checked = true;
And you use evaluate to run that and of course correct selector not 'input'
