### ISSUE TITLE
How can I make the phantom instance to load the website without loading their js files just like NoScript?

### ISSUE THREAD

**Issue by MakoMakox** [segmentio/nightmare#162]
How can I make the phantom instance to load the website without loading their js files just like NoScript? Thanks for the help :)

**Comment by petecoop** [comment]
I don't think you can just turn javascript off that easily, I think the way to do this is to list to `resourceRequestStarted` and abort it's network request e.g.

```
.on('resourceRequestStarted', function(requestData, networkRequest) {
  if(requestData.url.indexOf('.js') !== -1) networkRequest.abort();
});
```

**Comment by sinkingshriek** [comment]
@petecoop, I'm not sure if there's a plugin for `NoScript` like `YSlow` for `phantomjs` but if OP can find that plugin then s/he should be able to load it just like [`YSlow`](http://yslow.org/phantomjs/)

**Comment by petecoop** [comment]
There is actually a `javascriptEnabled` setting in phantomjs itself: http://phantomjs.org/api/webpage/property/settings.html

However not sure if that would break the connection between phantomjs and nightmare/phantomjs-node

**Comment by sinkingshriek** [comment]
@petecoop, That's in fact quite possible in `nightmare`. Just did a quick test and seems to me that it's working. 

@MakoMakox, plug the following lines in `/lib/actions.js` and see if that helps. This is just a quick test to see if it's working and if everyone agrees with this, I or anyone can send a PR.

```
/**
 * Enable/Disable JavaScript.
 *
 * @param {Boolean} useragent
 * @param {Function} done
 */

exports.noJS= function(value, done) {
  debug('.noJS() to ' + value);
  this.page.set('settings.javascriptEnabled', !value, done);
};
```
The usage of this would be:-
```
nightmare
  .noJS(true)
  .viewport(1920, 1080)
  .goto('http://angularjs.org')
  .screenshot('./test.jpg')
  .wait()
  .run(function(err, nightmare) {
    if(err) console(err);
    console.log('done!!');
  });
```

**Comment by petecoop** [comment]
Nice, think I'll look at putting this into [Phantasma](https://github.com/petecoop/phantasma)

**Comment by sinkingshriek** [comment]
Awesome!! In the meantime I'll go ahead and send a PR on this one.

**Comment by inca** [comment]
I don't think you'd be able to `evaluate` anything after that :smirk:

**Comment by giulianok** [comment]
Nothing happened with this?
