### ISSUE TITLE
Couple of suggestions

### ISSUE THREAD

**Issue by puzrin** [segmentio/nightmare#163]
On integrating Nightmare to our test suite, we had to rewrite/extend too much of basic methods. IMHO some thing could be usefult for all:

- goto - accept function instead of URL string.
- wait - option to throw on timeout
- evaluateAsync
- inherit from something like EventEmitter, to simplify action extention. For example, to inject chai, helpers & set viewport after each goto/refresh.
- (?) use `async` in core instead of manual magic & abort on errors immediately.
- (?) rethrow assertions from client to server.

Our current implementation is here: https://github.com/nodeca/nodeca.core/blob/master/lib/test/browser.js.

Here is [test example](https://github.com/nodeca/nodeca.users/blob/master/test/client/users/album/create.js). Note, that asserts on the client make tests for complex cases more easy to write/understand.

Will you accept PR into mainstream? If some of suggestions are not ok - let me know.

**Comment by sinkingshriek** [comment]
> - goto - accept function instead of URL string.

This seems a little too much diversion even from the `phantomjs` API itself. Any particular reason why you would want this when you can already pass a function on the second parameter?


>- wait - option to throw on timeout

Correct me if I'm wrong, but I believe `wait` already [takes in few arguments](https://github.com/segmentio/nightmare/blob/master/lib/actions.js#L297-L350) on which you can just pass in a function for your throw logic after certain `ms`. *tbh, I haven't tried this yet so I could be totally off*  
Unfortunately, I can't speak for other requests but I'm curious to see your use cases.

**Comment by puzrin** [comment]
__goto__

See https://github.com/nodeca/nodeca.users/blob/master/test/client/users/album/create.js#L19 . I need to open profile url to dynamically created users. Since function are stacked in advance, i can't use constant. Alternative solution will require much more code.

__wait__

Alternative solution, without throw on timeout will require more code.

Most suggestion from the first post significantly simplify tests writing, compared to existing methods. A provided links to implementation and example. Try to do the same with current API and you will see the difference.

**Comment by sinkingshriek** [comment]
@puzrin hey, I'll try out your suggestions this weekend. Thanks.

**Comment by puzrin** [comment]
Closing. No longer actual. Since we need suite mostly for testing, it was more simple design api from scratch to make it more effective for our needs https://github.com/nodeca/navit

**Comment by sinkingshriek** [comment]
Oh wow. I completely forgot about this. And :+1: for `navit`. It looks clean.
