### ISSUE TITLE
Teaching new people about nightmare

### ISSUE THREAD

**Issue by mastef** [segmentio/nightmare#166]
This might be a bit out of scope for github issues, since it's not directly code related -

But how would you go in teaching somebody about nightmare and how to use it? I'm asking because every business owner loves to have automated testing, but training people to do it is a bit of a challenge, unless they are already devs. But especially with helpers like 

Maybe you guys know of suggested or complementary courses that can bring you from learning about...

a) html/css selectors
to ...
e) phantomjs
f) nightmare?
g) daydream

For beginners? Any ideas? Especially with extensions like Daydream I think the barriers to get non-devs involved into testing and automation are getting easier with each day; but there's still basics that have to be covered

**Comment by reinpk** [comment]
i think daydream is probably where i'd start... becomes pretty obvious what the code is doing :)

i'd probably do:
1. daydream
2. html/css selectors
3. nightmare
4. dive deeper into how javascript is working
