### ISSUE TITLE
Loses cookies each .goto(...)

### ISSUE THREAD

**Issue by matthewmueller** [segmentio/nightmare#168]
Seems like cookies don't persist if you have multiple `goto(...)`, even if it's the same domain.

Anyone have a solution for this?

**Comment by sinkingshriek** [comment]
You would have to pass the name of the file that you want the cookie persist as an option while you're creating an instance of `nightmare`.

Something like:-

     var nightmare = new Nightmare({ cookiesFiles: "./cookie.txt"});
 
Seems to work for me.

**Comment by MatthewMueller** [comment]
Can you provide an example? I've tried this and no luck :-/

**Comment by sinkingshriek** [comment]
Okay, let's take an example of [onedrive.com](http://onedrive.com). Since they both use the same login and they share the same cookie, below is an example of how that would work.

    var Nightmare = require("nightmare");
    var nightmare = new Nightmare({ cookiesFile: "./cookie.txt"});
    nightmare
      .goto("http://www.hotmail.com")
      .type("input[type=\"email\"]", "your_account_here")
      .type("input[type=\"password\"]", "your_pass_here")
      .screenshot("./beforeLoggedIn.jpg")
      .click("input[type=\"submit\"]")
      .wait()
      .screenshot("./afterLoggedIn.jpg")
      .goto("http://www.onedrive.com")
      .screenshot("./onedrive.jpg")
      .wait()
      .run(function(err, nightmare){
        if(err) throw new Error(err);
        console.log("completed");
      });

**Comment by lucassus** [comment]
```javascript
nightmare.evaluate(function() {
  window.location = '...';
}).wait(..);
```

does the job. ;)

**Comment by reinpk** [comment]
just retested this in `2.x` and cookies are saved across `.goto()` calls now

```
var Nightmare = require("nightmare");
var vo = require('vo');

vo(function *() {
  var nightmare = yield Nightmare({ show: true })
    .goto("https://segment.com/login")
    .type("input[name=\"login\"]", "<login>")
    .type("input[type=\"password\"]", "<password>")
    .click("button[type=\"submit\"]")
    .wait(2000)
    .goto("http://www.google.com")
    .goto("https://segment.com/workspaces");
})(function (err) {
  console.log(err);
});
```
