### ISSUE TITLE
Quit process during runtime

### ISSUE THREAD

**Issue by sean-hill** [segmentio/nightmare#172]
Hey is there a way I could do something like

	Nightmare	
		.goto(url)		
		.evaluate(function(){
			return document.getElementById('test').innerHTML
		}, function(test){
			
			if (test === 'some text') {
				// SOMEHOW QUIT PROCESS and not type below
				process.quit();
			}
			else {
				// Continue on typing below
			}

		})
		// I don't want this to run because of conditions above
		.type('input[name="email"]', email)			
		.type('input[name="password"]', password)
		.click('input[type="submit"]')	
		.run(function (err, nightmare) {
			return;
		});

So quit the process and stop the chain. Thanks!

**Comment by reinpk** [comment]
not easily in the current nightmare v1.x, but in v2  see #200 you'll be able to have proper flow control using generators and an explicit `.end()`
