### ISSUE TITLE
How to detect failed page loads and their reasons?

### ISSUE THREAD

**Issue by nylen** [segmentio/nightmare#173]
When pages fail to load, it looks like `nightmare` will just continue along the queue of operations anyway.  Instead, it should fail and stop trying to do any other queued actions, or at least provide a way to catch the error and decide what to do.

Example log output:

```
  nightmare .goto() url: https://wordpress.com/post/89812188/2 +5ms
  nightmare .goto() page loaded: fail +3ms
```

The page load doesn't always fail after only 3ms, but why would that happen?  Is there a way to see why page loads are failing?  I've added `resourceError` callbacks, but I just get a bunch of these with "Operation canceled" as the error message.

Right now I'm doing something like this, which does detect the failure but is not ideal:

- It's not the simple API that I really like about Nightmare.
- It doesn't provide a way for me to see why the page load failed.
- I'd have to write the same logic for functions other than `goto` like clicking a button etc.

```js
lib.gotoPage = function( url ) {
	return function( nightmare ) {
		nightmare
			.on( 'loadFinished', function( status ) {
				if ( status == 'fail' ) {
					throw new Error( util.format(
						'Failed to load page: "%s"',
						url ) );
				}
			} )
			.goto( url );
	};
};

nightmare.use( lib.gotoPage( pageUrl ) );
```

**Comment by nylen** [comment]
@reinpk thoughts?  Error handling seems like an important feature that is so far lacking in nightmare.

**Comment by reinpk** [comment]
indeed, sorry for the radio silence. this has been fixed in `2.x` as part of the move to electron. here's the test case illustrating how to listen for page load fails:
https://github.com/segmentio/nightmare/commit/2241314e7f5aead3aa03699a314e9427e3245388
