### ISSUE TITLE
Split run into setup -> execQueue -> teardown

### ISSUE THREAD

**Issue by inca** [segmentio/nightmare#175]
Opening an issue to explain upcoming PR.

It would be handy to be able to work with a single PhantomJS instance multiple times (queue some things, run them, do some stuff, queue some more things, run again, etc.). For example in a typical BDD-style spec someone would want to do this:

```js
describe('My awesome page', function() {
  var nightmare = new Nightmare();

  before(function(done) {
    nightmare.setup(done);
  });

  it('should login', function(done) {
    nightmare.goto('/some/login/page').exec(done);
  });

  it('should do something stateful with a page and assert some results', function(done) {
    nightmare.click('btn--primary')
      // assert something
      .exec(done);
  });

  it('should do some more stuff', function(done) {
    nightmare
      // do something
      // assert something
      .exec(done);
  });

  after(function() {
    nightmare.teardownInstance();
  });

});
```

The funny thing is that it's super-easy to support this flow, all we have to do is:

  * extract a method which actually runs a queue from `run` (I called it `exec`)
  * make `setup` and `teardownInstance` methods public (document them, remove `@api private`)
  * (optionally) rename `teardownInstance` into `teardown`

Implementing this would also solve #36 and other similar issues. Although it does not introduce control explicit flow helpers, it becomes kinda doable with explicit `exec` calls (callback pyramid can be optimized/eliminated in numerous ways).

As for automated tests (with Mocha), this solution fits the bill ideally: async tests work like a charm and you also gain a significant performance boost by instantiating PhantomJS only once per `describe` or even per entire spec.

**Comment by nylen** [comment]
A big :+1: to this!  I'm currently hacking together something similar by disabling `teardownInstance` and manually calling it when I'm ready.

**Comment by inca** [comment]
@nylen Thanks! I've also included a [small test in PR](https://github.com/inca/nightmare/blob/56d3bb262d0a887f232c297ac587741c065a0c8a/test/index.js#L743) to illustrate a potential use case with `localStorage`, but it could really be anything.

**Comment by reinpk** [comment]
the extra flow control here is a great idea, though we wanted to hold off and implement it using generators. v2 (#200) should get us there with the explicit `.end()` as well
