### ISSUE TITLE
add support for advanced jquery-style selectors

### ISSUE THREAD

**Issue by lvyachao** [segmentio/nightmare#178]
I know nightmare using standard css selector. So here, when I want to using css path like this:

    .click('body.sz1200 > div > div >a')  
This is worked.
But when I want to try 

     .click('body.sz1200 > div > div >a:eq(1)')
Which is worked in JQuery environment, but not work in Nightmare

**Comment by sinkingshriek** [comment]
That's primarily because `:eq` is `jQuery` only feature. I believe you can still use `nth-child` selector from `CSS` which does something similar except that it starts with 1 index than 0 index that `:eq` starts with.

**Comment by lvyachao** [comment]
No, they are not exactly same, I just thinking jQuery support is very necessary for DOM operation

**Comment by rosshinkley** [comment]
@lvyachao You could use [`.inject()`](https://github.com/segmentio/nightmare#injecttype-file) to add jQuery to a page and then use `.evaluate()` to execute DOM actions.  There's a [unit test](https://github.com/segmentio/nightmare/blob/master/test/index.js#L231-L247) that injects jQuery to get specific tags, as a reference.

You could even go a step further and use [`.action()`](https://github.com/segmentio/nightmare#extending-nightmare) to add custom commands to wrap the jQuery functionality you want.

I don't think including jQuery out of the box is in scope for Nightmare.  If you have any more questions, feel free to reopen or file a new issue.
