### ISSUE TITLE
Resolve promise in .run callback?

### ISSUE THREAD

**Issue by Xlator** [segmentio/nightmare#181]
I'm using Nightmare to make a screenshot service for a social media site I'm building. I've got the page loading down, and the screenshots look as expected, but now I need to upload them to S3.

I have an express app that sends some route params in to .evaluate callbacks in Nightmare to find the thing that needs screenshotting. What I'm trying to do is resolve a separate promise in the .run callback to tell my app that everything is done, so you can upload the screenshot to S3 now.

```javascript
function(var1, var2, var3) {
   var d = when.defer(); 
   new Nightmare()
        .someQueuedCalls()
        .run(function(err, nightmare) { 
            if(err) d.reject();
            d.resolve();
        });
   return d.promise;
}
```

It seems like the promise resolves immediately, before the page even starts loading. Is .run the wrong place for it, or what am I missing?

**Comment by reinpk** [comment]
hmmmm... not sure based on the sample but it shouldn't be called immediately. in v2 we're moving to use generators and this should be substantially easier...

```js
function*(var1, var2, var3) {
   var d = when.defer(); 
   yield nightmare.someQueuedCalls();
}
```
