### ISSUE TITLE
What happens if .wait(selector) doesn't find anything?

### ISSUE THREAD

**Issue by rclai** [segmentio/nightmare#182]
Is there a callback handler for when the selector is not found after the timeout is up?

**Comment by maxshenfield** [comment]
@rclai Definitely! When the `wait` function times out, it emits a `timeout` event that can be handled using the [`Nightmare.on` method](https://github.com/segmentio/nightmare#onevent-callback).  All `.on()` calls must happen before the first `.goto()` so consider it more of a configuration step.

Here's a brief example using `on` to handle a `wait(selector)` timeout. Note the default timeout for `wait(selector)` can be configured in the [Nightmare options](https://github.com/segmentio/nightmare#new-nightmareoptions).

```js
var Nightmare = require('nightmare');
new Nightmare()
  .on('timeout', function(msg) {
     return console.log(msg);
   })
  .goto('http://yahoo.com')
    .type('input[title="Search"]', 'github nightmare')
    .click('.searchsubmit')
    .wait('#non-existent')
    .run(function (err, nightmare) {
      if (err) return console.log(err);
      console.log('Done!');
    });
// Output:
//     timeout elapsed before selector "#non-existent" became present
//     Done!
```

**Comment by rclai** [comment]
Ah there it is. Thanks.
