### ISSUE TITLE
How to enable cache?

### ISSUE THREAD

**Issue by fritx** [segmentio/nightmare#184]
Hi, I'm new to nightmare and phantomjs.

Each time I `open` a new url all the requests got a status of `200`,
using the same `nightmare` instance,
while the e-tag was enabled and
the browsers would get from cache or at least a `304` always.

How could I turn on the cache option somewhere, or something else? Thanks.

````
GET /song/5802 200 4.489 ms - -
GET /static/dist/app/common.css 200 5.591 ms - -
GET /static/dist/app/common.js 200 3.369 ms - 399
GET /static/dist/zepto.min.js 200 5.157 ms - -
GET /static/dist/modern/css/modern.min.css 200 8.725 ms - -
GET /static/dist/modern/fonts/iconFont.svg 200 41.429 ms - -
GET /songlist 200 13.260 ms - -
      ✓ back to songlist (7361ms)
GET /song/5802 200 4.854 ms - -
GET /static/dist/app/common.css 200 3.115 ms - -
GET /static/dist/app/common.js 200 2.181 ms - 399
GET /static/dist/zepto.min.js 200 4.044 ms - -
GET /static/dist/modern/css/modern.min.css 200 9.829 ms - -
GET /static/dist/modern/fonts/iconFont.svg 200 46.414 ms - -
GET /song/5656 200 7.081 ms - -
      ✓ links to next (7264ms)
```

**Comment by luatnd** [comment]
1 up vote! I need the cache too, anyone can help ?

**Comment by a7madgamal** [comment]
yeah!
I really like how nightmare magically connects to PhantomJS on node but at this point I really need to know how to control this connection for setting cache and other settings too

**Comment by fritx** [comment]
hi guys, as metioned in https://github.com/atom/electron/issues/1360
seems nightmare (in electron) now always supports cache. is it right?

**Comment by rosshinkley** [comment]
@fritx @a7madgamal @luatnd Is this still an issue since the move to Electron?

**Comment by rosshinkley** [comment]
Following up on this, electron/electron#1360 links to to electron/electron#3432, which adds the part to use the pragma directive when using [`webContents.loadURL()`](https://github.com/electron/electron/blob/master/docs/api/web-contents.md#webcontentsloadurlurl-options).

I think this issue is resolved.  If you have any more questions, feel free to reopen or open another issue.

**Comment by mashaalmemon** [comment]
@rosshinkley I read the electron threads referenced by you earlier. As I understand it: with electron, by default caching is enabled correct (which can be disabled explicitly with the pragma if need be). And so thus nightmare has caching enabled by default. Is this the case?
