### ISSUE TITLE
Using nightmare from AWS Lambda

### ISSUE THREAD

**Issue by KyleGobel** [segmentio/nightmare#185]
Hey,

So like the title says, I have some small scripts that use nightmare that i'd love to use with AWS lambda.

I've been trying with no luck.

Since phantomjs is not installed on the lambda machines, I have to package it with my app.  (I've just been placing it at the root of the app named ``phantomjs``).  

Can someone give me so pointers of if this is possible, and where I need to change or update nightmare to look at this location rather than wherever it's looking.  

Or am I going about this the wrong way?

**Comment by bdentino** [comment]
you can explicitly specify a path to phantomjs in the options you use to create your Nightmare instance:

e.g.
`var nightmare = new Nightmare( { phantomPath: envvar.string('PHANTOM_PATH') } )`

**Comment by KyleGobel** [comment]
Thanks, I see that's right in the docs in the options section :blush:
