### ISSUE TITLE
Option to delete phantomjs cache?

### ISSUE THREAD

**Issue by serv** [segmentio/nightmare#186]
I noticed that on Jenkins, some nightmare tests are failing due to the fact that nightmare tests are running on old view files. I think these are phantomjs cached pages.
There should be an option to delete phantomjs cached pages before you run the tests. Maybe using something like `new Nightmare().clearMemoryCache()`

**Comment by reinpk** [comment]
in v2 #200 we're moving to electron, hopefully this resolves some of this complexity!
