### ISSUE TITLE
FR: Support being able to inject external URLs

### ISSUE THREAD

**Issue by rclai** [segmentio/nightmare#188]
Like CDNs.

**Comment by sinkingshriek** [comment]
Technically, you can use `npm` as your CDN and do the injection. Either that or you can inject any one of script loaders into the page to load the external URLs for you.

**Comment by rclai** [comment]
Huh? Can you elaborate on that?

**Comment by sinkingshriek** [comment]
Okay, let me give this a shot.
**From npm:-**
Let's say you want to inject `jquery` or `angular`. There are npm packages for them so you can just do 
```javascript
var $ = require('jquery');  
var angular = require('angular');
```

and with nightmare you can just inject them in your browser scope (I'm guessing this is what you're looking for?) as this:-

```javascript
new Nightmare()
  .evaluate(function($, angular){
      console.log($); //in browser scope
      console.log(angular); //in browser scope
    }, 
    function(){}, //in node scope if you want anything being returned from browser to node
    $, angular //injection happens here
  )
  .run();
```
It's described more [here](https://github.com/segmentio/nightmare#evaluatefn-cb-arg1-arg2).

**From script loaders:-**
```javascript
var requirejs = require('requirejs'); //one of the AMD script loader

new Nightmare()
  .evaluate(function(require){
    require(['//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.js']);
  }, function(){ },
  requirejs //injection
  )
  .run();
```
There are other non AMD script loaders as well but this was just one example. I hope this somewhat clarifies what you're trying to do.

**Comment by rclai** [comment]
Oh! I get it now, I didn't think of that. Thanks!

**Comment by rclai** [comment]
Looks like you can't pass complex objects into the browser scope.

**Comment by rclai** [comment]
I figured it out by doing this:

```js
nightmare
  .evaluate(function () {
    $.getScript('https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.3/moment.min.js');
  }, function () {
    console.log('Injected moment.js into the page.');
  })
  .wait(function () {
    return typeof moment;
  }, 'function')
  .evaluate(function () {
    return moment(new Date()).format('MM/DD/YYYY');
  }, function (date) {
    console.log('Today is', date);
  })
  .run(function () {});
```
