### ISSUE TITLE
Conditional actions based on what was evaluated?

### ISSUE THREAD

**Issue by rclai** [segmentio/nightmare#189]
Is it possible to execute actions based on the result of an `evaluate()`?

For example, I login, then I evaluate to check that I logged in, if I logged in, do this, if it did not log in, do something else.

**Comment by rclai** [comment]
I figured it out:

```js
var loggedIn = false;
nightmare
  // Logging in
  .goto('...')
    .type('...', '...')
    .type('...', '...')
    .click('...')
  .wait()
  // Check if logged in and save
  // login state to a variable
  .use(function (nightmare) {
    nightmare
      .evaluate(function () {
        // This is fictitious
        return 'i am logged in!';
      }, function (result) {
        loggedIn = !!result;
      })
  })
  .use(function (nightmare) {
    // Use logged in state to do different things
    if (loggedIn) {
      nightmare
        .doSomethingWhenLoggedIn(); // Fictitious function
    } else {
      nightmare
        .doSomethingElseWhenNotLoggedIn(); // Fictitious function
    }
  });
```

**Comment by matthewmueller** [comment]
Also finding this to be kind of a pain for more complicated sites. Do you have any suggestions for improvement of this use case?

**Comment by rclai** [comment]
I don't know how else you could improve this, I think the `.use()` function is pretty good. The code might get pretty insane, but at least I can do all sorts of things.

**Comment by reinpk** [comment]
it seems like the next major version of nightmare could be build with generators, then `yield` would make it a lot easier to reason about these kinds of flows?

**Comment by rclai** [comment]
I haven't used yields before so that should be interesting.

**Comment by rclai** [comment]
Looks like I can't nest `.use()` inside another `.use()`?

```js
nightmare
  .use(function (nightmare) {
    nightmare
      .evaluate(function () {

      }, function () {

      })
      .use(function (nightmare) {
        // This doesn't happen..
        nightmare
          .doSomething();
      })
  })
  .run(function (error, nightmare) {

  })
```

The debugger says it uses the nested `.use()` but immediately tears down phantom right afterwards.

```
$ nightmare .use()-ing a plugin
$ nightmare .teardownInstance() tearing down
```

**Comment by rclai** [comment]
Crap, it seems like `evaluate`'s callback is asynchronous? This causes the queue to start shifting before the callback has even finished.

**Comment by rclai** [comment]
My workaround currently is to `wait()` and arbitrary amount of time before I do the next thing.

**Comment by rclai** [comment]
Okay, since I've been using this in a Meteor app, I forked Nightmare to create a Fiber-wrapped version, which has fixed my problem.
