### ISSUE TITLE
Preserve state after run.

### ISSUE THREAD

**Issue by fpinzn** [segmentio/nightmare#198]
I'm trying to scrap a page with dynamic pagination. I want to be able to scrap the first page (using evaluate), send the info to the node process, scrap the second page if there's one, and repeat the process.

I'm trying to do it using the run callback recursively, but it seems the state is lost after calling the run method.

**Comment by rclai** [comment]
Look into using the .use() function. That will allow you to do what you're doing.

**Comment by abe-winter** [comment]
@rclai are you sure? I don't think `use()` gets a chance to modify the nightmare task queue after `run()` has started.
@fpinzn I had the same issue. I monkey-patched [`Nightmare.prototype.run`](https://github.com/segmentio/nightmare/blob/master/lib/index.js#L59-L76) to take an additional suppressTeardown param and additionally to not call this.setup if this.page was defined.

**Comment by fpinzn** [comment]
@rclai It doesn't
@abe-winter I think that's pretty useful if you check there's an open pull request for exactly that https://github.com/segmentio/nightmare/pull/59 

The same guy that did the pull request created this https://github.com/johntitus/node-horseman which seems like a substantial improvement over nightmare.

At the end I just went the trivial way: no flow control login inside the nightmare instance.

**Comment by reinpk** [comment]
@abe-winter @fpinzn in v2 we're moving to using generators and an explicit `.end()` method, which should bring the benefit of stronger flow control.
