### ISSUE TITLE
v2 proposal

### ISSUE THREAD

**Issue by reinpk** [segmentio/nightmare#200]
we're starting to consider major improvements that could be made in v2 of nightmare. the proposal is to move from phantomjs to electron, and move the api to use generators.

## speed
some of the most vexing issues with nightmare (e.g. #199 and #192) _seem_ to boil down to underlying issues in phantomjs. @matthewmueller has done some experimentation with [atom/electron](https://github.com/atom/electron) and sees 2-3x speed improvements loading and getting the title of the page:

Site | Phantom | Electron | Speedup
----- | ------- | ------ | -----
Google | 2064ms | 866ms | 2.4x
Yahoo | 4059ms | 1862ms | 2.2x
CNN | 8658ms | 2729ms | 3.2x

## generators
one of nightmare's original goals was to eliminate the callback hell of raw phantomjs. with [generators](https://strongloop.com/strongblog/how-to-generators-node-js-yield-use-cases/) now on node stable, it makes sense to take the api one step closer to eliminating callbacks using generators. this should also make the execution more linear, understandable and controllable. ideally this is a solution to requests like #177, #176, #160 and #59.

```js
var nightmare = new Nightmare();

// generators allow us to get the value back synchronously
var title = yield nightmare
    .goto('http://facebook.com')
    .evaluate(function() {
      return document.title;
    });

// continue with the same instance of nightmare + page state
var titleSearch = yield nightmare
    .click('#search')
    .evaluate(function(){
      return document.title;
    });

// tear down the page state
yield nightmare.close();
```

---

if you have other feedback or frustrations at this deeper level, please let us know!

**Comment by a7madgamal** [comment]
Awesome stuff! I wonder how soon will that be :)

**Comment by a7madgamal** [comment]
May I ask a small question here: how can I reuse the same page object with mocha tests instead of creating a new phantomJS instance for each 'it' function although I'm using the same nightmare object

**Comment by sinkingshriek** [comment]
I'm glad that this is getting some `generator` love too. :+1:

**Comment by matthewmueller** [comment]
Just pushed up a branch for `v2`. I could use some help finishing up some of the remaining tasks:

- [ ] port over the remaining actions
- [ ] add some examples
- [ ] write some tests

**Comment by reinpk** [comment]
awesome @matthewmueller just pushed some updates with a structure for testing based on the old tests, as well as circleci setup, and adding the `.back()` action... will push it a bit further this afternoon

**Comment by reinpk** [comment]
ported over a bunch more actions (with tests)... remaining ones are things like `pdf`, `screenshot`, some variants of `wait`, the event handlers, and initial options. the readme is mostly updated as well.

**Comment by matthewmueller** [comment]
Nice work @reinpk!

**Comment by reinpk** [comment]
todos:
* [ ] add support for `.wait(selector)`
* [ ] add support for `.wait(fn, val, [delay])`
* [ ] add support for `.screenshot(path)`
* [ ] add support for `.pdf(path)`
* [ ] add support for page events
* [ ] add support for initial browser window options
* [ ] update readme for page events and initial options
* [ ] update landing page description and example at https://nightmarejs.org

**Comment by reinpk** [comment]
Getting close... will pick this up next week when I'm back from vacation.

**Comment by FredXue** [comment]
Nice!  can't wait for v2

**Comment by smithb1994** [comment]
Excited for this! Thank you :D

**Comment by matthewmueller** [comment]
@reinpk Interested to hear your thoughts on this. One thing I'd like to change is the ability to wait for click events to be fulfilled. Unless I'm missing something, right now you need to basically know what's coming (on the next page) and wait for it.

It'd be nice to be able to say something like:

```js
yield Nightmare()
  .click('a')
```

And detect that the page is transitioning (maybe using `window.beforeunload`) and wait.

**Comment by reinpk** [comment]
ah, that's a very interesting idea yeah. in v1 you could just call `.wait()` without any arguments... do you think omitting the `.wait()` altogether is the right solution, or just making it so that the complexity of finding a relevant selector is unnecessary?

**Comment by angelgarrido** [comment]
I think when you are on html pages with wait method is enough but on
angular or pages that inject and load content on some elements on page you
need to point exactly the selector you want to wait for

**Comment by matthewmueller** [comment]
Yah, I think it's definitely dependent on the use case. Personally, I think `click()` should handle it because for the case when you actually navigate to another page, it's sort of like the action is "half-complete" (page still in transition) before the next action is triggered and the next action is almost never going to be what you expect (unless it's a `wait()`).

So my preference would be `.wait()` is for things like, waiting for a slidedown to display content or something.

**Comment by matthewmueller** [comment]
Also don't want to bias the API too much though, since my use-case will mostly be for scraping, but there's a ton of other areas nightmare is useful.

**Comment by reinpk** [comment]
:+1: i'm cool with that, thanks @matthewmueller!

**Comment by reinpk** [comment]
a bit stuck on getting `screenshot` to work, but pdf is working and the landing page is ready to go segmentio/nightmarejs.org#1

**Comment by reinpk** [comment]
alrighty.... this is pretty much ready to go! thanks @matthewmueller!

**Comment by reinpk** [comment]
released :)

**Comment by myrubapa** [comment]
I use nightmare for electron and my opinion nightmare for phantomjs was better.

**Comment by gavinengel** [comment]
Would it make sense to have 2 projects?  nightmare/phantom and `proton`/electron, with the same api?

**Comment by myrubapa** [comment]
Why not?

**Comment by reinpk** [comment]
@myrubapa gotcha, you can always continue pulling `1.x` or fork from that commit. phantomjs had SO many weird issues upstream that we had constant reliability problems with it. we opted for a smaller feature set that worked reliably in our testing.

**Comment by matthewmueller** [comment]
@myrubapa can you give an example of how phantom was better for you?

**Comment by smithb1994** [comment]
In my opinion, electron works much better. I use to get all sorts of node-gyp errors, but I don't get them anymore with the electron release.
