### ISSUE TITLE
add eventType to click() for 'mousedown' support

### ISSUE THREAD

**Issue by abe-winter** [segmentio/nightmare#201]
I'm working with a page that needs `'mousedown'`, not `'click'`events. Any interest in adding an `eventType` param to Nightmare.click? (would default to eventType='click').

Change would be [here](https://github.com/segmentio/nightmare/blob/073fa6dc02b84ab6762805d4b40239aa9fa7d57b/lib/actions.js#L193)

Not sure how this overlaps with the new `mouseover` action.

**Comment by rosshinkley** [comment]
Fixed in #308.  Closing.
