### ISSUE TITLE
I have problems with weak module

### ISSUE THREAD

**Issue by MakoMakox** [segmentio/nightmare#204]
I get this error every time:

```javascript
Error: Cannot find module 'weak'
    at Function.Module._oldRes (module.js:695:15)
    at Function.Module._resolveFilename (module.js:1401:19)
    at Function.Module._load (module.js:267:25)
    at Module.require (module.js:377:17)
    at require (module.js:395:17)
    at new D (F:\node_modules\phantom\node_modules\dnode\index.js:28:20)
    at module.exports (F:\node_modules\phantom\node_modules\dnode\index.js:8:12)

    at F:\node_modules\phantom\phantom.js:159:13
    at Server.handler (F:\node_modules\phantom\node_modules\shoe\index.js:22:9)
    at Server.emit (events.js:82:15)
```

**Comment by sinkingshriek** [comment]
Can you tell me what version of node you're using? In Linux, this error usually happens when you don't have `build-essential` (I don't know specific to which compiler but I'm guessing C++ compiler) installed that causes this. If you're running the latest node/npm then you might want to download the latest VS available on your Windows machine and remove `node_modules` package and try re-installing again.

**Comment by MakoMakox** [comment]
I get 
``javascript
MSBUILD : error MSB4132: The tools version "2.0" is unrecognized. Available too
ls versions are "12.0", "14.0", "4.0".
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files\MSBuild\14.0\bin\msbuild.exe` failed wit
h exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Dany\.jx\npm\node_modules\no
de-gyp\lib\build.js:271:23)
gyp ERR! stack     at ChildProcess.emit (events.js:85:15)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:824:
12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "jx" "C:\\Users\\Dany\\.jx\\npm\\node_modules\\node-gyp\\bin\\n
ode-gyp.js" "rebuild"
gyp ERR! cwd F:\node_modules\nightmare\node_modules\phantom\node_modules\dnode\n
ode_modules\weak
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v0.13.1
gyp ERR! not ok
npm WARN optional dep failed, continuing weak@0.4.1
```

I use jxcore instead of nodejs.

**Comment by reinpk** [comment]
in v2 we're moving to electron rather than phantomjs, which should hopefully be more stable and less of these kinds of difficult build errors :/
