### ISSUE TITLE
Screenshot() action goes wrong after injecting a js script.

### ISSUE THREAD

**Issue by FredXue** [segmentio/nightmare#206]
If inject a js file before the screenshot action, the output file would be a empty png file.

Here is my code:

     nightmare
	 .goto("http://www.google.com/")
         .inject("js","./test.js")  	  
	 .wait('.event-title')   // should be a valid element
	 .screenshot("shot1.png")

	 .click('.event-title')  // click a button or something 
         .wait('#sell-tickets') // wait some element
         .screenshot('shot2.png')

	 .run(function (err, nightmare) {	
	     if (err) return console.log(err);
	 });

Any idea about this? Thanks!

**Comment by reinpk** [comment]
hey i'm not sure for v1, but this is now fixed in `2.0.0` (just tested it there)
