### ISSUE TITLE
.select()

### ISSUE THREAD

**Issue by mattyhead** [segmentio/nightmare#207]
Is anyone getting this to work?  If so, can you point out the version of phantomJs you have?

I'm never seeing .select('#selectelement', value) work.  Period.  I get predictably inaccurate results on .type() on a select element, but it matches what you'd see in chrome in a select with option texts of 01 - 99, typing 55 will get you 51 and 66 will get you 61, etc -- but it literally is a 'type' method.  .select() just does *nothing* with phantomjs 1.9.8.

**Comment by mattyhead** [comment]
Hmm, when I perform the same operations as .select does in chrome console, nothing is selected either.

**Comment by sinkingshriek** [comment]
Here's a quick demo on how to use [select](https://jsbin.com/becowa/edit?html,js,output) within DOM. However, in `nightmare` you have this:-
[`.select(selector, option)`](https://github.com/segmentio/nightmare#selectselector-option), 
where `option` is the value of `value` and `selector` is the DOM object.

**Comment by mattyhead** [comment]
...which is how i'm using it.  Thanks for the demo of working javascript working on the DOM.  The demo is not quite what nightmare does...  Have you gotten .select working in nightmare?  If so, could so you say what version of phantomjs you're using?

**Comment by reinpk** [comment]
does this test pass for you? https://github.com/segmentio/nightmare/blob/master/test/index.js#L251 ...trying to isolate the issue

**Comment by mattyhead** [comment]
Thanks for asking.  Can't run any the tests.  Getting:
    /usr/lib/node_modules/express/lib/application.js:209
        throw new TypeError('app.use() requires middleware functions');
Having trouble figuring out what is needed.

**Comment by sinkingshriek** [comment]
@mattyhead I'm currently in PhantomJS 1.9.0. I've wanted to upgrade to 2.0 but haven't yet. 
And yes, I have been able to make selection with `.select`. You can play with it [here](https://ide.c9.io/shriek/nightmare).(had to scour the Internet to find classic dropdown). Anyway, often times your selector might return an array of DOM objects when nightmare only expects one. I easily forget that part many times. Not sure if it's the same with you but just a note.

**Comment by mattyhead** [comment]
@sinkingshriek Thanks!  I'll downgrade a bit and see what I get.

**Comment by samavamsi1** [comment]
how to select the react Drop down list using nightmare

**Comment by thanhbinh710** [comment]
How do i select an option when the value of the option is an object? 

I'm trying to write a test script for an angular site. This is what the rendered HTML looks like

`<select class="select_input" ng-model="mainCtrl.data.company" required>
<option value="?" selected="selected"></option>
<option label="option-abc" value="object:16">option-abc</option>
<option label="option-xyz" value="object:17">option-xyz</option>
</select>`
