### ISSUE TITLE
Using extracted data in selectors

### ISSUE THREAD

**Issue by jurepolutnik** [segmentio/nightmare#210]
Is there any way to use extracted data in selector. 
I extract some data from webpage using evaluate() method, and would like
to use that to perform next actions (click).

Only way I can think of atm, is to run nightmare two times. First time to 
extract data and second time to use that data...

**Comment by angelgarrido** [comment]
I hace a similar problem, tris problem should be perforemos using yield on
v2

**Comment by jurepolutnik** [comment]
Yes in v2 this is solved. 
For v1 I did following workaround... It is possible to use nightmare ref. 
further in run callback.
```
Nightmare.prototype._run = function(callback) {
  var self = this;
  next();

  var noop = function() {};

  function next(err) {
    var item = self.queue.shift();
    if (!item) {
      return (callback || noop)(err, self);
    }
    var method = item[0];
    var args = item[1];
    args.push((next));
    method.apply(self, args);
  }
};

Nightmare.prototype.run = function(callback) {
  var self = this;
  if (!self.page) {
    self.setup(function() {
      self._run(callback);
    });
  } else {
    self._run(callback);
  }
};

```

**Comment by reinpk** [comment]
cool, v2 is coming tomorrow hopefully :)
