### ISSUE TITLE
How can I set `navigationLocked` for preventing page redirection?

### ISSUE THREAD

**Issue by dickeylth** [segmentio/nightmare#211]
RT, in PhantomJS there is [navigationLocked](http://phantomjs.org/api/webpage/property/navigation-locked.html) property, how should I set this property in nightmare? Thank you!

**Comment by rosshinkley** [comment]
With the inclusion of `.action()` being able to patch Electron, I've gone ahead and published a [navigation lock plugin](https://www.npmjs.com/package/nightmare-navigation-lock).  If you have questions, feel free to open an issue in that project's repository or reopen this issue.
