### ISSUE TITLE
V2 demo runs incorrectly

### ISSUE THREAD

**Issue by FredXue** [segmentio/nightmare#213]
I am getting started on javascript.     When I run the v2 demo, I encounter a error message:
 
      if (err) throw err;
                          ^
      TypeError: You may only yield a function, promise, generator, array, or object,
       but the following was passed: "[object Object]"
           at next (..\wrap-fn\node_modules\co\index.js:106:12)
           at ..\wrap-fn\node_modules\co\index.js:45:5
           at ..\wrap-fn\index.js:53:21
           at _resolve_function (..\vo\index.js:176:8)
           at series (\node_modules\vo\index.js:103:3)
           at start (\node_modules\vo\index.js:51:7)
           at vo (\node_modules\vo\index.js:41:7)
             .......
          at Object.Module._extensions..js (module.js:478:10)

Is there any idea? It may help me.

**Comment by reinpk** [comment]
can you share your script? or are you running the tests? the error itself is pretty generic.

**Comment by FredXue** [comment]
A demo provided by the Readme: 

  var Nightmare = require('nightmare');
   var vo = require('vo');

    vo(run)(function(err, result) {
     if (err) throw err;
    });

   function *run() {
     var nightmare = Nightmare();
     var title = yield nightmare
      .goto('http://cnn.com')
       .evaluate(function() {
         return document.title;
       });
     console.log(title);
     yield nightmare.end();
    }

**Comment by FredXue** [comment]
It seems that the return object was represented by a text value when transferred to the vo and it invokes the toString() method which return "[object, Object]".  How to fix it? Still working on this.

**Comment by matthewmueller** [comment]
Should be fixed now in latest `v2` sorry for the confusion!
