### ISSUE TITLE
Node 4.0 can't install 

### ISSUE THREAD

**Issue by myrubapa** [segmentio/nightmare#216]
>myrubapa@myrubapa:~/httpdocs/phantomjs/tests$ npm install nightmare
npm WARN package.json tests@1.0.0 No description
npm WARN package.json tests@1.0.0 No repository field.
npm WARN package.json tests@1.0.0 No README data
>
\> weak@0.4.1 install /home/myrubapa/httpdocs/phantomjs/tests/node_modules/nightmare/node_modules/phantom/node_modules/dnode/node_modules/weak
\> node-gyp rebuild
>
make: Entering directory '/home/myrubapa/httpdocs/phantomjs/tests/node_modules/nightmare/node_modules/phantom/node_modules/dnode/node_modules/weak/build'
  CXX(target) Release/obj.target/weakref/src/weakref.o
In file included from ../src/weakref.cc:19:0:
../node_modules/nan/nan.h:261:25: error: redefinition of ‘template<class T\> v8::Local<T\> _NanEnsureLocal(v8::Local<T\>)’
 NAN_INLINE v8::Local<T\> _NanEnsureLocal(v8::Local<T\> val) {
                         ^
../node_modules/nan/nan.h:256:25: note: ‘template<class T\> v8::Local<T\> _NanEnsureLocal(v8::Handle<T\>)’ previously declared here
 NAN_INLINE v8::Local<T\> _NanEnsureLocal(v8::Handle<T\> val) {
                         ^
../node_modules/nan/nan.h:661:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../node_modules/nan/nan.h:661:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object\> NanNewBufferHandle(char*, size_t, int)’:
../node_modules/nan/nan.h:665:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../node_modules/nan/nan.h:665:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object\> NanNewBufferHandle(const char*, uint32_t)’:
../node_modules/nan/nan.h:672:67: error: call of overloaded ‘New(v8::Isolate*, const char*&, uint32_t&)’ is ambiguous
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../node_modules/nan/nan.h:672:67: note: candidates are:
In file included from ../node_modules/nan/nan.h:25:0,
                 from ../src/weakref.cc:19:
/home/myrubapa/.node-gyp/4.0.0/include/node/node_buffer.h:31:40: note: v8::MaybeLocal<v8::Object\> node::Buffer::New(v8::Isolate*, v8::Local<v8::String\>, node::encoding) <near match\>
 NODE_EXTERN v8::MaybeLocal<v8::Object\> New(v8::Isolate* isolate,
                                        ^
/home/myrubapa/.node-gyp/4.0.0/include/node/node_buffer.h:31:40: note:   no known conversion for argument 3 from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’
/home/myrubapa/.node-gyp/4.0.0/include/node/node_buffer.h:43:40: note: v8::MaybeLocal<v8::Object\> node::Buffer::New(v8::Isolate*, char*, size_t) <near match\>
 NODE_EXTERN v8::MaybeLocal<v8::Object\> New(v8::Isolate* isolate,
                                        ^
/home/myrubapa/.node-gyp/4.0.0/include/node/node_buffer.h:43:40: note:   no known conversion for argument 2 from ‘const char*’ to ‘char*’
In file included from ../src/weakref.cc:19:0:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object\> NanNewBufferHandle(uint32_t)’:
../node_modules/nan/nan.h:676:61: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object\>’ to ‘v8::Local<v8::Object\>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                                                             ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object\> NanBufferUse(char*, uint32_t)’:
../node_modules/nan/nan.h:683:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
weakref.target.mk:90: recipe for target 'Release/obj.target/weakref/src/weakref.o' failed
make: *** [Release/obj.target/weakref/src/weakref.o] Error 1
make: Leaving directory '/home/myrubapa/httpdocs/phantomjs/tests/node_modules/nightmare/node_modules/phantom/node_modules/dnode/node_modules/weak/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/node-v4.0.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "/usr/bin/node" "/opt/node-v4.0.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/myrubapa/httpdocs/phantomjs/tests/node_modules/nightmare/node_modules/phantom/node_modules/dnode/node_modules/weak
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok 
npm WARN optional dep failed, continuing weak@0.4.1
>

Node v0.10.29 work fine

**Comment by reinpk** [comment]
got it, yeah that's a dependency of nightmare unfortunately. in v2 (see #200) we've moved away from phantom and i've just verified that the latest build of v2 runs fine on v4:

<img width="661" alt="screen shot 2015-09-12 at 9 01 39 pm" src="https://cloud.githubusercontent.com/assets/658545/9835171/9cf74a5e-5991-11e5-86c0-4f5a1f816db2.png">

looking to release v2 tomorrow, so closing this
