### ISSUE TITLE
window.open events are shown

### ISSUE THREAD

**Issue by bchr02** [segmentio/nightmare#218]
@reinpk While trying to find a way to accomplish https://github.com/segmentio/nightmare/issues/148 even though you closed it here: https://github.com/segmentio/nightmare/issues/148#issuecomment-139900939 I was reading the electron [window-open.md api documentation](https://github.com/atom/electron/blob/master/docs/api/window-open.md) and noticed that it said:
>When window.open is called to create a new window in a web page, **a new instance of BrowserWindow will be created** for the url and a proxy will be returned to window.open to let the page have limited control over it.

and thought this might cause the windows to be shown because I remember reading in [runner.js](https://github.com/segmentio/nightmare/blob/master/lib/runner.js#L33) that you hard code the options.show to false for the main instance of BrowserWindow.

Running the following code causes the spawned window to be shown for the duration of script. I left ```nightmare.end();``` out to exaggerate the issue.

````javascript
var Nightmare = require('nightmare');
var vo = require('vo');

vo(run)(function(err, result) {
  if (err) throw err;
});

function *run() {
  var nightmare = Nightmare();
  yield nightmare
    .goto('http://www.cnn.com')
    .evaluate(function() {
		window.open("http://www.google.com");
    });
  //yield nightmare.end();
}
````

We should probably hard code the show option within the browser-window function to false so that this doesn't happen.

**Comment by matthewmueller** [comment]
Hm, if I'm understanding this issue correctly, you'd like to be able to programmatically handle open windows, without actually opening the window. Is that correct? If so:

1. programmatically manipulate open windows

We probably won't add support for this case directly, but keep in mind most the library just builds on that `.evaluate(...)` function. Taking a look at how the actions is a good place to start.

There are definitely ways to access popup windows on the page from the host. Here's one way if you have control over the popup: https://github.com/lapwinglabs/oauth-open/blob/master/index.js#L28-L29

2. don't actually opening the window when `{ show: false }`

I'm not sure electron is respecting this default for newly spawned windows, we may need to investigate this more or open up an issue on electron to fix.

**Comment by bchr02** [comment]
Hi @matthewmueller thanks for the reply and for the example.  Ultimately, I would like to use the nightmare api to interface with new windows.

Regardless of whether this repo decides to support this, the fact is some websites may spawn new windows on there own. When this happens, the windows are shown (instead of running headless) which is not the desired effect...

Like you said, we may need to open an issue on the electron repo. Instead of monkey patching window.open we may need to monkey patch browser-window function so it defaults to ```{show: false}```.

**Comment by matthewmueller** [comment]
I can confirm the bug and I've opened the issue on electron's side: https://github.com/atom/electron/issues/2771

I don't really see a good way of handling this on our side, so let's track that issue instead.

**Comment by bchr02** [comment]
Okay, sounds good. Thank you.
