### ISSUE TITLE
ignoreSslErrors in V2

### ISSUE THREAD

**Issue by idrakimuhamad** [segmentio/nightmare#219]
In previous version, there is this option `ignoreSslErrors` that can overcome the SSL error on the targeted page. How can I do this in V2? The instances options only resolve around the browser window of electron. The only thing related to HTTPs are the `allow-displaying-insecure-content` and `allow-running-insecure-content` but that can't overcome the SSL error.

**Comment by matthewmueller** [comment]
Can you provide a failing example please?

**Comment by idrakimuhamad** [comment]
Well, you can try with this site: https://cas2.northport.com.my/myapp/wa/r/nmbctr

I just try to load it up, and take screenshot -- it never did. But if it was replaced with CNN site for example, it worked well.

It is not really failing, cause it didn't return any error, but it didn't do anything, so I'm suspecting this as one of the reason since the site do have SSL errors.

Is this option available in V2 or is it automatically set?

**Comment by idrakimuhamad** [comment]
This is the exact thing I do.

        import Nightmare from 'nightmare';
        import vo from 'vo';

        vo(run)(function(err, result) {
          if (err) throw err;
        });

        function *run() {
            var title = yield nightmare
            .goto('https://cas2.northport.com.my/myapp/wa/r/nmbctr')
            .evaluate(function() {
                return document.title;
            });
            console.log(title);
            yield nightmare.end();
        }

And nothing happened, which I suspect related to the SSL error, because it work with `1.8.2`.

**Comment by yura415** [comment]
Hi, @idrakimuhamad.

It seems that we could achieve this using "--ignore-certificate-errors" switch, passing it through app.commandLine.appendSwitch in runner.js. I suggest new feature request in nightmare to provide such api for setting more advance options for electron. Associated electron issue: https://github.com/atom/electron/issues/1221

Also your example is a bit unclear – for me it looks like it wont compile.

Here is mine:
```js
process.env.DEBUG = "nightmare nightmare:*";

(function () {
  "use strict";

  var Nightmare = require("nightmare"),
    vo = require("vo");

  vo(function* run() {
    var nightmare = new Nightmare()
      .goto("https://cas2.northport.com.my/myapp/wa/r/nmbctr")
      .title();
    var title = yield nightmare;
    yield nightmare.end();
    return title;
  })(function (err, title) {
    if (err) {
      throw err;
    }
    console.log(title);
  });

}());
```
this is what i do
```
  nightmare queueing action "goto" for https://cas2.northport.com.my/myapp/wa/r/nmbctr +0ms
  nightmare queueing action "title" +5ms
  nightmare:log did-start-loading +964ms [{"sender":{"session":{"cookies":{}},"_events":{"crashed":[null,null]},"_eventsCount":21}}]
```
and this is the output (then it just got stuck).
OSX 10.10 / iojs v3.2.0 / nightmare v2.0.6.

**Comment by idrakimuhamad** [comment]
Hey thanks @yura415 I'll try that out. My example of course, aren't complete. I've only showing the important part of the code, excluding the `module.exports` etc

**Comment by reinpk** [comment]
potentially open to a simple pull request, but closing for now as it looks like your immediate question is resolved! thanks!

**Comment by chrisvariety** [comment]
I'm not sure I follow this issue, but I was running into the same problem, essentially a blank white page with nothing loading, until I added `app.commandLine.appendSwitch('ignore-certificate-errors', 'true');` in `runner.js` after the imports. It seems like `ignoreSslErrors` doesn't cover all ssl errors? Monkeypatching nightmare doesn't seem like an awesome solution to the problem though.
