### ISSUE TITLE
Unexpected identifier

### ISSUE THREAD

**Issue by thucnc** [segmentio/nightmare#225]
Hello, I'm a newbie of nightmare, got this error: "Syntax error: unexpected identifier" for the below code
var nightmare = Nightmare();
function login () {
       var a = yield nightmare
	.goto('http://somewebpage.com')
}
Anyone can help.

**Comment by matthewmueller** [comment]
Probably need `node --harmony index.js`

**Comment by thucnc** [comment]
Thanks Matt, now I have a problem running nightmarejs on linux server (it does not do anything even throw exception/error). I guess I have the same problem as issue #228 . Please help

**Comment by reinpk** [comment]
closing as a dupe of #228
