### ISSUE TITLE
evaluate has me stumped

### ISSUE THREAD

**Issue by kanethal** [segmentio/nightmare#226]
Hello, so far I'm loving nightmare as a much more semantic use for phantomjs. I've been able to login to the site I'm gathering data from, and got screenshots confirming I am working on the correct page. But I am having trouble working the evaluate feature. I followed the tutorial here: https://azurelogic.com/posts/web-scraping-with-nightmare-js/  and then adapted it to my use case. I have now found this tutorial to maybe be out of date because I get errors when I execute it verbatim. 

I'm confident I am simply using this wrong, so any correction will be very welcome. I am not getting any console output for except for 'I suck', which I do :(

```javascript 
var nightmare = require('nightmare');

var n= new nightmare()
  .viewport(1000,1000)
  .goto('A URL')
  .wait()
  .screenshot('pic1.png')
  .type(login.idfield , login.id)
  .screenshot('pic2.png')
  .type(login.pwfield , login.pw)
  .screenshot('pic3.png')
  .click("input.cartaccountlogin")
  .wait()
  .screenshot('pic4.png')
  .goto('ANOTHER URL')
  .wait()
  .screenshot('pic5.png')  <===== This picture shows the intended page with login intact
  .evaluate(function (){
    return document.querySelector('body'); <==== confirmed this selector is working in chrome.
  }, function(res){
    var out = res
      console.log('eval output') <====== no action here
    console.log(out)   <===== no action here
  })
  .run(function(err, nightmare){
    if (err) return consoloe.log(err);
    console.log('I suck');  <==== plenty of action here //I suck
    })
```

Again, I'm sure I am just using this wrong. I've followed the examples as closely as possible but I must be missing something.

**Comment by sperand-io** [comment]
First of all, you don't suck! We recently released V2 of this library —

**Comment by sperand-io** [comment]
Hey there! I'm not sure exactly what's going on here just yet — what version of nightmare do you have installed? (looks like 1.x, have you checked out 2.x?)

One thing that jumps out at me is I'm not sure if node will be able to interpret the element object passed to the second function in evaluate. Could you try this instead?

```
...
.evaluate(function (){
    return document.querySelector('body').innerHTML;
  }, function(res){
    console.log(res) 
  })
.run(function(err, nightmare){
    if (err) return console.log(err);
    console.log('I'm awesome!');
    })
```

**Comment by kanethal** [comment]
Thanks for the response! I have copied in your lines in place of my .evaluate. I don't see a change in the console output as seen here:
```
node test.js
[4592:0916/204719:INFO:renderer_main.cc(200)] Renderer process started
[11220:0916/204723:INFO:renderer_main.cc(200)] Renderer process started
I suck
```
I also put in some more console.logs to see if I can get static feedback, but there was no change in the console output.

```javascript
.evaluate(function (){
    console.log('eval function')
    return document.querySelector('body').innerHTML;
    } ,function(res){
      console.log('eval res function')
      console.log(res)
    })
```
I checked on the version and I pulled v2.02. Are there some other dependencies I need to include? Right now I have python 2.7, node, phantomjs available to PATH, and nightmare and that's everything. Thanks again for getting back, I appreciate your interest!

**Comment by sperand-io** [comment]
gotcha, makes sense then! the method signature for evaluate changed in 2.0.0, it only takes a single callback function now that the IPC works a bit differently: https://github.com/segmentio/nightmare/#evaluatefn-arg1-arg2

looks like you're after something along the lines of:

```js
var body = yield nightmare()
  .viewport(1000,1000)
  .type(login.idfield , login.id)
  .type(login.pwfield , login.pw)
  .click("input.cartaccountlogin")
  .wait()
  .goto('ANOTHER URL')
  .wait()
  .evaluate(function (){
    return document.querySelector('body').innerHTML;
  })
```

**Comment by kanethal** [comment]
Thanks Chris, I really appreciate your help here. I was able to get an
evaluation to work successfully!

**Comment by sperand-io** [comment]
boom! psyched to hear it.
