### ISSUE TITLE
Is it possible to start electron with "xvfb-run electron" through Nightmare ?

### ISSUE THREAD

**Issue by Rayjax** [segmentio/nightmare#228]
See stack post http://stackoverflow.com/questions/32612868/running-electron-atom-shell-headlessly-on-linux-server-through-nightmare-js

**Comment by matthewmueller** [comment]
Looks like a dup of: https://github.com/segmentio/nightmare/issues/224

**Comment by reinpk** [comment]
closing as dupe of #224
