### ISSUE TITLE
.url() returns null

### ISSUE THREAD

**Issue by kanethal** [segmentio/nightmare#229]
Help, I broke nightmare :(

I did this:
```javascript
var Nightmare = require('nightmare')

Nightmare()
.goto('http://google.com')
.screenshot('goog.png')
.url(function(link) {
  console.log('url is: '+link)
})
.run()
```
And got back a screen shot of google.com and null for the URL.
If I `.url()` before `.screenshot()` then it hangs the process before generating a screenshot, so I'm guessing I'm just using this wrong. Any sagely words of wisdom?

I noticed that all the documented examples here are using `yield`. Is it necessary to use generators to execute nightmare properly? 

I'm following usage examples from [http://www.devsbytes.com/browser-automation-with-nightmarejs.html](http://www.devsbytes.com/browser-automation-with-nightmarejs.html) and [https://azurelogic.com/posts/web-scraping-with-nightmare-js/](https://azurelogic.com/posts/web-scraping-with-nightmare-js/)

Has the proper usage changed from these examples (I understand you released a new version)

Thanks in advance! Dan

**Comment by reinpk** [comment]
hey dan, yep the new usage would look something like this:

```
var Nightmare = require('nightmare')
var vo = require('vo');

vo(function* () {
  var url = yield Nightmare()
    .goto('http://google.com')
    .screenshot('goog.png')
    .url();
})(console.log);
```
