### ISSUE TITLE
Tests not working

### ISSUE THREAD

**Issue by quicksilver7** [segmentio/nightmare#231]
I've tried running your yahoo search example in mocha. Initially it passes, but I realized that the test was never actually run. When I modify the test to fail it still passes and a break point in the test callback is never hit.

I realized mocha was never executing the test because it was a generator. Using a library like co-mocha allowed me to hit the break point, but the test exploded with some funny errors.

How are you running your tests with generators? Can you verify the test is actually working?

**Comment by quicksilver7** [comment]
I have further experimented and discovered a few solutions. Make sure to set the slow, timeout, and require options as shown in the test/mocha.opts file. Additionally, I think the yahoo pages changes some things that the test does not reflect. I was able to get things working without the errors after applying these changes and adjusting the selectors.

**Comment by TheSoftwareFarm** [comment]
@quicksilver7 we're seeing the same things, as in, mocha never run the tests. Could you please post the solutions you've found (a jsbin or similar would go a long way)
thank you

**Comment by quicksilver7** [comment]
@TheSoftwareFarm I created [a repository](https://github.com/quicksilver7/nightmarejs-examples). You can clone it an it should work fine. I tried explaining what I had to do to get it working there.

**Comment by TheSoftwareFarm** [comment]
thank you @quicksilver7
