### ISSUE TITLE
upload functionality removed?

### ISSUE THREAD

**Issue by ugin** [segmentio/nightmare#235]
In a previous version there was an `upload` function in `lib/actions.js`, as far as I understand after switching to Electron the functionality was removed, its because is not supported by Electron or was not implemented yet?

Is there an obvious way on how to upload files and I missed it?

**Comment by vidakovic** [comment]
+1

**Comment by matthewmueller** [comment]
not sure off the top of my head. two things to check:

- https://github.com/atom/electron/blob/master/docs/api/browser-window.md
- browser events we can trigger programmatically. i would start here: https://github.com/component/file-picker

**Comment by IonicaBizau** [comment]
Any news on this issue?

**Comment by rosshinkley** [comment]
I don't think so.  Electron does not directly allow a way to intercept requests for uploads [like it does for downloads](https://github.com/atom/electron/blob/master/docs/api/session.md#event-will-download).  I've seen it discussed in the Electron issues, most notably [#749](https://github.com/atom/electron/issues/749) and [#3999](https://github.com/atom/electron/issues/3999), but as far as I know, it's still an open problem.

**Comment by IonicaBizau** [comment]
@rosshinkley True... Saw these issues too. :+1:

**Comment by DavidePastore** [comment]
+1

**Comment by Zn4rK** [comment]
I just tested [this](https://github.com/electron/electron/issues/749#issuecomment-213822739), and it actually works really well. I'll see if I can find the time and make a PR to add this.

**Comment by rosshinkley** [comment]
Added as a [plugin](https://www.npmjs.com/package/nightmare-upload).

**Comment by rosshinkley** [comment]
As the plugin should solve this issue, I'm closing it.  If you have questions/problems, fee free to reopen/open a new issue.

**Comment by vshvydky** [comment]
its work: https://github.com/rosshinkley/nightmare-upload

**Comment by tryer3000** [comment]
from the perspective of user, it'd be better that `upload` is native feature of nightmare

**Comment by rodrigoruiz** [comment]
https://github.com/rosshinkley/nightmare-upload didn't work when inside an iframe: https://github.com/rosshinkley/nightmare-upload/issues/9
