### ISSUE TITLE
Support for X-Ray/X-Ray-Phantom?

### ISSUE THREAD

**Issue by kanethal** [segmentio/nightmare#236]
Hello! I noticed that installing nightmare also brought in x-ray-phantom. Is there support for using x-ray with nightmare?

**Comment by matthewmueller** [comment]
yikes, it shouldn't have. x-ray will be a user of new nightmare very soon though ;-) just trying to work out the details

**Comment by kanethal** [comment]
Looking forward to it :)

**Comment by kanethal** [comment]
So I'm a big fat liar, no x-ray-phantom module in nightmare. I don't know what I was thinking. Many apologies :)
