### ISSUE TITLE
Using nightmare for Load/Stress testing

### ISSUE THREAD

**Issue by ndamjan** [segmentio/nightmare#238]
Hello, I am trying to use nightmare to perform load and stress testing of a web application where e.g. 20 concurrent users are expected. However, it appears that only 1 session is active and others are simply waiting, although I can see 20 phantomjs processes in task manager (using Windows 7).
Did anyone else also try this, does nightmare support such use case at all? Thanks for feedback!

Here is my script:

``` javascript
var Nightmare = require('nightmare');

var createTest = function (id) {
    return new Nightmare({timeout: 7200000})
    .log('#' + id + ' << BEGIN >>')
    .log('#' + id + ' ' + 'Starting to load')
    .goto('http://192.168.1.1:8080/webapp/index.jsf')
    .log('#' + id + ' ' + 'Page loaded')
    .log('#' + id + ' ' + 'Enter user/pass')
    .type('input[id="loginForm:tab:username"]', 'test')
    .type('input[id="loginForm:tab:password"]', 'xxxxxx')
    .screenshot('test' + id + ' ' + 'screen-1.png')
    .log('#' + id + ' ' + 'Click Login button')
    .click('button[name="loginForm:tab:btnLogin"]')
    .wait()
    .screenshot('test' + id + ' ' + 'screen-2.png')
    .log('#' + id + ' ' + 'Click APP button') 
    .click('button[name="overviewForm:j_id_d:j_id_q"]')
    .wait()
    .log('#' + id + ' ' + 'Enter 123456')
    .type('input[id="Search:j_id_c:j_id_s"]', '123456')
    .log('#' + id + ' ' + 'Click Search button') 
    .click('button[name="Search:j_id_c:j_id_z"]')
    .screenshot('test' + id + ' ' + 'screen-3.png')
    .wait('form[name="App:SomeInfo"]')
    .wait(2000) // wait 2 more seconds to finish the chart animation
    .screenshot('test' + id + ' ' + 'screen-4.png')
    .log('#' + id + ' ' + 'View search page')
    .log('#' + id + ' << END >>');
}

var runTest = function (test) {
    test.run(function (err, nightmare) {
      if (err) return console.log(err);
    });
}

var tests={};

var numTests = 20;

console.log('Preparing ' + numTests + ' tests');

for (i=1; i<=numTests; i++) {
    tests[i] = createTest(i);
}

console.log("Executing tests");

for (i=1; i<=numTests; i++) {
    runTest(tests[i]);
}
```

**Comment by ndamjan** [comment]
Tried the script using the latest version of NightmareJS in an Ubuntu 14.04 virtual machine. I removed the timeout and set show to true. Although I can see things happening now in parallel, not all instances finish and hang at waiting for a selector (removing the long timeout didn't raise any error). Tried it also with only 5 instances, and only 3 finished. 
Could it be related to https://github.com/segmentio/nightmare/issues/251 or https://github.com/segmentio/nightmare/issues/171?

Are there any known issues with Electron instances running in parallel from the same process?

**Comment by reinpk** [comment]
yeah i also had problems running parallel instances of nightmare `2.x` on the same machine (macbook)

**Comment by ndamjan** [comment]
Do you have an idea if the problem is somewhere in nightmarejs or in electron? Would be very interested in helping to fix it.

**Comment by reinpk** [comment]
my suspicion is that it's somewhere in the ipc mechanism, but i'm not sure exactly how to pinpoint it off the top of my head. would be surprising if the electron processes/windows had any shared state like that.

**Comment by inversion** [comment]
If the nightmare processes are all using the same temporary directory (because the app name is the same) could this cause issues? See https://github.com/atom/electron/blob/master/docs/api/app.md#appgetpathname

**Comment by rosshinkley** [comment]
Possibly related to #493?

**Comment by rosshinkley** [comment]
@ndamjan Are you still experiencing this problem with more recent versions of Nightmare?

**Comment by catdad** [comment]
@rosshinkley I have this problem with the latest version installed today. Interestingly enough, this happens on an Ubuntu box and a Mac, but on Windows, it's fine. I've come to expect the opposite usually.

**Comment by pkantsedalov** [comment]
+1. 
I have a similar case: a lot of links (>15k), processed by bunch (10-50) in a loop, for each of it I run async function where new Nightmare instance is created. I also use Promise.all(arrayOfFunctions). 
As the result after some time (depends on the number of links you have in a bunch) 1 of electron processes hangs, sometimes - even before DOM is ready, but sometimes - between evaluate() and end() invocations.
When I dumped Nightmare instance of hung process I saw that the proc.status code is SIGSEGV.

**Comment by GautierT** [comment]
Hi! Did someone find a solution to run multiple nightmare instance on the same machine at the same time ? Once i launch 4-5 times the same script some of them hang and finally timeout on a .wait() or a .goto()

**Comment by casesandberg** [comment]
Go ahead and try out the headless Chrome implementation in v3, it allows you to run multiple nightmare instances at the same time! https://github.com/segmentio/nightmare/tree/v3.

I am going to close this, but feel free to re-open if it's still an issue.

**Comment by Khady** [comment]
> Go ahead and try out the headless Chrome implementation in v3, it allows you to run multiple nightmare instances at the same time!

It means that the version running on chrome headless doesn't have anymore the limitation of running only once per nodejs process?

Related to #1223

**Comment by casesandberg** [comment]
Headless chrome will seamlessly run multiple processes up to ~100 and then you might run into some issues. This will not work, however, [if you have deployed headless chrome to lambda](https://github.com/adieuadieu/serverless-chrome/issues/15#issuecomment-301754730).
