### ISSUE TITLE
Polymer v1.0

### ISSUE THREAD

**Issue by quicksilver7** [segmentio/nightmare#239]
I am attempting to use NightmareJS to test a Polymer v1.0 application. So far I have been unsuccessful. I assume electron is the problem, but can't access any electron debugging information to verify this. Is there any way to get some feedback from electron while running NightmareJS?

**Comment by reinpk** [comment]
yep three ways:
1. the debug flag: https://github.com/segmentio/nightmare#debug
2. listen for specific events https://github.com/segmentio/nightmare#onevent-callback
3. pass `{ show: true }` to the nightmare constructor to have it actually create a visible, rendered window that you can watch what's happening: https://github.com/segmentio/nightmare#nightmareoptions

**Comment by reinpk** [comment]
added docs here: https://github.com/segmentio/nightmare#debugging
