### ISSUE TITLE
Page's JavaScript is not running

### ISSUE THREAD

**Issue by antpaw** [segmentio/nightmare#242]
I've cloned this repo and tried `make test`, it succeeded. Then I went ahead and modified the 'navigation' fixture, (html is appended in this message), to checkout Electron's JS abilities. Looks like absolutely no JS is running, I tried to do `.click('.a')` and instead of creating a `<div>` it took me to a.html (`.title()` was no longer 'Navigation' but 'A') I tried to take a screenshot right after `goto and wait(1000)` the `div#foo` was not rendered. So I'm quite sure JS doesn't run at all, that makes v2 inferior to v1? Am I missing something?

`````html
<!DOCTYPE html>
<html>
  <head>
    <title>Navigation</title>
  </head>
  <body>
    <a class="a" href="a.html">A</a>
    <a class="b" href="b.html">B</a>
    <a class="c" href="c.html">C</a>
    <script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script>
        $(document.body).append('<div id="foo">bar</div>');
        $('.a').click(function(e){
            e.preventDefault();
            setTimeout(function(){
                $(document.body).append('<div id="no">yes</div>');
            }, 2000);
            return false;
        });
    </script>
  </body>
</html>
`````

**Comment by mpangrazzi** [comment]
Looks like Electron doesn't like JS loaded from an external website. To fix your problem, simply load jQuery in this way:

 ```js
<script src="http://code.jquery.com/jquery-2.1.4.min.js" onload="window.$ = window.jQuery = module.exports;"></script>
```

Then your jQuery snippet below will be executed. You can find more details [here](https://github.com/atom/electron/issues/345).

**Comment by antpaw** [comment]
Okay I will try this, the other question is: why is nightmare not giving me any errors on this one. Like `$ "undefined is not a function"`. This would make it much simpler to debug.

**Comment by mpangrazzi** [comment]
Agreed. 
This weird Nightmare "behaviour" took me some time to figure how to fix it. Nightmare should have an option for reporting all Electron error or debug messages.

**Comment by antpaw** [comment]
Okay i've just tried it and it looks like Electron gives the browser a package management system just like in node. So the browser has no longer to deal with global var. Instead of doing this onload hack, we can simply

`````html
	<script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script>
		var $ = require('jquery');
        $(document.body).append('<div id="xxx">lolxxx</div>');
        $('.a').click(function(e){
            e.preventDefault();
            setTimeout(function(){
                $(document.body).append('<div id="omg">yes</div>');
            }, 2000);
            return false;
        });
    </script>
`````

but we really need a way to access JS errors

**Comment by matthewmueller** [comment]
It really should propagate through. Are listening to the `nightmare.on('error')` event?

**Comment by mpangrazzi** [comment]
@matthewmueller Thanks for the hint. I've tried to listen to `error` event on `nightmare` on an example very similar to @antpaw's one, but with no luck (didn't see any errors). I was expecting something like `$ is not defined`.

**Comment by Nisthar** [comment]
I am getting a lot of errors like $ is not defined, undefined is not a function, could not load jquery when i tried to login to linkedin using nightmare. Can you please tell how i can resolve this?

**Comment by antpaw** [comment]
@matthewmueller I've created this issue with a testcase #248 please help me :)

**Comment by fritx** [comment]
hey guys i hope my PR #249 helps
