### ISSUE TITLE
What happened to .use() and plugins?

### ISSUE THREAD

**Issue by nathan-martinez** [segmentio/nightmare#243]
I haven't used Nightmare in about a month; I came back this morning, and it seems that a lot has changed, including removing any mention of plugins and .use(). Are they still available to use?

**Comment by reinpk** [comment]
i removed plugins and `.use()` from the initial release of `2.x` but totally open to bringing them back

**Comment by rclai** [comment]
This is because we can now do `yield`s right?

**Comment by matthewmueller** [comment]
+1. `.use(fn)` is still useful in the context of `yields`. generators just allow you to use regular programming control flow in addition to chaining.

**Comment by trip41** [comment]
+1, i rely heavily on plugins

**Comment by adrian-ludwig** [comment]
+1, please bring it back

**Comment by matthewmueller** [comment]
hey guys, please weigh in here: https://github.com/segmentio/nightmare/issues/243

**Comment by rosshinkley** [comment]
I believe this was fixed in #376.  Feel free to reopen/file a new issue if this is still a problem.
