### ISSUE TITLE
Use Electron's new sendInput native keyboard events

### ISSUE THREAD

**Issue by matthewmueller** [segmentio/nightmare#244]
Looks like Electron added support for `sendEvent`. We should replace probably replace our synthetic events with the real ones: https://github.com/atom/electron/issues/2269#issuecomment-142504305

**Comment by fritx** [comment]
+1 for this, hope it works as well as the real user keyboard typing

**Comment by factologist** [comment]
yes please!

**Comment by timwis** [comment]
+1 If an `<input>` has a javascript powered input mask on it, `.type()` doesn't let you type into it. I think this is what's necessary to remedy that, because it works fine in CasperJS

**Comment by rosshinkley** [comment]
`.type()` uses `sendInputEvent`.  I believe this can be closed.
