### ISSUE TITLE
Wrapping nightmare up into my own methods

### ISSUE THREAD

**Issue by kanethal** [segmentio/nightmare#246]
OK, so I may have gone too far down the rabbit hole:
I have a script that is working nicely. Now I want to wrap some of this up into methods on my own objects and stay DRY. When I execute this function:
```javascript

var go =  function(sel, attr){
  var resp= n.evaluate(function(sel, attr){
    return document.querySelector(sel)[attr];
  },sel, attr)
  return resp;
};

vo(function* () {
var init= yield n
    .goto(scraper.start)
    .wait(500)

if(yield n.exists(scraper.id[0])){
    var scrape= yield go(scraper.id[0], "innerText");
    scraped.push(scrape);
  }
```

Everything runs fine; but if I try to pass the nightmare instance to a method within my function WITHIN the generator, things fall apart, namely everything goes back to async mode and self destructs. How do I keep things running synchronously with vo.js when I want to pass a nightmare instance to a method within a function within a generator? I tried initially to call ``yield`` on the nightmare phrases in the methods like I did in the snippit above, but my console got mad at me and started saying very rude things about the method being an unexpected identifier when preceded by ``yield``. This is what I am working with. I removed the offending yields already:

```javascript
scrapes= {
      fixed: {
        init: function(sel, attr){
            var fixed = n
            .evaluate(function(sel,attr){
              for (el in sel){
                var q = document.querySelector(sel[el]);
                if(!!q){
              // add to fixed[el]
                  return q[attr];
                } else {fixed[el]=null};
              }
            },sel, attr);
            return fixed;
          },

        sel: {
          id: "[itemprop='name']",
        },
        attr: "innerText",
        // <<<<close fixed>>>>
    }

var goSuperScrape = function(scrapes){
      var pageload= n
        .goto(url)
        .wait()
var args = scrapes.fixed
    var scrape = args.init(agrs.sel, args.attr)
}

var n = new Nightmare();

vo(function* () {
  console.log('Nightmare Started');
  var auth = yield n
    .goto(login.url)
    .wait()

//login stuff here then fire up goSuperScraper to go to scraping page and scrape scrapables

var theInfos = yield goSuperScrape(scrapes);
```
I've been looking over the vo.js documentation and I'm starting to glean some knowledge, but I'm not smart enough to extend the examples to what I'm doing. Can I get a booster shot of smarts please!? 

Thanks, Dan.

PS, I'm wondering if I'm violating the purpose of this forum, and if I should post these kinds of help requests elsewhere. I'm really very new to this whole scene, and figured this is probably where people who are familiar with nightmare will be lurking. If I should put this kind of content up on stackOF instead, just let me know :) Thanks for all your awesomeness!

**Comment by kanethal** [comment]
3am jibber jabber, sorry.

**Comment by matthewmueller** [comment]
hahaha, we've all been there ;-)
