### ISSUE TITLE
$ is not defined, module ipc is not availiable

### ISSUE THREAD

**Issue by Nisthar** [segmentio/nightmare#247]
I am getting a lot of errors like $ is not defined, module ipc is not availiable, could not load jquery when i tried to login to linkedin using nightmare. Can you please tell how i can resolve this?

**Comment by fritx** [comment]
I think this is related to another issue of mine https://github.com/atom/electron/issues/2659
And nightmare should pass `node-integration: false` and a `preload` script to the `BrowserWindow` so it could work as normal browser loading, it would cause a slight refactor of `lib/javascript.js`.

**Comment by Nisthar** [comment]
Sorry i am new to nightmare. Can you tell me how can i do it?

**Comment by fritx** [comment]
No, maybe you need to wait nightmare to fix such problem.. unless you want to implement something the nightmare does like what I does in my [wxbot](https://github.com/fritx/wxbot).

**Comment by Nisthar** [comment]
Thanks. I thought its a error in my system or code.

**Comment by fritx** [comment]
Use provide a PR for this bug, test passed

**Comment by fritx** [comment]
related #242
