### ISSUE TITLE
nightmare.on('error', callback) doesn't work

### ISSUE THREAD

**Issue by antpaw** [segmentio/nightmare#248]
I've added this testcase and I'm not able to pass it
https://github.com/antpaw/nightmare/commit/5e3f6617a3838eebca411db4644d04a536a5573f

**Comment by antpaw** [comment]
Can you maybe give a little feedback why this is a bug and how I could fix it, or a hint where to start looking for a fix?

**Comment by fritx** [comment]
https://github.com/segmentio/nightmare/blob/master/lib%2Frunner.js#L103-L105
seems it would emit `javascript` instead of `error`

**Comment by antpaw** [comment]
yes, the first suggestion didn't work

**Comment by edasque** [comment]
Would you use this to capture JS console errors from Electron so as to output them in node.js? How would you capture output from console.* ?

**Comment by antpaw** [comment]
@edasque you mean if something is happning inside .evaluate() ? there is a `.on('javascript')` callback for js-erros and you can start your script with `DEBUG=nightmare:log` to see the logs.

btw my pr was merged, so this can be closed https://github.com/segmentio/nightmare/pull/300

**Comment by edasque** [comment]
@antpaw are you sure it's DEBUG=nightmare:log ? This does nothing here. Is it just the normal DEBUG=nightmare ?

**Comment by antpaw** [comment]
yes https://github.com/segmentio/nightmare/blob/master/lib/nightmare.js#L5, but there is also a '.on('log', func)' event
