### ISSUE TITLE
google.com blocked in China while running test

### ISSUE THREAD

**Issue by fritx** [segmentio/nightmare#249]
Could I replace it just with ~~`yahoo.com`~~`github.com`? I can use a VPN though, but not all the time..

**Comment by fritx** [comment]
Oops, because of #247 , yahoo.com won't work now, looking for another popular site that works in China.

**Comment by FredXue** [comment]
Po主 好嗨！

**Comment by fritx** [comment]
@FredXue 嗨，我哭了

**Comment by FredXue** [comment]
终于看到同胞在鼓捣nightmare O(∩_∩)O （这个issue跟nightmare没关系啊）

**Comment by FredXue** [comment]
@fritx  以后遇到问题可以交流交流！

**Comment by fritx** [comment]
nice  XD 毛问题 已follow

**Comment by fritx** [comment]
sometimes even `<link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet'>` is blocked too.. it's really disappointing.. but let's just leave it for now..
