### ISSUE TITLE
Api doc for `end` function

### ISSUE THREAD

**Issue by nichoth** [segmentio/nightmare#254]

**Comment by sperand-io** [comment]
No longer used in 2.x, as your pipeline will return a generator you can `yield` instead. For `.end` documentation see the [readme @1.x](https://github.com/segmentio/nightmare/blob/1.8.2/Readme.md)

**Comment by sperand-io** [comment]
whoa i totally jumped to an early conclusion on this one, confusing `run` with `end` — my apologies!

**Comment by reinpk** [comment]
added brief docs: https://github.com/segmentio/nightmare#end

is there a specific behavior you're looking to see documented? thanks for the find!

**Comment by nichoth** [comment]
Are there any arguments or return value? It might be good to use .end() consistently in the readme examples. It is only in the example at the end. Or it's just confusing because no one knows how to use generators? I'm not sure what is going on in the chainable nightmare methods. In version one it used callbacks, so you had `nightmare.something().something().run(function onEnd() {})`. 

```js
var Nightmare = require('../nightmare');
var vo = require('vo');

vo(run)(function(err, result) {
  if (err) throw err;
});

function *run() {
  var nightmare = Nightmare();
  var title = yield nightmare
    .goto('http://cnn.com')
    .evaluate(function() {
      return document.title;
    });
  console.log(title);
  yield nightmare.end();
}
```

**Comment by matthewmueller** [comment]
Same API as run, only difference is that it'll shut processes down.

```js
yield Nightmare()
  .goto('https://github.com')
  .evaluation(fn)
  .end()
```

Or

```js
Nightmare()
  .goto('https://github.com')
  .evaluation(fn)
  .end(onEnd)
```
