### ISSUE TITLE
How to click on all the buttons with same class?

### ISSUE THREAD

**Issue by Nisthar** [segmentio/nightmare#255]
I am trying to click all the buttons with the same class. But its only clicking one button with the class name.

Is there any way, i can retrieve the collection of the button with the class name and loop over each item and click it?

**Comment by reinpk** [comment]
yeah, you can do that in javascript with the `.evaluate()` method, check out the implementation of `.click()`:
https://github.com/segmentio/nightmare/blob/master/lib/actions.js#L77
