### ISSUE TITLE
Use promises for `.then()`

### ISSUE THREAD

**Issue by nichoth** [segmentio/nightmare#256]
Are people opposed to using a real promise in `.then` method? I think it's confusing to name the method that when it's really a callback.

**Comment by FdezRomero** [comment]
Agreed. I'm currently wrapping the Nightmare chain in a promise and calling `resolve()` inside the fulfilled callback of the `.then()` method.

Besides, some methods such as `.screenshot()` are not even then-able (or I just can't make it work).

**Comment by matthewmueller** [comment]
FWIW `.then()` is undocumented and part of the private API. May change this going forward, but right now the only reason we have it in there is so we can yield on any piece of the chain:

```js
yield Nightmare()
  .title()
```

`.screenshot()` should definitely be yieldable, that's a bug

**Comment by nichoth** [comment]
I don't fully understand generators, so this may not make sense, but my understanding is that `yield nighmare.someAction()` sends a promise or async function to whoever is iterating over the generator, so `.then` is exposed to the control flow logic, for example in `vo(function* () {})`, `vo` would depend on the `.then` method.

**Comment by matthewmueller** [comment]
yep it can, among other things. vo is using co internally, and co has: https://github.com/tj/co/blob/master/index.js#L100

**Comment by FdezRomero** [comment]
@matthewmueller Sure thing. In the following example, the `debug` message is never shown (using thenables instead of generators):

```javascript
nightmare
.screenshot('./example.png')
.then(function() {
  debug('Screenshot taken');
})
.end();
```

In this other snippet, both `getTitle` and `.screenshot()` are never executed:

```javascript
nightmare
.evaluate(findTitle)
.then(getTitle)
.screenshot('./example.png')
.end();
```

Hope it helps. I'm currently using version 2.0.5 because with 2.0.6 it doesn't even get passed the first `.evaluate()`.

I know you're all putting time and effort into this and I'm thankful, but the lack of documentation and consistency is making the experience to really be a nightmare...

**Comment by nichoth** [comment]
@FdezRomero – haha isn't nightmare a great name for a software library?

I would like to specify and document the async interface for nightmare. Whether it is consumed by a generator function or some other pattern is outside the scope of nightmare.

I think using a `.run` method would be the simplest solution. You would end up with an API that looks like:

```js
var title;

// callbacks
nightmare
    .goto('http://cnn.com')
    .evaluate(function() {
      return document.title;
    })
    .run(function(err, res) {
        if (err) throw new Error(err);
        title = res;
    })
;

// or return a promise if no argument is passed in
myPromise = nightmare
    .goto('http://cnn.com')
    .evaluate(function() {
      return document.title;
    })
    .run()
;
myPromise
    .then(function(res) {
        title = res;
    }).catch(function(err) {
        throw new Error(err);
    })
;
```

Which could then be consumed in a number of ways:

```js
require('async').series(nightmare.someAction().run, function onEnd() {/*...*/});
require('co')(function* () { return yield nightmare.someAction().run(); })
    .then(/*...*/);

```

This would change the examples b/c you would need to end every method chain block with `.run`. Another option is to have every chainable method return a promise. This is how [petecoop/phantasma](https://github.com/petecoop/phantasma) works. The API is maybe prettier, but I think this adds unnecessary complexity.

**Comment by matthewmueller** [comment]
Guys, I can see why this is confusing but you are thinking about it in terms of how it should work with promises, which is part of the private API and undocumented. 

```js
nightmare
.screenshot('./example.png')
.then(function() {
  debug('Screenshot taken');
})
.end();
```

This looks like it should work but you're not handling the error case so it's tough to say whether it's a bug in nightmare or a bug in your code. The following adjustment will determine this:

```js
nightmare
.screenshot('./example.png')
.then(function() {
  debug('Screenshot taken');
}, onerror)
.end();
```

Please open up a new issue if you still can't get to the debug statement.

---

Like I mentioned, I'm open to accepting a PR to implement promises, but it should be small and concise.

**Comment by FdezRomero** [comment]
Hi @matthewmueller,

I think I found the issue I was having with the undocumented use of `.then()`. I was chaining several actions like this (omitting the parameters for clarity):

```javascript
nightmare
.evaluate()
.then()
.screenshot()
.then()
.end();
```

And saw that the next action didn't hook up with the previous part of the chain. I think this is why the `.then()` after the `.screenshot()` didn't run. Please correct me if I'm wrong as I'm still trying to get the inner workings of Nightmare.

**Comment by fzaninotto** [comment]
+1, Promises are getting ubiquituous in the Node landscape since 4.0. It's very surprising that you push a custom way of handling async calls. I love co and koa and generators, but Promises are yieldable by co, too. So offering a Promise-based API would let existing developers use generators if they want to, and be more open to newcomers.

**Comment by matthewmueller** [comment]
Guys, this is where we left off:

> Like I mentioned, I'm open to accepting a PR to implement promises, but it should be small and concise.

No more comments please, just open a PR.
