### ISSUE TITLE
Network monitoring

### ISSUE THREAD

**Issue by AlexanderKozhevin** [segmentio/nightmare#258]
Is there any approach to network monitoring? Like in phantomJS
page.onResourceRequested = function(request) {
  console.log('Request ' + JSON.stringify(request, undefined, 4));
};

http://phantomjs.org/network-monitoring.html

**Comment by danhalliday** [comment]
Not that I can see — depending on what you're doing I've managed to structure all my tests so that I `wait()` for new DOM elements (all my requests are XHRs to my backend API). YMMV

**Comment by reinpk** [comment]
check out `did-get-response-details`:
https://github.com/segmentio/nightmare#onevent-callback

**Comment by AlexanderKozhevin** [comment]
Awesome!
