### ISSUE TITLE
Not working on Linux (CentOS)

### ISSUE THREAD

**Issue by afuggini** [segmentio/nightmare#269]
I'm running some basic NightmareJS code on my Macbook and it works perfectly. But when I do the same on my CentOS cloud server on debug mode, I see all actions being queued and then the script terminates without any results. It's like the actual actions are never run.

Node, Electron and Python are all present. PhantomJS and CasperJS too. Any ideas?

Thanks.

**Comment by matthewmueller** [comment]
duplication of: #224
