### ISSUE TITLE
Create a chatroom in gitter.im?

### ISSUE THREAD

**Issue by fritx** [segmentio/nightmare#272]
Is there any chatroom like in https://gitter.im where we can talk about this project, other than the github issues?

**Comment by rosshinkley** [comment]
I know I'm late to the party: +1 :)

**Comment by fritx** [comment]
+1 xP

**Comment by mousemke** [comment]
gitter/slack/whatever, i would love a forum to be able to discuss between users and ask questions

+1

**Comment by fritx** [comment]
since nightmare currently has no chatroom.
guys can join here: https://gitter.im/fritx/nixe?utm_source=share-link&utm_medium=link&utm_campaign=share-link
[nixe](https://github.com/segmentio/nightmare) is a fork of nightmare, highly inspired
