### ISSUE TITLE
Adding nightmare.paste()

### ISSUE THREAD

**Issue by fritx** [segmentio/nightmare#274]
In my project I implement a paste with some specified drop-in data but the code becomes a little ugly:
https://github.com/fritx/wxbot/blob/dev/preload.js#L249-L270
I wonder if there is any way better for a paste action, so we can do that in nightmare.

In addition, in some cases paste could be a better replacement of type, tricking around the input stuffs.
We could just do a brute paste instead of triggering some keydown/keyup event.

**Comment by rosshinkley** [comment]
@fritx Could you use [`.insert()`](https://github.com/segmentio/nightmare#insertselector-text) instead?  That sends text directly to the specified selector.

**Comment by fritx** [comment]
Hey, @rosshinkley, i'm afraid not.
I need to somehow trigger the inputbox to react the action.
"Insert" does not trigger events, but "Paste" does.
Paste can also bring images too (if it is copied).

```js
document.execCommand('paste')
```

**Comment by rosshinkley** [comment]
@fritx Are you thinking of something like [`webContents.paste()`](https://github.com/electron/electron/blob/master/docs/api/web-contents.md#webcontentspaste)?

**Comment by rosshinkley** [comment]
Adding edit actions could be accomplished with `.action()`.  

With the ability to do so, I'm considering this issue resolved.  Closing.
