### ISSUE TITLE
Unable to run the co-mocha example

### ISSUE THREAD

**Issue by riston** [segmentio/nightmare#275]
I have problems with running the mocha test example, seems like some module version issue. I am running Arch Linux, tried both node v0.12 and v4.1.2 both have same problem.

The file is in directory `test/main-test.js`.

```js
var Nightmare = require('nightmare');
var expect = require('chai').expect; // jshint ignore:line

describe('test yahoo search results', function() {

  it('should find the nightmare github link first', function*() {

    var nightmare = Nightmare()
    var breadcrumb = yield nightmare
      .goto('http://yahoo.com')
      .type('input[title="Search"]', 'github nightmare')
      .click('.searchsubmit')
      .wait('.url.breadcrumb')
      .evaluate(function () {
        return document.querySelector('.url.breadcrumb').innerText;
      });
    expect(breadcrumb).to.equal('github.com');
  });
});
```

Installed following modules `package.json`

```js
{
  "name": "app-smoke-test",
  "private": "true",
  "description": "Flow testing",
  "version": "0.0.1",
  "engines": {
    "node": "~4.1.2"
  },
  "scripts": {
    "test": ""
  },
  "dependencies": {},
  "devDependencies": {
    "chai": "^3.3.0",
    "co-mocha": "^1.0.1",
    "mocha": "^2.3.0",
    "nightmare": "^2.0.7"
  }
}
```

Added `mocha.opts`

```
--slow 3s
--timeout 10s
--require co-mocha
```

Used following command line to trigger mocha runner which ends error, seems like some generators handling is broken `node_modules/.bin/mocha --harmony`. I also tried to run the nightmare package tests which works well.

The mocha result:

```
node_modules/.bin/mocha --harmony


  test yahoo search results
    1) should find the nightmare github link first


  0 passing (10s)
  1 failing

  1) test yahoo search results should find the nightmare github link first:
     Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.
```

**Comment by kuraga** [comment]
+1
@riston , any news?
@segmentio , can you help us, please?

**Comment by kuraga** [comment]
See https://github.com/vdemedes/mocha-generators instead of `co-mocha`

**Comment by riston** [comment]
@kuraga did you get the example working, I switched to your suggested `mocha-generators` library which seems to at least output errors. I am not sure why spawning an electron process fails ?

`Error: spawn /home/risto/deekit/scripts/flow-tests/node_modules/nightmare/node_modules/electron-prebuilt/dist/electron ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1046:32)
    at child_process.js:1137:20`

**Comment by kuraga** [comment]
That's something else. Reinstall Electron and Nightmare?

**Comment by riston** [comment]
True that's something else, made clean install and now it's working. Actually it seems the original test case should "work" from the test execution part. The only problem is that some of the test steps seems to fail which does not throw errors but instead timeout. This is really annoying problem when you have no clue where the test just broke.

**Comment by reinpk** [comment]
https://github.com/segmentio/nightmare/blob/master/Readme.md#examples

sorry fellas, just updated the examples to fit with yahoo.com's classname changes

**Comment by nhducit** [comment]
I got this issue too when I run mocha example, then I found that I should increase the timeout of mocha test suit by adding this line:
```js
this.timeout(20000);
```
Should I create a pull request to add this fix?
```js
var Nightmare = require('nightmare');
var expect = require('chai').expect; // jshint ignore:line

describe('test yahoo search results', function() {
  this.timeout(20000); //<======= add this line
  it('should find the nightmare github link first', function(done) {
    var nightmare = Nightmare()
    nightmare
      .goto('http://yahoo.com')
      .type('form[action*="/search"] [name=p]', 'github nightmare')
      .click('form[action*="/search"] [type=submit]')
      .wait('#main')
      .evaluate(function () {
        return document.querySelector('#main .searchCenterMiddle li a').href
      })
      .end()
      .then(function(link) {
        expect(link).to.equal('https://github.com/segmentio/nightmare');
        done();
      })
  });
});
```

**Comment by rosshinkley** [comment]
@nhducit Memory serving, the default Mocha timeout is something like 2s.  The test suite sets this to [10s](https://github.com/segmentio/nightmare/blob/master/test/mocha.opts#L2).

It might be more helpful to put an example mocha command to run with the test options.  Thoughts?
