### ISSUE TITLE
dom tree only 

### ISSUE THREAD

**Issue by jney** [segmentio/nightmare#277]
is it possible to block specific ressources ? (ie : images, css, or facebook scripts) as i only want to acceed to generated dom tree very quicly ?

**Comment by jney** [comment]
on `phantomjs-node`, we can do : 

```js
page.onResourceRequested(function (data, request) { request.abort() })
```

**Comment by jney** [comment]
related to #258 maybe it should be considered as a duplicate

**Comment by reinpk** [comment]
based on my searching, i don't believe this is possible with electron, but happy to reopen if someone finds otherwise! sorry :/ definitely see the utility there...

**Comment by aggied** [comment]
Untested, but I'm wondering if perhaps https://github.com/kyungw00k/nightmare-webrequest-addon might be of some help. Might be a way in there to listen for certain types of resources and block their loading
