### ISSUE TITLE
blocking function

### ISSUE THREAD

**Issue by jney** [segmentio/nightmare#278]
doing the following code, `console.log('after')` is called 1/10 times. most of the time it stays blocked

```es6
  const nightmare = Nightmare()
  console.log('before')
  const objects = yield nightmare
    .goto(url)
    .evaluate(function () {
      return 'noop'
    })
  console.log('after')

  yield nightmare.end()
  return objects
```

**Comment by matthewmueller** [comment]
what's the url?

**Comment by jney** [comment]
`http://fd5-courses.leclercdrive.fr/magasin-069401-Vitry-sur-Seine.aspx`

**Comment by rosshinkley** [comment]
@jney Is this still an issue?

**Comment by jney** [comment]
i just tried it now (i don't use nightmare for now) and it works !
thank you
