### ISSUE TITLE
Let's use mocha-generators instead of co-mocha?

### ISSUE THREAD

**Issue by kuraga** [segmentio/nightmare#279]
Let's use [mocha-generators](https://github.com/vdemedes/mocha-generators) instead of [co-mocha](https://github.com/blakeembrey/co-mocha) in tests?
It's more lightweight and predictable.
See also #275 .

**Comment by matthewmueller** [comment]
sure, if it'll fix some issues, it doesn't really matter to me

**Comment by LarryBattle** [comment]
This issue should be closed.
