### ISSUE TITLE
Electron processes don't exit after tests finish

### ISSUE THREAD

**Issue by kuraga** [segmentio/nightmare#280]
Electron processes don't exit after tests finish.
Is it expected behavior?

If no, is it Nightmare issue?

Thanks!

**Comment by danhalliday** [comment]
I found this too — I realised you need to call `end()` when you're done:

    after(function*() {
      yield nightmare.end();
    });

Hope that helps!

**Comment by kuraga** [comment]
@danhalliday , thanks!

Let's mention in docs?

**Comment by reinpk** [comment]
https://github.com/segmentio/nightmare#end
