### ISSUE TITLE
each()

### ISSUE THREAD

**Issue by timothylhuillier** [segmentio/nightmare#283]
Hi,

It's possible to use each function ?
I would like to crawl comments and click on the paginate (javascript paginate) when there aren't comments.

Thanks,

**Comment by matthewmueller** [comment]
The nice thing about generators is that you can use them inside control flow loops, so you could  do something like:

```js
while (pages.length) {
  var page = pages.pop()
  var response = yield nightmare
    .goto(page)
    .evaluate(fn)
}
```
