### ISSUE TITLE
Nightmare() just lock the application

### ISSUE THREAD

**Issue by EZaca** [segmentio/nightmare#284]
I just copied the `cnn.js` example from the docs here and started it with `node --harmony cnn.js`.
When it start, it *does not* show any error or anything. It just stop when calling `Nightmare()` and do not go on nor terminate the application.
Everytime I try to call `Nightmare()` (in any code) it just stop on the function.

Further information:
```
Linux Mint 17.1 Rebecca
Node v0.12.2
"npm -v nightmare": 2.7.4
Node packages installed:
  npm install --save nightmare
  npm install vo
```

**Question 1:** Does Nightmare require some other package or applciation?
**Question 2:** Any idea why the function is locking the node application? It's just me?

**Comment by LarryBattle** [comment]
I tested `cnn.js` using node v0.12.2 and worked. 
The problem might be that you have a slow connection to cnn.com.
For simplicity, change the url to `example.com` and see if the `cnn.js` script works.

Or add this file to root of the nightmare directory and run this.
**nightmare_example_com_test.js**

    var Nightmare = require('../nightmare');
    var vo = require('vo');
    
    vo(run)(function(err, result) {
        if (err) throw err;
    });
    
    function* run() {
        var nightmare = Nightmare();
        var title = yield nightmare
            .goto('http://example.com')
            .evaluate(function() {
                return document.title;
            });
        console.log("Title: ", title);
        yield nightmare.end();
    }

Expected output:

    Title:  Example Domain

**Comment by reinpk** [comment]
no additional requirements, but added another complete example here: https://github.com/segmentio/nightmare#examples

you can also try the `DEBUG=*` flag to see what's happening:
https://github.com/segmentio/nightmare/blob/master/Readme.md#debugging

**Comment by lichunqiang** [comment]
Hi. Can you help me?

this is my test code:
```
var debug = require('debug')('test:nightmare');
var vo = require('vo');
var Nightmare = require('nightmare');

vo(run)(function(err, result) {
  if (err) throw err;
  debug(result);
});

function* run() {
  var nightmare = Nightmare();
  var title = yield nightmare
    .goto('http://www.bing.com')
    .evaluate(function() {
      return document.title;
    });
  console.log("Title: ", title);
  yield nightmare.end();
  return title;
}

```

It's works fine on windows. but the same problem that application blocked on linux(centos)

This is my debug information`DEBUG=* node --harmony test.js`

```
  nightmare queueing action "goto" for http://www.bing.com +0ms
  nightmare queueing action "evaluate" +5ms
```
That's all the log...
