### ISSUE TITLE
V2 inject() action doesn't work

### ISSUE THREAD

**Issue by FredXue** [segmentio/nightmare#285]
Here is my test script:
        
      var Nightmare = require('nightmare');
      var vo = require('vo');
      var tp = 'test', page_tag = 'artist_page';
        vo(run)(function(err,result) {
          if (err) throw err;
         });

        function *run() {
            var nightmare = Nightmare();
            yield nightmare
           .goto('http://google.com')
           .inject('js','anotherjs.js')
           .evaluate(function(tp,page_tag) {
               ev(tp,page_tag);
            });
   
             yield nightmare.end();
       }

"anotherjs.js" file just contains a function called ev() which  is invoked in the .evalute() action.
              function ev(tp,page_tag){
            		var loadtiming =  new Date().getTime()-window.performance.timing.navigationStart;
                        var xhr = new XMLHttpRequest();
	               xhr.open( "post", "http://localhost:8887/postkf", false);
		       xhr.setRequestHeader("Content-Type","application/x-www-form-urlencoded");
                       xhr.send('client_id='+page_tag+'&topic='+tp+'&msg='+loadtiming);
             };

I send a message to a server machine in function ev().  But, in this way, the server cannot receive the request.  I cannot figure out where goes wrong.

**Comment by LarryBattle** [comment]
It seems that `ev()` is receiving undefined values.
Pass in `tp` and `page_tag` as additional arguments to `.evaluate()`
Example:

	.evaluate(function(tpVal,page_tagVal) {
		ev(tpVal, page_tagVal);
	}, tp, page_tag);

**Comment by FredXue** [comment]
@LarryBattle  Ah, sorry for missing the arguments in evaluate(). However, it still doesn't work.

**Comment by smallcar88** [comment]
It semms that the ev() is in browser client scope while the .evaluate() is in nightmare (phantomjs) scope. 
Maybe you should try .use(plugin) for the sub-routine (sending local server a message) in the phantomjs scope after the .evaluate() return the desired values?

**Comment by LarryBattle** [comment]
Make `ev()` global by in `anotherjs.js` by adding `this.ev = ev` at the end of the file.
Example:

	  function ev(tp, page_tag) {
	      var loadtiming = new Date().getTime() - window.performance.timing.navigationStart;
	      var xhr = new XMLHttpRequest();
	      xhr.open("post", "http://localhost:8887/postkf", false);
	      xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
	      xhr.send('client_id=' + page_tag + '&topic=' + tp + '&msg=' + loadtiming);
	  };
	  this.ev = ev
	  window.ev = ev

`undefined` is returned when there's a problem with your script. So for testing have `.evalulate()` 
return the source of `ev()` to see if it exist or not.

Example:

	  var evSource = yield nightmare
	      .goto(url)
	      .inject("js", "another_js.js")
	      .evaluate(function(tpVal, page_tagVal) {
	          if (this.ev) this.ev(tpVal, page_tagVal);
	          return String(this.ev || "Can't find ev()")
	      }, tp, page_tag);

	  console.log(evSource);

**Comment by FredXue** [comment]
Great!  it works.  I really need to practice JS coding more.  LOL.        Really appreciate your help!  @LarryBattle
