### ISSUE TITLE
Stops scraping after several good scrapes

### ISSUE THREAD

**Issue by souly1** [segmentio/nightmare#292]
At the beginning looks ok but around the 15th attempt it just refuses to work, loading about 20 instances of Electron and dying on me. 

for each call I use:

var result = yield nightmare
      .useragent('....')
      .viewport(1000, 1000)
      .goto(uri)
      .wait(2000)
      .evaluate(function () {
        return document.querySelector('.blabla').innerHTML;
      });
    yield nightmare.end();

**Comment by danhalliday** [comment]
Not sure about Nightmare loading multiple instances of Electron, but to start narrowing it down, how about `wait()`ing on the HTML element rather than setting a timeout? That would at least show you whether the expected element is showing up on the failed run.

    .wait(2000) -> .wait(".blabla") ...

**Comment by souly1** [comment]
Thanks @danhalliday for the reply, the issue was something completely different in the code with illegal values, sorry I forgot to remove this issue.
