### ISSUE TITLE
:hover not set on mouseover

### ISSUE THREAD

**Issue by psimyn** [segmentio/nightmare#294]
When using `nightmare.mouseover` the :hover pseudo class isn't triggered in the browser. Looking into it a bit has largely convinced me to not hover events for anything other than cosmetic changes. But to allow screenshots to show effect of mouse hover it could be pretty useful.

Workaround I have is to alias all :hover styles with a `--hover` class, then add the class to `element` inside `nightmare.mouseover`.

As I understand it, this is caused by Chromium not triggering the :hover pseudo class on mouseenter. Issue is possibly covered by [this chromium issue](https://code.google.com/p/chromium/issues/detail?id=486176)).

Curious if you have any thoughts, or I'm missing something more obvious. Thanks!

**Comment by reinpk** [comment]
yeah, it appears to be an underlying bug in chromium: https://github.com/atom/electron/issues/2797

unfortunately going to close here since it's several layers down :/
