### ISSUE TITLE
Basic examples don't work

### ISSUE THREAD

**Issue by mlmarius** [segmentio/nightmare#295]
Hi. I want to give it a try but the basic examples don't work for me. I read everything and searched the web for my errors but can't get nightmare do do anything. I can't even run the tests. The docs don't say how and going into the nightmare dir, running npm install and node tests/index.js dosn't do it either. I paste the example scripts and try to run them and i get this:

>/nodeapps/nightmare_app/index.js:2
>yield Nightmare()
>           ^^^^^^^^^
>SyntaxError: Unexpected identifier
>    at exports.runInThisContext (vm.js:73:16)
>    at Module._compile (module.js:443:25)
>    at Object.Module._extensions..js (module.js:478:10)
>    at Module.load (module.js:355:32)
>    at Function.Module._load (module.js:310:12)
>    at Function.Module.runMain (module.js:501:10)
>    at startup (node.js:129:16)
>    at node.js:814:3

i am running it like so:  
```
node --harmony --harmony_proxies index.js
```
. no luck at all. is that what it's supposed to do ? give me nightmares ?

P.S. this is the code ( running on CentOS 7 ):

```javascript
var Nightmare = require('nightmare');
yield Nightmare()
  .goto('http://yahoo.com')
  .type('input[title="Search"]', 'github nightmare')
  .click('.searchsubmit');
```

Does anyone know how to get it working ?

**Comment by matthewmueller** [comment]
You have to wrap it in `co` or `vo`

```js
vo(function * () {
  var Nightmare = require('nightmare');
yield Nightmare()
  .goto('http://yahoo.com')
  .type('input[title="Search"]', 'github nightmare')
  .click('.searchsubmit');
})(function (err) {
  
})
```

@reinpk maybe we should change this to avoid confusion

**Comment by laychopy** [comment]
@matthewmueller Yes, you should change the example, because you want start try it out and you got this error it's frustrating at the beginning.

**Comment by reinpk** [comment]
thanks! updated here: https://github.com/segmentio/nightmare/blob/master/Readme.md#examples
