### ISSUE TITLE
Is it possible to wait for 'did-finish-load'

### ISSUE THREAD

**Issue by CatTail** [segmentio/nightmare#297]
I wan't to wait for 'did-finish-load' event fired and take a screenshot, is there a nicer way of doing this?

```js
var loaded = false;
yield nightmare
    .on('did-finish-load', function() {
        loaded = true;
    })
    .goto(link)
    .wait(function() {
        return loaded;
    })
    .screenshot('test.png')
```

And because of the #251 , even the example above can't work!

**Comment by FdezRomero** [comment]
@CatTail `.evaluate()` internally waits for the `did-finish-load` event before running. So you can replace the `.wait()` with `.evaluate()`, like this:

```javascript
yield nightmare
    .goto(link)
    .evaluate(function() {
        return false;
    })
    .screenshot('test.png')
    .end();
``` 

It's a little bit hacky because the internal implementation can change, but it should work.

**Comment by sintanial** [comment]
@CatTail if still relevant, i solved this issue in this ticket https://github.com/segmentio/nightmare/issues/481
