### ISSUE TITLE
Custom request header

### ISSUE THREAD

**Issue by kevinprotoss** [segmentio/nightmare#309]
Hi, 

Great work, at first.
I use this module to replace phantom for web page automation. However, I need to set custom header or `accept-language` header of the requests.

How can I achieve that?

Best regards,
Kevin

**Comment by fr-** [comment]
I've got a feature branch that implements passing options to goto. With this you can add headers to your request. @reinpk if you think this is an appropriate pull request, let me know. Here's the branch: https://github.com/fr-/nightmare/commit/21fb1eb597ad85981333583ec7dc33098ea309e2

**Comment by rosshinkley** [comment]
@kevinprotoss @fr- Could you use `.header()` to accomplish this?

**Comment by rosshinkley** [comment]
Closing as I think this is solvable with the existing implementation.  If this is still an issue, feel free to reopen or open a new issue.
