### ISSUE TITLE
PDF to format other than A4

### ISSUE THREAD

**Issue by dolphub** [segmentio/nightmare#311]
Is it possible to export a page to pdf that forces a specific aspect ratio / resolution?

**Comment by reinpk** [comment]
not sure tbh, that would depend on the underlying electron implementation, which nightmare just passes through to:
* https://github.com/segmentio/nightmare#pdfpath-options
* http://electron.atom.io/docs/v0.30.0/api/browser-window/#webcontents-printtopdf-options-callback
