### ISSUE TITLE
Retrieving response headers and code

### ISSUE THREAD

**Issue by michenriksen** [segmentio/nightmare#312]
Hi,

I am currently looking for alternatives to PhantomJS for a project of mine and Nightmare looks very promising!

However, I need to be able to retrieve response details such as response code and response headers. Is it possible to get this information with Nightmare somehow?

**Comment by reinpk** [comment]
check out `did-get-response-details`:
https://github.com/segmentio/nightmare#onevent-callback

**Comment by scarletsky** [comment]
@reinpk I've try to capture `did-get-response-details` event, but I got EVERY response of the resources(js, css, images...) in the page. I only want the main page's response info.

Is there any way to do this?

**Comment by matthewmueller** [comment]
@scarletsky as far as i know you'd need to filter for the resource you are looking for yourself
