### ISSUE TITLE
Times out on TravisCI

### ISSUE THREAD

**Issue by dbkaplun** [segmentio/nightmare#313]
See [Build #1](https://travis-ci.org/dbkaplun/domscii/builds/87059257) for [dbkaplun/domscii](https://github.com/dbkaplun/domscii). Runs great locally but fails on TravisCI due to timeouts.

See also travis-ci/travis-ci#5002

**Comment by juliangruber** [comment]
https://github.com/juliangruber/electron-stream#travis

**Comment by dbkaplun** [comment]
Aha, thanks @juliangruber!

**Comment by matthewmueller** [comment]
@juliangruber nice!

**Comment by justinmchase** [comment]
:+1:
