### ISSUE TITLE
Install Problems

### ISSUE THREAD

**Issue by emgould** [segmentio/nightmare#314]
Node version 4.2.1
Mac Os 10.10.5

Running: node --harmony test.js

Test script is the cnn test but with { show: true } passed to the constructor.    A window pops up titled Electron but is hung.  Have to kill the process and kill the script.  Any thoughts on what I am doing wrong?

**Comment by rosshinkley** [comment]
@emgould Everything there looks fine to me.  Are you still having this problem with later versions of Nightmare?

**Comment by rosshinkley** [comment]
Due to lack of attention and issue age, I'm going to close this issue.  If you're still having this problem, feel free to reopen/ file a new issue.
