### ISSUE TITLE
Having problem runnnig a script after switching pc

### ISSUE THREAD

**Issue by DavidBarishev** [segmentio/nightmare#317]
Hello! <br>
I have a script using nightmare and which works on my pc ,and couldnt get it working on another pc.
This is the error im getting :  
```
Error: spawn D:\Projects\Lounge\Lounge\node_modules\electron-prebuilt\dist\elect
ron.exe ENOENT
    at exports._errnoException (util.js:874:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)
    at Function.Module.runMain (module.js:469:11)
    at startup (node.js:134:18)
    at node.js:961:3
```

It seems like its searching for the electron on my pc's path , how could i change it? I have the electron exec , in the node moudle , but the path is diffrent (F:\Lounge\Lounge\node_modules\electron-prebuilt\dist\electron.exe)

**Comment by reinpk** [comment]
sorry i'm not sure, been a long time since i had a pc around :/ stackoverflow is the better source for these path questions!

**Comment by hovosanoyan** [comment]
Hello. Maybe it's late but anyway. I had the same trouble and searched more and found solution for me. The path.txt file which is located in "nightmare\node_modules\electron-prebuilt" containe path where it is installed so you have to change it for current module location.
