### ISSUE TITLE
Tests always pass regardless of implementation

### ISSUE THREAD

**Issue by ThibWeb** [segmentio/nightmare#321]
While trying to use the `page-error` and `page-load` events inside one of my scripts, I discovered that all of the project's tests are passing no matter what is being tested. This seems to be the case since 08bd260 (PR #281, switching from co-mocha to mocha-generators).

To reproduce, in `test/index.js`:

```js
it('should be constructable', function*() {
    var nightmare = Nightmare();
    nightmare.should.be.ok;
    yield nightmare.end();
  });
```

switch the test to `nightmare.should.equal('test');`.

I tried this on 2d6ddc8, and it does report the error.

As a result, I'm not sure if `page-error` and `page-log` are properly implemented, as the test passed no matter what. My test implementation doesn't work either.

**Comment by chrisgeo** [comment]
Take a look at #290

**Comment by ThibWeb** [comment]
That's it! Thanks @chrisgeo.
