### ISSUE TITLE
nightmare hangs on .evaluate()

### ISSUE THREAD

**Issue by davis** [segmentio/nightmare#322]
running with babel-node for es6 stuff

```
vo(...urls.map(run), endN)(end);

function run(url) {
  return function*() {
    const title = yield nightmare
      .goto(url)
      .evaluate(() => document.title);
    console.log(`crawling: ${title}`);
    const html = yield nightmare
      .evaluate(() => document.documentElement.outerHTML);
    const savepath = `${md5(url)}.html`;
    console.log(`writing ${title} to ${savepath}`);
    fs.writeFile(savepath, html, 'utf8');
  };
}

function* endN() {
  yield nightmare.end();
}

function end(err, res) {
  if (err) throw err;
  if (res) console.log(res);
}
```

it always gets stuck at
```
nightmare queueing action "evaluate" +1ms
```

**Comment by davis** [comment]
it runs fine if i remove all `.evaluate` blocks

**Comment by davis** [comment]
it always get stuck at
```
nightmare queueing action "evaluate" +1ms
```

**Comment by davis** [comment]
even replacing the `evaluate(() => document.title);` to  `evaluate(() => 'hello');` causes it to hang

**Comment by smallcar88** [comment]
+1 for the issue.
I have this issue occasionally. Like a random event
I don't know where to get the chromium debeg info.

**Comment by reinpk** [comment]
could this be related to #320?

**Comment by edasque** [comment]
I think this might be an ES6 issue. I have the same problem with running nightmare on ES6 with node v4.2.3

**Comment by rosshinkley** [comment]
Upon further investigation, I can't recreate this behavior.  Doing something like:

```js
var nightmare = require('nightmare')(),
  vo = require('vo');

var run = function * () {
  return yield nightmare.goto('http://example.com')
    .evaluate(() => document.title)
};

vo(run)(function(err, val) {
  console.dir(val);
});
```

@edasque @smallcar88 @davis Are you still experiencing problems with `.evaluate()` and fat-arrow functions?

**Comment by davis** [comment]
@rosshinkley i haven't used nightmare in a long time, but yes it was with fat arrow functions, thought it shouldn't have mattered either way because I was transpiling down to es5 before running...

**Comment by rosshinkley** [comment]
@davis Hm, I'd be curious what transpiler you were using - it _should_ have worked.  At any rate, the ES6 features you needed are now supported out of the box with Node 4+, so I'm going to consider this issue closed.  If you continue to have this problem, feel free to reopen/open a new issue.
