### ISSUE TITLE
Bump electron and expose extraHeaders to goto?

### ISSUE THREAD

**Issue by danielstjules** [segmentio/nightmare#325]
As of electron 0.34, you can override headers as part of loadUrl: https://github.com/atom/electron/pull/3227

``` javascript
webContents.loadUrl('https://www.example.com', {
  extraHeaders: 'Accept-Encoding: gzip;q=0,deflate;q=0'
});
```

It'd be great if goto could accept a second argument that included these headers. Happy to submit a PR if interested. :)

**Comment by reinpk** [comment]
definitely interested... language settings and basic auth could maybe be supported now too?

**Comment by danielstjules** [comment]
Yup! Would you want to expose the extraHeaders argument as a string like in electron, or improve on the API a bit and allow passing a headers object instead?

**Comment by reinpk** [comment]
seems like allowing a sticky `.header()` and then the additional parameter for loading a single url?

**Comment by danielstjules** [comment]
Since I may have misunderstood, do you mean adding two things?
* `.headers(object)`
* optional goto param, `.goto(url, headers)`

I'd assume you prefer a headers object to the headers string electron uses?
