### ISSUE TITLE
Page selection/range support for .pdf()

### ISSUE THREAD

**Issue by dbkaplun** [segmentio/nightmare#330]
According to [the docs](https://github.com/segmentio/nightmare#pdfpath-options) (which refer to [these docs](http://electron.atom.io/docs/v0.30.0/api/browser-window/#webcontents-printtopdf-options-callback)), doesn't look like there's a way to select what pages to export to PDF. Would be great if there was!

**Comment by rosshinkley** [comment]
Could you print to PDF and then use GhostScript to trim off the pages you don't want (see tip [here](http://www.linuxjournal.com/content/tech-tip-extract-pages-pdf))?  That would allow you trim pages from the document.

Not that introducing another dependency would be ideal, but it is an option.

It _looks_ like Electron supports partial selections to print to PDF, but the documentation is lean on how such selections are made.  (It looks like you can select all, and unselect, but it isn't clear how to do partial selections).

**Comment by matthewmueller** [comment]
yah, i think you'd want to do this outside of nightmare
