### ISSUE TITLE
When goto is too long

### ISSUE THREAD

**Issue by jtunggit** [segmentio/nightmare#331]
I use nightmare like there
vo(function* () {
    var nightmare = Nightmare({timeout: 6000, show: true,"web-preferences":{"web-security":false}});
    var link = yield nightmare
        .goto('https://www.marriott.com.cn/Channels/rewards/signIn-cn.mi')
        .type(#'field-user-id', "user")
        .evaluate(function () {
            return alert('ok');
        });
    yield nightmare.end();
    return link;
})(function (err, result) {
    if (err) return console.log(err);
    console.log(result);
});

It has no type in the user to the input and has no alert the msg,I see the log is loading the resource,but I can see the window is loaded,is it there any way to set the css,js and the other request is timeout in a few time or can ignore the other request to execute the type function ?

**Comment by rosshinkley** [comment]
I think you hit the same issue as #345.  When you set `web-preferences`, the sugar that allows Nightmare to work is overwritten.  This is fixed with #348, pending approval.
