### ISSUE TITLE
Can't get examples to work

### ISSUE THREAD

**Issue by simonsez** [segmentio/nightmare#341]
I'm new to nightmare, and thought I'd start with your mocha example to see how to use it.

I copy:
```
var Nightmare = require('nightmare');
var expect = require('chai').expect; // jshint ignore:line

describe('test yahoo search results', function() {
  it('should find the nightmare github link first', function*() {
    var nightmare = Nightmare()
    var link = yield nightmare
      .goto('http://yahoo.com')
      .type('input[title="Search"]', 'github nightmare')
      .click('.searchsubmit')
      .wait('.ac-21th')
      .evaluate(function () {
        return document.getElementsByClassName('ac-21th')[0].href;
      });
    expect(link).to.equal('https://github.com/segmentio/nightmare');
  });
});
```

And the output:

```
simonsez@MacBook-Pro $ ../node_modules/mocha/bin/mocha

  test yahoo search results
    ✓ should find the nightmare github link first

  1 passing (11ms)
```

Okay, great looks good. But just to ensure I understand how it works I changed

```
    expect(link).to.equal('https://github.com/segmentio/');
```

This shouldn't succeed if I've changed the string.

```
 test yahoo search results
    ✓ should find the nightmare github link first

  1 passing (13ms)
```

So it doesn't seem to actually run the tests as I expect them. Am I missing something?

**Comment by fmaruki** [comment]
Are you using mocha-generators?
The regular mocha don't know how to call generator functions, it will just create the iterator object and never call .next() on it; ie, your test will always pass because the line with .expect() will never be executed.

**Comment by simonsez** [comment]
@fmaruki thanks - yes, adding `require('mocha-generators').install();` resolved it.

Seems like the readme should include that line?

**Comment by istr** [comment]
Definitely. At least the test suite should contain a test that mocha-generators is in place and working.

The "test always passing" problem is present within nightmare's own test suite, too.
Running the nightmare test suite on a vanilla checkout just happily "passes" even though lots of tests fail for me after removing the fancy new ES6/ES7 stuff. Simple check: add ```throw new Error('FAIL');``` to any of the tests and run the test suite again (```make test``` or ```npm test```) -- it passes.

(node version 0.12.7, npm version 3.3.5 on an Ubuntu 14.04.3 LTS (trusty))
