### ISSUE TITLE
Nightmare JS Tor sockets connector

### ISSUE THREAD

**Issue by ilabvb** [segmentio/nightmare#343]
Hello, does nightmarejs allow page access through a tor socket (https://www.torproject.org)?
Is it planned to provide this feature?

Thank you.

**Comment by matthewmueller** [comment]
nothing planned, but we'd like to support proxies at some point, here's a good place to start #241. We'd gladly accept a PR :-)

**Comment by codenessjl** [comment]
does anyone get "ERR_NO_SUPPORTED_PROXIES" when use proxy in nightmare?
