### ISSUE TITLE
how to store cookies in a file and load it from file?

### ISSUE THREAD

**Issue by zxdvd** [segmentio/nightmare#344]
I can keep cookies in a file with phantoms.

Since nightmare moved to  Electron, is there any document about how to store cookies so that I needn't to do the login trick again and again.

Thanks.

**Comment by rosshinkley** [comment]
Electron maintains sessions and cookies across logins in a partition (see [here](http://electron.atom.io/docs/v0.34.0/api/browser-window/#new-browserwindow-options)).  You shouldn't have to log in every time provided you're using the same persisted session.  By default, I believe Nightmare uses the default Electron partition, which does get persisted.

As an aside, there is currently no choice _but_ to use the default partition as trying to use a [different session breaks Nightmare](https://github.com/segmentio/nightmare/issues/345).

If you are wondering how to load cookies from scratch into a new partition, that is a topic of lengthy [discussion on the Electron repo](https://github.com/atom/electron/issues/959), the TLDR is that it's not currently possible.

**Comment by rosshinkley** [comment]
#345 has been fixed, and this issue has not had activity in quite a while, so I'm going to close it.  If you have any more questions, feel free to reopen or file a new issue.

**Comment by daniel3d** [comment]
@rosshinkley Hi for some reason the partition is not working for me
https://github.com/segmentio/nightmare/issues/754
