### ISSUE TITLE
Execute rightclick ?

### ISSUE THREAD

**Issue by Olegatro** [segmentio/nightmare#346]
Hi, how execute right click on element ?

**Comment by rosshinkley** [comment]
At present, I don't think it is _directly_ possible, but you could potentially use `evaluate` or `file` to inject your own rightclick handler.

**Comment by rosshinkley** [comment]
For what's worth, I hastily threw together a `rightClick` action on [my fork](https://github.com/rosshinkley/nightmare/blob/rightclick/lib/actions.js#L84-L132).  It _technically_ works, at least in my local sandboxes.  I'm not super-comfortable with issuing a PR, as I'm not sure `contextmenu` is really the correct way for client-side javascript to generate/handle right-click events.

Thoughts? /cc @reinpk

**Comment by Olegatro** [comment]
@rosshinkley Thanks! I will try use your fork.

**Comment by inversion** [comment]
I've submitted a PR for sendInputEvent in Electron which lets you do this (though you'd need to calculate element co-ordinates yourself right now)

https://github.com/segmentio/nightmare/pull/361

**Comment by rosshinkley** [comment]
@inversion Far and away better than my implementation.  Thanks!

**Comment by rosshinkley** [comment]
Closed with `sendInputEvent` and `.action()` being exposed.

**Comment by bcherny** [comment]
Are you guys planning on shipping in a rightClick API with nightmare, or do consumers still have to roll this themselves?
