### ISSUE TITLE
evaluate can't get params if params is a function

### ISSUE THREAD

**Issue by scarletsky** [segmentio/nightmare#349]
```js
function* extractPage(page) {
    let test1 = true
    let test2 = () => true;

    const title1 = yield page.evaluate((test1) => {
        return test1 ? 1 : 2;
    }, test1);
    console.log(title1);
    const title2 = yield page.evaluate((test2) => {
        return test2() ? 2 : 3;
    }, test2);
    console.log(title2);
}
```

and this is what I get:
```
  nightmare queueing action "evaluate" +52ms
1
  nightmare queueing action "evaluate" +13ms
test2 is not a function
```

**Comment by davidmatas** [comment]
I think you can't pass functions or objects to `evaluate` https://github.com/segmentio/nightmare/issues/89#issuecomment-102769448

**Comment by yonatanmn** [comment]
Why is that? 
I really need utility functions in evaluate.

BTW - objects are passing, but without all methods.

**Comment by rosshinkley** [comment]
@yonatanmn Everything passed from Nightmare to Electron is serialized, and functions do not serialize nicely.  If you find that you need methods in `.evaluate()` commonly, you may want to look into defining a custom preload.

**Comment by yonatanmn** [comment]
I see, I'll take a look.
thx
