### ISSUE TITLE
Event Emitter Memory Leak: using evaluate function

### ISSUE THREAD

**Issue by bollywood-coder** [segmentio/nightmare#350]
Hi Nightmare Team

The 1st test uses the evaluate function to retrieve the document.title of the pages.
However, after the 10nth iteration, there is the warning of node of a potential memory leak problem with the event emitters (see screenshot).

The 2nd test shows no such things. Evaluate was removed completly.
Is this the correct behaviour of the evaluate function or do we have a bug here?

1. Test
--------
// with evaluate -> Memory Leak after the 10nth loop
function *start() {
var nightmare = new Nightmare({ show: true });
for (var i = 0; i < links.length; i++) {
var title = yield nightmare.goto(links[i]).evaluate(_extractTitle);
console.log(links[i], title);
}
yield nightmare.end();
}

2. Test
--------
// no evaluate -> everything runs fine!
function *start() {
var nightmare = new Nightmare({ show: true });
for (var i = 0; i < links.length; i++) {
var title = yield nightmare.goto(links[i]);
console.log(links[i], title);
}
yield nightmare.end();
}

Node version: 4.2.2
Nightmare version: 2.14.7

![issue](https://cloud.githubusercontent.com/assets/10127605/11236542/542c03c6-8dd2-11e5-9dcd-f32802632e6a.JPG)

Cheers
R.

**Comment by rosshinkley** [comment]
You may want to double-check the version of Nightmare you're on: `npm -v` shows the version of npm you're on and doesn't take a module name argument.  For that, you can try either `npm list nightmare` or `npm view nightmare version`.

I've tried to recreate your problem with Node v4.1.2 and Nightmare v2.0.7, and did not have the same results.

Could you run the above and report back what version of Nightmare you are on?

**Comment by bollywood-coder** [comment]
I am on nightmare 2.0.7 same like yours. Any idea what could be the problem?

**Comment by s0m3on3** [comment]
nightmare/lib/runner.js, lines 98-112
```javascript
parent.on('javascript', function(src) {
  renderer.once('response', function(event, response) {
    parent.emit('javascript', null, response);
  });

  renderer.once('error', function(event, error) {
    parent.emit('javascript', error);
  });

  renderer.once('log', function(event, args) {
    parent.emit.apply(parent, ['log'].concat(args));
  });

  win.webContents.executeJavaScript(src);
});
```
if response emitted => remove log and error listeners
if error emitted => remove response and log listeners
```javascript
parent.on('javascript', function(src) {
  function response(event, response) {
    renderer.removeListener('error', error);
    renderer.removeListener('log', log);
    parent.emit('javascript', null, response);
  }

  function error(event, error) {
    renderer.removeListener('response', response);
    renderer.removeListener('log', log);
    parent.emit('javascript', error);
  }

  function log(event, args) {
    parent.emit.apply(parent, ['log'].concat(args));
  }

  renderer.once('response', response);

  renderer.once('error', error);

  renderer.once('log', log);

  win.webContents.executeJavaScript(src);
});
```

**Comment by bollywood-coder** [comment]
could you copy here the test code which you run?

**Comment by s0m3on3** [comment]
```javascript
'use strict';

const co = require('co');
const Nightmare = require('nightmare');


let links = ['http://outlook.com'];

for (let i = 0; i < 30; ++i) {
    links.push(links[0]);
}

function* start() {
    var nightmare = new Nightmare({ show: true });
    for (var i = 0; i < links.length; i++) {
        var title = yield nightmare.goto(links[i]).evaluate(_extractTitle);
        console.log(i, links[i], title);
    }
    yield nightmare.end();
}


function _extractTitle() {
    return document.title;
}

co(function*() {
    try {
        yield* start();
    } catch (err) {
        console.error(err);
        console.error(err.stack);
    }
    process.exit();
});
```

**Comment by rosshinkley** [comment]
@s0m3on3 You shouldn't have to remove the event listener, that's the purpose of using [`EventEmitter.once`](https://nodejs.org/api/events.html#events_emitter_once_event_listener).  The listener should remove itself when the event handler is called.  Were you able to recreate the original issue?

@bollywood-coder It looks like you're running on Windows - I don't _think_ it would be Windows-specific, but just to rule it out, what version are you on?  I'd like to make sure this is tested on a similar environment.

I'm not convinced that the changes to runner.js are necessary.

**Comment by s0m3on3** [comment]
@rosshinkley yes, i recreated. "listener should remove itself when the **event handler is called**". if i will emit only `response` event, handlers for `error` & `log` from every `.evaluate()` will wait for `error` & `log` event

**Comment by rosshinkley** [comment]
@s0m3on3 I meant the original issue of having node complain about the EventEmitter leak.  I can't reproduce it locally, even though my event emitter listener limit is also set to 10 (which is the nodejs default).

And yes, see my edit: I misinterpreted what I read the first time.  That is my fault, and I apologize. :)  

@s0m3on3 is correct, and as a quick sanity check, I threw together an emitter watcher.  Sure enough, the counts go up but do not fall back down.  Interestingly, even after a couple dozen address changes, node does complain about extra event listeners.  (Maybe that's an issue with my environment?)

At any rate, your fix should be submitted as a PR as it should address @bollywood-coder's issues.

**Comment by s0m3on3** [comment]
may be. for example, webstorm dont show me any warnings, but console yes :)

**Comment by bollywood-coder** [comment]
@s0m3on3 thanks for the fix in the code! those once emitters can be tricky if not all of them are called ;)
glad i could help you guys to fix it.

**Comment by rosshinkley** [comment]
Is it possible this is related to #282?
