### ISSUE TITLE
Handling pop-up windows

### ISSUE THREAD

**Issue by kavuri** [segmentio/nightmare#352]
I have a scenario to handle a pop-up window that opens up via a javascript call in the main window. If I read the documentation correct, I need to use the .on('new-window', function()) method to handle the pop-up, but not sure how the callback needs to be handled. I need to further perform some selections and clicks on the new pop-up

Can anyone point me to an example on how I can achieve this? Thanks

**Comment by rosshinkley** [comment]
It may be worth looking at [this comment](https://github.com/segmentio/nightmare/issues/510#issuecomment-189782115).  I wrote a plugin to at least partially handle this case.

Merging this into #593.
