### ISSUE TITLE
[question] implement callback function callable within evaluate

### ISSUE THREAD

**Issue by fentas** [segmentio/nightmare#354]
Hey there,
is there a way to implement a callback function callable within evaluate?
Like this
```js
nightmare.on('nightmare-message', function(mixed) {
 //do stuff
 console.log(mixed)
})
nightmare
 .goto('example.com')
 .evaluate(function() {
   //do browser stuff
   var myobject = {...}
   //[...]
   window.nightmare(myobject)
   //[...]
   window.nightmare("hello")
 })
```

**Comment by rosshinkley** [comment]
Short answer is no, I don't think so, at least not in the way you're imagining.

However, I think you could use `yield` to get your desired effect.  Something like the following:

```javascript
var Nightmare = require('nightmare'),
    vo = require('vo');

function nightmareMessage(mixed) {
    //do stuff
    console.log(mixed)
};

function *run() {
    var nightmare = new Nightmare();
    var myobject = yield nightmare
        .goto('http://example.com')
        .evaluate(function() {
            //do browser stuff
            var myobject = {...};
            //[...]
            return myobject;
        });
    nightmareMessage(myobject);

    var message = yield nightmare.evaluate(function() {
        //[...]
        return "hello";
    });
    nightmareMessage(message);
};

vo(run)(function(err){
    console.log('done');
});
```

**Comment by fentas** [comment]
Hm. This is not really sutiable for my usecase. I want to be able to trigger a "log time" process giving status updates on the go. @rosshinkley Your example only (my perspective) would work (my use case) if I would trigger the process and then check in a certain interval if there is any update. - no "live data".

I had a quick look  through the source an found this
```js
window.__nightmare = {};
__nightmare.ipc = require('ipc');
__nightmare.sliced = require('sliced');

window.addEventListener('error', function(e) {
  __nightmare.ipc.send('page-error', e.message, e.error.stack);
});
```

Can't I utilize somehow `__nightmare.ipc.send` ? (or I am on the wrong track..)

**Comment by rosshinkley** [comment]
@fentas Ah, I see.  Using `yield` and `evaluate` in this manner probably wouldn't work then. :)

I also take it you're trying to go beyond using `console.log` and the `DEBUG` environment variable?

If so, I'm not sure you can set up ad hoc events with `__nightmare.ipc.send`.  My gut instinct is no, as the event from `ipc` needs to be emitted up through the Electron process to Nightmare.  I don't _think_ the plumbing for that exists.  I'll have to play with it to see.

**Comment by matthewmueller** [comment]
I think the way to this would be to use the `ipc.send('customevent', args)` functionality to send your events, which is in scope: https://github.com/segmentio/nightmare/blob/master/lib/javascript.js#L21-L24

There would need to be some addition logic on nightmare to set up something like: `nightmare.bind('customevent', fn)` in: https://github.com/segmentio/nightmare/blob/master/lib/nightmare.js#L225-L228

Which would tell the child to listen for that custom event and forward onto the node process: https://github.com/segmentio/nightmare/blob/master/lib/runner.js

Probably won't get around to implementing this myself, but I'd accept a PR that implements this :-)

**Comment by rosshinkley** [comment]
@matthewmueller I (embarrassingly) missed the `ipc.send`.  That's handy.

I think I'm on the same train of thought - I was tinkering with adding user-customizable events to accomplish what @fentas needed and have at least some of the basic mechanics down.  As time permits, I'll see if I can pull together the changes + documentation required. :)

**Comment by rosshinkley** [comment]
@fentas Custom eventing is now a plugin: [nightmare-custom-event](https://github.com/rosshinkley/nightmare-custom-event).  I'm going to go ahead and close this item.  If you have any more questions, feel free to reopen/open another issue.
