### ISSUE TITLE
Passing arguments to wait(fn)

### ISSUE THREAD

**Issue by yoz** [segmentio/nightmare#356]
There appears to be no way to pass parameters from node to the browser for wait() functions, though it is possible with evaluate().

For example, I expect the usage might look like:
```
yield nightmare.wait(function(expected_title) {
  return expected_title === document.title
}, "Expected Title")
```

**Comment by yoz** [comment]
Well, I just noticed #305 (from a month ago) also does this. =/

**Comment by a7madgamal** [comment]
exactly!
we made it because we are using it all over the place in our tests :D 
please accept the pull request :pray:
