### ISSUE TITLE
preload script causes nightmare to hang

### ISSUE THREAD

**Issue by yoz** [segmentio/nightmare#359]
If I specify the 'preload' option in nightmare's web-preferences (that get passed through to electron), nightmare hangs. This happens even when the preload script does nothing.

Example script: https://gist.github.com/yoz/b7420bf6fa38d351b8cc
It uses this preload script: https://gist.github.com/yoz/829b05a344d37f3cff26

Expected behavior (which is what we get if the preload line is commented out):
1. open example.com
2. console.log "Example Domain"
3. click a link to http://www.iana.org/domains/reserved
4. console.log "IANA — IANA-managed Reserved Domains"

Actual:
1. open example.com
nothing else happens

**Comment by rosshinkley** [comment]
You're overwriting the baked-in Nightmare [preload script](https://github.com/segmentio/nightmare/blob/master/lib/preload.js) which (I think) ultimately sets up the Electron process Nightmare needs to work properly.  This is why it appears to hang.  I don't think you can have multiple preload scripts (see [here](https://github.com/atom/electron/issues/2406)).

Do you need to have a preload step?  Could you use [`inject`](https://github.com/segmentio/nightmare#injecttype-file) or [`evaluate`](https://github.com/segmentio/nightmare#evaluatefn-arg1-arg2) instead?

**Comment by yoz** [comment]
I'm trying to use preload because I'm running in a headless environment, but I have a page where the `onload` event pops up an `alert()` (which is blocking), so I'm attempting to preempt it by setting `document.alert = console.log;` or some such *before* the `onload` event fires.

I tried to `evaluate` at `on('dom-ready')`, but it didn't seem to be early enough. But I'll see if `inject` or other events work better.

**Comment by rosshinkley** [comment]
@yoz ah, I see.  I don't think you'll have great luck with `inject` then, either.  Both `inject` and `evaluate` are (at least in my read) the same under the covers.

Pondering out loud: since alerts are blocking, should they be caught and emitted as alert events to Nightmare, similar to how `console.log` works?
