### ISSUE TITLE
Enable adding event listeners to webContents.session

### ISSUE THREAD

**Issue by pkawiak** [segmentio/nightmare#371]
When I ```goto``` a web page containing ```iframe``` with a pdf, save file dialog pops up blocking the process. I've found out that it is possible to resolve that by adding ```will-download``` listener to ```webContents.session``` of ```BrowserWindow``` as described [here](https://github.com/atom/electron/issues/3142). Would it be desirable to extend Nightmare's API to support this usecase? If yes then would sth like that be fine?
```
nightmare.session.on('will-download', handler);
```
If that's acceptable then I could submit PR

**Comment by rosshinkley** [comment]
@fmaruki, @darthcloud and myself touched on this in #332.  I didn't pull together a PR because I wasn't too keen on polluting options with download rules and I was/I am _pretty_ certain my implementation and approach were not good.  Since then, I haven't set aside time to take a second (hopefully longer) look.

Adding an event handler in this way might work.  It side-steps the immediate action problem, and offloads responsibility for cleanup and multiple downloads to the user, which simplifies things.

Thoughts?

**Comment by pkawiak** [comment]
Is there any other way we can automate pages containing iframes with pdf content? I don't even want to download it, I just don't want it to get in my way by displaying blocking system window.

Would it be acceptable to just hardcode ```will-download``` event prevention in Nightmare?

Is it of any use to display blocking system dialog in context of browser automation? If yes then is there any way to interact with it in automated way?

**Comment by rosshinkley** [comment]
While I understand the temptation to discard/ignore downloads, I don't think that is a particularly good approach.  If Nightmare is being used for scripting, it is possible that the downloaded file will help determine what steps to take after the download (eg, with integration testing).  I suppose Nightmare could simply accept every download, but that also seems like an unpleasant option.

Answering your second question: From within browser automation, no, modal system dialogs are not useful and cause problems.  For example, `alert`, `confirm`, and `prompt` cause Nightmare to hang just like with download prompts.  (For what it's worth, some work has been done to address those three, and for more information, see #359, #365, #366 and #374.)

Answering your third question: from within Electron, you can either cancel the download or set the download path within the `will-download` handler.  This is functionally the same as interacting with the download dialog and will prevent one from showing.

**Comment by pkawiak** [comment]
Thank you for your time @rosshinkley. Unfortunately it means that I will either have to switch to barebone Electron or deal with this issue in forked Nightmare. It would be nice to know if there is some long term plan to support those usecases or if the idea is not even considered to be included in Nightmare's source.

**Comment by rosshinkley** [comment]
@pkawiak no problem.  I can't imagine this particular issue is going away as there are already a couple of other open download questions akin to this one.  Plus, willfully not supporting a common browser activity would be sort of silly.

As for inclusion, I'm sure a PR to take care of the obvious download cases would be welcome.

**Comment by pkawiak** [comment]
OK then during weekend I'll try to put together PR with following API:
```
nightmare.session.on('will-download', handler);
```

**Comment by rosshinkley** [comment]
@pkawiak I didn't mean to step on your toes, but I've put together (a hopefully reasonable?) PR #382 to handle downloads.  I'd like to get your feedback. :)

**Comment by rosshinkley** [comment]
With the release of #425 in 2.3.0, I've gone ahead and released plugins that will take care of downloads:

* [nightmare-download-manager](https://github.com/rosshinkley/nightmare-download-manager)
* [nightmare-inline-download](https://github.com/rosshinkley/nightmare-inline-download)

I'm considering this issue resolved.  If you have further questions or problems, please open a new issue.
