### ISSUE TITLE
How to set proxy

### ISSUE THREAD

**Issue by hovosanoyan** [segmentio/nightmare#372]
Hi I was using the nightmare the one that was using phantomjs and there I can set proxy by passing proxy: 'username:password@host:port'. Question is there any available option for this now? I tried to set it in runner.js like this "win.webContents.session.setProxy(config, callback)"  but it's throw an unexpected error. So can someone tell how I should do that?

**Comment by matthewmueller** [comment]
There's some info in this PR: https://github.com/segmentio/nightmare/pull/241/files. Unfornately, it's really out of date at this point. Would love for you to open up a new PR :-)

**Comment by juanpaulo** [comment]
#410 will let you set proxy settings, etc. through [Chrome's command line switches](https://github.com/segmentio/nightmare#switches). Hope it helps!

**Comment by hovosanoyan** [comment]
I leaved that for now but will check it later anyway thank you very much.
