### ISSUE TITLE
Prevent loading Google Analytics

### ISSUE THREAD

**Issue by SerjoPepper** [segmentio/nightmare#373]
How can I prevent loading the Google Analytics when I scrape page with nightmare.js?

**Comment by matthewmueller** [comment]
if you're not able to catch the event as the window via inject, it  can be fixed with a custom preload script outlined here: https://github.com/segmentio/nightmare#custom-preload-script

**Comment by SerjoPepper** [comment]
@matthewmueller I expected a more elegant solution, eg blocking scripts loading by domain or hostname, this way works in PhantomJS.

**Comment by matthewmueller** [comment]
let's see if more people need this. there's a million things nightmare *could* do, it's up to us to make sure the API remains simple, while not being limiting.

**Comment by nquoctuan** [comment]
Hi @matthewmueller ,

I am not really sure the issue that I create a custom preload script to capture alert message. Actually I follow the site that you provided, but no chance.

```
VM106:3 Uncaught TypeError: Cannot read property 'nightmare' of undefined
javascript @ VM106:3
(anonymous function) @ VM106:38
electron.ipcRenderer.on @ init.js:51
emitMany @ events.js:127
emit @ events.js:201
 ```

**Comment by nquoctuan** [comment]
source code is quite simple:
```
var Nightmare = require('nightmare'),
  nightmare = Nightmare({
    openDevTools: {
      mode:'detach'
    },
  show: true,
  webPreferences: {
        devTools: true,
        preload: 'alertMessage.js',
        nodeIntegration: false,
        webSecurity: false,
        allowRunningInsecureContent: true
      }
});
  
nightmare.useragent('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3015.0 Safari/537.36');

nightmare.goto('http://www.google.com')
  .then(function() {
	return nightmare.url();  
  })
  .then(u => {
	  console.log('The url is: ' + u);
  });
```

**Comment by rosshinkley** [comment]
@nquoctuan I'm _almost_ positive that the path for `preload` has to be fully qualified.  What happens if you change that to `preload: require('path').resolve('alertMessage.js')`?
