### ISSUE TITLE
Provide custom parameters for actions

### ISSUE THREAD

**Issue by antpaw** [segmentio/nightmare#379]
The new actions feature is great, but we need to be able to pass in arguments to the callback
so we can do something like this:

````js
Nightmare.action('evaluValue', function*(done, value, cb) {
  var test = yield this.evaluate(cb);
  assert.strictEqual(test, value, 'evaluValue() ' + errorMessageHelper(value, cb));
  done();
});
````

**Comment by matthewmueller** [comment]
hm, did you try:

```js
Nightmare.action('evaluValue', function*(value, cb, done) {
  var test = yield this.evaluate(cb);
  assert.strictEqual(test, value, 'evaluValue() ' + errorMessageHelper(value, cb));
  done();
});

Nightmare().evaluValue('some value', function cb() { ... } ) 
```

?

**Comment by antpaw** [comment]
no sorry didnt tried that, though done is the first arg, this works indeed. can you help me out with this code here? thanks

```js
var url = 'http://google.com';
Nightmare.action('googleto', function(page, done) {
  this.goto(url + page);
  return done();
});

var t = yield Nightmare().googleto('/').evaluate(function(){
  document.querySelector('a').click();
}).title()
console.log(t);

**Comment by matthewmueller** [comment]
hmm, i'm not sure. that's just not working at all?

**Comment by antpaw** [comment]
this example just hangs (white screen in electron) in the air an doesn't go to the google page, the callback function of vo is never called

    var Nightmare = require('nightmare');
    var vo = require('vo');

    vo(function* () {
      var url = 'http://google.com';
      Nightmare.action('googleto', function(page, done) {
        this.goto(url + page);
        return done();
      });

      return yield Nightmare({show: true}).googleto('/').title();
    })(function (err, result) {
      if (err) return console.log(err);
      console.log(result);
    });



this code works as expected and writes 'Google' to the bash

    var Nightmare = require('nightmare');
    var vo = require('vo');

    vo(function* () {
      var url = 'http://google.com';
      return yield Nightmare({show: true}).goto(url).title();
    })(function (err, result) {
      if (err) return console.log(err);
      console.log(result);
    });

**Comment by rosshinkley** [comment]
The `DEBUG` output from above yields a clue:

```
nightmare queueing action "googleto" +0ms
nightmare queueing action "title" +5ms
nightmare running +3ms
nightmare queueing action "goto" for http://google.com/ +607ms
nightmare:actions .title() getting it +4ms
```

From that, it looks like the title action would happen _before_ the goto, which would certainly cause problems.  Actions that add other actions would enqueue them after the last action in the chain.  Consider the following:

```js
var Nightmare = require('nightmare');
var vo = require('vo');

vo(function * () {
  var url = 'http://google.com';
  Nightmare.action('googleto', function(page, done) {
    this.goto(url + page);
    return done();
  });


  var nightmare = Nightmare({
      show: true
    });
    yield nightmare.googleto('/');

  return yield nightmare.title();
})(function(err, result) {
  if (err) return console.log(err);
  console.log(result);
});
```

This will (misleadingly) work: `.googleto()` is the last action in the first chain, and as a side effect, will run the internal `.goto()` enqueued by `.googleto()` before the next nightmare chain.

I don't think that `.action()` is intended to execute other internal actions, and in this case, I think `.use()` may be more appropriate.  Something like:

```js
var Nightmare = require('nightmare');
var vo = require('vo');

vo(function * () {

  var url = 'http://google.com';
  var googleto = function(page){
    return function(nightmare){
      nightmare.goto(url + page);
    };
  };

  var nightmare = new Nightmare({show:true});
  
  var title = yield nightmare
    .use(googleto('/'))
    .title();
    
  yield nightmare.end();
  
  return title;
})(function(err, result) {
  if (err) return console.log(err);
  console.log(result);
});
```

... might yield better results.

**Comment by matthewmueller** [comment]
yah, i agree with @rosshinkley. `use` let you bundle a set of actions together, while `action` defines a new method. let me know if this is unclear and maybe i can clear it up in the docs

**Comment by shadowmint** [comment]
The documentation on this is extremely sparse. 

For anyone else who finds this, the way to pass arguments to an action is to pass additional arguments to child.call, like this:

```
var path = require('path');
var Nightmare = require('nightmare');

//define a new Nightmare action named "foo"
Nightmare.action('foo',

    // This task runs in the remote process
    function (name, options, parent, win, renderer, done) {
        parent.respondTo('foo',
            function (args, done) { // <---- See args 
                // Do whatever with args here...
                done();
            });
        done();
    },

    // use the IPC child's `call` to call the action added to the Electron instance
    function (args, done) {
        this.child.call('foo"', args, done); // <--- Args passed in
    });

    ...

    var nightmare = Nightmare();
    nightmare
        .goto('http://www.google.com")
        .foo({ some: 'value' })
        .then(function () { nightmare.end(); }, function (error) { console.log(error); });
```

**Comment by josephrocca** [comment]
I agree with @shadowmint - there definitely needs to be more documentation for passing parameters to custom actions. There's almost nothing in the documentation that I could find, and the actual solution is not very intuitive - a bad combination.
