### ISSUE TITLE
Nightmare integrarting keydown event

### ISSUE THREAD

**Issue by sriducati** [segmentio/nightmare#386]
Hello people below is my code ...

        var Nightmare = require('nightmare');
        var vo = require('vo');
        var tags = [];
        vo(function* () {
          var nightmare = Nightmare({ show: true });
          var example = yield nightmare
            .goto('https://example.com')
            .type('#thesearchbox', 'film')
            .wait()
            .evaluate(function (tags) {
            
               $('#thesearchbox').keydown().delay(100000);
              //setTimeout(function(){ tags.push({url:$(".autocomplete").html()}) }, 10000);
              
              if($('ul.autocomplete li').length >= 1)
              {
                  $('.autocomplete li').each(function(i)
                  {

                    tags.push({search:$(this).html()});
                    //console.log("good");

                  });
              } else{
                tags.push({url:"nothing"})
              }

              return tags;
            },tags);
          console.log(example);
           return res.json(example);
        })(function (err, result) {
          if (err) return console.log(err);
        });

It works fine by typing `film` inside seacrhbox. electron ui will also show `autocomplete` class ... but iam not able to fetch html contents within `autocomplete` .. is there any ways to fix this?

**Comment by rosshinkley** [comment]
I believe before 2.1.5, the keydown/keypress/keyup events were not getting sent through Nightmare, and I wonder if that's causing you problems.  Could you upgrade and try again?

**Comment by rosshinkley** [comment]
Due to lack of attention and issue age, I'm going to close this issue.  If you're still having this problem, feel free to reopen/open a new issue.
