### ISSUE TITLE
wait and click

### ISSUE THREAD

**Issue by squirmy** [segmentio/nightmare#388]
hi - I've found myself using with this pattern frequently:

``` javascript
yield nightmare
  .wait('.page-next')
  .click('.page-next')
```

How about we include this behavior by default in the click method? Either as is above, or if the overhead for the .wait() is too much it could only enter .wait() if it doesn't find it immediately.

As it currently stands when it doesn't find the element you get an error:

```
Cannot read property 'dispatchEvent' of null
```

Perhaps it also applies equally to some of the other methods too. ie.
- select
- check
- type
- mouseover
- mousedown

**Comment by matthewmueller** [comment]
yah, i agree that it should wait

is that leading to another page? it should wait for the click to happen if there's a page transition: https://github.com/segmentio/nightmare/blob/master/lib/runner.js#L251-L254 before continuing.

unfortunately, i'm not exactly sure how we'd pull this off. we could listen for clicks on the top of the window, but if there's a stopPropagation, somewhere, we won't catch it and we'll wait forever. 

open to ideas.

**Comment by squirmy** [comment]
The .click() above is not leading to another page in this case. Here's my scenario:

- single page application
- user clicks a button which switches the main view
- user is shown a spinner until the data is pulled down
- when we have the data the spinner is removed and the content rendered
  - it's at this point the `.page-next` button is shown

so it goes something like this in nightmare:

``` javascript
yield nightmare
  .click('.change-view')
  .wait('.page-next')
  .click('.page-next')
```

if i omit the `.wait(.page-next)` i get an error because the spinner is showing for a short duration before the button is shown.

**Comment by casesandberg** [comment]
Happy to hear if you have any ideas or want to take a stab at a PR. I am going to close this for now.
