### ISSUE TITLE
inject not working : __nightmare is not defined

### ISSUE THREAD

**Issue by dingziran** [segmentio/nightmare#395]
I updated to 2.1.0. And after inject jquery.js. The console of electron print "Uncaught ReferenceError: __nightmare is not defined".

**Comment by matthewmueller** [comment]
weirddd. can you give me the code snippet you're using?

**Comment by dingziran** [comment]
@matthewmueller 
maybe it is not caused by inject
The below code will stop during the second yield. 
Ans also "Uncaught ReferenceError: __nightmare is not defined"
```javascript

         var login_url="https://passport.weibo.cn/signin/login?entry=mweibo&res=wel&wm=3349&r=http%3A%2F%2Fm.weibo.cn%2F%3Fjumpfrom%3Dweibocom";
        var nightmare = Nightmare({
                show:true,
                waitTimeout:3000,
                "web-preferences":{
                    partition:"persissdfsdft"//+username
                }
            });
        if(nightmare.state==="initial") {
            yield nightmare.goto(login_url).wait(1000)
            yield nightmare
                //.inject("js", "jquery.js")
                //.wait(function () {
                //    return jQuery ? true : false;
                //})
                .click("#loginAction")
            console.log("jquery on");
        }
        yield nightmare
            .type("#loginName",username)
            .type("#loginPassword",password)
            .type("#loginVCode",captcha)
```

**Comment by dingziran** [comment]
I tried on an old machine which has installed nightmare 2.0.8. And it is working.
After delete nightmare folder and npm install. The same problem appear.
After npm install nightmare that will update to 2.1.0. Also show the same error.
Maybe it is because of electron-prebuilt?

I am using windows 10, node 4.2.

**Comment by dingziran** [comment]
also not work in ubuntu 14.04 desktop :''' (

**Comment by dingziran** [comment]
I find the problem. After delete web-preferences config. Everything is ok.
```
"web-preferences":{
                    partition:"persissdfsdft"//+username
                }
```

After some test, partition is not working anymore. Is that a bug?

**Comment by matthewmueller** [comment]
@dingziran Oh, I think it might be electron renaming it's options, try `webPreferences`.

**Comment by felixcrive** [comment]
@dingziran @matthewmueller Matt you are right, it wasn't working for me and I renamed the web preferences and it did work. Thanks.
