### ISSUE TITLE
My code is not working with the release 2.1.0 and 2.1.1

### ISSUE THREAD

**Issue by gabrielperales** [segmentio/nightmare#404]
> # UPDATE
>   I have found out that this is the same issue that #395 

Hi, I'm trying to run my code (it's very similar to the example code) and it's not working. When I launch my code with the show option to true, in the developers tools console shows up the next text:
```
Uncaught ReferenceError: __nightmare is not defined
```

Otherwise, it runs ok with the release 2.0.8. and release 2.0.9. ~~I'll check if code still working properly with the release 2.1.0~~. My code stops working with 2.1.0

You can reproduce the issue with this code:
```javascript
'use strict';
var Nightmare = require('nightmare');
var vo = require('vo');

vo(run)(function(err, result){
  if (err) throw err;
  console.log(result);
});

function *run() {
  var nightmare = Nightmare({
    height: 700,
    width: 1280,
    show: true,
    "web-preferences": {
      partition: ""
    }
  });

  yield nightmare
    .goto('http://www.google.com/')
    .wait(400)
    .type('.gsfi:fist-child', 'hello world')
    .wait(20000);

  yield nightmare.end();
}
```

**Comment by matthewmueller** [comment]
For those that are running into this, the solution is changing `web-preferences` => `webPreferences`.
