### ISSUE TITLE
How to use Nightmare in generator function (without vo)

### ISSUE THREAD

**Issue by fabrik42** [segmentio/nightmare#406]
Hi!

I'm planning to use nightmare as the headless browser for my mockup generator: https://github.com/fabrik42/responsive_mockups/pull/6

However, I can not figure out how to use the Nightmare API without the `vo` lib with pure generator functions. I created this simplified code to show what I mean:

```javascript
var Nightmare = require('nightmare');

var urls = [
  'http://google.com',
  'http://yahoo.com',
  'http://bing.com'
];

function *renderInNightmare(url, savePath) {
  yield Nightmare()
    .goto(url)
    .wait(100)
    .screenshot(savePath)
    .end();
}

function *batchProcessing() {
  for(var i = 0; i < urls.length; i++) {
    var url = urls[i];
    var savePath = __dirname + 'screenshot_' + i + '.png';
    yield *renderInNightmare(url, savePath);
  }
}

for(var result of batchProcessing()) {
  console.info('finished a screenshot...');
}
```

At the moment, this will spawn up three electron processes and they just seem to stay idle without ever finishing or taking the screenshot.

I'm not very familiar with generator functions in JavaScript, so I'm happy about every hint. :)
Am I missing something here?

Cheers,
Chris

**Comment by matthewmueller** [comment]
generators on their own do not do control flow, you have to pair them with libraries like `vo` or `co`, so your example will never actually run the generators.

To use this library without generators though, you can do...

```
Nightmare()
    .goto(url)
    .wait(100)
    .screenshot(savePath)
    .end(fn);
```

or `.run(fn)` if you don't want to stop the electron process after running

**Comment by fabrik42** [comment]
Hi Matthew,

thanks for the heads up - I think I got it now. :)

My code didn't work because Nightmare works asynchronously so it didn't make sense to return it as an argument of a yield statement.

Closing this ticket now, happy holidays!
