### ISSUE TITLE
Any way to tell electron to keep miscellaneous messages to a minimum?

### ISSUE THREAD

**Issue by kanethal** [segmentio/nightmare#419]
It seems like electron has suddenly become quite verbose, transmitting any small browser error for me to read in my node console. I think I must have performed a rebuild, because I don't recall seeing all these messages before:

``Renderer process started:`` 

I see this every time the scraper goes to a new URL. Is this normal behavior? I recall seeing this message once when the scraper first initialized, but now I see it with every page change.

``[10800:1228/105431:ERROR:cookie_monster.cc(1742)] Found 1 duplicate cookies for host='....``

I never used to see these kind of messages. Actually I don't remember seeing many messages from Electron at all, previously. The scraper is still performing well, it's just quite noisy now.
Any tips on how to tone down the noise? Thanks!

**Comment by emars** [comment]
in `lib/nightmare.js` it appears the only messages being logged to the console directly are `uncaughtException`'s so unless you are using `DEBUG` there shouldn't be a ton of output. 

I'll update the README with a list of DEBUG flags for more targeted logging?

**Comment by kanethal** [comment]
Interesting... I really have no idea what is causing the behavior. I
remember attempting to put my console into debug mode once upon a time,
does that state persist after closing powershell? Thanks for responding,
BTW.

**Comment by emars** [comment]
Not 100% sure because I'm on OSX, but try:
`Get-ChildItem Env:`
in powershell and look for the `DEBUG` flag.

**Comment by kanethal** [comment]
Here's an example of the errors that I didn't used to see until rebuilding:

![nightmarejserrors](https://cloud.githubusercontent.com/assets/8418137/13235833/73517546-d97d-11e5-98ef-4740b673a5ea.jpg)

**Comment by rosshinkley** [comment]
@kanethal Do you have `ELECTRON_ENABLE_LOGGING` set?  It might be worth to check your environment variables against [the Electron environment variable flags](https://github.com/electron/electron/blob/master/docs/api/environment-variables.md).

**Comment by kanethal** [comment]
I hadn't explicitly set any conditions like this. It's possible they are
enabled in the nightmare package? I'm using v2.0.2. Thank you so much for
the link, I had been trying to find these flags.

**Comment by rosshinkley** [comment]
@kanethal No problem!

As for them being enabled for 2.0.2, I don't think so.  I don't see the same behavior.  I'd be curious if you'd get the same behavior with a different version.  Could you upgrade to 2.3.0 and run it again?

**Comment by kanethal** [comment]
I'd be happy to try!

**Comment by rosshinkley** [comment]
@kanethal Did you have any luck with an upgrade?

**Comment by kanethal** [comment]
Hi Ross, I believe there had been some semantic changes between the two
versions, and was going to have to reconfigure the scraping script and
haven't had time to focus on that. I'm sorry, I wish I had time to play
with it some more!

**Comment by rosshinkley** [comment]
Closing due to lack of information/age.  If you're still experiencing this problem, feel free to reopen/open a new issue.
