### ISSUE TITLE
phantom stdout: TypeError: undefined is not an object (evaluating 'phantom.args[0]')

### ISSUE THREAD

**Issue by matthewmueller** [segmentio/nightmare#42]
Running into this when trying to run the examples:

```
  nightmare queueing action "evaluate" +0ms
  nightmare run +5ms
  nightmare .setup() creating phantom instance on port 12301 +1ms
phantom stdout: TypeError: undefined is not an object (evaluating 'phantom.args[0]')


phantom stdout:   /Users/matt/Playground/node_modules/nightmare/node_modules/phantom/shim.js:5421
  /Users/matt/Playground/node_modules/nightmare/node_modules/phantom/shim.js:5599
  /Users/matt/Playground/node_modules/nightmare/node_modules/phantom/shim.js:159
  /Users/matt/Playground/node_modules/nightmare/node_modules/phantom/shim.js:11 in require
```

This could definitely be an issue with `phantomjs` on 10.10, but any ideas?

**Comment by dtothefp** [comment]
I've forked Node PhantomJS and hacked around with it to install the only "stable" version for Mac of Phantom 2.0.0 I could find:

Version I'm using: https://github.com/eugene1g/phantomjs/releases/download/2.0.0-bin/phantomjs-2.0.0-macosx.zip
Fork: https://github.com/dtothefp/phantomjs

So, you could just `require` the binary
```js
var phantomBinary = require('phantomjs').path
```

@bprodoehl it looks like you have shimmed the `phantomjs-node` package and the binary works fine with it. I've not tried using it with Nightmare yet but assume I will run into some of the same problems.
