### ISSUE TITLE
.check(selector): Can't unchecked if default value of checked="checked"

### ISSUE THREAD

**Issue by nathanielvarona** [segmentio/nightmare#428]
Can't toggles the selector checkbox element if default value of checked="checked"
https://github.com/segmentio/nightmare#checkselector

**Comment by rosshinkley** [comment]
Looking at the source, it looks like `.check()` will only check checkboxes, not uncheck.  I would suspect this is intentional behavior, but then why `.uncheck()` isn't also in core is a mystery.

That aside, you could add your own `.uncheck()` with `.action()`:

```js
 Nightmare.action('uncheck', function(selector, done) {
    this.evaluate_now(function(selector) {
      var element = document.querySelector(selector);
      var event = document.createEvent('HTMLEvents');
      element.checked = null;
      event.initEvent('change', true, true);
      element.dispatchEvent(event);
    }, done, selector);
  });

  yield Nightmare()
    .goto('[your url]')
    .check('input[type=checkbox]')
    .uncheck('input[type=checkbox]')
```
