### ISSUE TITLE
confusion about waitTimeout option

### ISSUE THREAD

**Issue by joychester** [segmentio/nightmare#429]
From the Readme doc it says:
waitTimeout
This will throw an exception if the .wait() didn't return true within the set timeframe.
```javascript
var nightmare = Nightmare({  
  waitTimeout: 1000 // in ms  
}); 
```
however, in my dummy tests, it does not work if we set .wait() in following:

```javascript
const RENDER_TIME_MS = 30000  
function *run() {  
  var nightmare = Nightmare({'waitTimeout': 15000});  
  yield nightmare  
    .goto('some_url')  
    .wait(RENDER_TIME_MS)  
    .screenshot("shot_debug.png")  
    .end();  
}  
```
this test will still running 30 seconds instead of 15 seconds we set in the option, it had better to describe in the doc if 'waitTimeout' only works in the .wait(selector) function :)
Thanks!

**Comment by rosshinkley** [comment]
Possibly related: #397, and to a lesser extent #375
