### ISSUE TITLE
Reason for lack of pdf to buffer?

### ISSUE THREAD

**Issue by derrickpelletier** [segmentio/nightmare#431]
Is there a reason for why `.screenshot()` with no path provided will return the buffer data, but `.pdf()` has no ability to do the same? Or does it just have to be implemented?

**Comment by emars** [comment]
It currently is set up to use electron as the underlying implementation:

see:
https://github.com/atom/electron/blob/master/docs/api/browser-window.md#browserwindowprinttopdfoptions-callback
and:
https://github.com/atom/electron/blob/master/docs/api/web-contents.md#webcontentsprinttopdfoptions-callback

It appears to just not have been implemented.

I just submitted a pull request that should take care of it.

**Comment by derrickpelletier** [comment]
Awesome, thanks!
