### ISSUE TITLE
Calling Local Websites with Windows Authentication

### ISSUE THREAD

**Issue by neeldeep** [segmentio/nightmare#432]
How can call a local site hosted in IIS and using windows authentication using nightmare?

**Comment by matthewmueller** [comment]
i'm not really sure. don't have access to an IIS box atm

**Comment by rehael** [comment]
Struggled with it too for a while. Solution / workaround (because `authenticate()` didn't work):

    .goto('domain\\username:password@hostname:port/path');

…correctly used NTLM authentication in my case. Fixing `authenticate()` would be the best option though.

**Comment by rosshinkley** [comment]
@rehael I'd be curious if NTLM causes the [`login` event](https://github.com/electron/electron/blob/master/docs/api/web-contents.md#event-login) to be fired.  I suspect the answer is no - which would explain why `.authenticate()` doesn't work - but I'd appreciate it if you (or someone else) would double-check.

**Comment by rehael** [comment]
@rosshinkley I'm fairly sure I've tried `.on('login', …)` but let's wait until Monday when I check this at work. Nb. I've had exactly the same problem with Casper/Phantom.

**Comment by rosshinkley** [comment]
Closing due to age and viable workaround.
