### ISSUE TITLE
please keep this package evil

### ISSUE THREAD

**Issue by thisconnect** [segmentio/nightmare#433]
https://github.com/segmentio/nightmare/blob/master/package.json

![screen shot 2016-01-12 at 8 23 49 am](https://cloud.githubusercontent.com/assets/546900/12257365/4393a028-b906-11e5-9eed-e86c4c59634b.png)

**Comment by stephenmathieson** [comment]
lol

**Comment by matthewmueller** [comment]
hahaha we'll do our best.
