### ISSUE TITLE
Using Nightmare within an Express route

### ISSUE THREAD

**Issue by adrianparr** [segmentio/nightmare#448]
How would I go about using Nightmare.js within an Express route?

I have tried the following but it is not working ...

```javascript
var express = require('express');
var router = express.Router();
var Nightmare = require('nightmare');

router.get('/', function(req, res) {

	new Nightmare({ show: true })
		.useragent('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36')
		.viewport(1200, 950)
		.goto('http://www.bbc.co.uk/')
		.wait()
		.screenshot('screenshots/bbc.png')
		.run(function() {
			res.send('Screenshot has been captured');
		})
		.end();

});

module.exports = router;
```

Any ideas?

**Comment by shri3k** [comment]
Just to get some context, is this all the code that you're running?

**Comment by adrianparr** [comment]
No, I have other Express code that initialises the server etc (in separate files). The code above is just what gets run when the '/' route is matched.

**Comment by shri3k** [comment]
Oh..which version of nightmare are you using?

**Comment by rosshinkley** [comment]
What you have _should_ work.  What happens when you run it?  Have you tried running it with `DEBUG`?

In addition to version, are you running this headlessly?  (I suspect since you have `show: true`, the answer is no, but it's worth double-checking.)  How are you running the node process?

**Comment by adrianparr** [comment]
@shri3k I have `"nightmare": "^2.0.7"` in my package.json file.

@rosshinkley When I run it I never get a response back and the PNG screenshot doesn't get created. 
Do you mean run it like ...
`$ DEBUG=app bin/www`

I want it to run headlessly. I have changed it to `new Nightmare({ show: false })` but it hasn't made any difference.

I know the route is matched and running ok, as I have put `console.log`'s in there and I can see them in Terminal.

I'm just about to go on holiday for a week. So I won't be able to reply to this thread. But when I get back I'll put together a simple(r) demo that I can share with you.

Thanks in advance.

**Comment by rosshinkley** [comment]
Electron requires a framebuffer to render, and I'd wager your headless solution doesn't have a framebuffer running.  If you are running headlessly - and testing what you provided as a sample headlessly - you're probably going to want to at least read through #224.  It has some proposed solutions to try.  I have a sneaking suspicion you're hitting the same issue.

**Comment by rosshinkley** [comment]
@adrianparr Are you still having this issue?

**Comment by adrianparr** [comment]
@rosshinkley I think you were right. I am having the same issue as #224. I managed to get it working locally, but I need it to run on Digital Ocean (headlessly. It appears I'm not the only one having problems with this, judging by the thread on #224.

**Comment by rosshinkley** [comment]
@adrianparr Ah, okay.  Closing and merging with #224.
