### ISSUE TITLE
Suggestion: _timeoutMs value for waitfn() can be override in option

### ISSUE THREAD

**Issue by joychester** [segmentio/nightmare#450]
can we expose *_timeoutMs* to option as well, so that users can override this value if they want, 250ms sometimes sounds relative long, for example measuring page loaded time..

```javascript
/**
 * Wait until evaluated function returns true.
 *
 * @param {Nightmare} self
 * @param {Function} fn
 * @param {...} args
 * @param {Function} done
 */

var _waitMsPassed = 0;
var _timeoutMs = 250;
function waitfn (self, fn/**, arg1, arg2..., done**/) {
...
}
```

**Comment by rosshinkley** [comment]
Using, say, `will-navigate` and `did-stop-loading` and taking the time difference between the two might be a better approach barring redirects (or other edge cases I'm sure I'm not thinking of).

I could agree that `_timeoutMs` should be an option you can set, but I'm also not sure I understand the utility of doing so.  Is there a use case beyond measuring page load time?

**Comment by joychester** [comment]
Hi, @rosshinkley , measuring page load time is the case i can think of currently which matters most for the accuracy to the test numbers.
