### ISSUE TITLE
Can't run example on Readme.md

### ISSUE THREAD

**Issue by chocolait** [segmentio/nightmare#451]
I am total newbie to JS and node and I am trying out the first example (immediately after executing "npm install vo nightmare" with success) and I get the following error
# node --harmony yahoo.js

yahoo.js:4
vo(function* () {
           ^
SyntaxError: Unexpected token *
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3

Could you please help? Thanks in advance.

**Comment by rosshinkley** [comment]
@chocolait Out of curiosity, what version of node are you using?

**Comment by chocolait** [comment]
# node --version
v0.10.36

**Comment by rosshinkley** [comment]
Correct me if I'm wrong, but off the top of my head I don't think generator support was introduced until v0.11.x or v0.12.x.  Is an upgrade possible?

**Comment by chocolait** [comment]
That's the package manager default (fedora). I'll try using the latest version.  
Thank you for your help.
