### ISSUE TITLE
`wait(ms)` does not work at all unless you explicitly set `optionWaitTimeout`...

### ISSUE THREAD

**Issue by the-t-in-rtf** [segmentio/nightmare#453]
This should go away once a new release is cut that includes [this commit](https://github.com/segmentio/nightmare/commit/24d9efa4a42a9937910650b860eed37bec0b1b1b).  I am making a note of it here to help anyone else who encounters the problem with version 2.1.3.

In version 2.1.3, which includes [this change](https://github.com/segmentio/nightmare/commit/f75b48aad09339b1407f3d3422a1dd51b936c2f0), a call to `nightmare.wait(ms)` will fail unexpectedly as demonstrated in the following code:

```
"use strict";

var Nightmare = require("Nightmare");
var nightmare = new Nightmare();

nightmare.wait(500).run(function (error, result) {
    console.log("error:", error.message);
});
```

This consistently outputs `.wait() timed out after undefinedmsec`.  The solution (until a new release is cut that sets a default value) is simply to set the required option, as in `new Nightmare({ waitTimeout: 30000})`.

**Comment by matthewmueller** [comment]
thanks for the note, this should be fixed in 2.1.4 :sparkles:
