### ISSUE TITLE
Electron warns about deprecated calls on Windows... 

### ISSUE THREAD

**Issue by the-t-in-rtf** [segmentio/nightmare#454]
When using Nightmare 2.1.2 and 2.1.3, we see the following warnings,  but only on Windows.

```
(electron) ipc module is deprecated. Use require("electron").ipcMain instead.
(electron) getUrl is deprecated. Use getURL instead.
(electron) loadUrl is deprecated. Use loadURL instead.
```

I am preparing a pull request to fix each of these warnings now.

**Comment by the-t-in-rtf** [comment]
The PR is here: https://github.com/segmentio/nightmare/pull/455

**Comment by the-t-in-rtf** [comment]
The "url" fixes were trivial.  The "ipc" change was not, so I left that for now.  This will at least get rid of 2/3 warnings.

**Comment by matthewmueller** [comment]
this should be fixed in the new release :-)
