### ISSUE TITLE
How to start nightmare (electron) with clean resources (session, cookies, etc..)

### ISSUE THREAD

**Issue by AveVlad** [segmentio/nightmare#456]
How to start nightmare (electron) with clean resources (session, cookies, localStorage, etc..)

**Comment by rosshinkley** [comment]
Possibly a duplicate of the original intent of #398?

I have a _slight_ improvement on that answer, though.  Three methods, depending on what you need:

1. Use [`webPrefereces.partition`](https://github.com/atom/electron/blob/master/docs/api/browser-window.md#new-browserwindowoptions).  Example:

```javascript
var nightmare = Nightmare({
   webPreferences:{
       partition: 'your-unique-partition-name'
   }
});
```

2. Use [`options.paths`](https://github.com/segmentio/nightmare#paths).  Example:

```javascript
var nightmare = Nightmare({
   paths:{
       userData: '/path/to/your/data'
   }
});
```

3. Remove the default Electron cache/config/session directory.  I think where this is depends on your setup, but at least on Debian systems with the current version of `electron-prebuilt` (0.35.2 at the time of this answer), it's at `~/.config/Chromium/Electron`.

**Comment by AveVlad** [comment]
@rosshinkley Thank you very much!
