### ISSUE TITLE
Is it possible to use nightmare with tampermonkey?

### ISSUE THREAD

**Issue by lancevo** [segmentio/nightmare#457]
Is there some way to use nightmare without a headless browser, like include it tampermonkey plugin?

**Comment by matthewmueller** [comment]
not at the moment, but adding adapters would be a cool addition :-)

**Comment by rosshinkley** [comment]
For clarity: are you asking if Nightmare could be used under TamperMonkey?

If you're asking if TamperMonkey could be included as an extension for a Nightmare process, that is currently not possible.  Electron does not have a plan to [include Chrome's extension APIs](https://github.com/atom/electron/issues/1498).

**Comment by lancevo** [comment]
I'm not writing an extension for TamperMonkey. I just want to use nightmare API to write scripts in TamperMonkey. Thank you for your replies.
