### ISSUE TITLE
Process halts after wait(fn)

### ISSUE THREAD

**Issue by paranoiq1** [segmentio/nightmare#460]
I'm trying to work on a page on which some data is loaded in the background. There is a progress bar (in some div) indicating that process isn't completed. Usually it takes 4-6minutes for this process to complete. After that, box with progress bar disappears, page is fully loaded and I can continue working on data. 
After checking the page's code I figured out, that visibility of this box is being set to "hidden", so the way to handle this would be checking within wait(fn) what is the status of visibility. Unfortunately this doesn't work for me. Just when the progress bar disappears
`nightmare:actions .wait() for fn +3m`
is triggered in console (indicating that wait(fn) returned true?) and the process halts.
I've tried this on nightmare 2.0.8 and 2.1.6

Here is the code:
```
var Nightmare = require('nightmare');
var vo = require('vo');
var iframe = require('nightmare-iframe');

vo(run)(function(err, result) {
  if (err) throw err;
});

function *run() {
  var nightmare = Nightmare(
	{ show: true},
	{ 'web-preferences': {'web-security': false} },
	{ waitTimeout:900000}
);
  nightmare.on('timeout', function(msg) {
     return console.log(msg);
   });
 
  var title = yield nightmare

_[...]some code[...]_

.wait(25000)
.goto('main page')
.wait(function() {
	var x = document.getElementById("webiViewFrame");
	var y = (x.contentWindow || x.contentDocument);
	if (y.document)
		y = y.document;
	while(y.waitDlg.css("visibility") != "hidden")
	{
		sleep(10000);
	}
	return true;
    })
.wait(1000)
.evaluate(function() {
	document.getElementById('webiViewFrame').contentWindow.MenuItem_delayedClick(34);
	return true;
    })
.wait(5000)
}
```

What I see in console:
```
nightmare:actions .wait() for 25000ms +16s
nightmare:actions .wait() for fn +3m
```

Any ideas?

**Comment by rosshinkley** [comment]
Where is the `sleep()` function defined?  I suspect you're encountering an evaluation error interior to Electron.

I don't think you need to do that yourself at any rate.  The `.wait(fn)` method polls on its own every 250ms, memory serving.  You could change that wait function to something like:

```js
function() {
    var x = document.getElementById("webiViewFrame");
    var y = (x.contentWindow || x.contentDocument);
    if (y.document)
        y = y.document;
    return y.waitDlg.css("visibility") != "hidden";
})
```
... which should work, provided `y.waitDlg` exists.

If you really wanted the 10s wait between checks, you could write the wait as a `.wait(ms)` and `.evaluate(fn)` combination.  Off the top of my head without being able to test it, something like:

```js
var visible = false;
while (!visible) {
    visible = yield nightmare
        .wait(10000)
        .evaluate(function() {
            var x = document.getElementById("webiViewFrame");
            var y = (x.contentWindow || x.contentDocument);
            if (y.document)
                y = y.document;
            return y.waitDlg.css("visibility") != "hidden";
        })
}
```
...should yield your desired result.

**Comment by paranoiq1** [comment]
That's true, I accidentally ignored 250ms pause in `wait(fn)`. Tried the first solution of yours, but the result is the same. I'm not sure if it's not a bug, because below script (exactly as it's printed) run with 2.1.6:
```
var Nightmare = require('nightmare');
var vo = require('vo');

vo(run)(function(err, result) {
  if (err) throw err;
console.log(nightmare);
});

function *run() {
  var nightmare = Nightmare({ show: true});
  nightmare
   .wait(100)
   .wait(function() {return true;})
   .wait(100)
  yield nightmare.end();
}
```
ends up with the same problem - script hangs up just after `wait(fn)` has finished
```
  nightmare:actions .wait() for 100ms +0ms
  nightmare:actions .wait() for fn +108ms
```
Could you try to replicate this?

**Comment by rosshinkley** [comment]
Hm, I can recreate the behavior almost as-is - I added a `yield` before `nightmare` on the line where it's by itself.  However, if you actually have Nightmare load a page with `.goto(url)` first, it works.  You would _probably_ be using it that way anyhow.

In your second example, I suspect the page context for javascript isn't created with the default webview.  A quick read of the Electron documentation [doesn't really say](http://electron.atom.io/docs/v0.36.5/api/web-contents/#webcontents-executejavascript-code-usergesture) one way or another.  I'll have to dig into it when I have a little more time.  (Does anyone happen to know offhand?)

Does your source try to evaluate prior to loading a page?

Setting that aside and going back to your original question: I would probably start by taking a look at the contents of your wait function, ensuring the parts you're expecting exist.  I still think you might be hitting an evaluation error.

**Comment by paranoiq1** [comment]
I digged into logs and tried some other approaches. Seems, there's no need to do `wait(fn)`. Unitl bar dissappears there is still some data exchanged in background. When the process is finished two events are triggered: `did-stop-loading ` and `navigated to`.

Current situation is that once a while program works as designed and other time - `evaluate(fn)` is not triggered. What I've found in logs is that  `did-stop-loading ` and `navigated to` events are triggered three times until page is fully loaded and progress bar disappears. Unfortunately on some situations (no schema) next command after `goto` (command `wait(25000)`) is triggered after second `did-stop-loading ` event (so page is not fully loaded, because data is still being exchanged, progress bar is visible and... page functions are disabled). I belive this can be problem with my situation. 

Is there any way to force nightmare to wait longer before passing to next command, so it could be aware (despite `did-stop-loading ` event), that the page is still loading?

Below is my current code:
```
var Nightmare = require('nightmare');
var vo = require('vo');

vo(function* () {
  var nightmare = Nightmare({ show: true },
	{ 'web-preferences': {'web-security': false} },
	{ waitTimeout:30000});
  var link = yield nightmare

//some code with goto, types, clicks, waits

.goto('https://page_with_very_long_address')
.wait(25000)

.evaluate(function() {
	return document.getElementById('webiViewFrame').contentWindow.MenuItem_delayedClick(34);
	
    })
  yield nightmare.end();
  return link;
})(function (err, result) {
  if (err) return console.log(err);
  console.log(result);
})
`

**Comment by rosshinkley** [comment]
I can believe you're getting finished loading events for the page before the page is really "done" loading/rendering.

For clarity, and so I get a better grasp on what you're asking, you said:
> page functions are disabled

This sounds like elements in the loaded page are disabled (or perhaps styled to look that way).  If that's the case, could you use `.wait(fn)` to wait for those to become available?

**Comment by paranoiq1** [comment]
There is one big transparent div on top of the page, so page functions are loaded but are not accessible because of this div. Later when div style is set to `display='none'` all functions get accessible. I tried to `wait(fn)` for this div to change style to `display='none'`, but this leads me to first problem - `wait(fn)` hangs...
What I've mentioned earlier - `wait()` is triggered after first (or second) of three `did-finish-load` events. It's hard to debug it, but it's possible that JS context it's not loaded yet, what leads us to problem - using `wait(fn)` without earlier `goto` use...

**Comment by paranoiq1** [comment]
Resolved problem in the easiest way by adding few additional `wait(time)` before `wait(fn)`. When one of `did-finish-load` events occurs,` wait(500)` function is triggered allowing to continue loading page. Simple and easy.

**Comment by SantoshSrinivas79** [comment]
@paranoiq1 can you provide the updates to your above code that allowed you fix this please? I think I have a similar problem

**Comment by avimar** [comment]
I think I may have just had a similar issue.

On my desktop, viewing my script, it always worked: It would do a `click` and then `wait` for an element on the result page. I even made sure to clear if that element existed.

Somehow, on the server this would fail. I even attached vnc to watch, but no difference. It seemed, _somehow_ the `wait` was triggered too early and somehow returned true. Simply adding a `.wait(1500)` after the `click` allowed my next wait to evaluate the page properly... weird.

**Comment by vagnerj** [comment]
it somehow depends when the timer in waitfn (actions.js:441) is started, I have some not trivial scenario involving up to 3 redirects in a row (company SSO) .. if I don't wait for some time before starting waiting for some element (even if it's static html element in the page from the start), it _sometimes_ stops checking for existence after few ticks .. the only difference between un/successful executions I see is the order in which other assets from the pages are 'loaded' (css, other js, etc), so they might interfere ..
