### ISSUE TITLE
best way to intercept request

### ISSUE THREAD

**Issue by yoshi95** [segmentio/nightmare#461]
Hi,

whats the best way to get access to `win.session.webRequest` object through Nightmare?
(looks like it s in revision 36+, not the currently electron version used in nightmare, but i was able to use it by passing the `electronPath`)

A use case for me
when scraping sites using Nightmare, there are a lot of ads/tracking pixels firing. they slow down the page dramatically.
i want to filter out those request (request not originating from the domain i m interested in).
i was able to do this by adding the `win.session.webRequest.onBeforeRequest` handler.

wondering if theres a way to do this through the `plugin/action` extension pattern.

thanks

**Comment by yoshi95** [comment]
looks like the `cookies.get/set` should be using `win.session` object, but i am unable to find the usage in the Nightmare code base.

**Comment by matthewmueller** [comment]
it's here: https://github.com/segmentio/nightmare/blob/master/lib/runner.js#L303-L306

`win.session` is a recent change, right now we're using the old reference (that still works).

I'd be interested to see a PR that supports this or when we land #425, it could be a plugin too :-)

**Comment by rosshinkley** [comment]
Selfish +1 for making this a plugin.  I'd be happy to put it together. :)

Half-kidding aside, though, if you would rather have this be a part of core I'd be happy to throw together a PR.  Which would you prefer?

**Comment by matthewmueller** [comment]
depends on the use case :-) i'd probably prefer a plugin, but i think there could be an argument for providing a highlevel way to intercept requests in nightmare.

**Comment by rosshinkley** [comment]
[Curiosity got the best of me](https://github.com/rosshinkley/nightmare-load-filter).  If that seems like something worth submitting for core, I'd be happy to do it.  I'd love to hear your arguments for including it. :)

**Comment by kyungw00k** [comment]
@yoshi95 I added `nightmare.webRequest.onBeforeRequest` in PR #495 
@matthewmueller In order to make plugin like this, I think some apis are needed which can access electron side api or event message receiver written in `runner.js` just like [this](https://github.com/segmentio/nightmare/pull/495/files#diff-b3b53682a18f203ac8d29b0e277cad26R353) which is the same as the way of cookie api.

**Comment by rosshinkley** [comment]
@kyungw00k the API you're requesting is done.  For more information, read through #391 and #425.

**Comment by kyungw00k** [comment]
@rosshinkley the API will be available to use after #391 is completed, right?

**Comment by rosshinkley** [comment]
@kyungw00k Correct.

**Comment by rosshinkley** [comment]
#425 has been merged, and [nightmare-load-filter](https://github.com/rosshinkley/nightmare-load-filter) has been released.  Closing.

**Comment by kyungw00k** [comment]
@yoshi95 now, you can use `webRequest.onBeforeRequest` handler with [this](https://github.com/kyungw00k/nightmare-webrequest-api)
