### ISSUE TITLE
Evaluate not working

### ISSUE THREAD

**Issue by Crazometer** [segmentio/nightmare#462]
G'day, I have the following bit of code that I can't get to work for the life of me. I have the preview window on and can see electron navigating around properly but I can never get the "hello" to come up as the result.

		getLinks(function() {
			co(downloadRecord).then(function(res) {
				console.log("res is ");
				console.log(res);
			}, x => console.log("Error is " + x));
		});

		function* downloadRecord() {
			var return_button = "#licenceHolderForm\\:returnButton";
			var results = [];
			var a;
			for (var i = 0; i < 2; i++) {
				var link = links[i];
				yield nightmare.click(link).wait(return_button);
				yield a = nightmare.evaluate(function() {return "hello"});
				yield nightmare.back().wait(refine_button);
			}
			return a;
		}

I've tried about a million different combinations where the only I could get to work involved using .run where the second parameter returned "hello" instead of the nightmare instance. Previously I had `yield a = nightmare.click(link).wait(return_button).evaluate(function() {return "hello"})` all in one line. In that case res was returning an instance of nightmare. Since I've split them res is now undefined.  I'm new to generators and co/vo in js so any help would be greatly appreciated!

**Comment by rosshinkley** [comment]
I don't know if this is the entirety of your problem, but this line:
```js
 yield a = nightmare.evaluate(function() {return "hello"});
```
...should read:
```js
 a = yield nightmare.evaluate(function() {return "hello"});
```
The former waits for an assignment of what `.evaluate()` returns, which is a Nightmare instance.  The latter awaits fulfillment of what `.evaluate()` yields.

**Comment by Crazometer** [comment]
Thanks for that! I knew it would be something simple.

**Comment by matthewmueller** [comment]
it would be a great help if you can close your own issues once the problem is resolved. this repo has a lot of traffic. it helps us know what issues need our attention and which are resolved.
