### ISSUE TITLE
using type('#input-element-id', 'file-path') to upload file similar to selenium

### ISSUE THREAD

**Issue by mgsh** [segmentio/nightmare#466]
Hi,
Is it possible to upload files using nightmare.type('#input-element-id', '/tmp/img001.jpg'), similar to what selenium supports?
http://www.seleniumeasy.com/selenium-tutorials/uploading-file-with-sendkeys-method

If not, is there a suggested alternative way to achieve the same, which is to programatically initiate a file upload, without having to open a file browser?

**Comment by danielyogel** [comment]
+1

**Comment by Zn4rK** [comment]
The only thing that might work is to fake a drop event with the file(s) attached. But one would probably run into some other browser restrictions, but it might be worth a try. 

If the above approach does not work, then this is not possible until Electron adds some way of intercepting the file dialog or manually setting the file(s). There's more to read in the [other issue](https://github.com/segmentio/nightmare/issues/235) regarding uploading files.

**Comment by rosshinkley** [comment]
Merging with #235.  Closing.
