### ISSUE TITLE
Control typing speed on .type()

### ISSUE THREAD

**Issue by jviotti** [segmentio/nightmare#469]
When using `.type()` and showing the Electron window, I can see how the text I put in gets typed. Is there a way to control the typing speed?

**Comment by matthewmueller** [comment]
not right now :-) do you want to speed it up or slow it down?

we have a delay in place as a hack to ensure the characters are entered in the correct order.

**Comment by jviotti** [comment]
@matthewmueller I wanted to speed it up. How much do you think we could increase the speed without compromising the ordering?

**Comment by kylewelsby** [comment]
I've tested my tests with `0` timeout on the `.type()` function and can't report any keystrokes being emitted in the wrong order. 

Using the `setTimeout(fn, 0);` hack to defer the event to the next event loop of JavaScript should be just fine. 

I was tempted to make this timeout a configurable variable to aid debugging without making test suites run longer than necessary, but I did not want to introduce a breaking change.
