### ISSUE TITLE
API Document got no info about return value of each method

### ISSUE THREAD

**Issue by magicdawn** [segmentio/nightmare#472]
I tried code like this:
```js
var night = Nightmare();
var goto = night.goto('http://www.baidu.com');
var eva = goto.evaluate(() => document.getElementByTagName('title')[0].innerText);
```

![image](https://cloud.githubusercontent.com/assets/4067115/12953183/4723f962-d054-11e5-89f8-072f97fee59b.png)

And I found that both `goto` & `evaluate` return the Nightmare instance. Shouldn't `evaluate` return a promise or a thunk? How can I use nightmare without the vo module? How can I use nightmare with co?
Please doc the return value of method. Tks.

**Comment by rosshinkley** [comment]
If you don't want to use generators, you can use the internal `.run()` method, but you'll have to manage the control flow yourself:

```js
var Nightmare = require('nightmare'),
  nightmare = Nightmare();

nightmare.goto('http://baidu.com')
  .evaluate(() => document.getElementsByTagName('title')[0].innerText)  
  .run(function(err, title) {
    console.log(title);
    nightmare.end().run(function(){
      console.log('done');
    });
  });
```

**Comment by magicdawn** [comment]
@rosshinkley Oh, I get this https://github.com/segmentio/nightmare/blob/2.1.6/lib/nightmare.js#L309-L319

the Nightmare instance is implicitly using `then` to perform a fake Promise instance. so it can be yield to a flow control tool like co or vo. And this is weird & should be documented.

**Comment by magicdawn** [comment]
Let me explain why this is weird:

1. you know the flow control tool will call `yield_result.then`
2. you implement a `then` method
3. It just works.

**Comment by rosshinkley** [comment]
I realize now I only answered one of your questions, figuring this boiled down to a control flow issue.  I think I understand what you're asking now, especially with respect to promises.  Let me attempt a more comprehensive answer:

> And I found that both goto & evaluate return the Nightmare instance. Shouldn't evaluate return a promise or a thunk? 

No.  They return the Nightmare instance so the calls can be chained.  (I'll get to the promise/thunk question in a moment.)

> How can I use nightmare without the vo module?

You can use `co`:
```js
var Nightmare = require('nightmare'),
  nightmare = Nightmare(),
  co = require('co');

co(function * () {
  var title = yield nightmare.goto('http://baidu.com')
    .evaluate(() => document.getElementsByTagName('title')[0].innerText);

  yield nightmare.end();
  return title;
})
  .then(function(title) {
    console.log(title);
  });
```
Conceivably, you could also use the promise-like behavior of Nightmare to control behavior:
```js
var Nightmare = require('nightmare'),
  nightmare = Nightmare();

nightmare.goto('http://baidu.com')
  .evaluate(() => document.getElementsByTagName('title')[0].innerText)
  .then(function(title){
    console.log(title);
  })
  .then(function(){
    nightmare.end();
  });
```
... or control the flow yourself, as I did in my previous comment.

> the Nightmare instance is implicitly using then to perform a fake Promise instance. so it can be yield to a flow control tool like co or vo. 

Getting back to the promise question, yes, Nightmare (partially) implements a promise so it can be yielded in `co` or `vo`.  The `.then()` implementation is ultimately what causes the queue to be processed when using flow control libraries.  If Nightmare inherited from a promise implementation, I'd think the `.then()` behavior would have to be overridden to support the custom behavior needed to execute the queued commands, which I think would be much more strange.  Do you have a suggestion for an alternative? 

> And this is weird & should be documented.

Not sure I agree that it's weird, but I can understand wanting a broader explanation of how the guts of Nightmare work with `vo`/`co`.  I'm not sure where this would be included, but it's probably worth doing.

---

I have a question for you: what problem were you having or trying to solve where this question came up?  I'm curious why and where the promise implementation was causing issues.

**Comment by magicdawn** [comment]
> what problem were you having or trying to solve where this question came up

I was familar with Promise & co, and I know we should yield a thunk or promise so it can be `next(resolved_val)` to the yield left value. But code like this

```js
co(function * () {
  var title = yield nightmare.goto('http://baidu.com')
    .evaluate(() => document.getElementsByTagName('title')[0].innerText);
  yield nightmare.end();
  return title;
})
```

I was thinking maybe the `evaluate` method is ending the chain operation and return a thunk or promise whatever. I tried, and found I was wrong. So I get confused & don't how it works. Then I request to document the return value of each methods. Next tick I step into the co method, and I found that the nightmare instance is treated as a promise instance because it got a `then` method. https://github.com/tj/co/blob/4.6.0/index.js#L198 I'm not confused anymore. Thanks.

> If Nightmare inherited from a promise implementation, I'd think the .then() behavior would have to be overridden to support the custom behavior needed to execute the queued commands, which I think would be much more strange. Do you have a suggestion for an alternative?

I use superagent a lot. It use chain methods too. Normally I will add an `endAsync` to the prototype
```js
var request = require('superagent');
var Request = require('superagent').Request;
Request.prototype.endAsync = Promise.promisify(Request.prototype.end); // using bluebird promisify

// so endAsync return a promise now
co(function* (){
  var res = yield request
    .get('http://www.baidu.com')
    .endAsync();
  var html = res.text;
})

// or
co(function* (){
  var html = yield request
    .get('http://www.baidu.com')
    .endAsync()
    .then(res => res.text);
})
```
the promisified `endAsync` return a standard promise, it can be thened too

After figuring out how Nightmare works, I can use like
```js
var Nightmare = require('nightmare');
Nightmare.prototype.runAsync = Promise.promisify(Nightmare.prototype.run);

co(function* (){
  var title = yield nightmare
    .goto('http://baidu.com')
    .evaluate(() => document.getElementsByTagName('title')[0].innerText)
    .runAsync();
  yield nightmare.end();
  return title;
})
```

Conclusion: someone(like me :joy:) don't like the implicit then, and it did not return a standard promise instance, just for control flow to work. The `run` method is real hero, I suggest document the `run` method. Thanks.

**Comment by magicdawn** [comment]
After using nightmare for a while, I found it's pretty nice to use the implicit then with co. Thank you.

**Comment by kanethal** [comment]
```
var Nightmare = require('nightmare'),
  nightmare = Nightmare(),
  co = require('co');

co(function * () {
  var title = yield nightmare.goto('http://baidu.com')
    .evaluate(() => document.getElementsByTagName('title')[0].innerText);

  yield nightmare.end();
  return title;
})
  .then(function(title) {
    console.log(title);
  });
```

This returned an error for me: ``` co(...).then() is not a function```
Was that a fully fleshed example, or am I supposed to know something about co to interpret it?

I was also having a hard time returning data out of nightmare, This information is very helpful, thank you

**Comment by rosshinkley** [comment]
@kanethal Out of curiosity, what version of `co` are you using?

**Comment by magicdawn** [comment]
@kanethal yeah, that's a full example, and will log the page title

![image](https://cloud.githubusercontent.com/assets/4067115/13415848/4297e634-df99-11e5-8588-546eb9bcf5a4.png)

maybe you are using an old verison of co(before v4.0 probably)~

**Comment by kanethal** [comment]
I had grabbed a fresh version I thought... I'll double check when I get
home.

**Comment by rosshinkley** [comment]
I'm considering this matter closed.  If any of you are having problems, feel free to open a new issue.
