### ISSUE TITLE
Kill electron instance when nightmare's process exits

### ISSUE THREAD

**Issue by Mr0grog** [segmentio/nightmare#474]
Since I started working on #468, I noticed that exiting a process that is using Nightmare doesn't end the electron process that Nightmare is controlling. At first, I had no idea this was happening because I was running nightmare with `{show: false}`, but I soon discovered I had *a lot* of electron processes floating around:

![lotsofelectrons](https://cloud.githubusercontent.com/assets/74178/12967599/30b896ec-d01d-11e5-8823-5eafb5e52853.jpg)

Unless there's an important reason for that, it seems like simply adding a listener to the process's `exit` event in Nightmare's constructor that kills electron would be both simple and helpful:

```js
process.on('exit', function() {
  self.proc.disconnect();
  self.proc.kill();
});
```

That is, I don't think I'm unique in sometimes forgetting to call `end()` ;)

**Comment by rosshinkley** [comment]
Put me down for +1.  I've run `killall` a _shameful_ number of times.
