### ISSUE TITLE
can't get inject() to work (getting a "is not defined" error)

### ISSUE THREAD

**Issue by max-l** [segmentio/nightmare#480]
I have the following code (nightmare v2.1.6 and  node v4.3.0)

```
      var nightmare = new Nightmare({show: showBrowser})
          .useragent('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36')
          .goto('http://someSite)
          .inject('js', './node_modules/underscore/underscore.js')
          .wait(2000)
          .wait(".someClass")
          .evaluate(function() {
              _.map(someArray,function(z) {...})
           })

```

Nightmare gives me a "_ is not defined" error

I have verified that the path of underscore.js is correct, since I can do : 

 var _ = require('./node_modules/underscore/underscore.js')

inside my nodejs script.

**Comment by rosshinkley** [comment]
What you have there ought to work.  Out of curiosity, is the `.goto()` causing a redirect?  What happens if you move the injection to after `.wait(".someClass")`?

**Comment by rosshinkley** [comment]
Upon deeper inspection, injected scripts [do not inject to global scope](https://github.com/rosshinkley/nightmare-examples/blob/master/docs/known-issues/globally-defined-variables.md).  That's why your call to `_.map()` is not working.
