### ISSUE TITLE
.type() sometimes starts before focusing

### ISSUE THREAD

**Issue by matthewmueller** [segmentio/nightmare#485]
This causes the .type() to get cut off. My guess is that the page isn't ready before we try focusing, but it needs more investigation.

**Comment by rafalneves** [comment]
I'm also experiencing this. I made sure the page is ready with a very long wait. And already tried everything that I could think of.

Did you found a workaround?

**Comment by marckubischta** [comment]
I've seen this a few times recently as well.

**Comment by rosshinkley** [comment]
Closing this issue for now as I have not seen this issue in quite a while.  If anyone sees this, I'd be happy to reopen.
