### ISSUE TITLE
In version 2.2.0, in sample file nightmare.end() is called before promise is resolved

### ISSUE THREAD

**Issue by rafaelb** [segmentio/nightmare#490]
In sample.js, nightmare.end() is called before promise is resolved.
I've tried placing nighmare.end() inside the .then() section but it doesn't help.

Is it possible to have a working example that shows how to get nightmare.end() to only execute only after the .then() statement has finished executing?

**Comment by rosshinkley** [comment]
Two problems: one, move `.end()` to before `.then()`, and two, the name of the search button has changed:

```javascript
var Nightmare = require('nightmare');
var nightmare = Nightmare({ show: true })

nightmare
  .goto('http://yahoo.com')
  .type('input[title="Search"]', 'github nightmare')
  .click('#uh-search-button')
  .wait('#main')
  .evaluate(function () {
    return document.querySelector('#main .searchCenterMiddle li a').href
  })
  .end()
  .then(function (result) {
    console.log(result)
  });
```

I opened up a PR to fix this + the questions posed in #482.
