### ISSUE TITLE
`insert` should fire element `change` when clearing a field...

### ISSUE THREAD

**Issue by the-t-in-rtf** [segmentio/nightmare#499]
I have code that looks for the `change` event on a text field.  In browsers, this is fired once the affected field loses focus (for example, when hitting the "submit" button).

Using the new `insert` method to clear out a field and then changing focus does not result in the `change` event being fired.

I seem to remember the previous implementation of `type` would work as expected, but now that `type` lacks the ability to clear text, that also doesn't work.

I can work around the problem for now by simulating clearing text using `evaluate` statements, but this is moving in the wrong direction, as I want things like the new `type` that behave more like we'd expect from a user typing things into a browser.

Happy to prepare a pull, but I can't figure out when to trigger the change without breaking the flow in the other direction (i.e. triggering the change too soon, when a real browser would wait until the loss of focus).

Any thoughts on addressing this?

**Comment by the-t-in-rtf** [comment]
I thought about this overnight, and did some tests.  I now have a workaround that I would like to propose as a solution.

If I pass the backspace key (`\b`) to `type`, it will erase one character of the existing text.  I would propose that when `type` receives a "falsy" value, it should look at the current value and type `\b` `value.length` times.

If this approach seems reasonable, I am happy to submit a pull request.

**Comment by matthewmueller** [comment]
yah, i'm +1 to that idea. and then have `.insert` just clear things out.

**Comment by rosshinkley** [comment]
@the-t-in-rtf Any progress on the PR suggestion?

**Comment by yoz** [comment]
Does PR #548 do what you want here? I submitted it because I was also trying to get 'change' events.

**Comment by rosshinkley** [comment]
I agree with @yoz.  I think #548 fixes this, and as such, I'm closing this issue.
