### ISSUE TITLE
Click canvas

### ISSUE THREAD

**Issue by csysmans** [segmentio/nightmare#507]
Hi! I'm a huge fan of the framework!!!

I just have one problem, that I do not know how to solve:
One of my webpages renders "virtual" buttons inside a <canvas> element.
Is there a way that I can simulate a click inside this canvas?

**Comment by rosshinkley** [comment]
Not yet.  `.click()` doesn't support clicking at arbitrary coordinates.  Even if it did, you'd have the added problem of trying to figure out the absolute coordinates of items rendered in the canvas.  Do you have that ability?

**Comment by csysmans** [comment]
Hi Ross,

I have the exact x y coordinates available.
However, I found another solution, so this feature is not urgent anymore.

Thanks for the help!

**Comment by rosshinkley** [comment]
@csysmans no problem.  After I walked away, I realized I also hadn't mentioned that this could be pretty readily accomplished using `.evaluate()`.

Anyway, glad you found a solution. :)

**Comment by csysmans** [comment]
Yeah, I use the evaluate extensively when the nightmare module does not offer what I need.
However, I do not know of a way to simulate a click on a canvas from JavaScript or something like that. I was hoping "nightmare" + "electron" had a way to overcome this limitation of basic browsers.

**Comment by rosshinkley** [comment]
Issue resolved.  Closing.
