### ISSUE TITLE
Failing promises?

### ISSUE THREAD

**Issue by kokujin** [segmentio/nightmare#508]
I noticed that it is not possible to resolve the promise returned by a nightmare session multiple times. From the docs:
````
  .evaluate(function () {
    return document.querySelector('#main .searchCenterMiddle li a').href
  })
  .end()
  .then(function (result) {
    console.log('Do this', result)
  })
 .then(function (result) {
    console.log('Do that', result)
  }) // <---- THIS EMITS AN ERROR

````
Am I mistaken? Thanks

**Comment by rosshinkley** [comment]
This seems to work under 2.2.0 - what version of Nightmare are you using?

By the by, your second `.then()`'s result will be undefined as the previous `.then()` didn't return anything.

**Comment by kokujin** [comment]
Ok. Thanks. it works under 2.2.0
