### ISSUE TITLE
Nightmare ignores console log formatting

### ISSUE THREAD

**Issue by kokujin** [segmentio/nightmare#518]
Give this application code:

`````
 console.log('LOG TEST ::   %s',  productID);
`````

I am trying to do something based on the console output. So using this snippet

``````
nightmare
    .on('console', function (type, msg) {      
        console.log('msg: ', msg);       
    })

`````
Nightmare logs out:

`````
msg:  'LOG TEST ::  %s
`````

The formatter, "%s" is completely ignored. Is there a workaround for this? Thanks

**Comment by rosshinkley** [comment]
Take a look at the [preload redefinition of `console.log`](https://github.com/segmentio/nightmare/blob/master/lib/preload.js#L13-L16).  The string interpolation for ordinary logging calls isn't applied when `console.log` is called.  The arguments are applied to the log event, allowing for more flexibility in using `console` events in Nightmare.

In your example, you could do:

```js
nightmare.on('console', function(type, msg, argument){
  console.log(msg, argument);
})
```

... which would produce `LOG TEST :: 1` or whatever the product ID is set to.

In general, if you wanted the default behavior, you could apply the arguments slicing off the `type` argument.  Something like:
```js
nightmare.on('console', function(){
  console[arguments[0]].apply(null, Array.prototype.slice.call(arguments, 1));
})
```

**Comment by kokujin** [comment]
Thanks @rosshinkley
