### ISSUE TITLE
Add custom header to all the requests sent from Electron

### ISSUE THREAD

**Issue by michalbe** [segmentio/nightmare#521]
I need to add custom header to the every request. Using `nigthmare.header()` method sends those only with `goto` call, so for instance if I have an XHReq in the app I'm automating with `nightmare`, the header isn't sent with it. Is there any way to make it happen?

**Comment by rosshinkley** [comment]
I don't think `.header()` was intended to wrap _every_ request from Electron.  (If I'm wrong on that, someone please correct me.)

If you wanted to add headers to every XHR request from the site's client code, you could conceivably use a [custom preload script](https://github.com/segmentio/nightmare#custom-preload-script) to override how `XMLHttpRequest.send()` works.  Something like this at the end of a custom preload script:

```js
  XMLHttpRequest.prototype._send = XMLHttpRequest.prototype.send;
  XMLHttpRequest.prototype.send = function(){
    this.setRequestHeader('x-foo', 'some value');
    this._send();
  };
```
... would add `'x-foo'` to every request

Disclaimer: I don't think overriding the constructor for `XMLHttpRequest` is the best of ideas, but for a controlled, non-production test environment, it is probably okay.

Is that closer to what you had in mind?

**Comment by michalbe** [comment]
The app I'm automating uses jQ for all of the requests so I just added this snippet that forces every XHReq to contain those headers, what is close to what you proposed.
```
  $.ajaxSetup({
    headers: { 'X-HWDP' : 'JP100' }
  })
```

Thanks @rosshinkley .

**Comment by rosshinkley** [comment]
Looking at this again, it looks like you can use [`webRequest.onBeforeSendHeaders()`](https://github.com/electron/electron/blob/2cf0843f82af4eae283ad759d806360973bbd869/docs/api/session.md#webrequestonbeforesendheadersfilter-listener) to amend the request headers.  You could pretty readily write a plugin with `.action()` to take care of that for you.

With that, I'm going to consider this issue resolved, seeing as how I think we've covered how to do it with a preload and from within Electron.

**Comment by feniljariwala82** [comment]
> I don't think `.header()` was intended to wrap _every_ request from Electron. (If I'm wrong on that, someone please correct me.)
> 
> If you wanted to add headers to every XHR request from the site's client code, you could conceivably use a [custom preload script](https://github.com/segmentio/nightmare#custom-preload-script) to override how `XMLHttpRequest.send()` works. Something like this at the end of a custom preload script:
> 
> ```js
>   XMLHttpRequest.prototype._send = XMLHttpRequest.prototype.send;
>   XMLHttpRequest.prototype.send = function(){
>     this.setRequestHeader('x-foo', 'some value');
>     this._send();
>   };
> ```
> 
> ... would add `'x-foo'` to every request
> 
> Disclaimer: I don't think overriding the constructor for `XMLHttpRequest` is the best of ideas, but for a controlled, non-production test environment, it is probably okay.
> 
> Is that closer to what you had in mind?

This is not working dude!
