### ISSUE TITLE
Problems using nightmare in a loop

### ISSUE THREAD

**Issue by kokujin** [segmentio/nightmare#522]
I cannot seem to get Nightmare to work in a loop. Given this quick simple example:

`````
var nightmare = Nightmare( {
    'show': false,
    'openDevTools': {
        'detach': true
    }
} );

var allTags = [ 'Tag1', 'Tag2', 'Tag3'];

test( 'Test a few items ID tags', function ( t ) {
    t.plan( 3 );

    for ( var idx = 0; idx < allTags.length; idx++ ) {
        var selector = '#' + allTags[ idx ] + ' a';
        console.log( 'selector: ', selector ); // <--- THIS WORKS
            nightmare // <-- THIS DOESNT ITERATE
                .goto( 'http://www.my-test-domain.com' )
                .viewport( 1024, 768 )
                .click( selector )
                .wait( 'body' )
                .then( function ( result ) {
                    var msg = allTags[ idx ] ;
                    t.equal( result, 'Tag1',
                        msg2 );
                }, function ( err ) {
                    console.log( err );
                } );        
        t.equal( 'mock-result', allTags[ idx ]);
    } // END FOR LOOP
} );

`````

On the first item nightmare instance is instantiated and tested, the second and third not. Can someone explain to me what I am doing wrong? Thanks

**Comment by kokujin** [comment]
Nice! Thanks for your patience and time @rosshinkley

**Comment by cue232s** [comment]
What would be the best way to handle an error that occurs  inside the resolve function of the accumulator?  For example in my call to `return accumulator.then` I'm passing a function that makes an asynchronous call and pushes the result into array like in your example above. If that asynchronous call fails, the next trip in the reduce loop, my array will be replaced by `undefined`.  Is there a way to catch errors and pass the array along?
