### ISSUE TITLE
EventEmitter memory leak detected inside forEach

### ISSUE THREAD

**Issue by NetanelBasal** [segmentio/nightmare#526]
I am trying to loop over array and call nightmare but I get this error:
```js
possible EventEmitter memory leak detected. 11 ready listeners added. Use emitter.setMaxListeners() to increase limit.
```

I am using version 2.2.0 with node 5.7

```js
Object.keys(urls).forEach(blogUrl => {
  getLinks(blogUrl, blogs[blogUrl].selector);
});

function getLinkst(url, selector) {
  nightmare
    .goto(url)
    .evaluate(() => {
     return document.querySelector(selector).href;
    })
    .end()
    .then(result => {
      console.log(result);
    })
}
```

**Comment by Mr0grog** [comment]
It might be that the maximum number of listeners should be boosted, but you may still want to restructure your code slightly anyway. As a side benefit, doing so might alleviate the problem, too.

Try rewriting `getLinks()` this way:

```js
function getLinks(url, selector) {
  Nightmare()  // <- create a new Nightmare instance every time
    .goto(url)
    .evaluate((selector) => {
     return document.querySelector(selector).href;
    }, selector)
    .end()
    .then(result => {
      console.log(result);
    })
}
```

Each nightmare instance represents one browser window; if you don’t wait for all the actions in that window to complete before triggering new actions, you can easily run into problems. In this case, your original code would likely result in the window constantly browsing to new URLs before ever getting around to looking for a selector, so most of your attempts to get the `href` from the selector would wind up getting it from the wrong page. Doing each query in a new Nightmare instance keeps it safe.

Alternatively, you could wait for each series of actions to complete before asking for the next link:

```js
getLinks(Object.keys(urls));

function getLinks(blogUrls) {
  var blogUrl = blogUrls.shift();
  getLink(blogUrl, blogs[blogUrl].selector)
    .then(result => {
      console.log(result);
      getLinks(blogUrls);
    });
}

function getLink(url, selector) {
  return nightmare
    .goto(url)
    .evaluate((selector) => {
      return document.querySelector(selector).href;
    }, selector);
}
```

The flow is a little more complicated there, but you can avoid running lots of electron processes at once this way.

**Comment by NetanelBasal** [comment]
Thanks you!

**Comment by rosshinkley** [comment]
This issue seems to be resolved, closing.  If you are still having this issue, feel free to reopen or open a new issue.
