### ISSUE TITLE
Difference between `nightmare.then` and `promise.then`

### ISSUE THREAD

**Issue by Mr0grog** [segmentio/nightmare#527]
In attempting to explain the behavior of `run` and `then` for #516, I realized the details of how Nightmare’s `then` method works means you can’t just say “works like `promise.then`.” The difference is minor and the likelihood of it tripping someone up is probably low, but it could still happen, especially given the promise-y expectations the method’s name sets up. Since `then` is now the preferred API, it should really be documented and, in doing so, the details of `then` should be made clear.

In the spirit of @rosshinkley’s comments on #491:

> I am certain it's going to come up in questions again and I wanted to have a reference to point at.

It might be helpful to understand *why* Nightmare’s `then` method does not behave in accordance with a promise’s `then` (or any Promises/A+ compliant thenable) in order to better document it.

Specifically, *if an error occurs in the success callback that is passed as the first argument to `then` (or if that callback returns a promise that rejects), the error callback passed as the second argument to `then` will handle it instead of it bubbling up the promise chain.*

Is this difference intentional? If so, what was the intent behind that decision? What was it meant to enable or prevent, if anything? If not, is this a bug to be fixed?

**Comment by rosshinkley** [comment]
I suspect the difference is a side effect of ensuring `vo`, `co`, and possibly `mocha-generators` Just Work&trade;.  Consider the following (admittedly contrived) example:

```js
var Nightmare = require('nightmare'),
    vo = require('vo');

function * run() {
    var nightmare = new Nightmare({
        show: false,
    });

    yield nightmare
        .goto('http://example.com')
        .wait('body')
        .evaluate(function(){
            throw new Error('uh oh');
        });

    yield nightmare.end();
}

vo(run)(function(err) {
    if (err) {
        console.dir(err);
    }
    console.log('done');
});
```

Out of the box, `vo` runs the promise and passes internal methods to `fulfill` and `reject` as prescribed by [the native promise documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise).  If you remove the `.catch()` call from Nightmare under `.then()`, the above example hangs.  Simillarly, with `co`, the rejection callback is never called (for hopefully obvious reasons).

All of that said, I agree with you that it is a _little_ misleading that you couldn't modify my original example to something like the following:

```js
var Nightmare = require('nightmare'),
var nightmare = Nightmare();
nightmare
  .goto('http://example.com')
  .wait('body')
  .evaluate(function() {
    throw new Error('uh oh');
  }).then(function(){
    console.log('done');
  }).catch(function(err){
    console.dir(err);
  });
```
... which is the situation I think you have in mind.  I think this top-level `.catch()` is a legitimate use case.  I don't think it's as much of an edge case as you're leading us to believe. :)

And with that in mind, [I played around with Nightmare in an attempt to address this issue](https://github.com/rosshinkley/nightmare/blob/527/lib/nightmare.js#L321-L343).  I haven't opened a PR for it _just_ yet, I wanted to get feedback from you first.  Thoughts?

---

PS: excellent explanation at #516.  Thank you for taking the time to do that. :)

**Comment by Mr0grog** [comment]
Ok, I’m suddenly realizing that my initial post was super hand-wavey on what the exact difference was, and it’s that we are doing this:

`nightmare.then(onSuccess, onError)  -->  promise.then(onSuccess).catch(onError)`

instead of:

`nightmare.then(onSuccess, onError)  -->  promise.then(onSuccess, onError)`

which is only very subtly different (namely, it conflates an error in the thing being promised [actions in Nightmare] with an error in user code *handling* the promise). More below…

> If you remove the .catch() call from Nightmare under .then(), the above example hangs.

Right—but you wouldn’t want to just remove the `catch`, call; you’d want to pass the `reject` callback as the second argument to `then`'s internal `then`. So then the implementation of `then` would then be:

```js
Nightmare.prototype.then = function(fulfill, reject) {
  var self = this;

  return new Promise(function (success, failure) {
    self.run(function(err, result) {
      if (err) failure(err);
      else success(result);
    })
  })
  .then(fulfill, reject);  // <- the only change
};
```

If I make that change, I see identical behavior to the previous implementation when using Vo/Co (we get to logging 'done', but not to actually closing down nightmare). Is that what you see, or am I misunderstanding what you were getting at here?

> All of that said, I agree with you that it is a little misleading that you couldn't modify my original example…

Wellllll, as long as `console` is present (which it is), that example works “right” in promise terms, though it doesn’t (and arguably shouldn’t) do the same thing as your previous generator example. If you always want “done” to get logged, you’d have to do it after handling the error:

```js
var Nightmare = require('nightmare'),
var nightmare = Nightmare();
nightmare
  .goto('http://example.com')
  .wait('body')
  .evaluate(function() {
    throw new Error('uh oh');
  })
  .then()
  .catch(function(err){ // you could combine w/ the above line: `.then(null, function(err){`
    console.dir(err);
  })
  .then(function(){
    console.log('done');
  });
```

But anyway, none of that really changes if `then` behaves like it currently does or if exactly like `promise.then`. Here’s (I think) the only difference in practice:

```js
var Nightmare = require('nightmare'),
var nightmare = Nightmare();
nightmare
  .goto('http://example.com')
  .wait('body')
  .evaluate(function() { return document.title; })
  .then(function(title) {
    console.oops('Title:', title);
  }, function(error) {
    console.dir(error);
  });
```

In a normal promise, our error handler would never run because the only error here is in the success callback. The way Nightmare implements `then`, though, it does—the console logs `[TypeError: console.oops is not a function]`.

If you used `catch` (or a second `then`) instead of a two-arg `then`, you’d both expect (with a standard promise) and get the same behavior Nightmare produced in the above example:

```js
var Nightmare = require('nightmare'),
var nightmare = Nightmare();
nightmare
  .goto('http://example.com')
  .wait('body')
  .evaluate(function() { return document.title; })
  .then(function(title) {
    console.oops('Title:', title);
  })
  .catch(function(error) {  // or `.then(null, function(error) {`
    console.dir(error);
  });
```

That’s why I don’t think a lot of people will trip over this—the above is generally the recommended way to do things (to ensure you catch your own errors in your handler) and it behaves just fine with Nightmare right now.

> And with that in mind, I played around with Nightmare in an attempt to address this issue.

So assuming we *wanted* `then` to behave exactly like a promise’s then (which I am trying not to assume is the case), I think the relevant change would be my first example at the top of this comment.

In your experiment, you’re handling a lot of different conditions explicitly, but still using the `then(onSuccess).catch(onError)` construct, which is the source of the difference in behavior. That is to say, I don’t think your change there would “solve” what I was trying to get at with this issue, though it might solve something else I wasn’t thinking about :)

**Comment by rosshinkley** [comment]
As I'm rereading what I originally wrote, and the original content of my little experiment, three things jump out: one, that I was hopelessly vague; two, that your solution was staring me in the face and I didn't spot it off the bat; and three, I am pretty certain I am way, _way_ off.  (And now I feel silly.  More on your solution/my feelings in a moment.)

>  Is that what you see, or am I misunderstanding what you were getting at here?

I'm following now, and thank you for the clarification.  I can see why you were confused, though: I had gotten it in my head that the way Nightmare implemented `.then()`, it might be eating the exception, making a `.catch()` at the end of a chain never get called.  Clearly not, as `.then()`/`.catch()` with falsey arguments still returns a promise.  Looking over my original notes and sandbox, I'm not entirely sure how I got to the "eats exceptions" conclusion.

> If you always want “done” to get logged, you’d have to do it after handling the error:

No, I wouldn't expect "done" to always get logged, and this is where I _knew_ I had been vague, and was reasonably certain I had done something improperly.  See previous paragraph.  I was well into the weeds and wrong whole cloth.

> So assuming we wanted then to behave exactly like a promise’s then (which I am trying not to assume is the case),

I think expecting Nightmare's `.then()` implementation to behave like a compliant promise seems reasonable.  Why would that be an unfair assumption?  Is there something I'm not thinking of?  More to the point, would there be a reason for Nightmare's `.then()` _not_ to behave like Promise's `.then()`?

> That is to say, I don’t think your change there would “solve” what I was trying to get at with this issue, though it might solve something else I wasn’t thinking about :)

It doesn't, at least nothing your implementation doesn't also solve.  I was fighting my own ignorance - again, see above.

Setting self-deprecation and self-disappointment aside, I agree - especially now that I think (hope?) I understand the problem - this is a pretty minor inconsistency, but an inconsistency nonetheless.  I'd prefer to err on the side of compliance over not.  Thoughts?

**Comment by Mr0grog** [comment]
> Looking over my original notes and sandbox, I'm not entirely sure how I got to the "eats exceptions" conclusion.

I’m betting that might be at least partially my fault; I think I said something to that effect in my description on #516. *In fact,* that is exactly what I thought was happening at the time, before I sat down to really think about it when writing this very issue. The original title was “difference**s** between…” before I realized that wasn’t actually happening :P

> Is there something I'm not thinking of? More to the point, would there be a reason for Nightmare's .then() not to behave like Promise's .then()?

Not that I can think of; that’s why I raised the issue! Hopefully @matthewmueller will fill us in at some point.

> I'd prefer to err on the side of compliance over not. Thoughts?

I would generally agree. But since @matthewmueller didn’t write any docs and didn’t invite any discussion or review of the feature, I didn’t want to make an assumption about whether the non-compliant behavior was intended or just a bug. So I asked by way of this issue :)

**Comment by Mr0grog** [comment]
>> I'd prefer to err on the side of compliance over not. Thoughts?

> I would generally agree. But since @matthewmueller didn’t write any docs and didn’t invite any discussion or review of the feature, I didn’t want to make an assumption about whether the non-compliant behavior was intended or just a bug.

Since this has sat for more than a month with no feedback from @matthewmueller , I’m going to go ahead and just transform it from a question to a statement and call it a bug:

`then()` **should** act like Promises/A+ `then()` and ES6 Promise `then()`. The second argument should not be called because of an exception while running the first argument.

If that’s cool with you, @rosshinkley. The implications are minor and, I think, an improvement.

**Comment by rosshinkley** [comment]
> If that’s cool with you, @rosshinkley. The implications are minor and, I think, an improvement.

👍 Absolutely.  Please, go ahead.
