### ISSUE TITLE
Equivalent to --ignore-ssl-errors in Phantom

### ISSUE THREAD

**Issue by nubunto** [segmentio/nightmare#530]
Hello. First of all, thanks for everyone that contributed to this awesome project!

Is there an equivalent to `--ignore-ssl-errors` (command line parameter in Phantom) in Nightmare?

I was able to find an option to the Nightmare constructor, `ignoreSslErrors` but it doesn't seems to be working (the page gets all dark and nothing happens). I found it outside of official documentation, so I don't really trusted it would work after all.

Thanks!

**Comment by Mr0grog** [comment]
I *think* you should be able to use the `ignore-certificate-errors` switch as documented under [switches](https://github.com/segmentio/nightmare#switches):

```js
var nightmare = Nightmare({
  switches: {
    'ignore-certificate-errors': true
  }
});
```

Does that work for you?

**Comment by nubunto** [comment]
I've been out of the project where I was prototyping with Nightmare, but I'll check it first thing tomorrow and get right back.

**Comment by rosshinkley** [comment]
I can validate that works with the switch enabled.  I posted a brief example in #535.

**Comment by nubunto** [comment]
It worked here as well. Thanks for the help!

**Comment by Mr0grog** [comment]
No problem. @nubunto, do you mind closing this issue since you’ve got it figured out?
