### ISSUE TITLE
Always fail to set cookie

### ISSUE THREAD

**Issue by Velissel** [segmentio/nightmare#531]
It seems like setting a cookie always fails. Below is my config object:

`
{
	show: false,
	images: false,
	waitTimeout: 5000,
	paths: {
		userData: path.join('./appData/userData'),
		temp: path.join('./appData/temp'),
		home: path.join(./appData/home')
	}
}
`

What I have done is: 
start a nightmare instance A to url , login to somewhere, extract all cookies as array, close instance A
then start a another instance B, set cookies to extracted ones from instance A

Problem is B.cookies.set(array) always fails...
`
B.cookies.set(array).then(null, function(err) {
  // err is an empty object...
});
`
One of cookie entry has attribute like:
"domain: something.abc.com","hostOnly":true,"path":"/","secure":false,"httpOnly":true,"session":true,"expirationDate":0
It is the one that fails all the time...
Looks like it is because setting cookie to domain 'something.abc.com' when you are not on that page is causing this problem...
Can anyone help please...

**Comment by rclai** [comment]
I am having this issue as well.

**Comment by rosshinkley** [comment]
I don't think you can transfer cookies across domains.  The [current specification](http://tools.ietf.org/html/rfc6265) that most browsers honor says the domain requested from the browser must match the cookie's origin domain or be a subdomain.  I'm paraphrasing, of course, but that's the spirit.  [This article on the current state of cookie domains](http://bayou.io/draft/cookie.domain.html) does a much more comprehensive job explaining how this works than I could do here.

@Velissel's example appears to be trying to put cookies from one domain onto another, which is forbidden to the best of my knowledge.

@rclai _might_ be talking about something different: are you trying to reuse cookies from the same domain across Nightmare instances?

**Comment by rclai** [comment]
@rosshinkley I figured it out, this issue is not relevant to me anymore.

**Comment by rosshinkley** [comment]
@rclai Ah, okay.  Good to know.  Thanks for the response. :)

**Comment by Velissel** [comment]
@rosshinkley, problem is even with .something.abc.com, it does not work. What I wanted to do is as simple as set cookies before I start anything, but still can not find out a way

**Comment by rosshinkley** [comment]
> ... set cookies before I start anything...
Are you trying to set cookies before your first call to `.goto()`?  I don't think `.cookies.set()` will work prior to a page being loaded.

**Comment by Velissel** [comment]
@rosshinkley, the procedure is like this, I firstly go to google, then try to set cookies of a session I extracted from something.abc.com so that multiple newly opened instances will have the same session when I change those instances to something.abc.com, but it fails all the time no matter if domain is .something.abc.com or something.abc.com.

I tried it with phantomJS, it works with dot prefixed. Maybe it is the implementation of electron preventing it?

**Comment by rosshinkley** [comment]
> ...  I firstly go to google, then try to set cookies of a session I extracted from something.abc.com so that multiple newly opened instances will have the same session when I change those instances to something.abc.com...

@Velissel I understand you want to preload the cookies before navigation, but I don't think Nightmare allows for adding cookies _prior_ to navigation.  I still don't think adding cookies across domains like you're doing is permitted.

With #425, you could probably extend Electron to add a hook to the `'did-start-loading'` event to add cookies prior to the page loading.  If it interests you, I could pull together an experimental plugin to prove feasibility.

> I tried it with phantomJS, it works with dot prefixed. Maybe it is the implementation of electron preventing it?

I'm skeptical it works in exactly the manner you're describing under Phantom.  I'd have to put together an experiment to see for myself.

> As far as I know, cookies without dot as prefix is usually set through set-cookie header section of a server's response, but most modern browsers consider cookies with or without dot at beginning the same now, so I was expecting electron to act the same...

This is correct - with or without is considered equivalent, at least to the best of my knowledge.

> BTW, using persist:somthing does not work for the website I am working on

Could you expand on this?  What exactly isn't working?

**Comment by Velissel** [comment]
> Could you expand on this? What exactly isn't working?

If I get purpose of persist partition correct, the scenario I am having is like this:
1. start an instance with partition set as 'persist:SAHRED_SESSION'
2. open www.example.com
3. type credentials to login
4. page is redirected to something.example.com and cookies for session is set at this point
5. start another instance with partition set as 'persist:SHARED_SESSION'
6. open something.example.com
I was expecting new instance will stay at something.example.com, but the fact is it gets redirected back to www.example.com because session in first instance is not shared with new instance

> @Velissel I understand you want to preload the cookies before navigation, but I don't think Nightmare allows for adding cookies prior to navigation. I still don't think adding cookies across domains like you're doing is permitted.
With #425, you could probably extend Electron to add a hook to the 'did-start-loading' event to add cookies prior to the page loading. If it interests you, I could pull together an experimental plugin to prove feasibility.

If persist partition works then there is no issue on this at all. I know setting cross-domain cookie using javascript is definitely not permitted for safety reason, but when it comes to testing, having a way to preload cookie to keep session status is resonable I feel

**Comment by rosshinkley** [comment]
> start another instance with partition set as 'persist:SHARED_SESSION'

Ah!  I think I see the issue.  I first hit this problem in trying to address #398, and then again in #532 (specifically, [this comment](https://github.com/segmentio/nightmare/issues/532#issuecomment-198070852)).  If you open an instance, log in, and open a second instance with the same persistence data before closing the first, the session information doesn't appear to be shared (or the data from the first session isn't persisted or shareable yet).  I'm _still_ not sure why this is the case.

> ... but when it comes to testing, having a way to preload cookie to keep session status is resonable I feel

I agree, but from the sound of it, you shouldn't have to preload your session cookie to begin with.  That session should persist.

**Comment by 3zzy** [comment]
@rosshinkley  Has this been fixed yet? I'm logging in and then trying to access a protected page but it doesn't store the cookies from the previous session. Is there a workaround to set multiple cookies?
