### ISSUE TITLE
save html page

### ISSUE THREAD

**Issue by nick2012** [segmentio/nightmare#532]
How can we save HTML content?

**Comment by 6pm** [comment]
Hello. Run this code:
`var Nightmare = require('nightmare');
var nightmare = Nightmare({ show: true });
var fs = require('fs');

nightmare
  .goto('http://site.com')
  .evaluate(function () {
    var page =  document.querySelector('body').innerHTML;
    fs.writeFile('page-html.txt', page, function (err) {
        if (err) return console.log(err);
        console.log('Hello World > helloworld.txt');
     });
    return page 
  })
  .end()
  .then(function (result) {
    console.log(result)
  })`
it must be works.

**Comment by nick2012** [comment]
I've tried this: `var Nightmare = require('nightmare');
var nightmare = Nightmare({ show: true });
var fs = require('fs');

nightmare
.goto('http://site.com')
.evaluate(function () {
var page = document.querySelector('body').innerHTML;
fs.writeFile('page-html.txt', page, function (err) {
if (err) return console.log(err);
console.log('Hello World > helloworld.txt');
});
return page 
})
.end()
.then(function (result) {
console.log(result)
})`

but it gives the following error:

```
alex@ubuntu:~/test-nightmare$ node test4.js
ReferenceError: Promise is not defined
    at Nightmare.then (/home/alex/node_modules/nightmare/lib/nightmare.js:311:14)
    at Object.<anonymous> (/home/alex/test-nightmare/test4.js:16:2)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
alex@ubuntu:~/test-nightmare$ 
```

**Comment by rosshinkley** [comment]
What version of Node are you running?  I suspect you're running with <=0.12.x.

If that's the case, you may want to consider running with the `--harmony` switch, including a Promise polyfill like [`promise-polyfill`](https://www.npmjs.com/package/promise-polyfill), or upgrading to a more recent version.

**Comment by nick2012** [comment]
rosshinkley, you are right about that. 
I've updated it, using this tutorial: http://stackabuse.com/how-to-install-node-js-on-ubuntu/
I don't know if everything is ok now, but, now the following happens:

1) I can see Electron opening the page. 
2) I cannot find the saved file. 

This is what I've just ran:

var Nightmare1 = require('nightmare');
var nightmare = Nightmare1({ show: true });
var fs = require('fs');

nightmare
.goto('http://site.com')
.evaluate(function () {
var page = document.querySelector('body').innerHTML;
fs.writeFile('page-html.txt', page, function (err) {
if (err) return console.log(err);
console.log('Hello World > helloworld.txt');
});
return page; 
})
.end()
.then(function (result) {
console.log(result)
})

**Comment by rosshinkley** [comment]
@nick2012 At a glance, the linked article should work fine.  Glad you got that sorted.

For your source, you're trying to write the file inside of an `.evaluate()` call, which runs in the Electron instance, not in your source.  Evaluated functions are stringified, transmitted to the wrapped Electron instance, and rebuilt using the `Function` constructor.  The variable lifting you're doing with `fs` won't work as the function is constructed and run in an entirely separate context, and `fs` is not included in the context object.  (Off the top of my head, I don't think `require` is even on the context object that is applied against `.evaluate()`.  Even if you wanted to include it there, I don't think you could.)

Fixing it should be straightfoward: rather than trying to write the file interior to `.evaluate()`, move the write out to `.then()`.  Something like:

```js
var Nightmare1 = require('nightmare');
var nightmare = Nightmare1({
  show: true
});
var fs = require('fs');

nightmare
  .goto('http://site.com')
  .evaluate(function() {
    return document.querySelector('body')
      .innerHTML;
  })
  .end()
  .then(function(page) {
    fs.writeFile('page-html.txt', page, function(err) {
      if (err) return console.log(err);
      console.log('Hello World > helloworld.txt');
    });
  })
```
... should get you headed in the right direction.

**Comment by nick2012** [comment]
Thank you very much, rosshinkley.
You've really helped me a lot, also in understanding how it does work.

**Comment by nick2012** [comment]
rosshinkley, may I ask you a few more questions?
1) How can I feed this line from a txt file filled with links? ".goto('http://site.com')" so that the script would connect and save a bunch of different links?
2) Can I somehow make it save the cookies, so that it doesn't login each time I run the script using the credentials that I provide?

**Comment by rosshinkley** [comment]
> rosshinkley, may I ask you a few more questions?

Of course.  I'm happy to help. :)

> 1) How can I feed this line from a txt file filled with links? ".goto('http://site.com')" so that the script would connect and save a bunch of different links?

It depends on how sophisticated you need to be.  The following example will work with reasonably small file sizes and uses `Array.reduce` to run promises sequentially:

```js
var Nightmare1 = require('nightmare');
var nightmare = Nightmare1({
  show: true
});
var fs = require('fs');
var URL = require('url');

//split the read links on operating-specific newlines into an array
var links = fs.readFileSync('links.txt')
  .toString()
  .split(require('os')
    .EOL);

//filter out blank lines
links = links.filter(function(link){
  return !(/^\s*$/.test(link));
});

//use `Array.reduce` to run promises sequentially
links.reduce(function(accumulator, url) {
  return accumulator.then(function() {
    return nightmare.goto(url)
      .evaluate(function() {
        return document.querySelector('body')
          .innerHTML;
      })
      .then(function(page) {
        var filename = URL.parse(url).hostname + '.txt';
        fs.writeFileSync(filename, page);
      })
  })
}, Promise.resolve())
  .then(function() {
    nightmare.end(function() {
      console.log('done');
    });
  });
```

> 2) Can I somehow make it save the cookies, so that it doesn't login each time I run the script using the credentials that I provide?

I thought the session information is persisted to the default session.  This _should_ work out of the box.  However, if you open an instance, log in, and open a second instance with the same persistence data before closing the first, the session information doesn't appear to be shared (or the data from the first session isn't persisted or shareable yet).  Does this differ from the behavior you're seeing?

You may also want to take a look at [`webPrefereces.partition`](https://github.com/atom/electron/blob/master/docs/api/browser-window.md#new-browserwindowoptions), as well as [`options.paths`](https://github.com/segmentio/nightmare#paths).  #398 might also interest you.

**Comment by nick2012** [comment]
Thank you. Everything that you wrote works perfect. 
Now I realize that I have to handle various scenarios, like selector has a different prefix, and the script does not click it, or selector doesn't exist at all and the script should continue with the next page. :)
You are right about the cookies also. At first it didn't keep it, but now it does. Strange.

Do you think there's something simpler for crawling than Javascript based APIs? 
I find it so hard to advance with all these restrictions. 
I liked so much the freedom of Perl. Too bad that mechanize::firefox fails for some unknown reason to me.

**Comment by rosshinkley** [comment]
> Thank you. Everything that you wrote works perfect.

No problem, although it sounds like it might be insufficient.

> Now I realize that I have to handle various scenarios, like selector has a different prefix, and the script does not click it, or selector doesn't exist at all and the script should continue with the next page.

You can still do that, but it requires increasing complexity inside the `Array.reduce`.  It's also worth mentioning that you could write arguably neater code using something like `vo` or `co`.  For example, the above rewritten using `vo` might look like this:

```js
var Nightmare1 = require('nightmare');
var nightmare = Nightmare1({
  show: true
});
var fs = require('fs');
var URL = require('url');
var vo = require('vo');

var run = function * () {
  //split the read links on operating-specific newlines into an array
  var links = fs.readFileSync('links.txt')
    .toString()
    .split(require('os')
      .EOL);

  //filter out blank lines
  links = links.filter(function(link) {
    return !(/^\s*$/.test(link));
  });

  //run the page HTML retrieval and save for each link
  for (var ix in links) {
    var page = yield nightmare.goto(links[ix])
      .evaluate(function() {
        return document.querySelector('body')
          .innerHTML;
      });
    var filename = URL.parse(links[ix]).hostname + '.txt';
    fs.writeFileSync(filename, page);

  }
  yield nightmare.end();
};

vo(run)(function(err){
  console.log('done');
});
```

... that might make it simpler to add conditions and add logic you need.

> You are right about the cookies also. At first it didn't keep it, but now it does. Strange.

I tried digging into this when looking at #398, but didn't get terribly far.  For now, I'm accepting that it's a known quirk, but I'd love to know the underlying reason.

> Do you think there's something simpler for crawling than Javascript based APIs? 
I find it so hard to advance with all these restrictions. 

Have a look at the above `vo` example.  It sounds like using generators + a flow control library might make more sense to you.

**Comment by rosshinkley** [comment]
I believe this matter is closed.  Closing.

**Comment by nick2012** [comment]
Hi,
Can you please tell me how can I use this one in a simple script?I don't understand how to integrate this code. I find JS so difficult compared to Perl...
/**
 * Save page markup to a file. Respect an existing savePageContent function, if
 * casper.js core introduces one.
 * 
 * @param String targetFile
 *   A target filename.
 * @return Casper
 */
casper.savePageContent = casper.savePageContent || function(targetFile) {
  var fs = require('fs');
  var f  = require('utils').format;

  // Get the absolute path.
  targetFile = fs.absolute(targetFile);
  // Let other code modify the path.
  targetFile = this.filter('page.target_filename', targetFile) || targetFile;
  this.log(f("Saving page html to %s", targetFile), "debug");
  // Try saving the file.
  try {
    fs.write(targetFile, this.getPageContent(), 'w');
  } catch(err) {
    this.log(f("Failed to save page html to %s; please check permissions", targetFile), "error");
    this.log(err, "debug");
    return this;
  }

  this.log(f("Page html saved to %s", targetFile), "info");
  // Trigger the page.saved event.
  this.emit('page.saved', targetFile);

  return this;
};Thank you.
Best regards,
