### ISSUE TITLE
Setting up a Nightmare.js test with Electron and a self signed certificate

### ISSUE THREAD

**Issue by CrashyBang** [segmentio/nightmare#535]
Thought I would add this here to as it may be helpful to others:
 
Trying to get Nightmare up and running with a local dev site with self signed certificates.

Link to full question here: http://stackoverflow.com/questions/36001701/setting-up-a-nightmare-js-test-with-electron-and-a-self-signed-certificate

**Comment by rosshinkley** [comment]
Looks like you removed your question on SO.  Also, this _might_ be a duplicate of #530.

I'm assuming you're having trouble with the self-signed certificate giving you security problems.  Is that the issue you're having?

If so, you should be able to use [`ignore-certificate-errors` switch](https://github.com/segmentio/nightmare#switches) to clear that up.  A quick example might be useful.

The Express server using a self-signed SSL certificate:
``` js
var fs = require('fs'),
  http = require('http'),
  https = require('https'),
  express = require('express');

var port = 8000;

var options = {
  key: fs.readFileSync('./ssl/key.pem'),
  cert: fs.readFileSync('./ssl/cert.pem'),
};

var app = express();

var server = https.createServer(options, app)
  .listen(port, function() {
    console.log("Express server listening on port " + port);
  });

app.get('/', function(req, res) {
  res.writeHead(200);
  res.end("<div id='hello'>hello world</div>");
});
```

The Nightmare script:
```js
var Nightmare = require('nightmare'),
  nightmare = Nightmare({
    switches: {
      'ignore-certificate-errors': true
    }
  });

nightmare.goto('https://localhost:8000').evaluate(function(){
  return document.querySelector('#hello').innerText;
}).then(function(text){
  console.log(text);
  nightmare.end(function(){
    console.log('done');
  });
});
```
... prints "hello world" without issue.

**Comment by CrashyBang** [comment]
Hey @rosshinkley,

Thank you, yeah sorry I removed my SO question should have updated here I actually did not have my `.dev` domain added to me ehosts and Chromes `.dev` magic was working for me but electron obviously does not do that.

Sorry for the question felt like a fool when I figured it out.

Cheers,
Otis.

**Comment by rosshinkley** [comment]
@CrashyBang Ahhh, okay.  That makes sense.  Glad you got it sorted out.
