### ISSUE TITLE
Is it possible to include nightmare in a electron application?

### ISSUE THREAD

**Issue by tommasosotte** [segmentio/nightmare#539]
The application I've built in electron is based on nightmare to fetch and create content.
I have nightmare on dependecies. When I build the application with electron-builder it does not give me errors.
When I start the packaged electron application the console tells me that "there's no electron-prebuilt node modules"

**Comment by sonnhy** [comment]
Anyone?
Maybe I've explained it badly, are any clarification needed?

**Comment by bjrmatos** [comment]
keep track of #393 , i will find time to support that

**Comment by sonnhy** [comment]
I need nightmare to make the app I'm working on to run, as I've not found a better alternative for electron.
Thanks, I really aprreciate!

**Comment by rosshinkley** [comment]
This should be merged with #393, closing.

**Comment by starInEcust** [comment]
hi guys! how's it going?

I just need to include nightmare in a electron application
