### ISSUE TITLE
Block external scripts and css

### ISSUE THREAD

**Issue by justinmchase** [segmentio/nightmare#540]
I would like to load up a page and block all scripts that aren't from the same domain as well as block all requests for css files. Can someone point me in the right direction to figure out how to do this?

**Comment by rosshinkley** [comment]
You can't... yet.  Nightmare does not expose `win.session.webRequest.onBeforeRequest` directly.  

This topic was discussed in #461: #425 would allow for hooking into the Electron events directly.  I put together [a load filter plugin](https://github.com/rosshinkley/nightmare-load-filter) to be published once that PR is accepted.

**Comment by justinmchase** [comment]
Cool, I'll check those out and see if I can help. Thanks.

**Comment by justinmchase** [comment]
This PR appears to implement the feature I was looking for: #495

**Comment by rosshinkley** [comment]
#495 _could_ work, but it's not as flexible as #425.  You lose access to other parts of the Electron internals as well as the ability to pass arguments (or do any kind of variable lifting) to the handlers themselves.

**Comment by justinmchase** [comment]
Yeah after looking at the load filter plugin you made, I do think I like that. It appears to be the same thing only as an extension and more explicitly related to "filtering". Thanks for the explanations.

**Comment by sebastienbarre** [comment]
For those people landing here, you would want to try this:
```javascript
var Nightmare = require('nightmare');
require('nightmare-load-filter')(Nightmare);
var nightmare = Nightmare();

nightmare
  .filter({
    urls: [ 'http://foo/bar/*.css' ],
  }, function(details, cb) {
    return cb({ cancel: true });
  })
  .goto('whatever')
... etc
```
For testing purposes, you can display the URL being filtered from the listener:
```javascript
  }, function(details, cb) {
    console.log(details.url);
    return cb({ cancel: true });
  })
```
then run your script using:
```
DEBUG=electron:stdout node test.js
```

**Comment by AlexanderKozhevin** [comment]
Well, maybe there is a simpler  solution. 
Just rewrite hosts on machine and return some "hello world" instead of real script.
So change operation system configuration or router protection.

**Comment by KingWu** [comment]
just try @sebastienbarre  way. but css still load. @AlexanderKozhevin any solution for this issue?

**Comment by justinmchase** [comment]
The filter method does work you may just have to adjust your filter.

Here is the mozilla documentation on how to formulate your filter:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webRequest/RequestFilter

This worked for me in my case:
```
import Nightmare from 'nightmare'
import filter from 'nightmare-load-filter'

filter(Nightmare) // load the filter plugin

// https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webRequest/ResourceType
const filterTypes = [
  'beacon',
  'csp_report',
  'font',
  'image',
  'imageset',
  // 'main_frame', // actual content
  'media',
  'object',
  'object_subrequest',
  'ping',
  // 'script', // critical for processing data
  'stylesheet',
  'sub_frame',
  'web_manifest',
  'websocket',
  'xbl',
  'xml_dtd',
  // 'xmlhttprequest', // let these through
  'xslt',
  'other'
]


const nightmare = Nightmare({ show: false })
nightmare
  .filter({ types: filterTypes }, (details, response) => response({ cancel: !details.url.match(/[.]html/) }))
  .goto(link)
  .wait(`body`)
  .evaluate(() => {
    return document.querySelector('.exampleSelector').innerText
  })
  .end()
  .then(result => {
    console.log(result) 
  })
  .catch(err => console.log(err))

**Comment by amkayondo** [comment]
> The filter method does work you may just have to adjust your filter.
> 
> Here is the mozilla documentation on how to formulate your filter:
> https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webRequest/RequestFilter
> 
> This worked for me in my case:
> 
> ```js
> import Nightmare from 'nightmare'
> import filter from 'nightmare-load-filter'
> 
> filter(Nightmare) // load the filter plugin
> 
> // https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webRequest/ResourceType
> const filterTypes = [
>   'beacon',
>   'csp_report',
>   'font',
>   'image',
>   'imageset',
>   // 'main_frame', // actual content
>   'media',
>   'object',
>   'object_subrequest',
>   'ping',
>   // 'script', // critical for processing data
>   'stylesheet',
>   'sub_frame',
>   'web_manifest',
>   'websocket',
>   'xbl',
>   'xml_dtd',
>   // 'xmlhttprequest', // let these through
>   'xslt',
>   'other'
> ]
> 
> 
> const nightmare = Nightmare({ show: false })
> nightmare
>   .filter({ types: filterTypes }, (details, response) => response({ cancel: !details.url.match(/[.]html/) }))
>   .goto(link)
>   .wait(`body`)
>   .evaluate(() => {
>     return document.querySelector('.exampleSelector').innerText
>   })
>   .end()
>   .then(result => {
>     console.log(result) 
>   })
>   .catch(err => console.log(err))
> ```

i got `TypeError: NightMare.filter is not a function`
