### ISSUE TITLE
entering text with multiple lines - how to go to a new line with enter key after a line

### ISSUE THREAD

**Issue by sanathko** [segmentio/nightmare#541]
I am trying to enter multiple lines of text in a text area using nightmare. This is my sample code snippet.

```
nightmare
  .goto('http://www.google.com/intl/si/inputtools/try/')
  .type('textarea[id="demobox"]', 'typing text line 1')
  //enter key for new line
  .wait(200)
 .type('textarea[id="demobox"]', 'typing text line 2')
  //enter key for new line
  .wait(200)
  .evaluate(function () {
    return document.querySelector('#demobox').value
  })
  .end()
  .then(function (result) {
    console.log(result)
```
  })

how can this be done? 

I tried using 
`.type('textarea[id="demobox"]', '/n') `
 but didn't work

**Comment by rosshinkley** [comment]
Nightmare's `.type()` splits the string into characters blindly, causing `\n` to be typed as `['\', 'n']`.

There are two alternatives I can think of.  One, [use `.insert()`](https://github.com/segmentio/nightmare#insertselector-text).  The `.insert()` method adds text without triggernig keyboard events.  Text will be entered into the selector as passed, honoring newlines, backspaces, etc.  

Two,  use `.evaluate()`.  If you need keyboard events (eg `keyup`, `keydown`, etc) to occur with the typed text, use `.type()` as you are now followed by an `.evaluate()` call.  Something like:
```js
nightmare
  .goto('http://www.google.com/intl/si/inputtools/try/')
  .type('textarea[id="demobox"]', 'typing text line 1')
  .evaluate(function(){
    document.querySelector('#demobox').value += '\n';
  })
  .wait(200)
 .type('textarea[id="demobox"]', 'typing text line 2')
  .evaluate(function () {
    return document.querySelector('#demobox').value
  })
  .end()
  .then(function (result) {
    console.log(result)
})
```
It's worth pointing out that the keyboard events will not be fired for the newline.  Do you need the keyboard events for the newline?

**Comment by sanathko** [comment]
I was able to move to a new line using insert with \n. Thanks for that.
I am trying to use google input tools (http://www.google.com/intl/cn/inputtools/try/), so that after each letter I need to use the enter key. will this be possible?

**Comment by rosshinkley** [comment]
@sanathko I think so.

A little more research (and some later issues, notably #549 and #559) shows that you could also include a unicode character.  Something like `.type('#demobox', 'typing text line 1\u000d')`.

**Comment by rosshinkley** [comment]
@sanathko I'm considering this issue closed.  If you have more problems with this, feel free to reopen/open a new issue.

**Comment by jchook** [comment]
Hey I found this issue while searching "nightmare type enter" and wanted to leave my solution here for anyone else who may need it:

`"my string to type" + String.fromCharCode(13);`
