### ISSUE TITLE
async code in evaluate function

### ISSUE THREAD

**Issue by johncornell** [segmentio/nightmare#543]
Hi all, 
I'm triyng to build a scraper for a site that needs login with captcha. I want that a certain point nightmare waits for the user to fill in the solution for the captcha in the prompt, then submit the form.
Basically, the problem is that I can't write async code in an evaluate function. Is it possible at all? Here is my code:

```

var nightmare = Nightmare({
    show: true,
        switches: {
            'proxy-server': 'socks5://127.0.0.1:9150',
            'ignore-certificate-errors': true
        }
})

nightmare
    .goto(myurl)
    .type('input[name="username"]', 'myuser')
    .type('input[name="password"]', 'mypass')

    .evaluate( function(){
        prompt.start();
        return prompt.get(['captcha: '])
    })
    .then(function(c){
        console.log("this is the captcha :)")
        console.log(c);
    })

```

**Comment by rosshinkley** [comment]
I assume you're using [prompt](https://www.npmjs.com/package/prompt)?  It's not included in the sample you provided.

If so, the first issue is `.evaluate()` is intended for executing code on the page.  I'm guessing you want to prompt the user for the captcha.  For that, you should probably have that inside of a `.then()`.

Setting that aside, one option is wrapping `prompt.get()` in a new Promise.  Something like: 
```js
nightmare
    .goto(myurl)
    .type('input[name="username"]', 'myuser')
    .type('input[name="password"]', 'mypass')

    .then( function(){
        prompt.start();
        return new Promise(function(resolve, reject){
            prompt.get(['captcha'], function(err, values){
                if(err){
                    return reject(err);
                }
                resolve(values);
            });
        });
    })
    .then(function(c){
        console.log("this is the captcha :)")
        console.log(c.captcha);
    })
```

**Comment by johncornell** [comment]
Thanks @rosshinkley, it's all clearer now. I still have some doubts about the general behaviour of the framework: when I try to do some action after an evaluate-then couple, I get an error. So what if I want to do some stuff, then evaluate something on the page, then continue the navigation (i.e. go to a second link of the site with goto)? This is useful if I want to use always the same Electron window to retain the logon credentials.

**Comment by rosshinkley** [comment]
> ... when I try to do some action after an evaluate-then couple, I get an error. 

Could you provide a minimal example?

> So what if I want to do some stuff, then evaluate something on the page, then continue the navigation (i.e. go to a second link of the site with goto)? 

In keeping with using the Promise API, you could return a Nightmare chain from the `.then()` to the next `.then()` call.  An example would be helpful.  Reusing the previous, this time with added actions:

```js
nightmare
    .goto(myurl)
    .type('input[name="username"]', 'myuser')
    .type('input[name="password"]', 'mypass')

    .then( function(){
        prompt.start();
        return new Promise(function(resolve, reject){
            prompt.get(['captcha'], function(err, values){
                if(err){
                    return reject(err);
                }
                resolve(values);
            });
        });
    })
    .then(function(c){
        console.log("this is the captcha :)")
        console.log(c.captcha);
    })
    .then(function(){
        //this could also be the return value of the previous `then`
        //type something into a selector, click something, then evaluate the result of an element
        //the return of evaluate will be passed as an argument to the next call to `then`
        return nightmare
            .type('some.other.selector', 'hello world')
            .click('some.selector')
            .evaluate(function(){
                return document.querySelector('yet.another.query').value;
            });
    })
    .then(function(value){
        console.log(value);
    });
```

**Comment by johncornell** [comment]
That made the job. Thanks again and sorry for the silly questions, I just didn't get how nightmare works.

**Comment by rosshinkley** [comment]
@johncornell No problem.  Closing.

**Comment by dcy0701** [comment]
thanks
