### ISSUE TITLE
Can't end Nightmare from chained promise

### ISSUE THREAD

**Issue by wyqydsyq** [segmentio/nightmare#546]
I'm using Nightmare in conjunction with tape in order to produce TAP output from my automated tests.
I have a test where I'm doing a chain of commands and assertions, e.g. assert a button exists, click the button, assert the expected result (opening an iframe) happened.

I've noticed some weird behaviour in ending Nightmare, I cannot call `.end()` after a `.then()` or within a `.then()`, which would be the logical place to put it, example:

````
var Nightmare = require('nightmare'),
  test = require('tape'),
  newWindow = function(url){
    return Nightmare({show: false}).goto(url);
  };

test('Example', function(t){
  var window = newWindow('http://localhost:3000/');

  // find script tag
  window.exists('script[src="./button.js"]')
  .then(function(r){
    t.ok(r, 'Found a script tag');
  })

  // find button
  .then(function(){
    return window.exists('button');
  })
  .then(function(r){
    t.ok(r, 'Found button');
  })

  // click button
  .then(function(){
    return window.click('button').exists('iframe');
  })
  .then(function(r){
    t.ok(r, 'Clicking button created iframe');
  })

  // find login button
  .then(function(){
    return window.evaluate(function(){
      return document.querySelector('iframe').contentDocument.querySelector('input[name="login"]');
    }).end();
  })
  .then(function(r){
    t.ok(r, 'Found login button inside iframe');
  })

  // end test
  .then(function(){
    t.end();
  });
});
````

This code works as expected, my issue is that I need to place `.end()` on the last call to `window` (my nightmare instance) so if I add more steps I need to move the `.end()` call to the last promise.

Putting `.end()` on the last `.then()` doesn't work, nor does calling `window.end()` within the last `.then()`. Is there any way I can do this cleaner than manually ensuring my last call to the nightmare instance is followed by `.end()` ?

Thanks

**Comment by rosshinkley** [comment]
Out of the box, `.end()` puts another action in the action queue, same as anything else.  Modifying your example, excerpted for brevity:

```js
  // find login button
  .then(function(){
    return window.evaluate(function(){
      return document.querySelector('iframe').contentDocument.querySelector('input[name="login"]');
    });
  })
  .then(function(r){
    t.ok(r, 'Found login button inside iframe');
  })
  // end test
  .end()
  .then(function(){
    //instance is ended
  });
```

Alternatively, you could pass a callback to `.end()` as without it, Nightmare assumes you wanted to add the action to the queue.  Again, using your example:

```js
```js
  // find login button
  .then(function(){
    return window.evaluate(function(){
      return document.querySelector('iframe').contentDocument.querySelector('input[name="login"]');
    });
  })
  .then(function(r){
    t.ok(r, 'Found login button inside iframe');
  })
  .then(function(){

    //instance is ended
  });
```
```

**Comment by Mr0grog** [comment]
I know this has been sitting for a bit and wanted to make a minor note here. @wyqydsyq you should be able to make your final `then()` to end the test work by simply *returning* `t.end()`, like so:

```js
// end test
.then(function(){
  return t.end();
});
```

As @rosshinkley noted, “`.end()` puts another action in the action queue, same as anything else,” so just calling `.end()` at the end queues up the end action, but never executes it. Returning a thennable from a promise handler causes that thennable to be run automatically, so the above code is *kind of* like:

```js
// end test
.then(function() {
  t.end().then();
})
```

…but either way, yeah, this is definitely a little confusing :\

**Comment by kuraga** [comment]
@rosshinkley @Mr0grog your explanations are very helpful but you confuse `t.end()` with `window.end()`. I won't check your code snippets but this works, @wcjohnson11 :
```js
var Nightmare = require('nightmare');
var tape = require('tape');

tape('Nightmare test', function (t) {
  var nightmare = Nightmare();
  nightmare
    .goto('http://localhost:4567/#1')
    .wait('.node-info')
    .exists('.node-info')
    .then((exists) => {
      t.assert(exists);
    })
    .then(() => {
      nightmare.end().then(() => {
        t.end()
      });
    });
});
```

**Comment by kuraga** [comment]
P.S. @rosshinkley , Add `queue` argument to callbacks, maybe? And why result of `nightmare.then(cb)` isn't chainable? Is it good that `TypeError: nightmare.goto(...).wait(...).exists(...).then(...).end is not a function`?

**Comment by Mr0grog** [comment]
@kuraga Augh, sorry. Did not read carefully :(

Either way, `.then(function() { return nightmare.end(); })` (or `.then(() => nightmare.end()` if you have fat arrow support) will do what you want. Hopefully that, at least, was clear!

As an even more concise bonus, since `tape.end()` takes a potential error as its first argument, you can *probably* (I haven’t tested this) do `nightmare.end(t.end)` at any point to end your tests, too.

**Comment by rosshinkley** [comment]
Oh boy, I didn't read carefully either.  I apologize.  Good catch, @kuraga.

> P.S. @rosshinkley , Add queue argument to callbacks, maybe? And why result of nightmare.then(cb) isn't chainable?

It is... insofar as `.then()` returns a native promise, and can chain promise methods off of it (eg, another `.then()`).

> Is it good that TypeError: nightmare.goto(...).wait(...).exists(...).then(...).end is not a function?

Promises don't expose `.end()`, Nightmare does.  Once you call `.then()`, you're not dealing with a Nightmare instance anymore, you're dealing with a native promise.  If you wanted `.then()` to execute (and clear the queue) _before_ calling `.end()`, something like:

```js
nightmare
  .goto(url)
  .click('some-selector')
  .then(function(){
    //current chain has run
    //do some other logic
    return nightmare.end();
  })
  .then(function(){
    //nightmare is now ended
  })
```
... should work.

**Comment by kuraga** [comment]
@rosshinkley @Mr0grog @wyqydsyq 
Hm, but for `.evaluate` it really doesn't work!
```js
  t.test('информацию об узле 2', function(t) {
    page
      .wait('.node-info')
      .evaluate((selector) => {
        console.log(1);
        return document.querySelector(selector).innerText;
      }, '.node-info')
      .then((text) => {
        console.log(2);
        expect(text).to.match(/Информация об узле 1:/);
      }).then(() => {
        console.log(3);  // ISN'T CALLED!
        t.end();
      });
  });
```

**Comment by Mr0grog** [comment]
@kuraga Does your expectation (`expect(text).to.match(/Информация об узле 1:/)`) fail? If so, `console.log(3)` *shouldn’t* be called, because that’s in a success handler. The failed expectation will throw an exception, which will cause the promise returned by the `then` that it’s in to *reject* instead of resolve.

So if that’s your problem, you should probably:

```js
  t.test('информацию об узле 2', function(t) {
    page
      .wait('.node-info')
      .evaluate((selector) => {
        console.log(1);
        return document.querySelector(selector).innerText;
      }, '.node-info')
      .then((text) => {
        console.log(2);
        expect(text).to.match(/Информация об узле 1:/);
      }).then(() => {
        console.log(3);
        t.end();
      }).catch((error) => {
        console.log(’something failed:’, error);
        t.end(error);
      });
  });
```

or

```js
...
      }).then(() => {
        console.log(3);
        t.end();
      }).catch(t.end);
```

**Comment by kuraga** [comment]
Yeah, you're completely right, thanks!

**Comment by kuraga** [comment]
@wyqydsyq you also can use `[t.plan()](https://github.com/substack/tape#tplann)`

**Comment by rosshinkley** [comment]
@wyqydsyq I'm considering this issue resolved.  If you have any more questions, feel free to reopen/open a new issue.
