### ISSUE TITLE
selectors for elements inside iframes

### ISSUE THREAD

**Issue by AVVS** [segmentio/nightmare#547]
How do I easily use elements inside an iframe of a page?
Lets assume we have a path like:

`body iframe#id1 #email`

and I want to

```js
.wait('#email')
.type('#email', 'xxx@example.com')
```

How do I do that without writing functions to select elements like `document.getElementById('myframe1').contentWindow.document.getElementById('x')`

**Comment by rosshinkley** [comment]
I don't think you can - at least, not yet.  You might want to read through #203  and #496.

**Comment by rosshinkley** [comment]
Merging with #203, closing.
