### ISSUE TITLE
Wait for promise to settle in document

### ISSUE THREAD

**Issue by marcoscaceres** [segmentio/nightmare#552]
It would be great if there was a means to `.evaluate()` and wait on a promise. For example:

```JS
nm.evaluate(function(nmjsResolver, nmjsRejector){
   navigator.api.
    .waitForThing
    .then(result => nmjsResolver(result))
    .catch(nmjsRejector);
});
```

This could avoid the unnecessary polling that Nightmarejs currently does while waiting for values to become true in the document.

**Comment by rosshinkley** [comment]
I'm not clear on what you're asking.  Are you asking if `.evaluate()` could wait on a promise internally?  Or are you asking if Nightmare can somehow pick up document changes via events to make `.wait()` passive?

**Comment by marcoscaceres** [comment]
> I'm not clear on what you're asking. Are you asking if .evaluate() could wait on a promise internally?

Sorry for not being clear. Yes, that's what I'm asking for. In fact, you could even check if the function passed to evaluate is a GeneratorFunction and underpin evaluate() with promise handling machinery ala async/await or returns a promise. This would allow evalute() to continue to be backwards compatible, but also work with async functions:

```
nm.evaluate(function*(){
   const response  = yield fetch("thing");
   const json = yield response.json();
   return json; 
});
```

Or eventually:

```JS
nm.evaluate(async function(){
   const response  = await fetch("thing");
   const json = await response.json();
   return json; 
}).then(json => doSomethingElse);
```

> Or are you asking if Nightmare can somehow pick up document changes via events to make .wait() passive?

No. Though semantically that could make sense... it would be like `waitUntil(promiseToResolve)` [API in Service Workers](https://www.w3.org/TR/service-workers/#wait-until-method).

**Comment by ivan-kleshnin** [comment]
Any updates? I'd like to have this implemented as well.
