### ISSUE TITLE
Documentation for firing keypress using .type and unicode

### ISSUE THREAD

**Issue by djdavidi** [segmentio/nightmare#559]
When I used nightmare and a mobile useragent, some of the clickable buttons went away and I was trying to fire an enter keypress using `.evaluate`. However, using `.type('document', '\u000d')` is much simpler and easier to fit into the flow of code. Would that be something that I could add to the documentation? Thanks.

**Comment by rosshinkley** [comment]
@djdavidi I'd be open to including a bit about unicode characters.

**Comment by Mr0grog** [comment]
Is this solved by #560? If so, someone should close this.

**Comment by rosshinkley** [comment]
@Mr0grog I meant to do that yesterday after 2.3.1 and got sidetracked.  Closing.
