### ISSUE TITLE
openDevTools hangs the electron instance.

### ISSUE THREAD

**Issue by itsyogesh** [segmentio/nightmare#563]
Hi there,

I was trying to get openDevTools to work for debugging, but as soon as it opens the electron instance, it hangs the operation and exits after a few seconds. Is this an issue, since the openDevTools was added recently and I couldn't find any tests to check if I am doing this correctly.

Here is the debug output:
```
nightmare:log did-start-loading +508ms [{"sender":{"session":{"cookies":{},"webRequest":{}},"hostWebContents":null,"devToolsWebContents":null,"debugger":{},"_maxListeners":0,"_events":{"page-title-updated":[null,null],"crashed":[null,null]},"_eventsCount":28,"browserWindowOptions":{"show":true,"openDevTools":true,"alwaysOnTop":true,"webPreferences":{"preload":"/Users/Yogesh/Projects/drift/node_modules/nightmare/lib/preload.js","nodeIntegration":false}}}}]
  nightmare electron child process exited with code null: undefined +4s
```

**Comment by rosshinkley** [comment]
Hm, that's one of mine, and I should have added unit tests for it.  I'll add that to my list.

What bothers me about your particular case is the "exited with code null" bit: The only time that happens (at least that I'm aware of) is when a segmentation fault occurs in Electron.  Could you provide a minimum case that reproduces the issue?

**Comment by rosshinkley** [comment]
Suspicion confirmed, this is a segfault internal to Electron that appears to happen with the version of Electron Nightmare is currently on.  It does not happen with the current version of `electron-prebuilt` (0.37.5 at the time of this comment).  Curiously, electron/electron#4103 is the closest problem I can find in the repository.  It's not exactly the same thing, but the symptoms are very similar.

At any rate, I'll put together a PR with the requested tests and a version bump.

**Comment by lunow** [comment]
In the latest version, `webPreferences` setting on nightmare object causing this problem for me: electron instance is crashing immediately.

**Comment by rosshinkley** [comment]
@lunow if that's true, it's likely got a different cause.  Could you open a new issue with a minimal reproduction case?
