### ISSUE TITLE
Grab URL from page, then goto it

### ISSUE THREAD

**Issue by jamesaspence** [segmentio/nightmare#580]
Hi all,

I'm attempting to go to a page, grab a URL from an anchor tag, and then use `goto` to change the current browser window to that URL (since otherwise it opens a new window I'm unable to access at all).

I don't see a way to do this in the docs. Is this possible?

I've tried using `evaluate.then` to return the url to `then`, which works, but then I can't change my current nightmare instance from within the `then`. It appears to have no effect.

EDIT: The equivalent of what I'm trying:

```
var nightmare = Nightmare({});
nightmare.goto('http://website.com')
    .evaluate(function () {
        return document.querySelector('#url').href;
    })
    .then(function (url) {
        //Never does anything, never changes the current URL
        nightmare.goto(url);
    })
```

**Comment by rosshinkley** [comment]
Judging from your example, it looks like you're queuing the `.goto()` action but not executing it.  What happens if you modify your example to something like:

```js
var nightmare = Nightmare({});
nightmare.goto('http://website.com')
    .evaluate(function () {
        return document.querySelector('#url').href;
    })
    .then(function (url) {
        return nightmare.goto(url);
    })
    .then(function(){
        //nightmare should be at the url from evaluate
    })
```

**Comment by jamesaspence** [comment]
Works perfectly! Thanks for the help.
