### ISSUE TITLE
Execute Javascript URL in goto

### ISSUE THREAD

**Issue by uncledlm** [segmentio/nightmare#590]
I have a page that has a javascript function that gets executed to navigate.  In version 2.3.1 of nightmare I could:

.goto('javascript:__doPostBack(\'ctl100$ctl00$MainMenu\',\'DAT\')')

and it navigated successfully.  When I upgraded nightmare to v2.3.3 it stopped. Here is the return error

{ message: 'navigation error',
      code: -1000,
      details: 'unhandled protocol',
      url: 'javascript:__doPostBack(\'ctl00$ctl00$MainMenu\',\'DAT\')' }

**Comment by Mr0grog** [comment]
Ah, this is definitely a result my trying to fix URLs that caused Electron to hang in #553. I think it’ll need a little investigation to make sure all the new load handling machinery works if you use a `javascript:` URL.

In the mean time, you ought to be able to use [evaluate](https://github.com/segmentio/nightmare#evaluatefn-arg1-arg2):

```js
nightmareInstance.evaluate(function() {
  __doPostBack('ctl100$ctl00$MainMenu','DAT');
});
```

Honestly, that might be a better solution anyway unless there’s something very particular about your use case.
