### ISSUE TITLE
Can nightmare render to a buffer?

### ISSUE THREAD

**Issue by trusktr** [segmentio/nightmare#592]
Is there some way to get the pixels of what Nightmare is doing? Would be cool to specify a window size that Nightmare operates in and then get those pixels to pipe them somewhere.

**Comment by Mr0grog** [comment]
You could write a plugin that does this—on the Electron side, just subscribe to `FrameManager’s `data` event and you’ll receive a buffer with full-frame image data each time the browser window renders.

Maybe something like (totally untested):

```js
Nightmare.action(
  'renderStream',
  function(name, options, parent, win, renderer, done) {
    var manager = FrameManager(win);
    function sendFrame(buffer) {
      parent.emit('renderStreamFrame', buffer);
    }
    parent.on('startRenderStream', function() {
      manager.on('data', sendFrame);
    });
    parent.on('stopRenderStream', function() {
      manager.removeListener('data', sendFrame);
    });
    done();
  },
  function(done) {
    this.child.emit('startRenderStream');
    done();
  });

Nightmare.action('stopRenderStream', function(done) {
  this.child.emit('stopRenderStream');
});
```

And use it like so to watch yahoo.com load and render, frame by frame:

```js
Nightmare()
  .on('renderStreamFrame', function(buffer) {
    // do something here with the image data, e.g. save to disk
  })
  .renderStream()
  .goto('http://yahoo.com')
  .stopRenderStream()
  .end()
  .then(function() {
    console.log('done');
  });
```

**Comment by rosshinkley** [comment]
@trusktr did @Mr0grog's suggestions work for you?

**Comment by trusktr** [comment]
@rosshinkley I haven't tried it yet. Seems like it will though. I'll re-open if I get around to it (or if anyone reading tries and it doesn't work, they can re-open too).
