### ISSUE TITLE
Expose interface to set chromium arguments

### ISSUE THREAD

**Issue by yotamlaufer** [segmentio/nightmare#594]
It will be really useful to set chromium arguments, allowing tweaking of the runtime.

https://github.com/electron/electron/blob/master/docs/api/app.md#appcommandlineappendargumentvalue

**Comment by yotamlaufer** [comment]
#Add #A

**Comment by yotamlaufer** [comment]
https://github.com/segmentio/nightmare/pull/595

**Comment by casesandberg** [comment]
Go ahead and try out the headless Chrome implementation in v3, it allows you to pass options in when instantiating a new Nightmare class! https://github.com/segmentio/nightmare/tree/v3.

I am going to close this, but feel free to re-open if it's still an issue.
