### ISSUE TITLE
Make version info available via API

### ISSUE THREAD

**Issue by Mr0grog** [segmentio/nightmare#599]
To help people with debugging and other issues, we should make the versions of:

- Nightmare itself
- Electron
- Chromium

available at runtime via the API. See also #597

**Comment by Mr0grog** [comment]
A quick note on this: getting the versions for Electron/Chromium requires running Electron, so this either needs to be an async call or it will be a potentially slow, blocking call (the first time; we can cache it after that). Any thoughts on which approach is better, @rosshinkley?

**Comment by rosshinkley** [comment]
Could the information be captured during the `app.on('ready')` handler and piped up as part of the response there, then attached to the Nightmare instance inside of the instance construction sugar?  That would negate the need for extra calls, and that uses a trip that's already being made, so we get version info for (almost) free.  Thoughts?

**Comment by rosshinkley** [comment]
Although... that would mean the version info is not immediately available like you might expect.  It'd only be available after Nightmare has entered a ready state, like it would prior to executing a chain.  I was trying to get away with _not_ having a `.version()` (or similar) method, but now I'm not sure that's particularly feasible.

**Comment by Mr0grog** [comment]
Well, maybe the Electron/Chrome version stuff isn’t necessarily needed in API? We *could* just log it whenever starting Electron if people only need it informationally. Not quite as much utility there, but maybe enough.

**Comment by rosshinkley** [comment]
I think I still prefer exposing _some_ way of getting the versions programmatically, and I can't think of a good method for doing that without an explicit method that doesn't require side-effect-y stuff.

That said, adding a debug call for the versions on `ready` is probably worth doing and will cover most (probably an overwhelming majority) of cases.

**Comment by rosshinkley** [comment]
"Fixed" in 2.4.0, closing.
