### ISSUE TITLE
SlimerJS and TrifleJS support via engine option

### ISSUE THREAD

**Issue by changalberto** [segmentio/nightmare#60]
Any plans to add support for SlimerJS and TrifleJS? I believe it has similar implementation.

Would be nice to see an ``engine`` method as an option (defaults to phantomjs).

```javascript
var Nightmare = require('nightmare');
new Nightmare()
+  .engine('slimerjs')
  .goto('http://kayak.com')
  .evaluate(function () {
    return document.documentElement.innerHTML;
  }, function (res) {
    console.log(res);
  })
  .run();
```
Thoughts?

Thanks!

**Comment by sdesalas** [comment]
Let me know if you need a hand with TrifleJS, I'm development mode at the moment.

**Comment by reinpk** [comment]
thanks all, in v2 we decided to go a different direction towards depending on electron. may reconsider down the road.
