### ISSUE TITLE
Does the selector of nightmare support psuedo classes?

### ISSUE THREAD

**Issue by shri3k** [segmentio/nightmare#603]
Quick question. I'm not sure if this has been answered already before but I didn't find this in the docs or during my issue search but does nightmare support psuedo classes like `:first` or like [these](https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes) as it's selector?

**Comment by Mr0grog** [comment]
Generally, things are selected by running `document.querySelector()`, so pseudo-selectors are supported to the extent that Chrome supports that API.

Most of them are well supported. I’m not sure if they *all* are, though. I don’t think anyone has tested all of them, especially things like `:focus`, which might be supported differently depending on whether the window is visible on screen or hidden (PhantomJS has a long standing bug related to this particular issue: https://github.com/ariya/phantomjs/issues/10427).

**Comment by shri3k** [comment]
Ahh, that actually clarifies things quite a bit. Apparently `:first` [isn't supported](https://developer.mozilla.org/en-US/docs/Web/CSS/:first) and I happened to be testing only that. 😿  Found alternative to it by using `:first-child`. Thanks, @Mr0grog
