### ISSUE TITLE
Readme Yahoo example needs a `.catch()`

### ISSUE THREAD

**Issue by rosshinkley** [segmentio/nightmare#607]

**Comment by shesmu** [comment]
the missing catch wouldn't happen to cause a 'Cannot read property 'dock'' would it?

**Comment by Mr0grog** [comment]
@shesmu no, it doesn’t. Are you referring to #602, or are you seeing that error independently (and do you have a reproducible test case)? I can see, where that error is happening, but can’t see how the conditions that cause it would ever be true. I’d love to know if you have a way to make it reliably happen.

**Comment by rosshinkley** [comment]
Fixed in 2.4.0, closing.
