### ISSUE TITLE
.click() not working.

### ISSUE THREAD

**Issue by mingsterism** [segmentio/nightmare#610]
I've been trying the .click() method on various sites, but all seems to give errors. Appreciate some help. 

wikipedia.org
```
var Nightmare = require('nightmare');
var nightmare = Nightmare({ show: true })

nightmare
  .goto('https://www.wikipedia.org/')
  .type('#searchInput', 'nobelPrize')
  .wait(5000)
  .click(".central-featured-lang lang1")
  .end()
  .then(function(result) {
  	console.log(result);
  })
  .catch(function(err) {
  	console.dir(err);
  })
```
output debug
```
ming_o01 (master) nightmare1 $ DEBUG=nightmare node wikipediaSearch.js
  nightmare queueing action "goto" for https://www.wikipedia.org/ +0ms
  nightmare queueing action "type" +14ms
  nightmare queueing action "wait" +6ms
  nightmare queueing action "click" +1ms
  nightmare running +3ms
'Cannot read property \'dispatchEvent\' of null'
ming_o01 (master) nightmare1 $
``` 
It fails at 
` .click(".central-featured-lang lang1")`. I realize that `'Cannot read property \'dispatchEvent\' of null'` error only occurs when CSS selector is wrong. But I can't figure out what is the right one? Appreciate some help. 

yahoo.js
```
var Nightmare = require('nightmare');
var nightmare = Nightmare({ show: true })

nightmare
  .goto('http://yahoo.com')
  .type('input[id="uh-search-box"]', 'github nightmare')
  .wait('#main')
  .click('#uh-logo')
  .end()
  .then(function (result) {
    console.log(result)
  })
  .catch(function(err) {
    console.dir(err);
  });
```

output debug
```
ming_o01 (master) nightmare1 $ DEBUG=nightmare node yahoo.js
  nightmare queueing action "goto" for http://yahoo.com +0ms
  nightmare queueing action "type" +38ms
  nightmare queueing action "wait" +5ms
  nightmare queueing action "click" +1ms
  nightmare running +3ms
'Cannot read property \'blur\' of null'
ming_o01 (master) nightmare1 $
```

Typing in the search box works. Only  .click(). I pasted Source code below for reference. 
```
exports.click = function(selector, done) {
  debug('.click() on ' + selector);
  this.evaluate_now(function (selector) {
    document.activeElement.blur();
    var element = document.querySelector(selector);
    var event = document.createEvent('MouseEvent');
    event.initEvent('click', true, true);
    element.dispatchEvent(event);
  }, done, selector);
};
```

I tried the function in Chrome console and it works. Thanks very much for the advise.

**Comment by johndvorakHR** [comment]
+1

**Comment by yoz** [comment]
@mingsterism on wikipedia.org, the CSS selector doesn't find any elements. The space operator in selectors "a b" means "an element b with an element a ancestor". You might have intended
`.central-featured-lang,lang1`

In the Chrome console you can try `$$(mySelector)` to see what gets returned from a querySelectorAll.

I'm not sure what's going on with the yahoo.com example, because there is no #main that I can find on the page and it waits indefinitely, but if I remove that wait() call then I don't get the same error.

**Comment by mingsterism** [comment]
@yoz thanks for the advise. I followed your direction on the wikipedia selectors. Turns out, it was a (dot) i had to put in. `.central-featured-lang.lang1`. 
However, I still cant get the actual href element using CSS selectors. It gives me the entire line. I posted the question on stackoverflow as well. http://stackoverflow.com/questions/36928172/how-to-get-href-text-using-css-selectors 

For .wait(#main) on yahoo, I too had a hang. However, I tried a workaround and it worked. 

Below the whole wait function from actions.js
```
exports.wait = function () {
  var args = sliced(arguments);
  var done = args[args.length-1];
  if (args.length < 2) {
    debug('Not enough arguments for .wait()');
    return done();
  }

  var arg = args[0];
  if (typeof arg === 'number') {
    debug('.wait() for ' + arg + 'ms');
    if(arg < this.optionWaitTimeout){
      waitms(arg, done);
    } else {
      waitms(this.optionWaitTimeout, function(){
        done(new Error('.wait() timed out after '+this.optionWaitTimeout+'msec'));
      }.bind(this));
    }
  }
  else if (typeof arg === 'string') {
    debug('.wait() for ' + arg + ' element');
    waitelem(this, arg, done);
  }
  else if (typeof arg === 'function') {
    debug('.wait() for fn');
    args.unshift(this);
    waitfn.apply(this, args);
  }
  else {
    done();
  }
};
```

I took a method of the wait function and implemented that directly in my code instead and it worked for some reason. 
Added `exports` to implement in my code. Implement with `waitms(5000)`

```
exports.waitms = function(ms, done) {
  setTimeout(done, ms);
}
```
Maybe something for others to check into. 


In regards to the .click() issue, what actually happened was electron was redirecting yahoo to my country specific yahoo. Thus the selectors were wrong. I changed the selectors with my specific yahoo url  `'https://sg.yahoo.com/?p=us'` , and it worked.
