### ISSUE TITLE
How to add a file in a form?

### ISSUE THREAD

**Issue by kud** [segmentio/nightmare#611]
I've got a file input in a form, how to handle it?

**Comment by rosshinkley** [comment]
As far as I know, you can't, at least not yet.  #235 covers it, and I don't think the `debugger` method has been tried/made into a plugin.

**Comment by kud** [comment]
Thank you @rosshinkley.

**Comment by lukehorvat** [comment]
@kud Or you can use Nightmare v1.8.2, which does have file upload functionality, but uses PhantomJS instead of Electron. https://github.com/segmentio/nightmare/tree/1.8.2 😉

**Comment by kud** [comment]
Interesting. Thanks @lukehorvat

**Comment by rosshinkley** [comment]
I wrote a [plugin](https://www.npmjs.com/package/nightmare-upload) that should give you the same ability as 1.x to add files to a file input.  As that should solve this issue, I'm going to go ahead and close this issue.  If this is still a problem, feel free to reopen/open a new issue.
