### ISSUE TITLE
How to guess option value depending on term in select

### ISSUE THREAD

**Issue by kud** [segmentio/nightmare#618]
I've got a select like:

```markup
<select name="category">
    <option value="44">This is a sentence</option>
    <option value="33">Another words</option>
</select>
```

I'd like to get the option value from the string "This is a sentence". Do you know how to do that? I've tried to handle it via `evaluate` like

`return $('select[name="category"]:contains("This is a sentence")').val()`

It works but I don't know how to use the result after.

**Comment by rosshinkley** [comment]
Maybe I'm not grasping what you're asking, but it seems like `.evaluate()` might do what you want?

```js
nightmare
  .goto(someUrl)
  .evaluate(function(){
    return $('select[name="category"]:contains("This is a sentence")').val();
  })
  .then(function(value){
    console.log(value);
  })

**Comment by kud** [comment]
Kinda work but how to use nightmare in then function?

```
.evaluate(function(){
        return $('select[name="category"] option:contains("Voitures")').val()
      })
      .then(function(value){
        nightmare.select('#category', value)
      })
```

**Comment by rosshinkley** [comment]
A common pattern is to return a `then`able (like Nightmare) out of `.then()` and use `.then()` again in the chain.  For example:

```js
.evaluate(function(){
        return $('select[name="category"] option:contains("Voitures")').val()
      })
      .then(function(value){
        return nightmare.select('#category', value)
      })
      .then(function(){
        //value in #category will be selected...
      })
```

**Comment by kud** [comment]
This is perfect @rosshinkley. Thank you for your clear explanation and your time. I appreciate it. :)

**Comment by kud** [comment]
But it means: 

```
nightmare
      .viewport(1600, 768)
      .useragent('Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:49.0) Gecko/20100101 Firefox/49.0')
      .goto('https://www.leboncoin.fr/')
      .click('.loggedOut button')
      .wait('.popin-content-template_main')
      .insert('input[name="st_username"]', userData.email)
      .insert('input[name="st_passwd"]', userData.password)
      .click('.popin-content-template_main input[type="submit"]')
      .wait('.deposer a')
      .click('.deposer a')
      .select('#category', argv.category)
      .evaluate(function(){
        return $('select[name="category"] option:contains("Voitures")').val()
      })
      .then(function(value){
        return nightmare
          .select('#category', value)
          .check('#private_ad_id')
          .check('#rs')
          .insert('#subject', argv.title)
          .insert('#body', argv.content)
          .insert('input[name="price"]', argv.price)
          .check('input[name="phone_hidden"]')
          .end()
      })
```

that I've got to put everything in the `then` function? Because for instance `.check()` doesn't exist if I use it just after:

```
.then(function(value){
        return nightmare.select('#category', value)
      })
```

**Comment by kud** [comment]
In fact, `evaluate` is a promise-like?

**Comment by kud** [comment]
Plus,

```
.evaluate(function() {
        return $('select[name="category"] option:contains("' + argv.category + '")').val()
      })
```

doesn't work because apparently argv (from yargs) is not defined there. Should I create a new nightmare function and use evaluate_now maybe?

**Comment by kud** [comment]
Got it:

```
.evaluate(function(argv) {
        return $('select[name="category"] option:contains("' + argv.category + '")').val()
      }, argv)
```

However still asked: https://github.com/segmentio/nightmare/issues/618#issuecomment-216905454

**Comment by rosshinkley** [comment]
> that I've got to put everything in the then function? Because for instance .check() doesn't exist if I use it just after:

This gets into some confusing territory: `.then()` returns a native Promise, not a Nightmare instance.  If I'm understanding properly, this:

```js
nightmare
  .goto(someUrl)
  .then(function(){
    //do something
  })
  .click(someSelector)
  ....
```
... won't work as `.then()` turns the downstream chain into a native Promise chain.  So to answer your question, yes, I think everything has to be in the `.then()`.

> doesn't work because apparently argv (from yargs) is not defined there. Should I create a new nightmare function and use evaluate_now maybe?

Looks like you got this figured out with passing arguments to `.evaluate()`.

**Comment by kud** [comment]
Hahaha yeah. :D thank you. I understand more how it works now. :)
