### ISSUE TITLE
package should specify engine

### ISSUE THREAD

**Issue by rosshinkley** [segmentio/nightmare#621]
Outgrowth of #620.

**Comment by Mr0grog** [comment]
Should probably document it clearly in the README, too. To be honest, I’m not really sure what the compatibility requirement *is.* (I was under the impression, based on some comment in an issue or PR I can’t find a little while back, that it was Node 4+ now.)

**Comment by rosshinkley** [comment]
> Should probably document it clearly in the README, too. 

👍 

> To be honest, I’m not really sure what the compatibility requirement is.

We talked about it (I can't find the reference offhand either), and I believe we came to the consensus that Node 4+ was "official", but I _think_ everything will still work using 0.12.x with `--harmony`.

**Comment by rosshinkley** [comment]
> Node 4+ was "official", but I think everything will still work using 0.12.x with --harmony.

Scratch that.  Template strings don't work with <4.

**Comment by Mr0grog** [comment]
> Template strings don't work with <4.

Worth noting that doesn't matter for node compatibility (for now), since we only use template strings on the Electron side, which does support them in the version we require in `package.json`.

**Comment by rosshinkley** [comment]
... won't calls to [`.call()`](https://github.com/segmentio/nightmare/blob/master/lib/ipc.js#L72) fail, specifically when the emitter [gets a result](https://github.com/segmentio/nightmare/blob/master/lib/ipc.js#L87)?

**Comment by Mr0grog** [comment]
d'oh, forgot `ipc.js` also runs in the user process! (Was only looking at `nightmare.js`.)

**Comment by rosshinkley** [comment]
Totally fine!  :)  Just making sure my read of things was okay.

**Comment by Mr0grog** [comment]
(Do we need to change `ipc.js`?)

**Comment by rosshinkley** [comment]
> (Do we need to change ipc.js?)

I don't think so.  My stance is that it's _fairly_ reasonable to say that 4.x is a good minimum requirement.  What do you think?

**Comment by Mr0grog** [comment]
I am cool with that—especially since I was the one who thought the minimum had been updated to 4.x in the first place :P  (Also since 6.x will soon be the new long-term-support version of node)

**Comment by rosshinkley** [comment]
I'm almost 100% sure we had this conversation (or a very close approximation), but it's beyond my searching ability.  Now it's official in #653! ;)
