### ISSUE TITLE
Question: Using nightmare in promise form for intermediate checks

### ISSUE THREAD

**Issue by chrisgeo** [segmentio/nightmare#629]
Hey Nightmare Team,

I still love the work you've been producing, but I've run into a few snags. With the old generator form, I used to be able to having intermediate steps in my promise or function that would check for specific conditions before failing or continuing. 

With the new promise format, I don't see a way I can do this, or perhaps I'm missing something.

An example might be:

- Go to a login page
- Check for a selector
- Type username and password
- Login fails
- Check for failed message, throw error.
- Take a screenshot to send with the error for debugging purposes

In the case of the new promise-based nightmare, the failure is just a timeout since I have yet to figure out a way to have an intermediary step.

Any advice on how I might be able to achieve this?

**Comment by Mr0grog** [comment]
First off, you should still be able to write the exact same code with generators. Nothing’s changed there so far as I’m aware. (The generator support was always based on the promise-style API; I think the change in messaging was just a desire not to push learning both Nightmare *and* async generators on a new user.)

I’m imagining you might have had code like…

```js
function doTheThing*() {
  var showingFailedMessage = yield nightmare
    .goto('loginpage.html')
    .wait('selector')
    .type('text-field-selector', 'login-info')
    .exists('failed-message-selector');
  if (showingFailedMessage) {
    var image yield nightmare.screenshot();
    saveScreenshot(); // <-- this is just made up; it's whatever you would do with the screenshot
    throw new Error('login failed!');
  }
}
```

If that's way off, drop an actual example in here so we can see what you're trying to translate to promises.

A promise version of the above might be:

```js
function doTheThing() {
  return nightmare
    .goto('loginpage.html')
    .wait('selector')
    .type('text-field-selector', 'login-info')
    .exists('failed-message-selector')
    .then(function(showingFailedMessage) {
      if (showingFailedMessage) {
        var image yield nightmare.screenshot();
        saveScreenshot(); // <-- this is just made up; it's whatever you would do with the screenshot
        throw new Error('login failed!');
      }
    });
  }
```

In the above, `doTheThing()` would return a promise that resolves if the login worked and rejects if the login failed.

**Comment by chrisgeo** [comment]
Thanks @Mr0grog. I'll go and give it a try again. Thanks for your help.

**Comment by chrisgeo** [comment]
Hey @Mr0grog,

Sorry for opening this up again, but looking at the promise example, I'm not positive generators would work inside of it.

Here's an example based on your suggestion:

```javascript
const Nightmare = require('nightmare');
const nightmare = Nightmare({
  show: true
});

function getCnn(resolve, reject) {
  return nightmare
      .goto('http://www.cnn.com')
      .wait(400)
      // selector that fails on purpose.
      .exists('.some-random-selector')
      // simple equivalent of what I'm attempting.
      // let c  = () => function* testTwo() { yield *function* test() { yield 1; }(); }().next();
      // this might only be possible with VO.
      .then((failed) => {
        console.log(failed);

        // definitely won't work in promise form
        // const image = yield nightmare.screenshot();

        // only way to get yield to work, sort of in a promise
        // still fails
        // const image = yield *nightmare.screenshot();

        // fun way of trying generators, but doesn't work either.
        // const image = function* getImage() {
        //  yield *nightmare.screenshot();
        // }().next();

        //console.log(image); // never printed.
      });
}

getCnn();
nightmare.end();
```

It's possible for my use-case that using the generator form may be better altogether because I have other actions that need to occur after `.then`, an example building off the original, 

- Login fails, fail and take screenshot
- Login success, go to the next page
  - do a few actions
  - take a screenshot.

**Comment by Mr0grog** [comment]
Oh no, I think you might have some crossed wires here about how promises and generators work, probably caused by a **horrible** copy/paste error in my initial reply. So sorry about that :(

While you *can* mix the promise-style `then()` API with generators, you really don’t want to. (You’d still need `vo`; setting it up right would be complicated, etc). When I wrote:

```js
.then(function(showingFailedMessage) {
  if (showingFailedMessage) {
    var image yield nightmare.screenshot();
    saveScreenshot(); // <-- this is just made up; it's whatever you would do with the screenshot
    throw new Error('login failed!');
  }
});
```

That was a copy/paste error from the window I’d written the code in. It’s completely wrong and wouldn’t ever work *at all.* That was supposed to be:

```js
.then(function(showingFailedMessage) {
  if (showingFailedMessage) {
    return nightmare.screenshot().then(function(imageBuffer) {
      saveScreenshot(); // <-- this is just made up; it's whatever you would do with the screenshot
      throw new Error('login failed!');
    }
  }
});
```

**Comment by Mr0grog** [comment]
> It's possible for my use-case that using the generator form may be better altogether because I have other actions that need to occur after .then, an example building off the original

So… this is equally do-able in generator form or in promise-form. The main difference is in the way you branch. Let’s say we fixed my original example with the code from above (sorry again):

```js
function doTheThing() {
  return nightmare
    .goto('loginpage.html')
    .wait('selector')
    .type('text-field-selector', 'login-info')
    .exists('failed-message-selector')
    .then(function(showingFailedMessage) {
      if (showingFailedMessage) {
        return nightmare.screenshot().then(function(imageBuffer) {
          saveScreenshot(); // <-- this is just made up; it's whatever you would do with the screenshot
          throw new Error('login failed!');
        }
      }
    });
  }
```

The easiest way to use that would be:

```js
doTheThing().then(function() {
  return nightmare
    .someActionAfterLoggingIn()
    .anotherActionAfterLoggingIn()
    .youGetTheIdea()
    .screenshot()
    .end()
    .then(function(imageBuffer) {
      fs.writeFileSync('success-screenshot.png', imageBuffer);
      console.log('Success!');
    })
}).catch(function() {
  // make sure to end nightmare in case something went wrong along the way
  return nightmare.end();
});
```

It might also just be simpler to:

```js
// this is just a quick utility that makes screenshotting a little simpler
function saveScreenshotAndEnd(savePath) {
  return nightmare.screenshot().end().then(function(imageBuffer) {
    fs.writeFileSync(savePath, imageBuffer);
  });
}

nightmare
  .goto('loginpage.html')
  .type('text-field-selector', 'login-info')
  .click('login-button-selector')
  .wait('selector-that-indicates-you-are-logged-in')
  .someActionAfterLoggingIn()
  .anotherActionAfterLoggingIn()
  .youGetTheIdea()
  .then(function() {
    console.log('Success!');
    saveScreenshotAndEnd('success.png');
  })
  .catch(function(error) {
    console.error('Something broke:', error);
    saveScreenshotAndEnd('failure.png');
  });
```

There are *a lot* of ways to formulate this. What works best will depend on exactly what it is you want to do.
