### ISSUE TITLE
Got error when install

### ISSUE THREAD

**Issue by Muyv** [segmentio/nightmare#631]
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "nightmare"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! electron-prebuilt@0.37.8 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-prebuilt@0.37.8 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.

**Comment by Mr0grog** [comment]
@Muyv This is an issue in `electron-prebuilt` and I believe it’s already been filed: https://github.com/electron-userland/electron-prebuilt/issues/125 (but you should make sure that bug matches what you’re experiencing)

**Comment by rosshinkley** [comment]
@Muyv Is this resolved?

**Comment by Muyv** [comment]
@rosshinkley Nope, but this issue is WINDOWS-only, I tried to do it in CentOS, eveything goes well.

**Comment by Muyv** [comment]
@Mr0grog Thx, It seems a compatibility problem of `electron-prebuilt`. In fact I've already used another Phantomjs bridge to realize my requirements.
