### ISSUE TITLE
Upgrade electron

### ISSUE THREAD

**Issue by lamecoder** [segmentio/nightmare#632]
Electron have released version 1.0, nightmare needs to upgrade electon-prebuilt. 
http://electron.atom.io/blog/2016/05/11/electron-1-0

**Comment by rosshinkley** [comment]
#644 needs to be pulled in first at a minimum.

**Comment by LinusU** [comment]
#644 is merged, what is next for making this happening?

**Comment by LinusU** [comment]
Tried it locally with Electron 1.0.2 and seems to be working great. All tests are passing and I was able to use our internal app as before.

I'm affected by electron/electron#5444 so it would be really nice to be able to upgrade to version 1.0.2...

**Comment by rosshinkley** [comment]
@LinusU It works fine with 1.0.x and (memory serving) 1.1.x, but some of the tests involving `webSecurity` break with 1.2.x.  I believe it's symptoms of electron/electron#5712, which have been fixed but as yet unreleased (at least with `electron-prebuilt`).  

I'm comfortable upgrading to a non-breaking version in the meantime, barring protest.  Thoughts?

**Comment by albinekb** [comment]
`1.2.1` is released from electron, just need to wait for `electron-prebuilt` to upgrade

**Comment by albinekb** [comment]
`1.2.1` is now released in `electron-prebuilt` https://www.npmjs.com/package/electron-prebuilt

**Comment by albinekb** [comment]
ping @rosshinkley @matthewmueller

**Comment by rosshinkley** [comment]
@albinekb This will get pulled into the next version. :)
