### ISSUE TITLE
Override the failure output for .wait()

### ISSUE THREAD

**Issue by atomless** [segmentio/nightmare#638]
It would be really nice if there were a way to pass in the failure message you'd like logged when a wait call times out. So instead of just seeing the default `failed with ".wait() timed out after 30000msec"` you would be able to call wait like so 
```Javascript 
nightmare.wait('selector', 'Failed to find expected element.');
```

**Comment by Mr0grog** [comment]
`wait` could definitely have a better message, but I don’t think user customization is a good idea. Are you looking for better output in unit/functional tests? If so, I think is is much better handled (and probably already supported) by whatever assertion/expectation library you’re using.

**Comment by LinusU** [comment]
I'm also 👎 on being able to customise the message, if you are implementing a library and want to provide useful errors to your consumers, use `try`/`catch`.

e.g.

```js
async function () {
  try {
    await nightmare.wait('selector')
  } catch (err) {
    throw new Error('My error description')
  }
}
```

**Comment by Mr0grog** [comment]
@atomless since you’re using Ava (I think?), you could do something like:

```js
test('shows some element', t => {
  t.plan(1);
  t.notThrows(nightmare.wait('selector'), 'it never showed up');
});
```

**Comment by atomless** [comment]
@Mr0grog nice idea! Thanks.
