### ISSUE TITLE
Get Nightmare.click() to work with React?

### ISSUE THREAD

**Issue by timotgl** [segmentio/nightmare#639]
Is there any way to make .click() work in a React app? Calling it with the selector string that yields the element on which the `onClick` handler is defined doesn't seem to work.

All the sources I found recommend using the React test utils to simulate a click, but of course production websites don't expose these. I'm considering to monkey-patch the react test utils into the page (insert script tag or something) but that seems a bit obscure.

I guess the question extends to other page interactions like .type(), do these work with React apps?

I tried a workaround suggested in https://github.com/facebook/react/issues/3249

```
var event = document.createEvent("HTMLEvents");
event.initEvent("click", true, true);
var target = $('.buttons .login')[0];
target.dispatchEvent(event);
```

But this doesn't even work in the Chrome console.

**Comment by Mr0grog** [comment]
I _suspect_ this is the same as the notes about whether `click` should be using `sendInputEvent` in #619. Does writing a plugin that clicks by using `sendInputEvent` work for you?

**Comment by Mr0grog** [comment]
If it helps to test, here’s a quickie example plugin:

```js
Nightmare.action('realClick', function(name, options, parent, win, renderer, done) {
  parent.respondTo('realClick', function(x, y, done) {
    win.webContents.sendInputEvent({
      type: 'mousedown',
      x: x,
      y: y,
      clickCount: 1
    });
    win.webContents.sendInputEvent({
      type: 'mouseup',
      x: x,
      y: y
    });
    setTimeout(function() { done(); }, 50);
  });
  done();
}, function(selector, done) {
  var child = this.child;
  this.evaluate_now(function(selector) {
    var bounds =  document.querySelector(selector).getBoundingClientRect();
    return {
      left: bounds.left,
      top: bounds.top,
      width: bounds.width,
      height: bounds.height
    };
  }, function(error, bounds) {
    if (error) return done(error);
    var x = bounds.left + bounds.width / 2;
    var y = bounds.top + bounds.height / 2;
    child.call('realClick', x, y, done);
  }, selector);

});
```

Use it like so:

```js
Nightmare({show: true})
  .goto('about:blank')
  // this is just logging the events so you can see that they happened
  .on('console', function(type) { console.log([].slice.call(arguments, 1)); })
  .evaluate(function() {
    function logEvent(event) { console.log(`EVENT: "${event.type}"`); }
    document.body.addEventListener('mousedown', logEvent);
    document.body.addEventListener('mouseup', logEvent);
    document.body.addEventListener('click', logEvent);
  })
  // actually trigger the events
  .realClick('body')
  .end()
  .then(function() {
    console.log('ok');
  })
  .catch(function(error) {
    console.error('UHOH:', error);
  });
```

**Comment by timotgl** [comment]
@Mr0grog your example works perfectly, but using `realClick` on a React button still doesn't work for some reason. I either get 'parent doesn't respond to .realClick' or just nothing happens. But thank you for the investigation nonetheless 👍

**Comment by Mr0grog** [comment]
> I either get 'parent doesn't respond to .realClick' or just nothing happens.

Where do you see that error? Nothing in Nightmare should generate that message and nothing outside Nightmare should have any clue about `realClick`, so it doesn’t sound like it’s working perfectly at all! I wouldn’t conclude it’s not working for React yet until we know it’s actually working ;)

Do you have a full test case you can post as a [gist](https://gist.github.com)?

**Comment by timotgl** [comment]
Turns out that I was using an incorrect selector string with .click(). It needs to be the exact same DOM node where the corresponding React component has the onClick handler. I tried with a wrapping element and assumed it would be propagated. The normal .click() does work in fact. Sorry for taking up your time :/

**Comment by samavamsi1** [comment]
how to select the react dropdown which is in hidden state type="hidden" .
