### ISSUE TITLE
Nightmare does not save updated HTML file when using "HTMLOnly" option

### ISSUE THREAD

**Issue by nick2012** [segmentio/nightmare#654]
Basically, if you click, scroll, etc so that the content of the page gets extended via JavaScript, when using the save page option with `HTMLOnly` option, Nightmare does not save the latest HTML, but the one that was loaded at the beginning. However, it saves the latest version when using `HTMLComplete`.

**Comment by rosshinkley** [comment]
It looks like [you might already have an answer](https://github.com/electron/electron/issues/5635).  I think (someone please correct me if I'm wrong) Chromium uses the HTML from `DOMReady` for fulfilling that action.

As an example, you could write something to fulfill this yourself using `.evaluate()` on the document's HTML.  Something like:

```js
var nightmare = require('nightmare')(),
  fs = require('fs'),
  path = require('path');

nightmare.goto('http://example.com')
  .evaluate(() => document.documentElement.innerHTML)
  .then((html) => {
    fs.writeFileSync(path.join(__dirname, 'output.html'), html);
    return nightmare.end();
  })
  .then(() => console.log('done'));
```

**Comment by nick2012** [comment]
Its ok like this. Thank you.
