### ISSUE TITLE
How to get status code?

### ISSUE THREAD

**Issue by kuyoonjo** [segmentio/nightmare#656]
The HTTP status code (e.g. 200, 404, 500)

**Comment by rosshinkley** [comment]
The resolution of [`.goto()`](https://github.com/segmentio/nightmare#gotourl-headers) has that information.  For example:

```js
var nightmare = require('nightmare')();
nightmare.goto('http://example.com')
  .then((gotoResult) => {
    console.log(gotoResult.code); //prints out the HTTP status for the request
  })
```

**Comment by kuyoonjo** [comment]
Thank you Ross, but it does not work.


On May 22, 2016, at 1:38 PM, Ross Hinkley <notifications@github.com<mailto:notifications@github.com>> wrote:


The resolution of .goto()<https://github.com/segmentio/nightmare#gotourl-headers> has that information. For example:

var nightmare = require('nightmare')();
nightmare.goto('http://example.com')
  .then((gotoResult) => {
    console.log(gotoResult.code); //prints out the HTTP status for the request
  })

**Comment by rosshinkley** [comment]
What does not work?  How is it failing?

**Comment by kuyoonjo** [comment]
Oops, it works now. Just by updating nightmare.
Thank you very much Ross.

**Comment by kuyoonjo** [comment]
Hi Ross,

Thank you very much for your previous help. One more question. How to force kill the electron.
my code:
setTimeout(() => {
nightmare.end(_ => {}) // it does not exit immediately.
reject('Promise timed out after ' + timeout + ' ms')
}, timeout)

Regards,
Yu Chen


On May 22, 2016, at 1:50 PM, Ross Hinkley <notifications@github.com<mailto:notifications@github.com>> wrote:


What does not work? How is it failing?

**Comment by rosshinkley** [comment]
@kuyoonjo Be sure you're calling `.then()` after `.end()`.  That will run the queued actions (if any) and end Nightmare gracefully.

**Comment by rosshinkley** [comment]
@kuyoonjo also, if you have a more complete example, I'd like to see it.  I might be able to help more that way.

**Comment by kuyoonjo** [comment]
Thank you Ross, You are genius. At moment, everything is OK.
BTW, this is my Repo using nightmare.js https://github.com/kuyoonjo/google-auto-oauth2

On May 22, 2016, at 4:50 PM, Ross Hinkley <notifications@github.com<mailto:notifications@github.com>> wrote:


@kuyoonjo<https://github.com/kuyoonjo> also, if you have a more complete example, I'd like to see it. I might be able to help more that way.

**Comment by rosshinkley** [comment]
Awesome.  Closing this as I think it's resolved.  If you have any more problems, reopen/open a new issue.

**Comment by kuyoonjo** [comment]
^^ Yes. Really helpful. Thank you again.

On May 22, 2016, at 5:13 PM, Ross Hinkley <notifications@github.com<mailto:notifications@github.com>> wrote:


Awesome. Closing this as I think it's resolved. If you have any more problems, reopen/open a new issue.
