### ISSUE TITLE
Click based on extracted data

### ISSUE THREAD

**Issue by TechplexEngineer** [segmentio/nightmare#662]
Is there a way to make page actions based on extracted data? I'm interacting with an asp.net webforms application so after i load the page and perform the search, I have to use that Nightmare instance to do all of the remaining scraping as none of the "links" are true urls they are javascript ajax calls which update portions of the page.

The only way I can find to operate on scraped data from .evaluate is after an end() call which just won't work.

Is it possible to click or perform other actions based on data returned from an .evaluate() call?

**Comment by rosshinkley** [comment]
Sure!  The `.then()` function will have as its arguments the results of the previous method:

```js
nightmare
  .goto('http://example.com')
  .evaluate(() => {
    return document.querySelector('#my_awesome_thing').innerHTML;
  })
  .then((awesomeThingHtml) => {
    //do something with the HTML value
  })
  .then(() => nightmare.end());
```

As another example, you may want to have a look at `nightmare-example`'s ["Running Multiple Steps" example](https://github.com/rosshinkley/nightmare-examples/blob/master/docs/beginner/promises.md#running-multiple-steps).

**Comment by TechplexEngineer** [comment]
Perfect! I didn't realize there was an examples repo!
