### ISSUE TITLE
could not make the proxy work

### ISSUE THREAD

**Issue by mikkokotila** [segmentio/nightmare#665]
Is there a code example where the proxy, and proxyAuth options are working. I spent a few hours trying to get it work, but could not. I tried maybe 100 different variations of the syntax as the documentation is not really clear about this, and about half did not return any errors, the remaining code ran fine, but the IP did not change to the one set in the proxy settings. After every attempt I checked the log files on the server, to confirm if requests came in and if the IP was changed. 

Here is where I was left (I've replaced my test domain with google.com below):

    var Nightmare = require('nightmare');

    var testbot = new Nightmare({
   	    switches: {
	    proxy: 'http://1.proxy.com:80', 
	    proxyType: 'http', 
	    proxyAuth : 'user:password'
    }})
    testbot
      .goto('http://google.com')
      .wait()
      .run(function(err, nightmare) {
       if (err) return console.log(err);
      console.log('Done!');
      process.exit()
      });

**Comment by Mr0grog** [comment]
I don’t think any of those are actually valid switches (you can see the whole list at http://peter.sh/experiments/chromium-command-line-switches). I think the switch you want is `proxy-server`:

```js
var Nightmare = require('nightmare');

var testbot = new Nightmare({
  switches: {
    'proxy-server': 'http://1.proxy.com:80'
  }
});
```

I don’t know if you can set the auth info in the URL (e.g. `http://user:pass@1.proxy.com:80`) or if you would need to use the `authentication()` action, e.g:

```js
Nightmare({
  switches: { 'proxy-server': 'http://1.proxy.com:80' }
})
.authentication('user', 'password')
.goto('http://google.com')
.doSomething()
.run(function (error, result) { ... });
```

Alternatively, you could write a plugin that uses the `setProxy` method on Electron’s `session` object, as documented here: http://electron.atom.io/docs/api/session/#sessetproxyconfig-callback

**Comment by mikkokotila** [comment]
Thank you. 

I had tried that as well. I tried again and neither of the examples you change anything i.e. I could change the switch (proxy-server) to lkjlkj-weioruweoriu and the code still runs the rest of the program. It seems to me that for some reason the switches part is totally ignored at the moment, because it can be changed to anything without any effect on the rest of code. Thank you for the plugin tip, though it would be great if this could work as in the examples you had provided given how amazing Nightmare otherwise is!

**Comment by rosshinkley** [comment]
> I had tried that as well. I tried again and neither of the examples you change anything i.e. I could change the switch (proxy-server) to lkjlkj-weioruweoriu and the code still runs the rest of the program.

Hm, setting `proxy-sever` to a bogus URL (or even a malformed URL) causes provisional load and load failures, at least with 2.5.0.  Out of curiosity, what version of Nightmare are you running?

> I don’t know if you can set the auth info in the URL (e.g. http://user:pass@1.proxy.com:80) or if you would need to use the authentication() action

I would be _very_ curious to know the answer to this.

**Comment by xmen4u** [comment]
@rosshinkley : you need to use authentication() with setting 'proxy-server' (with out user + password)

**Comment by mikkokotila** [comment]
@xmen4u can you clarify, is this what should work, or something that you have actually effectively worked with? In case it's the latter, can you please provide exact code example and I will test it also.

I got the proxy authentication to work on Electron, but would prefer to use Nightmare if possible. At the moment, given that there are no specific detailed answers to this issue, unless someone provides a working code example, my suggestion is to assume that proxy authentication does not work.

**Comment by Mr0grog** [comment]
This works just fine for me:

```js
Nightmare({
  switches: {
    'proxy-server': '192.92.205.132:80'
  }
})
  .goto('http://whatismyip.com')
  .evaluate(function(){ return document.querySelector('.ip').textContent; })
  .end()
  .then(ip => console.log(ip))
  .catch(error => console.error('oops', error));
```

Granted, that proxy does not require auth, but it is clearly proxying.

**Comment by xmen4u** [comment]
@mikkokotila:

let nightmare = Nightmare({
      switches: {
        'proxy-server': proxy,
        'ignore-certificate-errors': true
      }
    });
   
    nightmare
    .authentication('user','pwd')
    .goto('http://www.cnn.com') 

Works well. Changing the proxy during run-time is an issue i couldn't figure out how.

**Comment by agrberg** [comment]
Thanks @xmen4u for the answer and @mikkokotila for already posting what I needed help with. I've added this information to the Read me for others to find more easily in PR #687.

**Comment by rosshinkley** [comment]
With #687 being merged in, I'm going to consider this issue resolved.
