### ISSUE TITLE
Skip the tests when writing new tests?

### ISSUE THREAD

**Issue by brotzky** [segmentio/nightmare#668]
Hi,

How does one skip all the previous tests when writing a new test? Currently I have about 20 nightmare tests that take about 2000ms each. Whenever I save my file they have to rerun from the beginning. Is there some sort of flag or something that will skip the previous tests and only run the new one? Something of that sort. 

Thanks

**Comment by rosshinkley** [comment]
You can use an [exclusive test](https://mochajs.org/#exclusive-tests) - eg, `describe.only` or `it.only`.

If you're using `mocha-generators`, there is a [known bug](https://github.com/vdemedes/mocha-generators/issues/2) with `it.only`.  There's a [PR](https://github.com/vdemedes/mocha-generators/pull/4) to fix it that you could pull down and link to, if you were so inclined.  (`describe.only` works fine with `mocha-generators`, for what it's worth.)

**Comment by brotzky** [comment]
Thank you, I will try it out.

**Comment by rosshinkley** [comment]
Considering this issue resolved.  If you're still having problems with `.only()`, feel free to reopen/open a new issue.

**Comment by brotzky** [comment]
Sorry for the late response. The issue has been resolved once we upgraded some npm deps. Thanks for the reply/support!
