### ISSUE TITLE
Problem with .type() and accents

### ISSUE THREAD

**Issue by bob6664569** [segmentio/nightmare#671]
`nightmare.type('#password', 'aJk3é;KDja2')` only types `aJk3;KDja2` skipping the `é`.

**Comment by Hesiode** [comment]
idem here, problem with accent.

**Comment by bob6664569** [comment]
It seems that the characters must be sent as utf-8 combinations tu sendInputEvent method of Electron to avoid the limitations of the Accelerator's API (see Issue #549). Maybe it could be automatically added.

**Comment by warka0** [comment]
Hi !
Same problem here too :)

**Comment by casesandberg** [comment]
Go ahead and try out the headless Chrome implementation in v3, it fixes this issue! https://github.com/segmentio/nightmare/tree/v3.

I am going to close this, but feel free to re-open if it's still an issue.
