### ISSUE TITLE
.goto() to same url is a no-op

### ISSUE THREAD

**Issue by coyotte508** [segmentio/nightmare#676]
Sample code:

``` js
const Nightmare = require('nightmare');
const nightmare = Nightmare({
  show: true
});

nightmare
  .goto("http://bash.org/?random")
  .then(() => {}); /* Why do I need to do .then() to make things show? */

setInterval(() => {
    nightmare.goto("http://bash.org/?random").then(() => {
        console.log("Went to page");
    });
}, 5000);
```

Expected behavior: the page refreshes every 5000 ms.
Observed behavior: the page doesn't refresh (but the logged messages still show).

I'm aware that `refresh()` would work in this instance but sometimes it's not known whether the page we want to get the latest data from is already the current page. And such information is hard to get as there's no easy way to directly get the current url.

Imo, there should be one of the following:
- Doc of `goto` specifies that nothing happens if the url given is already the current page
- Behavior of `goto` changed to correctly reload the page if url is the same
- Possibly add an option to the `goto` command.to specify the behavior

**Comment by coyotte508** [comment]
A hack to achieve the desired behavior at the moment is doing ```url = `${baseUrl}#${counter++}```` (as the correct way to achieve the behavior is much too verbose).

**Comment by rosshinkley** [comment]
> Observed behavior: the page doesn't refresh (but the logged messages still show).

When the URLs match, you're right - [nothing happens](https://github.com/segmentio/nightmare/blob/master/lib/runner.js#L171-L172).

> I'm aware that refresh() would work in this instance but sometimes it's not known whether the page we want to get the latest data from is already the current page.

I'm not sure I follow - can you elaborate?

> And such information is hard to get as there's no easy way to directly get the current url.

True, there's no `.url()` method or something similar.  Extracting the information should be reasonably straightforward, though:

```js
nightmare
  .goto('http://example.com')
  .action()
  .anotherAction()
  .evaluate(() => window.location.toString())
  .then((location) => console.log(location))
```

> Doc of goto specifies that nothing happens if the url given is already the current page

That's a good idea.  As mentioned, that's how it's set up.  (I'm sure there was/is a reason, although I can't recall off the top of my head.)

**Comment by coyotte508** [comment]
Extracting the information is straightforward, but chaining is not.

Instead of having:

```
nightmare
   .goto(page)
   .doStuff(); //<- can be .type, .then or whatever
```

If not using the hack (page + "#..."), the code becomes:

```
nightmare
    .evaluate( () => window.location.toString() )
    .then((location) => {
        if (location == page) {
            return nightmare.refresh().then(); 
       } else {
           return nightmare.goto(page).then(); // <- without then() nightmare doesn't move
       }
    }, (error) => {
        /* In case there's no page to do evaluate() in */
       return nightmare.goto(page).then();
    })/* <- can't do .type() or whatever, have to use .then() here */;
```

**Comment by casesandberg** [comment]
It doesn't look like there has been any progress on this issue lately. I am going to go ahead and close it, but feel free to open it back up if anyone wants to take a stab at a PR.
