### ISSUE TITLE
No (documented) way to clear all cookies

### ISSUE THREAD

**Issue by coyotte508** [segmentio/nightmare#678]
`nightmare.cookies.clear()` only clears cookies for the current website.

It'd be handy to be able to clear all cookies, so you know you start with a fresh start no matter what tests you ran with the electron browser before.

My precise use case is I want to clear all cookies after payment, and the payment processor & store both have different domains obviously so I have to make a bit of extra code to really clear all cookies.

In any case, it's natural to assume being able to control the electron browser like that.

**Comment by albinekb** [comment]
```
const uuid = require('uuid')
const Nightmare = require('nightmare')

const nightmare = Nightmare({ webPreferences: { partition: uuid.v4() })

```

If you use a different partition each time you'll be sure that you get a "clean" browser, as the default is a persistent partition.

**Comment by rosshinkley** [comment]
Also worth pointing out: there is an API for [clearing data](https://github.com/electron/electron/blob/master/docs/api/session.md#sesclearstoragedataoptions-callback) exposed by Electron, but the method isn't directly exposed in Nightmare.  

You could use `.action()`, but I think `webSession.clearStorageData()` should probably be core.  Thoughts?
