### ISSUE TITLE
How to disable '_blank' ?

### ISSUE THREAD

**Issue by rluisr** [segmentio/nightmare#679]
I want to download CSV with Nightmare and [Nightmare-download-manager](https://github.com/rosshinkley/nightmare-download-manager).

Target site generated new window when use '.click' for download.
`<input confirm="Download CSV. \n Is it ok ?" onclick="window.open('/customers/apply/inbox.csv?', '_blank');" style="float:right;margin-right:16px;_margin-right:8px;" type="button" value="Download CSV" />`
`.click('input[value=Download CSV]')`
Electron open new window but doesn't start download.
New windows's title is '_blank'.

How to rewrite '_blank' to '_self' or download or disable '_blank'

Thanks.

**Comment by albinekb** [comment]
I would just return the window.open url (`/customers/apply/inbox.csv?`) from an evaluator and then use something like https://github.com/sindresorhus/got to download the file separately

**Comment by rosshinkley** [comment]
There are two different questions here: one, can the download plugin be applied to other windows; and two, if the target of the click event can be changed.

Answering the first: Nightmare will not handle popup windows by default.  I wrote a prototype [plugin](https://github.com/rosshinkley/nightmare-window-manager) to show how it could be handled, but your example has the added complexity of trying to mix another plugin in with window management.  Under the current incarnation of Nightmare, that would be difficult to accomplish.  Native window management is on the list for the next major revision (see #593).

As for the second: I'm not sure, but I doubt it.  If the input has an `onclick` defined specifically, could you use `.evaluate()` to point the target of the action to `_self`?  Something like: 

```js
nightmare
  // .... actions setting up your conditions ... 
  .evaluate(() => {
    document.querySelector('input[value=Download CSV]').onclick = 
      () => window.open('/customers/apply/inbox.csv?', '_self');
  })
  .click('input[value=Download CSV]')
  // ... other actions... 
```
... I _suspect_ this won't work, but it might be worth a shot.

**Comment by rosshinkley** [comment]
@rluisr Did you get this resolved?

**Comment by Siilwyn** [comment]
Had the same issue, overwriting the `onclick` or `target` solved it for me.

**Comment by rosshinkley** [comment]
Thanks, @Siilwyn.  Going to consider this resolved, closing.
