### ISSUE TITLE
TypeError: Cannot read property 'connected' of undefined

### ISSUE THREAD

**Issue by gjmveloso** [segmentio/nightmare#680]
Hi,

I've started playing around with Nightmare on **Windows** and I'm receiving the _TypeError: Cannot read property 'connected' of undefined_ error every time I try to run my basic code:

```javascript
var config = require("./settings.json");
var Nightmare = require("nightmare");
var browser = Nightmare({
    "waitTimeout": config.timeout * 1000
});
browser.goto(config.url);
if (browser.title() === config.loginTitle && browser.exists("input.login")) {
    doLogin(config.expectedTitle);
} else if (browser.title() === config.loginTitle) {
    console.log("Application Check Passed \u2713");       
} else {
    console.error("Unknown page was open: ${browser.title()}");
}
browser.end();
```

>TypeError: Cannot read property 'connected' of undefined
    at endInstance (C:\Code\test\node_modules\nightmare\lib\nightmare.js:178:20)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
[Finished in 0.256s]

Thoughts?

*Nightmare Version:* 2.5.1
*NodeJS Version:* 6.2.1
*Windows 7 x64*

**Comment by mrjj** [comment]
I've described the reason and fix here:
https://github.com/segmentio/nightmare/issues/682
Have a nice day!

**Comment by rosshinkley** [comment]
This is related to #682, but I also don't think your source will do what you intend.  Nightmare is asynchronous, queuing actions in a chain until `.then()`, `.run()` or `.end()` is called.  Your `if` statement will always run the `else` condition, and produce undesirable outputs.  From the hip, written to use `.then()`:

```js
var config = require("./settings.json");
var Nightmare = require("nightmare");
var browser = Nightmare({
    "waitTimeout": config.timeout * 1000
});
var title, exists;
browser.goto(config.url)
    .title()
    .then((t) => title = t)
    .then(() => browser.exists("input.login"))
    .then((e) => exists = e)
    .then(() => {
        if(title === config.loginTitle && exists) {
            doLogin(config.expectedTitle);
        } else if(title === config.loginTitle) {
            console.log("Application Check Passed \u2713");
        } else {
            console.error(`Unknown page was open: ${title}`);
        }
    })
    .then(() => browser.end())
    .then(() => console.log('done'));
```
... of course, this depends on what `doLogin()` does.  It might make sense to return a promise from `doLogin()` and return the result.

You could also use [`vo`](https://github.com/matthewmueller/vo) or [`co`](https://github.com/tj/co) to help with generators and then use `yield` to make your script look a little more synchronous.  Also totally from the hip, written to use `vo`:

```js
var config = require("./settings.json");
var Nightmare = require("nightmare");
var vo = require('vo');

var browser = Nightmare({
    "waitTimeout": config.timeout * 1000
});

vo(function*() {
    yield browser.goto(config.url);
    if(yield browser.title() === config.loginTitle && yield browser.exists("input.login")) {
        doLogin(config.expectedTitle);
    } else if yield browser.title() === config.loginTitle){
        console.log(`Application Check Passed \u2713`);
    } else {
        console.error(`Unknown page was open: ${yield browser.title()}`);
    }
})(() => {
    console.log('done');
});
```
Same caution as above, this also depends on what `doLogin` does.

**Comment by mrjj** [comment]
The root cause is no process was created due you are not actually connecting until you finalize your request;
This will work:

```
var config = require("./settings.json");
var Nightmare = require("nightmare");
var browser = Nightmare({
    "waitTimeout": config.timeout * 1000
});

browser.goto(config.url);

if (browser.title() === config.loginTitle && browser.exists("input.login")) {
    doLogin(config.expectedTitle);
} else if (browser.title() === config.loginTitle) {
    console.log("Application Check Passed \u2713");
} else {
    console.error("Unknown page was open: ${browser.title()}");
}
// -------- changed ---------
browser.end().then(
  function (val) {
    console.log('Success: ', val)
  },
  function (val) {
    console.error('Failure:', val)
  }
);
```

**Comment by gjmveloso** [comment]
Thanks for your help @mrjj and @rosshinkley - I'd completed forgot about the _asynchronous_ thing.

But I think I'm still doing something wrong :cry: 

Here is my complete code:

```javascript
var config = require("./settings.json");
var Nightmare = require("nightmare");
var browser = Nightmare({
    "show": true,
    "waitTimeout": config.timeout * 1000
});

browser
    .goto(config.app.url)
    .title()
    .evaluate(() => {
        return browser.title() === config.login.title;
    })
    .exists("input#submit")
    .then(() => console.log("Login Detected, trying to login using ${config.login.user}"))
    .then(doLogin, performCheck)
    .end()
    .then(result => {
        console.log(result);
        console.log("Application Check Passed \u2713");
    })
    .catch(err => {
        console.error(err);
    });

var doLogin = function() {
    return browser
        .type("input#userId", config.app.user)
        .type("input#pwd", config.app.pwd)
        .click("input#submit")
        .wait(() => {
            browser.title() === config.app.title;
        })
        .wait(() => {
            return !browser.visible(".loading");
        });
};

var performCheck = function() {
    return browser
        .title()
        .then(t => {
            t === config.app.title;
            console.warn("App detected, Login phase was skipped");
        }, () => console.error("Unknown page was open: ${t}"))
        .visible("div#main");
};
```

I'm receiving the following error message:
> TypeError: browser.goto(...).title(...).evaluate(...).exists(...).then(...).then
(...).end is not a function
    at Object.<anonymous> (C:\Code\test\app.js:17:6)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:456:3

**Line 17 is on _end()_ call**

Thanks again, really appreciated your help
