### ISSUE TITLE
Odd behaviour on Windows 7 running in VMWare Fusion VM

### ISSUE THREAD

**Issue by TimNZ** [segmentio/nightmare#681]
OS X 10.11.5
Node 6.2.0
Electron 1.2.2

Got an issue where running the main example the Electron process will sit at 99% for ages and the example may or may not eventually complete.

Runs fine in a Windows 2008 VM hosted on MS Azure

What's the best way to debug this?

**Comment by rosshinkley** [comment]
My first gutcheck would be to run the example script with `DEBUG=*` to see if Electron has any useful output.  (My guess is probably not, but it's worth a try.)

Do you have different results running with showing the Electron instance using [`{show: true}`](https://github.com/electron/electron/blob/master/docs/api/browser-window.md#new-browserwindowoptions)?

If you write an example against a simpler site (like http://example.com, say) does it have the same behavior?

**Comment by TimNZ** [comment]
Feels like an Electron issue.  No issue in other Win 2008/Win 7 VM environments.
