### ISSUE TITLE
Improper behaviour on termination without actual usage

### ISSUE THREAD

**Issue by mrjj** [segmentio/nightmare#682]
When nighmare instance have not used it have no process attached and process property. As the result process termination handler as the event reaction trying to detach process using not existing attribute what is producing slightly misleading error.

The least impact fix seems to become aware that process attribute does not exists.

/Users/justaman/projects/ifetch/node_modules/nightmare/lib/nightmare.js:178
  if (instance.proc.connected) {
                   ^

TypeError: Cannot read property 'connected' of undefined
    at endInstance (/Users/justaman/projects/ifetch/node_modules/nightmare/lib/nightmare.js:178:20)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)

**Comment by gjmveloso** [comment]
Thanks @mrjj but I think we still doesn't have a _workaround_ on this, right?

**Comment by mrjj** [comment]
Please, see my answer in related bug.

**Comment by rosshinkley** [comment]
Fixed in #684.  Closing.
