### ISSUE TITLE
how can use flash?

### ISSUE THREAD

**Issue by littleweb** [segmentio/nightmare#683]

**Comment by rosshinkley** [comment]
Interacting with a Flash application is going to be difficult with Nightmare.  What are you trying to do?

**Comment by Wykks** [comment]
I need this too. Not because I need to directly interact with a flash app, but because the web page I load need flash to work.

**Comment by rosshinkley** [comment]
For what it's worth, you _can_ load [Flash in Electron](https://github.com/electron/electron/blob/master/docs/tutorial/using-pepper-flash-plugin.md).

Something like the following should work:

```js
var Nightmare = require('nightmare');

var nightmare = Nightmare({
  show: true,
  webPreferences: {
    plugins: true,
  },
  switches: {
    //note: the path on your machine is likely different
    //I'm lifting the player from my local chrome-unstable install
    'ppapi-flash-path': '/opt/google/chrome-unstable/PepperFlash/libpepflashplayer.so'
  }
});

nightmare.goto('http://www.adobe.com/software/flash/about/')
  .then();
```

You should see the Flash intro animation letting you know it is working properly.

**Comment by rosshinkley** [comment]
Closing for lack of response from the OP.  If this is still an issue, feel free to reopen/submit a new issue.

**Comment by Wykks** [comment]
Sorry for the delay ! It's working perfectly, thanks ! :)

**Comment by najmsheikh** [comment]
I tried the exact same steps and even made sure the path was correct but I still can't seem to load Flash content. Any fix for this?
