### ISSUE TITLE
electron child process exited with code null: undefined

### ISSUE THREAD

**Issue by oncletom** [segmentio/nightmare#694]
I use `xvfb-maybe` to run electron in Docker but since 2.5.1, it seems to crash with no further indication.

`nightmare@2.5.1`:

```
...
  nightmare queueing action "wait" +1ms
  nightmare queueing action "viewport" +0ms
  nightmare queueing action "screenshot" +0ms
  nightmare queueing action "viewport" +1ms
  nightmare queueing action "screenshot" +0ms
  nightmare queueing action "evaluate" +0ms
  nightmare running +1ms
  electron:stderr Xlib:  extension "RANDR" missing on display ":99". +120ms
  electron:stderr Fontconfig warning: ignoring C.UTF-8: not a valid language tag +222ms
  nightmare electron child process exited with code null: undefined +21ms
```

`nightmare@2.5.2`:

```
...
  nightmare queueing action "wait" +1ms
  nightmare queueing action "viewport" +0ms
  nightmare queueing action "screenshot" +0ms
  nightmare queueing action "viewport" +1ms
  nightmare queueing action "screenshot" +0ms
  nightmare queueing action "evaluate" +0ms
  nightmare running +1ms
  electron:stderr Xlib:  extension "RANDR" missing on display ":99". +100ms
  electron:stderr Fontconfig warning: ignoring C.UTF-8: not a valid language tag +200ms
  nightmare electron child process exited with code null: undefined +22ms
  nightmare electron child process not started yet, skipping kill. +1ms
```

Reverting to 2.5.0 solves the problem.

**Comment by albinekb** [comment]
What OS?

**Comment by LinusU** [comment]
`nightmare electron child process exited with code null: undefined +21ms`

I saw this as well on Ubuntu 16.04, it seems like the electron binary is exiting with a SIGSEGV right away. Could you try just starting electron (`./node_modules/electron-prebuilt/dist/electron`) and post the output?

**Comment by oncletom** [comment]
It uses an old Ubuntu:

```bash
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty
```

Sadly when I run the following, nothing gets returned:

```bash
# DEBUG=* ./node_modules/electron-prebuilt/dist/electron
```

**Comment by bahmutov** [comment]
There is an issue in electron repo that looks related https://github.com/electron/electron/issues/6186

**Comment by albinekb** [comment]
This is fixed with electron `1.2.5` and `electron-prebuilt` is released.
So run `npm install` again and it should work 😄 
close? @oncletom

**Comment by LinusU** [comment]
Please bump the dependency in Nightmare before closing

**Comment by oncletom** [comment]
I confirm the problem is solved thanks the new release of electron.

Thank you all for your help :-)

**Comment by rosshinkley** [comment]
Reopening until Nightmare dependency is bumped.

**Comment by trompx** [comment]
I am getting this error too.
Nightmare: 2.5.3
Electron prebuilt: 1.2.8
Ubuntu 14.04 in docker container
`electron:stderr Xlib:  extension "RANDR" missing on display ":1".`

**Comment by rosshinkley** [comment]
@trompx `XRANDR` being missing is not that big of a deal; unless you're explicitly loading it with `Xvfb` (or whatever X buffer you're using), that line is going to show up, serving as a warning that you will not be able to resize and rotate your buffer.  The original problem with this thread had to do with how Electron was being started, and on certain flavors of Linux, was crashing, which would cause Nightmare to misbehave.
