### ISSUE TITLE
Constrained screenshot height

### ISSUE THREAD

**Issue by OleVik** [segmentio/nightmare#695]
I was trying out rosshinkley's solution in [#328](https://github.com/segmentio/nightmare/issues/328#issuecomment-159311982) for taking full screenshots, that is, where the height adjusts to the measured dimensions of the `body`-element. As a test, I ran it against BBC.com, which in console returns:

```
{ height: 7119, width: 997 }
```

But the returned screenshot is 987px wide and 1025px high. I saw in some other issues that this may have to do with the system, so for reference this was run on Windows 10 64-bit 1920x1080 resolution (no HiDPI or other peculiarity, plain old laptop with an Nvidia card).

Why would the dimensions of the output image not match the recorded dimensions?

For reference, the script ran:

```
var Nightmare = require('nightmare'),
    vo = require('vo');

function * run() {
    var nightmare = new Nightmare({
        show: false,
        width: 1024,
        height: 768
    });
    var dimensions = yield nightmare.goto('http://bbc.com')
        .wait('body')
        .evaluate(function() {
            var body = document.querySelector('body');
            return { 
                height: body.scrollHeight,
                width: body.scrollWidth
            }
        });

    console.dir(dimensions);
    yield nightmare.viewport(dimensions.width, dimensions.height)
        .wait(1000)
        .screenshot(require('path')
            .join(__dirname, 'bbc.png'));

    yield nightmare.end();
}   

vo(run)(function() {
    console.log('done');
});
```

**Comment by rosshinkley** [comment]
Is this possibly the same problem as #596?

**Comment by OleVik** [comment]
Seemingly not, as the resulting screenshot is limited to a "standard" viewport, not affected by scaling. There is no zooming or proportionally dubious screenshots, rather just the absence of a variable height. The outcome width is as expected, but the outcome height is 1025px where it should be 7119px.

**Comment by antixrist** [comment]
+1 I have too the same issue (with almost equal code) on windows 7 x64.
But I getting the page size with following method:

```javascript
Nightmare.action('dimensions', function (done) {
  this.evaluate_now(function() {
    var body = document.body,
        html = document.documentElement;

    var height = Math.round(Math.max(
      body.scrollHeight,
      body.offsetHeight,
      html.clientHeight,
      html.scrollHeight,
      html.offsetHeight
    ));

    var width = Math.round(Math.max(
      body.scrollWidth,
      body.offsetWidth,
      html.clientWidth,
      html.scrollWidth,
      html.offsetWidth
    ));

    return {width, height};
  }, done)
});
```

**Comment by rosshinkley** [comment]
@OleVik Specifically, I was referring to the scrollbar/title et al eating into the pixel count.  I think that might be _part_ of the problem.  The buffer height being incorrect is distressing.

I know there is a problem where you cannot create a window larger than the display size on Windows (see electron/electron#4932 and possibly electron/electron#5053), but resetting the viewport (which calls `BrowserWindow.setSize()` under the covers) _should_ work.

Out of curiosity: can you set the height using `.viewport()` to something big but smaller than the size returned?  Something on the order of `.viewport(dimensions.width, 4000)`?  (I wonder if you're possibly hitting a texture limit and Chromium is misbehaving because of it.)

**Comment by OleVik** [comment]
Running the same script as above, but with `yield nightmare.viewport(dimensions.width, 4000)`, the resulting image is 987x1025.

**Comment by rosshinkley** [comment]
@OleVik Out of curiosity, what happens if you try to snap a screenshot of say, `.viewport(4000,4000)`?

A while back, I wrote a quick and dirty [gist](https://gist.github.com/rosshinkley/b5fb5061073756e926b791a66d62b24b) that spit out the max texture size - I wonder if that could be ported to use opengl and freeglut for Windows?

**Comment by OleVik** [comment]
With `yield nightmare.viewport(dimensions.width, 4000)` the output image is 1914x1025, and the console output `{ height: 7469, width: 997 }`. So seems like a texture limit, not quite sure how to port that gist to Windows, but it would be very handy to be able to take unconstrained screenshots.

**Comment by rosshinkley** [comment]
Hm, that's ... odd.  I would not expect a texture tile to be rectangular.  This makes me wonder if it's something perhaps Windows-specific.

What version of Windows are you running?

**Comment by OleVik** [comment]
Not sure which details matter most, but: Windows 10 64-bit, DirectX 12 on Nvidia GeForce GT 540M (driver v353.62). Resolution is 1920x1080, and since the graphics are integrated (Intel HD Graphics 3000) its current resolution is reported by Speccy as 1536x864 pixels.

**Comment by mkmkku** [comment]
Try this code
` var nightmare = new Nightmare({
maxHeight:2000,
maxWidth:2000
    });`

**Comment by jimmaay** [comment]
var nightmare = new Nightmare({ maxHeight:2000, maxWidth:2000 }); **almost** fixed it for me. It's only getting 95% of the screenshot now even with max-height being extremely large and the actually screenshot being nowhere near the max height. It looks like the screenshot png is getting capped at 4500 KB.

**Comment by BhavinPatel04** [comment]
@jimmaay, can you try 
var nightmare = new Nightmare({ minHeight:7119, minWidth:1000 });

It worked for me.

**Comment by OleVik** [comment]
@BhavinPatel04 It is indeed much closer to the expected output than before. Using Nightmare v2.9.1, running the same script as before but with

```
    var nightmare = new Nightmare({
        show: false,
        minWidth: 1000,
        width: 1024,
        minHeight: 7119,
        height: 768
    });
```

The returned image is 1914px wide and 7060px high. Apart from the small error margins in dimension, which presumably could be offset with higher `min`-properties, there is a fairly large discrepancy with set `width` and `height`. When I add in `maxHeight:2000` and `maxWidth:2000`, as suggested by @mkmkku, the returned image is 1990px wide and 7060px high.

I should add, the output of `console.dir(dimensions);` is `{ height: 7144, width: 993 }`, so there is also a discrepancy between how big Nightmare measures the target to be, and what the output is, at least with the setup from the initial post updated with the above.

**Comment by jimmaay** [comment]
Yeah I ended up changing maxHeight to 16384, anything higher will cause #906
