### ISSUE TITLE
Error handling when we provide wrong password of http authentication

### ISSUE THREAD

**Issue by snakewa** [segmentio/nightmare#696]
Hi, 

For now, it looks like the nightmare is hanged if the http authenticate with wrong password and need to wait navigation timeout. 

Thanks,
Tim

**Comment by rosshinkley** [comment]
Looking at the current implementation of `.authentication()` and the documentation for the [`login` event](https://github.com/electron/electron/blob/master/docs/api/web-contents.md#event-login), the actual authentication happens out-of-band with respect to the Nightmare action chain.  There also isn't a login failure event exposed by Electron.  This makes handling error cases tough.

The best solution I can think of is to have Nightmare support an internal event to kill the event chain from an out-of-band event, then creating an out-of-band event after a certain number of retries.

Trying to fix this also uncovered another problem: being able to change authentication after it is set.

All of the above _should_ be addressed in #714.
