### ISSUE TITLE
Slow websites

### ISSUE THREAD

**Issue by geostant** [segmentio/nightmare#698]
Hey,

I'm using nightmare to build scrapers,
till now it went pretty well with fast response website - however I've encountered a very slow response website which give me timeouts on wait for elements (it's set to 30 seconds).

I know that I can change the wait timeout, however I'm trying to figure out a better way to solve it as a static timeout isn't the great solution when it fluctuating.

Thanks !

**Comment by rosshinkley** [comment]
I'm not exactly sure I understand the problem you're trying to solve.  Are you asking if `.wait()` could accept a timeout per-call?

**Comment by rosshinkley** [comment]
I _think_ the intent of this is the same as #742.  Merging.
