### ISSUE TITLE
Screen resolution (Not a viewportSize)

### ISSUE THREAD

**Issue by Firues** [segmentio/nightmare#699]
Can I change the screen resolution in nightmarejs?
For example, how it works in Casperjs:
```
var casper = require("casper").create({
    onPageInitialized: function (page) {
        page.evaluate(function () {
            window.screen = {
                width: 1920,
                height: 1080
            };
        });
    }
});
```
Already more than 4 hours trying to figure out. Thank you!

**Comment by rosshinkley** [comment]
I'm not certain, but I don't think so, at least not directly.  Electron's screen resolution depends on the framebuffer it's rendering to.  You could use something like `xvfb-run` to alter the framebuffer (#224 touches on this, although for an entirely different reason).

What are you trying to accomplish?

**Comment by rosshinkley** [comment]
Closing for lack of response from OP.  Feel free to reopen/open a new isuse if this is still a problem and you have more information.
