### ISSUE TITLE
add support for Phantom 2

### ISSUE THREAD

**Issue by bprodoehl** [segmentio/nightmare#70]
I have a fork of phantomjs-node that supports PhantomJS 2, and I am trying to get it accepted upstream.  The changes so far look pretty clean and are backwards compatible with PhantomJS 1.9.7, so hopefully that goes smoothly.  In the meantime, people that want to give Phantom 2 a spin should be able to replace the nightmare version in their package.json with "https://github.com/bprodoehl/nightmare/archive/phantom2.tar.gz"

The PR for phantomjs-node is here: https://github.com/sgentle/phantomjs-node/pull/209

**Comment by samuelmeireles** [comment]
Any results with Nightmare + Phantomjs 2?

**Comment by xzyfer** [comment]
PhantomJS just released 2.0.0-stable https://github.com/ariya/phantomjs/releases/tag/2.0.0

**Comment by thotypous** [comment]
Should this be closed? Nightmare is apparently working without any problems with PhantomJS 2.

**Comment by bprodoehl** [comment]
Yes, please close.  Thanks!
