### ISSUE TITLE
scrollTo not working with more than one scrollbar?

### ISSUE THREAD

**Issue by felix185** [segmentio/nightmare#703]
I have an issue with a web application we develop in our company: There are presented the first results of a search and to see more results you have to scroll down. As there are many indexes to choose, there is a second scrollbar. And I wanted Nightmare to scroll down to the bottom of the page until no more results are presented. But it was not possible to scroll down.
I tried to reproduce it with another website and I found a website where I can see the same behaviour.

I am running the latest version of NightmareJS on Windows 7, 64 bit

Here is my code: 
```
var Nightmare = require('nightmare');
var vo = require('vo');
var nightmare = Nightmare({
    show: false
});
var run = function * () {
    yield nightmare.goto('http://codepen.io/Yakudoo/pen/YXxmYR');

    var previousHeight, currentHeight = 0;
    while (previousHeight !== currentHeight) {
        yield nightmare.screenshot('screenBefore.png');
        previousHeight = currentHeight;
        var currentHeight = yield nightmare.evaluate(function () {
            return document.body.scrollHeight;
        });      
        yield nightmare
            .scrollTo(currentHeight, 0)
            .wait(3000);
        console.log('Current: ' + currentHeight);
        console.log('Previous: ' + previousHeight);
        yield nightmare.screenshot('screenAfter.png');
    }
    yield nightmare.end();
};
vo(run)(function (err) {
    console.dir(err);
    console.log('done');
});
```

And I also will attach the screenshots to show you that none of the scrollbars scrolled down: 

Before:
![screenbefore](https://cloud.githubusercontent.com/assets/10739344/16480387/e34f3f1a-3e9d-11e6-9c82-fd1f92a84c72.png)

After:
![screenafter](https://cloud.githubusercontent.com/assets/10739344/16480388/e35252e0-3e9d-11e6-9ede-1997d65ac5cd.png)

If anybody has found a solution for my problem, please let me know. 
Thank you

**Comment by rosshinkley** [comment]
`.scroll()` [scrolls on the window](https://github.com/segmentio/nightmare/blob/master/lib/actions.js#L494), not on the components contained in them.

That being said, you should be able to use `.evaluate()` and [`Element.scrollTop`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTop) to accomplish what you're trying to do.  If I'm reading your source, you're trying to scroll to the end of all of the code divs, yes?  Something like:

```js
var Nightmare = require('nightmare');
var vo = require('vo');
var nightmare = Nightmare({
  show: true
});
var run = function*() {
  yield nightmare.goto('http://codepen.io/Yakudoo/pen/YXxmYR');

  var currentHeight;
  var currentHeight = yield nightmare.evaluate(function() {
    var scrolls = document.querySelectorAll('.CodeMirror-scroll');
    return {
      html: scrolls[0].scrollHeight,
      css: scrolls[1].scrollHeight,
      js: scrolls[2].scrollHeight,
    }
  });
  console.dir(currentHeight);

  yield nightmare.evaluate(function(heights){
    var scrolls = document.querySelectorAll('.CodeMirror-scroll');
    scrolls[0].scrollTop = heights.html;
    scrolls[1].scrollTop = heights.css;
    scrolls[2].scrollTop = heights.js
  }, currentHeight);

};
vo(run)(function(err) {
  console.dir(err);
  console.log('done');
});
```

I left both evaluate calls in for illustrative purposes.  You could cut one of the `.evaluate()` calls and determine height and scoll in a single step:

```js
var Nightmare = require('nightmare');
var vo = require('vo');
var nightmare = Nightmare({
  show: true
});
var run = function*() {
  yield nightmare.goto('http://codepen.io/Yakudoo/pen/YXxmYR');
  yield nightmare.evaluate(function() {
    Array.from(document.querySelectorAll('.CodeMirror-scroll')).forEach(function(el){
      el.scrollTop = el.scrollHeight;
    });
  });
};
vo(run)(function(err) {
  console.dir(err);
  console.log('done');
});
```

These might not be 100% what you need, but it should get you on track.

**Comment by felix185** [comment]
@rosshinkley Thank you very much for your help.
