### ISSUE TITLE
what about if I send an ajax request in evaluate function?

### ISSUE THREAD

**Issue by goddyZhao** [segmentio/nightmare#709]
What about if I have the follow test case:

```javascript
nightmare
  .goto('http://yahoo.com')
  .type('form[action*="/search"] [name=p]', 'github nightmare')
  .click('form[action*="/search"] [type=submit]')
  .wait('#main')
  .evaluate(function () {
    // send an ajax request and how can I wait to execute next step until the response is return?
  })
  .end()
```

**Comment by icaromh** [comment]
$.ajax has a setting named `async`, you can set up to "false". Maybe it works :dancer:

**Comment by goddyZhao** [comment]
Thanks @icaromh for your information. Actually ajax is just an example, I actually want to know how to handle the async case, because with phantomjs, if you execute an javascript function on the page you open, there is an API called `window.callPhantom` to communicate with the phantom process outside, so the async handler won't be a problem. I just want to ask whether there are corresponding solution in nightmarejs

**Comment by rosshinkley** [comment]
@goddyZhao This is one of the things that #573 was attempting to address.  Currently, there is no way to allow for asynchronous actions in `.evaluate()` out of the box.

**Comment by rosshinkley** [comment]
Merging into #552.
