### ISSUE TITLE
Iframe support 

### ISSUE THREAD

**Issue by diverse-soles** [segmentio/nightmare#710]
I did some research on switching to an iframe and found a package someone made for it. Unfortunately, this package is outdated.
I would like to switch to an iframe based on both the index and the name of the frame.
Thanks.

**Comment by rosshinkley** [comment]
@diverse-soles Out of curiosity, what library were you using?

**Comment by diverse-soles** [comment]
@rosshinkley https://www.npmjs.com/package/nightmare-iframe
https://github.com/segmentio/nightmare/issues/203
