### ISSUE TITLE
re-inject upon page refresh

### ISSUE THREAD

**Issue by dwelle** [segmentio/nightmare#711]
Is it possible to re-inject (manually or otherwise) previously injected files when the electron app refreshes due to file change (via watcher). The goal being to inject test files every time I update them (without having to restart nightmare).

**Comment by rosshinkley** [comment]
Instead of using `.inject()` (which is what I'm assuming you're using?), you _might_ want to define a [custom preload](https://github.com/segmentio/nightmare#custom-preload-script) for your test suite.

**Comment by dwelle** [comment]
Great, thanks for help.

For others, here's the MWP to append a file:

```
window.__nightmare = {};
__nightmare.ipc = require('electron').ipcRenderer;

const fs = require('fs');
const contents = fs.readFileSync( 'path/to/file', { encoding: 'utf8' });

document.addEventListener( 'DOMContentLoaded', () => {
    var script = document.createElement('script');
    script.innerHTML = contents;
    document.head.appendChild(script);
}, false);
```

But, you may want to copy/paste the default contents of [preload](https://github.com/segmentio/nightmare/blob/f6d52ca6fead555e8b460554b7b137bda53a0879/lib/preload.js), too, as stated.
