### ISSUE TITLE
electron crash? during paypal testing

### ISSUE THREAD

**Issue by AVVS** [segmentio/nightmare#712]
I've got an automated test-suite for a few paypal actions, manually testing stuff works (ie put an URL in the browser, complete the transaction), but going through nightmare/elector child processes closes from to time (based on what A/B testing bucket my test had fallen in).

Logs for the build:
https://semaphoreci.com/makeomatic/ms-payments/branches/fix-updated-transport/builds/1

Code for the test that fail:
https://github.com/makeomatic/ms-payments/blob/fix/updated-transport/test/suites/sales.js#L24-L85

Gets to this point:
https://github.com/makeomatic/ms-payments/blob/fix/updated-transport/test/suites/sales.js#L65

Then electron closes right away. I'm not sure what I can do here and how to avoid such a case or at least fail not on a timeout

**Comment by rosshinkley** [comment]
@AVVS are those files available publicly?  The links you provided all 404.

Maybe you could post the relevant parts here or in a gist?

**Comment by AVVS** [comment]
@rosshinkley restored branch so you can see the code, logs are also available again on this same build

**Comment by rosshinkley** [comment]
At first blush, I suspect the selector you're typing into does not exist.  It may be worth checking with `.exists()` first, and if it does not exist, throwing an exception.  Error handling/reporting could stand some improvement (see #646).

**Comment by AVVS** [comment]
I'll check it. Thanks for pointing out

**Comment by inakianduaga** [comment]
@AVVS Most crashes in electron in my experience are due to invalid selectors, run electron with the verbose flag, it should reveal invalid selectors (or whatever else is making it crash).

**Comment by rosshinkley** [comment]
@AVVS Is this resolved?

**Comment by AVVS** [comment]
@rosshinkley not yet, still playing with this. Please leave this issue opened and I'll let you know

**Comment by GautierT** [comment]
@inakianduaga : how to run electron with verbose flag ?

**Comment by AVVS** [comment]
@rosshinkley recent versions seem fine & thanks for the tips

**Comment by rosshinkley** [comment]
@AVVS No problem, glad you got it sorted.
