### ISSUE TITLE
Viewport API sets window height not viewport height

### ISSUE THREAD

**Issue by asakusuma** [segmentio/nightmare#722]
I have 4 divs, each 100px tall. I set the viewport height to 400px. The viewport should be the same height as the 3 divs combined, but the last div is cutoff. I noticed the amount cutoff is the same height of the window control bar at the top of the window. In other words, it would seem that `.viewport()` sets the height of the window not the height of the viewport.

![Screenshot](https://i.imgsafe.org/6698013ac1.png)

**Comment by rosshinkley** [comment]
This is a known quirk, for lack of a better word.  The underlying implementation calls [`BrowserWindow.setSize()`](http://electron.atom.io/docs/api/browser-window/#winsetsizewidth-height-animate).  It's been touched on in [#593](https://github.com/segmentio/nightmare/issues/593#issuecomment-216927915) as a breaking change, and also talked about in [#596](https://github.com/segmentio/nightmare/issues/596#issuecomment-214392429).

**Comment by rosshinkley** [comment]
Also worth pointing out: setting `webPreferences.useContentSize` to `true` will force the render area to be the size that `.viewport()` sets.

With that, I think this issue is resolved.  If you're still having problems, feel free to reopen/open a new issue.
