### ISSUE TITLE
getBoundingClientRect returns an empty object

### ISSUE THREAD

**Issue by xmen4u** [segmentio/nightmare#723]
Tried it on multiple sites, different elements, the element is being acquired, but the return is an empty object.

**Comment by rosshinkley** [comment]
I'm guessing you're trying to return `DOMElement.getBoundingClientRect()` from `.evaluate()`?  I suspect that the properties of DOM object you get back are not enumerable, and as such, aren't getting serialized.  Try explicitly returning an object with the properties you want.

**Comment by xmen4u** [comment]
@rosshinkley correct, that is what i'm trying to do. However, i've also tried explicitly doing that, by Object.keys it, however in both cases the return is an empty array [object]. Unless you meant something completely different.

**Comment by xmen4u** [comment]
anyone?

**Comment by rosshinkley** [comment]
@xmen4u Could you post an example?  I want to be sure we're on the same page.

**Comment by xmen4u** [comment]
@rosshinkley: sure:

`nightmare.viewport(800,600).goto(url)wait().evaluate(()=>document.getElementById('priceblock_ourprice').getBoundingClientRect()).then(bounds=>console.log(bounds. .... )).catch(...)`

where the console.log can be specific or JSON.stringify, i've tested both.

**Comment by rosshinkley** [comment]
Again, the `DOMRect` that `getBoundingClientRect()` won't serialize nicely, and won't cross the IPC boundary between Electron and Nightmare.  You'll lose the properties and be left with an empty object.

The easiest way to fix this is to return an object with the properties off of the `DOMRect` that you want.  Something like:
```js
var nightmare = require('nightmare')();
nightmare
  .goto('http://example.com')
  .evaluate(() => {
    //get the bounding rect for the `body`
    var rect = document.querySelector('body').getBoundingClientRect();
    //pull out `top` and `width`
    return {
      top: rect.top,
      width: rect.width
    };
  })
  .then(bounds => console.log(bounds))
```
I apologize this wasn't clear before.

**Comment by xmen4u** [comment]
@rosshinkley Thank you so much! this seems to work!

**Comment by sebastienbarre** [comment]
Do you guys would happen to know in which unit these coordinates are returned? The bounding rectangle I'm getting is distorted vertically...

**Comment by rosshinkley** [comment]
@sebastienbarre Memory serving, they're in pixels... you _might_ want to open a new issue (if you haven't already) with an example.

**Comment by jamesplease** [comment]
Just poppin' in here to mention the `toJSON()` method.

```js
const domRect = document.querySelector('body').getBoundingClientRect();

Object.values(domRect);
// => []

const domRectObj = domRect.toJSON();
Object.values(domRectObj);
// => [0, -1330, 1678, 2673, -1330, 1678, 1343, 0]
```
