### ISSUE TITLE
Get all errors and events.

### ISSUE THREAD

**Issue by hovosanoyan** [segmentio/nightmare#724]
Hi. i have some issue with running form filling in for loop. The problem is that i can't enable DevTool because i'm using "nightmare-upload" it wont work if i will enable DevTools. So i can't see is there any error in console or something else. It's running several times and stopping/freezing on some page. 
My question : is there any option to get all messages, events, errors with listening only one event so i can see what is happening on the page. 
After some more investigation i detected that it's stopping on .wait(selector) function. I checked and the callback is not working always once it's not working and the wait function is stopping working.
This is the code to test it. Sometimes it's working sometimes no, so i think it's some bug maybe.

```
const Nightmare = require('nightmare');
require('nightmare-upload')(Nightmare);
var co = require('co');
var sleep = require('co-sleep');

function* call() {
    let win = Nightmare({
        show: true,
        switches: {
            "proxy-server": "5.135.176.41:3123",
            'ignore-certificate-errors': true
        }
    });

    yield win.goto('https://www.leboncoin.fr/')
        .click('#header > section > section > aside > button')
        .wait('#popin-content > section > main > section.connexion-form.visible > form')
        .type('input[name="st_username"]', "alextuteur44@gmail.com")
        .type('input[name="st_passwd"]', "leboncoin123")
        .click('input[type="submit"]')
        .wait(".create a")
        .click(".create a");

    for (let i = 0; i < 50; i++) {
        console.log('Running ' + i);
        //win.goto("http://www2.leboncoin.fr/ai?ca=12_s")
        try {
            yield win.wait("#category")
                .select("#category", 36)
                .insert("#subject", "subject")
                .insert("#body", "ad text just for exmaple")
                .insert("#location_p", "")
                .insert("#location_p", "97017")
                .insert("#address", "")
                .insert("#phone", "+337743457865")
                .check("#phone_hidden")
                .upload('#image0', __dirname + "/original.jpg")
                .wait('#uploadPhoto-0[data-state="uploaded"]')
                .click("#newadSubmit")
                .wait("#accept_rule")
                .check("#accept_rule")
                .click("#lbc_submit")
                .wait(".confirm a:not(:first-child)")
                .click(".confirm a:not(:first-child)")
            let t = 1000;
            console.log(`Sleeping thread for ${t}s`);

            yield sleep(t);

            console.log(`Timeout is ${t}`)
        } catch (e) {
            console.log(e)
        }
        console.log('Finished ' + i);
    }

    win.end();
}

co(call()).then((m) => {
    console.log(`Thats ok ${m}`)
}).catch((err) => {
    console.log(err)
})
```

**Comment by rosshinkley** [comment]
>  is there any option to get all messages, events, errors with listening only one event so i can see what is happening on the page.

Try running your script with `DEBUG=nightmare*,electron*` if you're not already.  That might have some useful information.

> After some more investigation i detected that it's stopping on .wait(selector) function.

Is it the same one every time?

> I checked and the callback is not working always once it's not working and the wait function is stopping working.

Which callback?  The one for `co`?

**Comment by hovosanoyan** [comment]
hi, thanks for respond. Yeah i'm already using DEBUG flags. But can't get information about my issue.

It's every time in same page but the count of loops is different so once it may stop on 15 another time it will stop on 5.

And what about callback i meant the 
```
setTimeout(function () {
          tick.apply(self, args);
        }, _timeoutMs);
```
in action.js line : 405 .
