### ISSUE TITLE
Incorrect values with concurrent execution

### ISSUE THREAD

**Issue by cchamplin** [segmentio/nightmare#727]
I'm experiencing issues where I'm not able to perform Nightmare calls inside of an event callback. Specifically if I have a setup like:

``` javascript
  var screenshot = function *() {
      var url = yield nightmare.url();
      ...do some stuff
      yield nightmare.screenshot(...);
  }
  this.nightmare.on('did-finish-load',() => {
      co(screenshot).then(function (result) {},function (err) {console.log("Screenshot Error!: " + err)});
    });
```

``` javascript
var exists = yield this.nightmare
                .goto(site.backend)
        .type('input#username',admin.username)
        .type('input#login',admin.password)
        .click('#loginForm .form-button')
        .wait('ul#nav')
   .exists('#productGrid');
```

The result of exists and the result of url are often times mixed up (url will get "true", and exists will get a url).

Is there a way around this, or a proper was to perform nightmare actions inside of an event callback?

**Comment by casesandberg** [comment]
You have to use `.done()` at the end of all operations to make nightmare return a promise.
