### ISSUE TITLE
Improve documentation website

### ISSUE THREAD

**Issue by aendrew** [segmentio/nightmare#729]
Hi there! Apologies if this is the wrong place to put this, wasn't sure whether to do so here (due to the README) or segmentio/nightmarejs.org (where the site code lives).

I use Nightmare lots and it's the first thing I recommend to journalists wanting a resilient tool for scraping poorly-built websites. That said, the documentation tends to throw people — the syntax on nightmarejs.org uses generators while the README is functional. Regardless, it's honestly one of the best browser automation tools out there at the moment and I feel it could achieve a wider audience if the documentation was improved a bit.

Any chance you'd be interested in me helping to improve the documentation website? I'd add a bunch more examples covering a wider selection of use cases, allow the examples to be displayed using callbacks, generator, or await/async syntax and pull the doc comments into an online documentation viewer (or, in cases where the README is more detailed than the doc comments, open PRs migrating those into the codebase). I'd also try to migrate in some of @rosshinkley's excellent examples/documentation (which I just noticed and is somewhat buried in the README). I'm anticipating a 2-3 month timeline for such a project.

Thanks!

**Comment by vagnerj** [comment]
or at least put the link for the @rosshinkley's examples into the official readme: 
https://github.com/rosshinkley/nightmare-examples

it would have saved me few headaches :)

**Comment by aendrew** [comment]
For what it's worth, I wrote a Medium post about Nightmare awhile back:

**Comment by matthewmueller** [comment]
Hey @aendrew! Thanks for writing this article, I've included it in https://github.com/segmentio/nightmare#additional-resources.

I don't think segment is really promoting the website anymore, the readme appears to be the place to get the goods!
