### ISSUE TITLE
Screenshot with opened <select> object

### ISSUE THREAD

**Issue by ryanvincent29** [segmentio/nightmare#732]
I am currently attempting to take a screenshot using **Nightmare JS** where it also includes the dropdown (`<option>`) of a `<select>`. 

In order to get the dropdown to appear, I use the [**nightmare-real-mouse package**](https://github.com/Mr0grog/nightmare-real-mouse) to click the `<select>`. Locally, I have verified that this click will open the select (I set `show:true` on initialization of the nightmare object). However, the screenshot does not include the dropdown menu.

I have also tried adding a `nightmare.wait(1000)`, just in case the response to the `nightmare.realClick()` is not rendering quickly.

**Comment by rosshinkley** [comment]
Correct me if I'm wrong: isn't the default `<select>` control an OS-level control (or at best, an application control)?  It's not necessarily rendered by the web frame - meaning that I don't think it will show up with `.screenshot()`.
