### ISSUE TITLE
Output Nightmare logs to file

### ISSUE THREAD

**Issue by pkantsedalov** [segmentio/nightmare#734]
Hi everybody.

I have a question.
I haven't found the way how set up Nightmare's logs output to be saved to file, not to be displayed in the console. 
It seems that I could listen to the [specific Electron's events and work with them](https://github.com/segmentio/nightmare#onevent-callback), but my I'm interested in this one: **nightmare:log**. Could I catch it or something?

Thanks in advance.

**Comment by rosshinkley** [comment]
Could you do something like `DEBUG_FD=3 DEBUG=nightmare*,electron* node my-script.js 3>log.txt`?

**Comment by rosshinkley** [comment]
(Alternatively, I think you should be able to use `nightmare.on('log', fn)` to capture log messages.)

**Comment by pkantsedalov** [comment]
Thanks a lot!
