### ISSUE TITLE
Unable to set proxy and auth

### ISSUE THREAD

**Issue by antonellopasella** [segmentio/nightmare#735]
This is a _censored_ gist
https://gist.github.com/antonellopasella/0efa1fe935a4fbcc5b561b0699e809df

If can be useful, contact me on gitter and I can provide a couple proxy+auth for testing

Thanks!

**Comment by Snake4life** [comment]
how can I force the proxy to stay when page is changing by a link?

**Comment by rosshinkley** [comment]
@Snake4life The proxy server is set up for every request from Electron.  Are you not seeing that behavior?

**Comment by Snake4life** [comment]
oh yeah sorry forget my question I fixed it thanks!
