### ISSUE TITLE
Error on 'wait' after 'goto' status code check

### ISSUE THREAD

**Issue by voidmonk** [segmentio/nightmare#737]
Hey guys, I'm trying to check the `goto` request's HTTP status code before evaluating the results:

```node
nightmare
  .goto(url)
  .then((gotoStatus) => {
    if (!gotoStatus || !gotoStatus.code || gotoStatus.code != 200) {
      // non-OK response code: halt nightmare and respond with error
      nightmare.end();
      console.log("HTTP error");
    }
  })
  .wait(250) // only wait on OK response for DOM & page JS to complete updates
  .evaluate(function() {
    // some eval code that returns results
  })
  .end()
  .then(function(results) {
    console.log(results);
  })

```

But I keep getting the error:

```
 .wait(250)
       ^

TypeError: nightmare.goto(...).then(...).wait is not a function
```

Any idea why an error is thrown? It works if the `then` function (which checks the status code) after `goto` is removed.

**Comment by johnferro** [comment]
Someone with more knowledge than I have might be able to provide a better explanation, but you're running into this issue because the `then` function is returning a promise, not the instance of nightmare that has the `wait` function.

The second example shown here describes chaining multiple steps together:

https://github.com/rosshinkley/nightmare-examples/blob/master/docs/beginner/promises.md

**Comment by voidmonk** [comment]
Thanks @johnferro. An internal chain of steps worked:

```node
nightmare
  .goto(url)
  .then((gotoStatus) => {
    if (!gotoStatus || !gotoStatus.code || gotoStatus.code != 200) {
      // non-OK response code: halt nightmare and respond with error
      console.log("HTTP error");
      return nightmare.end();
    } else {
      // OK response
      return nightmare
        .wait(250)
        .evaluate(function() {
          // some eval code that returns results
        })
        .end()
        .then(function(results) {
          console.log(results);
        });
      } // if-else-end
  });
```

Hopefully @rosshinkley or someone with a better understanding of Nightmare can confirm the validity and object disposal.

**Comment by Mr0grog** [comment]
Some notes:

```js
.then((gotoStatus) => {
    if (!gotoStatus || !gotoStatus.code || gotoStatus.code != 200) {
```

`goto` *always* returns an object, whether there was success or error, so you can just `if (gotoStatus.code !== 200)`

You should also add a `.catch(error => { /* do something */ })` after the `.then()` handler in case the `goto` fails (e.g. you are offline, the server doesn't respond, the request times out, too many redirects, etc) and in case there are other errors in the rest of your code.

This last one is purely stylistic, but you can pull the last `.then()` up a level so you have less nesting.

Here’s a slight revision that might be a bit more solid:

```js
nightmare
  .goto(url)
  .then(gotoStatus => {
    if (gotoStatus.code !== 200) {
      return Promise.reject("HTTP error");
    }
    // OK response
    return nightmare
      .wait(250)
      .evaluate(function() {
        // some eval code that returns results
      });
  })
  .then(result => console.log('Result:', result))
  .catch(error => console.log('An error occurred:', error))
  .then(_ => nightmare.end());
```

**Comment by Mr0grog** [comment]
Another nice thing you can do to tidy up your code is make a plugin for rejecting responses based on status code:

```js
Nightmare.action('rejectNonOkResponses', status => {
  return status.code === 200 ? status : Promise.reject("HTTP error");
});

nightmare
  .goto(url)
  .rejectNonOkResponses()
  .wait(250)
  .evaluate(function() {
    // some eval code that returns results
  })
  .then(result => console.log('Result:', result))
  .catch(error => console.log('An error occurred:', error))
  .then(_ => nightmare.end());
```

**Comment by voidmonk** [comment]
Thanks @Mr0grog, that looks much cleaner.

On a related note, the process hangs if response code is HTTP 30: issue #740. Any clues on that one?!

**Comment by Mr0grog** [comment]
Actually, nevermind my second comment; it won’t work. I was working on something that would enable that at one point, but I guess I never got around to finishing it and submitting a PR. :\

The first example is still all good, though.
