### ISSUE TITLE
Nightmare + CodeceptJS

### ISSUE THREAD

**Issue by DavertMik** [segmentio/nightmare#738]
Not an issue but an announcement that we have added Nightmare as a running backend for [CodeceptJS](http://codecept.io/nightmare/) testing framework. We are using one API for Selenium and Nightmare tests so you can easily switch between drivers. One of the major technical improvements that CodeceptJS allows to use not only CSS but XPath locators in tests. It was pretty complicated but it works.

Thanks to segmentio and all Nightmare contributors!

**Comment by rosshinkley** [comment]
Nice!  Thanks for the update!
