### ISSUE TITLE
Multiple .evaluate() + .then()

### ISSUE THREAD

**Issue by nashwaan** [segmentio/nightmare#741]
I think this is a common question but I could not find a clear answer.
```Javascript
var items = [];
var nightmare = Nightmare({show: true});
for (var i = 1; i < 5; ++i) {
    nightmare
    .goto('http://www.example.com/page' + i)
    .evaluate(function () {
        return document.querySelector('#item');
    })
    .then(function (item) {
        items.push(item);
    });
}
nightmare.end();
```
This doesn't work.
In most of the examples in Readme.md, `.end()` is called before `.then()`, but if i do that then nightmare instance is shut down before having the chance to execute the next `.goto()`.

**Comment by rosshinkley** [comment]
Give [asynchronous operations and loops](https://github.com/rosshinkley/nightmare-examples/blob/master/docs/common-pitfalls/async-operations-loops.md) a read - that should help you get started.
