### ISSUE TITLE
Document's height seems to be incorrect

### ISSUE THREAD

**Issue by dcgauld** [segmentio/nightmare#749]
I'm using the screenshot function to grab some images for a selection of webpages.

I use `document.documentElement` to retrieve the height of the page in an attempt to capture a screenshot of the full page, however the document's height returned from the `evaluate` function is different to the value returned in devtools when I manually execute it on the webpage.

It results in the addition of a large blank area at the bottom of the screenshot, which is the same colour as the background of the webpage itself.

I've included the code I'm using below to see if it can be replicated, using the BBC News website as an example. I've also attached the image produced from the below code.

Any help would be hugely appreciated! Thanks.

``` javascript
var Nightmare = require('nightmare');
var nightmare = Nightmare({
  frame: false,
  useContentSize: true,
});

nightmare
  .goto('http://bbc.co.uk/news')
  .wait(1000)
  .evaluate(function() {
    var rect = document.documentElement.getBoundingClientRect();
    return {
      x: Math.round(rect.left),
      y: Math.round(rect.top),
      width: 1200,
      height: Math.round(rect.height)
    };
  })
  .then(function(dimensions) {
    return nightmare
      .viewport(dimensions.width, dimensions.height)
      .wait(1000)
      .then(function() {
        return nightmare.screenshot('test.png', dimensions);
      })
      .then(function() {
        nightmare.end(function() {
          console.log('Done.');
        });
      });
  });
```

Image:

![test](https://cloud.githubusercontent.com/assets/1469007/17373986/846b2bf6-59a2-11e6-8e4c-3d9dfa0dc6b0.png)

**Comment by rosshinkley** [comment]
I'd be curious to know what operating system and version of Nightmare you're running.  Electron (and Chromium) misbehave beyond the texture size limit (see #616 and possibly #695) - is it possible you're hitting that?

**Comment by stevenvachon** [comment]
Perhaps the `.wait(1000)` isn't long enough? Try using a `.then()` instead:
```js
return browser
.goto( testPath.doc(doc) )
.viewport(1000, 0)  // for getting the actual height of short content
.then(() => browser.evaluate(calculateContentHeight))
.then(contentHeight => browser.viewport(1000, contentHeight))
.then(() => browser.screenshot())
```

**Comment by casesandberg** [comment]
Are you still having trouble and have you tried 2.10.0? I am going to close this, but feel free to re-open if it's still an issue.
