### ISSUE TITLE
Strange type() behavior

### ISSUE THREAD

**Issue by ivan-kleshnin** [segmentio/nightmare#750]
Possibly noob question (sorry)... but I just can't explain this behavior:

``` js
let load = nightmare
  .goto("http://facebook.com") 
  .wait(200)
  .type("#email", "xxx") // starts typing in #email field  
```

``` js
let load = nightmare
  .goto("http://facebook.com") 
  .type("#email", "xxx") // starts typing in #firstname field  
```

Any clues what's going on?

**Comment by rosshinkley** [comment]
@ivan-kleshnin What version of Nightmare are you using?  When I run your second example with 2.6.0, I get the expected behavior of typing in `#email`.

**Comment by ivan-kleshnin** [comment]
2.6.0.

My full code

```js
let Nightmare = require("nightmare")

let nightmare = Nightmare({
  show: true,
  dock: true,
  openDevTools: {
    mode: "detach"
  },
})

let load = nightmare
  .goto("http://facebook.com")
  .type("#email", "xxx") // starts typing in #firstname field
  .then(() => {
    console.log("!!!")
  })
```

With such setting 100% runs end filling the wrong field.
With other settings I observed random behavior for each run.
Sometimes it even was one character in one field and two subsequent in another field!

I believe this is somehow related to React but dunno who exactly.

**Comment by angus-c** [comment]
I'm also seeing this. When I have two inputs, no matter what selector I use, nightmare types into the second one. If I add a wait(200) it works.

Using Preact and nightmare 2.10

**Comment by casesandberg** [comment]
Are you still having trouble and have you tried 2.10.0? I am going to close this, but feel free to re-open if it's still an issue.

**Comment by matthewmueller** [comment]
Ran this about 10 times using this script and it seems to have been resolved:

```js
const Nightmare = require('nightmare')

main().catch(console.error)

async function main() {
  let nightmare = Nightmare({
    show: true,
    dock: true,
    openDevTools: {
      mode: 'detach'
    }
  })

  await nightmare.goto('http://facebook.com')
  await nightmare.type('#email', 'xxx') // starts typing in #firstname field

  await nightmare.end()
}
```
