### ISSUE TITLE
nightmare stucked after electron ended

### ISSUE THREAD

**Issue by flisky** [segmentio/nightmare#751]
version: 2.5.3

I run the program with the command `xvfb-run -a -s '-screen 0, 1024x768x24' node index.js`. At some time, it will be blocked in `wait` forever.

It turns out that electron process was died, and the debug log shows - 

```
electron:stderr [11982:0804/225110:ERROR:browser_main_parts.cc(126)] X IO error received (X server probably went away)
electron:stderr [12044:0804/225110:ERROR:x11_util.cc(89)] X IO error received (X server probably went away)
```

I'm curious how to capture this, so I can kill the main process? The supervisor, a process control system will restart  it for me. Thanks in advanced！

**Comment by rosshinkley** [comment]
Hm, try upgrading to 2.6.0, I think this may have been fixed by coincidence by fixing how Nightmare reacts to closing the Electron window.

If that doesn't solve it, it's possible a solution to #688 may fix your issue.

**Comment by flisky** [comment]
Will try it and keep you updated, thanks!

**Comment by Snake4life** [comment]
I cant confirm that my app is blocked in wait forever with latest 2.6.1 release

**Comment by flisky** [comment]
@Snake4life ,  you may give this code a try - 
```
nm.goto("...")
      .then(() => {
        nm.proc.on('close', (code) => {
          debug('electron process exited, kill myself...');
          process.exit(code);
        });
      });

```

**Comment by Snake4life** [comment]
thanks Im gonna try it out
