### ISSUE TITLE
Timeouts on `.evaluate`?

### ISSUE THREAD

**Issue by adityabansod** [segmentio/nightmare#759]
I am doing some browser automation and there are times where code I'm executing in the target page (e.g. an `.evaluate()`) dies.

Best I can tell there's no way to timeout waiting for an `.evaluate` to come back, so the entire nightmare queue/promise chain kinda just hangs until I notice and kill it.

Any suggestions?

My set up looks like:

```javascript
		.goto(urlBase + 'frmLogin.aspx')
		.type('#txtLoginName', username)
		.type('#txtPassword', password)
		.click('#btnLogin')
		.wait(function() {
			console.log('waiting for URL to become default.aspx');
			return window.location.href.includes('Default.aspx');
		})
		.evaluate(function() {
			// NOTE IT OFTEN DIES RIGHT HERE AS I NEVER
			// SEE THAT CONSOLE.LOG
			console.log('building base URL as', window.location.href.replace('Default.aspx', ''));
			return window.location.href.replace('Default.aspx', '');
		})
		.then(function(url) {
			logger.info('base URL built', url);
			self.options.urlBase = url;
			return callback();
		})
		.catch(function(e) {
			return callback(e);
		});
```

I've tried to wrap a `setTimeout` with a `throw` in the eval block, like so:
```javascript
.evaluate(function() {
	doTheThingWhichSometimesDoesntWorkButCasuesAPageNagivationWhenItWorks()
	setTimeout(function() {
		throw new Error('page hasnt navigated yet, so throwing');
	}, 10000);
})
```
but that doesn't always work, nor do I really want to do that in all my `.eval` blocks.

**Comment by adityabansod** [comment]
Another options/idea here would be to have a timeout on a `queue` so one could specify how long the entire set of queue'ed commands could run?

**Comment by GWP** [comment]
I'm having an identical problem, would love to know if anyone came up with a workaround. Right now I'm messing with splitting up the chain into steps and having a Promise.all after a certain amount of time to see if I can pinpoint an evaluate that never finishes.

**Comment by adityabansod** [comment]
@GWP this ended up solving the problem for me (as a workaround): https://github.com/segmentio/nightmare/issues/688#issuecomment-238473332

**Comment by rosshinkley** [comment]
FWIW, asynchronous evaluate is now possible with #819.

Between that and #688, I _think_ this is resolved.  Feel free to reopen/open a new issue if not.
