### ISSUE TITLE
Have done with Nightmare and Electron stuck and hangs

### ISSUE THREAD

**Issue by pkantsedalov** [segmentio/nightmare#760]
Hi everyone.

I've been working with Nightmare last 2 weeks in order to implement a crawler which works in this way:
we have a lot of links (~48k), split them on bunches (10-50 links per bunch) and run it in cycles. So in one cycle we have from 10 to 50 links => we have 10 - 50 Nightmare instances.
We decided to use Promise.all() in order to increase the speed of crawling by parallelizing. 
In each operation we have 3 steps:
1. first evaluation;
2. second evaluation;
3. ending.

And we use async/await for that. An example of our script which is executed in each cycle for each URL (and has its own Nightmare instances) looks like that:

``` javascript

try {
  let nightmare = (new Nightmare(options)).goto(url);

  // 1st eval
  let firstResult = await nightmare.evaluate(fn);

  // 2nd eval
  let secondResult = await nightmare.evaluate(fn)

  // ending
  await nightmare.end(); 

} catch (e) {
  // error handling
}
```

I ran my script a lot of times during that last 2 weeks and each time Nightmare stuck either on 1st eval or on the 2nd one. But I couldn't have the exact time or number of cycles after which my script will be stuck: depending on number of URLs I'm crawling in a cycle, it could be earlier or later. 

I started to log everything I could in order to debug such situation. I couldn't reproduce it quickly, so I waited as long as it was necessary. And at least I got a dump of Nightmare instance which was stuck, and I saw the next data inside it (dumped with [util.inspect](https://nodejs.org/api/util.html#util_util_inspect_object_options)):

``` javascript
Nightmare {
  ...
  proc: 
    ChildProcess {
      ...
      signalCode: 'SIGSEGV'
      ...
    }
}
```

Such signals aren't handled by Nightmare at all. And, by the way, not all signals could be handled by Node.js.
I started to dig into this problem. I found [this commit of Nightmare's 2.0.7 fork](https://github.com/fr-/nightmare/commit/c22b45c8a9d4e6712ba236e4c16761a44198ab59?diff=split), and it was helpful, but only in general (because of version), and I had to write the code on my own. And I decided to make [my own fork](https://github.com/sizewhiz/nightmare) where I started experiments with the problem.

Yesterday I successfully implemented and tested a fix for [almost all Ubuntu signals](http://manpages.ubuntu.com/manpages/precise/man1/kill.1.html). 
I simply ran my app, set some breakpoints and kill **electron** processes on each phase (1st eval, 2nd eval, end) with each of those signals. Only 1 signal - SIGSTOP - couldn't be handled, it means that `process.on('close', callback)` won't be invoked after that. Some signals are totally ignored by the electron and everything works fine. 
My fix is related to the **promises**, cause when you use async/await `then(fn)` method of Nightmare is invoked, and in my fix I invoke the **fn** you provided to this method as a callback in any case - even after unexpected closes. 

After my fix I ran my crawling script using my fork with the fix, and after a long time (35 URLs per cycle, 476 cycles, >4 hours) the stuck was reproduced. I saw the logs and there I found successful handlings of some signals (and so of unexpected closings of electron), but the stuck was reproduced, and I started to see Nightmare instances dumps. I have found that the stuck Nightmare instance had the next data inside it:

``` javascript
Nightmare {
  state: 'ready',
  running: false,
  ending: true,
  ended: true,
  ...
  proc: 
    ChildProcess {
      domain: null,
      _events: [Object],
      _eventsCount: 3,
      _maxListeners: undefined,
      _closesNeeded: 4,
      _closesGot: 0,
      connected: true,
      signalCode: null,
      exitCode: null,
      killed: true,
      ...
    }
}
```

While any other instance which was successfully ended had the next one:

``` javascript
Nightmare {
  state: 'ready',
  running: false,
  ending: true,
  ended: true,
  ...
  proc: 
    ChildProcess {
      domain: null,
      _events: {},
      _eventsCount: 0,
      _maxListeners: undefined,
      _closesNeeded: 4,
      _closesGot: 4,
      connected: false,
      signalCode: null,
      exitCode: 0,
      killed: true,
      ...
    }
}
```

Let's try to understand that:
- if an instance of Nightmare has `ending = true` it means that `.end(fn)` method of Nightmare was invoked (because such assignment is a first line of this method).
- if an instance of Nightmare has `ended = true` it means that `endInstance()` function inside nightmare.js is invoked where such assignment takes place and where an electron instance becomes killed and all its listeners are removed. 
- if `state = 'ready'` it means that the instance wasn't closed unexpectedly (because in my fix I set the value `'failed'` in such case).

As we see the main problem now is this one: **why an electron instance is simultaneously `killed` and `connected`?** And could we handle such situation in any way?

I've had an experimentation recently and I succeeded in reproducing the stuck. 
I did the next: I ran my script, in each cycle I crawl only 2 URLs instead of 10 - 50. I also set up some breakpoints. Then I sent **SIGSTOP** signal to one of those 2 - and after that my script stuck. 

The reason of stuck is the next. In Nightmare we have function  [evaluate_now(js_fn, done)](https://github.com/segmentio/nightmare/blob/master/lib/nightmare.js#L348) which is invoked after you use `evaluate(js_fn)`. As you see, there is a `done` callback, and if the electron process **stuck but not terminated, which is possible after it got SIGSTOP signal, the `done` callback will never be invoked. So your promise won't be resolved/rejected and the script will be stuck**.

So I decided to handle **SIGSTOP** too. [It's hard to do that, but possible](http://unix.stackexchange.com/a/298650). [Here](https://major.io/2009/06/15/two-great-signals-sigstop-and-sigcont/) and [here](http://blogofsiva.blogspot.com/2012/06/why-sigkill-and-sigstop-cannot-be.html) are good explanation too. 

As we see, the only way here - is to use an interval in order to check whether it was OK.
I've implemented such interval here and now it is under testing with 40 URLs in a cycle. 
By the way, I suggest I'm near the solution.

I think that this issue is related to [#751](https://github.com/segmentio/nightmare/issues/751), [#736](https://github.com/segmentio/nightmare/issues/736), [#688](https://github.com/segmentio/nightmare/issues/688), [#282](https://github.com/segmentio/nightmare/issues/282), [#238](https://github.com/segmentio/nightmare/issues/238).

I'm going to update this issue when the last script run with [this commit](https://github.com/sizewhiz/nightmare/commit/8c3572a0bf9b35feac142fd86dfec9fc29109d2d) will be ended.
So, let's discuss [my fork](https://github.com/sizewhiz/nightmare) here - it's for everyone who have ever had stuck/freeze/hang problems with Nightmare.

**Comment by adityabansod** [comment]
FYI, I've updated my nightmare code to use what was recommended in #688 which has helped quite a bit -- I haven't seen a hung nightmare in ~12/18 hours or so.

Would love to see your PR merged as I had opened #759 around a similar issue with less detailed analysis and no proposed fixes. :-).

Thanks!

**Comment by pkantsedalov** [comment]
Hi @adityabansod.
About [#688](https://github.com/segmentio/nightmare/issues/688): its OK only for orphaned electron processes which really could cause a leak, but my  crawler clears everything between cycles with
```js
child_process.exec ('kill all electron');
```
This code being wrapped in try...catch cleans everything fine. 
By the way, the proposed solution in #688 isn't OK due to the Nightmare's architecture, cause after `end()` invocation `disconnect` will be invoked too and electron can throw an exception about its repeated invocation of the `disconnect`.

In my case everything is about so called **zombie callback**.

**Comment by pkantsedalov** [comment]
After my latest experiments I've at least found that the problem described in [#688](https://github.com/segmentio/nightmare/issues/688) is really hard to solve without electron fix of orphan process. I think a sort of temporary solution could be a timer run in [.end()](https://github.com/segmentio/nightmare/blob/master/lib/nightmare.js#L370) method before [endInstance()](https://github.com/segmentio/nightmare/blob/master/lib/nightmare.js#L204) function invocation where we could check if after some time the process with `PID === this.proc.pid` or any of its orphans is alive - we need to kill it. There could be a parameter for that named like `killTimeout`

**Comment by matthewmueller** [comment]
Hi @pkantsedalov, are you still facing this issue? If so, I'd recommend taking a look at: https://github.com/segmentio/nightmare/issues/224#issuecomment-365938300

This script offers a robust way of running nightmare on Ubuntu, making sure stuff gets cleaned up after running. 

If you're still running into problems, please post your script so we can help you debug further. Thanks!
