### ISSUE TITLE
"Cannot read property 'blur' of null" on click

### ISSUE THREAD

**Issue by shanewignall** [segmentio/nightmare#762]
After doing a click on a button, this error is logged in the console, and nothing happens - the page just hangs. I'm wondering if this has something to do with the encoding on the page.. the button is a 'submit' form button from the Atlassian AUI framework. Any way to fix this issue?

**Comment by jhenriquez** [comment]
Interesting. I just started using the it and the same thin just happened to me. Unfortunately, I can't dig into it right now. But I'm afraid it is not related to clicking the button but, most likely the blur event fired by leaving the previous form field.

I don't know I'm only guessing. I'll continue to investigate, the API in this thing seems really cool, and Electron should be fine for my tests. 

The version I'm on is 2.6.1

**Comment by jhenriquez** [comment]
@shanewignall Quick update, yup. Just as I thought. In my case, the selector for the field was wrong. the querySelector was not matching anything. 

The interesting part is why it all the way in the blur event, and not in the while trying to put values in the element. Hope this helps you, too.

**Comment by shanewignall** [comment]
@jhenriquez Thanks for the info! I'll see if I can find the issue with  the previous field..

**Comment by shanewignall** [comment]
@jhenriquez so one of my issues was just having to use a 'wait' in a certain place. This allowed for the button to actually switch back to the parent form.. but then I still get the blur event error. After that happens, again, the script hangs. This is driving me nuts. The button that is clicked makes the form disappear, so the user sees the parent form, which is then focused on again. Why would it not be focusing back on the parent form like it should?

**Comment by jhenriquez** [comment]
@shanewignall Well, my use case was way simpler I'm afraid :sweat_smile: but then again I believe it seems to be similar in nature. In my case I was only filling a form and clicking submit. Yet, my field selectors where actually incorrect. So, my selectors were not returning any elements so when nightmare tried to move from field one, to let's say field two (calling blur() on field one) the result is this error.

In your case, I believe it might be similar. By disappearing, I suppose we're not talking about only _hiding_, if the markup is being removed this could render all selectors associated with that previous form invalid.

I would suggest you dig a little bit into the libraries code, and do a quick debug to try and identify which selector is being handled that doesn't bring any results at that particular moment in time. I think the stack trace indicates directly where to look in this case.

Hope this helps.

**Comment by rosshinkley** [comment]
`.click()` will blur the currently active element, which I'd _think_ should be the body if nothing has been selected.  From MDN:

> When there is no selection, the active element is the page's &lt;body&gt; or null. 

I know there are some OS differences with how this works, but I'd hope that Electron behaves the same across platforms.  I suppose it's possible AUI modifies this value, although it seems unlikely.  In any case, that's the only [`.blur()` call within `.click()`](https://github.com/segmentio/nightmare/blob/master/lib/actions.js#L88).

If you modify that line to check for the active element's existence first, do you still have this problem?

**Comment by shanewignall** [comment]
@rosshinkley Thanks for the response. I added a .wait('body') before and after the button click. Unfortunately, I still get the blur event about a second after the script clicks the button that makes the little inline-dialogue form disappear. I noticed that between clicking the button and the blur event error, a little banner appears and disappears on the page that just tells the user that the form was updated successfully. I wonder if this specific element disappearing and appearing causes a blur event? 

Also

@jhenriquez Looking back on your previous comment, I found that when I say the child form "disappears", the elements are actually dynamically removed from the page. This element is an inline-dialogue in the AUI framework. 
The thing is, I'm not trying to do anything with those elements after clicking the button to make the dialogue go away, so I _wouldn't think_ that this causes the issue..any thoughts?

**Comment by eddiesholl** [comment]
I've also been skewered by this, with a selector for a form field that didn't exist. The call to    document.activeElement.blur(); in the nightmare .click() handler sucked me in, assuming it was the culprit. It was a red herring, it was indeed an incorrect selector in a call to .insert() that caused it.

I'm dropping this here in case it helps anyone in the mean time, until/if/when a fix for the deeper issue (I assume at a deeper level) can be made.

**Comment by rosshinkley** [comment]
I did some digging with Chrome/Electron specifically: if you remove the active element from the DOM, the active element will point to the `body`.  The only way to get the active element to refer to null (at least in my experimentation) is to delete the `body` from the `html` tag.  (I sincerely doubt you're doing that.)

@willclarktech pointed out in [this issue](https://github.com/willclarktech/elm-boilerplate/issues/3) that the element could be removed between `.type()`/`.insert()` and `.blur()`, which would cause a similar problem, but those are getting the specific selectors, not the (somewhat nonspecific) active element.
