### ISSUE TITLE
How to make script continue flow after going to new page within .evaluate()

### ISSUE THREAD

**Issue by jelenajjo** [segmentio/nightmare#766]
Bellow is simple example that I am trying to make work, but no success. It don't have much sense and purpose. I am just trying to figure out how to make script go to some another page and then execute some function inside `.evaluate()` if possible. Or if can't be done inside `.evaluate()` , what is the way and best practice?

```
var Nightmare = require('nightmare');
var nightmare = Nightmare({
    show: true
});

nightmare

    .goto("https://www.google.com/")
    .type("input", "nightmare.js")
    .wait(3000)
    .click("button[type=submit]")
    .wait(2000)
    .evaluate(function() {
        var title = document.querySelectorAll("h3 a");
        i = 0;

        if (title.length > 0) {
            title[i].addEventListener("click", function() {
                setTimeout(function() {
                    that.click();
                    if ('a[href*=github]') {
                        document.querySelector('a[href*=github]').click();
                    }
                }, 5000);
            });
            title[i].click();
        }
    })

.then(function(result) {
        console.log("result", result);
    })
    .catch(function(error) {
        console.error('Search failed:', error);
    });
```

**Comment by rosshinkley** [comment]
Cross-site `.evaluate()` calls aren't going to work: the evaluated function is executed in the current page's context.  In other words, as soon as you `.click()` on one of those links, you'll lose your evaluation context.  Also, `.evaluate()` calls are currently designed to be synchronous, although there has been some work to make `.evaluate()` calls asynchronous (see #573).

Based on your snippet, I'm not clear on what you're trying to do: are you trying to click on each github link?

Also, as a matter of housekeeping, you _might_ want to take a look at [asynchronous operations and loops](https://github.com/rosshinkley/nightmare-examples/blob/master/docs/common-pitfalls/async-operations-loops.md).

**Comment by jelenajjo** [comment]
@rosshinkley  Thanks! :) [asynchronous operations and loops](https://github.com/rosshinkley/nightmare-examples/blob/master/docs/common-pitfalls/async-operations-loops.md) explanation helped me understand.

Script above is super basic, just to test this. Not much sense in there. :D

Thanks again!
