### ISSUE TITLE
Specific site throws error in Nightmare interaction code

### ISSUE THREAD

**Issue by scytalezero** [segmentio/nightmare#767]
At least that's what I think is happening. Here's a very simple snippet that works for most sites. For the login page below, however, Nightmare just hangs after the page renders:

```javascript
const nightmare = require("nightmare")({ show: true, width: 1000 })
nightmare
  .goto("https://vip.pet-records.com/users/sign_in")
  // .goto("https://www.google.com")
  .title()
  .end()
  .then(result => {
    console.log(result)
  })
```
If you open the console you can see a JS error:
```
Uncaught SyntaxError: Invalid regular expression: /^D:\Users\bcreel\Documents\_Projects\muninn\node_modules\electron-prebuilt\dist\resources\/: \ at end of pattern
```

Is this a problem in Nightmare or Electron? Is there anything I can do to work around it?

**Comment by rosshinkley** [comment]
This seems like a Windows-specific problem with Electron, but nothing is jumping out at me in the Electron repository (or `electron-prebuilt`, for that matter).  To be clear, the above works for the Google goto, but not the login?  What if you point it to a different version of `electron-prebuilt` with [`electronPath`](https://github.com/segmentio/nightmare#electronpath)?

**Comment by scytalezero** [comment]
I raised this issue with the Electron project. I'll either close or post more information here once I hear from them.

**Comment by rosshinkley** [comment]
Sorry for the delay, @scytalezero - yes, I'd go ahead and report it at Electron, which it looks like you've already done. :)

Would you mind linking to it here?

**Comment by scytalezero** [comment]
Sure! [Here is the issue.](https://github.com/electron/electron/issues/7071)

**Comment by scytalezero** [comment]
Someone from the Electron team has pointed out that the problem seems to be caused by a redefinition of String.prototype.startsWith() done by this specific site. So, bad on them, and I'm closing both issues. Thanks for your time on this.
