### ISSUE TITLE
Use Nightmare to control current webpage with webpack script

### ISSUE THREAD

**Issue by rkpatel33** [segmentio/nightmare#771]
Is it possible to user Nightmare with webpack to create a script that can be used for web automation tasks in a regular browser? I have poked around but not sure what the best approach is here.

Currently, I use a JQuery script bundled up using Webpack, but looking for an alternative.

**Comment by albinekb** [comment]
No, not possible. Nightmare works with electron (which exposes chrome APIs to node)
