### ISSUE TITLE
nightmare won't run without .then()

### ISSUE THREAD

**Issue by thewizarodofoz** [segmentio/nightmare#772]
It seems that nightmare is not running unless I chain a `.then()` (or other promise 'handler') at the end of the promises chain. I can see the actions get queued, but not ran.

Is this expected behaviour?

**Comment by noahtkeller** [comment]
That is not the expected behavior, can you post your code?

**Comment by thewizarodofoz** [comment]
code example:
```
var res = runScript();

function runScript() {
    this.nm = Nightmare();
    return nm.doSomething();
}

function doSomething() {
    return this.nm.goto('http://google.com');
}
```
This code doesn't run Nightmare, unless I change `runScript()` to `runScript().then(...)` (or put a `then()` after the last nightmare function in `doSomething()`.

**Comment by rosshinkley** [comment]
Yes, this is expected behavior.  Nightmare actions, as you noted, are queued but not run until `.then()` is executed.

**Comment by mateusz-no** [comment]
Wow, just lost 15 min trying to figure out why nightmare is not starting and exiting the script without any log. 😄
