### ISSUE TITLE
Execute with delayed return

### ISSUE THREAD

**Issue by caseygoodhew** [segmentio/nightmare#773]
Opening this issue to let you know about a new package that I've created that allows deferred returns against evaluates. We're using this so that we can test that ajax requests return valid data packages, but it could be used for any custom "waitUntil..." type of action.

https://www.npmjs.com/package/nightmare-evaluate-with-callback

**Comment by rosshinkley** [comment]
I was _really_ hoping to get something similar into core with #573.  If you want to pick that up and run with it, great - otherwise, I'm going to try to pick it up and submit a solution as time permits.

In the meantime, though, thank you.  This will help many outstanding problems.
