### ISSUE TITLE
Evaluate() vs end()

### ISSUE THREAD

**Issue by ChristosChristofidis** [segmentio/nightmare#774]
I have a loop containing a setTimeout inside the nightmare.evaluate function. It seems that there is a race condition where the nightmare.end() function executes faster than nightmare.evaluate. How can I prevent that from happening ? Note that I am not using multiple evaluates , all methods I use only once.

**Comment by rosshinkley** [comment]
`.evaluate()` is intended to be synchronous, at least for now.  I suspect that may be at least part of your problem.

There is a [plugin](https://www.npmjs.com/package/nightmare-evaluate-with-callback) that takes care of this, as well as an in-progess PR (#573) to try to address it.

**Comment by rosshinkley** [comment]
#819 should solve this problem.  Closing.
