### ISSUE TITLE
Add XPath support

### ISSUE THREAD

**Issue by gjmveloso** [segmentio/nightmare#775]
Hi,

I was thinking on how we can add XPath selectors support on nightmare.js and I'd tried the easy path - relying directly on ```$x()``` helper, available on Chrome. 

Not sure why it's not working within Electron/webContents.

Thoughts?

Thanks,
Gustavo

**Comment by rosshinkley** [comment]
According to the [Command Line API Reference](https://developers.google.com/web/tools/chrome-devtools/debug/command-line/command-line-reference):

> This API is only available from within the console itself. You cannot access the Command Line API from scripts on the page.

In other words, `$x()` isn't available from an evaluation context.

You could use `document.evaluate()`, it takes an XPath expression as an argument.  [MDN](https://developer.mozilla.org/en-US/docs/Introduction_to_using_XPath_in_JavaScript) has a good introduction on this topic.
