### ISSUE TITLE
Flipped arguments in`evaluate_now`

### ISSUE THREAD

**Issue by stevenvachon** [segmentio/nightmare#782]
`Nightmare.action()` does not work as I would've expected it to, where `done` is always the last argument.

``` js
Nightmare.action('iframeHeight', function(selector, done) {
  this.evaluate_now(function(selector) {
    //const element = document.querySelector(selector);
    //return window.getComputedStyle(element,null).getPropertyValue('height');
    return 100;
  }, selector, done);
});
```

``` js
it('works', function() {
  return browser.iframeHeight('#bigFrame').then(result => console.log(result))
  //return expect(browser.iframeHeight('#bigFrame')).to.eventually.equal(1000);
});
```

results in:

```
Nightmare runner error:

    TypeError: done is not a function
        at EventEmitter.response (/project/node_modules/nightmare/lib/runner.js:323:7)
```

After looking at [actions.js](https://github.com/segmentio/nightmare/blob/2.7.0/lib/actions.js#L55-L62), we can see that the args are backwards in `evaluate_now()`. The correct version would be:

``` js
Nightmare.action('iframeHeight', function(selector, done) {
  this.evaluate_now(function(selector) {
    const element = document.querySelector(selector);
    return window.getComputedStyle(element,null).getPropertyValue('height');
  }, done, selector);
});
```

**Comment by stevenvachon** [comment]
Ok, I figured it out. After looking at [actions.js](https://github.com/segmentio/nightmare/blob/2.7.0/lib/actions.js#L55-L62), we can see that the args are backwards in `evaluate_now()`. The correct version of my code is:
```js
Nightmare.action('iframeHeight', function(selector, done) {
  this.evaluate_now(function(selector) {
    const element = document.querySelector(selector);
    return window.getComputedStyle(element,null).getPropertyValue('height');
  }, done, selector);
});
```

**Comment by stevenvachon** [comment]
How can I define multiple arguments for `action()` ?
```js
Nightmare.action("broquire", function(id, browserValue, done)
{
	this.evaluate_now( function(id, browserValue)
	{
		//return window.broquire(id, browserValue);
		console.log(id, browserValue, done)
	}, done, id, browserValue);
});
```

This does not appear to be well documented.

**Comment by stevenvachon** [comment]
Optional arguments are even weirder:
```js
Nightmare.action("broquire", function(id, browserValue, done) {
    if (done === undefined) done = browserValue;  // nightmare.broquire(id)
    this.evaluate_now( function(id, browserValue) {
        return window.broquire(id, browserValue);
    }, done, id, browserValue);
});
```

**Comment by jeffijoe** [comment]
I also had to add a `return` for values to get passed back:

```
Nightmare.action('getText', function (selector, done) {
  return this.evaluate_now(function (selector) {
    return document.querySelector(selector).textContent
  }, done, selector)
})
```

**Comment by matthewmueller** [comment]
Yah I agree, `evaluate_now` is meant to be part of the private API so I didn't really consider it's DX, but later when we added actions, we needed to use it. My bad there.

We can't really change this now without needlessly breaking a bunch of existing actions, so I'm going to close.

**Comment by stevenvachon** [comment]
Should I be using a function other than `evaluate_now`?

**Comment by matthewmueller** [comment]
No, unfortunately you'll need to use `evaluate_now` for custom actions. 

The background is that `evaluate-now` was a private API before we had `Nightmare.action`, but then when we added `Nightmare.action`, we realized that you kind of need it. Now we have a silly API, that a bunch of custom actions depend on.

**Comment by stevenvachon** [comment]
Sounds to me like a breaking change is necessary.
