### ISSUE TITLE
How to intercept ajax responses?

### ISSUE THREAD

**Issue by barczaG** [segmentio/nightmare#784]
Hello,

Went through electron docs but it's still not obvious how to intercept all ajax responses? I would need something like: http://api.jquery.com/ajaxcomplete/

Thanks!

**Comment by d3ce1t** [comment]
I think you can do it by using 'did-get-response-details' event.

```
nightmare
      .goto(URL)
      .on('did-get-response-details', function(e, s, n, o, rc, rm, r, h, type) {
            console.log({url:n, type:type});}
        });
```

But I don't know if it's possible to read the actual response data.

More info:
- http://electron.atom.io/docs/api/web-contents/
- https://github.com/segmentio/nightmare/#onevent-callback

**Comment by rosshinkley** [comment]
For what it's worth, you could also capture it from preload using something like (from @nickstanish):

```js
  var open = window.XMLHttpRequest.prototype.open;
  window.__responses = [];
  window.XMLHttpRequest.prototype.open = function (method, url, async, user, pass) {
      this.addEventListener("readystatechange", function() {
        console.log('ready state %s is %s', url, this.readyState);
        if (this.readyState === 4) {
          window.__responses.push({
            responseText: this.responseText,
            readyState: this.readyState,
            url: url,
            method: method
          });
        }
      }, false);
    open.apply(this, arguments);
  };
```

**Comment by casesandberg** [comment]
Are you still having trouble and have you tried 2.10.0? I am going to close this, but feel free to re-open if it's still an issue.

**Comment by DPechacek** [comment]
@casesandberg I am also wondering this.  I have found no way to do this.  The library Sinon does not appear to work with nightmare.  And I see nothing in the nightmare API to allow you to mock ajax requests/responses.

**Comment by githubcyc** [comment]
i got a way to save the response data, url[]( https://docs.slimerjs.org/current/api/webpage.html#webpage-onresourcereceived),    but i wonder how can i solve this with nightmare or electron ???

**Comment by githubcyc** [comment]
i got a way to save the response data, [url,](https://docs.slimerjs.org/current/api/webpage.html#webpage-onresourcereceived) but i wonder how can i solve this with nightmare or electron ???

**Comment by matthewmueller** [comment]
Hi @githubcyc, I think you can use a custom action and Electron's [onBeforeRequest method](https://github.com/electron/electron/blob/master/docs/api/web-request.md#webrequestonbeforerequestfilter-listener)  to accomplish this. Here's an example for intercepting and disabling images:

```js
var Nightmare = require('nightmare')

main().catch(console.error)

async function main() {
  // define a new action
  Nightmare.action(
    'onBeforeRequest',
    //define the action to run inside Electron
    function(name, options, parent, win, renderer, done) {
      win.webContents.session.webRequest.onBeforeRequest((details, cb) => {
        // call our event handler
        parent.call('onBeforeRequest', details, res => {
          res ? cb(Object.assign({}, res)) : cb({ cancel: false })
        })
      })
      done()
    },
    function(handler, done) {
      // listen for "onBeforeRequest" events
      this.child.respondTo('onBeforeRequest', handler)
      done()
    }
  )

  const nightmare = Nightmare({ show: true })

  // start listening
  await nightmare.onBeforeRequest((details, cb) => {
    if (details.resourceType === 'image') {
      return cb({ cancel: true })
    }
    cb({ cancel: false })
  })

  await nightmare.goto('https://google.com')

  await nightmare.end()
}

function sleep(ms) {
  return new Promise(res => setTimeout(res, ms))
}
```

**Comment by mmsanalytics** [comment]
@matthewmueller Thanks for the last comment; very helpful for understanding the flow/parts. I'd like to modify the details.uploadData, but that doesn't appear to be an option in Electron's "onBeforeRequest" ... I am going to keep digging around the Electron manual, but I was wondering if you already had developed a way to do this that you could share. Thanks!
