### ISSUE TITLE
The clearCache example not working

### ISSUE THREAD

**Issue by rullyramanda** [segmentio/nightmare#789]
I tried the clearCache custom electron action example but not working, the script just hanged at the call of clearCache action, what could cause this? Thx

**Comment by vshvydky** [comment]
use nightmare.cookies.clearAll()
it's work

**Comment by rullyramanda** [comment]
So that function is also clear the browser (in this case Electron) cache? because what i want to achieve is to clear the browser cache not the cookies though.

**Comment by vshvydky** [comment]
//as an option, you can:

`
const
    Nightmare = require('nightmare'),
    vo = require('vo'),
    uuid = require('uuid'),
    rimraf = require('rimraf');

let myUuid = uuid.v1();

function * execute() {
    let nightmare = Nightmare({
        show: true,
        alwaysOnTop: false,
        paths: {
            userData: \`${__dirname}/browserData/${myUuid}/\`
        }
    });
    try {
        let html = yield nightmare.goto('https://www.google.com');
        console.log(html.code);
        return html.code;
    }
    catch (error) {
        throw error;
    }
    finally {
        yield nightmare.end();
        rimraf.sync(\`${__dirname}/browserData/${myUuid}/\`);
    }
}

vo(execute)
    .then(code=> {
        console.log(\`Code is: ${code}\`);
    })
    .catch(error=> {
        console.log('vo:execute:error: ', error);
    });
`

**Comment by vshvydky** [comment]
`//as an option, you can:

const
    Nightmare = require('nightmare'),
    vo = require('vo'),
    uuid = require('uuid'),
    rimraf = require('rimraf');

let myUuid = uuid.v1();

function * execute() {
    let nightmare = Nightmare({
        show: true,
        alwaysOnTop: false,
        paths: {
            userData: `${__dirname}/browserData/${myUuid}/`
        }
    });
    try {
        let html = yield nightmare.goto('https://www.google.com');
        console.log(html.code);
        return html.code;
    }
    catch (error) {
        throw error;
    }
    finally {
        yield nightmare.end();
        rimraf.sync(`${__dirname}/browserData/${myUuid}/`);
    }
}

vo(execute)
    .then(code=> {
        console.log(`Code is: ${code}`);
    })
    .catch(error=> {
        console.log('vo:execute:error: ', error);
    });`

**Comment by vshvydky** [comment]
`//as an option, you can:

const
    Nightmare = require('nightmare'),
    vo = require('vo'),
    uuid = require('uuid'),
    rimraf = require('rimraf');

let myUuid = uuid.v1();

function * execute() {
    let nightmare = Nightmare({
        show: true,
        alwaysOnTop: false,
        paths: {
            userData: __dirname+'/browserData/'+myUuid+'/'
        }
    });
    try {
        let html = yield nightmare.goto('https://www.google.com');
        console.log(html.code);
        return html.code;
    }
    catch (error) {
        throw error;
    }
    finally {
        yield nightmare.wait(1000);
        yield nightmare.end();
        rimraf.sync(__dirname+'/browserData/'+myUuid+'/');
    }
}

vo(execute)
    .then(code=> {
        console.log('Code is: ',code);
    })
    .catch(error=> {
        console.log('vo:execute:error: ', error);
    });`

**Comment by rullyramanda** [comment]
ok, thanks for the code i'll try to apply it in my code
