### ISSUE TITLE
If the page loads with a 404 no error is reported

### ISSUE THREAD

**Issue by justinmchase** [segmentio/nightmare#790]
I am loading a page and I have a bad path to a local script (which I can fix). But while I was debugging this problem my test was failing due to a wait timeout. It turned out that I was getting a 404 during the page load and I did not get any error messages despite attaching to the `'page'` and `'log'` functions.

What is the right way to detect 404's during page load?

**Comment by rosshinkley** [comment]
Non-200 codes are not treated as errors - pages that respond with non-200 codes might be expected behavior.

[`.goto()`'s return](https://github.com/segmentio/nightmare#gotourl-headers) will include metadata about the page load, including the response code.  A quick off-the-cuff example:

```js
var nightmare = require('nightmare')();
nightmare.goto('http://example.com/404')
  .then(function(gotoResult) {
    console.dir(gotoResult.code);
    return nightmare.end();
  })
  .then(()=>console.log('done'));
```

**Comment by justinmchase** [comment]
Perfect, thanks.

**Comment by Oted** [comment]
Im not sure this is clear in the documentation because it states
```
When a page load is successful, goto returns an object with metadata about the page load, including:
```
Maybe providing an example with this basic usage would make it easier to understand?

**Comment by rosshinkley** [comment]
Hm, I think I see what you're saying, @Oted.  The problem here is defining what a "load success" is.  Any page that completes the HTTP request - be it an HTTP success (eg, a 200) or an HTTP failure (eg, a 404) - is considered a successful request.  The documentation should be worded more carefully to make that clearer.
