### ISSUE TITLE
__nightmare is undefined at wellsfargo.com

### ISSUE THREAD

**Issue by drew-wallace** [segmentio/nightmare#791]
OS: Windows 10
node: 5.10.1
nightmare: 2.7.0
electron: electron-v1.3.6-win32-x64

Navigate to wells fargo and try to do anything.

``` javascript
var Nightmare = require('nightmare');
var nightmare = Nightmare({ show: true })

nightmare
   .goto('https://wellsfargo.com')
   .evaluate(function () {
      return "Made it";
   })
   .end()
   .then(function (result) {
      console.log(result)
   })
   .catch(function (error) {
      console.error('Login failed:', error);
   });
```

The electron window will come up with wellsfargo.com loaded and do nothing.
Open the console and you will see two errors, both saying `__nightmare is not defined`

I tested the yahoo search example and it worked fine. My guess is that it's forgetting the injection that happened.

Further investigation:
If you inspect the `window` object you will notice `__nighmare` no longer exists under `window.__nightmare`, it is now under `window[""].nightmare`

**Comment by drew-wallace** [comment]
I changed both of the ipc declarations in javascript.js to:
```javascript
var ipc = (window.__nightmare ? __nightmare.ipc : window[''].nightmare.ipc);
```
And it works now.

**Comment by drew-wallace** [comment]
Making a PR...

**Comment by 1mike12** [comment]
huh, _5300_WellsFargoEmployees also returns undefined

**Comment by reinpk** [comment]
merged PR
