### ISSUE TITLE
Errors after tests passed

### ISSUE THREAD

**Issue by erisnuts** [segmentio/nightmare#802]
I have two randomly appearing errors after tests passed:

![screenshot-6](https://cloud.githubusercontent.com/assets/3906376/18780021/047799dc-8195-11e6-8849-4c32ed47eb97.png)

![screenshot-5](https://cloud.githubusercontent.com/assets/3906376/18780019/00ce95d8-8195-11e6-8d2f-b94e7b449956.png)

Any advice, what do I doing wrong?

Basically tests are look like this:
`describe('Homepage', () => {

  it('returns code 200', () => (

```
new Nightmare()

  .goto(SITE_URL)

  .then((result) => {

    expect(result.code).toEqual(200);

  }, () => {

  })
```

  ));

});`

But I've got a problems described and solved at ["Electron instances not destroyed #688"](https://github.com/segmentio/nightmare/issues/688)
So, I've added this code: 
`      .then(() => {

```
    nightmare.end();

    nightmare.proc.disconnect();

    nightmare.proc.kill();

    nightmare.ended = true;

    nightmare = null;

  });`
```

It didn't helped.

**Comment by daniel3d** [comment]
Can you share the full test how do you access nightmare variable in the .then() function? and what is the problem you are trying to solve by using this nightmare.end(); ......

**Comment by casesandberg** [comment]
Are you still having trouble and have you tried 2.10.0? I am going to close this, but feel free to re-open if it's still an issue.
