### ISSUE TITLE
Example doesn't work at all

### ISSUE THREAD

**Issue by spoike** [segmentio/nightmare#803]
Trying to work through the example. But nothing really happens and it appears the Electron process never really starts judging by the debug output.

File:
```javascript
const Nightmare = require('nightmare');
const nm = Nightmare({show: true});

nm
    .goto('http://yahoo.com')
    .type('input[title="Search"]', 'github nightmare')
    .click('.searchsubmit');
```

This is the DEBUG output:
```sh
$ DEBUG=* node index.js
  nightmare queuing process start +0ms
  nightmare queueing action "goto" for http://yahoo.com +2ms
  nightmare queueing action "type" +2ms
  nightmare queueing action "click" +0ms
  nightmare electron child process not started yet, skipping kill. +1ms
```

I'm running with the following:
* MacBook Pro with OS X El Capitan (`10.11.6`)
* Node `6.3.1`, npm `3.10.3` (installed through nvm `0.29.0`)

Same happens on nightmare versions `2.6.1` and `2.7.0`.

**Comment by spoike** [comment]
I just realized the error. Nightmare doesn't run anything until you execute the run with:

* `yield`ing the chain (which needs to be inside a generator function)
* having a `.run()` at the end of the chain
* using `.then()` at the end of the chain

**Comment by sol-invictus481** [comment]
> - `yield`ing the chain (which needs to be inside a generator function)
> - having a `.run()` at the end of the chain
> - using `.then()` at the end of the chain

This should go in the API docs in my opinion
