### ISSUE TITLE
How to handle new window?

### ISSUE THREAD

**Issue by overflowz** [segmentio/nightmare#804]
I need to access new window from nightmare and manipulate it as I do in main window. Is that even possible?

```
nightmare
  .goto('http://website.com/')
  .click('button[id="mybutton"]') // this actually opens new window/tab whatever.
  .type('input[type="text"]', 'hello world') // I want this to happen on new window, how?
  .then(function () { console.log('all done'); })
  .catch(function (err) { console.log(err); });
```

basic html:

```
<button id="mybutton" onclick="javascript:window.open('http://website.com/', '_blank');">click me</button>
<input type="text"></input>
```

EDIT: Don't get me wrong, I've searched same questions here, but isn't there any workaround? If not, can I just block opening new window and load the new page into the current one?

EDIT2: I've noticed, that if you specify `show: false` opening new tab/window is shown by default. Any thoughts about this? It's getting annoying though.

**Comment by rosshinkley** [comment]
Out of the box? no.  Dealing with multiple instances of `BrowserWindow` isn't currently supported in Nightmare.  (Memory serving, it's one of the features talked about for a future version in #593.)

You can _kind_ of skirt this issue now, but it depends largely on what you need.  I'd suggest checking out [`nightmare-window-manager`](https://github.com/rosshinkley/nightmare-window-manager).  It's limited, but might be enough to help you skate by.

**Comment by overflowz** [comment]
Thanks for the reply! I've tried nightmare-window-manager too, but still I'm facing second issue. no matter if I specify `show: false` new window always opens up visible.

**Comment by rosshinkley** [comment]
Moving this to nightmare-window-manager.
