### ISSUE TITLE
Best ways to boost loading pages

### ISSUE THREAD

**Issue by jonatasfreitasv** [segmentio/nightmare#805]
Hi guys,
why the way to loading/render pages more fast ? Have parameters for this ?

thx a lot.

**Comment by rosshinkley** [comment]
That depends on what you mean.  If you've got assets - large images, for example - you could tap into `session.webRequest.onBeforeRequest()` to filter content that could slow your load process down.  There's a [plugin that you might find useful](https://github.com/rosshinkley/nightmare-load-filter) that does this.

As for speeding up the actual rendering process, that's internal to Chromium - I don't know of options offhand, but the [`BrowserWindow`](https://github.com/electron/electron/blob/master/docs/api/browser-window.md) documentation and perhaps the [Chromium switch list](http://peter.sh/experiments/chromium-command-line-switches/) (for use with [`switches`](https://github.com/segmentio/nightmare#switches)) might offer some options for you to tinker with.

**Comment by jonatasfreitasv** [comment]
Thx a lot @rosshinkley
