### ISSUE TITLE
Variables attached to window

### ISSUE THREAD

**Issue by marcelfalliere** [segmentio/nightmare#806]
I am using nightmare.js (awesome work by the way) to detect variables attached to the window object by some script.

So the setup is pretty basic. I have a web server serving a simple html file. Notice the `var beforeKeys = Object.keys(window)`

**thepage.html**

```
<!DOCTYPE html>
<html>
  <head>
  </head>
  <body>
  </body>
  <script>
    var beforeKeys = Object.keys(window);
  </script>
</html>

```

The way this page is used, with nightmare, is like so :

```
  var n = Nightmare();
  n.on('console', function(type, arg0, arg1){
    if (arg0 == 'windowVariablesDifferences') {
      // this is where the wtf happens
    }
  })
  .goto('http://localhost:1986/thepage.html')
  .inject('js', scriptPath)
```

The injected scripts, at `scriptPath`, looks like this :

```
var foo, foo2, foo3,
    bar = 0;

function init() {

  foo = new SOMECLASS();
  // ...

  foo2 = new SOOOOMECLASS();
  // ...

  foo3 = new SOMECLASSYCLASS();
  // ...

  qux = new SOMEOTHERCLASS();
  //

}

init();

console.log("windowVariablesDifferences", Object.keys(window).filter(function(i){ return beforeKeys.indexOf(i) < 0 }))

```

So to translate this code into what it does :
- nightmare loads thepage.html
- the `beforeKeys` variable holds the keys of the window object
- nightmare injects the scripts
- the scripts does its stuff
- at the end, it logs the difference between the keys before the script and after the script

So the difference **should be** an array containing `["foo", "foo2", "foo3", "bar", "qux"]`. 

**But it is not**. It is an array containing `["bar", "qux"]`

Something to consider : when I test this in a classic web browser (let's say Google Chrome) I get the expected result. I use the same content but with a one line addition for `<script src="scriptPath.js"></script>`, just before the `</html>`.

Weird ? Or am I missing something ? The test case is of course pruned from the actual work done here... but the idea is here.

**Comment by rosshinkley** [comment]
Hm, are any of the variables you're testing for defined on the global/window scope _before_ your injection?  I can recreate this behavior if the variables are defined prior to `.inject()`, as then they would already exist on the global scope.

It's worth pointing out that your consideration is not exactly the same thing as the test you've written.  In your test, the `init()` function is injected after the page is loaded, whereas in your consideration example, they are loaded together.  It's a small difference, and I don't _think_ it would be causing this, but it's worth thinking about.
