### ISSUE TITLE
how to clear input field value before typing/inserting? 

### ISSUE THREAD

**Issue by typekpb** [segmentio/nightmare#810]
I'm in a situation, that on script re-run are previously inserted input fields prefilled with old values.
So calling:

```
.insert('input#foo', 'zzz')
```

or

```
.type('input#foo', 'zzz')
```

makes the value to be appended only.
Any chance to overwrite?
Currently I'm workarounding it with:

```
.evaluate(function() {
    document.querySelector('input#foo').value = 'zzz'
    })
```

**Comment by marcelfalliere** [comment]
I think this is the desired behaviour. Following the philosophy of that, maybe you should try to insert backspace characters.

**Comment by typekpb** [comment]
@marcelfalliere OK you're right, what works for me is to do:

	.evaluate(function() {
	    document.querySelector('input#foo').value = ''
	})
	.insert('input#foo', 'zzz')

however it could be handy to have some API way to do that, either some boolean flag for replace, or some clear method.

**Comment by rosshinkley** [comment]
In addition to sending backspace characters as @marcelfalliere said, you can send empty or falsey values to `.type()` and `.insert()` to clear the selector.

I do have a question:

> ...on script re-run are previously inserted input fields prefilled with old values.

Meaning that the values are there between runs to the same site?

**Comment by typekpb** [comment]
@rosshinkley 

> I do have a question:

>>    ...on script re-run are previously inserted input fields prefilled with old values.

> Meaning that the values are there between runs to the same site?

correct

**Comment by kwnccc** [comment]
@rosshinkley I'm passing either empty or falsy values for text and none of these seems to clear the input value?

**Comment by StefanRoess** [comment]
I have a frame item, like:
 const fi_customer = await frame.$('#fi_customer');
 await fi_customer .type('Customer_Name', {delay: 20});

How can i clear the value for fi_customer before i fill in a new value of 'Customer_Name'.
Currently the values will appended like, 'Customer_NameCustomer_NameCustomer_NameCustomer_Name' etc.

Any suggestions.

**Comment by simov** [comment]
Just FYI in 0.13 this clears the input text:
```js
await page.evaluate(() => {
  document.querySelector('...').value = ''
})
```

However you may have to trigger the appropriate event to update the internal state of your app:

```js
await page.evaluate(() => {
  document.querySelector('...').value = ''
  document.querySelector('...')
    .dispatchEvent(new Event('change', {bubbles: true}))
})
```

**Comment by MichaelMartinez** [comment]
The method provided by @simov doesn't work for me... I have to resort to using 

    `await page.keyboard.press('Backspace');`

To clear a text box... seems like `xxx.clear()` would be super awesome and a pretty standard use case???

**Comment by Mihlyuk** [comment]
When I press Ctrl+A, all the page content is highlighted. And using click at some point can cause double click, so I use:
`
const elementHandle = await page.$('.id');
await elementHandle.focus();

// Move the carriage to the right
await page.keyboard.down('Control');
await page.keyboard.press('ArrowRight');
await page.keyboard.up('Control');

// Select text to the left of the caret
await page.keyboard.down('Control');
await page.keyboard.down('ShiftLeft');
await page.keyboard.press('ArrowLeft');
await page.keyboard.up('ShiftLeft');
await page.keyboard.up('Control');

await page.keyboard.press('Backspace');
`

**Comment by mikrstic** [comment]
Why not simply:


```
await page.click("input[name=email]", {clickCount: 3})
await page.type("input[name=email]", "some@email.com")
```

Select everything by clicking 3 times and then just start typing, it will replace the selected text.

**Comment by tuancaraballo** [comment]
This is what I ended up doing: a combination of @mikrstic and @MichaelMartinez 

`  await page.click("input[name=email]", {clickCount: 3})
    await page.keyboard.press('Backspace')
`
this worked for me.

**Comment by lukewlms** [comment]
Triple-click seems to only select current para, so that solution fails with a multi-para text input.

@tuancaraballo Backspace solution works for me.

**Comment by Legends** [comment]
What's the difference when doing this:

`await page.evaluate(selector => {document.querySelector(selector).value = "";}, selector);`

**Comment by nkpz** [comment]
Keep in mind that `el.setSelectionRange(0, el.value.length)` will not work for certain types of inputs. In my case it was an email input. Went with a triple-click.

**Comment by maheshtekawade95** [comment]
how can i clear multiple values from input box using playwright?
