### ISSUE TITLE
Cannot open Multi Electron window !

### ISSUE THREAD

**Issue by truthtaicom** [segmentio/nightmare#811]
I want to open new windows for each instance nightmare.

Eg:
```
const Nightmare = require('nightmare');
var nightmare = Nightmare({
    show: true,
    waitTimeout: 60000
});

const goTo = (url) => {
    nightmare.goto(url)
        .title()
        .then(function (title) {
            console.log(title);
        });
}

goTo('http://example.com');  // #1
goTo('https://github.com'); // #2
goTo('https://gitlab.com'); // #3
```

Resut :
`Example Domain`

I want to expected result as async:
`GitHub`
`Example Domain`
`GitLab`

Can you help me? Thank you~

**Comment by HarrisRobin** [comment]
@truthtaicom you will need to make new instances of nightmare

So for example, you can have 

```
var nightmare = Nightmare({
    show: true,
    waitTimeout: 60000
});
```

```
var nightmare_gitlab = Nightmare({
    show: true,
    waitTimeout: 60000
});
```

etc...

**Comment by gilbert** [comment]
@HarrisRobin I tried this approach, but the second instance never loads (it does open a new window, though). Any ideas?
