### ISSUE TITLE
docs: introduce available plugins list

### ISSUE THREAD

**Issue by typekpb** [segmentio/nightmare#812]
Since there is a support for plugins implemented, it would be nice to have a list of available ones.
Initially a list of plugins with short description (and as a bonus with github stars count) could serve well.

**Comment by casesandberg** [comment]
Would you be willing to open a PR for this? Looks like there is a handful here: https://github.com/search?utf8=%E2%9C%93&q=nightmare+plugin&type=

**Comment by casesandberg** [comment]
I am going to close this, but feel free to open up a PR if you would like to see it happen.
