### ISSUE TITLE
Get Image from Electron Cache

### ISSUE THREAD

**Issue by ak5** [segmentio/nightmare#823]
I have an image that changes on every download that is downloaded by electron (I can see it in the browser window). Is there any way to programmatically access this image without redownloading it?

Thanks!

**Comment by efernandesng** [comment]
I don't know a direct way to access to cached file, but you can use [screenshotpath-clip](https://github.com/segmentio/nightmare#screenshotpath-clip)

Check #107 for discussion.

**Comment by ak5** [comment]
Hey thanks, this seems like a doable workaround, it would be nicer to get the image from the cache though (it's there somewhere, no?) I'll play with this later today though, thanks!

**Comment by avimar** [comment]
See also the PR & plugin listed here: https://github.com/segmentio/nightmare/pull/358
