### ISSUE TITLE
Does Nightmare use PhantomJS?

### ISSUE THREAD

**Issue by danielnieto** [segmentio/nightmare#826]
I'm confused, on some places I've found it uses Electron and in others it says it's a wrapper for PhantomJS... what's correct?

**Comment by amokan** [comment]
It uses Electron.

**Comment by jgrancher** [comment]
Nightmare used to use PhantomJS under the hood before the release of the v2, when it switched to Electron.
You can use the old [1.8.2 version](https://github.com/segmentio/nightmare/tree/1.8.2) if you want to use Phantom instead.

**Comment by danielnieto** [comment]
Thank you
