### ISSUE TITLE
HTTPs requests are not proxy-ed 

### ISSUE THREAD

**Issue by IonicaBizau** [segmentio/nightmare#829]
How can I proxy the HTTPs requests?

https://github.com/electron/electron/issues/7564

**Comment by rosshinkley** [comment]
I'm not sure what you're asking here - are you asking how to set up a proxy?  Or what proxy to use?  

For the latter, [`node-http-proxy`](https://github.com/nodejitsu/node-http-proxy) is a good place to start.

**Comment by IonicaBizau** [comment]
I did check that out but it doesn't allow me to modify the content from response. 

I'm wondering if it's possible to proxy the https requests and change the content of the responses for specific urls.

**Comment by rosshinkley** [comment]
Hm, You could probably use a similar approach to #521 to patch request data coming back - does that help, or are you trying to modify data from `.goto()`?

**Comment by IonicaBizau** [comment]
@rosshinkley I was trying to modify the content of a script served over HTTPs. Still, I don't really have a solution for this, but I found a workaround for my case.

Would be curious how do modify that, tho.

**Comment by mashaalmemon** [comment]
Hi There,

I am having the same issue.  It appears that that proxy feature works for 'http' requests but not for 'https' requests through the same proxy. I am using a proxy service where I know I am able to, when using curl, visit both 'https' and 'http' pages through the same proxy.

However with this simple code which is similar to the examples given in the API readme:

```ts
import Nightmare = require('nightmare');

let nightmare = new Nightmare(<any>{
    switches: {
        'ignore-certificate-errors': true,errors
        'proxy-server': '<proxy host>:<proxy port>;'
    },
    show: true,
});

let url = 'https://www.google.ca/';

nightmare = nightmare
    .authentication('<proxy user>', '<proxy pass>')
    .goto(url)
    .end()
    .then(function(ip:string) {
        console.log('proxy IP', ip);
    },
    function (err:Error)
    {
        console.log('error %s, details: %s', err.message, err.details);
    });
```

I get the following results when `DEBUG=*`:

```ts

  nightmare queuing process start +0ms
  nightmare queueing action "authentication" +4ms
  nightmare queueing action "goto" for https://www.google.ca/ +2ms
  nightmare running +1ms
  nightmare:actions .authentication() +427ms
  nightmare:log Navigating: "https://www.google.ca/",
            headers: [none],
            timeout: 30000 +10ms
  nightmare:log did-start-loading +65ms [{}]
did-start-loading: {}, undefined, undefined, undefined, undefined, undefined, undefined
  nightmare:log did-fail-provisional-load +507ms [{},-323,"ERR_UNEXPECTED_PROXY_AUTH","https://www.google.ca/",true]
certificate-error: {}, -323, ERR_UNEXPECTED_PROXY_AUTH, https://www.google.ca/, true, undefined, undefined
  nightmare:log did-fail-load +2ms [{},-323,"ERR_UNEXPECTED_PROXY_AUTH","https://www.google.ca/",true]
  nightmare electron child process exited with code 0: success! +91ms
error navigation error, details: ERR_UNEXPECTED_PROXY_AUTH

Process finished with exit code 0

```

Any idea what might be happening here? Clearly the authentication is given and works with 'http' urls but not with 'https' urls. 

I suspect, maybe, the authentication is not getting through as the connection is encrypted but I'm not sure how to resolve this issue? Or I am missing something very obvious.

**Comment by mashaalmemon** [comment]
It is interesting to compare the output from the failed attempt to access an 'https' page vs a successful attempt to access an 'http' page:

'''
/Users/mashaal/.nvm/versions/node/v6.2.2/bin/node /Users/mashaal/Projects/kyosk-server-web/dev/sandbox/proxy_service.sandbox.js
  nightmare queuing process start +0ms
  nightmare queueing action "authentication" +8ms
  nightmare queueing action "goto" for http://www.google.ca/ +5ms
  nightmare running +2ms
  nightmare:actions .authentication() +588ms
  electron:stdout login listener added +36ms
  nightmare:log Navigating: "http://www.google.ca/",
            headers: [none],
            timeout: 30000 +14ms
  nightmare:log did-start-loading +69ms [{}]
  nightmare:log authenticating against http://www.google.ca/, try #1 +323ms
  nightmare:log did-get-redirect-request +328ms 
  ...

Process finished with exit code 0
'''

You'll notice from debugging output that authentication (or the 'loginListener' set in the nightmare.js runner) is executed after 'did-start-loading' whereas in the failed example the login listener is not called.

I've ruled out a certificate problem.

Now I'm trying to track down where the 'ERR_UNEXPECTED_PROXY_AUTH' error might originate from. Any feedback or knowledge that might point me in the right direction would be extremely helpful.

**Comment by matthewmueller** [comment]
Hi @mashaalmemon, were you able to resolve this issue? 

I'm not sure about the proxy server you were using, but `nightmare.authentication` is only for Basic Auth (e.g. `user:pass@server.com`). Is that how authentication works for the proxy server?

**Comment by matthewmueller** [comment]
Going to close this since this issue is getting stale. Please feel free to reopen if you're still running into this problem and have more information for us :-)

**Comment by davidsielert** [comment]
Getting the same issue here myself, definitely related but should create new issue?
