### ISSUE TITLE
how can i pass a function in parameter of .evaluate

### ISSUE THREAD

**Issue by neutron92** [segmentio/nightmare#832]
how can i pass a function in parameter of .evaluate  allways i have null

puu.sh/rHtgK/89af757a71.png

i want to scrape a website and every data collected saved in mongo no return in the .evaluate
any one can help me

**Comment by rosshinkley** [comment]
To be clear: are you trying to pass an actual function to evaluate?  Something like:

```js
var myfn = function() { ... };
nightmare
  .goto(myUrl)
  .evaluate(fn=>{ fn(); }, fn)
  .then( ... )
```

**Comment by cagataycali** [comment]
I'm trying the same, 

```javascript
var name = "demo.png";
var url = "https://demoUrl.com"

nightmare
  .downloadManager()
  .goto('https://google.com')
  .evaluate((name, url) => {
    console.log(name, url);
    return 'Done'
  })
```

That result will undefined

**Comment by entrptaher** [comment]
@cagataycali, maybe thats not the problem you are trying to solve. If you are trying to use download manager, then probably you should try their example first.

```js
var Nightmare = require('nightmare');
require('nightmare-download-manager')(Nightmare);
var nightmare = Nightmare();
nightmare.on('download', function(state, downloadItem){
  if(state == 'started'){
    nightmare.emit('download', '/some/path/file.zip', downloadItem);
  }
});
 
nightmare
  .downloadManager()
  .goto('https://github.com/segmentio/nightmare')
  .click('a[href="/segmentio/nightmare/archive/master.zip"]')
  .waitDownloadsComplete()
  .then(() => {
    console.log('done');
  })
```

If you want to pass something to evaluate, you have to pass it as @rosshinkley showed above.
But, from your example, it's not exactly clear what are you trying to do.
The actual code might be more helpful.

**Comment by rosshinkley** [comment]
@cagataycali In addition, you're not passing values to `.evaluate()` to print.  From the hip, this should work:
```js
var name = "demo.png";
var url = "https://demoUrl.com"

nightmare
  .downloadManager()
  .goto('https://google.com')
  .evaluate((name, url) => {
    console.log(name, url);
    return 'Done'
  }, "name", "url")
```

You may want to give [variable lifting](https://github.com/rosshinkley/nightmare-examples/blob/master/docs/common-pitfalls/variable-lifting.md) a read.

Going to close this due to age and I think possibly being solved.

**Comment by anthnyprschka** [comment]
Hi there,
I am actually trying to pass a function as a paramter to .evaluate(). Pretty much like your example:

```
var myfn = function() { ... };
nightmare
  .goto(myUrl)
  .evaluate(fn=>{ fn(); }, myfn)
  .then( ... )
```

Yet if i do this I get the error: `myfn is not a function`.

Is it possible to pass functions as parameters?

**Comment by Zhou-Bill** [comment]
@anthnyprschka i has the same case, are you has solved

**Comment by nurettin** [comment]
I don't think you can pass functions into evaluate, only values. If you want your functions to be available within the browser's page context (that is where evaluate works) you need to .inject your function and all it's dependencies into the page itself. So get your function, compile it with all it's dependencies, inject the resulting javascript file as if you are using it for frontend. 

For a lot of purposes this will work.
