### ISSUE TITLE
electron-prebuilt has been renamed to electron

### ISSUE THREAD

**Issue by xcarpentier** [segmentio/nightmare#833]
npm WARN deprecated electron-prebuilt@1.4.3: electron-prebuilt has been renamed to electron. For more details, see http://electron.atom.io/blog/2016/08/16/npm-install-electron

**Comment by SnakeO** [comment]
What's a good workaround for getting this to work -- can we make a change in package.json?

**Comment by TechplexEngineer** [comment]
I think this was fixed here https://github.com/segmentio/nightmare/commit/68b40a8ea605997ac4f38ca75b0db0bbca76f708

**Comment by xcarpentier** [comment]
Cool thanks !
