### ISSUE TITLE
also emit the URL on page events

### ISSUE THREAD

**Issue by justinjmoses** [segmentio/nightmare#834]
I'm using nightmare to navigate between various pages and log page errors. Due to the asynchronous nature of `url().then()` I need a way to get the URL at the time of the page error. Would something like this be acceptable?

https://github.com/segmentio/nightmare/compare/master...justinjmoses:master

If so, I'd be happy to write up a PR with test coverage.

**Comment by rosshinkley** [comment]
I can't think of a reason to not include it off the top of my head, and the change is pretty innocuous.  If you're willing to pull together the PR + tests, I'd say go for it. :)

**Comment by justinjmoses** [comment]
It's looking like it doesn't fix the problem. I played with some edge cases and it seems possible that the electron browser has moved on to a new URL by the time the event is handled. I need to dig deeper to find a thorough solution.

**Comment by rosshinkley** [comment]
Ah, I think I misunderstood the problem you're trying to solve.  You're after something blocking, I take it?  That's trickier, but there are a couple of options.  You could manually block using `.wait()`, which would solve your asynchronicity problem.  Or if you really want to get crazy, you could take a look at implementing a soft-blocking action to wait for your page errors, akin to how [`nightmare-inline-download`](https://github.com/rosshinkley/nightmare-inline-download/) works.

**Comment by justinjmoses** [comment]
Actually I don't want to block per se. I'm happy for nightmare to continue it's merry way, I'd just like to make sure I know where the error came from, even if nightmare is moving on to another page already.

**Comment by casesandberg** [comment]
Are you still having trouble and have you tried 2.10.0? I am going to close this, but feel free to open a new issue if you are still having problems.
