### ISSUE TITLE
Nightmare crashes on Heroku without an error

### ISSUE THREAD

**Issue by jussch** [segmentio/nightmare#836]
I've jumped through most of the hoops to get NightmareJS setup on Heroku. It renders most images fine like it does in my local Windows environment. The problem only arises when I load MathJax into an instance of Nightmare on Heroku. Nightmare appears to load the files just fine, but then just crashes.

With `debug=*` on, my output looks like this:
```
Tue, 18 Oct 2016 20:24:07 GMT nightmare queueing action "goto" for file:///app/server/app/nightmareRender/templates/blank.html
Tue, 18 Oct 2016 20:24:07 GMT nightmare queueing action "viewport"
Tue, 18 Oct 2016 20:24:07 GMT nightmare queueing action "evaluate"
 Tue, 18 Oct 2016 20:24:07 GMT nightmare queueing action "inject"
Tue, 18 Oct 2016 20:24:07 GMT nightmare queueing action "inject"
Tue, 18 Oct 2016 20:24:07 GMT nightmare queueing action "inject"
Tue, 18 Oct 2016 20:24:07 GMT nightmare queueing action "inject"
Tue, 18 Oct 2016 20:24:07 GMT nightmare queueing action "evaluate"
Tue, 18 Oct 2016 20:24:07 GMT nightmare queueing action "wait"
Tue, 18 Oct 2016 20:24:07 GMT nightmare queueing action "screenshot"
Tue, 18 Oct 2016 20:24:07 GMT nightmare running
Tue, 18 Oct 2016 20:24:07 GMT electron:stderr Xlib:  extension "RANDR" missing on display ":99".
Tue, 18 Oct 2016 20:24:08 GMT electron:stderr Xlib:  extension "RANDR" missing on display ":99".
Tue, 18 Oct 2016 20:24:08 GMT nightmare:log Navigating: "file:///app/server/app/nightmareRender/templates/blank.html",
            headers: [none],
            timeout: 30000
ue, 18 Oct 2016 20:24:08 GMT nightmare:log did-start-loading [{}]
Tue, 18 Oct 2016 20:24:08 GMT nightmare:log did-get-response-details [{},true,"file:///app/server/app/nightmareRender/templates/blank.html","file:///app/server/app/nightmareRender/templates/blank.html",200,"GET","",{"access-control-allow-origin":["*"]},"mainFrame"]
Tue, 18 Oct 2016 20:24:08 GMT nightmare:log dom-ready [{}]
Tue, 18 Oct 2016 20:24:08 GMT nightmare:log did-frame-finish-load [{},true]
Tue, 18 Oct 2016 20:24:08 GMT nightmare:log did-finish-load [{}]
Tue, 18 Oct 2016 20:24:08 GMT nightmare:log did-stop-loading [{}]
Tue, 18 Oct 2016 20:24:08 GMT nightmare:actions .viewport()
Tue, 18 Oct 2016 20:24:08 GMT nightmare:actions .evaluate() fn on the page
Tue, 18 Oct 2016 20:24:09 GMT nightmare:actions .inject()-ing a file
Tue, 18 Oct 2016 20:24:09 GMT nightmare:actions .inject()-ing a file
Tue, 18 Oct 2016 20:24:09 GMT nightmare:actions .inject()-ing a file
Tue, 18 Oct 2016 20:24:09 GMT nightmare:actions .inject()-ing a file
Tue, 18 Oct 2016 20:24:09 GMT nightmare:actions .evaluate() fn on the page
Tue, 18 Oct 2016 20:24:09 GMT nightmare:actions .wait() for fn
Tue, 18 Oct 2016 20:24:09 GMT nightmare:log did-get-response-details [{},true,"file:///app/node_modules/mathjax/jax/input/TeX/config.js?V=2.7.0","file:///app/node_modules/mathjax/jax/input/TeX/config.js?V=2.7.0",200,"GET","",{"access-control-allow-origin":["*"]},"script"]
Tue, 18 Oct 2016 20:24:09 GMT nightmare:log did-get-response-details [{},true,"file:///app/node_modules/mathjax/jax/output/HTML-CSS/config.js?V=2.7.0","file:///app/node_modules/mathjax/jax/output/HTML-CSS/config.js?V=2.7.0",200,"GET","",{"access-control-allow-origin":["*"]},"script"]
Tue, 18 Oct 2016 20:24:09 GMT nightmare:log did-get-response-details [{},true,"file:///app/node_modules/mathjax/extensions/tex2jax.js?V=2.7.0","file:///app/node_modules/mathjax/extensions/tex2jax.js?V=2.7.0",200,"GET","",{"access-control-allow-origin":["*"]},"script"]
Tue, 18 Oct 2016 20:24:09 GMT nightmare:log did-get-response-details [{},true,"file:///app/node_modules/mathjax/jax/element/mml/jax.js?V=2.7.0","file:///app/node_modules/mathjax/jax/element/mml/jax.js?V=2.7.0",200,"GET","",{"access-control-allow-origin":["*"]},"script"]
Tue, 18 Oct 2016 20:24:09 GMT nightmare:log did-get-response-details [{},true,"file:///app/node_modules/mathjax/jax/input/TeX/jax.js?V=2.7.0","file:///app/node_modules/mathjax/jax/input/TeX/jax.js?V=2.7.0",200,"GET","",{"access-control-allow-origin":["*"]},"script"]
Tue, 18 Oct 2016 20:24:09 GMT nightmare:log did-get-response-details [{},true,"file:///app/node_modules/mathjax/jax/output/HTML-CSS/jax.js?V=2.7.0","file:///app/node_modules/mathjax/jax/output/HTML-CSS/jax.js?V=2.7.0",200,"GET","",{"access-control-allow-origin":["*"]},"script"]
Tue, 18 Oct 2016 20:24:09 GMT nightmare:log did-get-response-details [{},true,"file:///app/node_modules/mathjax/jax/output/HTML-CSS/fonts/TeX/fontdata.js?V=2.7.0","file:///app/node_modules/mathjax/jax/output/HTML-CSS/fonts/TeX/fontdata.js?V=2.7.0",200,"GET","",{"access-control-allow-origin":["*"]},"script"]
Tue, 18 Oct 2016 20:24:09 GMT nightmare:log did-get-response-details [{},true,"file:///app/node_modules/mathjax/extensions/MathEvents.js?V=2.7.0","file:///app/node_modules/mathjax/extensions/MathEvents.js?V=2.7.0",200,"GET","",{"access-control-allow-origin":["*"]},"script"]
Tue, 18 Oct 2016 20:24:09 GMT nightmare:log crashed [{},false]
```

`nightmare:log crashed [{},false]` out of the blue has been really confusing me. I've hooked up my nightmare instance with
```javascript
nightmare
      .on('console', (type, ...args) => console.log(`In Page console.${type}: "`, ...args, '"'))
      .on('page', (type, message, extra) => console.log(`In Page event [${type}]:`, message, extra))
```
and its not printing anything that seems relevant.

Is there someway to get more helpful errors here? Or does the crash mean something that I'm not aware of? 

My code that is using Nightmare is a little convoluted, so let me know if it'd be useful, thanks!

**Comment by rosshinkley** [comment]
Heroku + Nightmare can get a little sketchy having to do with `/dev/shm` being too small, and as far as I know (I remember talking about this on Gitter, but can't dig out the conversation) it can't be adjusted.  This was first mentioned [here in #497](https://github.com/segmentio/nightmare/issues/497#issuecomment-187517613).  I wonder if you're hitting that limit?

**Comment by jussch** [comment]
>  You also may run into an issue with /dev/shm being too small, which manifests itself as Electron crashing after a few operations in Nightmare.

This definitely sounds like the problem I'm having. I've tried adjusting the dyno size to no avail. Is there anyway I can confirm this is the issue?

**Comment by rosshinkley** [comment]
I [found the original conversation](https://gitter.im/rosshinkley/nightmare?at=574b580aa78d5a256e38f3cd), and I _thought_ there was an outline on logs/testing for verifying that was the problem, but it's not jumping out at me.

The dyno sizes don't affect the size of shared memory - that setting is locked by Heroku.  Furthermore, memory serving, you don't have root access to change the shared memory partition.  

Re confirming the issue, you might be able to get away with using something like [`df`](http://man7.org/linux/man-pages/man1/df.1.html) to look at `/dev/shm` usage while your script is running.  (Something like `watch "df | grep /dev/shm"` or `watch "df -h | grep /dev/shm"`, maybe?)  I _think_ that's doable with `heroku run bash` on a one-off dyno, but my experience with Heroku is limited.

/cc @rickmed - any light to shed on this topic?

**Comment by rickmed** [comment]
@jussch @rosshinkley I tried all sorts of acrobatics to make it work on heroku until I emailed their tech support and confirmed that dev/shm is fixed to 5mb on all dynos. 

Even though I couldn't prove that dev/shm was the problem (if you read the chromium issue part of the problem is that you don't get logs about the crash), I tested the same script that was crashing on heroku on the smallest VMs of AWS and DO and worked perfectly. I _think_ (can't remember for sure) monitoring dev/shm at max usage on heroku.

If you _must_ use heroku I guess you could finally ask them to change the allocation ad-hoc (if possible).

Hope it helped.

**Comment by jussch** [comment]
Well that is unfortunate. NightmareJS has been doing wonders for me, especially over PhantomJS.

Regardless, thanks for the help and for the info. I'll keep looking into it, but it doesn't appear to be a Nightmare issue, so I'll close this.

**Comment by Chris911** [comment]
@jussch I'm running into the same issue. Wondering if you found a solution?

**Comment by Chris911** [comment]
@jussch Heroku just bumped the size of `/dev/shm/` on their dyno to allow headless browser test.

https://devcenter.heroku.com/changelog-items/1085

**Comment by jussch** [comment]
@Chris911 No I never found a solution, but thanks a bunch for the info! I'll give it another try.

**Comment by Chris911** [comment]
@jussch I managed to get it to run with a few buildpacks but it was crashing after loading 1 webpage. I contacted Heroku and they said they were working on increasing `/dev/shm/` and that it should fix it. Personally decided to deploy on Google Cloud for now but might switch back to Heroku. 

Let me know if it works for you!

**Comment by oscarmorrison** [comment]
For anyone still having trouble (I wasted 10+hours on this) I made a starter repo with a working setup and instructions for deploying on heroku: https://github.com/oscarmorrison/nightmare-heroku
