### ISSUE TITLE
What version of node is best to run with nightmare?

### ISSUE THREAD

**Issue by SnakeO** [segmentio/nightmare#838]
I'm trying to run , but I keep getting this error:
`(node:75110) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Unexpected number in JSON at position 26`

My Package.json:
`{
  "name": "loadspeed-tester",
  "version": "1.0.0",
  "private": true,
  "description": "tests the load speed using pingdom",
  "main": "main.js",
  "dependencies": {
    "bookshelf": "^0.10.1",
    "coffee-script": "^1.9.3",
    "enforce": "^0.1.6",
    "hat": "^0.0.3",
    "jquery": "^3.1.0",
    "knex": "^0.12.1",
    "lodash": "^4.15.0",
    "mandrill-api": "^1.0.45",
    "mysql": "^2.8.0",
    "node-slack": "^0.0.7",
    "orm": "^3.1.0",
    "nightmare": "^2.7.0",
    "sequelize": "^3.5.1",
    "sql-query": "^0.1.26",
    "trim": "^0.0.1",
    "worker-farm": "^1.3.1"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git@gitlab.websitesonwheels.net:root/loadspeed-tester.git"
  },
  "author": "",
  "license": "ISC"
}
`

**Comment by rosshinkley** [comment]
Answering your question, anything >=4.x will work.

I suspect, though, you're hitting the same thing as #839, fixed in #841.
