### ISSUE TITLE
Attribute selector is broken with nightmare@2.8.0

### ISSUE THREAD

**Issue by hakatashi** [segmentio/nightmare#839]
The CSS `[]` attribute selector, which worked nice with nightmare@2.7, now throws an “Unexpected number in JSON” error with the latest version 2.8.0.

# Reproduction

nightmare-test.js:

```js
const Nightmare = require('nightmare');

const nightmare = Nightmare({webPreferences: {partition: 'nopersist'}});

nightmare
.goto('http://localhost:8080/nightmare-test.html')
.click('div[data-x="0"]')
.then(() => console.log('no error'))
.catch((e) => console.error(e))
.then(() => nightmare.end());
```

nightmare-test.html (and serve it with localhost:8080):

```html
<!DOCTYPE html>
<div data-x="0"></div>
```

Terminal:

```
$ node nightmare-test.js
Unexpected number in JSON at position 14
```

Related: https://github.com/tsg-ut/mnemo/pull/105

Thanks.

**Comment by hakatashi** [comment]
I've figured the problem out, will send a patch in a hour...

**Comment by rosshinkley** [comment]
A change was made to allow for asynchronous execution when using `.evaluate()`, which `.click()` uses under the covers.  This change parses the arguments to `.evaluate()`, which parses them, and I think that's causing the issue.

**Comment by hakatashi** [comment]
fmm... the problem was unexpectedly sophisticated and

> send a patch in an hour...

was not possible. I found the selector string injected into "execute" template is wrongly escaped and causing syntax error.

https://github.com/segmentio/nightmare/blob/master/lib/javascript.js#L19

So providing `'div[data-x="0"]'` the above line will be...

    args = JSON.parse('["div[data-x=\"0\""]');

and making `0` to the unexpected number.

I couldn`t find right way to escape these characters.

And note, I found this error makes users be able to inject **arbitrary code** into the nightmare environment.

nightmare-test.js:

```js
const Nightmare = require('nightmare');

const nightmare = Nightmare({webPreferences: {partition: 'nopersist'}});

nightmare
.goto('http://localhost:8080/nightmare-test.html')
.then(() => nightmare.evaluate(() => document.title))
.then((title) => {
	console.log(`Title: ${title}`);
	return nightmare.click('"]\'); document.title = \'blah\'; (\'"');
})
.catch((e) => console.error(e))
.then(() => nightmare.evaluate(() => document.title))
.then((title) => console.log(`Title: ${title}`))
.then(() => nightmare.end());
```

nightmare-test.html:

```html
<!DOCTYPE html>
<title>Page Title</title>
<div data-x="0"></div>
```

Terminal:

```
$ node nightmare-test.js
Title: Page Title
Failed to execute 'querySelector' on 'Document': '"]'); document.title = 'blah'; ('"' is not a valid selector.
Title: blah
```

**Comment by rosshinkley** [comment]
I'm in the throws of fixing this issue now.  Yes, it has to do with how arguments to `evaluate_now` are parsed.  I'll hopefully have something shortly, possibly including a fix for the arbitrary code injection.  (Which, by the by, shouldn't really matter: that's what almost all of the Nightmare commands do.)

**Comment by hakatashi** [comment]
Thanks. I agree this shouldn't really matter, but did hope this be fixed sooner to avoid potential risk for nightmare users. :)
