### ISSUE TITLE
Bug in preload.js, won't fire page error if no error object present

### ISSUE THREAD

**Issue by justinjmoses** [segmentio/nightmare#840]
Steps to reproduce:

``` javascript
const Nightmare = require('nightmare')
const nightmare = new Nightmare({ show: true, openDevTools: true })
nightmare.on('page', console.error).goto('http://www.cachep2p.com/').then(() => {})
```

No errors outputted, and the following bug appears in Electron from `preload.js`:
![image](https://cloud.githubusercontent.com/assets/799038/19567789/17ae4036-96bd-11e6-883b-d4d18ae64225.png)

Fix is a single line (ignore second line from other diff)
https://github.com/segmentio/nightmare/compare/master...justinjmoses:master#diff-72b1e00ac76f0313032875e2182181bbR7

**Comment by casesandberg** [comment]
Would you mind opening up a PR for this?

**Comment by casesandberg** [comment]
I am going to close this, but feel free to open up a new issue or PR for this.
