### ISSUE TITLE
Run nightmare by pm2 or something like that on the server

### ISSUE THREAD

**Issue by neutron92** [segmentio/nightmare#844]
@rosshinkley please how to run nightmare by pm2 or something like that on the server because nightmare use the electron and electron need graphic now i'm using `xvfb-run npm start` but this sol° needs that i stay connected by ssh to the server have you any suggest?

**Comment by privilio** [comment]
There is the solution:

https://github.com/segmentio/nightmare/issues/224#issuecomment-239335488

**Comment by rosshinkley** [comment]
@privilio  is right: start with #224.  Closing this for now, feel free to reopen if you are still having an issue.
