### ISSUE TITLE
Can't use extra parameter in evaluate as async callback

### ISSUE THREAD

**Issue by rberner** [segmentio/nightmare#848]
When I return a promise from evaluate, everything works fine. However, when i specify one extra parameter in the function used as the first argument in evaluate, with the intent of calling it to signal completion of evaluate, the value is not passed to the next then in the chain.

This works fine:

``` javascript
var Nightmare = require('nightmare');
Nightmare()
    .goto('http://google.com')
    .evaluate(function () {
        return new Promise(done => {
            done('working');
        });
    })
    .end()
    .then(value => {
        console.log(value);
    });
```

And this doesn't:

``` javascript
var Nightmare = require('nightmare');
Nightmare()
    .goto('http://google.com')
    .evaluate(function (message, done) {
        done(message);
    }, 'working')
    .end()
    .then(value => {
        console.log(value);
    });
```

**Comment by rosshinkley** [comment]
This is because Nightmare uses the same callback style that Node uses where the first parameter is an (optional) error.  Consider:

```js
var Nightmare = require('nightmare');
Nightmare()
    .goto('http://google.com')
    .evaluate(function (message, done) {
        done(message);
    }, 'working')
    .end()
    .then(value => {
        console.log(value);
    })
    .catch(err => {
        console.log('ERROR: ' + err);
    });
```
This will produce the output of "ERROR: working".

**Comment by rberner** [comment]
So is there currently no way to run evaluate and receive back a value without it being taken as a error (without using a promise)?

**Comment by rosshinkley** [comment]
I should have been clearer with my example.  You certainly can also pass back an optional value.  Consider:

```js
var Nightmare = require('nightmare');
Nightmare()
    .goto('http://google.com')
    .evaluate(function (message, done) {
        done(null, message);
    }, 'working')
    .end()
    .then(value => {
        console.log(value);
    })
    .catch(err => {
        console.log('ERROR: ' + err);
    });
```
...will log "working".
