### ISSUE TITLE
add debugger support please

### ISSUE THREAD

**Issue by sneakywombat** [segmentio/nightmare#85]
Could you please add remote-debugger-port and remote-debugger-autorun?

I tried to hack this in myself,

index.js:
  if (this.options.debuggerPort !== null) {
    flags.push('--remote-debugger-port='+this.options.debuggerPort);
    flags.push('--remote-debugger-autorun=yes');
  }

But it didn't work, the console complained with the following:

phantom stdout: TypeError: 'undefined' is not a function (evaluating 'core_require('webpage')')

  about:blank:5433
  about:blank:5642
  about:blank:179
  about:blank:25
  about:blank:5645
  :1

**Comment by reinpk** [comment]
in `2.x` we've moved from phantomjs to electron, which has fixed a bunch of weird issues. among other things, you can now pass in `{ show: true }` as a constructor argument to just show the window as things are happening.

```
yield Nightmare({ show: true })
        .goto('http://walmart.com/')
        .click(...);
```

hopefully this helps with debugging!
