### ISSUE TITLE
simulate real keyboard event

### ISSUE THREAD

**Issue by Raidus** [segmentio/nightmare#850]
Hi there!

I'm trying to collect some keywords from the amazon auto completion. Unfortunately the input field isn't active after .type() or .insert() is fired. 

Is there a workaround to keep the input field active?

My first attempt:

```
'use strict';

var Nightmare = require('nightmare');
const realMouse = require('nightmare-real-mouse');

// add the plugin
realMouse(Nightmare);

var nightmare = Nightmare({show: true, dock: true, waitTimeout: 10000, port: 443});

nightmare
  .goto('https://www.amazon.de/')
  .wait(2000)
  .realClick('input[id="twotabsearchtextbox"]')
  .wait(2000)
  .clickSearchField()
  .type('#twotabsearchtextbox', 'a')
  .wait(2000)
  .end()
  .then(function (result) {
    console.log(result)
  })
  .catch(function (error) {
    console.error('Search failed:', error);
  });
```

**Comment by casesandberg** [comment]
You could try clicking the input box again after you have typed text into it, that would cause it to focus. I am going to close this, but feel free to re-open if you can't get it to work.
