### ISSUE TITLE
received resource event

### ISSUE THREAD

**Issue by saginadir** [segmentio/nightmare#853]
I want to track the loading of resources to the page, similar to casper's:
`casper.on('resource.received', () => {})`

Is it even possible to do with nightmare?

**Comment by Mr0grog** [comment]
Hi @saginadir, you can use the `did-get-response-details` event for this:

```js
Nightmare()
  .on('did-get-response-details', function (event, socketStatus, url, originalUrl, code, method, referrer, headers, type) {
    console.log('Response:');
    console.log('  url:', url);
    console.log('  originalUrl:', originalUrl);
    console.log('  code:', code);
    console.log('  method:', method);
    console.log('  referrer:', referrer);
    console.log('  type:', type);
  })
  .goto('http://vox.com')
  .end()
  .then();
```

**Comment by Mr0grog** [comment]
Nightmare surfaces most of the WebContents events from Electron: http://electron.atom.io/docs/api/web-contents/#instance-events
