### ISSUE TITLE
Chained evaluations

### ISSUE THREAD

**Issue by helmutgranda** [segmentio/nightmare#857]
Is there a proper way to chain evaluations?  I tried to find some samples in the docs at no vail, most samples have only one evaluation but in my case I need to navigate through the application and evaluate the state of the UI. Restarting the application may not be a problem but would slow down the testing process since we would have to run through all the steps that have already "passed".

```
new Nightmare()
.goto(site)
.evaluate(function(){
// run evaluation
})
then(function(result) {
//confirm result
})
.click()
.evaluate(function(){
// run evaluation
})
then(function(result) {
//confirm result
})

```

**Comment by rosshinkley** [comment]
The first `.then()` turns your Nightmare chain into a `Promise`.  With that, you can return another Nightmare chain (which resolves to a Promise) and continue evaluation.  Using your example, something like:

```js
var nightmare = new Nightmare();
nightmare
  .goto(site)
  .evaluate(function(){
    //run evaluation
  })
  .then(function(result){
    return nightmare.click()
      .evalute(function(){
        //run evaluation
      })
  })
  .then(function(result){
    //confirm result
  })
```

**Comment by gfot** [comment]
@rosshinkley You said that the first `.then()` returns a `Promise`. Can this promise be converted to `bluebird` Promise so to be able to use `.each()` and others from specified library, at a later point in Nightmare chain?

**Comment by zerkalica** [comment]
Just need chainable .then action, that returns nightmare instance, not promise.

**Comment by kgantchev** [comment]
@rosshinkley this doesn't seem to work, because the evaluate contents are executed inside the browser scope and the browser scope doesn't know that the ```nightmare``` variable exists. I get the following error: ```nightmare is not defined```.

**Comment by casesandberg** [comment]
You can make Nightmare use different promise libraries by following the docs here: https://github.com/segmentio/nightmare#promises
