### ISSUE TITLE
Pdf custom page size

### ISSUE THREAD

**Issue by MaheshLivera** [segmentio/nightmare#858]
Is that possible to generate pdf with custom page size other than A4, A3, Legal,Letter &Tabloid
Thanks in advance

**Comment by carlsa** [comment]
You can specify a custom page size by passing `pageSize:{height: <HEIGHT IN MICRONS>, width:<WIDTH IN MICRONS>}` an an option in the `.pdf(path, options)` function.

This would generate a pdf file with 100 x 100 mm page size for example.
`.pdf('test.pdf', {pageSize:{height: 100000, width:100000}})`

I have proposed an update to the documentation in pull request #930 .

**Comment by rosshinkley** [comment]
Documentation has been merged, I'm going to consider this issue closed.
