### ISSUE TITLE
Not able to use custom actions

### ISSUE THREAD

**Issue by DjTester** [segmentio/nightmare#859]
Hello,

Today I have stumbled to create any custom action which does actions both on server and page context. I have spent the last three days trying every possible combination of Nightmare.action with evaluate and with evaluate_now, and .use(), with no success. 

My task is very simple: I need to create a custom action where I return a property from a dom element, and then use push to store this property on an array on server-side. 

But even such a task is herculean when dealing with Nightmare.

For example: I try the "use" function, the same way as in the example in this page:

https://github.com/rosshinkley/nightmare-examples/blob/master/examples/beginner/use/yahooTopResult.js

In sketch, I do the following:

"var functionToUse = function(search) {
  return function(nightmare) {
    nightmare
    .evaluate(function(){
    })
    .then(function(){
        console.log("output1");
    }
  };
};

nightmare
  .use(functionToUse())
  .then(function(result) {
    console.log("output2")
  })
  .catch(function(error) {
    console.error(error);
  });"

The result: I get output 2 printed BEFORE output 1.

I have to say, in general terms, that Nightmare has a terrible API and documentation, and an almost unpredictable behaviour. For example: where is documentation for "use"? Where is documentation for "run"? What criteria nightmare uses for choosing when it is going to queue or when it is going to run the queued operations? I have to do everything with trial and error, because the api beyond the "readme" is almost absolutelly undocumented, and the only documentation comes in the form of very restrict examples, where there is no precise definition of function actions and the meaning of the parameters.

This is indeed a very general criticism, but, in restrict terms, what I want now is what I said in the beginning: to create a custom action that is minimaly general enough to get an dom property on the client, return it, and then storing it in an array server-side. Is that possible?

**Comment by rosshinkley** [comment]
> In sketch, I do the following:

Your `.use()` function calls `.then()`.  That's almost certainly going to lead to unintended side effects with queue management, so I'm not terribly surprised you're seeing strange behavior.

> For example: where is documentation for "use"?

The awful truth about `.use()` is that it's _never_ been particularly well documented.  The idea was to wrap up commonly used Nightmare chains for easy use, but it never really got the attention it deserved.

> Where is documentation for "run"?

`.run()` is in the throws of being deprecated.  See #575.

> What criteria nightmare uses for choosing when it is going to queue or when it is going to run the queued operations?

All operations (except for `.run()` and I think one overload of `.end()`) are queued. Operations are only executed when `.then()` is called, `.end()` is called with a callback, or `.run()` is called.  The TL;DR advice there is to _always_ use `.then()`.  (If you're using generators, this is done automatically for you with `vo` or `co`.)

> ... and the only documentation comes in the form of very restrict examples, where there is no precise definition of function actions and the meaning of the parameters.

This is a very valid criticism.  One of the things on my back burner has been to make a gh-pages branch and take a serious pass at updating/upgrading the documentation.  Nightmare's API surface is getting to be too big for a simple readme.

>  create a custom action that is minimaly general enough to get an dom property on the client, return it, and then storing it in an array server-side. Is that possible?

Yes, although I don't know that you need a "custom action" (or even a `.use()` function) to do so.  Using `.use()`, you could do the following to get all client widths for a given query, for example:

```js
var Nightmare = require('nightmare');

var nightmare = Nightmare();

var functionToUse = function(search){
  return function(nightmare){
    nightmare.evaluate((search) => {
      return Array.from(document.querySelectorAll(search)).map(element => element.clientWidth);
    }, search);
  };
};

var clientWidths = [];

nightmare
  .goto('http://example.org')
  .use(functionToUse('body'))
  .then(function(ws){
    ws.forEach(w => clientWidths.push(w));
  })
  .then(function(){
    return nightmare.use(functionToUse('p'));
  })
  .then(function(ws){
    ws.forEach(w => clientWidths.push(w));
  })
  .then(function(){
    console.log(clientWidths);
  });
```

**Comment by casesandberg** [comment]
Are you still having trouble? I am going to close this, but feel free to open a new issue if its still an issue.
