### ISSUE TITLE
Hardware Acceleration locks up VM

### ISSUE THREAD

**Issue by TechplexEngineer** [segmentio/nightmare#861]
I'm using Nightmare in a VirtualBox vm running Linux Mint as a guest. I have to disable hardware acceleration in Google Chrome so my VM doesn't lockup.

I have found that I also need to disable hardware acceleration in nightmare. 

I added ```app.disableHardwareAcceleration()``` just before app.on('ready' ... in [runner.js](https://github.com/segmentio/nightmare/blob/master/lib/runner.js#L66) and that solved my issue.

**Comment by rosshinkley** [comment]
Closing for a viable solution, but thank you for bringing it up!
