### ISSUE TITLE
`instance.then` causing trouble with promises

### ISSUE THREAD

**Issue by jeffijoe** [segmentio/nightmare#864]
Because the Nightmare instance is a thenable, the following will return a Promise that resolves to undefined:

```js
async function createNightmare () {
  const nightmare = Nightmare({ some: options })
  await doAsyncStuff()
  return nightmare
}
```

This took me 20 minutes to figure out, so it might be worth ensuring that the Nightmare instance is resolved when awaited. :shipit:

**Comment by Bnaya** [comment]
Same here!!

**Comment by JumpeiArashi** [comment]
Same here :-(

I think thenable object should return asynchronously something.

**Comment by rosshinkley** [comment]
I don't know that this is possible (someone correct me if I'm wrong).  This is tantamount to asking for a promise to come through a promise resolution unresolved itself, which (memory serving) breaks Promise standards.

That said, I'd be open a PR either here or on [`nightmare-examples`](https://github.com/rosshinkley/nightmare-examples) noting it.  Thoughts?

**Comment by casesandberg** [comment]
Go ahead and try out the headless Chrome implementation in v3, it has first class async / await support! https://github.com/segmentio/nightmare/tree/v3.

I am going to close this, but feel free to open a new issue if you are still having problems.
