### ISSUE TITLE
`evaluate()` always hangs on working selectors

### ISSUE THREAD

**Issue by zatziky** [segmentio/nightmare#866]
I have a selector `.input-search` that is working for nightmare methods like `click()`, `insert()`, `type()` but whenever I try to run it in `evaluate()` the whole app freezes. 

Here is a sample code:

```
 nightmare
                .wait('.input-search') // it works
               .evaluate(function(){
                    return document.querySelector('.input-search'); // gets stuck here
                })
                    .then(element => {
                        console.log('element found: ', element);
                    })
                    .catch(err => {
                        console.log('not found', err)
                    });
```

`then` and `catch` are never hit. 

The debug output says just this...

> nightmare:actions .wait() for .input-search element +1ms
> nightmare:actions .evaluate() fn on the page +24ms

I have tried with nightmare versions `2.8.1` and `2.7.0`.

**Comment by zatziky** [comment]
Ok, I realized that this happens only on url `https://web.whatsapp.com`.

Is it because it a Single Page Architecture (SPA)? I also had to use another `.click()` method to make a click (`nightmare-real-mouse`).

**Comment by zatziky** [comment]
The problem lies in:
* `return document.querySelector('selector');` or
* `console.log(document.querySelector('selector')`

There should be a better log but debugging it for a while I didn't get the mechanism very well. I'll let someone more experienced to handle it... :)

**Comment by matheus208** [comment]
I'm getting the same thing on a React application.

`console.log` doesn't print anything on the Dev Tools window either.


My code is something like:

```
return nightmare
      .goto(BASE_URL)
      .wait("#app")
      .type(".input-email", USERNAME + USERNAME)
      .type(".input-password", PASSWORD + PASSWORD)
      .click(".btn-app")
      .wait(500)
      .evaluate(() => {
        console.log(document.querySelector(".alert-danger"));
        return document.querySelector(".alert-danger");
      })
      .end()
      .then((errorElement) => {
        expect(errorElement).not.toBe(null);
      });
 ```

**Comment by rosshinkley** [comment]
You cannot return DOM elements or lists of DOM elements.  Any information returned from `.evaluate()` has to be serialized and passed over IPC.

Try extracting information out of the DOM element(s) before passing the information back.

**Comment by zatziky** [comment]
Thx @rosshinkley
