### ISSUE TITLE
Handling multiple window or pop-ups

### ISSUE THREAD

**Issue by zero-master** [segmentio/nightmare#869]
In Selenium, we can do it by using window_handles and switch_to_window method.

Before clicking the link first store the window handle as

`window_before = driver.window_handles[0]`
after clicking the link store the window handle of a newly opened window as

`window_after = driver.window_handles[1]
`then execute the switch to window method to move to newly opened window

`driver.switch_to_window(window_after)`

Is there any way to do it with nightmare?

**Comment by rosshinkley** [comment]
The short answer is no, not out of the box.  New `BrowserWindow` instances are created under Electron and are not created with all of the Nightmare sugar for interaction.  (It's planned for a future release, see #593.)

In the meantime, you can use [`nightmare-window-manager`](https://github.com/rosshinkley/nightmare-window-manager) to get some _very_ basic functionality.
