### ISSUE TITLE
Nightmare hangs with no errors when navigating to .pdf or .doc file

### ISSUE THREAD

**Issue by alyrik** [segmentio/nightmare#870]
Executing `.goto([some_address].pdf)` makes Nightmare process hang:
  
```
electron:stderr Xlib:  extension "RANDR" missing on display ":99". +0ms
  electron:stderr Xlib:  extension "RANDR" missing on display ":99". +225ms
  nightmare:actions .useragent() to Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36 +91ms
  nightmare:log Navigating: "https://www.akamai.com/us/en/multimedia/documents/content/white-paper/akamai-oreilly-high-performance-images-white-paper.pdf",
            headers: [none],
            timeout: 60000 +7ms
  nightmare:log did-start-loading +10ms [{}]
  nightmare:log did-get-response-details +332ms [{},false,"https://www.akamai.com/us/en/multimedia/documents/content/white-paper/akamai-oreilly-high-performance-images-white-paper.pdf","https://www.akamai.com/us/en/multimedia/documents/content/white-paper/akamai-oreilly-high-performance-images-white-paper.pdf",200,"GET","",{"accept-ranges":["bytes"],"cache-control":["max-age=2591543"],"content-length":["5769224"],"content-type":["application/pdf"],"date":["Thu, 03 Nov 2016 14:39:26 GMT"],"etag":["\"580808-53c9edf281a80\""],"expires":["Sat, 03 Dec 2016 14:31:49 GMT"],"last-modified":["Fri, 16 Sep 2016 12:12:10 GMT"],"link":["<https://scripts.demandbase.com>;rel=\"preconnect\",<https://www.googletagmanager.com>;rel=\"preconnect\",<https://www.google-analytics.com>;rel=\"preconnect\""],"status":["200"]},"mainFrame"]
```

**Comment by alyrik** [comment]
And timer function in `runner.js`(197-208) is never called.

**Comment by alyrik** [comment]
All the same for pages with automatic download process, e.g. https://netbeans.org/downloads/start.html?filename=zip/netbeans-8.2-201609300101-src.zip

**Comment by rosshinkley** [comment]
It would seem that downloads are now causing a dialog box to appear (that I don't think was happening before?).  This is preventing Nightmare from moving forward until the dialog box is dealt with.

As a stopgap, you could use [`nightmare-download-manager`](https://github.com/rosshinkley/nightmare-download-manager) or [`nightmare-inline-download`](https://github.com/rosshinkley/nightmare-inline-download) for the moment.  That will handle setting the save path, which prevents the dialog.

As for the timer not firing, that's strange.  It should, but it's possible there's a bug there.  It's also possible (albeit unlikely) that the modal dialog is preventing the timer function from firing.

**Comment by alyrik** [comment]
Ignoring downloads fixes the issue. Thank you!

**Comment by anperez78** [comment]
Why this issue has been closed? What if I don't want to "ignore downloads"? is there a way to make it work with nightmare? E.g. I need to click on a link (which triggers a PDF download) and check the response HTTP code is 200.

**Comment by rosshinkley** [comment]
@anperez78 Did you take a look at `nightmare-download-manager` or `nightmare-inline-download`?
