### ISSUE TITLE
Nightmare hangs when converting circular structure to JSON

### ISSUE THREAD

**Issue by Siilwyn** [segmentio/nightmare#874]
This issue very similar to issue #747: Electron and thus Nightmare hang when converting circular structure to JSON.

The last version where this is not a problem is `2.4.1` then the versions `2.5.x` give the following error:
```
    TypeError: Converting circular structure to JSON
        at process.target._send (internal/child_process.js:626:23)
        at process.target.send (internal/child_process.js:538:19)
        at EventEmitter.IPC.emitter.emit [as emit] (/home/selwyn/codeground/jukes/node_modules/nightmare/lib/ipc.js:54:15)
        at WebContents.<anonymous> (/home/selwyn/codeground/jukes/node_modules/nightmare/lib/runner.js:598:17)
        at emitMany (events.js:132:20)
        at WebContents.emit (events.js:201:7)
```
And up from version `2.6.0` it has the issue I described of freezing the whole process.

The following snippet will reproduce this, beware that keeping the process open for too long will cause your whole OS to hang too! :warning: 
```js
const Nightmare = require('nightmare');
const nightmare = Nightmare({show: true});

nightmare
  .goto('http://jukebox.today/testafreeze')
  .then(function () {
    console.log('page loaded');
  })
  .catch(function (error) {
    console.error(error);
  });
```

**Comment by casesandberg** [comment]
JSON.stringify has a censor function for ignoring children so that it won't get caught in a circular structure: https://stackoverflow.com/a/9653082/989006.

I am going to close this, but feel free to re-open if you can't get it work.

**Comment by Siilwyn** [comment]
Hi @casesandberg where should I do this? Note I'm not using the JSON myself or anything Nightmare does this internally.

**Comment by DruMasterMunch** [comment]
+1

**Comment by JakubSK** [comment]
+1

**Comment by allanjsx** [comment]
+ 1

**Comment by CarlosMC** [comment]
i'm having the same issue, please help!

**Comment by Siilwyn** [comment]
@allanjsx & @CarlosMC Nightmare development has been grinding to a halt over the past year, I would recommend switching to [puppeteer](https://www.npmjs.com/package/puppeteer).
