### ISSUE TITLE
Promise pending

### ISSUE THREAD

**Issue by albus01** [segmentio/nightmare#877]
Hello, I am a novice, and I have some questions to ask you.

I put the logic in the configuration file in order to modify later, and here is my code:
```
    //Pretending that these are configuration files
    var aas = [
        ['wait', '#main'],
        ['then', function(res) { console.log('finish'); }]
    ]
    //end configuration files

    var current = nightmare.goto('http://yahoo.com/');

    for (var i = 0; i < aas.length; i++) {
        var action = aas[i][0];
        var arg    = aas[i].slice(0, aas[i].length);
        current = current[action].apply(current, arg);
        console.log(current);
    }
```

And the output is: Promise { <pending> }.
Can you tell me how to solve the problem?

**Comment by edisch** [comment]
nightmare.goto($path) returns a Promise object

The promise is still pending when you try this `current = current[action].apply(current, arg);` or `console.log(current);`

To fix this, wrap your for loop in a Promise resolution like so:

```
var current = nightmare.goto('http://yahoo.com/').end().then(function () {
    for (var i = 0; i < aas.length; i++) {
        var action = aas[i][0];
        var arg    = aas[i].slice(0, aas[i].length);
        current = current[action].apply(current, arg);
        console.log(current);
     }
});
```

The `.end()` tells the nightmare crawler to stop crawling the page and the `.then()` resolves the Promise. This will definitely fix your Promise pending problem but there other issues to tackle with such a complex task like this one.

**Comment by albus01** [comment]
@edisch 
Thank you so much for anwser me, but it seems not work. The loop not work: `['then', function(res) { console.log('finish'); }]` not work, and `console.log(current);` also not work.

**Comment by albus01** [comment]
Solved.
