### ISSUE TITLE
Ability to feed KeyboardEvent objects to .type() action

### ISSUE THREAD

**Issue by edisch** [segmentio/nightmare#878]
## Problem

I'm trying to send a particular element on my page an Enter keydown event with the shiftKey down and as far as I'm aware that's impossible using only the unicode control codes which the .type() action allows presently.

## Solution

Rather than forcing us to stick to predefined behaviour as per your spec, it would be great if we could instead pass our own KeyboardEvent objects into the .type() action such that any type of Keyboard or Mouse event in the case of .click() for that matter could be entirely under the user's control.

Thanks in advance.

**Comment by casesandberg** [comment]
Do you have some time to throw together a PR for this? I would be happy to take a look at it. I am going to close this, but feel free to re-open if you get a chance to work on it.
