### ISSUE TITLE
use plugin with then or callback

### ISSUE THREAD

**Issue by dcy0701** [segmentio/nightmare#879]
when i use **plugin** in my code,i want a callback function or then function to run my code on Node. if i use callback，it doesn't work. i use then , and return nightmare.wait(),it will throw error

**Comment by rosshinkley** [comment]
Can you supply an example of what you're trying to do?

**Comment by casesandberg** [comment]
Can you provide some more information or a code example? I am going to close this for now but feel free to re-open it with some more details.
