### ISSUE TITLE
Emit events from the client side to the main process

### ISSUE THREAD

**Issue by IonicaBizau** [segmentio/nightmare#880]
I want to be able to send data from the client side to the main process. Is that possible?

**Comment by rosshinkley** [comment]
Yes, with `.evaluate()` you can return data up to the calling client.  For example:

```js
nightmare
  .goto(someUrl)
  .evaluate(() => { return "hello world"; })
  //prints "hello world"
  .then((str) => console.log(str));
```

Is that what you are after?

For completeness, the title of your question talks about events, and if you're wanting to capture events you can use `.on()`.  Any event emitted from Electron can be captured with that.  If you want to define your own events, you might want to check out [`nightmare-custom-event`](https://github.com/rosshinkley/nightmare-custom-event).

**Comment by IonicaBizau** [comment]
I want the reverse: emitting from the client side to the main script.

For example, I'd like in the `preload.js` to have something like:

```js
emitEvent("foo", 42, 7);
setTimeout(function () {
   emitEvent("foo", 42, 8);
}, 1000):
```

And in the main process:

```js
nightmare.on("foo", function (a, b) {
 // 42, 7
 // after one second
 // 42, 8
});
```

I guess that should be possible using the `ipc` module, right?

**Comment by rosshinkley** [comment]
Yeah, that's the intent of `nightmare-custom-event` - did you take a look at that?  I think that might be close to what you're after.  I don't think the Nightmare runner re-emits all events from the Electron context, so I don't think your preload example would work out of the box.  You'd have to patch together an `.action()` to do that, I think.

**Comment by IonicaBizau** [comment]
Ah, right! Thanks!
