### ISSUE TITLE
How to extend Nightmare?

### ISSUE THREAD

**Issue by artuross** [segmentio/nightmare#881]
I would like to extend Nightmare with custom actions (e.g. login, load page x, etc.). I cannot understand how to do that.

I basically copied Nightmare-swiftly:

extend.js file:
```js
exports.login = function(a) {
	return function(nightmare) {
		nightmare
			.goto('http://example.com')
			.wait();
	}
};
```

index.js file:
```js
var Nightmare = require('nightmare');

var nightmare = Nightmare({
	show: true
});

nightmare.use(require('./extend.js'))

nightmare
	.login()
```

This returns an error:
```
C:\Users\Artur\nightmare-test\node_modules\nightmare\lib\nightmare.js:496
  fn(this)
  ^

TypeError: fn is not a function
    at Nightmare.use (C:\Users\Artur\nightmare-test\node_modules\nightmare\lib\nightmare.js:496:3)
    at Object.<anonymous> (C:\Users\Artur\nightmare-test\index.js:7:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
```

Could you help with that? Also, is it possible to access underlying electron object, and for example display notifications?

**Comment by artuross** [comment]
Got it working.

**Comment by nick2012** [comment]
Can you please state how you fixed it? I want to do the same thing.

**Comment by tforbus** [comment]
@nick2012 when you just do `require('./extend.js')`, it comes back as an object with a `login` property. nightmare.use expects a function.

**Comment by JimTheMan** [comment]
@tforbus can you post the full code? When I follow the suggestions here I get:

`TypeError: fn is not a function`

**Comment by bembi454** [comment]
@tforbus Hi please show all your code, or give me your email I have questions

**Comment by tforbus** [comment]
@JimTheMan @bembi454 I'm just referencing code from the previous posts.
```
// extend.js
module.exports = url => nightmare => nightmare.goto(url)

// index.js
const myGoto = require('./extend')

nightmare.use(myGoto('https://github.com'))
```

**Comment by bembi454** [comment]
@tforbus 
okay if I need to do an export of the whole block IT mocha js 

it('Login', done => {
nightmare
.goto('https://....../')
.wait(loginPage.loginButton)
.insert(loginPage.loginInput, config.email_Staging)
.insert(loginPage.passwordInput, config.password_Staging)
.click(loginPage.loginButton)
.wait(loginPage.StydiaClick, 5000)
.wait('span[class="nav-name"]')
.evaluate(function () {
    return Name= document.querySelector('span[class="nav-name"]').textContent;
})
.then(Name => {done()
expect(Name).to.equal(pro);
  })
  .catch((error) => {
   nightmare.end()
     .then(() => { throw error; })
     .catch(done);
 })
})

**Comment by tforbus** [comment]
@bembi454 I'm not sure what you mean. Are you trying to make that `it` block something nightmare can use like `nightmare.use(myLogin(...))`?
