### ISSUE TITLE
is it possible to exclude a package electron

### ISSUE THREAD

**Issue by kodermax** [segmentio/nightmare#882]
it too much size

**Comment by abdihaikal** [comment]
If what you mean is
> "Can I use an external module of electron?"

The answer is Yes, you can.
Please consider to look at **Nightmare(options)** [options.electronpath] (https://github.com/segmentio/nightmare#electronpath)

**Comment by rosshinkley** [comment]
If what you mean is
> "Can I exclude Electron and have Nightmare still work?"
The answer is no.  Nightmare is a wrapper for Electron, and will not work without it.
