### ISSUE TITLE
Running on 0.12

### ISSUE THREAD

**Issue by flockonus** [segmentio/nightmare#883]
Howdy!

I'm just starting on Nightmare, looks promising, but our project is stuck at node 0.12 for some dependency issues.

I'm wondering if it's possible to run it under 0.12 if you guys have some knowledge on a project that does that? I'm thinking that porting it with babel perhaps could work?

**Comment by rosshinkley** [comment]
Nightmare depends on native Promises as well as fat-arrow functions.  Running under 0.12 isn't possible out of the box.  You _might_ be able to use Babel (possibly in tandem with something else) to roll up Nightmare as a dependency, but I personally have not tried it.

**Comment by flockonus** [comment]
Thank you for the response.

In this case it seems there is space for a `nightmare-babel` sort of package, but then it would be a different project. I might take some time off this December and be able to tackle it, but no guarantees atm.

Feel free to close the issue

**Comment by rosshinkley** [comment]
Closing for now.  Let me know if you get that put together, I'd be highly interested to see it!
