### ISSUE TITLE
Permission Denied when Deploying on AWS

### ISSUE THREAD

**Issue by QuentinDela** [segmentio/nightmare#884]
Hello,

I am trying to run NightmareJS on Elastic Beanstalk and I keep having an issue with Electron.

Error: EACCES: permission denied, mkdir '/tmp/deployment/application/node_modules/electron/electron-tmp-download-2233-1478789913678'

Here are the full logs: https://gist.github.com/QuentinDela/49e824c5889e14e899eafbe850d23055

Would you have any ideas on how to fix this? Thanks,

**Comment by jekku** [comment]
Please check the permissions of your /tmp folder.

For all I know, to work around this, you can change the temp folder to something else that you own in unix.
