### ISSUE TITLE
Why is this code not working?

### ISSUE THREAD

**Issue by bertolo1988** [segmentio/nightmare#885]
Hello! I was considering nightmare for a project that i will start and block in a very simple task, can you help me?

```javascript
var Nightmare = require('nightmare');
var timeout = 50000;

var nightmare = Nightmare({ show: true, waitTimeout: timeout });
var url = 'http://www.momondo.co.uk/flightsearch/?Search=true&TripType=2&SegNo=2&SO0=LIS&SD0=LON&SDP0=23-11-2016&SO1=LON&SD1=LIS&SDP1=28-11-2016&AD=1&TK=ECO&DO=false&NA=false';


nightmare.goto(url)
    .wait('#searchProgressText')
    .evaluate(function() {
        return document.querySelector('div.price-pax > span > span.value').text;
    })
    .end()
    .then(function(result) {
        console.log('result', result);
    })
    .catch(function(error) {
        console.error('Search failed:', error);
    });
```

I wanted to wait for that progress bar to end and start evaluating stuff after that... What have i done wrong?

**Comment by CvX** [comment]
The `.wait(selector)` only waits for given element to be present in the document. I assume you rather want to check if that element has expected text, using `.wait(fn)`, like this:

```
.wait(function() {
  var progressElement = document.querySelector('#searchProgressText');
  if (progressElement) {
    return progressElement.textContent == "Expected end string here";
  }
```

**Comment by bertolo1988** [comment]
It did not work for me. Have you tried @CvX ?

**Comment by CvX** [comment]
Yup. Just make sure to **(1)** wait for a correct string (that's "Search complete"), and **(2)** in `evaluate()` return what you need. In example you've given you'll have to replace `.text` with `.textContent` (it's always a good idea to double-check your queries manually in DevTools 😃).
