### ISSUE TITLE
Enter a File to a File Input

### ISSUE THREAD

**Issue by zatziky** [segmentio/nightmare#886]
With `nightmarejs` how to enter a file in a file input and confirm it?

It's for automation of an attachment (e.g. in email). The file input I mean is this:

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/7Usqa.png

**Comment by jekku** [comment]
Up for this. This is important in testing websites. Unless there could be alternatives using native electron.

**Comment by rosshinkley** [comment]
File uploads are not natively supported under Nightmare (or Electron for that matter).  You _can_ do uploads by using the debugger API, which is what [`nightmare-upload`](https://github.com/rosshinkley/nightmare-upload) does.  Does that plugin work for you?

**Comment by rodrigoruiz** [comment]
The plugin doesn't work inside an iframe: https://github.com/rosshinkley/nightmare-upload/issues/9

**Comment by jeje99** [comment]
The nightmare-upload plugin not work with the 3.0... this feature should included in nightmarejs directy.
