### ISSUE TITLE
How to access electron instance

### ISSUE THREAD

**Issue by zatziky** [segmentio/nightmare#887]
Is there a way to access electron instance so that we could fire keaboard events:
```

browserWindow.webContents.sendInputEvent({
  type: "keyDown",
  keyCode: '\u0008'
});
```

The example is from https://github.com/electron/electron/issues/2269

**Comment by rosshinkley** [comment]
Is [`.action()`](https://github.com/segmentio/nightmare#nightmareactionname-electronactionelectronnamespace-actionnamespace) what you're after?  That gives you the ability to define custom actions on the Electron instance.

**Comment by zatziky** [comment]
I wanted to handle an upload dialog and hoped there would be a way using electron directly. Is there another way?

**Comment by josephrocca** [comment]
I'd also like to be able to access the webContents of the BrowserWindow instance if this is possible? I need to do something like this:
```
browserWindow.webContents.sendInputEvent({
  type: "keyDown",
  keyCode: '\u0009'
});
```
And this (also requires access to electron clipboard object):
```
const {clipboard} = require('electron')
clipboard.writeText('Example String')
// ...
browserWindow.webContents.paste()
```

**Comment by rosshinkley** [comment]
@zatziky upload dialogs are _very_ tricky, requiring tapping into the debugger API.  There is a plugin for that: [`nightmare-upload`](https://github.com/rosshinkley/nightmare-upload).  Sending keyboard events to Electron for upload dialogs won't work.

@josephrocca Glad you got it figured out, and thank you for documenting your process! Highly appreciated. :)

Considering both of the above issues are covered, I'm going to go ahead and close this issue.

**Comment by ecrmnn** [comment]
@josephrocca I'm not able to get your action to work. Do you have a complete example? Help would be much appreciated

**Comment by josephrocca** [comment]
@ecrmnn Here's the code with a 50ms timeout:

```
Nightmare.action('sendKeyPress',
  function(name, options, parent, win, renderer, done) {
    parent.respondTo('sendKeyPress', function(unicodeValue, done) {
      win.focus();
      win.webContents.sendInputEvent({
        type: "keyDown",
        keyCode: unicodeValue,
      });
      setTimeout(() => {
        win.webContents.sendInputEvent({
          type: "keyUp",
          keyCode: unicodeValue,
        });
        done();
      },50);
    });
    done();
  },
  function(unicodeValue, done) {
    this.child.call('sendKeyPress', unicodeValue, done);
  });
```

It works for tab and backspace, but not for enter/return (`\u000d`) for some reason. It sort of stumped me so I've moved onto another project for now. If you make any progress, please let me know! Would be really nice if nightmare had a `sendKeys` sort of thing like selenium that abstracted all this stuff away.

**Comment by ecrmnn** [comment]
@josephrocca Thanks. I'll try it out. I'm trying to trigger left and right arrow keys. Hopefully I'll get it working

**Comment by export-mike** [comment]
@josephrocca hey just wondering have you managed to get arrow keys working?

**Comment by josephrocca** [comment]
No, sorry - bit of a mystery :/

**Comment by SergioCrisostomo** [comment]
Did some of you manage to use the `clipboard` API or `<webview>.paste()` for `paste` events? 
Made [a question about it on SO](http://stackoverflow.com/q/43584851/2256325), leaving a note here in case someone knows *how-to*.

**Comment by josephrocca** [comment]
I'm somehow back solving the same problem several months later, so to those who are trying to get arrow keys and other special keys working, check out [this code](https://github.com/segmentio/nightmare/issues/932#issuecomment-300398906). Seems to work fine for me without `win.focus()`.
