### ISSUE TITLE
question: invoking nightmare from an extension

### ISSUE THREAD

**Issue by brandonmp** [segmentio/nightmare#888]
I'm writing a Chrome extension that executes some tricky navigation/interaction flows via injected content scripts.  

I know Nightmare relies on `electron`, so I'm assuming it won't run out-of-the-box in a Chrome extension environment, but is there a practical way to use some part of the API to automate a regular Chrome instance w/ Nightmare from the `background`?

**Comment by casesandberg** [comment]
Go ahead and try out the headless Chrome implementation in v3, you can have it use a remote server to execute tasts! https://github.com/segmentio/nightmare/tree/v3.

I am going to close this, but feel free to re-open if it's still an issue.
