### ISSUE TITLE
nightmare.evaluate(fn, cb, [args]) variable/args scope and errors

### ISSUE THREAD

**Issue by Cramertech** [segmentio/nightmare#89]
I'm struggling with this one because it seems like it should just work.

When I've got things set up like so.... it should pass in arg1 and arg2 into the fn on the evaluate when it calls it right?  Well, it doesn't seem to.  In addition it seems to also throw errors that don't make sense sometimes.

The return statement is where I thought I could return whatever I wanted as a result, but when I have the callback called with res (for the result (what was returned from fn), sometimes it gives me some errors, and sometimes it just does nothing.

[pseudo-code...sort of]

```
global var1 // foo
global var2 // bar

new Nightmare()
    .blah-blah-blah
    .evaluate(fn(param1, param2){
        some code
        console.log(param1 + " " + param2);  // foo bar
        return "The result is pretty.";
    }, cb(res) { console.log(res); }, ["var1", "var2])
    .run();  // In theory produces the result of calling fn with var1 and var2, ...which would
    // be "foo bar" in the console, along with "The result is pretty."
```

**Comment by jfrumar** [comment]
It's very lucky that this GitHub issue exists, because without this thread I would never have understood that. I suggest we add this explanation to the main documentation.

**Comment by woohoowebs** [comment]
jfrumar I agree with you.  I actually feel that the documentation while enough to get doing some really cool things is still not what it could be.  I'm glad that I could help by bringing up the issue and then getting johntitus to clear it up.

This is really a great module, and I enjoy using it very much, but there's quite a bit I'm still not getting.  I hope more can be done for the docs and examples.  I find this to be so awesomely useful.

**Comment by hyq1860** [comment]
this is very useful

**Comment by reinpk** [comment]
thanks all, agree those docs were confusing, updated based on this thread:
https://github.com/segmentio/nightmare/blob/master/Readme.md#evaluatefn-cb-arg1-arg2

**Comment by seethroughtrees** [comment]
I'm able to pass strings like the example above.  But for some reason it fails on passing in functions.  Can't figure out what I could be doing wrong.  Any advice would be really appreciated.

```
var onPageLoad = function() {
  return 'I am a callback!';
};

nightmare
  .goto(url)
  .evaluate(function(pageCb) {
      return pageCb();
    },
    function(val) {
      return console.log(val);
    },
    onPageLoad
  );
```

**Comment by seethroughtrees** [comment]
Okay, in case anyone else gets stuck wondering why they can't pass functions or objects into the arguments of .evaluate(), its because all the values are serialized before being sent over. 

Great explanation here: https://stackoverflow.com/questions/12222856/passing-arguments-to-anonymous-function-inside-page-includejs-and-page-evaluat

**Comment by yunfanye** [comment]
Want to point out that the callback function is no longer the second argument. So basically johntitus's code should now be like  

`
var p1=1,
     p2 = 2;

nightmare
  .evaluate( function(param1, param2){
        //now we're executing inside the browser scope.
        return param1 + param2;
     }, p1, p2 // <-- that's how you pass parameters from Node scope to browser scope
  )
  .end();
`
