### ISSUE TITLE
electron child process exited with code null: undefined

### ISSUE THREAD

**Issue by albus01** [segmentio/nightmare#892]
Does nightmare can work on centos which has no desktop?
My system's version is Centos6.2 and node's version is  6.9.1. GCC is 4.8.5, nightmare's version is 2.8.0, electron's version is 1.2.5. When I run the yahoo's example on my centos server, it not works. I run with this cmd: 
    DEBUG=nightmare*,electron* xvfb-run --server-args="-screen 0 1024x768x24" node yahoo_demo.js
And the output is:
```
 nightmare queuing process start +0ms
  nightmare queueing action "goto" for http://yahoo.com/ +3ms
  nightmare queueing action "wait" +2ms
  nightmare running +1ms
  ....
  nightmare electron child process exited with code null: undefined +19ms
  nightmare electron child process not started yet, skipping kill. +1ms
```
  I'm very sad on this, and have been struggling for many days because it has no helpful error info. I do not know how to do next.  Very much hope to get your help.

**Comment by rosshinkley** [comment]
That looks like the Electron process is never starting.  Could you paste the version of the Yahoo example you are using?

**Comment by albus01** [comment]
@rosshinkley 
```
var Nightmare = require('nightmare');
var nightmare = Nightmare({ show: false });

nightmare
  .goto('http://yahoo.com')
  .type('form[action*="/search"] [name=p]', 'github nightmare')
  .click('form[action*="/search"] [type=submit]')
  .wait('#main')
  .end()
  .then(function (result) {
    console.log(result)
  })
  .catch(function (error) {
    console.error('Search failed:', error);
  });
```
And now when I try again, it just stucks here:
"
DEBUG=nightmare*,electron* xvfb-run --server-args="-screen 0 1024x768x24 -extension RANDR" node yahoo_demo.js
  nightmare queuing process start +0ms
  nightmare queueing action "goto" for http://yahoo.com +5ms
  nightmare queueing action "type" +3ms
  nightmare queueing action "click" +0ms
  nightmare queueing action "wait" +2ms
  nightmare running +1ms

  (stuck here)
"

**Comment by brandonmp** [comment]
same issue, was working yesterday, no significant changes to my build since then

```
  nightmare running +4ms
  nightmare queueing action "evaluate" +0ms
  nightmare running +4ms
  nightmare electron child process exited with code null: undefined +2s
 // CTRL+C
 nightmare electron child process not started yet, skipping kill. +2s
```


my dockerfile:
```
FROM node:latest

RUN apt-get update &&\
    apt-get install -y libgtk2.0-0 libgconf-2-4 \
    libasound2 libxtst6 libxss1 libnss3 xvfb

WORKDIR /app
COPY ./dist .
ARG NPM_TOKEN  
COPY .npmrc .npmrc  
COPY package.json .
RUN npm i
RUN rm -f .npmrc
COPY entrypoint /
RUN chmod +x /entrypoint
ENTRYPOINT ["/entrypoint"]

CMD DEBUG=nightmare node ./ygl-widget-scraper/index.js
```


entrypoint:

```
#!/usr/bin/env bash
set -e

# Start Xvfb
Xvfb -ac -screen scrn 1280x2000x24 :9.0 &
export DISPLAY=:9.0

exec "$@"
```

**Comment by sacabuche** [comment]
somebody found a solution?

**Comment by ejoebstl** [comment]
A hint for debugging: 

You can try to call electron directly, which will usually yield a more detailed error message. 

In my case, the error was a missing library (libX11-xcb).

**Comment by casesandberg** [comment]
Are you still having trouble and have you tried 2.10.0? I am going to close this, but feel free to re-open if it's still an issue.
