### ISSUE TITLE
load page from string [Question]

### ISSUE THREAD

**Issue by mehdyhaghy** [segmentio/nightmare#895]
Is it possible to load a page from a HTML string instead of going to an url?

**Comment by rosshinkley** [comment]
Depends on what you mean - do you want to load the HTML as a page?  If so, you can save the HTML as a file and have Nightmare `.goto()` that file, eg:

```js
nightmare
  .goto('file:///some/location/locally/mypage.html')
  .then( ... )
```

**Comment by mehdyhaghy** [comment]
HTML string means:
var str="<html><head><title>sample page</title></head><body> Sample content</body></html>";
now is there anyway to avoid disk io overhead and render this without writing it to a file?

**Comment by reinpk** [comment]
you could spin up a tiny node server at `localhost:8080` (or any other port) that just returns the string:
http://blog.modulus.io/build-your-first-http-server-in-nodejs

and then `.goto('localhost:8080')`

**Comment by lukaszmn** [comment]
It works if you use:
```
const url = 'data:text/html;base64,' + Buffer.from(html).toString('base64');
nightmare.goto(url)
```

Check https://github.com/electron/electron/issues/1146 for details.
