### ISSUE TITLE
Can't render saved MHTML file

### ISSUE THREAD

**Issue by sweinertjr** [segmentio/nightmare#903]
Hi-

I'm having an issue when opening an MHTML file with Electron, that was originally saved via Electron. It seems to just show me a blank white page. As an example: [Here is the MHTML for geico.com](https://s3.us-east-2.amazonaws.com/cdn.formulaic.io/uploads/html/-KX9_-osY2mLtxdct5vA-0.mhtml)

Does Electron simply not support opening it's exported MHTML files, or am I missing something? It opens fine in Chrome...

Thanks!

**Comment by rosshinkley** [comment]
Looks like public access isn't granted for that asset... can you fix it?

How are you trying to open the file?  Can you provide an example?

**Comment by casesandberg** [comment]
Can you provide some more information or a code example? I am going to close this for now but feel free to re-open it with some more details.
