### ISSUE TITLE
Modify function "goto" to call done at "dom-ready" and not at "did-finish-load"

### ISSUE THREAD

**Issue by wiliame** [segmentio/nightmare#904]
I don't need to wait for images and assets, I need to call code at the dom-ready, but I can only listen for the event, not continue with the queue.

There is any way to change the "done" policy for the goto function?

It's possible to change this behaviour with a plugin? Or add a gotoDomReady function?

**Comment by wiliame** [comment]
I added a new function called **gotoReady** that continues with the execution at dom-ready, without waiting for **did-stop-loading**.

I don't know exactly why, but to continue with the execution at **dom-ready** you have to emit a **did-stop-loading** event. Anyone knows why? I haven't found nothing related with **did-stop-loading**.

What I have modified from "goto" to "gotoReady":
http://i.imgur.com/zez2ldx.png

Add "gotoReady" action script:
https://gist.github.com/anonymous/37366335a29c85b2cde4fd810f5e4767

**Comment by wiliame** [comment]
The "gotoReady" only affects the page you are opening. But if you click in a submit button and the page changes alone, the next one will load only in "LOAD" event.

Another option, is to call "did-stop-loading" at every "dom-ready". Is not the clean way to do it, but for me it's ok until I found a cleaner way to do it.

The script, you must call **loadOnDOMReady** before the **goto**:
https://gist.github.com/anonymous/6c507a0aea7e85730bacd319c08a3328

Will be nice some property in the "goto" function to change the load policy. Something like:

```
nightmare
  .goto('http://google.com/', [], Nightmare.CONTINUE_LOAD)
  .goto('http://google.com/', [], Nightmare.CONTINUE_DOMREADY);
```

or...

```
new Nightmare({
   'load_policy': Nightmare.CONTINUE_DOMREADY
});
```

**Comment by jamie-pate** [comment]
Without this, some sites don't load, such as http://eluniversal.com.mx/

**Comment by jamie-pate** [comment]
Actually it looks like I was starved for resources as several instances of electron were hung

**Comment by iamwiliam** [comment]
@jamie-pate what do you mean? 

Sometimes you don't need to wait for "Load" page if you wan't to use something that is ready at DomReady event.

For all my cases DomReady is the fastest method.

**Comment by wiliame** [comment]
@jamie-pate what do you mean?

Sometimes you don't need to wait for "Load" event if you want to use something that is ready at DomReady event.

For all my cases DomReady is the fastest method.

**Comment by jamie-pate** [comment]
My use case is a crawler, which loops through many nightmare instances (one for each site)

Unfortunately some sites seem to hang the browser. I thought it was an issue where the site was just perpetually loading and never *did-stop-loading* but now I think it's something else. The specific case I was looking at seems to work after restarting linux (I had to hard reset because electron just wouldn't die!)

**Comment by wiliame** [comment]
@jamie-pate google cloud instances works fine with electron. If your machine has 4 cores, sumon only 4 electron and reuse them, don't close them when finish requests so you will be consuming resources to spawn them again.

Working with async.queue (or priority queue) helps.

After crawling a webpage clear cookies, application data and goto "about:blank" so the next page don't get the previous referer.

Don't clear cache so next crawling in that domain will be faster.

I'm getting good results with this practices.

**Comment by jamie-pate** [comment]
I was under the impression that the workflow had to be similar to 
```
nightmare
    .goto(url)
    .evaluate(function() {
        //Extract some data
    })
    .end()
    .then(function(result) {
        //store extracted data
    })
```

So something like this would be better?
```
var nightmare = new Nightmare();
var chain = nightmare;
var queue = ['some seed queue'];
while (url = queue.pop()) {
    chain = chain.goto(url)
    .evaluate(function() {
        //Extract some data
    })
    .then(function(result) {
        //store extracted data (including adding to the queue)
    })
});
chain.end();
```

**Comment by wiliame** [comment]
@jamie-pate right, a lot of time is spent in waiting. N maybe must be based in CPU usage.

Look, my crawler is something like this (i haven't tried the code):

```
const cheerio = require('cheerio');

let concurrency = 4;
let clients = [];

/**
 * Get or instanciate a client
 */
let client = () => {
    // Search a free instance
    for(let i=0; i<clients.length; i++) {
        let client = clients[i];
        
        if(!client.running) {
            client.running = true;
            return client;
        }        
    }
    
    // Add a instance
    let newInstance = {
        running: true,
        nightmare: new Nightmare(),
    };
    
    clients.push(newInstance);
    return newInstance;
};

/**
 * Scan a url
 */
let scan = (url) => {
    let client = client();

    return client
        .nightmare
        .goto(url)
        // interact with webpage
        .evaluate(function() {
            return document.documentElement.innerHTML;
        })
        .end()
        .then((html) => {
            let $ = cheerio.load(html);

            // extract data using cheerio
            // ....

            // free client
            client.running = false;
        });
};

// Queue
var queue = async.queue((url, end) => {
    scan(url)
        .then(() => end())   // handle response
        .catch(() => end()); // handle error
}, concurrency);

// Add urls to queue
for(let i=0; i<100; i++) {
    queue.push('http://example.com/1');
}
```

**Comment by wiliame** [comment]
Actually I handle the operations with block instructions:

![blocks](http://i.imgur.com/uUS1EIP.png)

And there is a class called BrowserManager that instanciates Browser, a wrapper of Nightmare.

**Comment by jamie-pate** [comment]
Mk, well I'm going to run with this for now and stop hijacking the issue thread ;)

**Comment by rosshinkley** [comment]
A plugin is _probably_ the way to go here.  If memory serves, I think there are circumstances where `dom-ready` never fires, but `did-finish-load` does.  I remember having a conversation about this at one point but cannot find the issue offhand, so take that with a grain of salt. :)

For what it's worth, if you're not interested in loading assets, you could also use a load filter like [`nightmare-load-filter`](https://github.com/rosshinkley/nightmare-load-filter).

**Comment by zeluspudding** [comment]
@wiliame, Have a version of your multi-client code you could share? I'm running yours and get failures on the fact that `clients` (plural) isn't defined.

**Comment by casesandberg** [comment]
Looks like this is resolved. I am going to close this for now but feel free to open a new issue if you are still having problems.
