### ISSUE TITLE
新浪微博搜索首页type 为什么提示cannot read property 'focus' of null

### ISSUE THREAD

**Issue by neal1991** [segmentio/nightmare#905]
你好，我想问一下，我想试一下搜索新浪微博首页的搜索框，type的时候为什么提示cannot read property 'focus' of null，我觉得应该已经拿到input那个搜索框了啊。
```
nightmare
  .goto('http://www.weibo.com/')
  .type('.gn_search_v2 input', 'github')
```

**Comment by jekku** [comment]
engurish plis

**Comment by jekku** [comment]
English

**Comment by jekku** [comment]
@neal1991 

```js
nightmare
  .goto('http://www.weibo.com/')
  .wait('.gn_search_v2 input')
  .type('.gn_search_v2 input', 'github);
```

**Comment by jekku** [comment]
Instead of opening up issues here (Which should be architectural problem, or feature requests) that are about using this library, go to https://stackoverflow.com

I find this kind of questioning stupid and pretty idiotic. First of all, not using a common language; secondly the point I raised above.

**Comment by neal1991** [comment]
If I violate the rules of here, I apology. But could you have the basic realization to respect each freshman. So you have the right to criticize anyone with these mean words. Who give you the right?

**Comment by jekku** [comment]
Myself and my freedom of expression. I may be mean but I'm pointing you to the right place to ask questions.

**Comment by neal1991** [comment]
You have your freedom of expression, so do I. If you were the administrator of this, you can close this issue or reminder me. Of course, it seems not. Moreover, as a normal guy, no one will just behave like you. May it is a basic rule for a developer. It seems that you do not have this.

**Comment by jekku** [comment]
Basic rule of a developer? You set the rules now?

**Comment by jekku** [comment]
@neal1991 you can't say who behaves normally. Even Linus Torvalds, creator and maintainer of git and linux is more of an asshole then me.

http://thenextweb.com/dd/2015/11/02/linux-creator-linus-torvalds-had-a-meltdown-over-a-pull-request-and-it-was-awesome/

**Comment by neal1991** [comment]
@jekku Maybe you are born like this.
