### ISSUE TITLE
Large Viewport for Heavy Websites Causes White Screen

### ISSUE THREAD

**Issue by jimmaay** [segmentio/nightmare#906]
When trying to change the viewport to a large value in order to do a full screenshot of a page on a somewhat heavy website the screen goes white and nightmare stops executing. Here's the code to cause it to crash on Windows 10 x64.

```
var Nightmare=require('nightmare');
var nightmare=Nightmare({show:true,maxHeight:100000,maxWidth:10000});

nightmare.goto('http://bleacherreport.com/articles/2677551-the-oral-history-of-the-2006-ohio-state-michigan-game-of-century?utm_source=cnn.com&utm_medium=referral&utm_campaign=editorial').viewport(734,18000).then(function(result){console.log(result)}).catch(function(error){console.error('Search failed:',error);});
```

**Comment by jimmaay** [comment]
When viewport is set to 16384 it works but 16385 it stop working. So there's a limit somewhere

**Comment by jimmaay** [comment]
Also it happens on any website even a blank one.

**Comment by reinpk** [comment]
16384 = 2^14 so doesn't seem too random. some buffer deep in electron or chromium somewhere probably has a max length

**Comment by jimmaay** [comment]
I tried looking through the electron source (which includes chromium) for "16384" or "16" but couldn't find anything unfortunately, do you where the limit would be?

**Comment by rosshinkley** [comment]
This has to do with the max texture tile size that Chromium can render - the texture tile size is limited (in general) by the hardware you're running.  It's _almost_ always 8k or 16k, and defaults to 16k.  [You can see it here for yourself.](https://cs.chromium.org/chromium/src/cc/resources/resource_provider.cc?rcl=1464366759&l=448-454)

You can also verify that if you're interested with [this gist](https://gist.github.com/rosshinkley/b5fb5061073756e926b791a66d62b24b) I threw together when I hit this same problem a while back.  I considered putting together a plugin for large format screenshots that are bigger than the texture size - something that would take small tiles and stitch them together manually, but I never got around to it.  Sounds like it might be worth doing.

**Comment by jimmaay** [comment]
That's great, you pinned it down fully. Regarding the plugin how would this work exactly? Is it a scroll based solution? Scroll based solutions will have issues with fixed elements usually

**Comment by rosshinkley** [comment]
@jimmaay To be honest, it never got past a doodle in my notebook.  (Ab)Using the viewport size and moving it around was going to be a first pass, but you're right - a fixed (or anchored) element would definitely throw a wrench in that.  There are other rendering problems that could crop up with any sort of responsive layout, too, which is ultimately why I tabled the idea.  Still, as a science experiment to float out, it might be worth doing to see if anyone has ideas or another approach.  Also - spitballing - I know you can hook into the frame rendering buffer directly (that's how the current incarnation of screenshots work) - I wonder if there's some raw frame buffer magic that could be pulled off?

**Comment by jimmaay** [comment]
The scroll based solution is currently what I have to rely on at the moment, I do a loop of all elements with a computed position of fixed and change it to static before scrolling but as you said there are definitely many scenarios that this still doesn't cover. 

Is there a way to get a recompiled chromium with max_texture_size_ set to something larger to work on a virtual frame buffer like xvfb? I wonder how phantomJS is able to take screenshots larger then 16384,

**Comment by rosshinkley** [comment]
> ...definitely many scenarios that this still doesn't cover.

Hey, if it works for your needs... :)  Beyond a doubt there are probably many we're not thinking of off the cuff.

> Is there a way to get a recompiled chromium with max_texture_size_ set to something larger to work on a virtual frame buffer like xvfb?

Oooh, good question - you'd have to patch the tilesize and get a working build of Chromium _and_ a working build of Electron off of your custom Chromium build, then patch a fork of Nightmare to use that custom Electron build.  Most likely, doing that would introduce other side effects (or break rendering altogether), but if you've got the time to burn and want to give it a shot, I'd love to see it.

> I wonder how phantomJS is able to take screenshots larger then 16384,

Another _great_ question, and full disclosure, I'm not sure.  This might be worth digging into.

**Comment by jimmaay** [comment]
If I increase max_texture_size_ it looks like I'll probably hit some hardware limit. Right off the bat PhantomJS has a completely different way of rendering which is not easily translatable to chromium. Maybe I'll look into this more when I have time later on, it's too time consuming at the moment for someone with no knowledge on chromium or webkit development.

**Comment by rosshinkley** [comment]
I'm going to close this issue for now as "not fixable" (at least without substantial effort).
