### ISSUE TITLE
Change proxy on the fly

### ISSUE THREAD

**Issue by wiliame** [segmentio/nightmare#908]
Electron is ignoring `session.setProxy`, there is any issue with nightmare that doesn't let me change the proxy on the fly?

Here is the action to change proxy:

```javascript
Nightmare.action('proxy',
    function(name, options, parent, win, renderer, done) {
        parent.respondTo('proxy', function(host, done) {
            win.webContents.session.setProxy({
                proxyRules: 'http=' + host + ';https='+ host +';ftp=' + host,

            }, function() {
                done();
            });
        });

        done();
    },
    function(host, done) {
        this.child.call('proxy', host, done);
    });
```

I have tried with lots of combinations.

**Comment by wiliame** [comment]
Ok, the action seems ok, I have tried it in a sandbox environment and is working ok. Electron is not ignoring `setProxy`. 

If you want change the proxy at runtime, it's enough to do:

```
client
    .proxy('host:port')
    .authentication('user', 'password')
    .goto('http://google.com')
    .proxy('another_host:port')
    .authentication('another_user', 'password') // if is the same user, this is optional
```

**Comment by wiliame** [comment]
I'm trying now to change authentication with the same proxy. Now is not possible because the `authentication` add an `login` event, so if you don't change the proxy, the auth is not called.

I'm going to try to clean password config and do something like:

```
client
    .proxy('host:port')
    .authentication('user', 'password')
    .goto('http://google.com')
    .resetProxyAuth() // for example
    .authentication('another_user', 'password')
```

**Comment by casesandberg** [comment]
Looks like this is resolved. I am going to close this for now but feel free to re-open it you are still having problems.

**Comment by saselovejulie** [comment]
really help me alot, thank you

**Comment by yortrosal** [comment]
Thank you @wiliame . saves me a lot of time.
