### ISSUE TITLE
Override timeout for .wait*()

### ISSUE THREAD

**Issue by zatziky** [segmentio/nightmare#910]
We need to override timeout length in custom `wait` methods. Is there a way how to do it now?

I don't mind providing a PR but when I opened `actions.js` and checked the `wait` method I didn't realize how does the `done` get in the arguments. Can you explain it to me?

**Comment by rosshinkley** [comment]
You can override the [base timeout[(https://github.com/segmentio/nightmare#waittimeout-default-30s) for wait right now.  Are you trying to add a timeout per call?

`done` is always the last argument to an action - the top of the funciton has `var done = args[args.length-1];` - is that what you're asking about?

**Comment by zatziky** [comment]
Yes, that was my question. Thx you, it's solved it. :D
