### ISSUE TITLE
Improved Screenshot Function

### ISSUE THREAD

**Issue by jimmaay** [segmentio/nightmare#911]
Any idea why #135 (the improved screenshot function) with multiple file formats was removed?

**Comment by Mr0grog** [comment]
That feature was based on functionality in PhantomJS. In 2015, Nightmare was rewritten to use Electron, which, at the time, didn’t have built-in support for outputting formats other than PNG. It does support some others now, though (see http://electron.atom.io/docs/api/native-image/) so you could write a PR to add support back in!

**Comment by rosshinkley** [comment]
+1 on a PR for this.

**Comment by kennuzzo** [comment]
HI, ive open PR #950 to support jpeg,  looking forward for some feedback :)

**Comment by matthewmueller** [comment]
Hi @kennuzzo, any chance you'll be finishing that PR up? Thanks!

**Comment by matthewmueller** [comment]
Going to close this since this issue is getting stale. Please feel free to reopen if you're still running into this problem and have additional information for us :-)
