### ISSUE TITLE
cannot return document.querySelector

### ISSUE THREAD

**Issue by BerlinaLI** [segmentio/nightmare#913]
The goal of my sketch is to get product information from an e-commerce website. The code is very similar to the yahoon example code but the result is always null. I tried to put console.log to debug and realized the mistake might lay in the querySelector. 
Below is the code if someone has the time to take a look. Really appreciate it. 

```
var Nightmare = require('nightmare');
var nightmare = Nightmare({ show: true });

nightmare
  .goto('https://www.taobao.com')
  .type('form[action*="/search"] [name=q]', 'hellow kitty')
  .click('form[action*="/search"] [type=submit]')
  .wait(2000)
  .evaluate(function () {
    return document.querySelector('.row.row-2.title a')
  })
  .end()
  .then(function (result) {
    console.log(result)
  })
  .catch(function (error) {
    console.error('Search failed:', error);
  });
```

**Comment by jekku** [comment]
[Please use this wonderful website](https://www.stackoverflow.com) Next time

You are returning the anchor tag from your queryselector. Maybe you should return its href instead, or more meaningful string data.

```js
return document.querySelector('.row.row-2.title a').href;
```

**Comment by rosshinkley** [comment]
DOM elements and DOM element lists are not serializable.  See [#567 (comment)](https://github.com/segmentio/nightmare/issues/567#issuecomment-209533871).

**Comment by canhongpoxiao** [comment]
when I use element.src it return null, it's seems not work

**Comment by jekku** [comment]
@canhongpoxiao this is not the venue for these kinds of questions. Go to Stackoverflow.

You cannot directly call the property of the DOMElement. You need to something like .getAttribute('src')
