### ISSUE TITLE
Nightmare should set a partition by default

### ISSUE THREAD

**Issue by justinmchase** [segmentio/nightmare#916]
```    
this.browser = Nightmare({
  webPreferences: {
    partition: 'nightmare'
  }
});
```

I got burned pretty hard by the fact that I am starting and stopping the browser and there is some state that is getting stored between instances and it was affecting my tests on subsequent runs.

I would like to make a PR that automatically sets a partition by default. If a user wanted to persist state between tests they could set the partition to be `paritition: 'persist: whatever'` still to override it or `partition: null` to revert to the default.

Is there any reason why it would be good or should  actually be set to persist between browser runs? If not I will make a PR to change it. Otherwise I may just add to the front page documentation with a tip about setting the partition to prevent this issue.

**Comment by overflowz** [comment]
Same problems here. I don't want sessions to be shared across different instances. I was trying to find the 'incognito' mode too, but no luck.

**Comment by jekku** [comment]
I've been doing 'nopersist' all the time in my main config to avoid Nightmare from persisting states. I use it in integration tests where tests should be initially stateless and also independent from all other tests.

**Comment by justinmchase** [comment]
@jekku Do you mean literally using the name `'nopersist'` as your partition name? I think you can use any name for the same effect but yeah that would work. I don't know of any other way to do it and you can get burned pretty hard if you don't.
