### ISSUE TITLE
How to slide a bar for user authentication 

### ISSUE THREAD

**Issue by BerlinaLI** [segmentio/nightmare#917]
I confronted a problem when I tried to log on the account. 
There is no command on nightmare.js for sliding a bar on a web page. 
I wonder if someone could shred me some light on this.

**Comment by jekku** [comment]
Can you please make the question more specific? What does the page look like? how is the sliding bar triggered? What does it look like in the DOM tree? There is almost every command you need if you use .evaluate().

**Comment by duyongbo520** [comment]
I think use js code in evaluate to "sliding a bar " is a proper way. Evaluate function can run any js code to manipulate the page  in the context of current page. Hope my advise helps.

**Comment by BerlinaLI** [comment]
This is the[ login page](https://login.taobao.com/member/login.jhtml?redirectURL=https%3A%2F%2Fwww.taobao.com%2F).  The bar shows up quite spontenously. 

![qq 20161205102637d](https://cloud.githubusercontent.com/assets/8443821/20873531/43cb38d2-bae3-11e6-8a66-4cd6996647e6.jpg)
![qq 20161205102637](https://cloud.githubusercontent.com/assets/8443821/20873532/45b40dcc-bae3-11e6-9a62-bbd2f7c0436c.jpg)

Here is how it looks in the DOM tree. 
```
<span id="nc_1_n1z" class="nc_iconfont btn_slide"></span>
<span class="nc-lang-cnt" data-nc-lang="_startTEXT">请按住滑块，拖动到最右边</span>
```

**Comment by jekku** [comment]
This is simple.

Just click the span with that opens the slider

```js
nightmare.click(/* whatever makes the form slide out*/);
```

Once it slides out you can then fill in the following according to my findings|

```js
nightmare.insert('.username-field', 'someusername')
  .insert('.password-field', 'somepassword')
  .click('.submit');
```

By the way, I don't mean to be rude but these kinds of questions belong [HERE](https://www.stackoverflow.com). The issues that should be brought up here I think are architectural problems within nightmare, and how it can be improved. Please try to code first before asking a question that gets you spoon fed.

**Comment by jekku** [comment]
I also highly recommend that you study how to do Inspect-element. Most modern browsers have it. You can't just say 'There is no command blablabla'. This is because of a lack of trying to understand and study the technology.

**Comment by jekku** [comment]
[This extension](https://chrome.google.com/webstore/detail/daydream/oajnmbophdhdobfpalhkfgahchpcoali) can also help you. It will record actions you do in the browser and turn it into a nightmare script. Hope it helps in the futre, too.

**Comment by BerlinaLI** [comment]
The slide bar requires visitor to press the button then drag it to the end of the bar which is similar to "slide to unlock" your mobile screen.

**Comment by casesandberg** [comment]
Are you still having trouble and have you tried 2.10.0? I am going to close this, but feel free to open a new issue if you are still having problems.
