### ISSUE TITLE
Possible to open browser windows through plug-in? 

### ISSUE THREAD

**Issue by BerlinaLI** [segmentio/nightmare#918]
I would like to build a plug-in for web page automation. The result I need to deliver is when user type a keyword on the plug-in, there will be a window popping up and showing the process of manipulating an [e-commerce website](www.taobao.com).  The target user would be ordinary people who don't use terminal.  Is it possible to run nightmare.js not through node on terminal but through other system with GUI? I am a junior programmer. Hope someone can shed me some light.

**Comment by rosshinkley** [comment]
Are you running the ecommerce site under Electron?  If not, then no, this is probably not the solution you're really after.

There are tools out there for giving site demonstrations and guidance.  I have used [Hopscotch](http://linkedin.github.io/hopscotch/) with moderate success.  (Others may have suggestions too, and if you do, please feel free to leave them!)  Is that closer to what you have in mind?

**Comment by BerlinaLI** [comment]
Thanks for your response. In the end, I used jQuery for the plug-in. It works quite well as well.

**Comment by BerlinaLI** [comment]
Thanks for your response. In the end, I used jQuery for the plug-in. It works quite well as well.
