### ISSUE TITLE
set cookies before loading page

### ISSUE THREAD

**Issue by stolendog** [segmentio/nightmare#921]
How to set cookies before loading the page? I need it for authtentication to load the page. If I set cookies before `.goto()` nightmare just exit process:

```  
nightmare:actions cookies.set() +276ms
  nightmare:log setting cookie: {"url":"","name":"test1","value":"test_value","path":"/","secure":true} +1ms
  nightmare electron child process exited with code 0: success! +42ms
```

**Comment by ewrogers** [comment]
It does not seem possible to `cookies.set(...)` before a page has been loaded.

A workaround I am using is to use a dummy `.goto('about:blank')` first, then setting the cookies in the following `.then()` block.

Note that you **MUST** use the `url` parameter of the cookie if you are setting a cookie that is different than the current browser URL.

**Comment by rosshinkley** [comment]
@ewrogers is correct: `session` is not created until after you navigate somewhere.

It might be worth having the discussion: should Nightmare navigate to `about:blank` first?  I can't think of any side effects off the top of my head, but it might be worth sandboxing to see.

Thoughts?

**Comment by ewrogers** [comment]
@rosshinkley  Navigating to `about:blank` initially would work.

Alternatively, you could have `cookies.set` check if a current `session` exists, and if not just treat it as a `.goto('about:blank').then(() => cookies.set(...))` instead.

**Comment by thebentern** [comment]
I ran into this issue as well. Although the reason I encountered it is that I could never get the partition persist under web preferences to work. Each subsequent (new) instance of Nightmare after the initial one, which was a login failed to pick up the cookies from the previous session... I'm not sure why at the moment.

**Comment by tmcleroy** [comment]
Has anyone gotten this to work yet?

**Comment by thebentern** [comment]
@tmcleroy 
As a temporary measure, I figured out a way around the issue by subscribing to the 'did-start-loading' event and throwing my cookies. I'm sure there are cleaner solutions. In particular I couldn't figure out how to pass in the url and cookies as params into my custom action so I used the node-persist package to write and the values out:

```
Nightmare.action('preloadCookies',
  function(name, options, parent, win, renderer, done) {
    parent.on('did-start-loading', function(url, sessionCookies) {
      if (sessionCookies) {
        parent.emit('log', 'Preloading cookies');

        for (var i = 0; i < sessionCookies.length; i++) {
          var details = Object.assign({ url: url }, sessionCookies[i]);
          win.webContents.session.cookies.set(details, function (error) {
            if (error) done(error);
          });
        }
      }
      parent.emit('did-start-loading');
    });
    done();
    return this;
  },
  function(done) {
    this.child.once('did-start-loading', done);
    let cookies = storage.getItemSync(process.env.COOKIES_STORAGE);
    let url = storage.getItemSync(process.env.URL_STORAGE);
    this.child.emit('did-start-loading', url, cookies);
  });
```
To use it: 

```
Nightmare(defaultSettings).preloadCookies().goto(url);
```
If someone can help me figure out how to pass the values into the function instead of relying on node-persist to write and pull them out, that would be optimal..

**Comment by navossoc** [comment]
@thebentern
Have you tried this?

```js
Nightmare.action('preloadCookies',
  function(name, options, parent, win, renderer, done) {
    parent.on('did-start-loading', function(url, sessionCookies) {
      if (sessionCookies) {
        parent.emit('log', 'Preloading cookies');

        for (var i = 0; i < sessionCookies.length; i++) {
          var details = Object.assign({ url: url }, sessionCookies[i]);
          win.webContents.session.cookies.set(details, function (error) {
            if (error) done(error);
          });
        }
      }
      parent.emit('did-start-loading');
    });
    done();
    return this;
  },
  function(cookies, url, done) {
    this.child.once('did-start-loading', done);

    this.child.emit('did-start-loading', url, cookies);
  });

let cookies = storage.getItemSync(process.env.COOKIES_STORAGE);
let url = storage.getItemSync(process.env.URL_STORAGE);

Nightmare().preloadCookies(cookies, url).goto(url);
```

I was playing with cookies today and I managed to set they as this:
```ts
(async function main() {
    let cookies = await nightmare
        .cookies.set({
            url: "https://www.navossoc.com",
            name: "myKey",
            value: "myValue"
        })
        .goto("https://www.navossoc.com/tests/cookie.php")
        .cookies.get();

    console.log(cookies);
})();
```

**Comment by jasonmorita** [comment]
@navossoc This seems to work, just add `url` property.

**Comment by 3zzy** [comment]
@thebentern Were you (or anyone else) able to get the partitions persistence working at all? Storing and saving cookies using @navossoc function isn't working for me either. It gets stuck at `nightmare running +0ms`

**Comment by casesandberg** [comment]
Looks like this is resolved. I am going to close this for now but feel free to open a new issue if you are still having problems.
