### ISSUE TITLE
How to set will-download event after setting webPreferences.partition option?

### ISSUE THREAD

**Issue by overflowz** [segmentio/nightmare#923]
Whenever I'm using webPreferences.partition option with random string (without 'persist:' prefix), nightmare-download-manager always asks for download path to be saved instead of handling it automatically. Even by debugging, breakpoints are never hit as well. May I ask what's the problem? Any thoughts?

**Comment by overflowz** [comment]
Anyone?

**Comment by rosshinkley** [comment]
This is a bug with `nightmare-download-manager` most likely.  I see you've already opened an [issue there](https://github.com/rosshinkley/nightmare-download-manager/issues/9), so let's move this conversation there.
