### ISSUE TITLE
[BUG] Viewport have limitation when running nightmare in Windows 7 task scheduler

### ISSUE THREAD

**Issue by martin-liu** [segmentio/nightmare#924]
I wrote a simple script that will set viewport and return width/height. See below:

```javascript
var Nightmare = require('nightmare');
var fs = require('fs');

function write(path, data) {
  return fs.writeFileSync(path, JSON.stringify(data));
}

var nightmare = Nightmare();

nightmare
  .goto("https://www.google.com")
  .wait(3000)
  .evaluate(function() {
    var w = Math.max(document.documentElement.clientWidth, window.innerWidth || 0);
    var h = Math.max(document.documentElement.clientHeight, window.innerHeight || 0);
    return {w:w, h:h};
  })
  .then(function(d) {
    write('C:/1.txt', d);
    return nightmare
      .viewport(d.w + 1200, d.h + 1200)
      .evaluate(function() {
        var w = Math.max(document.documentElement.clientWidth, window.innerWidth || 0);
        var h = Math.max(document.documentElement.clientHeight, window.innerHeight || 0);
        return {w:w,h:h};
      })
      .then(function(d){
        write('C:/2.txt', d);
      })
      .then(function(){
        nightmare.end(function(){
          console.log('Done!');
        });
      });
  });

```

It works well in Windows 7, when I test it, here's the result:
 * 1.txt
 ```
{"h":542,"w":784}
```

 * 2.txt
 ```
{"h":1684,"w":1968}
```
<hr>
But when I add a task in Windows 7 `task scheduler`, which call the same script. The result is:

  * 1.txt
 ```
{"h":542,"w":784}
```

 * 2.txt
 ```
{"h":730,"w":1028}
```

It's weird and I have no idea what's the issue, can you help check on this issue?

**Comment by rosshinkley** [comment]
Is your scheduled task running as the same user?  Could he default window size be different for the user that runs the scheduled task, and that the page renders differently result in a different client size?

What are you trying to do that this is an issue?

**Comment by martin-liu** [comment]
I was using the same user. 
Actually I had a work around to achieve my requirement, but for this specific issue, I have no idea why it happens.

**Comment by rosshinkley** [comment]
Sounds like this issue is at least tentatively resolved, going to close it for now.  If this crops up again, feel free to reopen.

**Comment by jeeinn** [comment]
I also encountered a similar problem. I'm here to solve this.
```
.viewport(parseInt(width), parseInt(height))
```
