### ISSUE TITLE
conditional injecting

### ISSUE THREAD

**Issue by sjfricke** [segmentio/nightmare#925]
I want to run evaluations with jQuery calls (way easier to grab things from DOM) but the issue is I did a 

```
.evaluate(function () {
    if (typeof jQuery != 'undefined') {  
        // jQuery is loaded => print the version
        return jQuery.fn.jquery;
    } else {   
        //need to inject jQuery
        return  "false"; 
    }
})
```

This tells me if jQuery is added or not but I don't want to run the 

```.inject('js', 'jquery.min.js')```

if there is already a version on because I don't need the chance that the rest of the page doesn't work.
I know I "should" be safe if I just use the latest version of jQuery each time, but all I need is a page to have a deprecated functions or some other support issues

**Comment by rosshinkley** [comment]
You can certainly do a conditional injection.  From the hip, something like:

```js
var nightmare = Nightmare();
nightmare
  .evaluate(()=> typeof jQuery == 'undefined')
  .then(jqueryDoesNotExist => {
    if(jqueryDoesNotExist){
      return nightmare.inject('js', 'jquery.min.js');
    }
  })
  .then(() =>{
    nightmare.click(mySelector) ...
  })
```
... should be close.  Is that what you had in mind?

**Comment by sjfricke** [comment]
Thanks, I didn't realize that the evaluate was passed as a parameter to the next piped instruction like that.
