### ISSUE TITLE
How to .wait(fn) element?

### ISSUE THREAD

**Issue by yodfz** [segmentio/nightmare#931]
```javascript
.wait(function (done) {
        setTimeout(() => {
            var jsAlert = document.querySelector('.js-alert')
            var btn = document.querySelector('#sso_submit')
            if (jsAlert != null) {
                done(true);
            }
        }, 500);
    })
```
wait is tiemout!!!
I think wait `.js-alert` in `body`,continue next!!!please,tks!

**Comment by jekku** [comment]
I think this is a good site!!!

https://stackoverflow.com

because this is not the right place for your banters!!

**Comment by rosshinkley** [comment]
@yodfz not sure what you're expecting to happen here: if the `.js-alert` element does not exist, that function will never return, and eventually the wait timeout will be hit.  You probably want an `else` statement to call `done()`, if I had to guess.

**Comment by casesandberg** [comment]
Can you provide some more information or a code example? I am going to close this for now but feel free to open a new issue with some more details.
