### ISSUE TITLE
Screenshot callback halts nightmare from advancing down the chain

### ISSUE THREAD

**Issue by tlshaheen** [segmentio/nightmare#934]
I have an issue similar to #555, but I'm not sure it's the same cause so I'm opening a new issue. I'm using `nightmare v2.9.0`. When the following code runs, it takes the screenshot, and "screenshot taken" is loaded to the console - but the window is never closed, `run()` is never called. If I enter a path like `nightmare.png` instead of the callback, it works. But the callback seems to freeze Nightmare.

Should I be returning something other than `true` from my callback, or calling another method inside my `screenshot()` callback to tell Nightmare to keep moving down the chain?

I tried [one suggestion](https://github.com/bahlo/nightmare/commit/31b17abdf53931cec87cca27b5e2d1f226b611df#diff-bc4eacf94ad1a8e7c9bea8b6b6451251R53) from #555 but no dice.

My end goal from the screenshot callback is to save the screenshot to AWS S3, directly inside the callback. But the problem exists without even having any of the S3 `putObject()` code in the callback.

```
var Nightmare = require('nightmare');
var nightmare = Nightmare({ show: true });
nightmare
    .goto('http://www.goldencityfooddelivery.com/index.php?main_page=index&cPath=14')
    .select('select[name="products_id[573]"]', '1')
    .click('#submit2')
    .wait('#cartDefaultHeading')
    .screenshot(function(something, theBuffer) {
        console.log('screenshot taken');
        return true;
    })
    .end()
    .run(function (err, nightmare) {
        if (err) return console.log(err);
        console.log('Done!');
    });
```

**Comment by jekku** [comment]
Instead of specifying the 'done' callback exclusively, specify the path and a simple callback

```js
const path = '/some/path/someFileName.jpg';
nightmare.screenshot(path, () => console.log('screenshot taken'));
```

Correct me if I'm wrong, but .end(), is also a thenable which you can use to do something like:

```
nightmare.screenshot(path, () => console.log('screenshot taken'))
  .end()
  .then(() => {
    s3Library.uploadToBucket(path); // LOL just guessing some API function names
  });
```

**Comment by jekku** [comment]
Please update me. I usually use async-await / generators for nightmareJS but I hope this works for you.

**Comment by rosshinkley** [comment]
`.screenshot()` does not take a function callback (at least, not anymore).  What version of Nightmare are you using, @tlshaheen?

**Comment by jekku** [comment]
@rosshinkley https://github.com/segmentio/nightmare/blob/master/lib/actions.js#L600

I think the current branch still does. It just isn't documented. The top level callback is bubbled down as a callback to fs.writeFile.

**Comment by casesandberg** [comment]
Looks like this is resolved. I am going to close this for now but feel free to open a new issue if you are still having problems.
