### ISSUE TITLE
Inconsistent Results

### ISSUE THREAD

**Issue by dfenstermaker** [segmentio/nightmare#936]
So I am new to Nightmare, I am trying to simply run a few checks on my staging environment and for whatever reason I am getting very inconsistent results. For the following code:

```javascript
const Nightmare = require('nightmare')


function createNighmare (options) {
  
  return Nightmare({
          typeInterval: 20,
          width: 1600,
          height: 800,
          x: (options.top || 0),
          y: (options.left || 0),
          // webPreferences: {
          //   partition: 'persist: testing'
          // },
          // fullscreen: true,
          // openDevTools: {
          //   mode: 'detach'
          // },
          show: true
        })

}

function loginToJiveweb (nightmare, {username, password}) {

  return nightmare
    .goto('https://my.staging.jive.com')
    .wait('form[id="jlf"]')
    .type('input[id="username"]', username)
    .type('input[id="password"]', password)
    .click('form button#go-button')
    .wait('#tos-accept-button')
    // wait for page to render entirely
    .click('#tos-accept-button')
    .wait('.dashboard')
    .evaluate(function () {
      return true
    })
    .run(function () {
      console.log('done')
    })
    .then(function () {
      console.log('something was promised')
    })
}
```
It runs everytime however, the .click('form button#go-button') is inconsistent. Soemtimes it clicks when the button is there and soemtimes it does not. Being as this is the very start of my app I cannot test anything else without this working consistently. Any help or thoughts? 

Here is the debug logs which appears to be trying to run the click
```
$ DEBUG=nightmare:actions* node tests/callTesting/calls.test.js
something was promised
  nightmare:actions .wait() for form[id="jlf"] element +0ms
  nightmare:actions .type() notactualemail@gmail.com into input[id="username"] +743ms
  nightmare:actions .type() password into input[id="password"] +506ms
  nightmare:actions .click() on form button#go-button +1s
  nightmare:actions .wait() for #tos-accept-button element +2ms
done
```
Appreciate any help

**Comment by jekku** [comment]
Maybe try waiting for it before clicking on it?

**Comment by dfenstermaker** [comment]
@jekku I am confused I am waiting for it before clicking:

```
.wait('#tos-accept-button')
    // wait for page to render entirely
 .click('#tos-accept-button')
```

**Comment by rosshinkley** [comment]
@dfenstermaker in your original post, though, you said it was not clicking on `form button#go-button`.  Is that button the problem, or is `tos-accept-button` the issue?  If it's `form button#go-button`, what happens if you have `.wait('form button#go-button)` prior to the click?

**Comment by casesandberg** [comment]
Are you still having trouble? I am going to close this, but feel free to open a new issue if its still a problem.
