### ISSUE TITLE
How can i set OS version to electron from nigthmarejs script

### ISSUE THREAD

**Issue by plcgi1** [segmentio/nightmare#939]

**Comment by rosshinkley** [comment]
Do you mean setting the OS in `User-Agent`?  The can be set using [`.userAgent()`](https://github.com/segmentio/nightmare#useragentuseragent).  Note you'll need to set the entire user agent string.

**Comment by casesandberg** [comment]
Are you still having trouble? I am going to close this, but feel free to open a new issue if its still a problem.
