### ISSUE TITLE
Extra page in PDF generation with custom page sizes

### ISSUE THREAD

**Issue by Mins** [segmentio/nightmare#943]
Most probably due to Electron but when rendering fullpage PDF using the pageSize option, 2 pages are rendered in the PDF instead of just 1.

The code below does the following
  - Load a page
  - Get the page width and height
  - Convert sizes to micron meters
  - Resize the viewport
  - Render full page PDF

```
var Nightmare = require('nightmare');
var nightmare = Nightmare({ show: false, width: 1980, maxWidth:100000, maxHeight:100000 });

var calcSize = function(width, height) {
  // Size in micronmeters
  return { pageSize: { height: Math.ceil(height * 254/96*100), width: Math.ceil(width * 254/96*100) }, marginsType: 1 };
};

nightmare
  .goto('https://facebook.com')
  .wait(3000)
  .evaluate(function () {
    var body = document.body, html = document.documentElement;
    var height = Math.max( body.scrollHeight, body.offsetHeight, html.clientHeight, html.scrollHeight, html.offsetHeight );
    var width = Math.max( body.scrollWidth, body.offsetWidth, html.clientWidth, html.scrollWidth, html.offsetWidth );
    return { width: width, height: height };
  })
  .then( function (result) {
    var size = calcSize(result.width, result.height)
    nightmare.viewport(result.width, result.height).wait(1000).pdf("./screenshot.pdf", size).end().then();
  })
```

While it happens with facebook.com, no issues are seen when rendering github.com. Looking at the problematic PDFs, I noticed that the last few pixels of the full page is rendered on the second page.

**Comment by reinpk** [comment]
given that the pdf printing happens under the covers in electron, it's likely an electron issue:
https://github.com/segmentio/nightmare/blob/master/lib/runner.js#L444

**Comment by Pelv** [comment]
hi Mins, i've the same issue. Did you find any solution?
