### ISSUE TITLE
Dynamic looping through links on a website

### ISSUE THREAD

**Issue by anthnyprschka** [segmentio/nightmare#944]
I want to fetch all links on a website and then sequentially visit them.

I have the following code:

```javascript
var Nightmare = require('nightmare');
var vo = require('vo');

var links = []; 

vo(run)(function(err, result) {
    if (err) throw err;
});

function* run() {
    var nightmare = Nightmare({ show: true })

    yield nightmare 
	.viewport(800, 1600)
	.goto('https://www.example.com')
	.wait(5000)

    links = yield nightmare.evaluate(function() {
	return document.querySelectorAll('#id');
    });

    for (var i = 0; i < links.length; i++) {
	yield nightmare
	    .goto(links[i].href)
	    .wait(5000)
    }
                                                                                                                                                                           
    yield nightmare.end()
}
```

For some reason it won't loop through the links. Can anybody give me a hint on how to solve this?

**Comment by jekku** [comment]
@anthnyprschka the return of document.querySelector and document.querySelectorAll are not serializable.

You have to do seomthing like
```js
links = yield nightmare.evaluate(function () {
  return Array.from(document.querySelectorAll('#id')).map(a => a.href);
});
```

recommended for closing @rosshinkley

**Comment by jekku** [comment]
Also it's weird to cast document.querySelectorAll on an ID selector, since that's only supposed to return 1 node. IDs should be unique per dom element. Are you sure about the structure of your scraping?

**Comment by anthnyprschka** [comment]
Wow thanks @jekku !! The serialization was the problem. The '#id' was just for illustration, was actually selecting for a class. Sorry its late in Berlin. Thanks again for the quick help!
PS. Wasn't really an issue of nightmare.js was it

**Comment by jekku** [comment]
It's actually pretty common for similar questions to be asked around. Maybe you can PR to electron or nightmare so we can parse it? :)))))

**Comment by anthnyprschka** [comment]
@jekku Haha sure you mean a pull request? What exactly? 

And is this the only way to send back data extracted from the site to my script? Seems like a workaround no?

**Comment by anthnyprschka** [comment]
Btw just found this question on SO about it: http://stackoverflow.com/questions/30876927/nightmare-phantomjs-and-extracting-page-data

**Comment by casesandberg** [comment]
Looks like this is resolved. I am going to close this for now but feel free to open a new issue if you are still having problems.
