### ISSUE TITLE
Electron.exe using 100% cpu on windows server 2008 R2

### ISSUE THREAD

**Issue by shhtephe** [segmentio/nightmare#946]
I have a piece of code, which grabs a page and saves it as a pdf. This works perfectly fine on my local machine (windows 10 with an I7 cpu). But when I run the app in windows server 2008 R2, electron.exe starts up and hits 100% cpu. There's a small chance that the page won't time out and it will grab the page, but more times than not, it will time out (gives an error that nightmare took more than 30000 ms to get to the page). 

I'm an absolute programming n00b, and it's entirely possible that I'm doing something wrong, but even when I point nightmare to google.com, electron spikes to 100%, and it still times out most of the time. 

The specs of the machine is i7-3930k, 2gb, if that makes any difference.

```
var nightmare = require('nightmare');
  var public_dir = '.\\public\\images\\emailquote';
  var pageURL = "http://" + req.hostname + ":8080" + req.body.data.url;

  //Create new nightmare ;)
  var screenshot = new nightmare()
  .goto(pageURL)
  .wait(5000)
  .pdf(public_dir + '/testfile.pdf') //Should name this file properly in case it isn't deleted
  .run(function(err, nightmare) {
    console.log("Running Nightmare");
    if (err){
      return console.log("Screenshot error:", err);
    } 
    else {
      //do other things, like emailing the page to a user
    }
  };
```

**Comment by jekku** [comment]
I'm just curious as to why you use that server and hardware. :)

**Comment by shhtephe** [comment]
It's what they provided me with.

I was originally setup with a centOs server, but I was having a really hard time getting nightmare to work, as it needed Xvfb to function. Like I said, I'm an absolute n00b, and couldn't get it to run properly (it would silently fail without any error).

What would you recommend they spin up for a server? I can certainly pass it along, if you think it'll fix the issue :)

**Comment by jekku** [comment]
@shhtephe lol we're both noobs but this is what I think - the containers in my Travis CI tests use Ubuntu Server edition. :) I think Xvfb or Xfce will be easier to set up there, so you can use nightmare.js. :grinning:

**Comment by shhtephe** [comment]
@jekku So I asked the admins to turn up the ram on the VM box, and they bumped it from 2gb to 8gb, and the issue has been solved. Electron runs speedily and doesn't go past 5%. I don't know why having low memory would tank the CPU usage, but as I said, I'm a n00b. I suppose we can consider this "solved" as there's a reasonable workaround?

**Comment by jekku** [comment]
@shhtephe that's awesome :D 

if we look closely, the windows VM might have been using some kind of swap partition. Modern browsers usually take up a lot of memory but I'm not sure how electron is benchmarked.

I tried running chrome on a small box with 3gb and the processor usage is around 50 to 60 percent for 5 tabs. That sounds a bit congruent to your experience.

**Comment by casesandberg** [comment]
Are you still having trouble? I am going to close this, but feel free to open a new issue if its still a problem.
