### ISSUE TITLE
Promise resolve returns undefined if nightmare passes through it

### ISSUE THREAD

**Issue by aml11** [segmentio/nightmare#947]
Hello,

I'm trying to create a function that creates the nightmare instance and does some work (I need it to always go to a site and run some script before running). So I've create a method the generates and returns a promise where it should return the working nightmare instance.

However for some reason when passing the nightmare instance through the resolve it gets `undefined` on the other end.

See repro:
```
function getNightmare() {

    var nightmare = Nightmare({});
    return new Promise((res, rej) => {
        nightmare
            .goto("http://cnn.com")
            .evaluate(function() { return document.title })
            .then((title) => {
                console.log(title);
                res(nightmare);
            })
            .catch((error) => {
                rej(error)
            })
    })
}
getNightmare().then((inst) => {
    console.log(inst);
})
```
Prints in the log:
```
node --debug-brk=19560 --nolazy src/scraper.js 
Debugger listening on 127.0.0.1:19560
CNN - Breaking News, U.S., World, Weather, Entertainment & Video News
undefined
```

Changing the line res(nightmare) to res(5) prints (obviously)
```
node --debug-brk=7732 --nolazy src/scraper.js 
Debugger listening on 127.0.0.1:7732
CNN - Breaking News, U.S., World, Weather, Entertainment & Video News
5
```

**Comment by JumpeiArashi** [comment]
I've also see same phenomenon.

**Comment by jekku** [comment]
can you actually check what 'this' and 'nightmare' are inside that 'then' clause? my short speculation is that within that function, 'this' is actually 'nightmare', instead of 'nightmare'.

**Comment by rosshinkley** [comment]
Isn't this because the Nightmare instance is a `.then()`able itself?  If you're resolving nightmare after it's run a chain, it's trying to resolve the now-currently-empty action chain, which will resolve to `undefined`.

Try wrapping the instance in an object literal, like `res({nightmare:nightmare})`.  Would something like that work?

**Comment by aml11** [comment]
Wrapping the nightmare like that is how I've been using it for awhile, it
does indeed work around the problem.

**Comment by JumpeiArashi** [comment]
wow! OK I'll try to wrap an object literal. thanks.

**Comment by entrptaher** [comment]
Can't you just do this?
```js
var Nightmare = require('nightmare'),
    nightmare = Nightmare();

function getNightmare() {
    var nightmare = Nightmare({});
    return nightmare
            .goto("http://example.com")
            .evaluate(function() {
                return document.title
            })
}

getNightmare().then((inst) => {
    console.log(inst);
})
```

**Comment by aml11** [comment]
I'm trying to have a single nightmare instance and use it in all kinds of scenarios during my program's lifecycle.
So I have a single "getInstance" which acts as a lazy getter to a static nightmare instance which needs to initialize only once, since nightmare takes time to initialize I return a promise.

**Comment by entrptaher** [comment]
Oh, that?
You can do it this way, 
Declare nightmare variable first, then update the variable.

```js
var Nightmare = require('nightmare'), nightmare;

function getNightmare() {
    nightmare = Nightmare();
    return nightmare
            .goto("http://example.com")
            .evaluate(function() {
                return document.title
            })
}

function printLog(data){
  console.log(data);
}

getNightmare().then(printLog)
```

Or, like this,

```js
var Nightmare = require('nightmare'),
    nightmare;

function init() {
    return nightmare = Nightmare();
}

function goThere() {
    return nightmare
        .goto("http://example.com")
        .evaluate(function() {
            return document.title
        })
}

function printLog(data) {
    console.log(data);
}

init()
    .then(goThere)
    .then(printLog)
```

There are always several ways to do the same thing.

**Comment by rosshinkley** [comment]
@entrptaher Isn't that effectively the same thing as using (the admittedly not-well-documented) `.use()`?

Anyway, seems like this issue is resolved for the moment.  Closing.

**Comment by entrptaher** [comment]
Maybe it's because you cannot use the same instance once you resolve it completely in the `printLog` function described above. If there is a better way to reuse the same instance using `.use`, I'll be happy to explore it.
