### ISSUE TITLE
NightmareJS not clicking a button on a modal

### ISSUE THREAD

**Issue by pfftdammitchris** [segmentio/nightmare#949]
Theres an ID to other elements like #btnMyWL that is easy to target and click on, but there is a button "Save" that has no id or class name to it. I can't target it to get it clicked.... I even did Array.from(document.querySelectorAll) and selected the specific save button (indexed 14), returned it from my evaluate function to my then function and tried to do the .click on it inside the then function but it doesnt click. Is there any way I can click an "anonymous" button like that?  

    var w = Nightmare({
        width: 1600,
        height: 900,
        waitTimeout: 8000 // 8 secs no answer, stop the script
    });
    w
    .goto(anondefault)
    .insert("#UserName", "*censored*")
    .insert("Password", '*censored*')
    .click("#btnLogin")
    .wait("#btnMyWL") // wait 1.5 secs
    .click("#btnMyWL") // clicks WL
    .wait("#txtBookNbrs")  
    .click("#txtBookNbrs") // add container # field
    .insert("#txtBookNbrs", 'TCLU7777777')
    .evaluate(function () {
        let r = Array.from(document.querySelectorAll("button"));
        let s = r; //  
        return $("button")[14];
    })
    .end()
    .then(z => {  // z  = save watchlist button
        console.log(z);  // returns "jQuery43249238324" or something--it is the save button
        w.click(z)
    })
    .catch(error => {
        console.log(error);
    });

**Comment by pfftdammitchris** [comment]
LADIES AND GENTLEMEN I FINALLY DID IT there was a attribute ng-click on it with SaveWatchList()  so I did:

 .click("button[type=\"submit\"][ng-click=\"SaveWatchList()\"]")

Impossible modals no more!

**Comment by rosshinkley** [comment]
Sounds fixed. :)  Closing.
