### ISSUE TITLE
return multiple results in a single `then` callback?

### ISSUE THREAD

**Issue by ianstormtaylor** [segmentio/nightmare#951]
Is there a way to lookup multiple values and have them all be returned to the ending promise/callback? I find myself wanting to do things like this for succinctness:

```js
nightmare
  .goto(...)
  .type(...)
  .click(...)
  .wait(1500)
  .path()
  .title()
  .cookies.get({ name: 'session' })
  .end()
  .then((path, title, cookie) => {

  })
```

Or is there another terse-ish way to do this?

**Comment by jekku** [comment]
I rarely end up like this because I usually use async-await or generators. They look something like this:

When wrapped in a generator function:
```js
yield nightmare.goto(...)
  .type(...)
  .click(...)
  .wait(TIME_SPAN);

const path = yield nightmare.path();
const title = yield nightmare.title();
const cookie = yield nightmare.cookies.get({ name: 'session'});
```

When wrapped in an async function:
```js
await nightmare.goto(...)
  .type(...)
  .click(...)
  .wait(TIME_SPAN);

const path = await nightmare.path();
const title = await nightmare.title();
const cookie = await nightmare.cookies.get({ name: 'session'});
```

**Comment by ianstormtaylor** [comment]
Thank you @jekku that's a much better API, I didn't realize that was possible!

**Comment by jekku** [comment]
@ianstormtaylor please tell me if it worked. You can use babel for es6 and es7. :)

**Comment by ianstormtaylor** [comment]
@jekku yup it worked! Thanks

**Comment by jekku** [comment]
Alright! Happy hacking to Golden State - from Asia! :)
