### ISSUE TITLE
Ubuntu 14.04, timeout wait()

### ISSUE THREAD

**Issue by harso121** [segmentio/nightmare#952]
So I managed to get nightmarejs up and running and it was working perfectly for a while and now it just works sometimes and with some websites not at all..
I didn't change anything in the code, they just started appearing the next day, I already rebooted, they still persist.

Here is some output of the example:

      root@docker-512mb-fra1-01:~/node# xvfb-run --server-args="-screen 0 1024x768x24" node index.js
      https://github.com/segmentio/nightmare
      root@docker-512mb-fra1-01:~/node# xvfb-run --server-args="-screen 0 1024x768x24" node index.js
      https://github.com/segmentio/nightmare
      root@docker-512mb-fra1-01:~/node# xvfb-run --server-args="-screen 0 1024x768x24" node index.js
      Search failed: Error: .wait() timed out after 30000msec
          at Timeout._onTimeout (/root/node/node_modules/nightmare/lib/actions.js:453:10)
          at ontimeout (timers.js:365:14)
          at tryOnTimeout (timers.js:237:5)
          at Timer.listOnTimeout (timers.js:207:5)
      root@docker-512mb-fra1-01:~/node# xvfb-run --server-args="-screen 0 1024x768x24" node index.js
      https://github.com/segmentio/nightmare
      root@docker-512mb-fra1-01:~/node# xvfb-run --server-args="-screen 0 1024x768x24" node index.js
      Search failed: Error: .wait() timed out after 30000msec
          at Timeout._onTimeout (/root/node/node_modules/nightmare/lib/actions.js:453:10)
          at ontimeout (timers.js:365:14)
          at tryOnTimeout (timers.js:237:5)
          at Timer.listOnTimeout (timers.js:207:5)

And yes the server has a perfect internet connection stability, so it's not that.

**Comment by leoalves** [comment]
I had this issue  with lubuntu. I installed a new version of chrome and it fixed.

**Comment by harso121** [comment]
I don't even have chrome installed though, as I'm just using the console

**Comment by jekku** [comment]
Is this on sudo? Why?

**Comment by harso121** [comment]
Someone said that it worked for him putting it on sudo, so I was trying it here, but the output is the same whether sudo or not..

**Comment by schickling** [comment]
Same here. Doesn't happen all the time but in 1/3 cases. Any idea? This problem didn't occur in the past.

Here is a docker image with our setup: https://github.com/graphcool/prep/blob/master/docker/Dockerfile

**Comment by vshvydky** [comment]
all have the same problem, and developers are silent.

**Comment by rosshinkley** [comment]
Did something change on the source site?

**Comment by mekasan** [comment]
same problem :( anybody know how to fix ?

**Comment by harso121** [comment]
@rosshinkley no, it did not.

**Comment by mekasan** [comment]
My problem was, when proxy die or site blocked this proxy in process..

**Comment by gretro** [comment]
I'm having the same issue.

I extracted the HTML when the test fails, and the item I'm looking for is indeed present on the page. Anybody had any luck figuring this problem out?

**Comment by matthewmueller** [comment]
Hey folks, there's a bunch of great information in #224 and specifically: https://github.com/segmentio/nightmare/issues/224#issuecomment-365938300

This issue is currently too broad to solve since it depends on a lot on the website you're targeting. If you're still running into issues, please open a new issue with the full script or a runnable example and I'd be happy to help you further. 

Here's a simple template for writing an example:

```js
const Nightmare = require('nightmare')
const express = require('express')
const http = require('http')

main().catch(console.error)

function html(body) {
  return `<!doctype><html><head><meta charset="UTF-8"> </head><body>${body}</body></html>`
}

async function main() {
  const app = express()
  const server = await Server(app)

  app.get('/', (req, res) => {
    res.send(html(`server response here`))
  })

  const nightmare = Nightmare({
    loadTimeout: 45 * 1000,
    waitTimeout: 5 * 1000,
    show: true
  })

  await nightmare.goto(server.url, '/')

  // nightmare code here

  await nightmare.end()
  await server.close()
}

async function Server(handler) {
  const server = await new Promise((res, _rej) => {
    var s = http.createServer(handler)
    s.listen(0, 'localhost', function() {
      res(s)
    })
  })

  const address = server.address()
  return {
    url: `http://${address.address}:${address.port}`,
    close: function() {
      return new Promise((res, _rej) => server.close(res))
    }
  }
}
```
