### ISSUE TITLE
Using nightmarejs in AWS Lambda functions

### ISSUE THREAD

**Issue by riccardo-89** [segmentio/nightmare#953]
Hi!

I am having some issue trying to use nightmare inside an AWS Lambda.

My code works great locally, but when I deploy (I use browserify to bundle my lambda package, otherwise it would be 150MB), I receive this error:

`Electron failed to install correctly, please delete node_modules/electron and try installing again`

Did you manage to run it on this environment? thanks

cheers

R

**Comment by ajagnanan** [comment]
I couldn't get it to deploy because of electron's file size. I tried going back pre version 2.0 (before electron is used), but it didn't work either for me. I was going to try other scrapers, this looked feasible: http://casperjs.org

**Comment by riccardo-89** [comment]
thanks a lot @ajagnanan I will have a look into that, hope anyway that nightmare can be run somehow inside lambdas and that as solution is already out there :D thanks

**Comment by schnerd** [comment]
Building on @ajagnanan's answer, it's unlikely that nightmare can be used in lambda since the electron binary is over 130mb compressed, and [lambda's maximum deployment package size is 50mb](http://docs.aws.amazon.com/lambda/latest/dg/limits.html). Would be impressed if someone can find a way around this.

**Comment by sopel** [comment]
@schnerd - someone has found away around this: [dimkir/nightmare-lambda-tutorial](https://github.com/dimkir/nightmare-lambda-tutorial)

While that is an impressive workaround indeed, if you are not too invested in nightmare, you might also want to check out [graphcool/chromeless](https://github.com/graphcool/chromeless), which draws a lot of inspiration from nightmare, but has a native AWS Lambda story (refer to [How is this different from NightmareJS, PhantomJS or Selenium?](https://github.com/graphcool/chromeless#how-is-this-different-from-nightmarejs-phantomjs-or-selenium) for details).

**Comment by casesandberg** [comment]
Looks like this is resolved. I am going to close this for now but feel free to open a new issue if you are still having problems.

**Comment by iblessedi** [comment]
It used to work. After upgrading Lambda to Node v10 (AWS forces us to do that) dimkir/nightmare-lambda-tutorial stopped working. We need another solution.
