### ISSUE TITLE
Screenshots timing out

### ISSUE THREAD

**Issue by twolfson** [segmentio/nightmare#955]
In a recent Nightmare script, I was consistently getting timeouts occurring and wound up writing #945 to resolve timeouts not cleaning up after themselves properly. This issue is mostly for @Mr0grog so they can debug issues on triggering frames in the said script. I made a minimal example here:

https://gist.github.com/twolfson/b666177b87ae339f3ab2183c2be77690

Things I noticed:

- Removing the `wait(100)` will cause it to start passing
- Removing 1 screenshot call will cause it to start passing
- Moving from `getbootstrap.com` to `google.com` will cause it to start passing

Best of luck on your debugging!

/cc @Mr0grog

**Comment by FredrikNoren** [comment]
Experiencing the same issue here

**Comment by entrptaher** [comment]
Calling screenshot function multiple times resulted in this problem.

![image](https://cloud.githubusercontent.com/assets/8284972/24954537/a3a668da-1fa1-11e7-91fe-95bf5cfa1a91.png)

**Comment by chunsli** [comment]
Bumping this up! Experiencing the same issue as well! Thanks guys!

**Comment by lokidokicoki** [comment]
bump! same issue

**Comment by ucjonathan** [comment]
bump, same issue

**Comment by Mr0grog** [comment]
Y'all should probably be bumping #945 since this depends on that.

**Comment by Mr0grog** [comment]
@casesandberg would you like to see a PR for this now that #945 is merged, or is this pretty much being left alone now that you are moving towards headless Chrome?

**Comment by Howardwlo** [comment]
@Mr0grog I'm running into this issue and I'd love to get the PR :). What's this about headless Chrome?

**Comment by Mr0grog** [comment]
The Segment folks are rewriting this library to use Chrome (headless) and not Electron, so the way a lot of stuff like this that heavily depends on the API for *controlling* the browser will have to be completely different.

**Comment by Howardwlo** [comment]
@Mr0grog Oohhh. Are there updates about the switch to Chrome somewhere?

**Comment by Mr0grog** [comment]
I think it’s on the v3 branch. I don’t know any details beyond what I’ve already stated, which was what @casesandberg told me in a reply on another issue (lost track of it now).

**Comment by matthewmueller** [comment]
Hey folks, we're going to stick with electron for now since puppeteer is already a great option for headless chrome.

Does the merged PR resolve this issue?

**Comment by Mr0grog** [comment]
If the merged PR you are referencing is #945, it does not solve this issue (though it was blocking the solution/the work for this issue).

**Comment by rasenplanscher** [comment]
@matthewmueller @Mr0grog 
Is this fixed, or should it be reopened?

**Comment by Mr0grog** [comment]
No change from my previous comment—unless the code in `frame-manager.js` has been changed (and it does not appear to have been), then no, this is not fixed.
