### ISSUE TITLE
How to get all network requests

### ISSUE THREAD

**Issue by jineshshah36** [segmentio/nightmare#957]
I want to get a list of all network requests the page makes, specifically a list of all the images that are downloaded. Here is my attempt at getting network request data, but I'm very lost.

```
const Nightmare = require('nightmare')
const nightmare = Nightmare({ show: false })

Nightmare.action('testAction', function(name, options, parent, win, renderer, done) {
    parent.respondTo('testAction', function(done) {
      win.WebRequest.onCompleted(filter, (details) => {
        done(details)
      })
    })
    done()
  }, function(done) { this.child.call('testAction', done) })

nightmare
  .goto('https://www.everlane.com/collections/womens-newest-arrivals/products/womens-penny-loafer-black')
  .testAction()
  .end()
  .then(result => {
    console.log(result)
  })
  .catch(error => {
    console.error('Search failed:', error)
  })
```

**Comment by scottmas** [comment]
Something similar to the PhantomJS event "onResourceRequested". See http://phantomjs.org/network-monitoring.html

**Comment by jineshshah36** [comment]
Isn't that what `win.WebRequest.onCompleted` does? I'm more just confused about how to make it work in nightmare.js

**Comment by rosshinkley** [comment]
Depending on what your needs are, you _might_ want to have a look at [`onBeforeRequest`](https://github.com/electron/electron/blob/master/docs/api/web-request.md#webrequestonbeforerequestfilter-listener) instead.  You may also want to have a look at [`nightmare-load-filter`](https://github.com/rosshinkley/nightmare-load-filter) as it might get you closer to what you're after.

Are you planning on doing an action with the images downloaded, or are you just trying to log them?

**Comment by jineshshah36** [comment]
Interesting, I'll take a look, thanks!

**Comment by d3ce1t** [comment]
I don't know about the requests. But you can log all of the responses. I have just commented that in https://github.com/segmentio/nightmare/issues/784#issuecomment-277490918.

**Comment by rosshinkley** [comment]
Considering this resolved for the moment.  If you have any more problems, feel free to reopen/open a new issue.

**Comment by AlexFerreras** [comment]
@jineshshah36 did you get your answer? 
I´m needding the same. Get all the network request the page is doing by nighmare js. 
Can someone help me?...

**Comment by jineshshah36** [comment]
@AlexFerreras  I switched to puppeteer a long time ago. Haven't . looked back
