### ISSUE TITLE
Bad repeating table headers

### ISSUE THREAD

**Issue by krulik** [segmentio/nightmare#958]
I have a really weird problem while using NightmareJS to print PDF:

A table header is repeated on the top of **the same page** where it's original ("source") occurrence, and not on the **next page** like expected.

The Chrome print preview for this page doesn't show this behaviour.

The table is properly defined with a `thead` etc. and is inside a `div.page` which has `page-break-after: always`.

I can probably workaround this by using an opaque strip on the top of the page to hide this orphan table header but it's hacky and I wonder whether someone had encountered a better solution.

Also asked on SO: http://stackoverflow.com/q/41677785/36821

**Comment by beastmike1** [comment]
I have the same problem
![captura](https://cloud.githubusercontent.com/assets/11091851/23708041/de2fac9e-0414-11e7-8e89-b08add4dba66.PNG)

**Comment by casesandberg** [comment]
Are you still having trouble and have you tried 2.10.0? I am going to close this, but feel free to open a new issue if you are still having problems.
