### ISSUE TITLE
Run custom code while procesing nightmare

### ISSUE THREAD

**Issue by novoxudonoser** [segmentio/nightmare#962]
How can I run custom code while nightmare goes? For example I wan to make the extrnal rest call or call a script.

**Comment by rosshinkley** [comment]
Depends on where you need to make the call from.  Are you trying to make the call from the Electron client (from the loaded page) or from your script?

From your script, you could use `.then()`:
```js
var someApi = require('SomeApiLibrary');
nightmare
  .goto(someUrl)
  .then(()=>{
    return new Promise((resolve, reject) => {
      api.someRestCall('parameter', (err, result) => {
        if(err) return reject(err);
        resolve(result);
      })
    })
  })
  .then((apiResult) => {
    ....
  });
```

Doing so from the client is marginally more complicated, but you could easily inject something that handles HTTP requests for you (like jQuery, for example).

**Comment by novoxudonoser** [comment]
I also found god examle [here](http://stackoverflow.com/questions/37857545/nightmare-js-conditional-browsing):
```
var Nightmare = require('nightmare');
var vo = require('vo');

vo(function * () {
  var nightmare = Nightmare({
    show: true,
    paths: {
      userData: '/dev/null'
    }
  });

  var title = yield nightmare
    .goto('http://www.example.com/')
    .wait('h1')
    .evaluate(function() {
      return document.querySelector('title')
        .innerText;
    });

  if (title == 'someTitle') {
    yield nightmare.goto('http://www.yahoo.com');
  } else {
    yield nightmare.goto('http://w3c.org');
  }

  //... other actions...

  yield nightmare.end();
})(function(err) {
  if (err) {
    console.log('caught', err);
  } else {
    console.log('done');
  }
});
```

Mabe add this too example? It will be useful for beginners.

**Comment by casesandberg** [comment]
Looks like this is resolved. I am going to close this for now but feel free to open a new issue if you are still having problems.
