### ISSUE TITLE
Add paste functionnality

### ISSUE THREAD

**Issue by coyotte508** [segmentio/nightmare#963]
This is a suggestion for the ability to directly paste content in a field, instead of typing it out letter by letter.

**Comment by jekku** [comment]
You mean to trigger a ctrl + v keypress? You can do that using existing functions in the API.

If typing out letter by letter annoys you, you can use nightmare.insert(<String>).

**Comment by jekku** [comment]
I think tho this would be useful in making tests for a webpage that disallows pasting to fields.

**Comment by coyotte508** [comment]
Didn't know about `insert`...

I tried it (replaced `type` with it) and it doesn't work, maybe I'm not selecting the precise selector and `.insert` would need that level of detail, or maybe it needs a `paste` or `keyboard event` (quite the custom design on the `input` in question...).

**Comment by rosshinkley** [comment]
@coyotte508 do you have a small example of your problem?

**Comment by coyotte508** [comment]
Sorry, not a small one...

https://gist.github.com/coyotte508/7bffdd66e251917c003bebe94ce343e3

It's inside a payment page. `.type` works but not `.insert`. I use the `nightmare-iframe-manager` plugin. The field itself is inside an iframe, maybe it's due to that too.

**Comment by casesandberg** [comment]
Are you still having trouble and have you tried 2.10.0? I am going to close this, but feel free to open a new issue if you are still having problems.
