### ISSUE TITLE
back method does not use disk cache to load the previous page

### ISSUE THREAD

**Issue by ericksli** [segmentio/nightmare#966]
I want to go back to previous page but I found that Nightmare does not load the previous page from disk cache. Instead it sends the previous page request to server which produces different results compared with Google Chrome.

Clicking back in Google Chrome to load previous page:
Status Code: 200 OK (from disk cache)

Calling `back` in Nightmare to load previous page:
Status Code: 200 OK

Can I enable Nightmare to load from disk cache when I call `back`?

**Comment by casesandberg** [comment]
Go ahead and try out the headless Chrome implementation in v3, handles the caching automatically! https://github.com/segmentio/nightmare/tree/v3.

I am going to close this, but feel free to re-open if it's still an issue.
