### ISSUE TITLE
.goto(url) is stuck for a particular url, gotoTimeout does not work, default timeout does not work, high memory used by Electron processes

### ISSUE THREAD

**Issue by kdgit1** [segmentio/nightmare#968]
Facing a strange issue with this particular url. Almost every other Url I have tested is working.
**.goto(url) is stuck , specified gotoTimeout does not work, default gotoTimeout of 30 sec also does not work, high memory used by Electron processes**: 

Here's the code outline:

let pageurl = "http://www.gamestop.com/pc/consoles/alienware-steam-machine-i7-1tb/121863"

// wrapped in promise -- 
return nightmare
      .goto(pageurl)
      .wait(waitInMs) 
      .evaluate(function () {
        return {
            // will return what is needed  here including html
        }
      })
      .end()
      .then(function (value) {
          // console.log( " -- made it past goto() ---   // * does not make it to this point 
         // return value  and kill nightmare.
          resolve(value)
       })
        . catch ( (err) => { 
         //  kill nightmare  and resolve( ) or reject( ) 
     })

Note: I have tried passing gotoTimeout : 5000   //ms in the nightmare constructor - but it does not seem to work either.
Default timeout of 30 sec also does not seem to be working. 
The process simply stops at .goto() and memory usage by electron goes to 12gb on my mac.

Here's the error message when process is manually terminated:
Failed: Error: Evaluation timed out after 30000msec.  Are you calling done() or resolving your promises?
    at Timeout._onTimeout (........./node_modules/nightmare/lib/actions.js:509:10)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

Thanks.

**Comment by kdgit1** [comment]
.. and nothing useful when run with DEBUG:


  nightmare queuing process start +4ms
  nightmare queueing action "goto" for http://www.gamestop.com/pc/consoles/alienware-steam-machine-i7-1tb/121863 +0ms
  nightmare queueing action "wait" +1ms
  nightmare queueing action "evaluate" +0ms
  nightmare running +0ms

( and it stays at this point - while memory usage continues to rise ) 

All I am looking for is an automated way for nightmare to exit out / kill itself after waiting for 15 seconds or so if there is no success in fetching the url.

thanks a lot for any pointers.

**Comment by navossoc** [comment]
Same here...
Windows 10 x64 + Nightmare 2.9.1 + Electron 1.4.15

For now, I think you can try to create some workaround with:
`.on("did-start-loading". ...);`

And
`nightmare.halt()`;

It seems the electron renderer process hangs.

**Comment by navossoc** [comment]
Just a tip for anyone who wants to fix this bug later.

If you open electron.exe and type on the console:
`window.location = "http://www.gamestop.com/pc/consoles/alienware-steam-machine-i7-1tb/121863"`

The browser didn't hang and load the page correctly.
So, maybe it's a startup switch flag or something with nightmare + IPC itself waiting for the "did-finish-load" event.

I can not help much more, I started using the nightmare only just a few days ago.

**Comment by kdgit1** [comment]
Thanks **navossoc** - I'll try the workaround per your suggestion.
Meanwhile - if anyone has dealt with this issue in the past / better approach / fix - that would certainly help.

**Comment by vshvydky** [comment]
I also have lost an electron and sometimes hangs in the memory. complete nightmare at the same time does not work. I tried to change all the timeouts, without results.

**Comment by rosshinkley** [comment]
@navossoc the _unload_ bindings are preventing the page from fully loading?  o_O

That particular chunk was added so if you attempt to navigate away from a page, it prevents an unclickable modal dialog from cropping up, which would cause Nightmare to freeze.  (Same goes for `alert`, `confirm`, etc.)

Under Nightmare 2.9.1, I could not recreate the behavior you're seeing.  Out of curiosity, what are you returning from `.evaluate()`?

**Comment by navossoc** [comment]
@rosshinkley As far I have tested it, yes...

My script was pretty simple, just a goto(), nothing more than that.

I think @kdgit1 can give you more details about the issue.

[]'s

**Comment by albus01** [comment]
I have the same problem. I have to add code: setTimout(()= { nightmare.halt() , 600000} , but this can not solve the problem from base.

**Comment by Khady** [comment]
I can also reproduce the issue if needed.

**Comment by ronolivarph** [comment]
same problem here, has anyone solved this yet?

**Comment by matthewmueller** [comment]
Hey guys,

The problem is that sites like this one take more than 30 seconds to fully load. Testing it myself, this website took: `60930.746ms`. 

`nightmare.goto` waits until the `load` event, which means all images, JS, and CSS in the main frame needs to be loaded, parsed and executed. In other words, when the spinner stops spinning in chrome.

You may want to follow along with #1138, we'll be soon adding a way to listen for a `DOMContentLoaded `, which should be much faster.
