### ISSUE TITLE
Mobiles ?

### ISSUE THREAD

**Issue by joeblew99** [segmentio/nightmare#969]
Sorry about a high level question, but can I use this on web apps for mobile ?

I currently use agousti ( golang) with different web drivers.

So I am trying to work out how that and this fit together architecturally. So I am hoping you don't mind giving a quick explanation.

**Comment by rosshinkley** [comment]
Presumably, yes?  It depends on what your needs are, but you can certainly set up the viewport and useragent to mimic a mobile device.  Beyond that, Electron is more or less a full Chromium instance, so there may be some storage differences with what you see no the mobile (I can't think of one offhand, but it wouldn't surprise me).  I don't feel like that necessarily answers your question - what are you trying to test/do?

**Comment by casesandberg** [comment]
Can you provide some more information? I am going to close this for now but feel free to re-open it with some more details.

**Comment by emcniece** [comment]
This is possible - I am in the process of migrating from CasperJS/PhantomJS to Nightmare.

The trick with getting proper dimensions for mobile is CSS scaling the page for the right screen size. Nightmare lets us set the `useragent` and `viewport`, so along with this you can `evaluate` and modify the body class to format scale for each platform.

Here are my scale styles:

```css
body.phantom-ios {
    transform: scale(3);
    transform-origin: 0% 0%;
    width:33.33333%;
    height:33.33333%;
}

body.phantom-android-hi {
    transform: scale(3);
    transform-origin: 0% 0%;
    width:33.33333%;
    height:33.33333%;
}
```

... and here are some viewport defs that I use for getting screenshots:

```js
const agents = {
    iphone6Plus: 'Mozilla/5.0 (iPhone; CPU iPhone OS 6_0 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10A5376e Safari/8536.25',
    ipadPro: 'Mozilla/5.0 (iPad; CPU OS 6_0 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10A5376e Safari/8536.25',
    nexus7: 'Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19'
}

module.exports = {
    agents: agents,
    platforms: [
        {
            name: 'iphone6Plus',
            imagePath: 'fastlane/screenshots/en-CA/',
            agent: agents.iphone6Plus,
            class: 'phantom-ios',
            width: 1242,
            height: 2208
        },
        {
            name: 'ipadPro',
            imagePath: 'fastlane/screenshots/en-CA/',
            agent: agents.ipadPro,
            class: 'phantom-ios',
            width: 2048,
            height: 2732
        },
        {
            name: 'galaxyS6',
            imagePath: 'fastlane/metadata/android/en-CA/images/phoneScreenshots/',
            agent: agents.nexus7,
            class: 'phantom-android-hi',
            width: 1440,
            height: 2560
        },
        {
            name: 'nexus7',
            imagePath: 'fastlane/metadata/android/en-CA/images/sevenInchScreenshots/',
            agent: agents.nexus7,
            class: 'phantom-android-lo',
            width: 800,
            height: 1280
        }
    ]
};
```

**Comment by joeblew99** [comment]
@emcniece nice. 

If i get the big picture here the problme is that the DPI for mobile apps is too high to fit on a desktop screen for testing ?

I was using Electron but started using a light weight one designed for golang.

here it is:
github.com/zserge/webview

its written in c++, with a goalng wrapper. 

It uses the Desktops native Browser and so work on Windows 10 store apps, as Microsoft limit store apps to use only their Edge browser. Pulling an Applie IOS move there..

Its small too of course. 10 MB versus 200 MB, and makes it very easy to build apps with the web gui and golang code in one.

I have no idea yet on the dependency chain between nightmware and Electron. 
Gotta dig deeper and see whats what..
