### ISSUE TITLE
.*$:21Uncaught Error: Cannot find module '/package.json'.

### ISSUE THREAD

**Issue by ryderlee** [segmentio/nightmare#972]
Hi. May I ask is that just me or anyone may face similar issue, I was trying to run nightmare code in my app but the following error returned : 

```
.*$:21Uncaught Error: Cannot find module '/package.json'.
```
I am using webpack under electron, version of nightmare is "2.9.1". Any idea? Thanks.

**Comment by casesandberg** [comment]
Are you still having trouble and have you tried 2.10.0? I am going to close this, but feel free to re-open if it's still an issue.
