### ISSUE TITLE
Binary compatibility with AWS linux / Lambda

### ISSUE THREAD

**Issue by diit** [segmentio/nightmare#974]
Been scowering for a solution for 3 days now, none of theses worked or asisted:

- [534](https://github.com/segmentio/nightmare/issues/534)
- [953](https://github.com/segmentio/nightmare/issues/953)
- [185](https://github.com/segmentio/nightmare/issues/185)

I have compiled the electron binary in an ec2 instance and given its path to the electronPath config option, but I still recieve a `{ [Error: spawn EACCES] code: 'EACCES', errno: 'EACCES', syscall: 'spawn' }`.

Any ideas on how to get this running?

**Comment by sweinertjr** [comment]
+1 I'm also interested in knowing how to set this up. I'm getting `nightmare electron child process exited with code 126: permission problem or command is not an executable - you may not have all the necessary dependencies for electron`

**Comment by sweinertjr** [comment]
Perhaps this is helpful:

https://gist.github.com/dimkir/f4afde77366ff041b66d2252b45a13db

**Comment by casesandberg** [comment]
Go ahead and try out the headless Chrome implementation in v3, it allows you to connect to a remote server! https://github.com/segmentio/nightmare/tree/v3.

I am going to close this, but feel free to re-open if it's still an issue.
