### ISSUE TITLE
Async page interaction within Custom Actions

### ISSUE THREAD

**Issue by shennan** [segmentio/nightmare#976]
Can we use all actions within a Nightmare custom action?

I'm attempting to define a generic login action as the code is reused many times. Here is my custom action:

```js
Nightmare.action('login', function (done) {
  
  this
    .goto(BASE_URL)
    .type("input[name='user[email]']", "test@email.com")
    .type("input[name='user[password]']", "password")
    .click("*[type=submit]")
    .then(() => {
      console.log('login action done')
      done()
    })

})
```

And an example of it being used in a test:

```js

it("allows to log in", function(done) {
    
    Nightmare({show: true})
      .login()
      .end()
      .then(function() {
        console.log('parent test done')
        done()
      })
  })
})
```

The action goes ahead as expected, and it even calls the callback in `then()` (i.e `login action done` is printed to terminal), but the chain of events stops there. The second `then()` callback, in the test suite, never gets called.

I'm sure I'm missing something simple here - or perhaps custom actions were not designed for this purpose?

**Comment by ysimonson** [comment]
Sounds like it might be the same as #959 -- see the discussion after the initial ticket

**Comment by rosshinkley** [comment]
Related, yes, but not the same. I think it's closer to #859 - the TL;DR is you shouldn't use `.action()` for defining custom chains.  Use `.use()`.
