### ISSUE TITLE
Use html string as page

### ISSUE THREAD

**Issue by ericadamski** [segmentio/nightmare#977]
Instead of requesting a live page it would be ideal to push a locally generated html string to have electron render it. This will mainly be useful for css regression testing though a test runner like jest.

I am very willing to help implement this but am unsure where to start.

**Comment by urlysses** [comment]
I can't test if this works with nightmare at the moment but maybe a [data URI](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs) could work?

Something like:
```
data:text/html,<!DOCTYPE html><html><head><meta charset="utf-8"><title>Ok</title></head><body>some body</body></html>
```

or (base64 converted):
```
data:text/html;base64,PCFET0NUWVBFIGh0bWw+PGh0bWw+PGhlYWQ+PG1ldGEgY2hhcnNldD0idXRmLTgiPjx0aXRsZT5PazwvdGl0bGU+PC9oZWFkPjxib2R5PnNvbWUgYm9keTwvYm9keT48L2h0bWw+
```

**Comment by ericadamski** [comment]
@urlysses I will give this a try thank you!

**Comment by ericadamski** [comment]
@urlysses using a plain string data uri works! Thank you for the suggestion!

**Comment by urlysses** [comment]
Thanks for checking @ericadamski. Glad I could help :--)
