### ISSUE TITLE
nightmare.screenshot is not a function

### ISSUE THREAD

**Issue by ericadamski** [segmentio/nightmare#978]
I have the very simple code here

```javascript
import Nightmare from 'nightmare';
import path from 'path';

describe('avatar', () => {
    fit('should screenshot', async () => {
        const nightmare = new Nightmare({ show: true, frame: true });

        await nightmare
            .goto('https://github.com')
            .screenshot()
            .end();
    });
});
```

When run with [Jest](https://facebook.github.io/jest) this is the terminal output I receive:

```
 FAIL  components/__tests__/avatar/avatar.spec.jsx
  ● avatar › should screenshot

    TypeError: nightmare.goto(...).screenshot is not a function
```

It doesn't matter which function I use after the `goto` they give the same `TypeError: nightmare.someApiFunction is not a function`.

This is exactly the package I need but it doesn't seem to work in my environment.

Help 😫

**Comment by entrptaher** [comment]
Perhaps it's because you are not calling `.then()` after `.end()`
```js
nightmare
 .goto('https://github.com')
 .screenshot()
 .end()
 .then(function(){console.log("Screenshot Saved")})
```

**Comment by ericadamski** [comment]
Thank you @entrptaher I will try this out

**Comment by ericadamski** [comment]
This still says that screenshot isn't a function.

**Comment by entrptaher** [comment]
Here is how I did this.

package.json
```js
{
  "name": "jestify",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "jest"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "jest": "^18.1.0",
    "nightmare": "^2.9.1"
  }
}
```

nightmare.test.js
```js
const takescreenshot = require('./nightmare');

test('Should Take Screenshot', () => {
  return takescreenshot().then((data) => {
    expect(data).toBe('Screenshot Done');
  });
})
```

nightmare.js
```js
var Nightmare = require('nightmare');

function takescreenshot(){    
  var nightmare = Nightmare({ show: true });
  return nightmare
  .goto('https://duckduckgo.com')
  .screenshot("test.png")
  .end()
  .then(function (result) {
    return ("Screenshot Done");
  })
  .catch(function (error) {
    console.error(error);
  });
  }

module.exports = takescreenshot
```

**Comment by rosshinkley** [comment]
@ericadamski how are you running async/await?  Node 7 or Babel or...?

**Comment by ericadamski** [comment]
I am using both Node 7 and babel.

**Comment by casesandberg** [comment]
Are you still having trouble and have you tried 2.10.0? I am going to close this, but feel free to re-open if it's still an issue.

**Comment by j622amilah** [comment]
I tried the exact same code example above with jest, and nothing outputs or saves. It just hangs and runs out of time. I set the timeout to be longer (9000), but nightmare can never return an html link or screenshot. Did anyone find a solution for this?
![Screenshot from 2023-11-21 16-57-52](https://github.com/segment-boneyard/nightmare/assets/91731082/606a7257-b366-470f-a6d2-fc3e6ab45a97)

**Comment by entrptaher** [comment]
> NOTICE: This library is no longer maintained.

You should start using playwright or puppeteer.
