### ISSUE TITLE
Document what run() does

### ISSUE THREAD

**Issue by ripper234** [segmentio/nightmare#979]
The main page does not mention the run() method.
However several examples around the web, including #226 use run() as **the** way to run Nightmare tests.

Can you add some doc to the readme about when to use it / not use it, and what are its limitations (e.g. I believe you can't call `run()` twice?)

**Comment by rosshinkley** [comment]
TL;DR: don't use `.run()`.  It's a holdover from Nightmare 1.x.  Use `.then()` instead.

For a more protracted conversation with more information/links, see #575.  Also, this [example](https://github.com/rosshinkley/nightmare-examples/blob/master/docs/beginner/callbacks.md) in `nightmare-examples` may be of some use.

Merging with #575.
