### ISSUE TITLE
.on(confirm) does not confirm the dialogue

### ISSUE THREAD

**Issue by soupdiver** [segmentio/nightmare#98]
I've got a site where I have to confirm a request. This is done via JavaScript confirm method.
```
var nightmare = new Nightmare()
  .on('confirm', function(msg) {
      console.log(msg);
      return true;
    })
  .goto()
  ....
```
I can see the message on the console but I'm stuck on the page with the confirmation and the request is not send properly.
[Phatom API](https://github.com/ariya/phantomjs/wiki/API-Reference-WebPage#webpage-onConfirm) says I just have to return `true`.

**Comment by reinpk** [comment]
closing now that we've moved to electron over phantomjs
