### ISSUE TITLE
network monitoring - exporting as har

### ISSUE THREAD

**Issue by lucaswxp** [segmentio/nightmare#986]
Hey guys.

Does nightmare have any monitoring capabilities? I need to export the requests/responses as HAR, but can't seem to find any docs in how to.

Regards!

**Comment by IronistM** [comment]
You'll need the `nightmare-har-plugin`. Then you can something like the following ([source](https://gist.github.com/justinph/0ffd7b7a443b82e4941636b65067ad1a)).

```
nightmare
    .viewport(1024, 768)
    .waitForDevtools()
    .goto(url)
    .wait('body')
    .getHAR()
    .end()
    .then((result) => {
        let onLoad = result.pages[0].pageTimings.onLoad;
        console.log(onLoad);
     });
```

**Comment by lucaswxp** [comment]
Ahh thanks!

**Comment by lucaswxp** [comment]
Sorry to bother, but I'm getting this from the console:

"Not allowed to load local resource: chrome://version/?get-har"

The script runs successfully, but should I worry about this error?

**Comment by lucaswxp** [comment]
I only noticed now, but HAR is not correct.

I have the following entry: 

```
"response": {
				"_transferSize": 947,
				"bodySize": 290,
				"content": {
					"compression": 20,
					"mimeType": "text/html",
					"size": 310
				},
```

Where is the body? It says it's 310 bytes, but no body is present?

**Comment by lucaswxp** [comment]
So for anyone stumbling into this, I have decided to use browsermob to capture my har content:
https://github.com/lightbody/browsermob-proxy

It acts as a proxy, produce reliable HAR and I can still use Nightmare if you loke.

**Comment by rpascal** [comment]
@lucaswxp Could you provide an example how you achieved this using browsermob-proxy? Does this method work with show set to false as well?

**Comment by lucaswxp** [comment]
@rpascal Sorry, I don't have any samples. About your question: probably. Since browsermob is a proxy, should have no impact on nightmare functions.
