### ISSUE TITLE
extract data from table

### ISSUE THREAD

**Issue by gencharitaci** [segmentio/nightmare#987]
Hi everyone,
I'm trying to extract data from the url below. What am I doing wrong. 

Please help me. 
Any help would be appreciated

`var Nightmare = require('nightmare'),
  nightmare = Nightmare(/*{ show: true }*/)

/* nightmare.inject('js', 'node_modules/jquery/dist/jquery.js'); */
nightmare.goto('https://goo.gl/9z0sZv')
  .evaluate(function(){
	var arr = [], 
	linkler = $("a[href^='https://goo.gl/nY5ey1']").each(function(){
		  $(this).attr("href");
	});
	for(var i=0; i<linkler.length; i++) {
	  arr.push(linkler[i].href);
	}
	alert(arr);
  }).end()
  .then(function(result){
    console.log(result);
  })`

**Comment by vshvydky** [comment]
```var Nightmare = require('nightmare'),
nightmare = Nightmare({ show: true });

/* nightmare.inject('js', 'node_modules/jquery/dist/jquery.js'); */
nightmare.goto('https://goo.gl/9z0sZv')
.evaluate(function(){
    var arr = [],
    linkler = $("a[href^='https://goo.gl/nY5ey1']").each(function(){
    $(this).attr("href");
    });
    for(var i=0; i<linkler.length; i++) {
        arr.push(linkler[i].href);
    }
    //alert(arr);
    return arr; /// -- send arr in then as result
})
.end()
.then(function(result){ // <--- its arr in result
    console.log(result);
})
```

**Comment by zeluspudding** [comment]
Is it just me or is selecting data from a table in that way just a million times more complex than it needs to be. I come from a Python scraping background where lifting table, rows or columns is a one liner. I'd love that functionality in nightmare.js.

How can one generally lift, say, the first column of a table using nightmare/injecting js?

**Comment by casesandberg** [comment]
The easiest way by far is to use jquery. I am going to close this for now but feel free to re-open it you are still having problems.
