### ISSUE TITLE
How to make Nightmare not to follow redirections?

### ISSUE THREAD

**Issue by d3ce1t** [segmentio/nightmare#989]
I have checked that Nightmare follows 3xx redirections transparently (reporting 200 as status code). I think this behavior is right most part of the time. However, it would be useful if this behavior could be disabled optionally.

AFAIK it's not possible to disable it right now, isn't it?. So, is there a workaround for this?. My use case is for a web site analyzer. However, I think it could also be useful for web testing.

Thank you very much.

**Comment by entrptaher** [comment]
Actually you can solve it by using the **events**.

```js
var Nightmare = require('nightmare');
var nightmare = Nightmare({ show: true , alwaysOnTop: false})

// Do something with redirection
function redirectfunction(e,o,n,i,h,r,r2,h){
  console.log("It's redirecting and the http header shows this: ")
  console.log(h);
  // halt it if you want
  nightmare.halt()
}

nightmare
  .on("did-get-redirect-request", redirectfunction)
  .goto('https://httpbin.org/redirect/1')
  .end()
  .then(function (result) {
    console.log(result);
  })
  .catch(function (error) {
    console.error('Search failed:', error);
  });
```

the result might be as follows:
```
> node test_delete_it.js
It's redirecting and the http header shows this:
{ 'access-control-allow-credentials': [ 'true' ],
  'access-control-allow-origin': [ '*' ],
  connection: [ 'keep-alive' ],
  'content-length': [ '215' ],
  'content-type': [ 'text/html; charset=utf-8' ],
  date: [ 'Fri, 03 Feb 2017 20:58:11 GMT' ],
  location: [ '/get' ],
  server: [ 'nginx' ] }
Search failed: Nightmare Halted
```

Learn more about this here, 
 - https://github.com/segmentio/nightmare#onevent-callback
 - and here, https://github.com/electron/electron/blob/master/docs/api/web-contents.md

**Comment by d3ce1t** [comment]
Thank you very much for your response. I think this is what I was looking for. It works perfectly :).
