### ISSUE TITLE
.useragent() is broken in 2.9.1

### ISSUE THREAD

**Issue by schickling** [segmentio/nightmare#990]
The newest version of Nightmare (2.9.1) stops `nightmare.useragent('my-agent')` from working (i.e. you cannot override the default useragent).

Downgraded to 2.9.0 and it works again.

**Comment by vshvydky** [comment]
hmmm, in my nm 2.9.1 on windows action useragent works

**Comment by jekku** [comment]
2.9.1 on archlinux latest works for me. It helps maybe if you can add details like your Operating system and its version :)

**Comment by schickling** [comment]
Weird. I've tested it twice and removed `node_modules` each time. I'm on MacOS Sierra.

**Comment by rosshinkley** [comment]
More bizarre still, I don't think `.userAgent()` has been touched in some time (almost a year!).  I'd say it might be an Electron issue, but there's not a version difference between 2.9.0 and 2.9.1.

Anyone else with a Mac out there that can validate this issue?

**Comment by casesandberg** [comment]
Are you still having trouble and have you tried 2.10.0? I am going to close this, but feel free to open a new issue if you are still having problems.
