### ISSUE TITLE
Is it possible to execute a function that is written from the javascript of a website?

### ISSUE THREAD

**Issue by pfftdammitchris** [segmentio/nightmare#996]
You know when you visit a page in a website and view the source code, sometimes you see an element execute a javascript function? For example:

`<button type="button" id="chocolate" onclick="EditShipment()">Click me</button>`

Can I use nightmare to visit this page and execute EditShipment() ? And if so, is it possible to pass in our own arguments to that function's argument?

**Comment by urlysses** [comment]
Sure. If the code on the site is defined and written exactly as in your description, then we can assume that `EditShipment` exists within the global namespace. If that's really the case, you should be able to call `EditShipment` from within a normal nightmare `evaluate` function.

Here's an example:

```node.js
nightmare.goto('http://www.example.org')
    .evaluate(function () {
        EditShipment(/* custom arguments ...*/);
    })
    .end()
    .then();
```

**Comment by rosshinkley** [comment]
Looks good to me.  Considering this issue closed.  If you have any more qusetions, feel free to reopen/open a new issue.
