### ISSUE TITLE
how to wait for the event dynamically?

### ISSUE THREAD

**Issue by overflowz** [segmentio/nightmare#998]
Is there any way to wait for event happen dynamically?
Here's the scenario.

1) page loads
2) after page loads, you do authentication.
3) when you submit, page finishes loading (dom-ready), but the website itself is really complicated and it also loads other things dynamically (ajax calls inside iframes, other script loads another script and so on), which I have no clue how to wait for.

wait(ms) is not acceptable, cause it might give non accurate results often.

The way I'm doing is that is following:

```
nightmare.on('did-get-response-details', async (event, status, newURL, originalURL, httpResponseCode, requestMethod, referrer, headers, resourceType) => {
    if (newURL.indexOf('file_to_wait_load.php') !== -1) {
      // NOTES: without file_to_wait_load.php, clicking on this does nothing at all, but it's still visible, same properties, etc.
      await nightmare.click('#element');
    }
  });

  await nightmare.goto('...');
  await nightmare.click('#loginHeader > li:nth-child(2) > a');
  await nightmare.type('#username', 'mydesiredusername');
  await nightmare.type('#password', 'randompassword')
  await nightmare.click('#submitButton');
  // here happens that click method.
  // but I want to able to use nightmare.on() HERE, not globally though.
```

is there any way to do that or some other workarounds?

**Comment by overflowz** [comment]
since I hurry and having not much knowledge about internal stuff, does this action seems good (well, it would be much better with timeouts as well, but dunno how to do it).

```
Nightmare.action('waitForResource',
  function (name, options, parent, win, renderer, done) {

    function _onResponseDetail(event, status, newURL, originalURL, httpResponseCode, requestMethod, referrer, headers, resourceType) {
      parent.respondTo('waitForResource', function (resourceName, done) {
        if (newURL.indexOf(resourceName) !== -1) {
          win.webContents.removeListener('did-get-response-details', _onResponseDetail);
          done();
        }
      });
    }

    win.webContents.on('did-get-response-details', _onResponseDetail);
    done();
  },
  function (resourceName, done) {
    this.child.call('waitForResource', resourceName, done);
  });
```

**Comment by rosshinkley** [comment]
What you have is fine. You could probably accomplish a close approximation using the [asynchronous form of `.wait()`](https://github.com/segmentio/nightmare#evaluatefn-arg1-arg2).  Waiting for a resource like you have it would be kind of tough without the action as you have it written, though.

Answering your second question: that usually happens when you attach an action to Nightmare multiple times.  That error was put there as a warning in case there were naming collisions for actions, which adding the same action multiple times would certainly cause.

**Comment by vshvydky** [comment]
hi, Rosshinkley!
For each job created another instance through: let nightmare = Nightmare(config). Every nightmare is an instance of a large list of tasks, including the creation of screenshots, upload files. I guess there are jobs that can potentially lock code on the browser side, after which the connection between the processes is terminated. I used .halt method, but it does not always help. I came to the idea to explicitly use fkill electron off ( nightmare.proc.pid). Separately, I note that the assignments that I give not block browser evalyuate.

In addition, I note that there is no electron closing event, if the electron close the arms, the nightmare did not know about it. But this is the problem of the above does not apply, a further observation.

**Comment by overflowz** [comment]
well, I dag in documentation / examples and this action now works fine! (it is just missing timeouts though).

```
Nightmare.action('waitForResource',
  function (name, options, parent, win, renderer, done) {

    parent.on('waitForResource', function (resourceName) {
      win.webContents.on('did-get-response-details', function (event, status, url) {
        if (url.indexOf(resourceName) !== -1) {
          parent.emit('waitForResource');
        }
      });
    });

    done();
  },
  function (resourceName, done) {
    this.child.once('waitForResource', done);
    this.child.emit('waitForResource', resourceName);
  });
```
